"use client";

import { GuidedField } from "@/components/field-guidance";
import type { ContainerPhysicalProfile } from "@/features/items/container-physics";
import { emptyContainerSource } from "@/features/items/container-rules";

/** Shared by both catalog scopes, inside the existing container section. */
export function ContainerRuleFields({ profile: p, onChange }: { profile: ContainerPhysicalProfile; onChange: (profile: ContainerPhysicalProfile) => void }) {
  const patch = (change: Partial<ContainerPhysicalProfile>) => onChange({ ...p, ...change });
  const select = <K extends keyof ContainerPhysicalProfile>(key: K, label: string, choices: readonly string[], help: string) =>
    <GuidedField key={key} className="item-field" label={label} help={help}><select value={String(p[key])} onChange={event => patch({ [key]: event.target.value })}>{choices.map(value => <option key={value} value={value}>{value}</option>)}</select></GuidedField>;
  const number = (label: string, value: number | null, update: (value: number | null) => void, help: string) =>
    <GuidedField className="item-field" label={label} help={help}><input type="number" min={0} step="any" value={value ?? ""} onChange={event => update(event.target.value === "" ? null : Number(event.target.value))} /></GuidedField>;
  const source = p.source;
  return <>
    {select("closureMode", "Container closure", ["always-accessible", "open-close"], "Always-accessible containers need no opening. Open-close copies begin closed; each copy keeps its own open, closed, locked or sealed state. Locked and sealed require a G.O.D. ruling.")}
    {(["retrieve", "stow", "open", "close"] as const).map(operation => number(`${operation[0].toUpperCase()}${operation.slice(1)} Initiative`, p[`${operation}InitiativeCost`], value => patch({ [`${operation}InitiativeCost`]: value }), "Combat Initiative cost. Zero is valid; blank requires an explicit G.O.D. cost and reason. Retrieve and stow add the costs of every container in the accessed chain. Outside combat, handling is immediate."))}
    {select("weightCapacityMode", "Weight capacity mode", ["normal", "unlimited"], "Normal uses the authored contents weight limit. Unlimited explicitly removes only the internal weight limit; other restrictions still apply.")}
    {select("volumeCapacityMode", "Volume capacity mode", ["normal", "unlimited"], "Normal uses the authored internal volume limit. Unlimited removes only that limit. The container's external Item volume still counts inside its parent.")}
    {select("containedWeightBehavior", "Contained weight behavior", ["normal", "contents-weightless", "fixed"], "Normal adds contents weight to the empty container. Contents-weightless counts its own weight only. Fixed uses the explicit loaded weight below, including when empty.")}
    {p.containedWeightBehavior === "fixed" ? number("Fixed external weight (lb)", p.fixedLoadedWeightLb, fixedLoadedWeightLb => patch({ fixedLoadedWeightLb }), "Required for fixed behavior. This is the entire loaded container's external weight, not an adjustment to its base weight.") : null}
    {select("magicalContentRestriction", "Magical content restriction", ["any", "mundane-only", "magical-only"], "Checks each directly stored Item's Is Magical classification, alongside the physical restrictions. It does not infer magic from names.")}
    {select("timeBehavior", "Time inside", ["normal", "suspended", "slowed", "accelerated"], "Provides elapsed time to future timed systems. Suspension means zero elapsed time; it does not currently run preservation, aging or other timed mechanics.")}
    {p.timeBehavior === "slowed" || p.timeBehavior === "accelerated" ? number("Contained time multiplier", p.timeMultiplier, timeMultiplier => patch({ timeMultiplier }), "Effective elapsed time equals outside elapsed time multiplied by this number. Slowed: greater than 0 and less than 1. Accelerated: greater than 1. Applicable ancestor ratios multiply; suspension wins.") : null}
    {p.timeBehavior !== "normal" ? <>
      {select("timeAppliesTo", "Time applies to", ["all", "perishables", "living", "categories-types"], "Perishables uses the Food or Perishable category/record type, or an explicit trait supplied by a future timed system. Living is a future capability; Characters and Creatures cannot currently be stored.")}
      {p.timeAppliesTo === "categories-types" ? (["timeCategories", "timeRecordTypes"] as const).map(key => <GuidedField key={key} className="item-field" label={key === "timeCategories" ? "Time categories" : "Time record types"} help="Comma-separated category or record type names. A match in either list applies this time rule, including through nested containers."><input value={p[key].join(",")} onChange={event => patch({ [key]: event.target.value.split(",") })} /></GuidedField>) : null}
    </> : null}
    <GuidedField className="item-field" label="Living contents allowed" help="Authors a future containment capability. This does not place Characters or Creatures in Item inventory, or simulate breathing or other environmental effects."><input type="checkbox" checked={p.livingContentsAllowed} onChange={event => patch({ livingContentsAllowed: event.target.checked })} /></GuidedField>
    <GuidedField className="item-field" label="Bulk substance source" help="Stores a measured substance separately from discrete Items. Finite copies start empty; infinite copies provide their authored substance without a quantity counter."><input type="checkbox" checked={!!source} onChange={event => patch({ source: event.target.checked ? emptyContainerSource() : null })} /></GuidedField>
    {source ? <>
      <GuidedField className="item-field" label="Source mode" help="Finite quantities can be added and drawn, up to the authored maximum. Infinite supplies never decrement and require contents-weightless or fixed external weight."><select value={source.mode} onChange={event => patch({ source: { ...source, mode: event.target.value as "finite" | "infinite" } })}><option value="finite">Finite</option><option value="infinite">Infinite</option></select></GuidedField>
      {(["id", "name"] as const).map(key => <GuidedField key={key} className="item-field" label={key === "id" ? "Substance identity" : "Substance name"} help={key === "id" ? "A stable identity, such as water. Use the same identity across compatible source definitions; changing it does not replace existing stored substance." : "The visible substance name. Names do not define density, magic or other rules."}><input value={source.substance[key]} onChange={event => patch({ source: { ...source, substance: { ...source.substance, [key]: event.target.value } } })} /></GuidedField>)}
      <GuidedField className="item-field" label="Substance unit" help="Quantities use this unit. Different units cannot be mixed or automatically converted during filling."><select value={source.substance.unit} onChange={event => patch({ source: { ...source, substance: { ...source.substance, unit: event.target.value as "L" | "kg" | "lb", weightLbPerUnit: null, volumeLPerUnit: null } } })}>{["L", "kg", "lb"].map(unit => <option key={unit}>{unit}</option>)}</select></GuidedField>
      {source.mode === "finite" ? number("Maximum substance quantity", source.maxQuantity, maxQuantity => patch({ source: { ...source, maxQuantity } }), "A positive maximum in the selected substance unit. Finite weight and volume limits also apply.") : null}
      {source.mode === "finite" ? number("Substance weight per unit (lb)", source.substance.weightLbPerUnit, weightLbPerUnit => patch({ source: { ...source, substance: { ...source.substance, weightLbPerUnit } } }), "Physical weight in pounds of one quantity unit. Blank means unknown, never weightless. Only finite stored quantities need this measurement.") : null}
      {source.mode === "finite" ? number("Substance volume per unit (L)", source.substance.volumeLPerUnit, volumeLPerUnit => patch({ source: { ...source, substance: { ...source.substance, volumeLPerUnit } } }), "External liters occupied by one quantity unit. Blank means unknown. A finite volume limit requires this data when substance is added.") : null}
      <GuidedField className="item-field" label="Substance physical form" help="Liquid-only containers accept only substances authored as liquid."><select value={source.substance.physicalForm} onChange={event => patch({ source: { ...source, substance: { ...source.substance, physicalForm: event.target.value as "solid" | "liquid" } } })}><option value="liquid">Liquid</option><option value="solid">Solid</option></select></GuidedField>
      <GuidedField className="item-field" label="Substance is magical" help="This classification participates in the container's magical or mundane content restriction."><input type="checkbox" checked={source.substance.isMagical} onChange={event => patch({ source: { ...source, substance: { ...source.substance, isMagical: event.target.checked } } })} /></GuidedField>
      <GuidedField className="item-field" label="Lock substance" help="Finite containers accept only their authored substance when locked. Unlocked empty containers can select another owned source definition with the same unit. Infinite sources always draw their authored substance."><input type="checkbox" checked={source.locked} onChange={event => patch({ source: { ...source, locked: event.target.checked } })} /></GuidedField>
      <GuidedField className="item-field" label="Allow ordinary Items with source" help="Off by default. Enable only if this source container should also accept discrete inventory Items, subject to its other rules."><input type="checkbox" checked={source.allowsItems} onChange={event => patch({ source: { ...source, allowsItems: event.target.checked } })} /></GuidedField>
    </> : null}
  </>;
}
