"use client";

import type { ItemAuthoringReferences } from "./actions";
import {
  MODIFIER_ATTRIBUTE_KEYS,
  TEMPORARY_MODIFIER_CHANNELS,
  type MechanicalEffect,
} from "@/features/mechanical-effects";

export function MechanicalEffectEditor({
  effect,
  skills,
  onChange,
}: {
  effect: MechanicalEffect;
  skills: ItemAuthoringReferences["skills"];
  onChange: (effect: MechanicalEffect) => void;
}) {
  return <div className="item-form-grid">
    {effect.kind === "health.heal" ? <><label className="item-field"><span>Amount</span><input type="number" min={0} step="any" value={effect.amount} onChange={(event) => onChange({ ...effect, amount: Number(event.target.value) })} /></label><label className="item-field"><span>Scope</span><select value={effect.scope} onChange={(event) => onChange({ ...effect, scope: event.target.value as "full-body" | "area" })}><option value="full-body">Full Body</option><option value="area">Area</option></select></label></> : null}
    {effect.kind === "health.damage" ? <label className="item-field"><span>Amount</span><input type="number" min={0} step="any" value={effect.amount} onChange={(event) => onChange({ ...effect, amount: Number(event.target.value) })} /></label> : null}
    {effect.kind === "condition.apply" ? <><label className="item-field"><span>Condition Name</span><input value={effect.name} onChange={(event) => onChange({ ...effect, name: event.target.value })} /></label><label className="item-field"><span>Duration</span><select value={effect.duration.kind} onChange={(event) => { const kind = event.target.value as "until-removed" | "scene" | "combat-steps" | "combat-rounds"; onChange({ ...effect, duration: kind === "combat-steps" || kind === "combat-rounds" ? { kind, value: 1 } : { kind, value: null } }); }}><option value="until-removed">Until Removed</option><option value="scene">Scene</option><option value="combat-steps">Combat Steps</option><option value="combat-rounds">Combat Rounds</option></select></label>{effect.duration.kind === "combat-steps" || effect.duration.kind === "combat-rounds" ? <label className="item-field"><span>Duration Count</span><input type="number" min={1} step={1} value={effect.duration.value ?? 1} onChange={(event) => onChange({ ...effect, duration: { ...effect.duration, value: Number(event.target.value) } })} /></label> : null}<label className="item-field item-field--wide"><span>Description</span><textarea rows={3} value={effect.description} onChange={(event) => onChange({ ...effect, description: event.target.value })} /></label></> : null}
    {effect.kind === "modifier.apply" ? <><label className="item-field"><span>Label</span><input value={effect.label} onChange={(event) => onChange({ ...effect, label: event.target.value })} /></label><label className="item-field"><span>Channel</span><select value={effect.channel} onChange={(event) => { const channel = event.target.value as typeof effect.channel; const targetKey = channel === "attribute" ? "STR" : channel === "skill" ? `skill:${skills[0]?.id ?? ""}` : channel === "movement" ? "movement:Land" : "self"; onChange({ ...effect, channel, targetKey }); }}>{TEMPORARY_MODIFIER_CHANNELS.map((channel) => <option key={channel}>{channel}</option>)}</select></label>{effect.channel === "attribute" ? <label className="item-field"><span>Attribute</span><select value={effect.targetKey} onChange={(event) => onChange({ ...effect, targetKey: event.target.value })}>{MODIFIER_ATTRIBUTE_KEYS.map((key) => <option key={key}>{key}</option>)}</select></label> : null}{effect.channel === "skill" ? <label className="item-field"><span>Skill</span><select value={effect.targetKey} onChange={(event) => onChange({ ...effect, targetKey: event.target.value })}>{skills.map((skill) => <option key={skill.id} value={`skill:${skill.id}`}>{skill.name}</option>)}</select></label> : null}{effect.channel === "movement" ? <label className="item-field"><span>Movement Mode</span><input value={effect.targetKey.replace("movement:", "")} onChange={(event) => onChange({ ...effect, targetKey: `movement:${event.target.value}` })} /></label> : null}<label className="item-field"><span>Amount</span><input type="number" step={1} value={effect.amount} onChange={(event) => onChange({ ...effect, amount: Number(event.target.value) })} /></label><label className="item-field"><span>Duration</span><select value={effect.duration.kind} onChange={(event) => { const kind = event.target.value as "until-removed" | "scene" | "combat-steps" | "combat-rounds"; onChange({ ...effect, duration: kind === "combat-steps" || kind === "combat-rounds" ? { kind, value: 1 } : { kind, value: null } }); }}><option value="until-removed">Until Removed</option><option value="scene">Scene</option><option value="combat-steps">Combat Steps</option><option value="combat-rounds">Combat Rounds</option></select></label>{effect.duration.kind === "combat-steps" || effect.duration.kind === "combat-rounds" ? <label className="item-field"><span>Duration Count</span><input type="number" min={1} step={1} value={effect.duration.value ?? 1} onChange={(event) => onChange({ ...effect, duration: { ...effect.duration, value: Number(event.target.value) } })} /></label> : null}</> : null}
    {effect.kind === "manual" ? <><label className="item-field"><span>Title</span><input value={effect.title} onChange={(event) => onChange({ ...effect, title: event.target.value })} /></label><label className="item-field item-field--wide"><span>Description / Instructions</span><textarea rows={4} value={effect.description} onChange={(event) => onChange({ ...effect, description: event.target.value })} /></label></> : null}
  </div>;
}
