// Explain the existing implementation. Do not use help copy to introduce rules.
const common: Record<string, string> = {
  Name: "Enter the name people should see when choosing or referring to this record. Save to keep your changes.",
  Description: "Explain what this is and how people should picture it. Use the separate rule fields for things the game should calculate.",
  Notes: "Add any extra explanation people will need. Notes are for reading; they do not change the game's calculations.",
  Search: "Type part of a name to narrow the available records. Choose the intended result before adding a link.",
  "Variant Name": "Give the new copy a name. Clone as Variant copies the last saved version. After that, changing one does not change the other.",
  "Movement Mode": "Name the way movement happens, such as Land, Swim or Fly. Use a separate row for each mode.",
  "Base Movement": "Enter the starting movement value for this mode. This is the base used by the existing movement calculations; put special circumstances in Notes.",
  "Damage Type": "Enter the damage category, such as Slashing or Fire. Matching protection and Interaction Rules use this type; use consistent names.",
  Magical: "Choose Yes if this attack or Ability is magical, or No if it is not. Leave Unspecified if that has not been decided. Adding a Magic construction makes it magical.",
  "Distance Unit": "Enter the unit used by the numeric ranges, for example feet. Keep every range band in the same unit.",
  Reach: "Author the melee reach if the rule specifies one. Reach describes contact range; melee does not require a ranged-distance entry.",
  "Short Range": "Enter the boundary for the short range band in the selected Distance Unit. Use the source's authored range, not a guessed default.",
  "Medium Range": "Enter the boundary for the medium range band in the same unit as Short Range.",
  "Long Range": "Enter the boundary for the long range band in the same unit as the other bands.",
  "Maximum Uses": "Enter how many uses are available in the selected refresh period. Pair this with Refresh Scope and any necessary recharge explanation.",
  "Refresh Scope": "Choose when this use limit can reset, such as the supported encounter, scene, session or named event. This sets the limit's period, not a second cost.",
  "Refresh Key": "For a named refresh event, enter its exact identifier. Typing a new key does not create an automatic event; explain any manual reset in Recharge Notes.",
  "Resource Key": "Enter the exact name used by the game for the resource this cost spends. Only use a resource the game already supports; typing a new name does not create one.",
  "Cost Amount": "Enter the amount consumed for this cost. Initiative and other resources are separate costs; author the amount required by the rule.",
  "Cost Notes": "Explain any special rules for paying this cost. The game uses Resource and Cost Amount to work out what to spend.",
  "Recharge Notes": "Explain how uses are restored and any conditions the G.O.D. needs to check. Text does not create a new automatic reset event.",
};

const race: Record<string, string> = {
  Description: "Describe this Race in a few sentences: who they are, what makes them different, and what a player should know about them. Use the other fields for appearance, culture and game rules.",
  Size: "Choose how large members of this Race are, from Minuscule to Colossal. This choice does not automatically raise or lower a Character's Attributes.",
  "Base Magic": "The racial Mana multiplier: Skill Mana 5 × Base Magic 3 gives 15 Mana. A Character's permanent increases use the existing Quintessence advancement.",
  Attribute: "Use one of the six normal Attributes: STR, DEX, CON, INT, WIS or CHR. This row sets that Attribute's racial cap.",
  "Attribute Cap": "The highest score a Character of this Race can buy during Character Creation. For example, a cap of 40 means they cannot buy that Attribute above 40. It does not give them 40 points.",
  "Age Range Text": "Describe the Race's typical lifespan or life stages for readers. Minimum and Maximum Age hold the separate numeric bounds.",
  "Minimum Age": "Enter the youngest age listed for this Race. Leave it blank if the rule does not give a minimum. Explain life stages in Age Range Text.",
  "Maximum Age": "Enter the oldest age listed for this Race. Leave it blank if the rule does not give a maximum.",
  "Physical Characteristics": "List recognisable shared traits such as build, skin, senses or anatomy. Describe mechanics in the dedicated fields as well.",
  "Physical Description": "Write the fuller appearance description used to help players portray this Race. This is narrative information.",
  "Protection Name": "Give this natural protection a readable name, such as Scales or Shell. The name identifies the entry; Soak sets its reduction.",
  Soak: "How much damage the body naturally blocks. Soak 2 removes 2 damage from a hit to a protected area. Zero means it blocks none. This is the Race's only natural reduction value; worn armor is separate.",
  Coverage: "Choose All locations if this protects the whole body. Otherwise choose Selected locations and tick the protected areas. If two entries protect the same area, the G.O.D. must decide how they work together.",
  "Racial Quirk Name": "Give the Race's special Quirk a name. Write what it does in Success Effect and Failure Effect. The people playing apply those rules; the game does not apply them automatically.",
  "Success Effect": "Describe what the Quirk does on success. This text guides the table and does not automatically apply damage, conditions or modifiers.",
  "Failure Effect": "Describe what happens when the Quirk fails. Keep the rule readable; it remains narrative guidance.",
  Classification: "Filter the Skill picker by its existing classification. This only narrows the search; it does not change any Skill.",
  "Matching Skills": "Choose the Skill this Race should be linked to. Races can link to Tier 1 Skills or Special Abilities. You are choosing an existing Skill, not making a new one.",
  "Link Type": "Choose Skill for a normal Skill link. Granted is for a Special Ability granted by the Race. Select the actual Skill or Ability in Matching Skills first.",
  "Link Value": "Optional numeric value retained on this Race-to-Skill link. Enter a value only when the written rule calls for one; it is not an extra Attribute bonus.",
  "Common Languages Known": "List languages commonly associated with the Race. This narrative field does not purchase or allocate language Skills for a Character.",
  "Common Archetypes": "Describe typical roles or character concepts to inspire players. These examples do not restrict Character choices by themselves.",
  "Genre Examples": "Give recognisable examples that communicate the Race's tone or portrayal. These are references, not imported mechanics.",
  "Cultural Mindset": "Describe common beliefs and social expectations. Individual Characters can differ; this field does not enforce behavior.",
  "Outlook on Magic": "Describe cultural attitudes toward magic. Set the actual racial Mana multiplier in Base Magic.",
};

const creature: Record<string, string> = {
  "Canonical Name": "Enter the name used for this master Creature definition. Individual NPCs can have their own names.",
  Size: "Choose the Creature's size. Creature size participates in the existing Creature calculations shown in the preview; Race Size follows different rules.",
  Family: "Name the broad Creature family used to organise and filter the library. Family text does not by itself grant an immunity or attack.",
  "Creature Type": "Enter the Creature's category for identification and library filtering. Author specific combat interactions in Interaction Rules.",
  "Derived From": "The source Creature recorded for this variant. This is a reference to its origin; use the variant's own saved values.",
  "Typical Behavior": "Describe how this creature usually acts, hunts or responds. This guides the G.O.D.; it does not automate its decisions.",
  "Habitat & Ecology": "Describe where it lives and its ecological role. This is descriptive information for encounters and worldbuilding.",
  "HP Multiplier Steps": "Enter how many increases this Creature has. Each step adds 0.25 to its HP multiplier. The summary shows the resulting multiplier and Health Points (HP).",
  "Base Movement Steps": "Enter how many increases this Creature has. Each step adds 0.25 to its Base Movement. The summary shows the total.",
  "Base Magic Steps": "Enter how many increases this Creature has. Each step adds 0.25 to its Base Magic. Enter the number of steps here, not the final multiplier.",
  "Roll #": "Choose the hit-location digit, 0 through 9. This maps a location roll to the body area and HP pool in this row.",
  "Location Name": "Name the body area, such as Head or Chest, so the hit-location result is understandable.",
  "Body Parts": "Describe the body parts covered by this hit-location row. Use HP Pool to assign where injury is tracked.",
  "HP Pool": "Select the health pool used when this location takes damage. Several locations may refer to a shared authored pool.",
  "Natural Armor": "How much damage this Creature's body blocks at this location. Creatures currently use both Natural Armor and Natural Soak as separate reductions. Races use only Soak.",
  "Natural Soak": "Creature natural Soak is a reduction at this location, in addition to its current Natural Armor value. Worn equipment is tracked separately.",
  "Location Effect": "Describe a special consequence of hitting this location. Text alone does not create a automatic effect.",
  "Matching Skill": "Choose the specific Skill already in the library to add to this Creature's authored Skill list.",
  "Manual CR Adjustment": "Adjust the calculated Challenge Rating by the entered amount. Record why the change is appropriate in Adjustment Reason.",
  "Adjustment Reason": "Explain the manual Challenge Rating change so another author or G.O.D. can review it.",
  "Attack Name": "Name the attack people will choose in play, such as Bite or Claw. Give distinct attacks distinct names.",
  "Attack %": "Author this attack's percentile target. This is its attack chance, not its damage or Initiative cost.",
  "Attack Initiative": "Enter a value greater than zero for the attack's Initiative cost. Blank means not filled in yet. Zero belongs to Hold, not an actual attack.",
  Damage: "Enter the damage specified by the attack's rule. This is separate from its success percentage; unsupported expressions need a G.O.D. ruling at use.",
  "Attack Mode": "Choose melee, ranged, hybrid or the supported area mode to reveal the appropriate reach/range fields. A melee attack does not need ranged distance bands.",
  "Reach Unit": "If you author melee reach, state its unit, such as feet. This gives meaning to the Reach number.",
  "Ability Name": "Give this special Ability a name people will recognise. Use the other fields to say when it can be used and what it does.",
  "Ability Initiative": "When an Activated, Triggered or Reaction Ability has an Initiative cost entered, it must be greater than zero. Blank means unspecified. Passive Abilities have no activation Initiative.",
  "Threat / CR Impact": "Choose how much this Ability adds to the Creature's threat. This contributes to Challenge Rating (CR); it does not add damage to an attack.",
  "Resolution Mode": "Choose how to decide whether the Ability works: no roll, a percentile roll against a set target, or a decision by the G.O.D. Fill in the extra fields shown for your choice.",
  "Fixed Roll Target %": "Enter a percentile target from 1 through 100. Fixed Roll requires a value; zero or a blank target is not valid.",
  Origin: "Describe where the Ability comes from, using the listed origin when applicable. Origin is classification; it does not itself establish magical status.",
  "Targeting Notes": "Explain valid targets and selection requirements for the person using it. These notes do not create a new automatic targeting rule.",
  Resource: "Choose what using the Ability consumes. Initiative is authored in its own field; add rows for other required resources.",
  "Use Name": "Name a harvestable material or practical use, such as Hide. This records the Creature's Harvest & Utility information.",
  "Use Notes": "Explain how this material or use can be obtained or applied. Keep quantities, conditions and any G.O.D. rulings in the description.",
};

const interaction: Record<string, string> = {
  "Rule Name": "Give the interaction a readable name, such as Fire Resistance or Requires Silver. The separate rule fields determine what it does.",
  "Rule Type": "Requirement means the attack must meet a condition to work. Immunity blocks it. Resistance reduces damage. Vulnerability increases damage. Absorption turns the listed share of damage into healing.",
  Percentage: "Enter a percentage greater than zero. For example, 25% Resistance reduces matching damage by one quarter. Requirement and Immunity do not use percentages.",
  Match: "ANY requires at least one listed source condition to match. ALL requires every condition. These conditions describe the incoming source, not a Character's Use Conditions.",
  "Damage Type": "Match an incoming damage category, such as Fire. Use the same name as the attack or effect that supplies the damage.",
  Magical: "Match an explicitly magical or nonmagical incoming source. Creature identity alone does not establish this fact.",
  "Property Name": "Name the incoming Item property to match, such as Material. Select a known property when available.",
  "Property Value (optional)": "Enter a specific property value, such as Silver for Material. Blank accepts any value for the named property.",
  "Condition Name": "Match the exact name of a condition being applied by the incoming effect. This is not a test for a condition already on the target.",
  Requires: "Choose the kind of source fact needed to satisfy this Requirement. Use Match to say whether any or all listed conditions are necessary.",
  Against: "Choose the kind of incoming-source fact this rule matches. Use More matching options for additional supported matchers.",
  "Applies To": "Choose whether the rule covers damage or a non-damage incoming effect. Percentage-based rules operate on damage.",
  "Matching Type": "Choose which incoming-source fact this condition checks. Add another condition when the rule needs another fact.",
  "Source Kind": "Restrict matching to the listed source kind, such as Weapon, Spell or Creature Ability.",
  "Weapon Family": "Optionally restrict a Weapon source to its authored family. Leaving it blank does not add a family restriction.",
  "Related Creature (optional)": "Optionally match an explicit Item Property relationship to this Creature. A descriptive mention in an Item's name is not enough.",
  "Item Tag": "Choose the catalog tag the incoming Item must actually carry. Typing similar words in its description does not assign a tag.",
  "Mechanical Effect Kind": "Match the type of effect, such as damage or applying a condition. This is the incoming effect's operation, not its display name.",
  "Threat / CR Impact": "Record how dangerous you think this Interaction Rule makes the Creature. This field is saved for review; it does not currently change the calculated Challenge Rating.",
  "Rule Notes": "Explain the rule and any special cases. The game uses the matching fields above to check whether it applies. If it cannot tell, it asks the G.O.D. to decide.",
};

const item: Record<string, string> = {
  "Canonical ID": "The unique ID used to identify this Item in the library. Keep it when editing the same Item. Use Name to change what people see.",
  "Equipment Group": "Choose the equipment grouping used by the library. An Item needs the appropriate profile and owned equipment state before it can be used in play.",
  "Record Type": "Choose what this catalog record represents. Weapon, Ammunition, Armor and other types expose their corresponding editing tools.",
  Family: "Enter the broad Item family. Weapon-family matching may also use the authored weapon profile; a descriptive name is not a substitute for that profile.",
  Category: "Enter the catalog category used to organise this Item. Review the dedicated profile for actual mechanical behavior.",
  Subtype: "Optionally refine the catalog category with a subtype. Use a consistent term so related Items are easy to find.",
  Credits: "Enter the catalog price in Credits, using Price Basis to state what the price buys. A blank price is unspecified, not a free Item.",
  "Price Basis": "State what the price applies to, for example Each. Make quantity or package information clear before using the Item in a shop.",
  Weight: "Enter the Item's authored weight and choose the matching Weight Unit. This is distinct from the quantity owned.",
  "Weight Unit": "Choose the unit for Weight so the numeric amount is unambiguous.",
  Size: "Describe this Item's physical size. This field does not invoke Creature size calculations.",
  Durability: "Record the Item's authored durability. Do not use this field for armor Soak or the number of uses remaining.",
  "Variant Of": "Shows the source Item for this variant. A variant is a copy-on-create record; changing the source does not rewrite the variant.",
  "Property Name": "Name a Item property, such as Material. Interaction Rules can match these properties; text in Description alone is not a property.",
  Value: "Enter the value for the adjacent property or modifier. For example, Material can have the value Silver. Follow that property's rule for numeric values.",
  Unit: "State the unit associated with this property value when it needs one. Leave it blank for a value that is not a measurement.",
  Quantity: "Enter the number associated with this property or relationship, following its written rule. This does not grant copies to a Character.",
  Relation: "Choose whether this property refers to another Item or a Creature. Selecting a related record preserves an explicit relationship.",
  "Find Relation": "Search for the record that this property refers to, then select the exact matching result.",
  "Related Item": "Choose the actual catalog Item referenced by this property. A name written in Notes does not create the link.",
  "Related Creature": "Choose the actual Creature referenced by this property, for example a material or creature-specific relationship.",
  "Use Mode": "Choose how this Item is used. Complete the corresponding consumption or effect fields; a descriptive use note does not supply automatic behavior.",
  "Activation Label": "Enter the action name shown to the user, such as Drink or Activate. This label does not set the action's cost or effect.",
  "Quantity Consumed Per Use": "Enter how many owned copies a use consumes. This is Item quantity, not damage or a charge count.",
  "Legacy Maximum Charges": "Retained older charge information. Review the current shared-charge settings for Item powers the game can use; do not assume legacy text alone configures a power.",
  "Legacy Charges Per Use": "Retained older per-use charge information. Current powers use their own Resource Cost and Resource Amount settings.",
  "Legacy Recharge Rule / Notes": "Preserve the older recharge description here. Use the current charge/recharge controls for supported automatic behavior.",
  "Use Notes": "Explain how the Item is used at the table. Structured costs and effects determine automated execution.",
  Effect: "Choose the effect from the list to apply. Manual instructions are appropriate when a rule cannot be represented by a supported effect.",
  Amount: "Enter the amount for the selected effect or modifier. Check the effect type and target before choosing a value.",
  Application: "Choose whether damage applies to a location or uses the available area behavior. Localized effects need the corresponding location context in play.",
  "Condition Name": "Use the exact condition name to apply or remove. Matching names matter; a condition description does not create another automatic effect.",
  Duration: "Choose the supported duration boundary. If a count is requested, enter it in Duration Count.",
  "Duration Count": "Enter the number of units for the chosen duration. This is meaningful only for duration types that use a count.",
  Label: "Name this effect or modifier so its source and purpose are recognisable in play.",
  Channel: "Choose the kind of value this modifier changes, then choose its target. For example, a Skill modifier and a Soak modifier affect different calculations.",
  Attribute: "Select which normal Attribute this modifier targets. Its Amount is separate from the Character's purchased Attribute value.",
  Skill: "Select the specific Skill already in the library this effect targets. Similar names or tiers do not make two Skills the same record.",
  Title: "Give this passive contribution or instruction a short, recognisable title.",
  "Required Equipment State": "Choose when the passive effect applies: while Equipped, Worn or Wielded. Owning the Item in inventory alone does not satisfy these states.",
  "Passive Effect": "Choose the supported ongoing contribution. The equipment-state requirement determines when it is active.",
  Lifecycle: "Choose the supported condition for this passive contribution to remain active. Review the resulting state in the Character's active effects.",
  Instructions: "Write clear manual steps for the G.O.D. when the effect needs a ruling. Instructions are displayed, not interpreted as automatic actions.",
  "Authoring Scope": "Choose whether this governing Skill path applies to the weapon generally or to a specific firing mode.",
  "Search canonical Skills": "Find the specific Skill already in the library by name or identity. Select its full intended path before adding a weapon mapping.",
  "Exact endpoint Skill": "Select the final Skill in the governing path. The approved mapping uses this exact identity; a similar name or tier is not interchangeable.",
  "Authoring Notes": "Explain the intended weapon Skill mapping or exceptions for review. Notes do not approve a new Skill path by themselves.",
  "Profile Record Type": "Choose whether this profile describes a weapon or its ammunition. Ammunition can supply linked damage to a weapon.",
  "Weapon Type": "Choose a supported weapon family. It controls which weapon preparation and attack workflows apply.",
  Handedness: "Choose the supported handling requirement for this weapon. This describes how the weapon is held, not how many copies the Character owns.",
  "Damage Source": "Choose where the attack obtains its damage, such as the weapon itself or linked ammunition. Complete the chosen source's damage profile.",
  Damage: "Enter the damage expression authored for this weapon or ammunition. The selected Damage Source determines which profile the attack reads.",
  "Initiative Cost": "Enter the Initiative cost required by the action. This is separate from drawing, loading or recovering the weapon; blank means not configured.",
  "Range Mode": "Choose melee, ranged or hybrid as appropriate. Melee use does not require ranged-distance bands. Ranged use needs authored limits and a unit.",
  "Reload Type": "Single charges reload Initiative per inserted round or projectile. Magazine uses the cost for a complete magazine swap; magazine capacity belongs to its model.",
  "Capacity (Rounds)": "Enter the number of rounds held by this weapon or magazine model. Magazine-fed weapons use the attached magazine's capacity.",
  "Draw Initiative": "Enter the Initiative spent bringing an owned weapon into use. Zero explicitly means free; blank leaves the cost unconfigured.",
  "Ready Initiative": "Enter the preparation cost given by the rule. Zero explicitly means free; blank leaves this step unresolved.",
  "Load / Reload Initiative": "Enter the cost for the selected Reload Type: per insertion for Single or per complete swap for Magazine. Zero is an explicit free cost.",
  "Unload Initiative": "Enter the unloading cost given by the rule. Zero is an explicit free action; blank means the cost still needs configuration.",
  "Change Mode Initiative": "Enter the cost to switch firing modes. This is separate from the cycling and recoil-recovery cost of firing.",
  "Cycling Initiative Modifier": "An ammunition adjustment to the weapon mode's cycling cost. This is a modifier, not the base cycling cost.",
  "Recoil Reset Initiative Modifier": "An ammunition adjustment to the firing mode's recoil-recovery cost. Keep its sign as specified by the ammunition rule.",
  "Find Ammunition": "Search for an existing ammunition Item, then choose the exact result to link its profile.",
  "Ammunition Item": "Select the actual ammunition record this weapon uses. A name in Compatibility text does not create this link.",
  "Mode Name": "Name the firing mode as users should choose it, for example Single. Configure its timing and delivery fields in the same row.",
  "Cycling Initiative Cost": "Enter the base Initiative needed for this firing mode to cycle. Ammunition modifiers can adjust the final timing.",
  "Recoil Reset Initiative Cost": "Enter the base Initiative needed to recover from this mode's recoil. This is separate from cycling.",
  "Delivery Cadence": "Choose how this firing mode releases its rounds over time. Then set how many rounds are released each time in Rounds Per Cadence.",
  "Rounds Per Cadence": "Enter how many rounds are released together each time this mode fires. Use the number given by the weapon's rule.",
  "Rate of Fire": "Retain the descriptive rate-of-fire rule. The firing-mode settings provide the delivery and timing the game uses.",
  "Legacy Reload Initiative Text": "Retained descriptive reload information. Use the current numeric Load / Reload Initiative field for the timing the game uses.",
  Compatibility: "Describe compatibility restrictions. Also create the actual ammunition or magazine links needed by the preparation workflow.",
  "Weapon Rules": "Keep the complete tabletop weapon rule here. Supported separate rule fields drive execution; special cases may need a G.O.D. ruling.",
  "Armor Type": "Describe the armor category. Set its reduction in Base Soak and its protected areas in Coverage.",
  "Base Soak": "The damage reduction supplied by this worn armor before applicable damage-type modifiers. The owned copy must be Worn and cover the hit location.",
  Coverage: "Describe armor coverage and select the corresponding covered locations. Worn armor only protects the areas it actually covers.",
  "Damage Modifier Source": "Preserve the source explanation for damage-type modifiers. Author the supported modifier rows to make those adjustments automatic.",
  "Armor Rules": "Explain special armor rules for the table. Use Base Soak, coverage and modifier fields for supported automatic protection.",
  "When does it happen?": "Choose deliberate activation, a weapon hit, or the required passive equipment state. This changes which costs and effects are appropriate.",
  "Ability Name": "Name the Item Ability users will recognise and choose. Its trigger, costs and effects are separate fields.",
  "Power Name": "Name this Item power. Configure when it happens and what it does below.",
  "Resolution Mode": "Choose how the power resolves. A fixed roll needs its percentile target; supported no-roll effects do not need a success roll.",
  "Resource Cost": "Choose whether the power spends shared charges, consumes Item quantity, or has no resource cost. Initiative is configured separately.",
  "Resource Amount": "Enter how many charges or Item copies the chosen Resource Cost consumes per use.",
  "Fixed Roll Target": "Enter the power's positive percentile target given by its rule. This is the success target, not a roll result entered during play.",
  Magic: "Choose no construction, an existing Magic Skill, or a custom construction. A power must not have conflicting existing and custom primary constructions.",
  "Existing Magic": "Choose the specific Skill already in the library that supplies the Magic construction for this activated power.",
  "Fixed Item Power Level": "Select the fixed power level used for this Item's Magic. This is authored on the Item rather than inferred from its user's Skill purchases.",
  "Fixed Custom Magic Power Level": "Select the fixed power level used to calculate this custom Item Magic construction.",
  "Description / Authoring Notes": "Explain the power in plain language. The Magic construction and effects tell the game what to do.",
  "Fill Initiative per Round": "Enter how much Initiative loading one round into this magazine takes. This is separate from swapping a magazine into a weapon.",
};

const campaign: Record<string, string> = {
  "Campaign Name": "Enter the name players will see when choosing this campaign.",
  "Campaign Overview": "Describe the setting, premise and expectations. This is visible context, not an rule the game applies automatically.",
  "Attribute Points": "Set the starting Attribute purchase budget used by this campaign's Character Creation rules.",
  "Skill Points": "Set the starting Skill purchase budget. This is a pool to spend, not a grant to every Skill.",
  "Max Starting Points per Skill": "Set the campaign's starting purchase limit for one Skill. Other eligibility and path requirements still apply.",
  "Points to Unlock Next Tier": "Set the campaign's number of purchased points needed for the next Skill tier. Existing Skill identities and parent paths still apply.",
  "Max Points in Standard Skill": "Set the campaign's purchase ceiling for a Standard Skill. This does not set the calculated Skill Rank directly.",
  "Starting Credits": "Set the initial Credits budget provided by the campaign's creation rules. Item prices remain separate catalog values.",
  "Fate Method": "Choose the supported method for determining starting Fate. Assigned methods use Assigned Fate Points.",
  "Assigned Fate Points": "Enter the starting Fate amount when the selected Fate Method uses a fixed assignment.",
  "Currency System": "Choose the campaign's currency representation. Review denomination values when using a custom system; display names alone do not set exchange values.",
};

const character: Record<string, string> = {
  "Role / Label · Required": "Identify this NPC's role or label in the campaign, such as Guard Captain. This helps the G.O.D. find the individual.",
  Campaign: "The campaign whose creation settings and allowed Races, Skills and Items this Character uses.",
  "Race · Required": "Choose a permitted Race. Its Attribute caps, Base Magic, movement and current natural protection supply this Character's racial definition.",
  "Age · Required": "Enter this Character's age, using the selected Race's listed information as context.",
  "Sex · Required": "Describe the Character's sex as intended for the sheet. This identity field does not automatically adjust Attributes.",
  Feet: "Enter the feet component of the Character's height. Use Inches for the remaining part.",
  Inches: "Enter the inches component of height, alongside Feet.",
  "Weight · Required": "Enter the Character's body weight using the unit shown in the editor. Equipment weight is tracked separately.",
  "Skin Color · Required": "Describe the Character's skin, scales or other outer coloring for their appearance on the sheet.",
  "Eye Color · Required": "Describe the Character's eye color. This is appearance information, not a vision modifier.",
  "Hair Color · Required": "Describe hair or equivalent appearance; use an appropriate description if the Character has none.",
  "Deity · Required": "Record the Character's deity or chosen description of their beliefs. This text alone does not buy Faith Skills or grant powers.",
  "Defining Marks & Character Quirks · Required": "Describe recognisable marks, habits and personality quirks. Author any automatic Ability through the existing Ability system.",
  "Search permitted Items": "Search the Items allowed by this campaign. Select an exact result before adding the owned quantity.",
  "Current Credits": "The Character's currently recorded currency balance. Review purchases and awards before making a manual correction.",
};

const derived: Record<string, string> = {
  "Requirement Type": "Choose what must be true to acquire or retain the Ability, such as an Attribute, Skill, possession or manual requirement.",
  Attribute: "Select the Attribute tested by this requirement, then choose the comparison and required value.",
  Operator: "Choose how to compare the actual value with the authored requirement, for example Greater than or equal to.",
  Value: "Enter the threshold for the selected requirement. Its meaning comes from Requirement Type and Operator.",
  Skill: "Choose the Skill this Ability requires from the library. The game checks points bought in that exact Skill; another Skill with a similar name does not count.",
  "Required Skill #": "Enter required purchased points in the selected Skill. This checks stored points, not calculated Rank.",
  "Derived Ability": "Choose another existing Derived Ability required by this entry. This creates a reference rather than a copy.",
  Possession: "State whether the referenced requirement must be possessed or absent, according to the written rule.",
  "Requirement Text": "Explain the prerequisite in plain language. For a manual requirement, the G.O.D. must determine whether it is satisfied.",
  "Condition Type": "Choose the kind of fact checked when using the Ability. Supported events, equipment and states can be checked; a manual condition needs a ruling.",
  "Manual Condition": "Describe exactly what the G.O.D. must decide before use, such as only while standing in moonlight.",
  "Cost Type": "Choose the resource spent when the Ability is committed. Add separate rows for each resource required by the rule.",
  Amount: "Enter the amount spent for this cost. The selected Cost Type determines the resource and unit.",
  "Refresh Event Key": common["Refresh Key"],
  "Acquisition Type": "Choose the existing method for gaining this Ability. Review its requirements separately; selecting a type does not grant it to Characters.",
  "Activation Type": "Passive effects apply while their conditions are met. Activated actions are chosen deliberately. Triggered and Reaction abilities require an appropriate event or response window and a choice by the person using it.",
  "Rules Text": "Keep the full tabletop rule here. Supported automatic results are authored separately as Mechanical Effects; this text is the explanation.",
};

const skill: Record<string, string> = {
  "Name *": "Enter the Skill's readable name. Renaming a Skill preserves its identity and affects every link to that record.",
  Classification: "Choose the existing Skill classification. With no governing Attribute, the editor treats the record as a Special Ability.",
  Tier: "Author the Skill's tier number. Tier does not create its parent path; use Pathing for the exact parent relationship.",
  "Primary Attribute": "Choose the Skill's main governing Attribute. Leaving both Attributes unset makes this a Special Ability with no tier.",
  "Secondary Attribute": "Choose a second governing Attribute if the rule specifies one. Do not use this as a prerequisite or a parent Skill.",
  Definition: "Explain what the Skill lets a Character do and how the table uses it. Any attached Spell Construction is authored separately.",
  "Find an exact parent at any depth": "Search by name, identity, Attribute or classification. Choose the actual parent record; similar names and tier numbers do not establish a path.",
  "Matching Skill identity": "Select the exact Skill that should be a parent of this record. Review the resulting path preview before saving.",
  Relationship: "Use parent for an actual path relationship. Other retained relationship labels are separate references; changing this value can alter the Skill's proposed lineage.",
};

export const FIELD_HELP: Record<string, Record<string, string>> = { race, creature, interaction, item, campaign, character, derived, skill };
export function fieldHelp(scope: string, label: string): string | undefined {
  if (scope === "interaction" && /%\)?$/.test(label)) return interaction.Percentage;
  if (scope === "campaign") {
    if (label === "Points Needed to Unlock Next Tier") return campaign["Points to Unlock Next Tier"];
    if (label === "Max Points in a Standard Skill") return campaign["Max Points in Standard Skill"];
    if (label === "Starting Credit Amount") return campaign["Starting Credits"];
  }
  return FIELD_HELP[scope]?.[label] ?? common[label];
}
