ALTER TABLE "campaign_session_encounter_firearm_attack" DROP CONSTRAINT "campaign_session_encounter_firearm_attack_fire_state_valid";--> statement-breakpoint
DROP INDEX "campaign_session_encounter_effect_plan_declaration_uq";--> statement-breakpoint
DROP INDEX "campaign_session_encounter_effect_plan_pending_action_uq";--> statement-breakpoint
ALTER TABLE "campaign_session_encounter_effect_plan" ADD COLUMN "firearm_portion" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "campaign_session_encounter_firearm_attack" ADD COLUMN "firing_portions_resolved" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "campaign_session_encounter_firearm_attack" SET "firing_portions_resolved" = "firing_duration_initiative" WHERE "fired_at" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "campaign_session_encounter_effect_plan_declaration_uq" ON "campaign_session_encounter_effect_plan" USING btree ("declaration_id","firearm_portion");--> statement-breakpoint
CREATE UNIQUE INDEX "campaign_session_encounter_effect_plan_pending_action_uq" ON "campaign_session_encounter_effect_plan" USING btree ("pending_action_id","firearm_portion");--> statement-breakpoint
ALTER TABLE "campaign_session_encounter_effect_plan" ADD CONSTRAINT "campaign_session_encounter_effect_plan_portion_valid" CHECK ("campaign_session_encounter_effect_plan"."firearm_portion" >= 0);--> statement-breakpoint
ALTER TABLE "campaign_session_encounter_firearm_attack" ADD CONSTRAINT "campaign_session_encounter_firearm_attack_portions_valid" CHECK ("campaign_session_encounter_firearm_attack"."firing_portions_resolved" >= 0 AND "campaign_session_encounter_firearm_attack"."firing_portions_resolved" <= "campaign_session_encounter_firearm_attack"."firing_duration_initiative");--> statement-breakpoint
ALTER TABLE "campaign_session_encounter_firearm_attack" ADD CONSTRAINT "campaign_session_encounter_firearm_attack_fire_state_valid" CHECK (("campaign_session_encounter_firearm_attack"."fired_at" IS NULL AND "campaign_session_encounter_firearm_attack"."fired_by_user_id" IS NULL AND "campaign_session_encounter_firearm_attack"."attack_roll_id" IS NULL AND "campaign_session_encounter_firearm_attack"."rounds_consumed" = 0 AND "campaign_session_encounter_firearm_attack"."rounds_loaded_after" IS NULL) OR ("campaign_session_encounter_firearm_attack"."fired_at" IS NOT NULL AND "campaign_session_encounter_firearm_attack"."fired_by_user_id" IS NOT NULL AND "campaign_session_encounter_firearm_attack"."attack_roll_id" IS NOT NULL AND "campaign_session_encounter_firearm_attack"."rounds_consumed" > 0 AND "campaign_session_encounter_firearm_attack"."rounds_consumed" <= "campaign_session_encounter_firearm_attack"."rounds_declared" AND "campaign_session_encounter_firearm_attack"."rounds_loaded_after" = "campaign_session_encounter_firearm_attack"."rounds_loaded_before" - "campaign_session_encounter_firearm_attack"."rounds_consumed"));
