"use client";
import { useEffect, useRef, useState, type FormEvent, type PointerEvent as ReactPointerEvent } from "react";
import { ArrowLeft, Hand, MousePointer2, Move, Pencil, MapPin, Undo2, Redo2, Save } from "lucide-react";
import { GuidedField } from "@/components/field-guidance";
import { MAP_HEIGHT, MAP_WIDTH, acceptSavedHistory, boundedPoint, commitAction, draftOf, fitViewport, mapLabels, moveGeometry, redoAction, rounded, undoAction, validateGeometry, validateMapDraft, zoomViewport, type AtlasMap, type AtlasFeature, type EditingHistory, type GeographyRecord, type MapDraft, type Point, type Vertex } from "./atlas";
import styles from "./atlas.module.css";
type Tool="select"|"draw"|"edit"|"move"|"marker"|"pan";
type Loaded={map:AtlasMap;geographies:GeographyRecord[]};
const tools=[{id:"select",label:"Select",icon:MousePointer2},{id:"draw",label:"Draw landmass",icon:Pencil},{id:"edit",label:"Edit points",icon:Pencil},{id:"move",label:"Move feature",icon:Move},{id:"marker",label:"Place location",icon:MapPin},{id:"pan",label:"Pan",icon:Hand}] as const;
const help:Record<Tool,string>={select:"Tap a feature or choose it from the list. Selection never moves the map's shapes.",draw:"Tap the map to add boundary points, then close the outline. Use Undo to remove the last unfinished point.",edit:"Select a landmass, then drag a boundary point or use its coordinate controls. Add a point after the chosen vertex.",move:"Drag the selected feature, or move it with the direction buttons. Its geography identity stays the same.",marker:"Tap the map to place a named location. You can rename it in the information panel.",pan:"Drag to explore the map. Zoom and Fit map also change only your view."};

export function AtlasMapEditor({map,geographies,canEdit,onDirtyChange,onClose,onSave,onReload}:{map:AtlasMap;geographies:GeographyRecord[];canEdit:boolean;onDirtyChange:(dirty:boolean)=>void;onClose:()=>void;onSave:(body:{revision:number;draft:MapDraft})=>Promise<Loaded>;onReload:()=>Promise<Loaded>}) {
  const initial=draftOf(map,geographies),[history,setHistory]=useState<EditingHistory>({past:[],present:initial,future:[]}),historyRef=useRef(history),[saved,setSaved]=useState(JSON.stringify(initial)),[revision,setRevision]=useState(map.revision),[tool,setTool]=useState<Tool>("select"),[view,setView]=useState(fitViewport),[selectedId,setSelectedId]=useState<string|null>(null),[vertexId,setVertexId]=useState<string|null>(null),[drawing,setDrawing]=useState<Vertex[]>([]),[drawingFuture,setDrawingFuture]=useState<Vertex[]>([]),[newKind,setNewKind]=useState<"continent"|"island">("continent"),[existingId,setExistingId]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[comparison,setComparison]=useState<Loaded|null>(null),[pointSize,setPointSize]=useState(18),[formDirty,setFormDirty]=useState(false);
  const inspector=useRef<HTMLFieldSetElement>(null),pendingForms=useRef(new Set<HTMLFormElement>());
  function editFields(e:FormEvent<HTMLFormElement>){pendingForms.current.add(e.currentTarget);setFormDirty(true);}
  function applyFields(e:FormEvent<HTMLFormElement>){pendingForms.current.delete(e.currentTarget);setFormDirty(pendingForms.current.size>0);}
  function discardFields(){pendingForms.current.forEach(form=>form.reset());pendingForms.current.clear();setFormDirty(false);}
  const svg=useRef<SVGSVGElement>(null),gesture=useRef<{pointer:number;start:Point;base:EditingHistory;featureId?:string;vertexId?:string;view:ReturnType<typeof fitViewport>}|null>(null);
  const draft=history.present,selected=draft.features.find(f=>f.id===selectedId),geography=draft.geographies.find(g=>g.id===selected?.geographyId),selectedVertex=selected?.geometry.type==="polygon"?selected.geometry.points.find(p=>p.id===vertexId):undefined;
  const labels=mapLabels(draft.features.filter(f=>!f.archived),new Map(draft.geographies.map(g=>[g.id,g.name])),pointSize/22);
  const dirty=JSON.stringify(draft)!==saved||drawing.length>0||formDirty,dirtyRef=useRef(dirty);
  useEffect(()=>{dirtyRef.current=dirty;onDirtyChange(dirty);},[dirty,onDirtyChange]);
  useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue="";}};const click=(e:MouseEvent)=>{const link=(e.target as Element).closest?.("a[href]");if(link&&dirtyRef.current&&!window.confirm("Leave this map and discard its unsaved changes?")){e.preventDefault();e.stopPropagation();}};window.addEventListener("beforeunload",before);let returning=false;const back=(e:PopStateEvent)=>{if(returning){returning=false;return;}if(dirtyRef.current&&!window.confirm("Leave this map and discard unsaved changes?")){e.stopImmediatePropagation();returning=true;window.history.go(1);}};document.addEventListener("click",click,true);window.addEventListener("popstate",back,true);return()=>{window.removeEventListener("beforeunload",before);document.removeEventListener("click",click,true);window.removeEventListener("popstate",back,true);};},[]);
  useEffect(()=>{const node=svg.current;if(!node)return;const resize=()=>{const matrix=node.getScreenCTM();if(matrix)setPointSize(22/Math.max(Math.abs(matrix.a),.01));};const observer=new ResizeObserver(resize);observer.observe(node);resize();return()=>observer.disconnect();},[view]);
  function update(next:EditingHistory){historyRef.current=next;setHistory(next);}
  function commit(next:MapDraft){update(commitAction(historyRef.current,next));setNotice("");setError("");}
  function changeGeometry(id:string,geometry:AtlasFeature["geometry"]){commit({...historyRef.current.present,features:historyRef.current.present.features.map(f=>f.id===id?{...f,geometry}:f)});}
  function choose(next:Tool){if(next===tool)return;if(formDirty&&!window.confirm("Discard the unapplied information fields?"))return;setFormDirty(false);if(drawing.length&&next!=="draw"&&!window.confirm("Discard this unfinished outline?"))return;setDrawing([]);setDrawingFuture([]);setTool(next);setError("");setExistingId("");}
  function project(clientX:number,clientY:number):Point {const matrix=svg.current!.getScreenCTM();if(!matrix)throw new Error("The map view is unavailable.");const point=new DOMPoint(clientX,clientY).matrixTransform(matrix.inverse());return {x:point.x,y:point.y};}
  function addFeature(geometry:AtlasFeature["geometry"]) {
    try{validateGeometry(geometry);const kind=geometry.type==="point"?"location":newKind,current=historyRef.current.present,existing=geographies.find(g=>g.id===existingId),geoId=existing?.id??crypto.randomUUID(),id=crypto.randomUUID();
      if(existing&&(existing.archived||existing.kind!==kind))throw new Error("Choose an active geography of the matching kind.");
      const geo=current.geographies.find(g=>g.id===geoId)??(existing?{id:existing.id,name:existing.name,description:existing.description,kind:existing.kind,parentId:existing.parentId,revision:existing.revision}:{id:geoId,revision:null,name:`New ${kind}`,description:"",kind,parentId:null});
      const next={...current,features:[...current.features,{id,geographyId:geoId,geometry,archived:false}],geographies:current.geographies.some(g=>g.id===geoId)?current.geographies:[...current.geographies,geo]};validateMapDraft(next);commit(next);setSelectedId(id);setVertexId(null);setDrawing([]);setDrawingFuture([]);setTool("select");setNotice("Feature added to your draft. Name it in the information panel, then save the map.");
    }catch(failure){setError((failure as Error).message);}
  }
  function down(e:ReactPointerEvent<SVGSVGElement>){if(formDirty&&(tool==="edit"||tool==="move")){setError("Apply the information fields before moving a feature or point.");return;}if(!e.isPrimary||e.button!==0||pending||gesture.current)return;e.preventDefault();const point=project(e.clientX,e.clientY),target=e.target as Element,featureId=target.closest("[data-feature]")?.getAttribute("data-feature")??undefined,pointId=target.closest("[data-vertex]")?.getAttribute("data-vertex")??undefined;
    if(tool==="draw"&&canEdit){if(drawing.length>=256){setError("An outline supports at most 256 points.");return;}setDrawing([...drawing,{...boundedPoint(point),id:crypto.randomUUID()}]);setDrawingFuture([]);return;}
    if(tool==="marker"&&canEdit){addFeature({version:1,type:"point",point:boundedPoint(point)});return;}
    if(tool!=="pan"){if(formDirty&&featureId!==selectedId&&!window.confirm("Discard the unapplied information fields?"))return;if(featureId!==selectedId)discardFields();setSelectedId(featureId??null);setVertexId(pointId??null);}
    if(tool==="pan"||(canEdit&&featureId&&(tool==="move"||(tool==="edit"&&pointId)))){gesture.current={pointer:e.pointerId,start:point,base:historyRef.current,featureId,vertexId:pointId,view};e.currentTarget.setPointerCapture(e.pointerId);}
  }
  function moving(e:ReactPointerEvent<SVGSVGElement>){const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;const current=project(e.clientX,e.clientY),dx=current.x-g.start.x,dy=current.y-g.start.y;
    if(tool==="pan"){const matrix=svg.current!.getScreenCTM()!;const originalScreen=new DOMPoint(g.start.x,g.start.y).matrixTransform(matrix);setView({...g.view,x:view.x-(e.clientX-originalScreen.x)/matrix.a,y:view.y-(e.clientY-originalScreen.y)/matrix.d});return;}
    const f=g.base.present.features.find(f=>f.id===g.featureId);if(!f)return;let geometry=f.geometry;
    if(tool==="move")geometry=moveGeometry(f.geometry,dx,dy);else if(f.geometry.type==="polygon")geometry={...f.geometry,points:f.geometry.points.map(p=>p.id===g.vertexId?{...p,...boundedPoint(current)}:p)};
    update({...g.base,present:{...g.base.present,features:g.base.present.features.map(n=>n.id===f.id?{...n,geometry}:n)}});
  }
  function finish(e:ReactPointerEvent<SVGSVGElement>,cancel=false){const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;gesture.current=null;if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);if(tool==="pan")return;
    if(cancel){update(g.base);setNotice("The interrupted move was cancelled. Saved geometry is unchanged.");return;}
    const next=historyRef.current.present;try{validateMapDraft(next);update(commitAction(g.base,next));setError("");}catch(failure){update(g.base);setError(`${(failure as Error).message} That move was cancelled; the previous shape is retained.`);}
  }
  function nudge(dx:number,dy:number){if(!selected)return;const geometry=tool==="edit"&&selected.geometry.type==="polygon"&&vertexId?{...selected.geometry,points:selected.geometry.points.map(p=>p.id===vertexId?{...p,...boundedPoint({x:p.x+dx,y:p.y+dy})}:p)}:moveGeometry(selected.geometry,dx,dy);try{validateGeometry(geometry);changeGeometry(selected.id,geometry);}catch(failure){setError((failure as Error).message);}}
  function undo(){if(drawing.length){setDrawingFuture([drawing.at(-1)!,...drawingFuture]);setDrawing(drawing.slice(0,-1));}else update(undoAction(historyRef.current));}
  function redo(){if(drawingFuture.length){setDrawing([...drawing,drawingFuture[0]]);setDrawingFuture(drawingFuture.slice(1));}else update(redoAction(historyRef.current));}
  function download(){const blob=new Blob([JSON.stringify({format:"serrian-atlas-draft-v1",mapId:map.id,revision,draft:historyRef.current.present},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="serrian-atlas-draft.json";a.click();URL.revokeObjectURL(url);}
  function accept(loaded:Loaded,reset:boolean){const next=draftOf(loaded.map,loaded.geographies);update(reset?{past:[],present:next,future:[]}:acceptSavedHistory(historyRef.current,next));pendingForms.current.clear();setFormDirty(false);setSaved(JSON.stringify(next));setRevision(loaded.map.revision);setDrawing([]);setDrawingFuture([]);setComparison(null);setError("");if(reset){setSelectedId(null);setVertexId(null);}}
  return <section className={styles.workshop} aria-label="Map editor"><header className={styles.heading}><div><p className={styles.eyebrow}>{map.scope} chart · {map.archived?"Archived map":"Private World Atlas"}</p><h2>{draft.name}</h2><p role="status">{dirty?"Unsaved changes":notice||"All changes saved"}{!canEdit?" · Read-only":""}</p></div><div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={()=>{if(!dirty||window.confirm("Close this map and discard unsaved changes?"))onClose();}}><ArrowLeft size={17}/>Map library</button>{canEdit&&<button className="st-button" disabled={pending||!dirty||drawing.length>0||formDirty} onClick={async()=>{setPending(true);setError("");try{validateMapDraft(historyRef.current.present);const fresh=await onSave({revision,draft:historyRef.current.present});accept(fresh,false);setNotice("Map saved. Your features and geography identities are preserved.");}catch(failure){setError(failure instanceof Error?failure.message:"Save failed. Your draft is retained.");}finally{setPending(false);}}}><Save size={17}/>{pending?"Saving…":"Save map"}</button>}</div></header>
    <div className={styles.toolbar} role="toolbar" aria-label="Map tools">{tools.filter(t=>canEdit||t.id==="select"||t.id==="pan").map(t=><button key={t.id} type="button" className="st-button is-secondary" aria-pressed={tool===t.id} disabled={pending} onClick={()=>choose(t.id)}><t.icon size={17}/>{t.label}</button>)}{canEdit&&<><button className="st-button is-ghost" aria-label="Undo" disabled={pending||(formDirty||(!history.past.length&&!drawing.length))} onClick={undo}><Undo2 size={18}/>Undo</button><button className="st-button is-ghost" aria-label="Redo" disabled={pending||(formDirty||(!history.future.length&&!drawingFuture.length))} onClick={redo}><Redo2 size={18}/>Redo</button></>}</div>
    {formDirty&&<p role="status" className={styles.feedback}>Apply the information or point changes below before saving the map.</p>}
    <p className={styles.toolHelp}><strong>{tools.find(t=>t.id===tool)?.label}.</strong> {help[tool]}</p>
    {(tool==="draw"||tool==="marker")&&<div className={styles.drawingBar}>{tool==="draw"&&<GuidedField label="Landmass kind" help="Draw a continent or island. Both keep individually editable boundary points."><select className="st-control" value={newKind} disabled={drawing.length>0} onChange={e=>{setNewKind(e.target.value as typeof newKind);setExistingId("");}}><option value="continent">Continent</option><option value="island">Island</option></select></GuidedField>}<GuidedField label="Link geography" help="Create a new record, or draw another representation of an existing geography in this World."><select className="st-control" value={existingId} onChange={e=>setExistingId(e.target.value)}><option value="">Create new geography</option>{geographies.filter(g=>!g.archived&&g.kind===(tool==="marker"?"location":newKind)).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField>{tool==="draw"&&<><span>{drawing.length} outline points</span><button className="st-button" disabled={drawing.length<3} onClick={()=>addFeature({version:1,type:"polygon",points:drawing})}>Close outline</button><button className="st-button is-secondary" disabled={!drawing.length} onClick={()=>{if(window.confirm("Discard this unfinished outline?")){setDrawing([]);setDrawingFuture([]);}}}>Cancel outline</button></>}</div>}
    {error&&<div role="alert" className={styles.feedback}><p>{error}</p>{canEdit&&<div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={async()=>{try{setComparison(await onReload());}catch(failure){setError((failure as Error).message);}}}>Load saved map to compare</button><button className="st-button is-secondary" onClick={download}>Download draft</button></div>}</div>}
    {comparison&&<aside className={styles.comparison}><h3>Saved map · revision {comparison.map.revision}</h3><p>{comparison.map.name} · {comparison.map.features.filter(f=>!f.archived).length} active features. Your unsaved draft is still in the editor below.</p><svg viewBox="0 0 2000 1200" aria-label="Saved geometry comparison">{comparison.map.features.filter(f=>!f.archived).map(f=>f.geometry.type==="polygon"?<polygon key={f.id} points={f.geometry.points.map(p=>`${p.x},${p.y}`).join(" ")}/>:<circle key={f.id} cx={f.geometry.point.x} cy={f.geometry.point.y} r={12}/>)}</svg><div className={styles.actions}><button className="st-button is-secondary" onClick={download}>Download draft</button><button className="st-button" onClick={()=>{if(window.confirm("Replace your unsaved draft with this saved map? Download the draft first if you want to keep it."))accept(comparison,true);}}>Use saved map</button><button className="st-button is-secondary" onClick={()=>setComparison(null)}>Keep viewing draft</button></div></aside>}
    <div className={styles.editorGrid}><div className={styles.mapFrame}><div className={styles.navigation} aria-label="Map navigation"><button className="st-button is-secondary" aria-label="Zoom in" onClick={()=>setView(v=>zoomViewport(v,1.4))}>+</button><button className="st-button is-secondary" aria-label="Zoom out" onClick={()=>setView(v=>zoomViewport(v,1/1.4))}>−</button><button className="st-button is-secondary" onClick={()=>setView(fitViewport())}>Fit map</button><span>{Math.round(MAP_WIDTH/view.width*100)}%</span></div>
      <svg ref={svg} className={styles.canvas} viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} role="application" aria-label="Editable map canvas" tabIndex={0} data-tool={tool} onPointerDown={down} onPointerMove={moving} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)} onKeyDown={e=>{if(e.key==="Escape"){if(gesture.current){update(gesture.current.base);gesture.current=null;}setSelectedId(null);setVertexId(null);}if(e.key==="+"||e.key==="=")setView(v=>zoomViewport(v,1.4));if(e.key==="-")setView(v=>zoomViewport(v,1/1.4));if(e.key==="Home")setView(fitViewport());}}>
        <defs><pattern id={`atlas-grid-${map.id}`} width="100" height="100" patternUnits="userSpaceOnUse"><path d="M 100 0 L 0 0 0 100" className={styles.gridLine}/></pattern></defs><rect width={MAP_WIDTH} height={MAP_HEIGHT} className={styles.water}/><rect width={MAP_WIDTH} height={MAP_HEIGHT} fill={`url(#atlas-grid-${map.id})`} pointerEvents="none"/><rect width={MAP_WIDTH} height={MAP_HEIGHT} className={styles.mapBorder} pointerEvents="none"/>
        {draft.features.filter(f=>!f.archived).map(f=>{const g=draft.geographies.find(g=>g.id===f.geographyId),textPosition=labels.get(f.id)!,label=f.geometry.type==="point"?f.geometry.point:{x:f.geometry.points.reduce((n,p)=>n+p.x,0)/f.geometry.points.length,y:f.geometry.points.reduce((n,p)=>n+p.y,0)/f.geometry.points.length};return <g key={f.id} data-feature={f.id} data-selected={selectedId===f.id} className={styles.feature}>{f.geometry.type==="polygon"?<polygon points={f.geometry.points.map(p=>`${p.x},${p.y}`).join(" ")} className={styles.land}/>:<><circle cx={label.x} cy={label.y} r={pointSize} className={styles.hit}/><circle cx={label.x} cy={label.y} r={pointSize*.4} className={styles.marker}/></>}<title>{g?.name}</title><text x={textPosition.x} y={textPosition.y} textAnchor="middle" className={styles.mapLabel} fontSize={pointSize*.6}>{textPosition.text}</text></g>;})}
        {drawing.length>0&&<g className={styles.drawing} pointerEvents="none"><polyline points={drawing.map(p=>`${p.x},${p.y}`).join(" ")}/>{drawing.map(p=><circle key={p.id} cx={p.x} cy={p.y} r={pointSize*.3}/>)}</g>}
        {canEdit&&tool==="edit"&&selected&&!selected.archived&&selected.geometry.type==="polygon"&&selected.geometry.points.map((p,i)=><g key={p.id} data-feature={selected.id} data-vertex={p.id} data-point-index={i} className={styles.vertex} data-selected={vertexId===p.id}><circle cx={p.x} cy={p.y} r={pointSize} className={styles.hit}/><circle cx={p.x} cy={p.y} r={pointSize*.35}/></g>)}
        <text x={MAP_WIDTH-55} y={65} textAnchor="middle" className={styles.compass}>N</text><path d={`M ${MAP_WIDTH-55} 80 l -12 35 l 12 -8 l 12 8 Z`} className={styles.compassArrow}/>
      </svg><p className={styles.coordinateNote}>2000 × 1200 map units · coordinates stay fixed when you zoom or resize</p></div>
      <aside className={styles.inspector} aria-label="Geographic information"><fieldset disabled={pending} className={styles.inspectorFields} ref={inspector}><h3>{geography?.name??"Geographic information"}</h3>{selected&&geography?<><p>{geography.kind}{selected.archived?" · archived feature":""} · stable geography {geography.id.slice(0,8)}</p>
        {canEdit?<form key={`${selected.id}:${geography.name}:${geography.description}:${geography.parentId}`} onChange={editFields} onSubmit={e=>{e.preventDefault();applyFields(e);const fields=new FormData(e.currentTarget),next={...historyRef.current.present,geographies:historyRef.current.present.geographies.map(g=>g.id===geography.id?{...g,name:String(fields.get("name")).trim(),description:String(fields.get("description")),parentId:String(fields.get("parentId"))||null}:g)};commit(next);setNotice("Geography updated in your map draft. Save the map to persist it.");}}><GuidedField label="Feature name" help="Rename the shared geography record. Other maps linked to this place will use the same name."><input className="st-control" name="name" required maxLength={160} defaultValue={geography.name}/></GuidedField><GuidedField label="Geographic description" help="Describe this place's climate, terrain or history. Saving changes updates its stable World record."><textarea className="st-control" name="description" maxLength={12000} rows={3} defaultValue={geography.description}/></GuidedField><GuidedField label="Within geography" help="Optionally associate this place with a parent in this World. Circular relationships are refused."><select className="st-control" name="parentId" defaultValue={geography.parentId??""}><option value="">No parent</option>{[...geographies,...draft.geographies.filter(g=>!geographies.some(n=>n.id===g.id))].filter(g=>g.id!==geography.id&&(!("archived"in g)||!g.archived||g.id===geography.parentId)).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField><button className="st-button is-secondary">Apply geography changes</button></form>:<p>{geography.description||"No description recorded."}</p>}
        {canEdit&&!selected.archived&&tool==="edit"&&selected.geometry.type==="polygon"&&<div className={styles.pointPanel}><GuidedField label="Boundary point" help="Choose a point, then adjust its coordinates, insert a midpoint after it, or remove it. An outline needs at least three points."><select className="st-control" value={vertexId??""} onChange={e=>{if(formDirty&&!window.confirm("Discard the unapplied information fields?"))return;discardFields();setVertexId(e.target.value||null);}}><option value="">Choose a point</option>{selected.geometry.points.map((p,i)=><option key={p.id} value={p.id}>Point {i+1} · {p.x}, {p.y}</option>)}</select></GuidedField>{selectedVertex&&<form key={`${selectedVertex.id}:${selectedVertex.x}:${selectedVertex.y}`} onChange={editFields} onSubmit={e=>{e.preventDefault();applyFields(e);const f=new FormData(e.currentTarget);if(selected.geometry.type!=="polygon")return;const geometry={...selected.geometry,points:selected.geometry.points.map(p=>p.id===vertexId?{...p,x:Number(f.get("x")),y:Number(f.get("y"))}:p)};try{validateGeometry(geometry);changeGeometry(selected.id,geometry);}catch(failure){editFields(e);setError((failure as Error).message);}}}><div className={styles.coordinates}><GuidedField label="Point X" help="Horizontal map units from the left edge, between 0 and 2000."><input className="st-control" type="number" name="x" min={0} max={MAP_WIDTH} step=".01" required defaultValue={selectedVertex.x}/></GuidedField><GuidedField label="Point Y" help="Vertical map units from the top edge, between 0 and 1200."><input className="st-control" type="number" name="y" min={0} max={MAP_HEIGHT} step=".01" required defaultValue={selectedVertex.y}/></GuidedField></div><button className="st-button is-secondary">Apply point position</button></form>}{selectedVertex&&<div className={styles.actions}><button className="st-button is-secondary" disabled={formDirty} onClick={()=>{if(selected.geometry.type!=="polygon")return;const points=[...selected.geometry.points],index=points.findIndex(p=>p.id===vertexId),a=points[index],b=points[(index+1)%points.length],id=crypto.randomUUID();points.splice(index+1,0,{id,x:rounded((a.x+b.x)/2),y:rounded((a.y+b.y)/2)});const geometry={...selected.geometry,points};try{validateGeometry(geometry);changeGeometry(selected.id,geometry);setVertexId(id);}catch(failure){setError((failure as Error).message);}}}>Add point after</button><button className="st-button is-danger" disabled={formDirty||selected.geometry.points.length<=3} onClick={()=>{if(selected.geometry.type!=="polygon")return;const geometry={...selected.geometry,points:selected.geometry.points.filter(p=>p.id!==vertexId)};try{validateGeometry(geometry);changeGeometry(selected.id,geometry);setVertexId(null);}catch(failure){setError((failure as Error).message);}}}>Remove point</button></div>}</div>}
        {canEdit&&!selected.archived&&(tool==="move"||(tool==="edit"&&selectedVertex))&&<div className={styles.nudges}><p>Move {tool==="edit"?"this point":"this feature"} by 10 map units</p>{[["Left",-10,0],["Up",0,-10],["Down",0,10],["Right",10,0]].map(([label,x,y])=><button key={String(label)} className="st-button is-secondary" disabled={formDirty} onClick={()=>nudge(Number(x),Number(y))}>{label}</button>)}</div>}
        {canEdit&&<button className="st-button is-danger" disabled={formDirty} onClick={()=>{if(window.confirm(selected.archived?"Restore this feature to the map?":"Archive this feature? Its geography and boundary points will be retained, and you can undo or restore it."))commit({...draft,features:draft.features.map(f=>f.id===selected.id?{...f,archived:!f.archived}:f)});}}>{selected.archived?"Restore feature":"Archive feature"}</button>}
      </>:<p>Choose a landmass or location from the map or the list below. Its description and editing controls will appear here.</p>}
      <h4>Map features</h4><div className={styles.featureList}>{draft.features.map(f=><button key={f.id} className="st-button is-secondary" aria-pressed={selectedId===f.id} onClick={()=>{if(formDirty&&!window.confirm("Discard the unapplied information fields?"))return;discardFields();setSelectedId(f.id);setVertexId(null);}}>{draft.geographies.find(g=>g.id===f.geographyId)?.name}{f.archived?" · archived":""}</button>)}{!draft.features.length&&<p>No geography drawn yet.</p>}</div>
      {canEdit&&<details><summary>Map information</summary><form key={`${draft.name}:${draft.description}:${draft.scope}`} onChange={editFields} onSubmit={e=>{e.preventDefault();applyFields(e);const fields=new FormData(e.currentTarget);commit({...draft,name:String(fields.get("name")).trim(),description:String(fields.get("description")),scope:String(fields.get("scope")) as MapDraft["scope"]});}}><GuidedField label="Map title" help="Name this visual representation. Geography records keep their own names."><input className="st-control" required maxLength={160} name="name" defaultValue={draft.name}/></GuidedField><GuidedField label="Map description" help="Describe what this map covers and how you intend to use it."><textarea className="st-control" name="description" maxLength={12000} defaultValue={draft.description}/></GuidedField><GuidedField label="Map scope" help="A library label for world, continent, regional or local maps. It does not set physical distances."><select className="st-control" name="scope" defaultValue={draft.scope}>{["world","continent","regional","local"].map(s=><option key={s}>{s}</option>)}</select></GuidedField><button className="st-button is-secondary">Apply map information</button></form></details>}
      </fieldset></aside></div>
  </section>;
}
