"use client";
import { SettlementEditor } from "./settlement-editor";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AtlasExplorer, atlasUrl } from "./atlas-explorer";
import { AtlasConnections } from "./atlas-connections";
import { Map, Plus } from "lucide-react";
import { worldApi } from "./client-api";
import { type AtlasBundle, type AtlasMap } from "./atlas";
import { AtlasRecordEditor, type AtlasRecordTarget } from "./atlas-record-editor";
import { AtlasThumbnail } from "./atlas-thumbnail";
import { AtlasGenerator } from "./atlas-generator";
import { AtlasMapEditor } from "./atlas-map-editor";
import styles from "./atlas.module.css";

export function AtlasWorkspace({worldId,worldName,review,onDirtyChange}:{worldId:string;worldName:string;review:boolean;onDirtyChange:(dirty:boolean)=>void}) {
  const params=useSearchParams(),exploring=params.get("atlas");
  const [background,setBackground]=useState(false);
  const [connections,setConnections]=useState<{bundle:AtlasBundle;map:AtlasMap;changed:()=>Promise<void>}|null>(null),[editorGeneration,setEditorGeneration]=useState(0);
  const connectionDialog=connections&&<AtlasConnections onDirtyChange={onDirtyChange} worldId={worldId} bundle={connections.bundle} map={connections.map} onClose={()=>setConnections(null)} onChanged={connections.changed}/>;
  const api=`/api/worlds/${worldId}/atlas`,[bundle,setBundle]=useState<AtlasBundle|null>(null),[selected,setSelected]=useState<AtlasMap|null>(null),[recordEditor,setRecordEditor]=useState<AtlasRecordTarget|null>(null),[archived,setArchived]=useState(false),[error,setError]=useState(""),[pending,setPending]=useState(false),[generator,setGenerator]=useState<{source:AtlasMap|null}|null>(null);
  useEffect(()=>{if(exploring)return;let alive=true;worldApi<AtlasBundle>(`${api}${review?"?review=1":""}`).then(b=>{if(alive)setBundle(b);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[api,review,exploring]);
  async function loadMap(id:string){const fresh=await worldApi<AtlasBundle>(`${api}?map=${id}${review?"&review=1":""}`);setBundle(fresh);return fresh;}
  async function openMap(m:AtlasMap){setError("");try{const fresh=await loadMap(m.id);setBackground(false);setSelected(fresh?.maps.find(n=>n.id===m.id)??null);}catch(e){setError((e as Error).message);}}
  const MapEditor=selected?.mapKind==="settlement"&&!background?SettlementEditor:AtlasMapEditor;
  async function reload(){const fresh=await worldApi<AtlasBundle>(`${api}${review?"?review=1":""}`);setBundle(fresh);return fresh;}
  async function lifecycle(body:unknown,question:string){if(!window.confirm(question))return;setPending(true);setError("");try{await worldApi(api,"POST",body);await reload();}catch(failure){setError((failure as Error).message);}finally{setPending(false);}}
  async function duplicate(map:AtlasMap){setPending(true);setError("");try{const result=await worldApi<{id:string}>(api,"POST",{action:"duplicate",id:map.id,revision:map.revision,newId:crypto.randomUUID(),name:`${map.name.slice(0,145)} copy`});try{const fresh=map.mapKind==="settlement"?await loadMap(result.id):await reload();setBackground(false);setSelected(fresh.maps.find(m=>m.id===result.id)??null);}catch(failure){setError(`Copy saved successfully. ${(failure as Error).message} Reload Atlas to open it.`);}}catch(failure){setError((failure as Error).message);}finally{setPending(false);}}
  if(exploring)return <><AtlasExplorer worldId={worldId} worldName={worldName} review={review} onConnections={(b,m,changed)=>setConnections({bundle:b,map:m,changed})} onEdit={async map=>{const fresh=await loadMap(map.id);const target=fresh.maps.find(m=>m.id===map.id&&!m.archived);if(!target)throw new Error("This map is unavailable. Your exploration context is retained.");setBackground(false);setSelected(target);window.history.pushState(null,"",atlasUrl(null));}}/>{connectionDialog}</>;
  if(generator&&bundle)return <AtlasGenerator source={generator.source} onDirtyChange={onDirtyChange} onClose={()=>setGenerator(null)} onSave={async body=>{const result=await worldApi<{id:string}>(api,"POST",body);setGenerator(null);onDirtyChange(false);try{const fresh=await reload();setSelected(fresh.maps.find(m=>m.id===result.id)??null);}catch(failure){setError(`Map saved successfully. ${(failure as Error).message} Reload Atlas to open it.`);}}}/>;
  if(selected&&bundle)return <><MapEditor closeLabel={background?"Return to settlement":"Map library"} onBackground={()=>{setBackground(true);setEditorGeneration(n=>n+1);}} key={`${selected.id}:${editorGeneration}`} map={selected} geographies={bundle.geographies} canEdit={bundle.canEdit&&!selected.archived} onDirtyChange={onDirtyChange} onExplore={()=>{setBackground(false);setSelected(null);onDirtyChange(false);window.history.pushState({atlasTrail:[selected.id]},"",atlasUrl(selected.id));}} onConnections={()=>setConnections({bundle,map:selected,changed:async()=>{const fresh=await loadMap(selected.id);setSelected(fresh.maps.find(m=>m.id===selected.id)??null);setEditorGeneration(n=>n+1);}})} onClose={()=>{if(background){setBackground(false);setEditorGeneration(n=>n+1);}else {setSelected(null);void reload().catch(e=>setError(e.message));}onDirtyChange(false);}} onSave={async draft=>{await worldApi(api,"POST",{action:"save",id:selected.id,revision:draft.revision,draft:draft.draft});const fresh=await loadMap(selected.id);const map=fresh.maps.find(m=>m.id===selected.id);if(!map)throw new Error("The save succeeded, but this map could not be reloaded. Keep your draft and reload the saved map.");setSelected(map);return {map,geographies:fresh.geographies};}} onReload={async()=>{const fresh=await loadMap(selected.id);const map=fresh.maps.find(m=>m.id===selected.id);if(!map)throw new Error("This map is unavailable. Your draft is retained.");setSelected(map);return {map,geographies:fresh.geographies};}}/>{connectionDialog}</>;
  return <section className={styles.workspace} aria-label="World Atlas"><header className={styles.heading}><div><p className={styles.eyebrow}>Chart the unknown</p><h2>Atlas</h2><p>Draw the lands and mark the places that give your World its shape.</p></div>{bundle?.canEdit&&<div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={()=>setRecordEditor({kind:"map"})}><Plus size={18}/>New map</button><button className="st-button is-secondary" disabled={pending} onClick={()=>setRecordEditor({kind:"map",settlement:true})}>New settlement map</button><button className="st-button" disabled={pending} onClick={()=>setGenerator({source:null})}>Generate map</button></div>}</header>
    {error&&<div role="alert" className={styles.feedback}>{error}<button className="st-button is-secondary" onClick={()=>reload().then(()=>setError("")).catch(e=>setError(e.message))}>Reload Atlas</button></div>}
    {!bundle&&!error&&<p>Opening your map archive…</p>}
    {bundle&&<><label className={styles.archiveToggle}><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived records</label><div className={styles.library}>{bundle.maps.filter(m=>archived||!m.archived).map(m=><article key={m.id} className={styles.mapCard}><AtlasThumbnail map={m} geographies={bundle.geographies} worldId={worldId} review={review}/><div><p className={styles.eyebrow}>{m.mapKind==="settlement"?"settlement":m.scope} map{m.archived?" · archived":""}</p><h3>{m.name}</h3><p>{m.description||"A new chart waiting for its first coastline."}</p><small>{m.features.filter(f=>!f.archived).length+(m.drawings??[]).filter(d=>!d.archived).length} editable features</small></div><div className={styles.actions}><button className="st-button is-secondary" onClick={()=>void openMap(m)}>Open {m.name}</button>{!m.archived&&<button className="st-button" onClick={()=>window.history.pushState({atlasTrail:[m.id]},"",atlasUrl(m.id))}>Explore {m.name}</button>}{bundle.canEdit&&!m.archived&&<button className="st-button is-secondary" disabled={pending} onClick={()=>setConnections({bundle,map:m,changed:async()=>{await reload();}})}>Connect {m.name}</button>}{bundle.canEdit&&!m.archived&&<><button className="st-button is-secondary" disabled={pending} onClick={()=>duplicate(m)}>Duplicate {m.name}</button><button className="st-button is-secondary" disabled={pending} onClick={()=>setGenerator({source:m})}>Generate variation of {m.name}</button></>}{bundle.canEdit&&!m.archived&&m.mapKind!=="settlement"&&<button className="st-button is-secondary" onClick={()=>setRecordEditor({kind:"map",settlement:true,adopt:{id:m.id,revision:m.revision}})}>Adopt {m.name} as settlement</button>}{bundle.canEdit&&<button className="st-button is-ghost" disabled={pending} onClick={()=>lifecycle({action:m.archived?"restore-map":"archive-map",id:m.id,revision:m.revision},m.archived?"Restore this map?":"Archive this map? All geography and saved shapes will be kept.")}>{m.archived?"Restore map":"Archive map"}</button>}</div></article>)}</div>
      {!bundle.maps.some(m=>archived||!m.archived)&&<div className={styles.empty}><Map size={48}/><h3>A World waiting to be charted</h3><p>Begin with a blank map, or generate an editable starting landscape. Give the land a name and return later to reshape it.</p></div>}
      <section className={styles.geographyLibrary}><div className={styles.heading}><div><p className={styles.eyebrow}>Places beyond the drawing</p><h3>Geography records</h3><p>Continents, islands, regions and named locations keep their identities across maps.</p></div>{bundle.canEdit&&<button className="st-button is-secondary" onClick={()=>setRecordEditor({kind:"geography"})}>New geography</button>}</div>{!bundle.geographies.length&&<p>Drawing a new feature creates its geography record. You can also name places here before mapping them.</p>}<div className={styles.geographyGrid}>{bundle.geographies.filter(g=>archived||!g.archived).map(g=><article key={g.id}><small>{g.kind}{g.archived?" · archived":""}</small><h4>{g.name}</h4><p>{g.description}</p>{g.parentId&&<p>Within {bundle.geographies.find(p=>p.id===g.parentId)?.name}</p>}{bundle.canEdit&&<div className={styles.actions}>{!g.archived&&<button className="st-button is-secondary" onClick={()=>setRecordEditor({kind:"geography",record:g})}>Edit {g.name}</button>}<button className="st-button is-ghost" disabled={pending} onClick={()=>lifecycle({action:g.archived?"restore-geography":"archive-geography",id:g.id,revision:g.revision},g.archived?"Restore this geography?":"Archive this geography? Linked records must be retained.")}>{g.archived?"Restore geography":"Archive geography"}</button></div>}</article>)}</div></section>
    </>}
    {connectionDialog}
    {recordEditor&&bundle&&<AtlasRecordEditor target={recordEditor} geographies={bundle.geographies} onClose={()=>setRecordEditor(null)} onSave={async body=>{const result=await worldApi<{id:string}>(api,"POST",body);setRecordEditor(null);try{const fresh=recordEditor.kind==="map"?await loadMap(result.id):await reload();setBackground(false);if(recordEditor.kind==="map")setSelected(fresh.maps.find(m=>m.id===result.id)??null);}catch(failure){setError(`Saved successfully. ${(failure as Error).message} Reload the Atlas to see the saved record.`);}}}/>}
  </section>;
}
