"use client";
import { useEffect, useState } from "react";
import { Map, Plus } from "lucide-react";
import { worldApi } from "./client-api";
import type { AtlasBundle, AtlasMap } from "./atlas";
import { AtlasRecordEditor, type AtlasRecordTarget } from "./atlas-record-editor";
import { AtlasMapEditor } from "./atlas-map-editor";
import styles from "./atlas.module.css";

export function AtlasWorkspace({worldId,review,onDirtyChange}:{worldId:string;review:boolean;onDirtyChange:(dirty:boolean)=>void}) {
  const api=`/api/worlds/${worldId}/atlas`,[bundle,setBundle]=useState<AtlasBundle|null>(null),[selected,setSelected]=useState<AtlasMap|null>(null),[recordEditor,setRecordEditor]=useState<AtlasRecordTarget|null>(null),[archived,setArchived]=useState(false),[error,setError]=useState(""),[pending,setPending]=useState(false);
  useEffect(()=>{let alive=true;worldApi<AtlasBundle>(`${api}${review?"?review=1":""}`).then(b=>{if(alive)setBundle(b);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[api,review]);
  async function reload(){const fresh=await worldApi<AtlasBundle>(`${api}${review?"?review=1":""}`);setBundle(fresh);return fresh;}
  async function lifecycle(body:unknown,question:string){if(!window.confirm(question))return;setPending(true);setError("");try{await worldApi(api,"POST",body);await reload();}catch(failure){setError((failure as Error).message);}finally{setPending(false);}}
  if(selected&&bundle)return <AtlasMapEditor key={selected.id} map={selected} geographies={bundle.geographies} canEdit={bundle.canEdit&&!selected.archived} onDirtyChange={onDirtyChange} onClose={()=>{setSelected(null);onDirtyChange(false);}} onSave={async draft=>{await worldApi(api,"POST",{action:"save",id:selected.id,revision:draft.revision,draft:draft.draft});const fresh=await reload();const map=fresh.maps.find(m=>m.id===selected.id);if(!map)throw new Error("The save succeeded, but this map could not be reloaded. Keep your draft and reload the saved map.");setSelected(map);return {map,geographies:fresh.geographies};}} onReload={async()=>{const fresh=await reload();const map=fresh.maps.find(m=>m.id===selected.id);if(!map)throw new Error("This map is unavailable. Your draft is retained.");setSelected(map);return {map,geographies:fresh.geographies};}}/>;
  return <section className={styles.workspace} aria-label="World Atlas"><header className={styles.heading}><div><p className={styles.eyebrow}>Chart the unknown</p><h2>Atlas</h2><p>Draw the lands and mark the places that give your World its shape.</p></div>{bundle?.canEdit&&<button className="st-button" onClick={()=>setRecordEditor({kind:"map"})}><Plus size={18}/>New map</button>}</header>
    {error&&<div role="alert" className={styles.feedback}>{error}<button className="st-button is-secondary" onClick={()=>reload().then(()=>setError("")).catch(e=>setError(e.message))}>Reload Atlas</button></div>}
    {!bundle&&!error&&<p>Opening your map archive…</p>}
    {bundle&&<><label className={styles.archiveToggle}><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived records</label><div className={styles.library}>{bundle.maps.filter(m=>archived||!m.archived).map(m=><article key={m.id} className={styles.mapCard}><div className={styles.thumbnail} aria-hidden="true"><svg className={styles.preview} viewBox="0 0 2000 1200">{m.features.filter(f=>!f.archived).map(f=>f.geometry.type==="polygon"?<polygon key={f.id} points={f.geometry.points.map(p=>`${p.x},${p.y}`).join(" ")}/>:<circle key={f.id} cx={f.geometry.point.x} cy={f.geometry.point.y} r={20}/>)}</svg>{!m.features.some(f=>!f.archived)&&<Map size={42}/>}</div><div><p className={styles.eyebrow}>{m.scope} map{m.archived?" · archived":""}</p><h3>{m.name}</h3><p>{m.description||"A new chart waiting for its first coastline."}</p><small>{m.features.filter(f=>!f.archived).length} editable features</small></div><div className={styles.actions}><button className="st-button is-secondary" onClick={()=>setSelected(m)}>Open {m.name}</button>{bundle.canEdit&&<button className="st-button is-ghost" disabled={pending} onClick={()=>lifecycle({action:m.archived?"restore-map":"archive-map",id:m.id,revision:m.revision},m.archived?"Restore this map?":"Archive this map? All geography and saved shapes will be kept.")}>{m.archived?"Restore map":"Archive map"}</button>}</div></article>)}</div>
      {!bundle.maps.some(m=>archived||!m.archived)&&<div className={styles.empty}><Map size={48}/><h3>A World waiting to be charted</h3><p>Begin with a blank map. Draw a coastline point by point, give the land a name, and return later to reshape it.</p></div>}
      <section className={styles.geographyLibrary}><div className={styles.heading}><div><p className={styles.eyebrow}>Places beyond the drawing</p><h3>Geography records</h3><p>Continents, islands and locations keep their identities across maps.</p></div>{bundle.canEdit&&<button className="st-button is-secondary" onClick={()=>setRecordEditor({kind:"geography"})}>New geography</button>}</div>{!bundle.geographies.length&&<p>Drawing a new feature creates its geography record. You can also name places here before mapping them.</p>}<div className={styles.geographyGrid}>{bundle.geographies.filter(g=>archived||!g.archived).map(g=><article key={g.id}><small>{g.kind}{g.archived?" · archived":""}</small><h4>{g.name}</h4><p>{g.description}</p>{g.parentId&&<p>Within {bundle.geographies.find(p=>p.id===g.parentId)?.name}</p>}{bundle.canEdit&&<div className={styles.actions}>{!g.archived&&<button className="st-button is-secondary" onClick={()=>setRecordEditor({kind:"geography",record:g})}>Edit {g.name}</button>}<button className="st-button is-ghost" disabled={pending} onClick={()=>lifecycle({action:g.archived?"restore-geography":"archive-geography",id:g.id,revision:g.revision},g.archived?"Restore this geography?":"Archive this geography? Linked records must be retained.")}>{g.archived?"Restore geography":"Archive geography"}</button></div>}</article>)}</div></section>
    </>}
    {recordEditor&&bundle&&<AtlasRecordEditor target={recordEditor} geographies={bundle.geographies} onClose={()=>setRecordEditor(null)} onSave={async body=>{const result=await worldApi<{id:string}>(api,"POST",body);setRecordEditor(null);try{const fresh=await reload();if(recordEditor.kind==="map")setSelected(fresh.maps.find(m=>m.id===result.id)??null);}catch(failure){setError(`Saved successfully. ${(failure as Error).message} Reload the Atlas to see the saved record.`);}}}/>}
  </section>;
}
