"use client";
import { useEffect, useLayoutEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, Compass, Minus, Plus } from "lucide-react";
import { DungeonLevelNavigation } from "./dungeon-levels";
import { InteriorFloorNavigation } from "./interior-floors";
import { worldApi } from "./client-api";
import { draftOf, fitViewport, zoomViewport, type AtlasBundle, type AtlasMap, type Viewport } from "./atlas";
import { geographyPath, geographyType, navigationIndex, representedPlaces, visitMap } from "./atlas-navigation";
import { CartographyScene } from "./cartography-scene";
import styles from "./atlas.module.css";

export function atlasUrl(mapId:string|null,placeId?:string|null){const url=new URL(window.location.href);if(mapId)url.searchParams.set("atlas",mapId);else {url.searchParams.delete("atlas");url.searchParams.delete("ordinary");}url.searchParams.delete("place");if(placeId)url.searchParams.set("place",placeId);return `${url.pathname}${url.search}${url.hash}`;}
export function AtlasExplorer({worldId,worldName,review,onEdit,onConnections,onCreateInterior}:{worldId:string;worldName:string;review:boolean;onEdit:(map:AtlasMap)=>Promise<void>;onCreateInterior?:(bundle:AtlasBundle,buildingId:string)=>void;onConnections:(bundle:AtlasBundle,map:AtlasMap,onChanged:()=>Promise<void>)=>void}) {
  const params=useSearchParams(),requested=params.get("atlas")!,placeId=params.get("place"),ordinary=params.get("ordinary")==="1";
  const [bundle,setBundle]=useState<AtlasBundle|null>(null),[shown,setShown]=useState<string|null>(null),[pendingRead,setLoading]=useState(true),[error,setError]=useState(""),[retry,setRetry]=useState(0),[view,setView]=useState(fitViewport),[motion,setMotion]=useState(false),[units,setUnits]=useState(2);
  const remembered=useRef(new Map<string,Viewport>()),svg=useRef<SVGSVGElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),gesture=useRef<{id:number;x:number;y:number;view:Viewport;place:string|null;dragged:boolean}|null>(null),frame=useRef<number|null>(null),nextView=useRef<Viewport|null>(null);
  const loading=pendingRead||(!error&&requested!==shown);
  const map=bundle?.maps.find(m=>m.id===shown),index=useMemo(()=>bundle?navigationIndex(bundle):null,[bundle]);
  const draft=useMemo(()=>map&&bundle?draftOf(map,bundle.geographies):null,[map,bundle]);
  const places=useMemo(()=>map&&bundle?representedPlaces(map,bundle):new Set<string>(),[map,bundle]);
  const selected=index?.places.get(placeId??map?.geographyId??""),selectedId=map?.features.find(f=>!f.archived&&f.geographyId===selected?.id)?.id??map?.drawings?.find(d=>!d.archived&&d.geographyId===selected?.id)?.id??map?.settlementShapes?.find(s=>!s.archived&&s.geographyId===selected?.id)?.id??map?.dungeonShapes?.find(s=>!s.archived&&s.entityId===selected?.id)?.id??map?.interiorShapes?.find(s=>!s.archived&&s.entityId===selected?.id)?.id;
  useEffect(()=>{let alive=true;worldApi<AtlasBundle>(`/api/worlds/${worldId}/atlas?map=${encodeURIComponent(requested)}${review?"&review=1":""}${ordinary?"&ordinary=1":""}`).then(b=>{if(!alive)return;setBundle(b);setShown(requested);setView(remembered.current.get(requested)??fitViewport());setError("");setLoading(false);}).catch(e=>{if(alive){setError(e.message);setLoading(false);}});return()=>{alive=false;};},[requested,worldId,review,retry,ordinary]);
  useEffect(()=>{if(shown)remembered.current.set(shown,view);},[shown,view]);
  useLayoutEffect(()=>{const node=svg.current;if(!node)return;const resize=()=>{if(node.clientWidth&&node.clientHeight)setUnits(Math.max(view.width/node.clientWidth,view.height/node.clientHeight));};const observer=new ResizeObserver(resize);observer.observe(node);resize();return()=>observer.disconnect();},[view,map]);
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(frame.current!==null)cancelAnimationFrame(frame.current);},[]);
  async function refresh(){const fresh=await worldApi<AtlasBundle>(`/api/worlds/${worldId}/atlas?map=${shown}${review?"&review=1":""}${ordinary?"&ordinary=1":""}`);setBundle(fresh);}
  function navigate(id:string,arrival?:string|null){if(id===shown){select(arrival??null);return;}setLoading(true);setError("");const old=window.history.state?.atlasTrail,trail=Array.isArray(old)?old.filter((id:unknown)=>typeof id==="string"):shown?[shown]:[];window.history.pushState({atlasTrail:visitMap(trail,id)},"",atlasUrl(id,arrival));}
  function select(id:string|null){window.history.replaceState({atlasTrail:window.history.state?.atlasTrail??[]},"",atlasUrl(shown,id??"world"));}
  function move(next:Viewport){setMotion(true);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setMotion(false),350);setView(next);}
  function close(){window.history.pushState(null,"",atlasUrl(null));}
  function down(e:PointerEvent<SVGSVGElement>){if(!e.isPrimary||e.button!==0||loading)return;e.preventDefault();const target=e.target as Element,fid=target.closest("[data-feature]")?.getAttribute("data-feature"),did=target.closest("[data-drawing]")?.getAttribute("data-drawing"),place=target.closest("[data-entity]")?.getAttribute("data-entity")??target.closest("[data-geography]")?.getAttribute("data-geography")??map?.features.find(f=>f.id===fid)?.geographyId??map?.drawings?.find(d=>d.id===did)?.geographyId??null;gesture.current={id:e.pointerId,x:e.clientX,y:e.clientY,view,place,dragged:false};e.currentTarget.setPointerCapture(e.pointerId);}
  function drag(e:PointerEvent<SVGSVGElement>){const g=gesture.current;if(!g||g.id!==e.pointerId)return;const rect=e.currentTarget.getBoundingClientRect(),dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.hypot(dx,dy)<6&&!g.dragged)return;g.dragged=true;const matrix=e.currentTarget.getScreenCTM(),scale=matrix?1/Math.max(Math.abs(matrix.a),.001):g.view.width/rect.width;nextView.current={...g.view,x:g.view.x-dx*scale,y:g.view.y-dy*scale};if(frame.current===null)frame.current=requestAnimationFrame(()=>{frame.current=null;if(nextView.current)move(nextView.current);nextView.current=null;});}
  function finish(e:PointerEvent<SVGSVGElement>,cancel=false){const g=gesture.current;if(!g||g.id!==e.pointerId)return;if(frame.current!==null){cancelAnimationFrame(frame.current);frame.current=null;}if(nextView.current)move(nextView.current);nextView.current=null;gesture.current=null;if(!g.dragged&&!cancel&&g.place)select(g.place);}
  const choices=(id:string)=>{const associated=index?.destinations.get(id)??[],preferred=index?.maps.get(index.preferred.get(`${shown}:${id}`)??"");return [...associated,...(preferred&&!preferred.archived&&!preferred.unavailable&&!associated.some(m=>m.id===preferred.id)?[preferred]:[])].filter(m=>m.id!==shown);};
  const mapLinks=(id:string)=>{const preferred=index?.preferred.get(`${shown}:${id}`);return <div className={styles.actions}>{choices(id).map(m=><button className="st-button is-secondary" key={m.id} disabled={loading} onClick={()=>navigate(m.id,bundle?.connections?.find(c=>c.sourceMapId===shown&&c.geographyId===id&&c.destinationMapId===m.id)?.destinationGeographyId)}>Open {m.name}{preferred===m.id?" · preferred":""}</button>)}</div>;};
  const previous=typeof window!=="undefined"&&Array.isArray(window.history.state?.atlasTrail)?(window.history.state.atlasTrail as string[]).slice(0,-1).at(-1):null;
  return <section className={styles.workshop} aria-label="Map explorer"><header className={styles.heading}><div><p className={styles.eyebrow}><Compass size={16}/> Explore the Atlas</p><h2>{map?.name??"Opening map"}</h2><p>Discover places and follow their maps. Drag to pan; select a place to read its story.</p></div><div className={styles.actions}><button className="st-button is-secondary" onClick={close}><ArrowLeft size={17}/>Map library</button>{previous&&index?.maps.get(previous)&&<button className="st-button is-secondary" disabled={loading} onClick={()=>navigate(previous)}>Previous map</button>}{map&&bundle?.canEdit&&<><button className="st-button" disabled={loading} onClick={()=>{setLoading(true);onEdit(map).catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>Edit map</button><button className="st-button is-secondary" disabled={loading} onClick={()=>onConnections(bundle,map,refresh)}>Edit connections</button></>}</div></header>
    {error&&<div role="alert" className={styles.feedback}><p>{error} {map?"Your previous map and view are retained.":"Choose an available map from the library."}</p><div className={styles.actions}><button className="st-button is-secondary" onClick={()=>{setLoading(true);setRetry(n=>n+1);}}>Retry map</button>{map&&requested!==shown&&<button className="st-button is-secondary" onClick={()=>window.history.replaceState({atlasTrail:window.history.state?.atlasTrail??[]},"",atlasUrl(shown))}>Return to displayed map</button>}</div></div>}
    {loading&&<p role="status">Opening geographic chart…</p>}
    {map&&draft&&bundle&&index&&<><nav aria-label="Geographic breadcrumbs" className={styles.breadcrumbs}><button onClick={()=>select(null)}>{worldName}</button>{geographyPath(map.geographyId,bundle.geographies).map(g=><span key={g.id}>› <button onClick={()=>select(g.id)} aria-current={g.id===map.geographyId?"location":undefined}>{g.name}</button></span>)}</nav><InteriorFloorNavigation bundle={bundle} map={map} buildingId={bundle.buildingIds?.includes(selected?.id??"")?selected?.id:undefined} onOpen={navigate} onCreate={bundle.canEdit&&onCreateInterior?id=>onCreateInterior(bundle,id):undefined}/><DungeonLevelNavigation bundle={bundle} map={map} siteId={bundle.dungeonSites?.find(s=>s.id===selected?.id)?.id} onOpen={navigate}/>{(ordinary||map.mapKind==="dungeon")&&<div className={styles.actions}><button className="st-button is-secondary" onClick={()=>{const url=new URL(atlasUrl(map.id),window.location.origin);if(ordinary)url.searchParams.delete("ordinary");else url.searchParams.set("ordinary","1");window.history.pushState({atlasTrail:window.history.state?.atlasTrail??[map.id]},"",url.pathname+url.search);}}>{ordinary?"Return to author view":"Ordinary-content server preview"}</button><p>{ordinary?"Owner-only preview: protected records and private notes were removed by the server. Sharing is not enabled.":"Author view includes protected records for authorized World review."}</p></div>}<div className={styles.editorGrid}><div className={styles.mapFrame}><div className={styles.navigation}><button className="st-button is-secondary" aria-label="Zoom out" onClick={()=>move(zoomViewport(view,1/1.3))}><Minus size={17}/></button><button className="st-button is-secondary" aria-label="Zoom in" onClick={()=>move(zoomViewport(view,1.3))}><Plus size={17}/></button><button className="st-button is-secondary" onClick={()=>move(fitViewport())}>Fit map</button><span>Explore mode</span></div><svg ref={svg} aria-label="Explorable geographic map" data-units-per-pixel={units} className={styles.canvas} data-tool="pan" viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} onPointerDown={down} onPointerMove={drag} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)}><CartographyScene draft={draft} id={`explore-${map.id}`} selectedId={selectedId} editable={false} explorable unitsPerPixel={units} motion={motion} cacheTerrain/></svg></div>
      <aside className={styles.inspector} aria-label="Place information">{selected?<><p className={styles.eyebrow}>{map.dungeonEntities?.find(e=>e.id===selected.id)?.kind??map.interiorEntities?.find(e=>e.id===selected.id)?.kind??geographyType(selected)}{selected.archived?" · archived":""}</p><h3>{selected.name}</h3>{map.settlementEntities?.find(e=>e.geographyId===selected.id)?.classification&&<p>{map.settlementEntities.find(e=>e.geographyId===selected.id)!.classification}</p>}{map.interiorEntities?.find(e=>e.id===selected.id)?.classification&&<p>{map.interiorEntities.find(e=>e.id===selected.id)!.classification}</p>}{map.dungeonEntities?.find(e=>e.id===selected.id)?.classification&&<p>{map.dungeonEntities.find(e=>e.id===selected.id)!.classification}</p>}{map.dungeonEntities?.find(e=>e.id===selected.id)?.visibility!=="ordinary"&&map.dungeonEntities?.find(e=>e.id===selected.id)&&<p>Protected author content: {map.dungeonEntities.find(e=>e.id===selected.id)!.visibility}</p>}{map.dungeonEntities?.find(e=>e.id===selected.id)?.privateNotes&&<details><summary>Private author notes</summary><p>{map.dungeonEntities.find(e=>e.id===selected.id)!.privateNotes}</p></details>}<p>{selected.description||"No description has been recorded for this place."}</p>{selected.parentId&&index.places.has(selected.parentId)&&<button className="st-button is-secondary" onClick={()=>select(selected.parentId)}>Within {index.places.get(selected.parentId)!.name}</button>}<h4>Detailed maps</h4>{mapLinks(selected.id)}{!choices(selected.id).length&&<p>No other available detail map is associated with this place.</p>}{bundle.maps.filter(m=>(m.archived||m.unavailable)&&(m.geographyId===selected.id||m.id===index.preferred.get(`${shown}:${selected.id}`))).map(m=><p key={m.id}>{m.name} · {m.archived?"archived":"floor archived"}, unavailable for exploration</p>)}<h4>Related places</h4>{map.settlementEntities?.find(e=>e.geographyId===selected.id)?.districtIds.map(id=><button key={id} className="st-button is-secondary" onClick={()=>select(id)}>District: {index.places.get(id)?.name}</button>)}<div className={styles.featureList}>{bundle.geographies.filter(g=>!g.archived&&g.parentId===selected.id).map(g=><button key={g.id} className="st-button is-secondary" onClick={()=>select(g.id)}>{g.name}</button>)}</div></>:<><h3>{worldName}</h3><p>{map.description||"Select a place on the map or from the list below."}</p></>}
      <h4>Places on this map</h4><div className={styles.featureList}>{[...places].map(id=>index.places.get(id)).filter(g=>g&&!g.archived).map(g=>g&&<button key={g.id} className="st-button is-secondary" aria-pressed={selected?.id===g.id} onClick={()=>select(g.id)}>{g.name}</button>)}</div><details><summary>All World places</summary><div className={styles.featureList}>{bundle.geographies.filter(g=>!g.archived).map(g=><button key={g.id} className="st-button is-secondary" onClick={()=>select(g.id)}>{g.name} · {geographyType(g)}</button>)}</div></details><h4>World maps</h4><div className={styles.actions}>{bundle.maps.filter(m=>!m.archived&&!m.geographyId&&m.id!==shown).map(m=><button key={m.id} className="st-button is-secondary" disabled={loading} onClick={()=>navigate(m.id)}>Open {m.name}</button>)}</div></aside></div></>}
  </section>;
}
