"use client";
import { useEffect, useRef, useState } from "react";
import type { PlaceMilestones } from "./atlas-milestone-service";
import { entryDraftSchema, accuracyLabels, narrativeLabels, dateLabels, prominenceLabels, timeLabel, type EntryDraft, type EntryRecord, type EraRecord } from "./history";
import { entryDraftOf, SaveError, worldApi } from "./client-api";
import { draftFromSource } from "./calendar-entry-fields";
import { Field } from "./world-field";
import { ChronologyYearInput } from "./chronology-year-input";
import styles from "./worlds.module.css";

export function AtlasPlaceHistory({worldId,timelineId,placeId,review,ordinary=false,eras,onClose,onChanged,onDirty}:{worldId:string;timelineId:string;placeId:string;review:boolean;ordinary?:boolean;eras:EraRecord[];onClose:()=>void;onChanged:()=>Promise<unknown>;onDirty:(dirty:boolean)=>void}) {
  const dialog=useRef<HTMLDialogElement>(null),[bundle,setBundle]=useState<PlaceMilestones|null>(null),[editing,setEditing]=useState<{id?:string;revision?:number;requestId:string;draft:EntryDraft}|null>(null),[original,setOriginal]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,setPending]=useState(false),[conflict,setConflict]=useState(false);
  const dirty=!!editing&&JSON.stringify(editing.draft)!==original;
  const query=new URLSearchParams({timeline:timelineId,place:placeId});if(review)query.set("review","1");if(ordinary)query.set("ordinary","1");const api=`/api/worlds/${worldId}/atlas/milestones`,url=`${api}?${query}`;
  async function reload(){const fresh=await worldApi<PlaceMilestones>(url);setBundle(fresh);return fresh;}
  useEffect(()=>{dialog.current?.showModal();let alive=true;worldApi<PlaceMilestones>(url).then(value=>{if(alive)setBundle(value);}).catch(failure=>{if(alive)setError(failure.message);});return()=>{alive=false;};},[url]);
  useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
  useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard);},[dirty]);
  function close(){if(!pending&&(!dirty||window.confirm("Discard this unsaved historical milestone?")))onClose();}
  function begin(record?:EntryRecord&{eventType:string},eventType="Founding"){const draft=record?{...entryDraftOf(record),eventType:record.eventType,...record.calendarSource?{calendarDate:draftFromSource(record.calendarSource)}:{}}:{...entryDraftOf(),title:`${bundle?.place.name} — ${eventType}`,eventType};setEditing({id:record?.id,revision:record?.revision,requestId:crypto.randomUUID(),draft});setOriginal(JSON.stringify(draft));setError("");setConflict(false);}
  function change(partial:Partial<EntryDraft>){if(editing)setEditing({...editing,draft:{...editing.draft,...partial}});}
  const draft=editing?.draft;
  return <dialog ref={dialog} className={styles.editor} aria-labelledby="place-history-title" onCancel={e=>{e.preventDefault();close();}}><header className={styles.editorHeader}><div><p className={styles.eyebrow}>Atlas historical milestones</p><h2 id="place-history-title">{bundle?.place.name??"Loading place history"}</h2></div><button className="st-button is-secondary" onClick={close} disabled={pending}>Close place history</button></header><div className={styles.reader}>
    {bundle&&<><p>Authoring timeline: <strong>{bundle.timelineName}</strong>{bundle.place.archived?" · Archived place":""}</p><p>Milestones save to History separately from map and place edits. Save a new place first, then author its history here. A discovery records an account of finding a place; it does not date the place&apos;s creation.</p>{notice&&<p role="status">{notice}</p>}
      {!editing&&<>{bundle.events.map(e=><article key={e.id}><h3>{e.title}</h3><p>{e.eventType} · {timeLabel(e.time)} · {prominenceLabels[e.prominence??"standard"]}{e.archived?" · Archived account":""}</p><a href={`/worlds/${worldId}?tab=history&timeline=${timelineId}&entry=${e.id}${review?"&review=1":""}${ordinary?"&knowledge=ordinary":""}`}>Read full historical account</a>{bundle.canEdit&&!e.archived&&<button className="st-button is-secondary" onClick={()=>begin(e)}>Edit milestone: {e.title}</button>}</article>)}{!bundle.events.length&&<p>No historical milestone has been authored for this place. Its existence implies no founding date.</p>}{bundle.canEdit&&<div className={styles.actions}>{["Founding","Discovery","Expansion","Destruction","Rebuilding","Rediscovery"].map(type=><button className="st-button is-secondary" key={type} onClick={()=>begin(undefined,type)}>Author {type.toLowerCase()}</button>)}<button className="st-button" onClick={()=>begin(undefined,"Original event")}>Author custom milestone</button></div>}</>}
      {draft&&editing&&<form onSubmit={async e=>{e.preventDefault();setError("");setConflict(false);const parsed=entryDraftSchema.safeParse(draft);if(!parsed.success||!draft.eventType?.trim()){setError(parsed.success?"Name the historical event type.":parsed.error.issues.map(i=>i.message).join(" "));return;}setPending(true);try{await worldApi(api,"POST",{timelineId,geographyId:placeId,geographyRevision:bundle.place.revision,requestId:editing.requestId,...editing.id?{entryId:editing.id,revision:editing.revision}:{},eventType:draft.eventType,draft:parsed.data});setEditing(null);setNotice("Historical milestone saved to History. Map and place edits use their own save.");try{await reload();await onChanged();}catch(failure){setError(`History was saved successfully. ${(failure as Error).message} Reload to read the acknowledged result.`);}}catch(failure){setError((failure as Error).message);setConflict(failure instanceof SaveError&&failure.status===409);}finally{setPending(false);}}}>
        <fieldset disabled={pending}><Field label="Historical event type" help="Name Founding, Discovery, Migration or any original authored event. Separate discovery perspectives can coexist."><input required maxLength={160} value={draft.eventType??""} onChange={e=>change({eventType:e.target.value})}/></Field><Field label="Milestone title" help="Give this distinct account a title. Several accounts can concern the same place."><input required maxLength={160} value={draft.title} onChange={e=>change({title:e.target.value})}/></Field><Field label="Historical account" help="Write the full account and perspective. The event is not inferred from a place description or database timestamp."><textarea required rows={4} maxLength={50000} value={draft.account} onChange={e=>change({account:e.target.value})}/></Field>
        <Field label="Date representation" help="Known years, approximate anchors, uncertain occurrence windows, durations and unknown dates keep their distinct meanings."><select value={draft.time.kind} onChange={e=>{const kind=e.target.value as EntryDraft["time"]["kind"],t=draft.time,year="year"in t?t.year:"startYear"in t?t.startYear:0;change({time:kind==="undated"?{version:1,scale:"world-year",kind}:kind==="known"||kind==="approximate"?{version:1,scale:"world-year",kind,year}:{version:1,scale:"world-year",kind,startYear:year,endYear:"endYear"in t?t.endYear:year}});}}>{Object.entries(dateLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
        {draft.time.kind!=="undated"&&<>{("year"in draft.time?["year"]:["startYear","endYear"]).map(key=><ChronologyYearInput key={`${draft.time.kind}:${key}`} label={key==="year"?"Year":key==="startYear"?"Starting year":"Ending year"} system={null} value={draft.time[key as keyof typeof draft.time] as number} onChange={value=>change({time:{...draft.time,[key]:value??NaN} as EntryDraft["time"]})}/>)}<p>Enter canonical World years, including negative years and Year 0. Existing calendar and reckoning source notation remains retained.</p></>}
        <Field label="Timeline prominence" help="Index-only retains this account in the index and place reader while hiding its usual visual marker. Featured and standard affect presentation, not privacy or reliability."><select value={draft.prominence??"standard"} onChange={e=>change({prominence:e.target.value as EntryDraft["prominence"]})}>{Object.entries(prominenceLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
        <details><summary>Reliability, eras and protected knowledge</summary><Field label="Historical accuracy" help="Classify confidence in this account without establishing universal truth."><select value={draft.accuracy} onChange={e=>change({accuracy:e.target.value as EntryDraft["accuracy"]})}>{Object.entries(accuracyLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Narrative status" help="An authored plan remains distinct from recorded history."><select value={draft.narrative} onChange={e=>change({narrative:e.target.value as EntryDraft["narrative"]})}>{Object.entries(narrativeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Account knowledge" help="Protected accounts are omitted from ordinary server previews. Timeline prominence grants no access."><select value={draft.visibility??"ordinary"} onChange={e=>change({visibility:e.target.value as EntryDraft["visibility"]})}><option value="ordinary">Ordinary knowledge</option><option value="protected">Protected author knowledge</option></select></Field>{eras.filter(e=>!e.archived||draft.eraIds.includes(e.id)).map(era=><label key={era.id}><input type="checkbox" checked={draft.eraIds.includes(era.id)} onChange={e=>change({eraIds:e.target.checked?[...draft.eraIds,era.id]:draft.eraIds.filter(id=>id!==era.id)})}/>{era.name}</label>)}<Field label="Author notes" help="Private notes remain separate from the historical account and are removed from ordinary preview."><textarea value={draft.notes} onChange={e=>change({notes:e.target.value})}/></Field></details>
        </fieldset><div className={styles.actions}><button type="button" className="st-button is-secondary" disabled={pending} onClick={()=>{if(!dirty||window.confirm("Discard this milestone draft?"))setEditing(null);}}>Cancel milestone</button><button className="st-button" disabled={pending}>{pending?"Saving…":"Save historical milestone"}</button></div>
      </form>}
    </>}{error&&<div role="alert"><p>{error}</p>{conflict&&editing&&<button className="st-button is-secondary" disabled={pending} onClick={async()=>{if(!window.confirm("Discard this draft and load the latest saved place and event?"))return;setPending(true);try{const fresh=await reload();const record=editing.id?fresh.events.find(e=>e.id===editing.id):undefined;if(editing.id&&!record)throw new Error("This event is unavailable. Your draft remains retained.");begin(record,editing.draft.eventType); }catch(failure){setError((failure as Error).message);}finally{setPending(false);}}}>Load latest milestone</button>}</div>}
  </div></dialog>;
}
