"use client";
import { useEffect, useMemo, useRef, useState, type FormEvent, type PointerEvent as ReactPointerEvent } from "react";
import { ArrowLeft, Hand, MousePointer2, Move, Pencil, MapPin, Undo2, Redo2, Save } from "lucide-react";
import { GuidedField } from "@/components/field-guidance";
import { MAP_HEIGHT, MAP_WIDTH, acceptSavedHistory, boundedPoint, commitAction, draftOf, fitViewport, moveGeometry, redoAction, rounded, undoAction, validateGeometry, validateMapDraft, zoomViewport, type AtlasMap, type AtlasFeature, type EditingHistory, type GeographyRecord, type MapDraft, type Point, type Vertex } from "./atlas";
import { GenerationHistory } from "./generation-history";
import { CartographyScene } from "./cartography-scene";
import { CartographyOptions, DrawingInspector, LinkedPlaceControl, MapLayerControls, defaultBrush } from "./cartography-controls";
import { defaultPresentation, drawingLayer, drawingSchema, moveDrawing, type MapDrawing } from "./cartography";
import { detailCoastline, prepareSculpt, sculptCoastline, simplifyTrace, smoothCoastline } from "./coastline";
import { exportMapPng } from "./cartography-export";
import styles from "./atlas.module.css";
type Tool="select"|"draw"|"trace"|"sculpt"|"paint"|"path"|"symbol"|"label"|"edit"|"move"|"marker"|"pan";
type Loaded={map:AtlasMap;geographies:GeographyRecord[]};
type MapGesture={pointer:number;start:Point;base:EditingHistory;featureId?:string;vertexId?:string;view:ReturnType<typeof fitViewport>;drawingId?:string;coast?:Extract<AtlasFeature["geometry"],{type:"polygon"}>;paint?:MapDrawing;trace?:Vertex[]};
const tools=[{id:"select",label:"Select",icon:MousePointer2},{id:"draw",label:"Draw landmass",icon:Pencil},{id:"edit",label:"Edit points",icon:Pencil},{id:"move",label:"Move feature",icon:Move},{id:"marker",label:"Place location",icon:MapPin},{id:"pan",label:"Pan",icon:Hand},{id:"trace",label:"Freehand coast",icon:Pencil},{id:"sculpt",label:"Sculpt coast",icon:Pencil},{id:"paint",label:"Paint terrain",icon:Pencil},{id:"path",label:"Draw path",icon:Pencil},{id:"symbol",label:"Place symbol",icon:MapPin},{id:"label",label:"Place label",icon:Pencil}] as const;
const help:Record<Tool,string>={trace:"Trace a coastline with mouse or touch, then close the outline. The saved coastline keeps editable boundary points.",sculpt:"Select a landmass first. Start near its coastline and drag inward to carve a bay, or outward for a peninsula. The brush changes real boundary points.",paint:"Drag to paint illustrated terrain. Each stroke is one editable group. Terrain is clipped to land when a coastline exists; select a stroke to resize, move or change it.",path:"Tap points to draw a river, stream, road or trail, then complete the path. Edit points reshapes the same path later.",symbol:"Tap to place a cartographic symbol. Real settlements and landmarks keep a linked location record.",label:"Tap to place readable text. Select its label later to move, resize, rotate or edit it.",select:"Tap a feature or choose it from the list. Selection never moves the map's shapes.",draw:"Tap the map to add boundary points, then close the outline. Use Undo to remove the last unfinished point.",edit:"Select a landmass, then drag a boundary point or use its coordinate controls. Add a point after the chosen vertex.",move:"Drag the selected feature, or move it with the direction buttons. Its geography identity stays the same.",marker:"Tap the map to place a named location. You can rename it in the information panel.",pan:"Drag to explore the map. Zoom and Fit map also change only your view."};

export function AtlasMapEditor({map,geographies,canEdit,onDirtyChange,onClose,onSave,onReload,onExplore,onConnections}:{map:AtlasMap;geographies:GeographyRecord[];canEdit:boolean;onDirtyChange:(dirty:boolean)=>void;onClose:()=>void;onSave:(body:{revision:number;draft:MapDraft})=>Promise<Loaded>;onReload:()=>Promise<Loaded>;onExplore?:()=>void;onConnections?:()=>void}) {
  const [history,setHistory]=useState<EditingHistory>(()=>({past:[],present:draftOf(map,geographies),future:[]})),historyRef=useRef(history),[saved,setSaved]=useState(()=>JSON.stringify(history.present)),[revision,setRevision]=useState(map.revision),[tool,setTool]=useState<Tool>("select"),[view,setView]=useState(fitViewport),[selectedId,setSelectedId]=useState<string|null>(null),[vertexId,setVertexId]=useState<string|null>(null),[drawing,setDrawing]=useState<Vertex[]>([]),[drawingFuture,setDrawingFuture]=useState<Vertex[]>([]),[newKind,setNewKind]=useState<"continent"|"island">("continent"),[existingId,setExistingId]=useState(""),[pending,setPending]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[comparison,setComparison]=useState<Loaded|null>(null),[pointSize,setPointSize]=useState(18),[formDirty,setFormDirty]=useState(false);
  const [brush,setBrush]=useState(defaultBrush),[artPreview,setArtPreview]=useState<MapDrawing|null>(null),[tracePreview,setTracePreview]=useState<Vertex[]>([]),[brushPosition,setBrushPosition]=useState<Point|null>(null),[gesturing,setGesturing]=useState(false),[exporting,setExporting]=useState(false);
  const [motion,setMotion]=useState(false),motionTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  function movingArtwork(){setMotion(true);if(motionTimer.current)clearTimeout(motionTimer.current);motionTimer.current=setTimeout(()=>setMotion(false),350);}
  function navigate(next:Parameters<typeof setView>[0]){movingArtwork();setView(next);}
  useEffect(()=>()=>{if(motionTimer.current)clearTimeout(motionTimer.current);},[]);
  const inspector=useRef<HTMLFieldSetElement>(null),pendingForms=useRef(new Set<HTMLFormElement>());
  function editFields(e:FormEvent<HTMLFormElement>){pendingForms.current.add(e.currentTarget);setFormDirty(true);}
  function applyFields(e:FormEvent<HTMLFormElement>){pendingForms.current.delete(e.currentTarget);setFormDirty(pendingForms.current.size>0);}
  function discardFields(){pendingForms.current.forEach(form=>form.reset());pendingForms.current.clear();setFormDirty(false);}
  const exportSvg=useRef<SVGSVGElement>(null);
  const svg=useRef<SVGSVGElement>(null),gesture=useRef<MapGesture|null>(null);
  const draft=history.present,selected=draft.features.find(f=>f.id===selectedId),geography=draft.geographies.find(g=>g.id===selected?.geographyId),selectedVertex=selected?.geometry.type==="polygon"?selected.geometry.points.find(p=>p.id===vertexId):undefined;
  const selectedDrawing=(draft.drawings??[]).find(d=>d.id===selectedId),linkedGeography=draft.geographies.find(g=>g.id===selectedDrawing?.geographyId),geographyOptions=[...geographies,...draft.geographies.filter(g=>!geographies.some(old=>old.id===g.id)).map(g=>({...g,revision:g.revision??1,archived:false}))],presentation=draft.presentation??defaultPresentation();
  const fingerprint=useMemo(()=>JSON.stringify(draft),[draft]);
  const dirty=fingerprint!==saved||drawing.length>0||formDirty||(gesturing&&tool!=="pan"),dirtyRef=useRef(dirty);
  useEffect(()=>{dirtyRef.current=dirty;onDirtyChange(dirty);},[dirty,onDirtyChange]);
  useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue="";}};const click=(e:MouseEvent)=>{const link=(e.target as Element).closest?.("a[href]");if(link&&!link.hasAttribute("download")&&dirtyRef.current&&!window.confirm("Leave this map and discard its unsaved changes?")){e.preventDefault();e.stopPropagation();}};window.addEventListener("beforeunload",before);let returning=false;const back=(e:PopStateEvent)=>{if(returning){returning=false;return;}if(dirtyRef.current&&!window.confirm("Leave this map and discard unsaved changes?")){e.stopImmediatePropagation();returning=true;window.history.go(1);}};document.addEventListener("click",click,true);window.addEventListener("popstate",back,true);return()=>{window.removeEventListener("beforeunload",before);document.removeEventListener("click",click,true);window.removeEventListener("popstate",back,true);};},[]);
  useEffect(()=>{const node=svg.current;if(!node)return;const resize=()=>{const matrix=node.getScreenCTM();if(matrix)setPointSize(22/Math.max(Math.abs(matrix.a),.01));};const observer=new ResizeObserver(resize);observer.observe(node);resize();return()=>observer.disconnect();},[view]);
  function update(next:EditingHistory){movingArtwork();historyRef.current=next;setHistory(next);}
  function commit(next:MapDraft){update(commitAction(historyRef.current,next));setNotice("");setError("");}
  function changeGeometry(id:string,geometry:AtlasFeature["geometry"]){commit({...historyRef.current.present,features:historyRef.current.present.features.map(f=>f.id===id?{...f,geometry}:f)});}
  function choose(next:Tool){if(gesture.current)return;if(next===tool)return;if(formDirty&&!window.confirm("Discard the unapplied information fields?"))return;if(drawing.length&&!window.confirm("Discard this unfinished outline?"))return;discardFields();setDrawing([]);setDrawingFuture([]);setTool(next);setError("");setExistingId(next==="label"?(geography?.id??selectedDrawing?.geographyId??""):"");if(next==="label"&&(geography||linkedGeography))setBrush(b=>({...b,text:(geography??linkedGeography)!.name}));}
  function project(clientX:number,clientY:number):Point {const matrix=svg.current!.getScreenCTM();if(!matrix)throw new Error("The map view is unavailable.");const point=new DOMPoint(clientX,clientY).matrixTransform(matrix.inverse());return {x:point.x,y:point.y};}
  function addFeature(geometry:AtlasFeature["geometry"]) {
    try{validateGeometry(geometry);const kind=geometry.type==="point"?"location":newKind,current=historyRef.current.present,existing=geographies.find(g=>g.id===existingId),geoId=existing?.id??crypto.randomUUID(),id=crypto.randomUUID();
      if(existing&&(existing.archived||existing.kind!==kind))throw new Error("Choose an active geography of the matching kind.");
      const geo=current.geographies.find(g=>g.id===geoId)??(existing?{id:existing.id,name:existing.name,description:existing.description,kind:existing.kind,parentId:existing.parentId,revision:existing.revision}:{id:geoId,revision:null,name:`New ${kind}`,description:"",kind,parentId:null});
      const next={...current,features:[...current.features,{id,geographyId:geoId,geometry,archived:false}],geographies:current.geographies.some(g=>g.id===geoId)?current.geographies:[...current.geographies,geo]};validateMapDraft(next);commit(next);setSelectedId(id);setVertexId(null);setDrawing([]);setDrawingFuture([]);setTool("select");setNotice("Feature added to your draft. Name it in the information panel, then save the map.");
    }catch(failure){setError((failure as Error).message);}
  }
  const layerEditable=(layer:ReturnType<typeof drawingLayer>)=>canEdit&&presentation.layers[layer].visible&&!presentation.layers[layer].locked;
  const featureEditable=selected&&layerEditable(selected.geometry.type==="polygon"?"land":"symbols");
  const artEditable=selectedDrawing&&layerEditable(drawingLayer(selectedDrawing));
  function changeDrawing(next:MapDrawing){try{if(!layerEditable(drawingLayer(next)))throw new Error("Show and unlock the destination layer before changing this drawing.");drawingSchema.parse(next);const changed={...historyRef.current.present,drawings:(historyRef.current.present.drawings??[]).map(d=>d.id===next.id?next:d)};validateMapDraft(changed);commit(changed);return true;}catch(failure){setError((failure as Error).message);return false;}}
  function reorderDrawing(direction:number){if(!selectedDrawing||!artEditable)return;const drawings=[...(draft.drawings??[])],at=drawings.findIndex(d=>d.id===selectedDrawing.id),layer=drawingLayer(selectedDrawing);let target=at+direction;while(target>=0&&target<drawings.length&&(drawings[target].archived||drawingLayer(drawings[target])!==layer))target+=direction;if(target<0||target>=drawings.length)return;[drawings[at],drawings[target]]=[drawings[target],drawings[at]];commit({...draft,drawings});}
  function addDrawing(source:MapDrawing){try{let next=historyRef.current.present;const realPlace=source.type==="symbol"&&!["mountain","pine"].includes(source.kind);if(source.type==="symbol"&&realPlace&&!source.geographyId){const geo={id:crypto.randomUUID(),revision:null,name:`New ${source.kind}`,description:"",kind:"location" as const,parentId:null};source={...source,geographyId:geo.id};next={...next,geographies:[...next.geographies,geo]};}else if(source.geographyId&&!next.geographies.some(g=>g.id===source.geographyId)){const g=geographies.find(g=>g.id===source.geographyId);if(!g||g.archived)throw new Error("Choose an active place in this World.");if(realPlace&&g.kind!=="location")throw new Error("Settlement and landmark symbols need a location record.");next={...next,geographies:[...next.geographies,{id:g.id,revision:g.revision,name:g.name,description:g.description,kind:g.kind,parentId:g.parentId}]};}drawingSchema.parse(source);next={...next,drawings:[...(next.drawings??[]),source]};validateMapDraft(next);commit(next);setSelectedId(source.id);setVertexId(null);setDrawing([]);setDrawingFuture([]);setTool("select");return true;}catch(failure){setError((failure as Error).message);return false;}}
  function completePath(){addDrawing({version:1,id:crypto.randomUUID(),name:`New ${brush.path}`,archived:false,geographyId:existingId||null,type:"path",kind:brush.path,points:drawing,width:brush.width,curve:brush.curve});}
  function down(e:ReactPointerEvent<SVGSVGElement>){if(!e.isPrimary||e.button!==0||pending||gesture.current)return;if(formDirty&&tool!=="pan"&&tool!=="select"){setError("Apply the information fields before editing the map.");return;}e.preventDefault();const point=project(e.clientX,e.clientY),target=e.target as Element,featureId=target.closest("[data-feature]")?.getAttribute("data-feature")??undefined,drawingId=target.closest("[data-drawing]")?.getAttribute("data-drawing")??undefined,pointId=target.closest("[data-vertex]")?.getAttribute("data-vertex")??undefined;
    const layer=tool==="paint"?"terrain":tool==="path"?(brush.path==="river"||brush.path==="stream"?"waterways":"paths"):tool==="label"?"labels":tool==="marker"||tool==="symbol"?"symbols":"land";
    if(["paint","path","label","marker","symbol","draw","trace","sculpt"].includes(tool)&&!layerEditable(layer)){setError("Show and unlock this tool's layer before editing it.");return;}
    if(tool==="draw"||tool==="path"){if(drawing.length>=(tool==="draw"?256:128)){setError("This outline or path has reached its point limit.");return;}setDrawing([...drawing,{...boundedPoint(point),id:crypto.randomUUID()}]);setDrawingFuture([]);return;}
    if(tool==="marker"){addFeature({version:1,type:"point",point:boundedPoint(point)});return;}
    const common={version:1 as const,id:crypto.randomUUID(),archived:false,geographyId:existingId||null};
    if(tool==="symbol"){addDrawing({...common,name:`New ${brush.symbol}`,type:"symbol",kind:brush.symbol,point:boundedPoint(point),scale:brush.scale,rotation:brush.rotation,style:brush.symbolStyle});return;}
    if(tool==="label"){addDrawing({...common,name:brush.text,type:"label",text:brush.text,point:boundedPoint(point),size:brush.labelSize,rotation:brush.rotation,style:brush.labelStyle});return;}
    if(tool==="paint"||tool==="trace"||tool==="sculpt"){
      try{const g:MapGesture={pointer:e.pointerId,start:point,base:historyRef.current,view};
        if(tool==="paint"){g.paint={...common,geographyId:null,name:`${brush.terrain} stroke`,type:"terrain",kind:brush.terrain,points:[{...boundedPoint(point),id:crypto.randomUUID()}],radius:brush.radius,spacing:brush.spacing,density:brush.density,seed:crypto.getRandomValues(new Uint32Array(1))[0]%2147483646+1};drawingSchema.parse(g.paint);setArtPreview(g.paint);}
        if(tool==="trace"){if(drawing.length)throw new Error("Close or cancel the current outline before tracing a new one.");g.trace=[{...boundedPoint(point),id:crypto.randomUUID()}];setTracePreview(g.trace);}
        if(tool==="sculpt"){if(!selected||selected.archived||selected.geometry.type!=="polygon")throw new Error("Select an active continent or island before sculpting.");g.featureId=selected.id;g.coast=prepareSculpt(selected.geometry,point,brush.radius,()=>crypto.randomUUID());}
        gesture.current=g;setGesturing(true);e.currentTarget.setPointerCapture(e.pointerId);
      }catch(failure){setError((failure as Error).message);}return;
    }
    if(tool!=="pan"){const id=featureId??drawingId;if(formDirty&&id!==selectedId&&!window.confirm("Discard the unapplied information fields?"))return;if(id!==selectedId)discardFields();setSelectedId(id??null);setVertexId(pointId??null);}
    const f=historyRef.current.present.features.find(f=>f.id===featureId),d=(historyRef.current.present.drawings??[]).find(d=>d.id===drawingId),editable=f?layerEditable(f.geometry.type==="polygon"?"land":"symbols"):d?layerEditable(drawingLayer(d)):false;
    if(tool==="pan"||(editable&&(tool==="move"||(tool==="edit"&&pointId)))){gesture.current={pointer:e.pointerId,start:point,base:historyRef.current,featureId,drawingId,vertexId:pointId,view};setGesturing(true);e.currentTarget.setPointerCapture(e.pointerId);}
  }
  function applyMove(e:{clientX:number;clientY:number;pointerId:number}){const current=project(e.clientX,e.clientY);if(tool==="paint"||tool==="sculpt")setBrushPosition(current);const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;const dx=current.x-g.start.x,dy=current.y-g.start.y;
    if(tool==="pan"){const matrix=svg.current!.getScreenCTM()!;const originalScreen=new DOMPoint(g.start.x,g.start.y).matrixTransform(matrix);navigate({...g.view,x:view.x-(e.clientX-originalScreen.x)/matrix.a,y:view.y-(e.clientY-originalScreen.y)/matrix.d});return;}
    if(g.paint&&g.paint.type==="terrain"){const p=boundedPoint(current),last=g.paint.points.at(-1)!;if(Math.hypot(p.x-last.x,p.y-last.y)>=8&&g.paint.points.length<128){g.paint={...g.paint,points:[...g.paint.points,{...p,id:crypto.randomUUID()}]};setArtPreview(g.paint);}return;}
    if(g.trace){const p=boundedPoint(current),last=g.trace.at(-1)!;if(Math.hypot(p.x-last.x,p.y-last.y)>=4&&g.trace.length<1024){g.trace.push({...p,id:crypto.randomUUID()});setTracePreview([...g.trace]);}return;}
    const f=g.base.present.features.find(f=>f.id===g.featureId),d=(g.base.present.drawings??[]).find(d=>d.id===g.drawingId);
    if(d){const next=tool==="move"?moveDrawing(d,dx,dy):(d.type==="path"||d.type==="terrain")?{...d,points:d.points.map(p=>p.id===g.vertexId?{...p,...boundedPoint(current)}:p)}:d;update({...g.base,present:{...g.base.present,drawings:(g.base.present.drawings??[]).map(n=>n.id===d.id?next:n)}});return;}
    if(!f)return;let geometry=f.geometry;
    if(g.coast)geometry=sculptCoastline(g.coast,g.start,boundedPoint(current),brush.radius);
    else if(tool==="move")geometry=moveGeometry(f.geometry,dx,dy);else if(f.geometry.type==="polygon")geometry={...f.geometry,points:f.geometry.points.map(p=>p.id===g.vertexId?{...p,...boundedPoint(current)}:p)};
    update({...g.base,present:{...g.base.present,features:g.base.present.features.map(n=>n.id===f.id?{...n,geometry}:n)}});
  }
  const moveFrame=useRef<number|null>(null),lastMove=useRef<{clientX:number;clientY:number;pointerId:number}|null>(null);
  useEffect(()=>()=>{if(moveFrame.current!==null)cancelAnimationFrame(moveFrame.current);},[]);
  function flushMove(){if(moveFrame.current!==null)cancelAnimationFrame(moveFrame.current);moveFrame.current=null;const point=lastMove.current;lastMove.current=null;if(point)applyMove(point);}
  function moving(e:ReactPointerEvent<SVGSVGElement>){lastMove.current={clientX:e.clientX,clientY:e.clientY,pointerId:e.pointerId};if(moveFrame.current===null)moveFrame.current=requestAnimationFrame(flushMove);}
  function finish(e:ReactPointerEvent<SVGSVGElement>,cancel=false){flushMove();const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;gesture.current=null;setGesturing(false);setArtPreview(null);setTracePreview([]);if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);if(tool==="pan")return;
    if(cancel){update(g.base);setNotice("The interrupted edit was cancelled; the previous draft is retained.");return;}
    if(g.paint){addDrawing(g.paint);setTool("paint");return;}
    if(g.trace){let points=simplifyTrace(g.trace,4);for(let tolerance=8;points.length>256&&tolerance<200;tolerance*=2)points=simplifyTrace(g.trace,tolerance);if(points.length>2&&Math.hypot(points[0].x-points.at(-1)!.x,points[0].y-points.at(-1)!.y)<6)points=points.slice(0,-1);setDrawing(points);setDrawingFuture([]);return;}
    const next=historyRef.current.present;try{validateMapDraft(next);update(commitAction(g.base,next));setError("");}catch(failure){update(g.base);setError(`${(failure as Error).message} That edit was cancelled; the previous geometry is retained.`);}
  }
  function nudge(dx:number,dy:number){if(selectedDrawing&&artEditable){const d=selectedDrawing,next=tool==="edit"&&(d.type==="terrain"||d.type==="path")&&vertexId?{...d,points:d.points.map(p=>p.id===vertexId?{...p,...boundedPoint({x:p.x+dx,y:p.y+dy})}:p)}:moveDrawing(d,dx,dy);changeDrawing(next);return;}if(!selected||!featureEditable)return;const geometry=tool==="edit"&&selected.geometry.type==="polygon"&&vertexId?{...selected.geometry,points:selected.geometry.points.map(p=>p.id===vertexId?{...p,...boundedPoint({x:p.x+dx,y:p.y+dy})}:p)}:moveGeometry(selected.geometry,dx,dy);try{validateGeometry(geometry);changeGeometry(selected.id,geometry);}catch(failure){setError((failure as Error).message);}}
  function undo(){if(drawing.length){setDrawingFuture([drawing.at(-1)!,...drawingFuture]);setDrawing(drawing.slice(0,-1));}else update(undoAction(historyRef.current));}
  function redo(){if(drawingFuture.length){setDrawing([...drawing,drawingFuture[0]]);setDrawingFuture(drawingFuture.slice(1));}else update(redoAction(historyRef.current));}
  function download(){const blob=new Blob([JSON.stringify({format:"serrian-atlas-draft-v1",mapId:map.id,revision,draft:historyRef.current.present},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="serrian-atlas-draft.json";a.click();URL.revokeObjectURL(url);}
  function accept(loaded:Loaded,reset:boolean){const next=draftOf(loaded.map,loaded.geographies);update(reset?{past:[],present:next,future:[]}:acceptSavedHistory(historyRef.current,next));pendingForms.current.clear();setFormDirty(false);setSaved(JSON.stringify(next));setRevision(loaded.map.revision);setDrawing([]);setDrawingFuture([]);setComparison(null);setError("");if(reset){setSelectedId(null);setVertexId(null);}}
  return <section className={styles.workshop} aria-label="Map editor">{exporting&&<svg ref={exportSvg} className={styles.exportScene} viewBox="0 0 2000 1200" aria-hidden="true"><CartographyScene draft={draft} id={`export-${map.id}`} editable={false} unitsPerPixel={1}/></svg>}<header className={styles.heading}><div><p className={styles.eyebrow}>{map.scope} chart · {map.archived?"Archived map":"Private World Atlas"}</p><h2>{draft.name}</h2><p role="status">{dirty?"Unsaved changes":notice||"All changes saved"}{!canEdit?" · Read-only":""}</p></div><div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={()=>{if(!dirty||window.confirm("Close this map and discard unsaved changes?"))onClose();}}><ArrowLeft size={17}/>Map library</button>{onExplore&&<button className="st-button is-secondary" disabled={pending||gesturing} onClick={()=>{if(!dirty||window.confirm("Explore the saved map and discard unsaved changes?"))onExplore();}}>Explore map</button>}{canEdit&&onConnections&&<button className="st-button is-secondary" disabled={pending||dirty||gesturing} onClick={onConnections}>Edit connections</button>}{canEdit&&<button className="st-button" disabled={pending||gesturing||!dirty||drawing.length>0||formDirty} onClick={async()=>{setPending(true);setError("");try{validateMapDraft(historyRef.current.present);const fresh=await onSave({revision,draft:historyRef.current.present});accept(fresh,false);setNotice("Map saved. Your features and geography identities are preserved.");}catch(failure){setError(failure instanceof Error?failure.message:"Save failed. Your draft is retained.");}finally{setPending(false);}}}><Save size={17}/>{pending?"Saving…":"Save map"}</button>}</div></header>
    <div className={styles.toolbar} role="toolbar" aria-label="Map tools">{tools.filter(t=>canEdit||t.id==="select"||t.id==="pan").map(t=><button key={t.id} type="button" className="st-button is-secondary" aria-pressed={tool===t.id} disabled={pending||gesturing} onClick={()=>choose(t.id)}><t.icon size={17}/>{t.label}</button>)}{canEdit&&<><button className="st-button is-ghost" aria-label="Undo" disabled={pending||gesturing||(formDirty||(!history.past.length&&!drawing.length))} onClick={undo}><Undo2 size={18}/>Undo</button><button className="st-button is-ghost" aria-label="Redo" disabled={pending||gesturing||(formDirty||(!history.future.length&&!drawingFuture.length))} onClick={redo}><Redo2 size={18}/>Redo</button></>}</div>
    {formDirty&&<p role="status" className={styles.feedback}>Apply the information or point changes below before saving the map.</p>}
    <p className={styles.toolHelp}><strong>{tools.find(t=>t.id===tool)?.label}.</strong> {help[tool]}</p>
    {(tool==="draw"||tool==="trace"||tool==="marker")&&<div className={styles.drawingBar}>{(tool==="draw"||tool==="trace")&&<GuidedField label="Landmass kind" help="Draw a continent or island. Both keep individually editable boundary points."><select className="st-control" value={newKind} disabled={drawing.length>0} onChange={e=>{setNewKind(e.target.value as typeof newKind);setExistingId("");}}><option value="continent">Continent</option><option value="island">Island</option></select></GuidedField>}<GuidedField label="Link geography" help="Create a new record, or draw another representation of an existing geography in this World."><select className="st-control" value={existingId} onChange={e=>setExistingId(e.target.value)}><option value="">Create new geography</option>{geographies.filter(g=>!g.archived&&g.kind===(tool==="marker"?"location":newKind)).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField>{(tool==="draw"||tool==="trace")&&<><span>{drawing.length} outline points</span><button className="st-button" disabled={drawing.length<3} onClick={()=>addFeature({version:1,type:"polygon",points:drawing})}>Close outline</button><button className="st-button is-secondary" disabled={!drawing.length} onClick={()=>{if(window.confirm("Discard this unfinished outline?")){setDrawing([]);setDrawingFuture([]);}}}>Cancel outline</button></>}</div>}
    {["paint","sculpt","path","symbol","label"].includes(tool)&&<CartographyOptions tool={tool} brush={brush} setBrush={setBrush}/>}
    {(tool==="symbol"||tool==="label"||tool==="path")&&<LinkedPlaceControl value={existingId} onChange={setExistingId} geographies={tool==="symbol"&&!(["mountain","pine"] as string[]).includes(brush.symbol)?geographyOptions.filter(g=>g.kind==="location"):geographyOptions}/>}
    {tool==="path"&&<div className={styles.actions}><span>{drawing.length} path points</span><button className="st-button" disabled={drawing.length<2} onClick={completePath}>Complete path</button><button className="st-button is-secondary" onClick={()=>{if(window.confirm("Discard this unfinished path?")){setDrawing([]);setDrawingFuture([]);}}}>Cancel path</button></div>}
    {selected?.geometry.type==="polygon"&&featureEditable&&<div className={styles.coastActions}><span>Coastline shaping</span><button className="st-button is-secondary" disabled={formDirty||gesturing} onClick={()=>{try{if(selected.geometry.type==="polygon")changeGeometry(selected.id,smoothCoastline(selected.geometry));}catch(failure){setError((failure as Error).message);}}}>Smooth coastline</button><button className="st-button is-secondary" disabled={formDirty||gesturing} onClick={()=>{try{if(selected.geometry.type==="polygon")changeGeometry(selected.id,detailCoastline(selected.geometry,18,()=>crypto.randomUUID()));}catch(failure){setError((failure as Error).message);}}}>Add coastal detail</button><small>These tools change the saved boundary points; Undo restores the previous coastline.</small></div>}
    {error&&<div role="alert" className={styles.feedback}><p>{error}</p>{canEdit&&<div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={async()=>{try{setComparison(await onReload());}catch(failure){setError((failure as Error).message);}}}>Load saved map to compare</button><button className="st-button is-secondary" onClick={download}>Download draft</button></div>}</div>}
    {comparison&&<aside className={styles.comparison}><h3>Saved map · revision {comparison.map.revision}</h3><p>{comparison.map.name} · {comparison.map.features.filter(f=>!f.archived).length} active features. Your unsaved draft is still in the editor below.</p><svg viewBox="0 0 2000 1200" aria-label="Saved geometry comparison"><CartographyScene draft={draftOf(comparison.map,comparison.geographies)} id={`comparison-${map.id}`} editable={false}/></svg><div className={styles.actions}><button className="st-button is-secondary" onClick={download}>Download draft</button><button className="st-button" onClick={()=>{if(window.confirm("Replace your unsaved draft with this saved map? Download the draft first if you want to keep it."))accept(comparison,true);}}>Use saved map</button><button className="st-button is-secondary" onClick={()=>setComparison(null)}>Keep viewing draft</button></div></aside>}
    <div className={styles.editorGrid}><div className={styles.mapFrame}><div className={styles.navigation} aria-label="Map navigation"><button className="st-button is-secondary" aria-label="Zoom in" onClick={()=>navigate(v=>zoomViewport(v,1.4))}>+</button><button className="st-button is-secondary" aria-label="Zoom out" onClick={()=>navigate(v=>zoomViewport(v,1/1.4))}>−</button><button className="st-button is-secondary" onClick={()=>navigate(fitViewport())}>Fit map</button><span>{Math.round(MAP_WIDTH/view.width*100)}%</span></div>
      <svg ref={svg} className={styles.canvas} viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} role="application" aria-label="Editable map canvas" tabIndex={0} data-tool={tool} onPointerDown={down} onPointerMove={moving} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)} onKeyDown={e=>{if(e.key==="Escape"){if(gesture.current){update(gesture.current.base);if(svg.current?.hasPointerCapture(gesture.current.pointer))svg.current.releasePointerCapture(gesture.current.pointer);gesture.current=null;setArtPreview(null);setTracePreview([]);setGesturing(false);}setSelectedId(null);setVertexId(null);}if(e.key==="+"||e.key==="=")navigate(v=>zoomViewport(v,1.4));if(e.key==="-")navigate(v=>zoomViewport(v,1/1.4));if(e.key==="Home")navigate(fitViewport());}}>
        <CartographyScene draft={artPreview?{...draft,drawings:[...(draft.drawings??[]),artPreview]}:draft} id={`map-${map.id}`} selectedId={selectedId} unitsPerPixel={pointSize/22} cacheTerrain motion={motion||gesturing}/>
        {(tool==="paint"||tool==="sculpt")&&brushPosition&&<circle cx={brushPosition.x} cy={brushPosition.y} r={brush.radius} className={styles.brushPreview} pointerEvents="none"/>}
        {tracePreview.length>0&&<polyline points={tracePreview.map(p=>`${p.x},${p.y}`).join(" ")} className={styles.tracePreview} pointerEvents="none"/>}
        {drawing.length>0&&<g className={styles.drawing} pointerEvents="none"><polyline points={drawing.map(p=>`${p.x},${p.y}`).join(" ")}/>{drawing.map(p=><circle key={p.id} cx={p.x} cy={p.y} r={pointSize*.3}/>)}</g>}
        {featureEditable&&tool==="edit"&&selected&&!selected.archived&&selected.geometry.type==="polygon"&&selected.geometry.points.map((p,i)=><g key={p.id} data-feature={selected.id} data-vertex={p.id} data-point-index={i} className={styles.vertex} data-selected={vertexId===p.id}><circle cx={p.x} cy={p.y} r={pointSize} className={styles.hit}/><circle cx={p.x} cy={p.y} r={pointSize*.35}/></g>)}
        {artEditable&&tool==="edit"&&selectedDrawing&&!selectedDrawing.archived&&(selectedDrawing.type==="terrain"||selectedDrawing.type==="path")&&selectedDrawing.points.map((p,i)=><g key={p.id} data-drawing={selectedDrawing.id} data-vertex={p.id} data-point-index={i} className={styles.vertex} data-selected={vertexId===p.id}><circle cx={p.x} cy={p.y} r={pointSize} className={styles.hit}/><circle cx={p.x} cy={p.y} r={pointSize*.35}/></g>)}
      </svg><p className={styles.coordinateNote}>2000 × 1200 map units · coordinates stay fixed when you zoom or resize</p></div>
      <aside className={styles.inspector} aria-label="Geographic information"><fieldset disabled={pending} className={styles.inspectorFields} ref={inspector}><GenerationHistory value={map.generation}/><MapLayerControls value={presentation} canEdit={canEdit&&!pending&&!formDirty&&!gesturing} onChange={p=>commit({...draft,presentation:p})}/><button className="st-button is-secondary" disabled={exporting||gesturing} onClick={async()=>{setExporting(true);try{await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));if(!exportSvg.current)throw new Error("Export could not be prepared. Your map draft is retained.");await exportMapPng(exportSvg.current,draft.name);setNotice("Image exported. The saved map remains editable.");}catch(failure){setError((failure as Error).message);}finally{setExporting(false);}}}>{exporting?"Exporting...":"Export PNG"}</button>{selectedDrawing&&<DrawingInspector drawing={selectedDrawing} pointId={vertexId} tool={tool} canEdit={!!artEditable} disabled={formDirty||gesturing} onEditFields={editFields} onApplyFields={applyFields} onChange={changeDrawing} onPointId={id=>{if(formDirty&&!window.confirm("Discard the unapplied drawing fields?"))return;discardFields();setVertexId(id||null);}} onNudge={nudge} onOrder={reorderDrawing} onArchive={()=>{if(window.confirm(selectedDrawing.archived?"Restore this drawing?":"Archive this drawing? Its editable source is retained."))changeDrawing({...selectedDrawing,archived:!selectedDrawing.archived});}}/>}{selectedDrawing&&linkedGeography&&<div className={styles.pointPanel}><p>Linked {linkedGeography.kind} · {linkedGeography.name} · stable geography {linkedGeography.id.slice(0,8)}</p>{artEditable&&<form key={`${linkedGeography.id}:${linkedGeography.name}`} onChange={editFields} onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);commit({...draft,geographies:draft.geographies.map(g=>g.id===linkedGeography.id?{...g,name:String(fields.get("name")).trim()}:g)});applyFields(e);}}><GuidedField label="Linked geography name" help="Rename this stable place in the World. Other maps linked to it use the same geography; independent label text remains separately editable."><input className="st-control" name="name" required maxLength={160} defaultValue={linkedGeography.name}/></GuidedField><button className="st-button is-secondary">Apply linked geography</button></form>}</div>}<h3>{geography?.name??(selectedDrawing?"Linked geography":"Geographic information")}</h3>{selected&&geography?<><p>{geography.kind}{selected.archived?" · archived feature":""} · stable geography {geography.id.slice(0,8)}</p>
        {featureEditable?<form key={`${selected.id}:${geography.name}:${geography.description}:${geography.parentId}`} onChange={editFields} onSubmit={e=>{e.preventDefault();applyFields(e);const fields=new FormData(e.currentTarget),next={...historyRef.current.present,geographies:historyRef.current.present.geographies.map(g=>g.id===geography.id?{...g,name:String(fields.get("name")).trim(),description:String(fields.get("description")),parentId:String(fields.get("parentId"))||null}:g)};commit(next);setNotice("Geography updated in your map draft. Save the map to persist it.");}}><GuidedField label="Feature name" help="Rename the shared geography record. Other maps linked to this place will use the same name."><input className="st-control" name="name" required maxLength={160} defaultValue={geography.name}/></GuidedField><GuidedField label="Geographic description" help="Describe this place's climate, terrain or history. Saving changes updates its stable World record."><textarea className="st-control" name="description" maxLength={12000} rows={3} defaultValue={geography.description}/></GuidedField><GuidedField label="Within geography" help="Optionally associate this place with a parent in this World. Circular relationships are refused."><select className="st-control" name="parentId" defaultValue={geography.parentId??""}><option value="">No parent</option>{[...geographies,...draft.geographies.filter(g=>!geographies.some(n=>n.id===g.id))].filter(g=>g.id!==geography.id&&(!("archived"in g)||!g.archived||g.id===geography.parentId)).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField><button className="st-button is-secondary">Apply geography changes</button></form>:<p>{geography.description||"No description recorded."}</p>}
        {featureEditable&&!selected.archived&&tool==="edit"&&selected.geometry.type==="polygon"&&<div className={styles.pointPanel}><GuidedField label="Boundary point" help="Choose a point, then adjust its coordinates, insert a midpoint after it, or remove it. An outline needs at least three points."><select className="st-control" value={vertexId??""} onChange={e=>{if(formDirty&&!window.confirm("Discard the unapplied information fields?"))return;discardFields();setVertexId(e.target.value||null);}}><option value="">Choose a point</option>{selected.geometry.points.map((p,i)=><option key={p.id} value={p.id}>Point {i+1} · {p.x}, {p.y}</option>)}</select></GuidedField>{selectedVertex&&<form key={`${selectedVertex.id}:${selectedVertex.x}:${selectedVertex.y}`} onChange={editFields} onSubmit={e=>{e.preventDefault();applyFields(e);const f=new FormData(e.currentTarget);if(selected.geometry.type!=="polygon")return;const geometry={...selected.geometry,points:selected.geometry.points.map(p=>p.id===vertexId?{...p,x:Number(f.get("x")),y:Number(f.get("y"))}:p)};try{validateGeometry(geometry);changeGeometry(selected.id,geometry);}catch(failure){editFields(e);setError((failure as Error).message);}}}><div className={styles.coordinates}><GuidedField label="Point X" help="Horizontal map units from the left edge, between 0 and 2000."><input className="st-control" type="number" name="x" min={0} max={MAP_WIDTH} step=".01" required defaultValue={selectedVertex.x}/></GuidedField><GuidedField label="Point Y" help="Vertical map units from the top edge, between 0 and 1200."><input className="st-control" type="number" name="y" min={0} max={MAP_HEIGHT} step=".01" required defaultValue={selectedVertex.y}/></GuidedField></div><button className="st-button is-secondary">Apply point position</button></form>}{selectedVertex&&<div className={styles.actions}><button className="st-button is-secondary" disabled={formDirty} onClick={()=>{if(selected.geometry.type!=="polygon")return;const points=[...selected.geometry.points],index=points.findIndex(p=>p.id===vertexId),a=points[index],b=points[(index+1)%points.length],id=crypto.randomUUID();points.splice(index+1,0,{id,x:rounded((a.x+b.x)/2),y:rounded((a.y+b.y)/2)});const geometry={...selected.geometry,points};try{validateGeometry(geometry);changeGeometry(selected.id,geometry);setVertexId(id);}catch(failure){setError((failure as Error).message);}}}>Add point after</button><button className="st-button is-danger" disabled={formDirty||selected.geometry.points.length<=3} onClick={()=>{if(selected.geometry.type!=="polygon")return;const geometry={...selected.geometry,points:selected.geometry.points.filter(p=>p.id!==vertexId)};try{validateGeometry(geometry);changeGeometry(selected.id,geometry);setVertexId(null);}catch(failure){setError((failure as Error).message);}}}>Remove point</button></div>}</div>}
        {featureEditable&&!selected.archived&&(tool==="move"||(tool==="edit"&&selectedVertex))&&<div className={styles.nudges}><p>Move {tool==="edit"?"this point":"this feature"} by 10 map units</p>{[["Left",-10,0],["Up",0,-10],["Down",0,10],["Right",10,0]].map(([label,x,y])=><button key={String(label)} className="st-button is-secondary" disabled={formDirty} onClick={()=>nudge(Number(x),Number(y))}>{label}</button>)}</div>}
        {featureEditable&&<button className="st-button is-danger" disabled={formDirty||gesturing} onClick={()=>{if(window.confirm(selected.archived?"Restore this feature to the map?":"Archive this feature? Its geography and boundary points will be retained, and you can undo or restore it."))commit({...draft,features:draft.features.map(f=>f.id===selected.id?{...f,archived:!f.archived}:f)});}}>{selected.archived?"Restore feature":"Archive feature"}</button>}
      </>:<p>Choose a landmass or location from the map or the list below. Its description and editing controls will appear here.</p>}
      <h4>Map features</h4><div className={styles.featureList}>{draft.features.map(f=><button disabled={!presentation.layers[f.geometry.type==="polygon"?"land":"symbols"].visible||presentation.layers[f.geometry.type==="polygon"?"land":"symbols"].locked} key={f.id} className="st-button is-secondary" aria-pressed={selectedId===f.id} onClick={()=>{if(formDirty&&!window.confirm("Discard the unapplied information fields?"))return;discardFields();setSelectedId(f.id);setVertexId(null);}}>{draft.geographies.find(g=>g.id===f.geographyId)?.name}{f.archived?" · archived":""}</button>)}{!draft.features.length&&<p>No geography drawn yet.</p>}</div><h4>Cartographic drawings</h4><div className={styles.featureList}>{(draft.drawings??[]).map(d=><button key={d.id} className="st-button is-secondary" aria-pressed={selectedId===d.id} disabled={!presentation.layers[drawingLayer(d)].visible||presentation.layers[drawingLayer(d)].locked} onClick={()=>{if(formDirty&&!window.confirm("Discard the unapplied drawing fields?"))return;discardFields();setSelectedId(d.id);setVertexId(null);}}>{d.name}{d.archived?" ? archived":""}</button>)}{!draft.drawings?.length&&<p>No terrain or artwork yet.</p>}</div>
      {canEdit&&<details><summary>Map information</summary><form key={`${draft.name}:${draft.description}:${draft.scope}`} onChange={editFields} onSubmit={e=>{e.preventDefault();applyFields(e);const fields=new FormData(e.currentTarget);commit({...draft,name:String(fields.get("name")).trim(),description:String(fields.get("description")),scope:String(fields.get("scope")) as MapDraft["scope"]});}}><GuidedField label="Map title" help="Name this visual representation. Geography records keep their own names."><input className="st-control" required maxLength={160} name="name" defaultValue={draft.name}/></GuidedField><GuidedField label="Map description" help="Describe what this map covers and how you intend to use it."><textarea className="st-control" name="description" maxLength={12000} defaultValue={draft.description}/></GuidedField><GuidedField label="Map scope" help="A library label for world, continent, regional or local maps. It does not set physical distances."><select className="st-control" name="scope" defaultValue={draft.scope}>{["world","continent","regional","local"].map(s=><option key={s}>{s}</option>)}</select></GuidedField><button className="st-button is-secondary">Apply map information</button></form></details>}
      </fieldset></aside></div>
  </section>;
}
