"use client";
import { useEffect, useState } from "react";
import { CalendarDays, Plus } from "lucide-react";
import { type CalendarBundle } from "./calendar";
import { CalendarEditor, type CalendarEditorTarget } from "./calendar-editor";
import { CalendarPreview } from "./calendar-preview";
import { SaveError, worldApi } from "./client-api";
import styles from "./calendar.module.css";
import shared from "./worlds.module.css";

export function CalendarWorkspace({worldId,review,onWorldChange}:{worldId:string;review:boolean;onWorldChange:()=>Promise<unknown>}){
  const api=`/api/worlds/${worldId}/calendars`,[bundle,setBundle]=useState<CalendarBundle|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[editor,setEditor]=useState<CalendarEditorTarget|null>(null),[showArchived,setShowArchived]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{let alive=true;worldApi<CalendarBundle>(`${api}${review?"?review=1":""}`).then(fresh=>{if(alive){setBundle(fresh);setSelectedId(fresh.defaultVersionId??fresh.versions.find(version=>!version.archived)?.id??null);}}).catch(failure=>{if(alive)setError(failure.message);});return()=>{alive=false;};},[api,review]);
  async function reload(){const fresh=await worldApi<CalendarBundle>(`${api}${review?"?review=1":""}`);setBundle(fresh);return fresh;}
  async function action(body:unknown,message:string){setPending(true);setError("");try{await worldApi(api,"POST",body);setNotice(message);try{await reload();await onWorldChange();}catch(failure){setError(failure instanceof Error?`Saved successfully. ${failure.message}`:"Saved; reload to see it.");}}catch(failure){setError(failure instanceof Error?failure.message:"Could not save.");}finally{setPending(false);}}
  const version=bundle?.versions.find(item=>item.id===selectedId),calendar=bundle?.calendars.find(item=>item.id===version?.calendarId),canEdit=!!bundle?.canEdit;
  if(!bundle)return <section className={styles.workspace} aria-label="World calendars"><h2>Calendars</h2>{error?<div role="alert" className={styles.feedback}><p>{error}</p><button className="st-button is-secondary" onClick={()=>reload().then(()=>setError("")).catch(failure=>setError(failure.message))}>Reload calendars</button></div>:<p>Opening the calendar archive…</p>}</section>;
  return <section className={styles.workspace} aria-label="World calendars">
    <div className={shared.sectionHeading}><div><p className={shared.eyebrow}>The shape of a year</p><h2>Calendars</h2><p className={shared.muted}>Build the months, weeks and observances that give time its names.</p></div>{canEdit&&<button className="st-button" disabled={pending} onClick={()=>setEditor({kind:"create"})}><Plus size={17}/>New calendar</button>}</div>
    {error&&<div role="alert" className={styles.feedback}><p>{error}</p><button className="st-button is-secondary" onClick={()=>reload().then(()=>setError("")).catch(failure=>setError(failure.message))}>Reload calendars</button></div>}{notice&&<p role="status" className={shared.notice}>{notice}</p>}
    <label className={styles.archiveToggle}><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Include archived calendars</label>
    <div className={styles.gallery}>{bundle.calendars.filter(item=>showArchived||!item.archived).map(item=>{const versions=bundle.versions.filter(v=>v.calendarId===item.id),chosen=versions.find(v=>v.id===bundle.defaultVersionId)??versions.findLast(v=>!v.archived)??versions.at(-1)!;return <article className={styles.calendarCard} key={item.id} data-selected={item.id===calendar?.id} data-archived={item.archived}><div className={styles.cardIcon}><CalendarDays size={32}/><span>{chosen.rules.months.length} / {chosen.rules.weekdays.length}</span></div><div><p className={styles.eyebrow}>{item.archived?"Archived tradition":"Calendar tradition"}{chosen.id===bundle.defaultVersionId?" · default":""}</p><h3>{item.name}</h3><p>{item.description||"A year shaped by its people."}</p><small>{versions.length} saved {versions.length===1?"definition":"definitions"} · {chosen.rules.months.length} months · {chosen.rules.weekdays.length}-day weeks</small></div><button className="st-button is-secondary" onClick={()=>setSelectedId(chosen.id)}>Open {item.name}</button></article>;})}</div>
    {!bundle.calendars.length&&<div className={styles.empty}><CalendarDays size={44}/><h3>A year waiting to take shape</h3><p>Create a calendar with your own months and weekdays, then explore its actual dates. Existing World history and year reckonings remain available without a calendar.</p></div>}
    {version&&calendar&&<section className={styles.selected} aria-label="Selected calendar"><div className={styles.selectedHeading}><div><p className={styles.eyebrow}>Calendar archive</p><h2>{calendar.name}</h2><p>{calendar.description}</p>{calendar.context&&<details><summary>Cultural context</summary><p className={styles.prose}>{calendar.context}</p></details>}</div><label className="st-field">Rules version<select className="st-control" aria-label="Rules version" value={version.id} onChange={e=>setSelectedId(e.target.value)}>{bundle.versions.filter(item=>item.calendarId===calendar.id).map(item=><option key={item.id} value={item.id}>{item.title}{item.archived?" (archived)":""}</option>)}</select></label></div>
      <p className={styles.caption}>Saved structures are immutable. Revising creates a separate definition and preserves every earlier year.</p>
      {canEdit&&<div className={styles.actions}><button className="st-button is-secondary" disabled={pending||calendar.archived} onClick={()=>setEditor({kind:"identity",calendar,version})}>Edit calendar identity</button><button className="st-button" disabled={pending||calendar.archived||version.archived} onClick={()=>setEditor({kind:"rules",calendar,version})}>Revise calendar rules</button>{bundle.defaultVersionId!==version.id&&<button className="st-button is-secondary" disabled={pending||calendar.archived||version.archived} onClick={()=>action({action:"default",revision:bundle.worldRevision,versionId:version.id},"Preferred calendar saved. This does not establish historical adoption.")}>Use as preferred calendar</button>}{bundle.defaultVersionId===version.id&&<button className="st-button is-secondary" disabled={pending} onClick={()=>action({action:"default",revision:bundle.worldRevision,versionId:null},"Calendar preference cleared.")}>Clear preferred calendar</button>}<button className="st-button is-ghost" disabled={pending||bundle.defaultVersionId===version.id} onClick={()=>action({action:version.archived?"restore-version":"archive-version",id:version.id,revision:version.revision},version.archived?"Rules version restored.":"Rules version archived; its definition is retained.")}>{version.archived?"Restore rules version":"Archive rules version"}</button><button className="st-button is-ghost" disabled={pending||bundle.versions.some(item=>item.calendarId===calendar.id&&item.id===bundle.defaultVersionId)} onClick={()=>action({action:calendar.archived?"restore":"archive",id:calendar.id,revision:calendar.revision},calendar.archived?"Calendar restored.":"Calendar archived; its definitions are retained.")}>{calendar.archived?"Restore calendar":"Archive calendar"}</button></div>}
      {(calendar.archived||version.archived)&&<p className={styles.caption}>Archived definitions remain readable. Restore before creating new uses.</p>}
      <CalendarPreview key={version.id} rules={version.rules}/>
    </section>}
    {editor&&<CalendarEditor key={`${editor.kind}:${editor.calendar?.id??"new"}:${editor.calendar?.revision??0}`} target={editor} onClose={()=>setEditor(null)} onReload={async()=>{const fresh=await reload(),current=fresh.calendars.find(item=>item.id===editor.calendar?.id);if(!current)throw new SaveError("This calendar is unavailable. Your draft is retained.",404);setEditor({...editor,calendar:current,version:fresh.versions.find(item=>item.id===editor.version?.id)});}} onSave={async body=>{const result=await worldApi<{id:string}>(api,"POST",body);setEditor(null);setNotice("Calendar saved to your World.");if(editor.kind!=="identity")setSelectedId(result.id);try{await reload();await onWorldChange();}catch(failure){setError(failure instanceof Error?`Saved successfully. ${failure.message}`:"Saved; reload to see it.");}}}/>}
  </section>;
}
