"use client";
import { useEffect, useRef, useState } from "react";
import { X } from "lucide-react";
import type { CalendarBundle } from "./calendar";
import type { EntryRecord } from "./history";
import { emptyPeriod, historicalPeriod, type AdoptionDraft, type ReformDraft } from "./calendar-evolution";
import { CalendarDateFields, initialEndpoint } from "./calendar-date-fields";
import { CalendarPeriodFields } from "./calendar-period-fields";
import { Field } from "./world-field";
import { SaveError } from "./client-api";
import shared from "./worlds.module.css";
import styles from "./calendar.module.css";
export type HistoryMode="origin"|"anchor"|"period"|"adoption"|"reform";
export function CalendarHistoryEditor({mode,bundle,versionId,entries,onClose,onSave,onReload}:{mode:HistoryMode;bundle:CalendarBundle;versionId:string;entries:EntryRecord[];onClose:()=>void;onSave:(body:unknown)=>Promise<void>;onReload:()=>Promise<void>}){
  const dialog=useRef<HTMLDialogElement>(null),[label,setLabel]=useState(""),[description,setDescription]=useState(""),[elapsed,setElapsed]=useState("0"),[point,setPoint]=useState(()=>initialEndpoint(bundle,versionId)),[period,setPeriod]=useState(()=>bundle.evolution.histories.find(item=>item.versionId===versionId)?.period??emptyPeriod()),[adoption,setAdoption]=useState<AdoptionDraft>({label:"",versionId,period:emptyPeriod()});
  const next=bundle.versions.find(item=>item.id!==versionId&&!item.archived&&!bundle.calendars.find(c=>c.id===item.calendarId)?.archived)?.id??versionId;
  const [reform,setReform]=useState<ReformDraft>({name:"",predecessorId:versionId,successorId:next,time:historicalPeriod("undated"),reason:"",details:"",entryId:null,cutover:null});
  const [pending,setPending]=useState(false),[error,setError]=useState(""),[conflict,setConflict]=useState(false),[discard,setDiscard]=useState(false);
  const draft=JSON.stringify({label,description,elapsed,point,period,adoption,reform}),[initial]=useState(draft),dirty=draft!==initial;
  useEffect(()=>{dialog.current?.showModal();},[]);useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  const titles={origin:"Establish the shared day origin",anchor:"Anchor this calendar version",period:"Historical effective period",adoption:"Record calendar adoption",reform:"Record a calendar reform"};
  function close(){if(pending)return;if(dirty)setDiscard(true);else onClose();}
  const versionSelect=(key:"predecessorId"|"successorId",text:string)=><Field label={text} help="Select an explicit saved version. Different epochs or repeated printed dates require distinct version identities."><select value={reform[key]} onChange={e=>setReform({...reform,[key]:e.target.value,cutover:null})}>{bundle.versions.filter(item=>!item.archived&&!bundle.calendars.find(c=>c.id===item.calendarId)?.archived).map(item=><option key={item.id} value={item.id}>{bundle.calendars.find(c=>c.id===item.calendarId)?.name} · {item.title} · {item.id.slice(0,8)}</option>)}</select></Field>;
  return <dialog ref={dialog} className={shared.editor} aria-labelledby="calendar-history-title" onCancel={e=>{e.preventDefault();close();}}><header className={shared.editorHeader}><h2 id="calendar-history-title">{titles[mode]}</h2><button type="button" className="st-button is-ghost" aria-label="Close calendar history editor" disabled={pending} onClick={close}><X size={20}/></button></header><form onSubmit={async e=>{e.preventDefault();setPending(true);setError("");setConflict(false);try{await onSave(mode==="origin"?{action:mode,label,description}:mode==="anchor"?{action:mode,endpoint:point,elapsedDay:elapsed,sameDayUnit:true}:mode==="period"?{action:mode,versionId,revision:bundle.evolution.histories.find(item=>item.versionId===versionId)?.revision??null,period}:mode==="adoption"?{action:mode,draft:adoption}:{action:mode,draft:reform});}catch(failure){setError((failure as Error).message);setConflict(failure instanceof SaveError&&failure.status===409);}finally{setPending(false);}}}><fieldset disabled={pending} className={`${shared.editorFields} ${styles.editorFields}`}>
    {mode==="origin"&&<><p className={styles.caption}>Define elapsed day 0 and what one shared day means. This origin becomes immutable. Canonical World years are a separate reference.</p><Field label="Day reference name" help="Name the world's shared elapsed-day reference."><input autoFocus required maxLength={160} value={label} onChange={e=>setLabel(e.target.value)}/></Field><Field label="Origin and day meaning" help="Describe the historical origin of day 0 and the common day unit. Do not assume Earth's day or any standard year length."><textarea required rows={5} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></Field></>}
    {mode==="anchor"&&<><p className={styles.caption}>Associate one printed date with one elapsed day. The anchor is immutable; a new epoch needs a separate version.</p><CalendarDateFields bundle={bundle} value={point} onChange={setPoint} label="Anchor" locked/><Field label="Anchor elapsed day" help="A signed whole day relative to the authored origin, with at most twenty digits. Negative values precede the origin."><input required inputMode="numeric" value={elapsed} onChange={e=>setElapsed(e.target.value)}/></Field><Field label="Confirm common day unit" help="Exact conversion requires every ordinary and inserted day in this version to represent one shared elapsed day. Optional hours/minutes do not establish that relationship."><input required type="checkbox"/></Field></>}
    {mode==="period"&&<><CalendarPeriodFields label="Effective" value={period.time} onChange={time=>setPeriod({...period,time,continues:time.kind==="duration"?false:period.continues})}/><Field label="Effective period has no recorded end" help="Treat the stated date or window as a beginning with an unknown ending. This never supplies an exact day."><input type="checkbox" disabled={period.time.kind==="duration"} checked={period.continues} onChange={e=>setPeriod({...period,continues:e.target.checked})}/></Field><Field label="Effective period context" help="Explain when this version was effective. Unknown boundaries stay unknown; this context never rewrites historical dates."><textarea rows={4} maxLength={4000} value={period.notes} onChange={e=>setPeriod({...period,notes:e.target.value})}/></Field></>}
    {mode==="adoption"&&<><Field label="Adopting people or institution" help="An authored label for a people, civilization, institution or region. It is not a new Faction or Geography record."><input autoFocus required maxLength={160} value={adoption.label} onChange={e=>setAdoption({...adoption,label:e.target.value})}/></Field><p className={styles.caption}>This adoption uses the selected rule version. Other calendars may coexist.</p><CalendarPeriodFields label="Adoption" value={adoption.period.time} onChange={time=>setAdoption({...adoption,period:{...adoption.period,time,continues:time.kind==="duration"?false:adoption.period.continues}})}/><Field label="Adoption has no recorded end" help="The stated beginning may be known, approximate or uncertain. The ending remains unknown."><input type="checkbox" disabled={adoption.period.time.kind==="duration"} checked={adoption.period.continues} onChange={e=>setAdoption({...adoption,period:{...adoption.period,continues:e.target.checked}})}/></Field><Field label="Adoption context" help="Optional usage and transition details, including any unknown beginning or ending."><textarea rows={3} maxLength={4000} value={adoption.period.notes} onChange={e=>setAdoption({...adoption,period:{...adoption.period,notes:e.target.value}})}/></Field></>}
    {mode==="reform"&&<><Field label="Reform name" help="Name the historical change between two saved versions."><input autoFocus required maxLength={160} value={reform.name} onChange={e=>setReform({...reform,name:e.target.value})}/></Field><div className={styles.columns}>{versionSelect("predecessorId","Predecessor version")}{versionSelect("successorId","Successor version")}</div><CalendarPeriodFields label="Reform effective" value={reform.time} onChange={time=>setReform({...reform,time})}/><Field label="Reason for reform" help="Explain why the structure, names or epoch changed. Rules and earlier history remain intact."><textarea required rows={3} maxLength={4000} value={reform.reason} onChange={e=>setReform({...reform,reason:e.target.value})}/></Field><Field label="Linked History entry" help="Reference an existing historical account without copying its narrative. Planned developments remain planned."><select value={reform.entryId??""} onChange={e=>setReform({...reform,entryId:e.target.value||null})}><option value="">No linked entry</option>{entries.filter(entry=>!entry.archived).map(entry=><option value={entry.id} key={entry.id}>{entry.title}{entry.narrative==="planned"?" (planned)":""}</option>)}</select></Field><Field label="Transition and adoption details" help="Optional cultural or transition context. This does not imply universal adoption."><textarea rows={3} maxLength={4000} value={reform.details} onChange={e=>setReform({...reform,details:e.target.value})}/></Field><details><summary>Optional exact cutover</summary><Field label="Specify consecutive cutover dates" help="Use only when both versions are anchored. The new version's first date must be exactly one shared day after the old version's last date. A year-only account cannot infer this."><input type="checkbox" checked={!!reform.cutover} onChange={e=>setReform({...reform,cutover:e.target.checked?{before:initialEndpoint(bundle,reform.predecessorId),after:initialEndpoint(bundle,reform.successorId)}:null})}/></Field>{reform.cutover&&<><CalendarDateFields bundle={bundle} value={reform.cutover.before} label="Last old date" locked onChange={before=>setReform({...reform,cutover:{...reform.cutover!,before}})}/><CalendarDateFields bundle={bundle} value={reform.cutover.after} label="First new date" locked onChange={after=>setReform({...reform,cutover:{...reform.cutover!,after}})}/></>}</details></>}
  </fieldset>{error&&<div role="alert" className={styles.feedback}><p>{error}</p>{conflict&&<button type="button" className="st-button is-secondary" disabled={pending} onClick={async()=>{if(!window.confirm("Discard this draft and load the latest calendar history?"))return;try{await onReload();}catch(failure){setError((failure as Error).message);}}}>Load latest calendar history</button>}</div>}{discard&&<div role="alert" className={styles.feedback}><p>Discard this historical calendar draft?</p><button type="button" className="st-button is-secondary" onClick={()=>setDiscard(false)}>Keep writing</button><button type="button" className="st-button is-danger" onClick={onClose}>Discard draft</button></div>}<footer className={shared.editorFooter}><span>{dirty?"Unsaved draft":""}</span><div className={styles.actions}><button type="button" className="st-button is-secondary" disabled={pending} onClick={close}>Cancel</button><button className="st-button" disabled={pending}>{pending?"Saving…":"Save calendar history"}</button></div></footer></form></dialog>;
}
