"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { nextYear, yearDays, type CalendarRules, type CalendarDay } from "./calendar";
import { YEAR_LIMIT } from "./history";
import { Field } from "./world-field";
import styles from "./calendar.module.css";

export function CalendarPreview({rules}:{rules:CalendarRules}){
  const [year,setYear]=useState(rules.numbering==="year-zero"?0:1),[raw,setRaw]=useState(String(year)),[month,setMonth]=useState(1),[selected,setSelected]=useState<CalendarDay|null>(null),[error,setError]=useState("");
  const days=useMemo(()=>yearDays(rules,year),[rules,year]);
  const monthIndex=Math.min(month,rules.months.length),visible=days.filter(day=>day.month===monthIndex);
  function move(delta:number){try{const value=nextYear(rules,year,delta);setYear(value);setRaw(String(value));setSelected(null);setError("");}catch(failure){setError(failure instanceof Error?failure.message:"Unsupported year.");}}
  function viewYear(){try{const value=Number(raw);if(!raw.trim())throw new Error("Enter a year.");yearDays(rules,value);setYear(value);setSelected(null);setError("");}catch(failure){setError(failure instanceof Error?failure.message:"Enter a supported year.");}}
  const leading=visible.find(day=>day.weekday!==null)?.weekday??0;
  return <section aria-label="Calendar year preview" className={styles.preview}>
    <div className={styles.previewHeading}><div><p className={styles.eyebrow}>A year in this tradition</p><h3>Year {year.toLocaleString("en-US")}</h3><p>{days.length.toLocaleString("en-US")} days · {rules.weekdays.length}-day weeks{rules.timeUnits?` · ${rules.timeUnits.hoursPerDay} hours/day · ${rules.timeUnits.minutesPerHour} minutes/hour`:""}</p></div><div className={styles.yearControls}><button type="button" className="st-button is-secondary" aria-label="Previous calendar year" onClick={()=>move(-1)}><ArrowLeft size={17}/></button><button type="button" className="st-button is-secondary" aria-label="Next calendar year" onClick={()=>move(1)}><ArrowRight size={17}/></button></div></div>
    <div className={styles.jump}><Field label="Preview calendar year" help="Navigate authored calendar years independently of canonical World years. Whole years within minus one trillion through one trillion are supported; zero is rejected when excluded."><input type="number" step={1} min={-YEAR_LIMIT} max={YEAR_LIMIT} required value={raw} onChange={event=>setRaw(event.target.value)} onKeyDown={event=>{if(event.key === "Enter"){event.preventDefault();viewYear();}}}/></Field><button type="button" className="st-button is-secondary" onClick={viewYear}>View year</button></div>
    {error&&<p role="alert" className={styles.feedback}>{error}</p>}
    <div className={styles.monthGallery} aria-label="Months in this year">{rules.months.map((item,index)=><button type="button" key={index} className={styles.monthTile} aria-pressed={monthIndex===index+1} onClick={()=>{setMonth(index+1);setSelected(null);}}><span>{String(index+1).padStart(2,"0")}</span><strong>{item.name}</strong><small>{days.filter(day=>day.month===index+1).length} days</small></button>)}</div>
    <div className={styles.monthHeading}><h3>{rules.months[monthIndex-1].name}</h3><p>Ordinary dates retain their numbers. Named extra days appear in order.</p></div>
    <div className={styles.weekScroll}><div className={styles.weekGrid} style={{gridTemplateColumns:`repeat(${rules.weekdays.length},minmax(44px,1fr))`}} aria-label="Weekday arrangement">{rules.weekdays.map((name,index)=><span key={index}>{name}</span>)}{Array.from({length:leading},(_,i)=><span key={`blank-${i}`} aria-hidden="true"/>)}{visible.filter(day=>day.weekday!==null).map(day=><button type="button" key={day.ordinal} className={styles.day} data-season={day.seasons.length>0} data-observed={day.observances.length>0} aria-label={`${day.name}, ${rules.weekdays[day.weekday!]}, ${rules.months[monthIndex-1].name}, Year ${year}${day.observances.length?`. ${day.observances.map(item=>item.name).join(", ")}`:""}`} onClick={()=>setSelected(day)}><strong>{day.name}</strong>{day.seasons.length>0&&<small>{day.seasons.join(" · ")}</small>}{day.observances.length>0&&<span>{day.observances.map(item=>item.name).join(" · ")}</span>}</button>)}</div></div>
    {visible.some(day=>day.weekday===null)&&<section className={styles.extraDays} aria-label="Days outside the week"><h4>Outside the weekday cycle</h4>{visible.filter(day=>day.weekday===null).map(day=><button type="button" className="st-button is-secondary" key={day.ordinal} onClick={()=>setSelected(day)}>{day.name} · after day {day.day}{day.observances.length?` · ${day.observances.map(item=>item.name).join(", ")}`:""}</button>)}</section>}
    {selected&&<aside className={styles.dayDetail} aria-label="Selected calendar day"><button type="button" className="st-button is-ghost" onClick={()=>setSelected(null)}>Close day details</button><h4>{selected.name} · {rules.months[selected.month-1].name}, Year {selected.year.toLocaleString("en-US")}</h4><p>Day {selected.ordinal} of {days.length} · {selected.weekday===null?"Outside the week":rules.weekdays[selected.weekday]}</p>{selected.seasons.length>0&&<p>Seasons: {selected.seasons.join(", ")}</p>}{selected.observances.map((item,index)=><div key={index}><strong>{item.name}</strong><p>{item.kind} {item.description&&`· ${item.description}`}</p></div>)}</aside>}
    <details className={styles.yearAgenda}><summary>Seasons and observances throughout this year</summary>{rules.seasons.map((season,index)=><p key={index}><strong>{season.name}</strong> · {rules.months[season.start.month-1].name} {season.start.day} through {rules.months[season.end.month-1].name} {season.end.day}{season.description&&` · ${season.description}`}</p>)}{days.filter(day=>day.observances.length>0).map(day=><button type="button" key={day.ordinal} className={styles.agendaItem} onClick={()=>{setMonth(day.month);setSelected(day);}}><span>{rules.months[day.month-1].name} · {day.name}</span><strong>{day.observances.map(item=>item.name).join(", ")}</strong></button>)}{!rules.seasons.length&&!days.some(day=>day.observances.length>0)&&<p>No seasons or observances occur in this year.</p>}</details>
    <p className={styles.caption}>Calendar browsing changes your view only. It never advances Campaign time. Weekdays follow the authored {rules.progression.replaceAll("-"," ")} rule.</p>
  </section>;
}
