"use client";
import { useEffect, useState } from "react";
import type { CalendarBundle } from "./calendar";
import type { CalendarEntryDraft, CalendarSource } from "./calendar-dates";
import { CalendarDateFields, initialEndpoint } from "./calendar-date-fields";
import { Field } from "./world-field";
import { worldApi } from "./client-api";
import styles from "./calendar.module.css";
export function draftFromSource(source:CalendarSource):CalendarEntryDraft{const start={versionId:source.start.versionId,revision:source.start.revision,date:source.start.date};return source.kind==="window"||source.kind==="duration"?{kind:source.kind,start,end:{versionId:source.end!.versionId,revision:source.end!.revision,date:source.end!.date}}:{kind:source.kind,start};}
export function CalendarEntryFields({worldId,value,onChange}:{worldId:string;value:CalendarEntryDraft|null|undefined;onChange:(value:CalendarEntryDraft|null)=>void}){
  const [bundle,setBundle]=useState<CalendarBundle|null>(null),[error,setError]=useState("");
  useEffect(()=>{let alive=true;worldApi<CalendarBundle>(`/api/worlds/${worldId}/calendars`).then(result=>{if(alive)setBundle(result);}).catch(failure=>{if(alive)setError(failure.message);});return()=>{alive=false;};},[worldId]);
  return <details className={styles.evolution} open={!!value}><summary>Original calendar date</summary><p className={styles.caption}>Optional calendar context uses explicit anchored versions. It does not change canonical years, infer days for old accounts, or promote their precision. Without an authored World-year relationship, an exact calendar date can remain outside the year timeline.</p>{error&&<p role="alert">{error}</p>}{!bundle&&!error&&<p>Opening calendar definitions…</p>}{bundle&&<><Field label="Calendar date precision" help="Known day, approximate day, uncertain occurrence window or a duration remain distinct. Selecting No calendar date explicitly clears retained calendar context. Canonical World-year precision stays unchanged."><select value={value?.kind??"none"} onChange={e=>{const kind=e.target.value as CalendarEntryDraft["kind"]|"none";if(kind==="none"){onChange(null);return;}const available=bundle.versions.find(item=>!item.archived&&!bundle.calendars.find(c=>c.id===item.calendarId)?.archived&&bundle.evolution.anchors.some(a=>a.versionId===item.id));const start=value?.start??(available?initialEndpoint(bundle,available.id):null);if(!start)return;onChange(kind==="window"||kind==="duration"?{kind,start,end:value&&"end"in value?value.end:start}:{kind,start});}}><option value="none">No calendar date</option>{["known","approximate","window","duration"].map(kind=><option key={kind} value={kind} disabled={!value&&!bundle.versions.some(item=>!item.archived&&!bundle.calendars.find(c=>c.id===item.calendarId)?.archived&&bundle.evolution.anchors.some(a=>a.versionId===item.id))}>{kind==="known"?"Known day":kind==="approximate"?"Approximate day":kind==="window"?"Uncertain occurrence window":"Known duration"}</option>)}</select></Field>{!bundle.evolution.anchors.length&&<p className={styles.caption}>Establish a shared day origin and version anchor in Calendars before authoring a precise date.</p>}{value&&<><CalendarDateFields bundle={bundle} value={value.start} label="Source" onChange={start=>onChange({...value,start})}/>{"end"in value&&<CalendarDateFields bundle={bundle} value={value.end} label="Source end" onChange={end=>onChange({...value,end})}/>}</>}</>}</details>;
}
