"use client";
import { useEffect, useState } from "react";
import { dateLabel, type CalendarBundle } from "./calendar";
import { fromElapsed, sourceLabel, type CalendarSource } from "./calendar-dates";
import { worldApi } from "./client-api";
import { Field } from "./world-field";
import styles from "./calendar.module.css";
export function CalendarSourceDetails({source,worldId,review}:{source:CalendarSource;worldId:string;review:boolean}){
  const [bundle,setBundle]=useState<CalendarBundle|null>(null),[target,setTarget]=useState(""),[error,setError]=useState("");
  useEffect(()=>{let alive=true;worldApi<CalendarBundle>(`/api/worlds/${worldId}/calendars${review?"?review=1":""}`).then(result=>{if(alive)setBundle(result);}).catch(failure=>{if(alive)setError(failure.message);});return()=>{alive=false;};},[worldId,review]);
  let equivalent="",limitation="";if(bundle&&target){try{const version=bundle.versions.find(v=>v.id===target)!;const anchor=bundle.evolution.anchors.find(a=>a.versionId===target);equivalent=[source.start,...(source.end?[source.end]:[])].map(point=>dateLabel(version.rules,fromElapsed(version.rules,anchor,point.elapsedDay))).join(source.kind==="window"?" and ":" through ");}catch(failure){limitation=(failure as Error).message;}}
  return <aside className={styles.dayDetail} aria-label="Original calendar context"><h3>Original calendar context</h3><p>{sourceLabel(source)}</p>{[source.start,...(source.end?[source.end]:[])].map((point,i)=><p key={i}>{point.calendarName} · {point.versionTitle} · {point.versionId.slice(0,8)}<br/>Month {point.date.month}{point.date.intercalaryId?" · named intercalary occurrence":""} · elapsed day {point.elapsedDay}</p>)}<p className={styles.caption}>{source.kind==="known"?"Known calendar day.":source.kind==="approximate"?"Approximate occurrence; the stored day is the authored estimate.":source.kind==="window"?"An occurrence somewhere inside these calendar boundaries.":"A duration spanning these calendar boundaries."} Canonical World-year context is independent; no mapping or timeline position is inferred.</p>{bundle&&<Field label="Compare original calendar date using" help="Compare the saved notation or boundaries in another explicitly anchored version. The account's original precision and position stay unchanged."><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Original notation</option>{bundle.versions.map(v=><option value={v.id} key={v.id}>{bundle.calendars.find(c=>c.id===v.calendarId)?.name} · {v.title} · {v.id.slice(0,8)}</option>)}</select></Field>}{equivalent&&<p role="status">Equivalent {source.kind==="known"?"date notation":source.kind==="approximate"?"estimated notation":"boundaries"}: {equivalent}</p>}{(limitation||error)&&<p role="alert">{limitation||error}</p>}</aside>;
}
