import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { acceptSavedHistory, commitAction, undoAction, redoAction, polygonCenter, validateGeometry, type Geometry, type MapDraft } from "./atlas";
import { detailCoastline, prepareSculpt, sculptCoastline, simplifyTrace, smoothCoastline } from "./coastline";
import { defaultPresentation, drawingSchema, moveDrawing, presentationSchema, strokeSamples, terrainMarks, validateDrawings, type TerrainDrawing } from "./cartography";
const coast=():Extract<Geometry,{type:"polygon"}>=>({version:1,type:"polygon",points:[[100,100],[1000,100],[1000,900],[100,900]].map(([x,y])=>({id:randomUUID(),x,y}))});
const stroke=():TerrainDrawing=>({version:1,id:randomUUID(),name:"Northern range",type:"terrain",kind:"mountains",geographyId:null,archived:false,points:[{id:randomUUID(),x:400,y:300},{id:randomUUID(),x:700,y:400}],radius:60,spacing:40,density:2,seed:12345});
test("coastline smoothing changes real coordinates while preserving every original point ID",()=>{const original=coast(),next=smoothCoastline(original);assert.notDeepEqual(next.points.map(({x,y})=>({x,y})),original.points.map(({x,y})=>({x,y})));assert.deepEqual(next.points.map(p=>p.id),original.points.map(p=>p.id));validateGeometry(next);assert.equal(original.points[0].x,100);});
test("sculpting inserts a local editable section, carves a bay and retains original geography geometry identities",()=>{const original=coast(),start={x:550,y:100},prepared=prepareSculpt(original,start,150,randomUUID),next=sculptCoastline(prepared,start,{x:550,y:260},150);assert.equal(next.points.length,9);assert.ok(next.points.some(p=>p.x===550&&p.y===260));for(const p of original.points)assert.ok(next.points.some(n=>n.id===p.id));validateGeometry(next);assert.throws(()=>prepareSculpt(original,{x:1700,y:1000},30,randomUUID),/near/);assert.equal(original.points.length,4);});
test("irregular detail retains original IDs, respects limits and leaves invalid topology visibly rejectable",()=>{const original=coast(),detailed=detailCoastline(original,20,randomUUID);assert.equal(detailed.points.length,8);for(const p of original.points)assert.ok(detailed.points.some(n=>n.id===p.id));validateGeometry(detailed);assert.throws(()=>detailCoastline({...original,points:Array.from({length:129},(_,i)=>({id:randomUUID(),x:i,y:i}))},20,randomUUID),/128/);assert.throws(()=>validateGeometry(sculptCoastline(original,{x:100,y:100},{x:1000,y:900},10)),/cross|touch|double|distinct|visible area/);});
test("freehand simplification retains the trace endpoints and produces editable source vertices",()=>{const trace=Array.from({length:200},(_,i)=>({id:randomUUID(),x:i*5,y:100+Math.sin(i/20)*20})),simple=simplifyTrace(trace,4);assert.ok(simple.length<trace.length);assert.equal(simple[0].id,trace[0].id);assert.equal(simple.at(-1)!.id,trace.at(-1)!.id);});
test("terrain painting is deterministic source data, bounded in density and editable without changing identity",()=>{const original=stroke();assert.deepEqual(terrainMarks(original),terrainMarks(structuredClone(original)));assert.notDeepEqual(terrainMarks(original),terrainMarks({...original,density:1}));const moved=moveDrawing(original,1900,-900);assert.equal(moved.type,"terrain");if(moved.type!=="terrain")return;assert.equal(moved.id,original.id);assert.deepEqual(moved.points.map(p=>p.id),original.points.map(p=>p.id));assert.equal(moved.points[1].x,2000);assert.equal(moved.points[0].y,0);validateDrawings([moved]);assert.throws(()=>strokeSamples(original.points,0),/positive/);assert.throws(()=>validateDrawings([{...original,points:Array.from({length:128},(_,i)=>({id:randomUUID(),x:i%2?2000:0,y:i*5})),spacing:12,density:3}]),/dense/);});
test("drawing schemas reject flattened or injected artwork and malformed geometry or presentation",()=>{const original=stroke();for(const bad of [{...original,type:"raster",url:"x"},{...original,script:"x"},{...original,seed:0},{...original,density:99},{...original,points:[]},{...original,points:[{id:randomUUID(),x:NaN,y:2}]}])assert.equal(drawingSchema.safeParse(bad).success,false);assert.throws(()=>validateDrawings([{...original,points:[original.points[0],original.points[0]]}]),/identity|distinct/);assert.throws(()=>validateDrawings([{...original,points:[{...original.points[0],x:1.001}]}]),/decimal/);assert.equal(presentationSchema.safeParse({...defaultPresentation(),public:true}).success,false);assert.equal(presentationSchema.safeParse({...defaultPresentation(),layers:{land:{visible:true,locked:false}}}).success,false);});
test("undo/save/redo/save of painted artwork retains saved IDs as archives and restores original editable source",()=>{const empty:MapDraft={name:"Map",description:"",scope:"world",features:[],geographies:[],drawings:[],presentation:defaultPresentation()},painted={...empty,drawings:[stroke()]};let history=commitAction({past:[],present:empty,future:[]},painted);history=acceptSavedHistory(history,painted);history=undoAction(history);assert.equal(history.present.drawings![0].archived,true);assert.equal(history.present.drawings![0].id,painted.drawings[0].id);history=acceptSavedHistory(history,history.present);history=redoAction(history);assert.deepEqual(history.present.drawings,painted.drawings);});

test("automatic continent label centers do not drift when collinear coastline detail is inserted",()=>{const original=coast(),more=[original.points[0],{id:randomUUID(),x:550,y:100},...original.points.slice(1)];assert.deepEqual(polygonCenter(original.points),polygonCenter(more));assert.deepEqual(polygonCenter(original.points),{x:550,y:500});});
