"use client";
import type { FormEvent } from "react";
import { GuidedField } from "@/components/field-guidance";
import { drawingLayer, drawingPoints, layers, symbolKinds, terrainKinds, type MapDrawing, type MapPresentation } from "./cartography";
import type { GeographyRecord, Point } from "./atlas";
import styles from "./atlas.module.css";

export type BrushSettings = { radius:number; spacing:number; density:number; terrain:typeof terrainKinds[number]; path:"river"|"stream"|"road"|"trail"; width:number; curve:number; symbol:typeof symbolKinds[number]; scale:number; rotation:number; text:string; labelSize:number; labelStyle:"place"|"region"|"water"; symbolStyle:"colored"|"ink" };
export const defaultBrush:BrushSettings={radius:65,spacing:35,density:2,terrain:"mountains",path:"river",width:7,curve:.8,symbol:"village",scale:1.1,rotation:0,text:"New label",labelSize:32,labelStyle:"place",symbolStyle:"colored"};
export function CartographyOptions({tool,brush,setBrush}:{tool:string;brush:BrushSettings;setBrush:(b:BrushSettings)=>void}) {
  const number=(key:keyof BrushSettings,label:string,help:string,min:number,max:number,step=1)=><GuidedField key={key} label={label} help={help}><input className="st-control" type="number" min={min} max={max} step={step} value={String(brush[key])} onChange={e=>setBrush({...brush,[key]:Number(e.target.value)})}/></GuidedField>;
  return <div className={styles.brushOptions}>
    {tool==="sculpt"&&number("radius","Coast brush size","The radius, in map units, of the coastline section affected by a drag. Start near the coastline; drag inward for a bay or outward for a peninsula.",20,200)}
    {tool==="paint"&&<><GuidedField label="Terrain brush" help="Each painted stroke remains an editable group. Mountains and trees use original illustrated vector marks; lakes and snow add soft water or snow coverage."><select className="st-control" value={brush.terrain} onChange={e=>setBrush({...brush,terrain:e.target.value as BrushSettings["terrain"]})}>{terrainKinds.map(k=><option key={k} value={k}>{k}</option>)}</select></GuidedField>{number("radius","Brush size","The width and size of the marks in map units. The brush preview shows the affected area.",12,160)}{number("spacing","Mark spacing","Distance between groups of marks. Larger spacing makes a lighter stroke and keeps dense maps responsive.",12,100)}{number("density","Brush density","One to three marks per sampled brush position. This can be changed after painting.",1,3)}</>}
    {tool==="path"&&<><GuidedField label="Path kind" help="Draw an editable river, stream, road or trail by tapping points. Complete path finishes it. Edit points reshapes it later."><select className="st-control" value={brush.path} onChange={e=>setBrush({...brush,path:e.target.value as BrushSettings["path"]})}>{["river","stream","road","trail"].map(k=><option key={k}>{k}</option>)}</select></GuidedField>{number("width","Path width","Line width in map units; this is illustrative and sets no physical distance.",1,24)}{number("curve","Path curvature","Zero joins points directly. Higher values make a flowing curve through the editable points.",0,1,.1)}</>}
    {tool==="symbol"&&<><GuidedField label="Symbol kind" help="Place an original illustrated symbol. Settlements and landmarks link to a stable location; mountains and trees may be decorative."><select className="st-control" value={brush.symbol} onChange={e=>setBrush({...brush,symbol:e.target.value as BrushSettings["symbol"]})}>{symbolKinds.map(k=><option key={k}>{k}</option>)}</select></GuidedField>{number("scale","Symbol scale","Resize this symbol relative to its original illustration. Scale remains editable after placing it.",.4,4,.1)}<GuidedField label="Symbol appearance" help="Colored uses terrain colors; Ink uses the map's paper and ink treatment."><select className="st-control" value={brush.symbolStyle} onChange={e=>setBrush({...brush,symbolStyle:e.target.value as BrushSettings["symbolStyle"]})}><option value="colored">Colored</option><option value="ink">Ink</option></select></GuidedField></>}
    {tool==="label"&&<><GuidedField label="New label text" help="Text placed where you tap. Link a named place when appropriate; decorative regional or water notes may stand alone."><input className="st-control" value={brush.text} maxLength={160} onChange={e=>setBrush({...brush,text:e.target.value})}/></GuidedField>{number("labelSize","Label size","Text size in map units, independent of browser width. You can reposition and restyle it after placement.",12,80)}<GuidedField label="Label appearance" help="Choose a place name, a spaced regional title, or an italic water name."><select className="st-control" value={brush.labelStyle} onChange={e=>setBrush({...brush,labelStyle:e.target.value as BrushSettings["labelStyle"]})}><option value="place">Place</option><option value="region">Region</option><option value="water">Water</option></select></GuidedField></>}
  </div>;
}
export function MapLayerControls({value,canEdit,onChange}:{value:MapPresentation;canEdit:boolean;onChange:(next:MapPresentation)=>void}) {
  return <details className={styles.layers}><summary>Style and layers</summary><p>Hidden layers stay saved. Locked layers cannot be edited. These are editing controls, not sharing permissions.</p><GuidedField label="Map appearance" help="Parchment uses warm paper and ink. Illuminated adds colored water. Night follows the darker site surfaces. All styles keep the same editable data."><select className="st-control" disabled={!canEdit} value={value.style} onChange={e=>onChange({...value,style:e.target.value as MapPresentation["style"]})}><option value="parchment">Parchment</option><option value="illuminated">Illuminated</option><option value="night">Night</option></select></GuidedField><label><input type="checkbox" disabled={!canEdit} checked={value.grid} onChange={e=>onChange({...value,grid:e.target.checked})}/> Show map grid</label><div className={styles.layerRows}>{layers.map(layer=><div key={layer}><span>{layer}</span><label><input type="checkbox" aria-label={`Show ${layer} layer`} disabled={!canEdit} checked={value.layers[layer].visible} onChange={e=>onChange({...value,layers:{...value.layers,[layer]:{...value.layers[layer],visible:e.target.checked}}})}/> Show</label><label><input type="checkbox" aria-label={`Lock ${layer} layer`} disabled={!canEdit} checked={value.layers[layer].locked} onChange={e=>onChange({...value,layers:{...value.layers,[layer]:{...value.layers[layer],locked:e.target.checked}}})}/> Lock</label></div>)}</div></details>;
}
export function DrawingInspector({drawing,pointId,tool,canEdit,disabled,onEditFields,onApplyFields,onChange,onPointId,onNudge,onOrder,onArchive}:{drawing:MapDrawing;pointId:string|null;tool:string;canEdit:boolean;disabled:boolean;onEditFields:(e:FormEvent<HTMLFormElement>)=>void;onApplyFields:(e:FormEvent<HTMLFormElement>)=>void;onChange:(d:MapDrawing)=>boolean;onPointId:(id:string)=>void;onNudge:(x:number,y:number)=>void;onOrder:(direction:number)=>void;onArchive:()=>void}) {
  const points=drawingPoints(drawing),selected=(drawing.type==="path"||drawing.type==="terrain")?drawing.points.find(p=>p.id===pointId):drawing.point;
  const field=(name:string,label:string,help:string,value:number,min:number,max:number,step=.01)=><GuidedField label={label} help={help}><input className="st-control" type="number" name={name} defaultValue={value} min={min} max={max} step={step} required/></GuidedField>;
  return <section className={styles.drawingInspector}><h3>{drawing.name}</h3><p>{drawing.type} · {drawingLayer(drawing)} layer{drawing.archived?" · archived":""}</p>{canEdit&&<form key={JSON.stringify(drawing)} onChange={onEditFields} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),n=(key:string)=>Number(f.get(key));let next:MapDrawing={...drawing,name:String(f.get("name")).trim()};if(next.type==="terrain")next={...next,kind:String(f.get("kind")) as typeof next.kind,radius:n("radius"),spacing:n("spacing"),density:n("density")};if(next.type==="path")next={...next,kind:String(f.get("kind")) as typeof next.kind,width:n("width"),curve:n("curve")};if(next.type==="symbol")next={...next,scale:n("scale"),rotation:n("rotation"),style:String(f.get("style")) as typeof next.style};if(next.type==="label")next={...next,text:String(f.get("text")).trim(),size:n("size"),rotation:n("rotation"),style:String(f.get("style")) as typeof next.style};if(onChange(next))onApplyFields(e);}}><GuidedField label="Drawing name" help="A name used in the editor's drawing list. Label text is edited separately, and linked places retain their geography identity."><input className="st-control" name="name" defaultValue={drawing.name} maxLength={160} required/></GuidedField>
    {drawing.type==="terrain"&&<><GuidedField label="Painted terrain" help="Change this stroke's terrain treatment while keeping its editable brush path and identity."><select className="st-control" name="kind" defaultValue={drawing.kind}>{terrainKinds.map(k=><option key={k}>{k}</option>)}</select></GuidedField>{field("radius","Stroke brush size","Change the size of this group's illustrated marks.",drawing.radius,12,160)}{field("spacing","Stroke spacing","Increase spacing to reduce the number of marks along this stroke.",drawing.spacing,12,100)}{field("density","Stroke density","One to three marks at each sampled position.",drawing.density,1,3,1)}</>}
    {drawing.type==="path"&&<><GuidedField label="Saved path kind" help="Restyle the same editable path as a river, stream, road or trail."><select className="st-control" name="kind" defaultValue={drawing.kind}>{["river","stream","road","trail"].map(k=><option key={k}>{k}</option>)}</select></GuidedField>{field("width","Saved path width","Illustrative line width in map units.",drawing.width,1,24)}{field("curve","Saved path curvature","Zero uses straight joins; higher values create flowing curves through the points.",drawing.curve,0,1,.1)}</>}
    {(drawing.type==="symbol"||drawing.type==="label")&&<>{drawing.type==="symbol"?field("scale","Placed symbol scale","Resize this original symbol without replacing its identity.",drawing.scale,.4,4,.1):<><GuidedField label="Label text" help="Edit the text displayed on the map; this does not rename its linked geography."><input className="st-control" name="text" defaultValue={drawing.text} maxLength={160} required/></GuidedField>{field("size","Placed label size","Text size in fixed map units.",drawing.size,12,80)}</>}{field("rotation","Drawing rotation","Rotate the symbol or text in degrees, clockwise when positive.",drawing.rotation,-180,180,1)}<GuidedField label="Drawing appearance" help="Change the visible treatment while retaining position and identity."><select className="st-control" name="style" defaultValue={drawing.style}>{(drawing.type==="symbol"?["colored","ink"]:["place","region","water"]).map(k=><option key={k}>{k}</option>)}</select></GuidedField></>}
    <button className="st-button is-secondary">Apply drawing changes</button></form>}
    {canEdit&&!drawing.archived&&<>{(drawing.type==="path"||drawing.type==="terrain")&&tool==="edit"&&<GuidedField label="Drawing point" help="Choose a source point to move or reshape this stroke or path. Touch users can use the numeric fields and direction controls."><select className="st-control" value={pointId??""} onChange={e=>onPointId(e.target.value)}><option value="">Choose a point</option>{drawing.points.map((p,i)=><option key={p.id} value={p.id}>Point {i+1} · {p.x}, {p.y}</option>)}</select></GuidedField>}
    {selected&&(tool==="edit"||drawing.type==="symbol"||drawing.type==="label")&&<form key={`${drawing.id}:${selected.x}:${selected.y}`} onChange={onEditFields} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),position:Point={x:Number(f.get("x")),y:Number(f.get("y"))};if(onChange(drawing.type==="terrain"||drawing.type==="path"?{...drawing,points:drawing.points.map(p=>p.id===pointId?{...p,...position}:p)}:{...drawing,point:position}))onApplyFields(e);}}><div className={styles.coordinates}>{field("x","Drawing X","Map units from the left edge, from 0 to 2000.",selected.x,0,2000)}{field("y","Drawing Y","Map units from the top edge, from 0 to 1200.",selected.y,0,1200)}</div><button className="st-button is-secondary">Apply drawing position</button></form>}
    {tool==="edit"&&selected&&(drawing.type==="path"||drawing.type==="terrain")&&<div className={styles.actions}><button className="st-button is-secondary" disabled={disabled||points.length>=128||pointId===drawing.points.at(-1)?.id} onClick={()=>{const index=drawing.points.findIndex(p=>p.id===pointId),a=drawing.points[index],b=drawing.points[index+1];if(!a||!b)return;const next=[...drawing.points];next.splice(index+1,0,{id:crypto.randomUUID(),x:Math.round((a.x+b.x)*50)/100,y:Math.round((a.y+b.y)*50)/100});onChange({...drawing,points:next});}}>Add drawing point</button><button className="st-button is-danger" disabled={disabled||points.length<=(drawing.type==="path"?2:1)} onClick={()=>onChange({...drawing,points:drawing.points.filter(p=>p.id!==pointId)})}>Remove drawing point</button></div>}
    {(tool==="move"||(tool==="edit"&&selected))&&<div className={styles.nudges}><p>Move {tool==="edit"?"this point":"this drawing"} by 10 map units</p>{[["Left",-10,0],["Up",0,-10],["Down",0,10],["Right",10,0]].map(([label,x,y])=><button key={String(label)} className="st-button is-secondary" disabled={disabled} onClick={()=>onNudge(Number(x),Number(y))}>{label}</button>)}</div>}</>}
    {canEdit&&!drawing.archived&&<div className={styles.actions}><p>Arrange overlaps within this layer.</p><button className="st-button is-secondary" disabled={disabled} onClick={()=>onOrder(-1)}>Send backward</button><button className="st-button is-secondary" disabled={disabled} onClick={()=>onOrder(1)}>Bring forward</button></div>}
    {canEdit&&<button className="st-button is-danger" disabled={disabled} onClick={onArchive}>{drawing.archived?"Restore drawing":"Archive drawing"}</button>}
  </section>;
}
export function LinkedPlaceControl({value,onChange,geographies}:{value:string;onChange:(id:string)=>void;geographies:GeographyRecord[]}) {return <GuidedField label="Linked place" help="Choose an existing World geography for a real place. Settlement and landmark symbols create a location if none is selected. Decorative terrain does not create geography."><select className="st-control" value={value} onChange={e=>onChange(e.target.value)}><option value="">No existing place selected</option>{geographies.filter(g=>!g.archived).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField>;}
