"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, Compass, Plus, X } from "lucide-react";
import { YEAR_LIMIT, yearLabel, type WorldBundle } from "./history";
import { datingDraftOf, datingDraftSchema, formatYear, fromReckoning, toReckoning, type DatingDraft, type DatingSystem } from "./chronology";
import { SaveError, worldApi } from "./client-api";
import { Field } from "./world-field";
import shared from "./worlds.module.css";
import styles from "./chronology.module.css";

function NumberingPreview({system}:{system:DatingDraft}) {
  const valid = datingDraftSchema.shape.epochYear.safeParse(system.epochYear);
  if (!valid.success) return <p className={shared.muted}>Enter a valid epoch to preview numbering.</p>;
  return <div className={styles.examples} aria-label="Year numbering preview">{[-1,0,1].map((offset)=>system.epochYear+offset).filter((year)=>Math.abs(year)<=YEAR_LIMIT).map((year)=><div key={year}><small>Canonical {yearLabel(year)}</small><strong>{formatYear(year,system)}</strong></div>)}</div>;
}
function DatingEditor({record,onClose,onSave,onReload}:{record?:DatingSystem;onClose:()=>void;onSave:(draft:DatingDraft)=>Promise<void>;onReload:()=>Promise<void>}) {
  const dialog=useRef<HTMLDialogElement>(null);
  const [draft,setDraft]=useState(()=>datingDraftOf(record));const [original]=useState(()=>JSON.stringify(draft));
  const dirty=original!==JSON.stringify(draft);const [pending,setPending]=useState(false);const [error,setError]=useState("");const [conflict,setConflict]=useState(false);const [discard,setDiscard]=useState(false);
  useEffect(()=>{dialog.current?.showModal();},[]);
  useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  function close(){if(pending)return;if(dirty)setDiscard(true);else onClose();}
  return <dialog ref={dialog} className={shared.editor} aria-labelledby="dating-editor-title" onCancel={(event)=>{event.preventDefault();close();}}>
    <header className={shared.editorHeader}><div><p className={shared.eyebrow}>World chronology</p><h2 id="dating-editor-title">{record ? "Edit dating system" : "Create dating system"}</h2></div><button className="st-button is-ghost" aria-label="Close dating editor" disabled={pending} onClick={close}><X size={20}/></button></header>
    <form onSubmit={async(event)=>{event.preventDefault();setError("");setConflict(false);const parsed=datingDraftSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues.map(({message})=>message).join(" "));return;}setPending(true);try{await onSave(parsed.data);}catch(failure){setError(failure instanceof Error ? failure.message : "The save failed. Your draft is retained.");setConflict(failure instanceof SaveError && failure.status===409);}finally{setPending(false);}}}>
      <fieldset className={shared.editorFields} disabled={pending}>
        <Field label="Dating system name" help="Name a year-counting tradition, such as the Founding Reckoning. This defines year labels; it does not define months or days."><input autoFocus required maxLength={160} value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})}/></Field>
        <Field label="Description" help="A short explanation of who uses this reckoning and why. Optional; up to 4,000 characters."><textarea rows={2} maxLength={4000} value={draft.description} onChange={(event)=>setDraft({...draft,description:event.target.value})}/></Field>
        <Field label="Historical origin" help="Describe the event or landmark that starts the count. This does not create a historical event automatically."><input required maxLength={1000} value={draft.origin} onChange={(event)=>setDraft({...draft,origin:event.target.value})}/></Field>
        {record?.referenced && <p className={shared.notice}>Historical dates use this system. Its epoch and numbering rule are locked; create a separate reckoning for different arithmetic.</p>}
        <div className={styles.editorColumns}>
          <Field label="Epoch in canonical years" help="The canonical world year corresponding to Year 0, or to Year 1 After when zero is excluded. This is an explicit index, not a year length. Range: minus one trillion through one trillion."><input type="number" step={1} required min={-YEAR_LIMIT} max={YEAR_LIMIT} readOnly={record?.referenced} value={Number.isFinite(draft.epochYear) ? draft.epochYear : ""} onChange={(event)=>setDraft({...draft,epochYear:event.target.value === "" ? NaN : Number(event.target.value)})}/></Field>
          <Field label="Year numbering" help="With Year 0, the epoch displays zero. Without Year 0, the preceding year is Year 1 Before and the epoch is Year 1 After."><select disabled={record?.referenced} value={draft.numbering} onChange={(event)=>setDraft({...draft,numbering:event.target.value as DatingDraft["numbering"]})}><option value="no-year-zero">Without Year 0</option><option value="year-zero">Include Year 0</option></select></Field>
        </div>
        <div className={styles.editorColumns}><Field label="Before-origin label" help="The suffix shown after a before-origin year, such as Before Founding. Negative input numbers use this label."><input required maxLength={80} value={draft.beforeLabel} onChange={(event)=>setDraft({...draft,beforeLabel:event.target.value})}/></Field><Field label="After-origin label" help="The suffix shown after an after-origin year, such as After Founding. Positive input numbers use this label."><input required maxLength={80} value={draft.afterLabel} onChange={(event)=>setDraft({...draft,afterLabel:event.target.value})}/></Field></div>
        <NumberingPreview system={draft}/>
        <details className={shared.optional}><summary>Contextual notes</summary><Field label="Chronology notes" help="Optional private context about this convention. These notes do not change conversions."><textarea rows={3} maxLength={50000} value={draft.notes} onChange={(event)=>setDraft({...draft,notes:event.target.value})}/></Field></details>
      </fieldset>
      {error && <div className={shared.feedback} role="alert"><p>{error}</p>{conflict && record && <button type="button" className="st-button is-secondary" disabled={pending} onClick={async()=>{if(!window.confirm("Discard this draft and load the latest saved version?"))return;setPending(true);try{await onReload();}catch(failure){setError(failure instanceof Error ? failure.message : "Could not reload; your draft is retained.");}finally{setPending(false);}}}>Load latest version</button>}</div>}
      {discard && <div className={shared.feedback} role="alert"><p>Discard your unsaved dating-system draft?</p><div className={shared.actions}><button type="button" className="st-button is-secondary" onClick={()=>setDiscard(false)}>Keep writing</button><button type="button" className="st-button is-danger" onClick={onClose}>Discard draft</button></div></div>}
      <footer className={shared.editorFooter}><span className={shared.muted}>{pending ? "Saving…" : dirty ? "Unsaved draft" : "Ready to define"}</span><div className={shared.actions}><button type="button" className="st-button is-secondary" disabled={pending} onClick={close}>Cancel</button><button className="st-button" disabled={pending}>{record ? "Save dating system" : "Create dating system"}</button></div></footer>
    </form>
  </dialog>;
}
export function ChronologyWorkspace({bundle,canEdit,reload,onDefaultChanged}:{bundle:WorldBundle;canEdit:boolean;reload:()=>Promise<WorldBundle>;onDefaultChanged:(id:string|null)=>void}) {
  const [editor,setEditor]=useState<{record?:DatingSystem}|null>(null);const [pending,setPending]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const [fromId,setFromId]=useState("");const [toId,setToId]=useState(bundle.defaultDatingSystemId ?? "");const [sample,setSample]=useState("0");
  const systems=bundle.datingSystems;const api=`/api/worlds/${bundle.world.id}/chronology`;
  const from=systems.find((system)=>system.id===fromId),to=systems.find((system)=>system.id===toId);
  let conversion:{canonical:number;label:string;signed:number}|undefined,conversionError="";
  try{if(!sample.trim())throw new Error("Enter a sample year.");const canonical=fromReckoning(Number(sample),from);conversion={canonical,label:formatYear(canonical,to),signed:toReckoning(canonical,to)};}catch(failure){conversionError=failure instanceof Error ? failure.message : "Enter a supported year.";}
  async function action(body:unknown,message:string,defaultId?:string|null) {
    setPending(true);setError("");setNotice("");try{await worldApi(api,"POST",body);if(defaultId!==undefined)onDefaultChanged(defaultId);setNotice(message);try{await reload();}catch(failure){setError(failure instanceof Error ? `Saved successfully. ${failure.message}` : "Saved successfully; reload to see it.");}}catch(failure){setError(failure instanceof Error ? failure.message : "Could not save chronology.");}finally{setPending(false);}
  }
  return <section className={styles.workspace} aria-label="World chronology">
    <div className={shared.sectionHeading}><div><p className={shared.eyebrow}>The world&apos;s ways of counting</p><h2>Chronology</h2><p className={shared.muted}>Different names for the same historical years. Your history stays where it belongs.</p></div>{canEdit && <button className="st-button" disabled={pending} onClick={()=>setEditor({})}><Plus size={17}/>New dating system</button>}</div>
    {error && <div role="alert" className={shared.feedback}><p>{error}</p><button className="st-button is-secondary" onClick={()=>reload().then(()=>setError("")).catch((failure)=>setError(failure.message))}>Reload chronology</button></div>}{notice && <p role="status" className={shared.notice}>{notice}</p>}
    <div className={styles.systemGrid}>
      <article className={styles.systemCard} data-default={!bundle.defaultDatingSystemId}><div className={styles.cardHeading}><span className={styles.seal}><Compass size={26}/></span><div><span className={shared.eyebrow}>Always available</span><h3>Canonical world years</h3></div>{!bundle.defaultDatingSystemId && <span className={shared.privateBadge}>Default display</span>}</div><p>The stable historical reference. Signed whole years include Year 0.</p><p className={styles.epoch}>−1 <ArrowRight size={14}/> 0 <ArrowRight size={14}/> 1</p><p className={shared.muted}>No configuration needed. This is a year index, with no implied months, days or year length.</p>{canEdit && !!bundle.defaultDatingSystemId && <button className="st-button is-secondary" disabled={pending} onClick={()=>action({action:"default",revision:bundle.world.revision,systemId:null},"Canonical world years are now the default display.",null)}>Use canonical as default</button>}</article>
      {systems.map((system)=><article key={system.id} className={styles.systemCard} data-default={bundle.defaultDatingSystemId===system.id} data-archived={system.archived}>
        <div className={styles.cardHeading}><span className={styles.seal}>{system.numbering === "year-zero" ? "0" : "1"}</span><div><span className={shared.eyebrow}>{system.archived ? "Archived · context preserved" : system.numbering === "year-zero" ? "Includes Year 0" : "No Year 0"}</span><h3>{system.name}</h3></div>{bundle.defaultDatingSystemId===system.id && <span className={shared.privateBadge}>Default display</span>}</div>
        {system.description && <p>{system.description}</p>}<p className={styles.origin}>{system.origin}</p><p className={styles.epoch}>Canonical {yearLabel(system.epochYear)} <ArrowRight size={15}/>{formatYear(system.epochYear,system)}</p><NumberingPreview system={system}/>
        {system.referenced && <p className={shared.muted}>Epoch and numbering protected by historical use.</p>}{system.notes && <details className={shared.optional}><summary>Contextual notes</summary><p className={shared.prose}>{system.notes}</p></details>}
        {canEdit && <div className={styles.cardActions}>{system.archived ? <button className="st-button is-secondary" disabled={pending} onClick={()=>action({action:"restore",id:system.id,revision:system.revision},"Dating system restored.")}>Restore {system.name}</button> : <><button className="st-button is-secondary" disabled={pending} onClick={()=>setEditor({record:system})}>Edit {system.name}</button>{bundle.defaultDatingSystemId!==system.id && <button className="st-button" disabled={pending} onClick={()=>action({action:"default",systemId:system.id,revision:bundle.world.revision},`${system.name} is now the default display.`,system.id)}>Use {system.name} as default</button>}<button className="st-button is-ghost" disabled={pending || bundle.defaultDatingSystemId===system.id} title={bundle.defaultDatingSystemId===system.id ? "Choose another default before archiving." : "History and source context will be preserved."} onClick={()=>action({action:"archive",id:system.id,revision:system.revision},"Dating system archived. Historical context is preserved.")}>Archive {system.name}</button></>}</div>}
      </article>)}
    </div>
    <section className={styles.converter} aria-label="Year conversion"><div><p className={shared.eyebrow}>Try a historical year</p><h3>One position, different reckonings</h3><p className={shared.muted}>Convert alternate numbering of the same canonical years. Negative inputs mean Before. This does not convert calendar days or advance time.</p></div>
      <div className={styles.conversionFields}><Field label="Convert from" help="Choose the convention used by your sample number. Retired reckonings remain available for historical context."><select value={fromId} onChange={(event)=>setFromId(event.target.value)}><option value="">Canonical world years</option>{systems.map((system)=><option key={system.id} value={system.id}>{system.name}{system.archived ? " (archived)" : ""}</option>)}</select></Field><Field label="Sample year" help="Enter a signed whole year. A convention without Year 0 rejects zero. The corresponding canonical index must be within minus one trillion through one trillion."><input type="number" step={1} value={sample} onChange={(event)=>setSample(event.target.value)}/></Field><Field label="Convert to" help="Choose how the same historical position should be labelled. This changes no saved record."><select value={toId} onChange={(event)=>setToId(event.target.value)}><option value="">Canonical world years</option>{systems.map((system)=><option key={system.id} value={system.id}>{system.name}{system.archived ? " (archived)" : ""}</option>)}</select></Field></div>
      <output className={styles.result} aria-live="polite">{conversion ? <><strong>{conversion.label}</strong><span>Signed input: {yearLabel(conversion.signed)} · Canonical year {yearLabel(conversion.canonical)}</span></> : <span role="alert">{conversionError}</span>}</output>
    </section>
    {editor && <DatingEditor key={`${editor.record?.id ?? "new"}:${editor.record?.revision ?? 0}`} record={editor.record} onClose={()=>setEditor(null)} onReload={async()=>{const fresh=await reload();const record=fresh.datingSystems.find((system)=>system.id===editor.record?.id);if(!record)throw new SaveError("This system is unavailable. Your draft is retained.",404);setEditor({record});}} onSave={async(draft)=>{await worldApi(api,"POST",{action:"save",id:editor.record?.id,revision:editor.record?.revision,draft});setEditor(null);setNotice("Dating system saved.");try{await reload();}catch(failure){setError(failure instanceof Error ? `Saved successfully. ${failure.message}` : "Saved; reload to see it.");}}}/>}
  </section>;
}
