import { memo, useId, useMemo } from "react";
import type { MapDraft } from "./atlas";
import { planBaseShapes, planCenter, type DungeonShape } from "./dungeon";
import { ShapeArt } from "./interior-scene";
import type { InteriorEntity } from "./interior";
import styles from "./dungeon.module.css";

export function passagePath(s:Extract<DungeonShape,{variant:"passage"}>){
 if(s.appearance==="constructed"||s.points.length===2)return s.points.map((p,i)=>`${i?"L":"M"} ${p.x} ${p.y}`).join(" ");
 return `M ${s.points[0].x} ${s.points[0].y} `+s.points.slice(1,-1).map((p,i)=>{const next=s.points[i+2];return `Q ${p.x} ${p.y} ${(p.x+next.x)/2} ${(p.y+next.y)/2}`;}).join(" ")+` L ${s.points.at(-1)!.x} ${s.points.at(-1)!.y}`;
}
export const DungeonScene=memo(function DungeonScene({draft,selectedId,units=1}:{draft:MapDraft;selectedId?:string|null;units?:number}){
 const prefix=useId().replaceAll(":",""),state=draft.dungeonState!,entities=useMemo(()=>new Map((draft.dungeonEntities??[]).map(e=>[e.id,e])),[draft.dungeonEntities]);
 const shapes=useMemo(()=>(draft.dungeonShapes??[]).filter(s=>!s.archived&&state.layers[entities.get(s.entityId)!.kind].visible),[draft.dungeonShapes,state,entities]);
 const floors=shapes.filter(s=>s.variant==="area"&&entities.get(s.entityId)?.kind!=="terrain"||s.variant==="passage"&&entities.get(s.entityId)?.kind==="corridor"),base=planBaseShapes(shapes);
 const grid=state.grid,s=grid.size,w=Math.sqrt(3)*s,flat=grid.orientation==="flat",hex=(x:number,y:number)=>Array.from({length:6},(_,i)=>`${x+Math.cos((i*60-30)*Math.PI/180)*s},${y+Math.sin((i*60-30)*Math.PI/180)*s}`).join(" ");
 const art=(shape:DungeonShape,outer:boolean)=>shape.variant==="area"?<polygon key={shape.id} points={shape.points.map(p=>`${p.x},${p.y}`).join(" ")} className={outer?styles.floorEdge:styles.floorFill}/>:shape.variant==="passage"?<path key={shape.id} d={passagePath(shape)} className={outer?styles.corridorEdge:styles.corridorFill} strokeWidth={shape.width+(outer?10:0)}/>:null;
 const occupied:{x:number;y:number;w:number;h:number}[]=[],labels=state.layers.labels.visible?shapes.filter(s=>entities.get(s.entityId)?.name).sort((a,b)=>Number(b.id===selectedId)-Number(a.id===selectedId)).flatMap(shape=>{const e=entities.get(shape.entityId)!,selected=shape.id===selectedId;if(!selected&&(units>5||!["room","cavern","corridor","transition","landmark"].includes(e.kind)))return [];const c=planCenter(shape,shapes),text=e.name.slice(0,36),box={x:c.x-text.length*6*units/2,y:c.y-12*units,w:text.length*6*units,h:16*units};if(!selected&&occupied.some(b=>box.x<b.x+b.w&&box.x+box.w>b.x&&box.y<b.y+b.h&&box.y+box.h>b.y))return [];occupied.push(box);return [{id:shape.id,c,text}];}):[];
 return <g className={styles.scene} data-dungeon-scene><defs><pattern id={`${prefix}-floor`} width={state.flooring==="boards"?90:60} height="60" patternUnits="userSpaceOnUse"><path className={styles.floorLine} d={state.flooring==="boards"?"M 0 0 H 90 M 45 0 V 60":"M 0 0 H 60 V 60"}/></pattern><pattern id={`${prefix}-grid`} width={grid.kind==="hex"?(flat?3*s:w):s} height={grid.kind==="hex"?(flat?w:3*s):s} patternUnits="userSpaceOnUse" patternTransform={`translate(${grid.offsetX} ${grid.offsetY})`}><g className={styles.gridInk}>{grid.kind==="square"?<path d={`M ${s} 0 H 0 V ${s}`}/>:<g transform={flat?"matrix(0 1 1 0 0 0)":undefined}>{[[0,0],[w,0],[w/2,1.5*s],[0,3*s],[w,3*s]].map(([x,y],i)=><polygon key={i} points={hex(x,y)}/>)}</g>}</g></pattern></defs>
 {state.layers.flooring.visible&&<rect className={styles.background} width={2000} height={1200} pointerEvents="none"/>}
 <g pointerEvents="none" data-dungeon-floor-union>{floors.map(shape=>art(shape,true))}{floors.map(shape=>art(shape,false))}</g>
 {state.layers.flooring.visible&&state.flooring!=="plain"&&<g pointerEvents="none" data-dungeon-floor-pattern={state.flooring}>{floors.map(shape=>shape.variant==="area"?<polygon key={shape.id} points={shape.points.map(p=>`${p.x},${p.y}`).join(" ")} fill={`url(#${prefix}-floor)`}/>:shape.variant==="passage"?<path key={shape.id} d={passagePath(shape)} fill="none" stroke={`url(#${prefix}-floor)`} strokeWidth={shape.width} strokeLinecap="round" strokeLinejoin="round"/>:null)}</g>}
 {shapes.filter(s=>entities.get(s.entityId)?.kind==="terrain").map(shape=><g key={shape.id} className={styles.environment} data-appearance={shape.variant==="passage"?shape.appearance:entities.get(shape.entityId)?.classification} data-interior={shape.id} data-entity={shape.entityId}>{shape.variant==="passage"?<path d={passagePath(shape)} strokeWidth={shape.width}/>:shape.variant==="area"?<polygon points={shape.points.map(p=>`${p.x},${p.y}`).join(" ")}/>:<ShapeArt shape={shape} entity={{...entities.get(shape.entityId)!,kind:"landmark"} as InteriorEntity} shapes={base} selected={shape.id===selectedId} units={units}/>}</g>)}
 {grid.visible&&grid.kind!=="none"&&state.layers.grid.visible&&<rect data-dungeon-grid={grid.kind} width={2000} height={1200} fill={`url(#${prefix}-grid)`} opacity={grid.opacity} pointerEvents="none"/>}
 {floors.map(shape=><g key={shape.id} data-interior={shape.id} data-entity={shape.entityId} data-geography={entities.get(shape.entityId)?.geographyId??undefined} data-secret={entities.get(shape.entityId)?.visibility!=="ordinary"} className={`${styles.place} ${shape.id===selectedId?styles.selected:""}`}>{shape.variant==="area"?<polygon points={shape.points.map(p=>`${p.x},${p.y}`).join(" ")}/>:shape.variant==="passage"?<path d={passagePath(shape)} strokeWidth={shape.width}/>:null}<title>{entities.get(shape.entityId)?.name||entities.get(shape.entityId)?.kind}</title></g>)}
 {shapes.filter(s=>!floors.includes(s)&&entities.get(s.entityId)?.kind!=="terrain").map(shape=><g key={shape.id} className={styles.feature} data-kind={entities.get(shape.entityId)?.kind} data-secret={entities.get(shape.entityId)?.visibility!=="ordinary"}><ShapeArt shape={shape as Exclude<DungeonShape,{variant:"passage"}>} entity={{...entities.get(shape.entityId)!,kind:entities.get(shape.entityId)?.kind==="transition"?"transition":entities.get(shape.entityId)?.kind==="furnishing"?"furnishing":"landmark"} as InteriorEntity} shapes={base} selected={shape.id===selectedId} units={units}/>{entities.get(shape.entityId)?.visibility!=="ordinary"&&<text className={styles.secret} x={planCenter(shape,shapes).x} y={planCenter(shape,shapes).y-20*units} fontSize={12*units} pointerEvents="none">S</text>}</g>)}
 {labels.map(l=><text key={l.id} x={l.c.x} y={l.c.y} textAnchor="middle" className={styles.label} fontSize={13*units} pointerEvents="none">{l.text}</text>)}
 </g>;
});
