"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { GuidedField } from "@/components/field-guidance";
import type { AtlasBundle, AtlasMap } from "./atlas";
import { gridSchema, type DungeonGrid, type DungeonLevel, type DungeonSite } from "./dungeon";
import styles from "./interior.module.css";
export type DungeonTarget={siteId?:string;level?:DungeonLevel;site?:DungeonSite;additionalMap?:boolean};
export function DungeonDialog({target,bundle,onClose,onSave,onDirtyChange}:{target:DungeonTarget;bundle:AtlasBundle;onClose:()=>void;onSave:(body:unknown)=>Promise<void>;onDirtyChange:(dirty:boolean)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),touched=useRef(false),[pending,setPending]=useState(false),[error,setError]=useState(""),[existing,setExisting]=useState("");
 const level=target.level,site=target.site,newSite=!target.siteId&&!level&&!site;
 useEffect(()=>{dialog.current?.showModal();return()=>onDirtyChange(false);},[onDirtyChange]);
 const close=()=>{if(pending||touched.current&&!window.confirm("Discard unapplied dungeon information?"))return;onClose();};
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(touched.current){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard);},[]);
 return <dialog ref={dialog} className={styles.modal} aria-labelledby="dungeon-dialog-title" onCancel={e=>{e.preventDefault();close();}}><form className={styles.dialog} onChange={()=>{touched.current=true;onDirtyChange(true);}} onSubmit={async e=>{
  e.preventDefault();const f=new FormData(e.currentTarget),draft={name:String(f.get("levelName")??""),description:String(f.get("levelDescription")??""),classification:String(f.get("levelClassification")??""),label:String(f.get("label")??""),order:f.get("order")?Number(f.get("order")):null,elevation:String(f.get("elevation")??"")};
  const chosen=bundle.geographies.find(g=>g.id===existing),siteDraft={name:chosen?.name??String(f.get("siteName")??""),description:chosen?.description??String(f.get("siteDescription")??""),classification:String(f.get("siteClassification")??""),parentId:site?.parentId??(f.get("parentId")?String(f.get("parentId")):null)};
  const body=target.additionalMap?{action:"dungeon-map",levelId:level!.id,name:String(f.get("mapName"))}:site?{action:"edit-dungeon-site",id:site.id,revision:site.revision,geographyRevision:site.geographyRevision,draft:siteDraft}:level?{action:"edit-dungeon-level",id:level.id,revision:level.revision,geographyRevision:level.geographyRevision,draft}:newSite?{action:"create-dungeon",geographyId:existing||null,draft:siteDraft,level:draft,mapName:String(f.get("mapName"))}:{action:"dungeon-level",siteId:target.siteId,draft,mapName:String(f.get("mapName"))};
  setPending(true);setError("");try{await onSave(body);touched.current=false;onDirtyChange(false);}catch(err){setError((err as Error).message);}finally{setPending(false);}
 }}><h2 id="dungeon-dialog-title">{target.additionalMap?"Another dungeon map":site?"Edit dungeon site":level?"Edit dungeon level":newSite?"Create a dungeon":"Add a dungeon level or section"}</h2>{error&&<p role="alert">{error}</p>}<fieldset disabled={pending}>
 {newSite&&<GuidedField label="Dungeon site" help="Create a new independent site, or use an existing location without duplicating or renaming it. A new site can be parented anywhere in this World."><select className="st-control" value={existing} onChange={e=>setExisting(e.target.value)}><option value="">New dungeon site</option>{bundle.geographies.filter(g=>g.kind==="location"&&!g.archived&&!bundle.dungeonSites?.some(s=>s.id===g.id)).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField>}
 {(newSite||site)&&<>{!existing&&<><GuidedField label="Dungeon name" help="Any name is welcome. The site is independent of its map drawings and does not require a building."><input className="st-control" required name="siteName" maxLength={160} defaultValue={site?.name??""}/></GuidedField><GuidedField label="Dungeon description" help="Optional narrative information. No danger, origin, genre or construction explanation is required."><textarea className="st-control" name="siteDescription" rows={3} maxLength={12000} defaultValue={site?.description??""}/></GuidedField></>}<GuidedField label="Dungeon classification" help="Optional custom classification, such as flooded installation or dimensional garden."><input className="st-control" name="siteClassification" maxLength={160} defaultValue={site?.classification??""}/></GuidedField>{newSite&&!existing&&<GuidedField label="Within a place" help="Optional geography parent. Blank makes this an independent World location. Entrances and transitions are authored separately."><select className="st-control" name="parentId"><option value="">Independent World location</option>{bundle.geographies.filter(g=>!g.archived).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField>}</>}
 {!site&&!target.additionalMap&&<><GuidedField label="Level or section name" help="Use any name for this stable section. Ordering and depth never create automatic connections."><input className="st-control" required name="levelName" maxLength={160} defaultValue={level?.name??""}/></GuidedField><GuidedField label="Level description" help="Optional narrative detail; rooms and passages are created in the workshop."><textarea className="st-control" name="levelDescription" rows={3} maxLength={12000} defaultValue={level?.description??""}/></GuidedField><GuidedField label="Level classification" help="Optional free text describing this section."><input className="st-control" name="levelClassification" maxLength={160} defaultValue={level?.classification??""}/></GuidedField><GuidedField label="Level label" help="Optional text, such as Beyond the Gate, Deck C or Western network."><input className="st-control" name="label" maxLength={80} defaultValue={level?.label??""}/></GuidedField><GuidedField label="Display order" help="Optional whole number, used only to order the menu. It does not change identity or imply elevation."><input className="st-control" name="order" type="number" min={-100000} max={100000} defaultValue={level?.order??""}/></GuidedField><GuidedField label="Depth or elevation reference" help="Optional notation with any meaning or units you choose. No physical rules are imposed."><input className="st-control" name="elevation" maxLength={80} defaultValue={level?.elevation??""}/></GuidedField></>}
 {!site&&(!level||target.additionalMap)&&<GuidedField label="Dungeon map name" help="This drawing represents the section; several drawings may share its stable identity."><input className="st-control" required name="mapName" maxLength={160}/></GuidedField>}
 </fieldset><div className={styles.tools}><button className="st-button" disabled={pending}>{pending?"Saving...":site||level&&!target.additionalMap?"Save dungeon information":"Create dungeon map"}</button><button type="button" className="st-button is-secondary" disabled={pending} onClick={close}>Cancel</button></div></form></dialog>;
}
export function DungeonLevelNavigation({bundle,map,siteId,onOpen,onCreate,onEdit}:{bundle:AtlasBundle;map?:AtlasMap;siteId?:string;onOpen:(id:string,place?:string)=>void;onCreate?:(id:string)=>void;onEdit?:(l:DungeonLevel)=>void}){
 const level=bundle.dungeonLevels?.find(l=>l.id===map?.geographyId),id=siteId??level?.siteId,site=bundle.dungeonSites?.find(s=>s.id===id);if(!site)return null;
 const levels=(bundle.dungeonLevels??[]).filter(l=>l.siteId===id&&!l.archived).sort((a,b)=>(a.order??100001)-(b.order??100001)||a.name.localeCompare(b.name));
 const entrances=bundle.maps.filter(m=>!m.archived&&!m.unavailable&&m.id!==map?.id&&(m.geographyId===site.id||m.geographyId===site.parentId||m.features.some(f=>f.geographyId===site.id&&!f.archived)||m.drawings?.some(d=>d.geographyId===site.id&&!d.archived)));
 return <section className={styles.floorBar} aria-label="Dungeon levels"><strong>{site.name}</strong>{level&&<p>{level.name}{level.label?` / ${level.label}`:""}{level.elevation?` / ${level.elevation}`:""}</p>}<label>Level map <select className="st-control" aria-label="Choose dungeon level map" value={map?.mapKind==="dungeon"?map.id:""} onChange={e=>{if(e.target.value)onOpen(e.target.value);}}><option value="">Choose a level map</option>{levels.map(l=><optgroup key={l.id} label={l.name}>{bundle.maps.filter(m=>m.geographyId===l.id&&!m.archived&&!m.unavailable).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</optgroup>)}</select></label>{level&&<><p>{level.classification}</p><p>{level.description}</p></>}{onCreate&&<button className="st-button is-secondary" onClick={()=>onCreate(site.id)}>Add dungeon level</button>}{level&&onEdit&&<button className="st-button is-secondary" onClick={()=>onEdit(level)}>Edit dungeon level</button>}{entrances.map(m=><button key={m.id} className="st-button is-secondary" onClick={()=>onOpen(m.id,site.id)}>Return to site map: {m.name}</button>)}</section>;
}
export function DungeonGridFields({grid,disabled,generation,onChange,onFieldsChange,onApplied}:{grid:DungeonGrid;disabled:boolean;generation:number;onChange:(g:DungeonGrid)=>boolean;onFieldsChange:(e:FormEvent<HTMLFormElement>)=>void;onApplied:(form:HTMLFormElement)=>void}){
 const [error,setError]=useState("");
 return <details><summary>Dungeon grid</summary><p>Optional drawing guide. Apply settings, then save the map. Existing geometry stays unchanged.</p><form key={generation} onChange={onFieldsChange} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const result=gridSchema.safeParse({kind:f.get("gridKind"),size:Number(f.get("gridSize")),offsetX:Number(f.get("gridOffsetX")),offsetY:Number(f.get("gridOffsetY")),orientation:f.get("gridOrientation"),opacity:Number(f.get("gridOpacity")),scale:String(f.get("gridScale")),visible:f.get("gridVisible")==="on",snap:f.get("gridSnap")==="on"});if(!result.success){setError("Check grid size, offsets and opacity, then apply again.");return;}if(onChange(result.data)){setError("");onApplied(e.currentTarget);}}}><fieldset disabled={disabled}>
 <GuidedField label="Grid kind" help="Choose no grid, square cells or hexagonal cells."><select className="st-control" name="gridKind" defaultValue={grid.kind}>{["none","square","hex"].map(k=><option key={k}>{k}</option>)}</select></GuidedField>
 <GuidedField label="Grid cell size" help="Drawing units: square side length or hexagon radius, from 12 to 240."><input className="st-control" name="gridSize" required type="number" min={12} max={240} step="any" defaultValue={grid.size}/></GuidedField>
 {(["offsetX","offsetY"] as const).map((k,i)=><GuidedField key={k} label={i?"Grid Y offset":"Grid X offset"} help="Shift the drawing guide's origin without moving any source geometry."><input className="st-control" name={i?"gridOffsetY":"gridOffsetX"} required type="number" min={i?-1200:-2000} max={i?1200:2000} step="any" defaultValue={grid[k]}/></GuidedField>)}
 <GuidedField label="Hex orientation" help="Used by hex grids: pointy top or flat top. Snapping uses their centers."><select className="st-control" name="gridOrientation" defaultValue={grid.orientation}><option value="pointy">Pointy top</option><option value="flat">Flat top</option></select></GuidedField>
 <GuidedField label="Grid opacity" help="Set the guide's contrast from 0.05 to 0.8."><input className="st-control" name="gridOpacity" required type="number" step="any" min={.05} max={.8} defaultValue={grid.opacity}/></GuidedField>
 <GuidedField label="Scale reference" help="Optional authored text, such as one cell is ten paces. It executes no rules."><input className="st-control" name="gridScale" maxLength={160} defaultValue={grid.scale}/></GuidedField>
 {(["visible","snap"] as const).map(k=><label key={k}><input name={k==="visible"?"gridVisible":"gridSnap"} type="checkbox" defaultChecked={grid[k]}/>{k==="visible"?"Show grid":"Snap drawing points to grid"}</label>)}
 <button className="st-button is-secondary">Apply grid settings</button></fieldset>{error&&<p role="alert">{error}</p>}</form></details>;
}
