"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { worldApi } from "./client-api";
import { Field } from "./world-field";
import { HistoricalTimeline } from "./historical-timeline";
import { accuracyLabels, dateLabels, narrativeLabels, prominenceLabels, type EntryRecord, type EraRecord } from "./history";
import { historyFiltersFromParams, type HistoryIndex } from "./history-index";
import { formatTime, type DatingSystem } from "./chronology";
import styles from "./worlds.module.css";

const keys=["q","category","eventType","era","from","to","dateKind","accuracy","narrative","archived"] as const;
export function HistoryBrowser({worldId,timelineId,eras,displaySystem,review,refresh,onEntry,onEra}:{worldId:string;timelineId:string;eras:EraRecord[];displaySystem:DatingSystem|null;review:boolean;refresh:string;onEntry:(e:EntryRecord)=>void;onEra:(e:EraRecord)=>void}) {
  const params=useSearchParams(),[result,setData]=useState<HistoryIndex|null>(null),[loadedApi,setLoadedApi]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[limit,setLimit]=useState(40);
  const query=new URLSearchParams({timeline:timelineId});for(const key of keys){const value=params.get(key);if(value!==null)query.set(key,value);}params.getAll("hide").forEach(c=>query.append("hide",c));if(review)query.set("review","1");if(params.get("knowledge")==="ordinary")query.set("ordinary","1");
  const api=`/api/worlds/${worldId}/history?${query}`;
  const data=loadedApi===api?result:null,waiting=loading||loadedApi!==api;
  useEffect(()=>{let alive=true;const timer=setTimeout(()=>{try{historyFiltersFromParams(new URLSearchParams(api.split("?")[1]));}catch(failure){setData(null);setLoadedApi(api);setError((failure as Error).message);setLoading(false);return;}setLoading(true);worldApi<HistoryIndex>(api).then(value=>{if(alive){setData(value);setLoadedApi(api);setError("");setLoading(false);setLimit(40);}}).catch(failure=>{if(alive){setData(null);setLoadedApi(api);setError(failure.message);setLoading(false);}});},120);return()=>{alive=false;clearTimeout(timer);};},[api,refresh]);
  function change(key:string,value:string,replace=false){const url=new URL(window.location.href);if(value)url.searchParams.set(key,value);else url.searchParams.delete(key);url.searchParams.delete("entry");window.history[replace?"replaceState":"pushState"](null,"",url.pathname+url.search);}
  const ordinary=params.get("knowledge")==="ordinary",archived=params.get("archived")==="1",list=params.get("historyView")==="list",showIndex=params.get("showIndexOnly")==="1";
  const entries=data?.entries??[],visual=entries.filter(e=>showIndex||e.prominence!=="index-only");
  return <section aria-label="History index">
    <div className={styles.historyFilters}>
      <Field label="Search history" help="Search titles, full historical accounts, authorized author notes and related entity names in this timeline. Each event appears once."><input type="search" value={params.get("q")??""} onChange={e=>change("q",e.target.value,true)} placeholder="Find an account or entity…"/></Field>
      <Field label="Entity category" help="Filter linked entity categories, or find events without visible links. This only changes the view; saved history remains intact."><select value={params.get("category")??""} onChange={e=>change("category",e.target.value)}><option value="">All categories</option><option value="geography">All geography</option><option value="unlinked">Unlinked / uncategorized</option>{data?.categories.filter(c=>c!=="geography").map(c=><option key={c} value={c}>{c}</option>)}</select></Field>
      <Field label="Event type" help="Choose an authored historical type or participant relationship. Original custom types are retained."><select value={params.get("eventType")??""} onChange={e=>change("eventType",e.target.value)}><option value="">All event types</option>{data?.eventTypes.map(t=><option key={t}>{t}</option>)}</select></Field>
      <Field label="Narrative status" help="Distinguish recorded accounts from authored plans."><select value={params.get("narrative")??""} onChange={e=>change("narrative",e.target.value)}><option value="">All statuses</option>{Object.entries(narrativeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
      <Field label="Accuracy" help="Filter the account's established, disputed, unverified or disproven classification without changing it."><select value={params.get("accuracy")??""} onChange={e=>change("accuracy",e.target.value)}><option value="">All accounts</option>{Object.entries(accuracyLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
      <Field label="Historical era" help="Filter explicitly authored era associations. An era is not inferred from a date."><select value={params.get("era")??""} onChange={e=>change("era",e.target.value)}><option value="">All eras</option><option value="none">No era association</option>{eras.map(e=><option key={e.id} value={e.id}>{e.name}{e.archived?" (archived)":""}</option>)}</select></Field>
      <Field label="From canonical year" help="Optional signed whole World year, including Year 0. Ranges match overlapping durations and possible windows, not proof of an exact occurrence."><input type="number" step="1" value={params.get("from")??""} onChange={e=>change("from",e.target.value,true)}/></Field>
      <Field label="Through canonical year" help="Optional inclusive ending World year. Approximate accounts use only their authored anchor; no tolerance is inferred. Undated accounts do not match a numeric range."><input type="number" step="1" value={params.get("to")??""} onChange={e=>change("to",e.target.value,true)}/></Field>
      <Field label="Date precision" help="Keep approximate dates, uncertain occurrence windows, known durations and undated accounts distinct."><select value={params.get("dateKind")??""} onChange={e=>change("dateKind",e.target.value)}><option value="">All date forms</option>{Object.entries(dateLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
    </div>
    <details><summary>Show or hide entity categories</summary><p>These view controls affect both presentations and preserve saved history. An event with several linked categories remains visible while at least one is shown. Unlinked accounts remain available.</p>{data?.categories.map(c=><label className={styles.archiveToggle} key={c}><input type="checkbox" checked={!params.getAll("hide").includes(c)} onChange={e=>{const url=new URL(window.location.href),hidden=url.searchParams.getAll("hide").filter(v=>v!==c);if(!e.target.checked)hidden.push(c);url.searchParams.delete("hide");hidden.forEach(v=>url.searchParams.append("hide",v));url.searchParams.delete("entry");window.history.pushState(null,"",url.pathname+url.search);}}/>Show {c}</label>)}</details>
    <div className={styles.historyViewBar}><div className={styles.tabs} role="group" aria-label="History presentation"><button aria-pressed={!list} className={!list?styles.activeTab:""} onClick={()=>change("historyView","")}>Timeline</button><button aria-pressed={list} className={list?styles.activeTab:""} onClick={()=>change("historyView","list")}>Chronological list</button></div><label className={styles.archiveToggle}><input type="checkbox" checked={archived} onChange={e=>change("archived",e.target.checked?"1":"")}/>View archived history</label><label className={styles.archiveToggle}><input type="checkbox" checked={showIndex} onChange={e=>change("showIndexOnly",e.target.checked?"1":"")}/>Show index-only markers</label><button className="st-button is-secondary" onClick={()=>change("knowledge",ordinary?"":"ordinary")}>{ordinary?"Return to author history":"Ordinary-knowledge history preview"}</button><button className="st-button is-ghost" onClick={()=>{const url=new URL(window.location.href);keys.forEach(k=>url.searchParams.delete(k));url.searchParams.delete("hide");window.history.pushState(null,"",url.pathname+url.search);}}>Reset history filters</button><span aria-live="polite">{waiting?"Searching history…":`${entries.length} matching entries · ${visual.length} visual entries`}</span></div>
    {error&&<p role="alert">{error}</p>}{ordinary&&<p>Protected accounts, linked names and author notes are filtered by the server. This owner preview does not publish the World.</p>}
    <p className={styles.caption}>Ranges find possible overlap. Approximate dates retain their authored anchor and uncertainty. Filters never alter history or Campaign time.</p>
    <div hidden={list}>{data&&<HistoricalTimeline displaySystem={displaySystem} eras={eras.filter(e=>e.archived===archived)} entries={visual} onEntry={onEntry} onEra={onEra}/>}</div>
    <div hidden={!list} className={styles.chronicle} aria-label="Chronological history">{entries.slice(0,limit).map(e=><article className={styles.chronicleEntry} key={e.id}><div className={styles.chronicleDate}>{formatTime(e.time,displaySystem)}<small>{narrativeLabels[e.narrative]}</small></div><div><div className={styles.chips}><span>{accuracyLabels[e.accuracy]}</span><span>{prominenceLabels[e.prominence??"standard"]}</span>{e.eventType&&<span>{e.eventType}</span>}</div><h3><button onClick={()=>onEntry(e)}>{e.title}</button></h3><p className={styles.excerpt}>{e.account}</p><button className="st-button is-ghost" onClick={()=>onEntry(e)}>Read account</button></div></article>)}{!waiting&&!entries.length&&<p>No matching historical entries. Adjust the filters or author an account.</p>}{entries.length>limit&&<button className="st-button is-secondary" onClick={()=>setLimit(n=>n+40)}>Read more entries</button>}</div>
  </section>;
}
