"use client";
import { useEffect, useState } from "react";
import { worldApi } from "./client-api";
import { Field } from "./world-field";
import type { MilestoneLinks } from "./milestone-service";
export function HistoricalEntityLinks({ordinary=false,worldId,timelineId,entryId,revision,review,canEdit,onChanged}:{ordinary?:boolean;worldId:string;timelineId:string;entryId:string;revision:number;review:boolean;canEdit:boolean;onChanged:()=>Promise<unknown>}) {
  const [bundle,setBundle]=useState<MilestoneLinks|null>(null),[target,setTarget]=useState(""),[eventType,setEventType]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState(false);
  const query=new URLSearchParams({timeline:timelineId,entry:entryId});if(review)query.set("review","1");if(ordinary)query.set("ordinary","1");const url=`/api/worlds/${worldId}/milestones?${query}`;
  useEffect(()=>{let alive=true;worldApi<MilestoneLinks>(url).then(data=>{if(alive)setBundle(data);}).catch(failure=>{if(alive)setError(failure.message);});return()=>{alive=false;};},[url,revision]);
  return <section aria-label="Related World entities"><h3>Related World entities</h3>{bundle?.links.map(link=><p key={link.id}><a href={`/worlds/${worldId}?tab=${link.kind==="lore"?(link.family==="individual"?"individuals":"peoples"):"atlas"}&timeline=${link.timelineId}&${link.kind==="lore"?"entity":"place"}=${link.id}${review?"&review=1":""}${ordinary?`&knowledge=ordinary${link.kind==="geography"?"&ordinary=1":""}`:""}`}>{link.name}</a> · {link.eventType}</p>)}{bundle?.links.length===0&&<p>No related entities have been authored for this event.</p>}{canEdit&&bundle&&<details><summary>Link a World entity or place</summary><p>Connect this existing event without duplicating it. The event remains the authoritative historical account.</p><Field label="Related entity" help="Choose an active identity from this World and timeline, or an existing Atlas place."><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose a record</option>{bundle.choices.map(c=><option key={`${c.kind}:${c.id}`} value={`${c.kind}:${c.id}`}>{c.name}</option>)}</select></Field><Field label="Event relationship" help="Write an original relationship, such as founding, migration, affected population or discovery."><input value={eventType} onChange={e=>setEventType(e.target.value)}/></Field><button className="st-button is-secondary" disabled={pending||!target||!eventType.trim()} onClick={async()=>{setPending(true);setError("");try{const [kind,targetId]=target.split(":");await worldApi(`/api/worlds/${worldId}/milestones`,"POST",{timelineId,entryId,revision,targetId,kind,eventType});await onChanged();setTarget("");setEventType("");}catch(failure){setError((failure as Error).message);}finally{setPending(false);}}}>{pending?"Saving…":"Link existing event"}</button></details>}{error&&<p role="alert">{error}</p>}</section>;
}
