import assert from "node:assert/strict";
import test from "node:test";
import { historicalTimeSchema, eraDraftSchema, entryDraftSchema, timeBounds, timeLabel, worldDraftSchema, YEAR_LIMIT, type EntryRecord, type EraRecord, type HistoricalTime } from "./history";
import { fitHistory, gotoYear, groupTimelineEntries, panViewport, timelineTicks, zoomViewport } from "./timeline";
const time = (kind: "known" | "approximate", year: number): HistoricalTime => ({version:1,scale:"world-year",kind,year});
function entry(id:string, date:HistoricalTime):EntryRecord {return {id,worldId:"world",revision:1,archived:false,updatedAt:"2026-01-01",title:id,account:"An account",notes:"",time:date,accuracy:"established",narrative:"recorded",eraIds:[]};}
test("names-only world creation defaults optional material, never accepts client ownership",() => {assert.deepEqual(worldDraftSchema.parse({name:" My world "}),{name:"My world",description:"",introduction:"",historicalOverview:"",tone:"primary",tagIds:[]});assert.equal(worldDraftSchema.safeParse({name:"Mine",ownerId:"other"}).success,false);});
test("known zero, negative, approximate, window, duration and undated remain distinct",() => {
  for(const value of [time("known",0),time("approximate",-200),{version:1,scale:"world-year",kind:"window",startYear:100,endYear:110},{version:1,scale:"world-year",kind:"duration",startYear:100,endYear:110},{version:1,scale:"world-year",kind:"undated"}]) assert.equal(historicalTimeSchema.safeParse(value).success,true);
  assert.equal(timeBounds({version:1,scale:"world-year",kind:"undated"}),null);
  assert.equal(timeLabel({version:1,scale:"world-year",kind:"window",startYear:100,endYear:110}),"Sometime between 100 and 110");
  assert.equal(timeLabel({version:1,scale:"world-year",kind:"duration",startYear:100,endYear:110}),"Years 100–110");
});
test("historical time fails closed on malformed dates, reversed intervals and unknown versions",() => {for(const value of [time("known",1.5),time("known",YEAR_LIMIT+1),{version:2,scale:"world-year",kind:"known",year:1},{version:1,scale:"gregorian",kind:"known",year:1},{version:1,scale:"world-year",kind:"duration",startYear:5,endYear:1},{version:1,scale:"world-year",kind:"undated",year:0},{version:1,scale:"world-year",kind:"known",year:NaN}])assert.equal(historicalTimeSchema.safeParse(value).success,false);});
test("era boundaries may be open or overlap; reversed known boundaries fail",() => {for(const range of [[null,null],[null,0],[-100,null],[-100,100]])assert.equal(eraDraftSchema.safeParse({name:"Age",description:"",tone:"primary",startYear:range[0],endYear:range[1]}).success,true);assert.equal(eraDraftSchema.safeParse({name:"Age",startYear:10,endYear:-10}).success,false);});
test("planned and accuracy statuses remain independent",() => {for(const accuracy of ["established","disputed","unverified","disproven"]) { const result = entryDraftSchema.parse({title:"Plan",account:"A future event",notes:"",time:time("known",10),accuracy,narrative:"planned",eraIds:[]});assert.equal(result.narrative,"planned");assert.equal(result.accuracy,accuracy); }});
test("a trillion-year viewport uses bounded ticks and signed years",() => {const view = fitHistory([], [entry("old",time("known",-YEAR_LIMIT)),entry("new",time("known",YEAR_LIMIT))]);assert.equal(view.start,-YEAR_LIMIT);assert.equal(view.end,YEAR_LIMIT);assert.ok(timelineTicks(view).length <= 16);assert.ok(timelineTicks(view).includes(0));assert.ok(timelineTicks({start:-101,end:-1}).every((year)=>year < 0));});
test("zoom, pan, year jumps and fit preserve bounds and do not mutate dates",() => {const original = entry("zero",time("known",0));const copy=JSON.stringify(original);const fit=fitHistory([], [original]);assert.ok(fit.start < 0 && fit.end > 0);assert.ok(zoomViewport(fit,.5).end < fit.end);assert.ok(panViewport(fit,.4).start > fit.start);const target=gotoYear(fit,-1000000);assert.equal((target.start+target.end)/2,-1000000);assert.equal(JSON.stringify(original),copy);});
test("thousands of coincident events form a selectable group; undated is excluded",() => {const entries=Array.from({length:2000},(_,index)=>entry(String(index),time("known",100)));entries.push(entry("unknown",{version:1,scale:"world-year",kind:"undated"}));const groups=groupTimelineEntries(entries,{start:0,end:10000000},900);assert.equal(groups.length,1);assert.equal(groups[0].entries.length,2000);});
test("open and overlapping eras fit finite known boundaries",() => {const eras = [{id:"A",startYear:null,endYear:10},{id:"B",startYear:0,endYear:100}] as EraRecord[];const fit=fitHistory(eras,[]);assert.ok(fit.start < 0 && fit.end > 100);});
test("crowded markers retain distinct narrative and accuracy signals",()=>{const one=entry("recorded",time("known",100));const two={...entry("planned",time("known",100)),narrative:"planned" as const};const three={...entry("disputed",time("known",100)),accuracy:"disputed" as const};assert.equal(groupTimelineEntries([one,two,three],{start:0,end:1000},390).length,3);});
