import assert from "node:assert/strict";
import { randomUUID as id } from "node:crypto";
import test from "node:test";
import { defaultInteriorState, duplicateInteriorSource, interiorShapeSchema, interiorStateSchema, openingAnchor, transformInterior, validateInterior, wallSegments, type InteriorEntity, type InteriorShape } from "./interior";
function fixture(){const wallEntity=id(),doorEntity=id(),wall:InteriorShape={version:1,id:id(),entityId:wallEntity,archived:false,variant:"wall",width:10,points:[{id:id(),x:100,y:200},{id:id(),x:500,y:200}]},door:InteriorShape={version:1,id:id(),entityId:doorEntity,archived:false,variant:"opening",wallId:wall.id,startId:wall.points[0].id,endId:wall.points[1].id,at:.5,width:80,style:"door"},entities:InteriorEntity[]=[{id:wallEntity,revision:null,kind:"wall",name:"",description:"",classification:"",geographyId:null},{id:doorEntity,revision:null,kind:"opening",name:"Living stone",description:"The doorway remembers visitors.",classification:"",geographyId:null}];return {wall,door,shapes:[wall,door],entities};}
test("door creates two real wall segments, with an 80-unit gap",()=>{const {wall,shapes}=fixture();assert.deepEqual(wallSegments(wall,shapes),[{a:{x:100,y:200},b:{x:260,y:200}},{a:{x:340,y:200},b:{x:500,y:200}}]);});
test("attached opening follows angled wall movement and rotation",()=>{const f=fixture(),wall=transformInterior(f.wall,f.shapes,20,30,1,90);assert.equal(wall.variant,"wall");const a=openingAnchor(f.door,[wall,f.door]);assert.equal(a.x,320);assert.equal(a.y,230);assert.equal(a.angle,90);assert.deepEqual((wall as typeof f.wall).points.map(p=>({x:p.x,y:p.y})),[{x:320,y:30},{x:320,y:430}]);});
test("segment removal, shortening and archiving reject invalid active attachments",()=>{const f=fixture();assert.throws(()=>validateInterior([{...f.wall,points:[{...f.wall.points[0],id:id()},f.wall.points[1]]},f.door],f.entities),/removes a segment/);assert.throws(()=>validateInterior([{...f.wall,points:[f.wall.points[0],{...f.wall.points[1],x:130}]},f.door],f.entities),/no longer fits/);assert.throws(()=>validateInterior([{...f.wall,archived:true},f.door],f.entities),/active wall/);assert.doesNotThrow(()=>validateInterior([{...f.wall,archived:true},{...f.door,archived:true}],f.entities));});
test("overlapping gaps merge without wall remnants inside either opening",()=>{const f=fixture(),second={...f.door,id:id(),entityId:id(),at:.6};assert.deepEqual(wallSegments(f.wall,[...f.shapes,second]),[{a:{x:100,y:200},b:{x:260,y:200}},{a:{x:380,y:200},b:{x:500,y:200}}]);});
test("floor map duplication remaps wall and endpoint representation IDs, retaining entities",()=>{const f=fixture(),copy=duplicateInteriorSource(f.shapes,id);assert.notEqual(copy[0].id,f.wall.id);assert.equal(copy[0].entityId,f.wall.entityId);assert.equal(copy[1].entityId,f.door.entityId);assert.equal((copy[1] as typeof f.door).wallId,copy[0].id);assert.doesNotThrow(()=>validateInterior(copy,f.entities));assert.deepEqual(wallSegments(copy[0] as typeof f.wall,copy),wallSegments(f.wall,f.shapes));});
test("object transform preserves identity and exact pivot coordinates",()=>{const shape:InteriorShape={version:1,id:id(),entityId:id(),archived:false,variant:"object",point:{x:400,y:300},width:100,height:40,rotation:0,symbol:"table"};const next=transformInterior(shape,[shape],15,-20,1.5,90);assert.deepEqual(next,{...shape,point:{x:415,y:280},width:150,height:60,rotation:90});});
test("layer contracts reject missing and independent extra palettes",()=>{const state=defaultInteriorState();assert.equal(interiorStateSchema.safeParse(state).success,true);assert.equal(interiorStateSchema.safeParse({...state,layers:{room:{visible:true,locked:false}}}).success,false);assert.equal(interiorStateSchema.safeParse({...state,color:"red"}).success,false);});
test("openings require real attachment identities and valid width",()=>{const f=fixture();assert.equal(interiorShapeSchema.safeParse({...f.door,wallId:undefined}).success,false);assert.equal(interiorShapeSchema.safeParse({...f.door,width:0}).success,false);assert.throws(()=>validateInterior(f.shapes,[...f.entities,{...f.entities[0],id:id(),kind:"room"}]),/geographic identity/);});
