"use client";
import { useEffect, useRef, useState } from "react";
import { GuidedField } from "@/components/field-guidance";
import type { AtlasBundle, AtlasMap } from "./atlas";
import type { InteriorFloor } from "./interior";
import { worldApi } from "./client-api";
import styles from "./interior.module.css";
export type FloorTarget={buildingId?:string;floor?:InteriorFloor;additionalMap?:boolean};
export function InteriorDestinationFields({worldId,bundle,mapId,destinationMapId,destinationGeographyId}:{worldId:string;bundle:AtlasBundle;mapId:string;destinationMapId:string|null;destinationGeographyId:string|null}) {
 const [destination,setDestination]=useState(destinationMapId??""),[arrival,setArrival]=useState(destinationGeographyId??""),[source,setSource]=useState<AtlasBundle|null>(null),[error,setError]=useState("");
 useEffect(()=>{let alive=true;if(!destination)return;worldApi<AtlasBundle>(`/api/worlds/${worldId}/atlas?map=${destination}`).then(b=>{if(alive){setSource(b);setError("");}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[worldId,destination]);
 const target=source?.maps.find(m=>m.id===destination),ids=new Set([target?.geographyId,...(target?.dungeonEntities??[]).filter(e=>target?.dungeonShapes?.some(s=>s.entityId===e.id&&!s.archived)).flatMap(e=>e.geographyId?[e.geographyId]:[]),...(target?.interiorEntities??[]).filter(e=>target?.interiorShapes?.some(s=>s.entityId===e.id&&!s.archived)).flatMap(e=>e.geographyId?[e.geographyId]:[]),...(target?.settlementEntities??[]).map(e=>e.geographyId),...(target?.features??[]).map(f=>f.geographyId),...(target?.drawings??[]).flatMap(d=>d.geographyId?[d.geographyId]:[])]),places=(source?.geographies??[]).filter(g=>ids.has(g.id)&&!g.archived);
 return <><GuidedField label="Destination map" help="Choose an existing map explicitly. Unconnected transitions never invent floors or destinations."><select className="st-control" name="destinationMapId" value={destination} onChange={e=>{setDestination(e.target.value);setArrival("");setSource(null);}}><option value="">Unconnected</option>{bundle.maps.filter(m=>m.id!==mapId).map(m=><option key={m.id} value={m.id} disabled={(m.archived||m.unavailable)&&m.id!==destination}>{m.name}{m.archived||m.unavailable?" (unavailable; retained)":""}</option>)}</select></GuidedField><GuidedField label="Arrival place" help="Optional room, transition or place represented on the chosen map. Map overview leaves the arrival at that map's floor."><select className="st-control" name="arrival" value={arrival} onChange={e=>setArrival(e.target.value)}><option value="">Map overview</option>{arrival&&!places.some(g=>g.id===arrival)&&<option value={arrival}>Retained arrival (currently unavailable)</option>}{places.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField>{error&&<p className={styles.hint}>Destination unavailable. The existing connection is retained: {error}</p>}</>;
}
export function InteriorFloorDialog({target,bundle,onClose,onSave,onDirtyChange}:{target:FloorTarget;bundle:AtlasBundle;onClose:()=>void;onSave:(body:unknown)=>Promise<void>;onDirtyChange:(dirty:boolean)=>void}) {
 const dialog=useRef<HTMLDialogElement>(null),touched=useRef(false),[pending,setPending]=useState(false),[error,setError]=useState("");
 const floor=target.floor,[building,setBuilding]=useState(target.buildingId??floor?.buildingId??"");
 useEffect(()=>{dialog.current?.showModal();return()=>onDirtyChange(false);},[onDirtyChange]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(touched.current){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard);},[]);
 const close=()=>{if(pending||touched.current&&!window.confirm("Discard these unapplied floor fields?"))return;onClose();};
 // Buildings already loaded in settlement source retain their existing geography identity.
 const buildings=bundle.geographies.filter(g=>!g.archived&&(bundle.buildingIds?.includes(g.id)||bundle.floors?.some(f=>f.buildingId===g.id)||g.id===target.buildingId));
 return <dialog ref={dialog} className={styles.modal} aria-labelledby="interior-floor-title" onCancel={e=>{e.preventDefault();close();}}><form className={styles.dialog} onChange={()=>{touched.current=true;onDirtyChange(true);}} onSubmit={async e=>{e.preventDefault();const values=new FormData(e.currentTarget),name=String(values.get("name")),draft={name,classification:String(values.get("classification")??""),description:String(values.get("description")??""),label:String(values.get("label")??""),order:values.get("order")?Number(values.get("order")):null,elevation:String(values.get("elevation")??"")};setPending(true);setError("");try{await onSave(target.additionalMap?{action:"floor-map",floorId:floor!.id,name:String(values.get("mapName"))}:floor?{action:"edit-floor",id:floor.id,revision:floor.revision,geographyRevision:floor.geographyRevision,draft}:{action:"create-floor",buildingId:building,draft,mapName:String(values.get("mapName"))});touched.current=false;onDirtyChange(false);}catch(err){setError((err as Error).message);}finally{setPending(false);}}}>
 <h2 id="interior-floor-title">{target.additionalMap?"Another map of this floor":floor?"Edit floor information":"Create an interior floor"}</h2>{error&&<p role="alert">{error}</p>}<fieldset disabled={pending}>
 {!floor&&<GuidedField label="Existing building" help="The interior belongs to this building already authored in a settlement. Its identity is retained."><select className="st-control" required value={building} onChange={e=>setBuilding(e.target.value)}><option value="">Choose a building</option>{buildings.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></GuidedField>}
 {!target.additionalMap&&<><GuidedField label="Floor name" help="Any recognizable name works, including an impossible or disconnected interior space."><input className="st-control" name="name" required maxLength={160} defaultValue={floor?.name??""}/></GuidedField><GuidedField label="Floor description" help="Optional narrative detail. Creating a floor does not invent rooms or connections."><textarea className="st-control" name="description" rows={3} maxLength={12000} defaultValue={floor?.description??""}/></GuidedField><GuidedField label="Floor classification" help="Optional custom description, such as laboratory deck, living chamber or observatory wing."><input className="st-control" name="classification" maxLength={160} defaultValue={floor?.classification??""}/></GuidedField><GuidedField label="Level label" help="Optional free text, such as Basement, Deck 4 or Beyond the Mirror."><input className="st-control" name="label" maxLength={80} defaultValue={floor?.label??""}/></GuidedField><GuidedField label="Display order" help="Optional whole number; lower numbers appear first. Reordering keeps this floor's identity and connections."><input className="st-control" name="order" type="number" min={-100000} max={100000} defaultValue={floor?.order??""}/></GuidedField><GuidedField label="Elevation reference" help="Optional authored reference, with any units or meaning you choose. It does not enforce physical height."><input className="st-control" name="elevation" maxLength={80} defaultValue={floor?.elevation??""}/></GuidedField></>}
 {(!floor||target.additionalMap)&&<GuidedField label="Floor-plan map name" help="This editable drawing represents the floor. More maps can represent the same floor later."><input className="st-control" name="mapName" required maxLength={160} defaultValue={target.additionalMap?`${floor!.name} alternate plan`:""}/></GuidedField>}
 </fieldset><div className={styles.tools}><button className="st-button" disabled={pending}>{pending?"Saving...":floor&&!target.additionalMap?"Save floor information":"Create floor map"}</button><button type="button" className="st-button is-secondary" disabled={pending} onClick={close}>Cancel</button></div></form></dialog>;
}
export function InteriorFloorNavigation({bundle,map,buildingId,onOpen,onCreate,onEdit}:{bundle:AtlasBundle;map?:AtlasMap;buildingId?:string;onOpen:(id:string,place?:string)=>void;onCreate?:(buildingId:string)=>void;onEdit?:(floor:InteriorFloor)=>void}) {
 const floor=bundle.floors?.find(f=>f.id===map?.geographyId),building=buildingId??floor?.buildingId;if(!building)return null;
 const floors=(bundle.floors??[]).filter(f=>f.buildingId===building&&!f.archived).sort((a,b)=>(a.order??100001)-(b.order??100001)||a.name.localeCompare(b.name)),geo=bundle.geographies.find(g=>g.id===building),exteriors=bundle.maps.filter(m=>!m.archived&&!m.unavailable&&m.mapKind==="settlement"&&m.geographyId===geo?.parentId);
 return <section className={styles.floorBar} aria-label="Building floors"><div><strong>{geo?.name??"Building"}</strong>{floor&&<p>{floor.name}{floor.label?` / ${floor.label}`:""}{floor.elevation?` / ${floor.elevation}`:""}</p>}</div><label>Floor map <select className="st-control" aria-label="Choose floor map" value={map?.mapKind==="interior"?map.id:""} onChange={e=>{if(e.target.value)onOpen(e.target.value);}}><option value="">Choose a floor map</option>{floors.map(f=><optgroup key={f.id} label={f.label?`${f.name} (${f.label})`:f.name}>{bundle.maps.filter(m=>m.geographyId===f.id&&!m.archived&&!m.unavailable).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</optgroup>)}</select></label>{floor&&floor.classification&&<p>{floor.classification}</p>}{floor&&floor.description&&<p>{floor.description}</p>}{onCreate&&<button className="st-button is-secondary" onClick={()=>onCreate(building)}>Add floor</button>}{floor&&onEdit&&<button className="st-button is-secondary" onClick={()=>onEdit(floor)}>Edit floor information</button>}{floor&&exteriors.map(m=><button key={m.id} className="st-button is-secondary" onClick={()=>onOpen(m.id,building)}>Return to exterior: {m.name}</button>)}</section>;
}
