"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { accuracyLabels, dateLabels, narrativeLabels, type HistoricalTime } from "./history";
import { fieldLabels, loreFamilies, loreDraftSchema, emptyLore, type LoreDraft, type LoreFamily, type LoreList, type LoreRecord, type LoreReferences } from "./peoples";
import { worldApi, SaveError } from "./client-api";
import { Field } from "./world-field";
import { ChronologyYearInput } from "./chronology-year-input";
import { CalendarEntryFields } from "./calendar-entry-fields";
import { CalendarSourceDetails } from "./calendar-source-details";
import { formatTime, type DatingSystem } from "./chronology";
import { HistoricalSourceReader } from "./historical-source-reader";
import styles from "./peoples.module.css";

export function requestUuid(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const s=Array.from(b,x=>x.toString(16).padStart(2,"0")).join("");return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;}
const modeLabel={authored:"Authored here",inherited:"Pinned inherited source",pending:"Source needs a decision",excluded:"Source excluded",interpretation:"Local interpretation"};
function changeTime(kind:HistoricalTime["kind"]):HistoricalTime {return kind==="undated"?{version:1,scale:"world-year",kind}:kind==="known"||kind==="approximate"?{version:1,scale:"world-year",kind,year:NaN}:{version:1,scale:"world-year",kind,startYear:NaN,endYear:NaN};}
function TimeFields({value,onChange,system,prefix="Account"}:{value:HistoricalTime;onChange:(time:HistoricalTime)=>void;system?:DatingSystem|null;prefix?:string}) {return <div><Field label={`${prefix} date precision`} help="Dates describe authored information. An uncertain window, duration, approximate year and unknown date retain different meanings."><select value={value.kind} onChange={e=>onChange(changeTime(e.target.value as HistoricalTime["kind"]))}>{Object.entries(dateLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>{"year"in value&&<ChronologyYearInput key={`${prefix}-${value.kind}`} label={`${prefix} year`} value={Number.isFinite(value.year)?value.year:null} system={system} onChange={year=>onChange({...value,year:year??NaN})}/>} {"startYear"in value&&<><ChronologyYearInput key={`${prefix}-${value.kind}-start`} label={`${prefix} starting year`} value={Number.isFinite(value.startYear)?value.startYear:null} system={system} onChange={year=>onChange({...value,startYear:year??NaN})}/><ChronologyYearInput key={`${prefix}-${value.kind}-end`} label={`${prefix} ending year`} value={Number.isFinite(value.endYear)?value.endYear:null} system={system} onChange={year=>onChange({...value,endYear:year??NaN})}/></>}</div>;}

export function PeoplesWorkspace({worldId,timelineId,timelineName,review,canEdit,datingSystems,displaySystem,onDirty,onHistoryChanged}:{worldId:string;timelineId:string;timelineName:string;review:boolean;canEdit:boolean;datingSystems:DatingSystem[];displaySystem:DatingSystem|null;onDirty:(dirty:boolean)=>void;onHistoryChanged:()=>Promise<unknown>}) {
  const search=useSearchParams(),requested=search.get("entity");const [list,setList]=useState<LoreList|null>(null),[query,setQuery]=useState(""),[family,setFamily]=useState(""),[ordinary,setOrdinary]=useState(false),[refs,setRefs]=useState<LoreReferences|null>(null),[record,setRecord]=useState<LoreRecord|null>(null),[editor,setEditor]=useState<LoreDraft|null>(null),[generation,setGeneration]=useState(0),[error,setError]=useState(""),[pending,setPending]=useState(false),[dirty,setDirty]=useState(false),[notice,setNotice]=useState("");
  const params=useCallback((extra:Record<string,string>={})=>{const q=new URLSearchParams({timeline:timelineId,...extra});if(review)q.set("review","1");if(ordinary)q.set("ordinary","1");return q;},[timelineId,review,ordinary]);
  const [source,setSource]=useState<{entityId:string;versionId:string}|null>(null);
  const api=`/api/worlds/${worldId}/peoples`;
  const refreshVersion=useRef(0);
  const refresh=useCallback(async()=>{const version=++refreshVersion.current;const [rows,choices]=await Promise.all([worldApi<LoreList>(`${api}?${params({q:query,...(family?{family}:{})})}`),worldApi<LoreReferences>(`${api}?${params({refs:"1"})}`)]);if(version===refreshVersion.current){setList(rows);setRefs(choices);}return rows;},[api,params,query,family]);
  useEffect(()=>{let alive=true;const activeVersion=refreshVersion;const timer=setTimeout(()=>{refresh().catch(failure=>{if(alive)setError(failure.message);});},150);return()=>{alive=false;++activeVersion.current;clearTimeout(timer);};},[refresh]);
  useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
  useEffect(()=>{if(!requested)return;let alive=true;worldApi<LoreRecord>(`${api}?${params({record:requested})}`).then(result=>{if(alive){setRecord(result);setError("");}}).catch(failure=>{if(alive){setRecord(null);setError(failure.message);}});return()=>{alive=false;};},[api,params,requested,generation]);
  function navigate(id:string|null,saved=false){if(dirty&&!saved&&!window.confirm("Discard this unsaved record draft?"))return;setEditor(null);setDirty(false);if(!saved)setNotice("");if(!id)setRecord(null);const url=new URL(window.location.href);if(id)url.searchParams.set("entity",id);else url.searchParams.delete("entity");url.searchParams.set("tab","peoples");window.history.pushState(null,"",`${url.pathname}${url.search}`);}
  async function act(body:unknown){setPending(true);setError("");try{await worldApi(api,"POST",body);await refresh();setGeneration(g=>g+1);await onHistoryChanged();}catch(failure){setError((failure as Error).message);}finally{setPending(false);}}
  function create(kind:LoreFamily,subject?:string){const draft=emptyLore(kind);if(subject)draft.participants=[{targetId:subject,authoredReference:"",role:"subject",account:""}];setEditor(draft);}
  const choices=list?.records.filter(row=>!family||row.family===family)??[];
  return <section className={styles.workspace} aria-label="Peoples and origins"><header className={styles.heading}><div><h2>Peoples and origins</h2><p>{timelineName} · Private World authoring</p><p className={styles.caption}>Build a simple identity or develop its origins and relationships. These records change World lore; Campaign gameplay stays independent.</p></div>{canEdit&&!ordinary&&<div className={styles.actions}>{Object.entries(loreFamilies).map(([key,label])=><button key={key} className="st-button is-secondary" onClick={()=>create(key as LoreFamily)}>Create {label.toLowerCase()}</button>)}</div>}</header>
    <div className={styles.toolbar}><Field label="Search peoples and origins" help="Search saved names and record families in this timeline."><input value={query} maxLength={160} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Record family" help="Races, peoples, origin accounts and relationships are distinct records."><select value={family} onChange={e=>setFamily(e.target.value)}><option value="">All records</option>{Object.entries(loreFamilies).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><button className="st-button is-secondary" disabled={dirty} onClick={()=>{setOrdinary(!ordinary);setRecord(null);}}> {ordinary?"Return to author knowledge":"Ordinary knowledge preview"}</button></div>
    {ordinary&&<p role="status">Protected accounts, notes, sections and related references are omitted by the server. This private preview does not publish the World.</p>}{error&&<p role="alert" className={styles.feedback}>{error}</p>}
    {notice&&<p role="status">{notice}</p>}
    {requested&&record&&record.id===requested&&<article className={styles.section} aria-label="World entity details"><div className={styles.heading}><div><h3>{record.draft.name}</h3><p>{loreFamilies[record.family]} · {modeLabel[record.mode]}{record.archived?" · Archived":""}</p></div><button className="st-button is-secondary" onClick={()=>navigate(null)}>Close record</button></div><p>{formatTime(record.draft.time,displaySystem)} · {accuracyLabels[record.draft.accuracy]} · {narrativeLabels[record.draft.narrative]}</p><p className={styles.prose}>{record.draft.description}</p>{Object.entries(record.draft.fields).filter(([,value])=>!!value).map(([key,value])=><section key={key}><h4>{(fieldLabels[record.family] as Record<string,string>)[key]}</h4><p className={styles.prose}>{value}</p></section>)}
      {record.participants.length>0&&<section><h4>Participants and references</h4>{record.participants.map((p,i)=><p key={i}>{p.role}: {p.targetId?<button className="st-button is-ghost" onClick={()=>navigate(p.targetId)}>{p.name}{p.unavailable?" · unavailable":""}</button>:<span>{p.authoredReference} · unresolved authored reference</span>}{p.account&&<span className={styles.prose}> · {p.account}</span>}</p>)}</section>}
      {record.related.length>0&&<section><h4>Related accounts</h4>{record.related.map(r=><button key={r.id} className="st-button is-secondary" onClick={()=>navigate(r.id)}>{r.name}</button>)}</section>}
      {record.historyNames.length>0&&<section><h4>Pinned historical sources</h4>{record.historyNames.map(h=><p key={h.entityId}><button className="st-button is-secondary" onClick={()=>setSource({entityId:record.id,versionId:h.versionId})}>{h.name}</button> · retained source version</p>)}</section>}
      {record.milestoneRecords.length>0&&<section><h4>Historical milestones</h4>{record.milestoneRecords.map(m=><p key={m.id}><a href={`/worlds/${worldId}?tab=history&timeline=${timelineId}&entry=${m.id}${review?"&review=1":""}`}>{m.title}</a> · {m.eventType} · {formatTime(m.time,displaySystem)}{m.archived?" · archived event":""}</p>)}</section>}
      {record.draft.sections.map(s=><section key={s.id}><h4>{s.title}{s.protected?" · Protected":""}</h4><p className={styles.prose}>{s.body}</p></section>)}{record.draft.privateNotes&&<section><h4>Protected author notes</h4><p className={styles.prose}>{record.draft.privateNotes}</p></section>}{record.calendarSource&&<CalendarSourceDetails source={record.calendarSource} worldId={worldId} review={review}/>}
      {canEdit&&!ordinary&&<div className={styles.actions}>{["pending","excluded"].includes(record.mode)?<button className="st-button" disabled={pending} onClick={()=>{if(window.confirm("Deliberately include the complete source, including its uncertain or post-divergence information?"))act({action:"resolve",timelineId,id:record.id,revision:record.revision,decision:"include"});}}>Include complete source</button>:<><button className="st-button" disabled={pending||record.archived} onClick={()=>setEditor(record.draft)}>Edit record</button><button className="st-button is-secondary" disabled={pending} onClick={()=>{if(window.confirm(`${record.archived?"Restore":"Archive"} this timeline's account? Its identity and references will be retained.`))act({action:record.archived?"restore":"archive",timelineId,id:record.id,revision:record.revision});}}>{record.archived?"Restore record":"Archive record"}</button>{record.family!=="origin"&&<button className="st-button is-secondary" onClick={()=>create("origin",record.id)}>Write another origin</button>}</>}{record.mode!=="authored"&&record.mode!=="excluded"&&<button className="st-button is-secondary" disabled={pending} onClick={()=>act({action:"resolve",timelineId,id:record.id,revision:record.revision,decision:"exclude"})}>Exclude source</button>}{record.parentRevision!==null&&record.parentRevision!==record.sourceRevision&&record.mode!=="authored"&&<button className="st-button is-secondary" disabled={pending} onClick={()=>{if(window.confirm("Replace this selection with the parent's latest immutable source? Local versions remain preserved."))act({action:"accept-parent",timelineId,id:record.id,revision:record.revision,parentRevision:record.parentRevision,parentVersionId:record.parentVersionId});}}>Review latest parent source</button>}</div>}
    </article>}
    {!list&&<p>Opening private records…</p>}{list&&choices.length===0&&<p>No matching records yet. A Race or people can begin with just a name and optional description.</p>}<div className={styles.grid}>{choices.map(row=><button key={row.id} className={styles.card} onClick={()=>navigate(row.id)}><strong>{row.name}</strong><small>{loreFamilies[row.family]} · {modeLabel[row.mode]}{row.archived?" · Archived":""}</small></button>)}</div>
    {list?.hasMore&&<button className="st-button is-secondary" onClick={async()=>{const version=refreshVersion.current;try{const next=await worldApi<LoreList>(`${api}?${params({q:query,...(family?{family}:{}),offset:String(list.records.length)})}`);if(version===refreshVersion.current)setList({...next,records:[...list.records,...next.records]});}catch(failure){setError((failure as Error).message);}}}>Load more records</button>}
    {canEdit&&!ordinary&&refs&&refs.parent.filter(p=>!list?.records.some(r=>r.id===p.id)).length>0&&<details className={styles.section}><summary>New parent sources available for deliberate adoption</summary><p>No parent record is added here automatically.</p>{refs.parent.filter(p=>!list?.records.some(r=>r.id===p.id)).map(p=><p key={p.id}>{p.name} <button className="st-button is-secondary" disabled={pending} onClick={()=>act({action:"adopt-source",timelineId,id:p.id,revision:0,parentRevision:p.revision,parentVersionId:p.versionId})}>Review {p.name} source</button></p>)}</details>}
    {source&&source.entityId===requested&&<HistoricalSourceReader key={source.versionId} worldId={worldId} timelineId={timelineId} entityId={source.entityId} versionId={source.versionId} review={review} ordinary={ordinary} onClose={()=>setSource(null)}/>}
    {editor&&refs&&<LoreEditor key={generation} initial={editor} record={editor===record?.draft?record:null} worldId={worldId} timelineId={timelineId} timelineName={timelineName} refs={refs} systems={datingSystems} displaySystem={displaySystem} onDirty={setDirty} onClose={()=>setEditor(null)} onReload={async()=>{if(!record)throw new Error("Retry creation with this same draft.");const latest=await worldApi<LoreRecord>(`${api}?${params({record:record.id})}`);setRecord(latest);setEditor(latest.draft);setGeneration(g=>g+1);await refresh();}} onSave={async body=>{const saved=await worldApi<{id:string}>(api,"POST",body);setNotice("Record saved.");setEditor(null);setDirty(false);navigate(saved.id,true);setGeneration(g=>g+1);try{await refresh();await onHistoryChanged();}catch(failure){setNotice(`Saved successfully. ${(failure as Error).message} Reload this view to refresh its lists.`);}}}/>}
  </section>;
}

function LoreEditor({initial,record,worldId,timelineId,timelineName,refs,systems,displaySystem,onDirty,onClose,onReload,onSave}:{initial:LoreDraft;record:LoreRecord|null;worldId:string;timelineId:string;timelineName:string;refs:LoreReferences;systems:DatingSystem[];displaySystem:DatingSystem|null;onDirty:(dirty:boolean)=>void;onClose:()=>void;onReload:()=>Promise<void>;onSave:(body:unknown)=>Promise<void>}) {
  const dialog=useRef<HTMLDialogElement>(null),[draft,setDraft]=useState(initial),[original]=useState(JSON.stringify(initial)),[requestId]=useState(requestUuid),[error,setError]=useState(""),[conflict,setConflict]=useState(false),[pending,setPending]=useState(false),[discard,setDiscard]=useState(false);
  const [historySearch,setHistorySearch]=useState(""),[historyLimit,setHistoryLimit]=useState(60);
  const historyChoices=refs.history.filter(h=>h.name.toLowerCase().includes(historySearch.toLowerCase()));
  const dirty=JSON.stringify(draft)!==original;const system=systems.find(s=>s.id===draft.datingSystemId)??displaySystem;
  useEffect(()=>{dialog.current?.showModal();},[]);useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
  useEffect(()=>{if(!dirty)return;const before=(e:BeforeUnloadEvent)=>e.preventDefault();const link=(e:MouseEvent)=>{const a=(e.target as Element)?.closest("a[href]");if(a&&!window.confirm("Leave and discard this unsaved record draft?")){e.preventDefault();e.stopPropagation();}};window.addEventListener("beforeunload",before);document.addEventListener("click",link,true);return()=>{window.removeEventListener("beforeunload",before);document.removeEventListener("click",link,true);};},[dirty]);
  function close(){if(pending)return;if(dirty)setDiscard(true);else onClose();}
  function patch(value:Partial<LoreDraft>){setDraft(d=>({...d,...value}));setError("");}
  return <dialog ref={dialog} className={styles.dialog} aria-labelledby="lore-editor-title" onCancel={e=>{e.preventDefault();close();}}><form className={styles.form} onSubmit={async e=>{e.preventDefault();setError("");setConflict(false);const parsed=loreDraftSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join(" "));return;}setPending(true);try{await onSave(record?{action:"save",timelineId,id:record.id,revision:record.revision,draft:parsed.data}:{action:"create",timelineId,requestId,draft:parsed.data});}catch(failure){setError((failure as Error).message);setConflict(failure instanceof SaveError&&failure.status===409);}finally{setPending(false);}}}>
    <header className={styles.heading}><div><h2 id="lore-editor-title">{record?"Edit":"Create"} {loreFamilies[draft.family].toLowerCase()}</h2><p>{timelineName} · {record?.mode==="inherited"?"Saving creates a local interpretation":"World lore"}</p></div><button type="button" className="st-button is-secondary" onClick={close} disabled={pending}>Close editor</button></header>
    <fieldset disabled={pending}><Field label="Name" help="The display name does not define identity. A saved record retains its ID when renamed."><input required maxLength={160} value={draft.name} onChange={e=>patch({name:e.target.value})}/></Field><Field label={draft.family==="origin"?"Origin account":"Description"} help="Write your own account. Biology, mortality, political structures and a specific origin are never required."><textarea rows={5} value={draft.description} onChange={e=>patch({description:e.target.value})}/></Field>
      <details className={styles.section}><summary>Characteristics and authored detail</summary><div>{Object.entries(fieldLabels[draft.family]).map(([key,label])=><Field key={key} label={label} help="Optional creator-authored information. Leave irrelevant categories blank, or use an original custom section."><textarea rows={3} value={draft.fields[key]??""} onChange={e=>patch({fields:{...draft.fields,[key]:e.target.value}})}/></Field>)}</div></details>
      <details className={styles.section} open={draft.participants.length>0}><summary>Subjects, ancestry and related records</summary><p>Use several progenitors or original roles. Unresolved references preserve your account without creating a god, Creature or mechanical record. An origin needs a World record with the role “subject”.</p><div>{draft.participants.map((p,index)=><section key={index} className={styles.section}><Field label={`Participant ${index+1} reference`} help="Choose a saved World identity or select an unresolved authored reference."><select value={p.targetId??""} onChange={e=>patch({participants:draft.participants.map((p,i)=>i===index?{...p,targetId:e.target.value||null,authoredReference:""}:p)})}><option value="">Unresolved authored reference</option>{refs.entities.map(r=><option key={r.id} value={r.id}>{r.name}{r.archived?" · archived":""}</option>)}{p.targetId&&!refs.entities.some(r=>r.id===p.targetId)&&<option value={p.targetId}>Retained unavailable reference</option>}</select></Field>{!p.targetId&&<Field label={`Participant ${index+1} authored reference`} help="Name or describe an unknown creator, ancestor, source or original concept. This remains an attributed claim."><input value={p.authoredReference} onChange={e=>patch({participants:draft.participants.map((p,i)=>i===index?{...p,authoredReference:e.target.value}:p)})}/></Field>}<Field label={`Participant ${index+1} role`} help="Use subject for an origin's subject. Other roles are entirely custom, such as claimed creator, ancestor, supports or conflicts."><input value={p.role} onChange={e=>patch({participants:draft.participants.map((p,i)=>i===index?{...p,role:e.target.value}:p)})}/></Field><Field label={`Participant ${index+1} account`} help="Optional explanation or competing interpretation of this connection."><textarea value={p.account} onChange={e=>patch({participants:draft.participants.map((p,i)=>i===index?{...p,account:e.target.value}:p)})}/></Field><button type="button" className="st-button is-secondary" onClick={()=>patch({participants:draft.participants.filter((_,i)=>i!==index)})}>Remove participant {index+1}</button></section>)}<button type="button" className="st-button is-secondary" disabled={draft.participants.length>=100} onClick={()=>patch({participants:[...draft.participants,{targetId:null,authoredReference:"",role:"",account:""}]})}>Add participant</button></div></details>
      <details className={styles.section}><summary>Historical context and source notation</summary><p>This dates an authored account. It does not automatically infer a complete life, a founding event or a Campaign clock.</p><Field label="Enter account years using" help="This changes input notation while retaining canonical World years."><select value={draft.datingSystemId??""} onChange={e=>{const s=systems.find(s=>s.id===e.target.value);patch({datingSystemId:s?.id??null,datingSystemRevision:s?.revision});}}><option value="">Canonical World years</option>{systems.filter(s=>!s.archived||s.id===draft.datingSystemId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><TimeFields value={draft.time} onChange={time=>patch({time})} system={draft.datingSystemId?system:null}/><Field label="Historical reliability" help="This describes fictional historical reliability, independently of platform System Canon."><select value={draft.accuracy} onChange={e=>patch({accuracy:e.target.value as LoreDraft["accuracy"]})}>{Object.entries(accuracyLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Narrative status" help="Planned development remains separate from recorded history."><select value={draft.narrative} onChange={e=>patch({narrative:e.target.value as LoreDraft["narrative"]})}>{Object.entries(narrativeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><CalendarEntryFields worldId={worldId} value={draft.calendarDate} onChange={calendarDate=>patch({calendarDate})}/></details>
      <details className={styles.section} open={draft.milestones.length>0}><summary>Historical milestones</summary><p>Only milestones you explicitly author create History entries. The linked event is authoritative and editable from History. Dates can stay unknown. Archive an existing milestone in History to retain it.</p><div>{draft.milestones.map((m,index)=><section key={m.entryId??index} className={styles.section}><Field label={`Milestone ${index+1} type`} help="Use an original event type, such as emergence, founding, migration or transformation."><input value={m.eventType} onChange={e=>patch({milestones:draft.milestones.map((m,i)=>i===index?{...m,eventType:e.target.value}:m)})}/></Field><Field label={`Milestone ${index+1} title`} help="This will be the linked event's title in the existing History timeline."><input value={m.draft.title} onChange={e=>patch({milestones:draft.milestones.map((m,i)=>i===index?{...m,draft:{...m.draft,title:e.target.value}}:m)})}/></Field><Field label={`Milestone ${index+1} account`} help="Write the historical fact or claimed account once. Contradictory milestones remain separate accounts."><textarea value={m.draft.account} onChange={e=>patch({milestones:draft.milestones.map((m,i)=>i===index?{...m,draft:{...m.draft,account:e.target.value}}:m)})}/></Field><TimeFields prefix={`Milestone ${index+1}`} value={m.draft.time} onChange={time=>patch({milestones:draft.milestones.map((m,i)=>i===index?{...m,draft:{...m.draft,time}}:m)})}/><Field label={`Milestone ${index+1} reliability`} help="Retain disputed, unverified or disproven accounts without promoting them to truth."><select value={m.draft.accuracy} onChange={e=>patch({milestones:draft.milestones.map((m,i)=>i===index?{...m,draft:{...m.draft,accuracy:e.target.value as LoreDraft["accuracy"]}}:m)})}>{Object.entries(accuracyLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label={`Milestone ${index+1} narrative status`} help="A planned milestone does not become recorded history."><select value={m.draft.narrative} onChange={e=>patch({milestones:draft.milestones.map((m,i)=>i===index?{...m,draft:{...m.draft,narrative:e.target.value as LoreDraft["narrative"]}}:m)})}>{Object.entries(narrativeLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>{!m.entryId&&<button type="button" className="st-button is-secondary" onClick={()=>patch({milestones:draft.milestones.filter((_,i)=>i!==index)})}>Remove unsaved milestone {index+1}</button>}</section>)}<button type="button" className="st-button is-secondary" disabled={draft.milestones.length>=40} onClick={()=>patch({milestones:[...draft.milestones,{eventType:"",draft:{title:"",account:"",notes:"",time:{version:1,scale:"world-year",kind:"undated"},accuracy:draft.accuracy,narrative:draft.narrative,visibility:draft.visibility,eraIds:[]}}]})}>Add historical milestone</button></div></details>
      <details className={styles.section}><summary>Existing historical sources</summary><p>Select an existing event or era once; its immutable source notation stays pinned.</p><Field label="Find historical sources" help="Search retained event and era names before selecting a source."><input value={historySearch} onChange={e=>{setHistorySearch(e.target.value);setHistoryLimit(60);}}/></Field>{historyChoices.slice(0,historyLimit).map(h=><label key={h.entityId} className="st-field"><span><input type="checkbox" checked={draft.historyRefs.some(r=>r.entityId===h.entityId)} onChange={e=>patch({historyRefs:e.target.checked?[...draft.historyRefs,{entityId:h.entityId,versionId:h.versionId}]:draft.historyRefs.filter(r=>r.entityId!==h.entityId)})}/> {h.name}{h.archived?" · archived":""}</span></label>)}{historyChoices.length>historyLimit&&<button type="button" className="st-button is-secondary" onClick={()=>setHistoryLimit(n=>n+60)}>Show more historical sources</button>}</details>
      <details className={styles.section} open={draft.sections.length>0}><summary>Custom sections</summary>{draft.sections.map((s,index)=><section key={s.id}><Field label={`Custom section ${index+1} title`} help="Choose your own category rather than fitting original beings into predefined biology."><input value={s.title} onChange={e=>patch({sections:draft.sections.map((s,i)=>i===index?{...s,title:e.target.value}:s)})}/></Field><Field label={`Custom section ${index+1} content`} help="Your unrestricted authored detail."><textarea value={s.body} onChange={e=>patch({sections:draft.sections.map((s,i)=>i===index?{...s,body:e.target.value}:s)})}/></Field><label><input type="checkbox" checked={s.protected} onChange={e=>patch({sections:draft.sections.map((s,i)=>i===index?{...s,protected:e.target.checked}:s)})}/> Protected section</label><button type="button" className="st-button is-secondary" onClick={()=>patch({sections:draft.sections.filter((_,i)=>i!==index)})}>Remove section {index+1}</button></section>)}<button type="button" className="st-button is-secondary" disabled={draft.sections.length>=40} onClick={()=>patch({sections:[...draft.sections,{id:requestUuid(),title:"",body:"",protected:false}]})}>Add custom section</button></details>
      <details className={styles.section}><summary>Protected knowledge</summary><Field label="Knowledge visibility" help="All World records stay private. Protected records are also omitted from the ordinary-knowledge server preview."><select value={draft.visibility} onChange={e=>patch({visibility:e.target.value as LoreDraft["visibility"]})}><option value="ordinary">Ordinary World knowledge</option><option value="protected">Protected author knowledge</option></select></Field><Field label="Protected author notes" help="These notes remain available only in authorized author/review responses, never in ordinary previews."><textarea value={draft.privateNotes} onChange={e=>patch({privateNotes:e.target.value})}/></Field></details>
    </fieldset>{error&&<p role="alert" className={styles.feedback}>{error}</p>}{conflict&&record&&<button type="button" className="st-button is-secondary" disabled={pending} onClick={async()=>{if(!window.confirm("Discard this draft and load the latest saved record?"))return;try{await onReload();}catch(failure){setError((failure as Error).message);}}}>Load latest record</button>}{discard&&<p className={styles.feedback}>Discard this unsaved draft? <button type="button" className="st-button is-secondary" onClick={()=>setDiscard(false)}>Keep editing</button> <button type="button" className="st-button" onClick={onClose}>Discard draft</button></p>}<footer className={styles.actions}><button type="button" className="st-button is-secondary" onClick={close} disabled={pending}>Cancel</button><button className="st-button" type="submit" disabled={pending}>{pending?"Saving…":"Save record"}</button></footer>
  </form></dialog>;
}
