import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { and, asc, eq, inArray, sql } from "drizzle-orm";
import { db } from "@/db";
import { world } from "@/db/world-schema";
import { worldHistoryHead, worldHistoryVersion } from "@/db/world-timeline-schema";
import { worldLoreIdentity as identity, worldLoreVersion as version, worldLoreHead as head, worldSpeciesVersion as species, worldPeopleVersion as people, worldOriginVersion as origin, worldRelationshipVersion as relationship, worldCultureVersion as culture, worldCivilizationVersion as civilization, worldLanguageVersion as language, worldPopulationVersion as population, worldBeliefVersion as belief, worldTraditionVersion as tradition, worldIndividualVersion as individual, worldIndividualName as individualName, worldRelationshipPeriod as relationshipPeriod, worldLoreGeography as geography, worldLoreParticipant as participant, worldLoreSection as section, worldLoreHistory as history, worldLoreChange as change, worldHistoryVersionEntity as eventLink } from "@/db/world-peoples-schema";
import { worldReadAccess, worldWriteTransaction, WorldError, sourceDatingFor, changeHistoryInTransaction } from "./world-service";
import { selectedTimeline, type HistoryTx } from "./history-version-service";
import { loreCommandSchema, loreInheritance, LORE_LIMIT, type LoreDraft, type LoreRecord, type LoreSummary, type LoreList, type LoreReferences, type LoreFamily } from "./peoples";
import { entryDraftSchema, type EntryRecord } from "./history";
import type { HistoricalSnapshot } from "./branching-history";
import type { CalendarSource } from "./calendar-dates";
import { resolveHistoryCalendarSource } from "./calendar-evolution-service";

import {lorePlaces,entityGeographies,entitiesAtPlace,geographicSourceReview} from "./peoples-geography-service";

const unavailable = () => new WorldError("This World record or historical source is unavailable.",404);
const conflict = () => new WorldError("A newer version was saved in another tab. Your draft is retained. Load the latest record before saving again.",409);
const name = sql<string>`coalesce(${species.name},${people.name},${origin.name},${relationship.name},${culture.name},${civilization.name},${language.name},${population.name},${belief.name},${tradition.name},${individual.name})`;
function metadata(tx:HistoryTx,worldId:string,timelineId:string,ordinary=false) {
  return tx.select({id:head.entityId,family:version.family,name,revision:head.revision,versionId:head.versionId,mode:head.mode,archived:version.archived,time:version.time,sourceRevision:head.sourceRevision,sourceTimelineId:head.sourceTimelineId,classification:ordinary?sql<string>`case when ${individual.protectedFields} ? 'classification' then '' else coalesce(${individual.classification},'') end`:sql<string>`coalesce(${individual.classification},'')`,searchNames:ordinary?sql<string>`concat_ws(' ',case when not (${individual.protectedFields} ? 'aliases') then ${individual.aliases} end,case when not (${individual.protectedFields} ? 'titles') then ${individual.titles} end,(select string_agg(n.name,' ') from world_individual_name n where n.version_id=${version.id} and not n.protected))`:sql<string>`concat_ws(' ',${individual.aliases},${individual.titles},(select string_agg(n.name,' ') from world_individual_name n where n.version_id=${version.id}))`})
    .from(head).innerJoin(version,eq(version.id,head.versionId)).leftJoin(species,eq(species.versionId,version.id)).leftJoin(people,eq(people.versionId,version.id)).leftJoin(origin,eq(origin.versionId,version.id)).leftJoin(relationship,eq(relationship.versionId,version.id)).leftJoin(culture,eq(culture.versionId,version.id)).leftJoin(civilization,eq(civilization.versionId,version.id)).leftJoin(language,eq(language.versionId,version.id)).leftJoin(population,eq(population.versionId,version.id)).leftJoin(belief,eq(belief.versionId,version.id)).leftJoin(tradition,eq(tradition.versionId,version.id)).leftJoin(individual,eq(individual.versionId,version.id))
    .where(and(eq(head.worldId,worldId),eq(head.timelineId,timelineId),ordinary?and(inArray(head.mode,["authored","inherited","interpretation"]),eq(version.visibility,"ordinary"),sql`not (${version.family}='relationship' and exists(select 1 from world_lore_participant protected_participant where protected_participant.version_id=${version.id} and protected_participant.protected))`):undefined)).orderBy(asc(head.entityId)).limit(LORE_LIMIT+1);
}
async function summaries(tx:HistoryTx,worldId:string,timelineId:string,ordinary=false):Promise<LoreSummary[]> {
  const rows=await metadata(tx,worldId,timelineId,ordinary);if(rows.length>LORE_LIMIT)throw new WorldError("This timeline exceeds its retained entity limit.",400);
  const timeline=await selectedTimeline(tx,worldId,timelineId);
  const parents=!ordinary&&timeline.parentId?await tx.select({entityId:head.entityId,versionId:head.versionId,revision:head.revision}).from(head).innerJoin(version,eq(version.id,head.versionId)).where(and(eq(head.worldId,worldId),eq(head.timelineId,timeline.parentId),ordinary?and(inArray(head.mode,["authored","inherited","interpretation"]),eq(version.visibility,"ordinary"),sql`not (${version.family}='relationship' and exists(select 1 from world_lore_participant protected_participant where protected_participant.version_id=${version.id} and protected_participant.protected))`):undefined)).limit(LORE_LIMIT+1):[];
  const byId=new Map(parents.map(p=>[p.entityId,p]));
  return rows.map(row=>({...row,parentVersionId:byId.get(row.id)?.versionId??null,parentRevision:byId.get(row.id)?.revision??null}));
}
function clientSummary({searchNames:_,classification,...row}:LoreSummary):LoreSummary {void _;return {...row,...classification?{classification:classification.slice(0,160)}:{}};}
export async function listPeoples(userId:string,worldId:string,timelineId:string,review=false,ordinary=false,query="",offset=0,family?:LoreFamily,category="",lifecycle=""):Promise<LoreList> {
  const parent=await worldReadAccess(userId,worldId,review);
  return db.transaction(async tx=>{const timeline=await selectedTimeline(tx,worldId,timelineId);const all=await summaries(tx,worldId,timeline.id,ordinary);const filtered=all.filter(row=>(!family||row.family===family)&&`${row.name} ${row.family} ${row.searchNames??""}`.toLowerCase().includes(query.toLowerCase())&&(!category||(row.classification??"").toLowerCase().includes(category.toLowerCase()))&&(!lifecycle||row.archived===(lifecycle==="archived")));return {records:filtered.slice(offset,offset+100).map(clientSummary),hasMore:filtered.length>offset+100,canEdit:!review&&parent.ownerId===userId&&!parent.archivedAt&&!timeline.archivedAt,timelineName:timeline.name};},{isolationLevel:"repeatable read",accessMode:"read only"});
}
export async function peoplesReferences(userId:string,worldId:string,timelineId:string,review=false,ordinary=false):Promise<LoreReferences> {
  await worldReadAccess(userId,worldId,review);
  return db.transaction(tx=>peoplesReferencesInTransaction(tx,worldId,timelineId,ordinary),{isolationLevel:"repeatable read",accessMode:"read only"});
}
export async function peoplesReferencesInTransaction(tx:HistoryTx,worldId:string,timelineId:string,ordinary=false):Promise<LoreReferences>{
  const timeline=await selectedTimeline(tx,worldId,timelineId),rows=await summaries(tx,worldId,timelineId,ordinary);
    const historyRows=await tx.select({entityId:worldHistoryHead.entityId,versionId:worldHistoryVersion.id,name:sql<string>`coalesce(${worldHistoryVersion.payload}->>'title',${worldHistoryVersion.payload}->>'name')`,kind:sql<"entry"|"era">`case when ${worldHistoryVersion.entryId} is null then 'era' else 'entry' end`,archived:sql<boolean>`coalesce((${worldHistoryVersion.payload}->>'archived')::boolean,false)`}).from(worldHistoryHead).innerJoin(worldHistoryVersion,eq(worldHistoryVersion.id,worldHistoryHead.versionId)).where(and(eq(worldHistoryHead.worldId,worldId),eq(worldHistoryHead.timelineId,timeline.id),inArray(worldHistoryHead.mode,["authored","inherited","partial","interpretation"]),ordinary?sql`coalesce(${worldHistoryVersion.payload}->>'visibility','ordinary')='ordinary'`:undefined)).limit(5000);
    return {places:await lorePlaces(tx,worldId,ordinary),entities:rows.filter(row=>row.mode!=="pending"&&row.mode!=="excluded").map(({id,name,family,archived})=>({id,name,family,archived})),history:historyRows,parent:!ordinary&&timeline.parentId?(await summaries(tx,worldId,timeline.parentId,ordinary)).filter(p=>!rows.some(r=>r.id===p.id)).map(clientSummary):[]};

}
function calendarDraft(source:CalendarSource|null) { if(!source)return undefined;const start={versionId:source.start.versionId,revision:source.start.revision,date:source.start.date};return source.kind==="window"||source.kind==="duration"?{kind:source.kind,start,end:{versionId:source.end!.versionId,revision:source.end!.revision,date:source.end!.date}}:{kind:source.kind,start}; }
export function milestoneDraft(record:EntryRecord&{sourceEventType?:string}) { const eventType="sourceEventType"in record?record.sourceEventType:record.eventType;return entryDraftSchema.parse({...eventType?{eventType}:{},...record.prominence?{prominence:record.prominence}:{},title:record.title,account:record.account,notes:record.notes,visibility:record.visibility??"ordinary",time:record.time,accuracy:record.accuracy,narrative:record.narrative,eraIds:record.eraIds,datingSystemId:record.datingSystemId,datingSystemRevision:record.datingSystemRevision,calendarDate:calendarDraft(record.calendarSource??null)}); }
export async function entityMilestones(tx:HistoryTx,worldId:string,timelineId:string,loreId:string,ordinary=false) {
  const rows=await tx.select({payload:worldHistoryVersion.payload,revision:worldHistoryHead.revision,eventType:eventLink.eventType}).from(eventLink).innerJoin(worldHistoryHead,and(eq(worldHistoryHead.versionId,eventLink.versionId),eq(worldHistoryHead.timelineId,timelineId))).innerJoin(worldHistoryVersion,eq(worldHistoryVersion.id,worldHistoryHead.versionId)).where(and(eq(eventLink.worldId,worldId),eq(eventLink.loreId,loreId),inArray(worldHistoryHead.mode,["authored","inherited","partial","interpretation"]),ordinary?sql`coalesce(${worldHistoryVersion.payload}->>'visibility','ordinary')='ordinary'`:undefined)).limit(41);
  if(rows.length>40)throw new WorldError("This entity exceeds its supported 40 milestones.",400);
  return rows.map(row=>({...row.payload as EntryRecord,...(ordinary?{notes:""}:{}),revision:row.revision,eventType:row.eventType,sourceEventType:(row.payload as EntryRecord).eventType??""}));
}
async function detail(tx:HistoryTx,worldId:string,timelineId:string,id:string,ordinary=false):Promise<LoreRecord> {
  const rows=await summaries(tx,worldId,timelineId,ordinary),summary=rows.find(row=>row.id===id);if(!summary)throw unavailable();
  const [v]=await tx.select().from(version).where(eq(version.id,summary.versionId));
  const [typed]=summary.family==="species"?await tx.select().from(species).where(eq(species.versionId,v.id)):summary.family==="people"?await tx.select().from(people).where(eq(people.versionId,v.id)):summary.family==="origin"?await tx.select().from(origin).where(eq(origin.versionId,v.id)):summary.family==="relationship"?await tx.select().from(relationship).where(eq(relationship.versionId,v.id)):summary.family==="culture"?await tx.select().from(culture).where(eq(culture.versionId,v.id)):summary.family==="civilization"?await tx.select().from(civilization).where(eq(civilization.versionId,v.id)):summary.family==="language"?await tx.select().from(language).where(eq(language.versionId,v.id)):summary.family==="population"?await tx.select().from(population).where(eq(population.versionId,v.id)):summary.family==="belief"?await tx.select().from(belief).where(eq(belief.versionId,v.id)):summary.family==="tradition"?await tx.select().from(tradition).where(eq(tradition.versionId,v.id)):await tx.select().from(individual).where(eq(individual.versionId,v.id));
  if(!typed)throw unavailable();
  const {versionId:_,worldId:__,family:___,name:recordName,description,...storedFields}=typed;void _;void __;void ___;
  const protectedFields="protectedFields" in storedFields?storedFields.protectedFields as string[]:[];
  const fields=Object.fromEntries(Object.entries(storedFields).filter(([key])=>key!=="protectedFields"&&(!ordinary||!protectedFields.includes(key)))) as Record<string,string>;
  const nameAccounts=await tx.select({id:individualName.id,name:individualName.name,kind:individualName.kind,meaning:individualName.meaning,perspective:individualName.perspective,time:individualName.time,protected:individualName.protected}).from(individualName).where(and(eq(individualName.versionId,v.id),ordinary?eq(individualName.protected,false):undefined)).orderBy(asc(individualName.position));
  const relationshipPeriods=await tx.select({id:relationshipPeriod.id,label:relationshipPeriod.label,status:relationshipPeriod.status,account:relationshipPeriod.account,perspective:relationshipPeriod.perspective,beginning:relationshipPeriod.beginning,ending:relationshipPeriod.ending,protected:relationshipPeriod.protected}).from(relationshipPeriod).where(and(eq(relationshipPeriod.versionId,v.id),ordinary?eq(relationshipPeriod.protected,false):undefined)).orderBy(asc(relationshipPeriod.position));
  const visible=new Map(rows.map(row=>[row.id,row]));
  const participants=(await tx.select().from(participant).where(eq(participant.versionId,v.id)).orderBy(asc(participant.position))).filter(p=>!ordinary||(!p.protected&&(!p.targetId||visible.has(p.targetId)))).map(p=>({targetId:p.targetId,authoredReference:p.authoredReference,role:p.role,account:p.account,...p.protected?{protected:true}:{},family:p.targetId?visible.get(p.targetId)?.family:undefined,name:p.targetId?visible.get(p.targetId)?.name??"Retained unavailable reference":p.authoredReference,unavailable:!!p.targetId&&(!visible.has(p.targetId)||visible.get(p.targetId)!.archived||["pending","excluded"].includes(visible.get(p.targetId)!.mode))}));
  const sections=await tx.select({id:section.id,title:section.title,body:section.body,protected:section.protected}).from(section).where(and(eq(section.versionId,v.id),ordinary?eq(section.protected,false):undefined)).orderBy(asc(section.position));
  const historyRows=await tx.select({entityId:history.entityId,versionId:history.historyVersionId,name:sql<string>`coalesce(${worldHistoryVersion.payload}->>'title',${worldHistoryVersion.payload}->>'name')`}).from(history).innerJoin(worldHistoryVersion,eq(worldHistoryVersion.id,history.historyVersionId)).where(and(eq(history.versionId,v.id),ordinary?sql`coalesce(${worldHistoryVersion.payload}->>'visibility','ordinary')='ordinary'`:undefined));
  const inbound=await tx.selectDistinct({id:head.entityId}).from(participant).innerJoin(head,and(eq(head.versionId,participant.versionId),eq(head.timelineId,timelineId))).innerJoin(version,eq(version.id,head.versionId)).where(and(eq(participant.targetId,id),eq(participant.worldId,worldId),inArray(head.mode,["authored","inherited","interpretation"]),ordinary?eq(participant.protected,false):undefined,ordinary?eq(version.visibility,"ordinary"):undefined,ordinary?sql`not (${version.family}='relationship' and exists(select 1 from world_lore_participant pp where pp.version_id=${version.id} and pp.protected))`:undefined)).orderBy(asc(head.entityId)).limit(100);
  const relatedIds=new Set(inbound.map(r=>r.id));const related=rows.filter(row=>relatedIds.has(row.id)&&row.id!==id&&row.mode!=="pending"&&row.mode!=="excluded").slice(0,100);
  const geographies=await entityGeographies(tx,worldId,v.id,ordinary);
  const milestones=await entityMilestones(tx,worldId,timelineId,id,ordinary);
  const draft:LoreDraft={family:summary.family,name:recordName,description:ordinary&&protectedFields.includes("description")?"":description,fields,...summary.family==="individual"?{protectedFields:ordinary?[]:protectedFields,nameAccounts}:{},...summary.family==="relationship"?{relationshipPeriods}:{},time:v.time,accuracy:v.accuracy as LoreDraft["accuracy"],narrative:v.narrative,visibility:v.visibility,privateNotes:ordinary?"":v.privateNotes,geographies:geographies.map(({name:_,destinationName:__,unavailable:___,...g})=>{void _;void __;void ___;return g;}),participants:participants.map(({targetId,authoredReference,role,account,protected:secret})=>({targetId,authoredReference,role,account,...secret?{protected:true}:{}})),historyRefs:historyRows.map(({entityId,versionId})=>({entityId,versionId})),sections,datingSystemId:v.datingSystemId,datingSystemRevision:v.sourceDating?.revision,calendarDate:calendarDraft(v.calendarSource),milestones:milestones.filter(m=>!m.archived).map(m=>({entryId:m.id,revision:m.revision,eventType:m.eventType,draft:milestoneDraft(m)}))};
  return {...clientSummary(summary),draft,geographies,participants,historyNames:historyRows,related:related.map(clientSummary),milestoneRecords:milestones,sourceDating:v.sourceDating,calendarSource:v.calendarSource,authorId:v.authorId,createdAt:v.createdAt.toISOString()};
}
export async function getPeople(userId:string,worldId:string,timelineId:string,id:string,review=false,ordinary=false) { await worldReadAccess(userId,worldId,review);return db.transaction(tx=>detail(tx,worldId,timelineId,id,ordinary),{isolationLevel:"repeatable read",accessMode:"read only"}); }

async function appendVersion(tx:HistoryTx,userId:string,worldId:string,timelineId:string,entityId:string,draft:LoreDraft,previous?:LoreRecord,archived=false) {
  const retained=new Set(previous?.draft.participants.map(p=>p.targetId).filter(Boolean));const ids=[...new Set(draft.participants.flatMap(p=>p.targetId?[p.targetId]:[]))];
  const matches=ids.length?await tx.select({id:head.entityId,mode:head.mode,archived:version.archived}).from(head).innerJoin(version,eq(version.id,head.versionId)).where(and(eq(head.worldId,worldId),eq(head.timelineId,timelineId),inArray(head.entityId,ids))):[];
  if(ids.some(id=>!matches.some(m=>m.id===id&&(retained.has(id)||(!m.archived&&m.mode!=="pending"&&m.mode!=="excluded")))))throw new WorldError("Choose available participants in this World and timeline. Existing references may be retained.",400);
  if(draft.historyRefs.length){
    const sources=await tx.select({id:worldHistoryVersion.id,entityId:worldHistoryVersion.entityId}).from(worldHistoryVersion).where(and(eq(worldHistoryVersion.worldId,worldId),inArray(worldHistoryVersion.id,draft.historyRefs.map(r=>r.versionId))));
    const current=await tx.select({entityId:worldHistoryHead.entityId,versionId:worldHistoryHead.versionId}).from(worldHistoryHead).where(and(eq(worldHistoryHead.worldId,worldId),eq(worldHistoryHead.timelineId,timelineId),inArray(worldHistoryHead.entityId,draft.historyRefs.map(r=>r.entityId)),inArray(worldHistoryHead.mode,["authored","inherited","partial","interpretation"])));
    for(const ref of draft.historyRefs){if(!sources.some(r=>r.id===ref.versionId&&r.entityId===ref.entityId))throw unavailable();if(!previous?.draft.historyRefs.some(r=>r.entityId===ref.entityId&&r.versionId===ref.versionId)&&!current.some(r=>r.entityId===ref.entityId&&r.versionId===ref.versionId))throw conflict();}
  }
  const placeIds=[...new Set(draft.geographies.flatMap(g=>[g.geographyId,...g.destinationId?[g.destinationId]:[]]))];
  const retainedPlaces=new Set(previous?.draft.geographies.flatMap(g=>[g.geographyId,...g.destinationId?[g.destinationId]:[]])??[]);
  const availablePlaces=await lorePlaces(tx,worldId,false,placeIds);
  if(placeIds.some(id=>!availablePlaces.some(p=>p.id===id&&(!p.archived||retainedPlaces.has(id)))))throw new WorldError("Choose places from this World. Existing archived references may be retained.",400);
  const years=draft.time.kind==="undated"?[]:"year"in draft.time?[draft.time.year]:[draft.time.startYear,draft.time.endYear];
  const source=await sourceDatingFor(tx,worldId,draft.datingSystemId,draft.datingSystemRevision,years,previous?{datingSystemId:previous.draft.datingSystemId??null,sourceDating:previous.sourceDating}:undefined);
  const calendarSource=await resolveHistoryCalendarSource(tx,worldId,draft.calendarDate,previous?.calendarSource);
  const versionId=randomUUID();await tx.insert(version).values({id:versionId,worldId,entityId,family:draft.family,timelineId,authorId:userId,archived,time:draft.time,accuracy:draft.accuracy,narrative:draft.narrative,visibility:draft.visibility,privateNotes:draft.privateNotes,...source,calendarSource,startVersionId:calendarSource?.start.versionId??null,endVersionId:calendarSource?.end?.versionId??null});
  const keys={versionId,worldId,name:draft.name,description:draft.description};
  if(draft.family==="species")await tx.insert(species).values({...keys,...draft.fields});else if(draft.family==="people")await tx.insert(people).values({...keys,...draft.fields});else if(draft.family==="origin")await tx.insert(origin).values({...keys,...draft.fields});else if(draft.family==="relationship")await tx.insert(relationship).values({...keys,...draft.fields});else if(draft.family==="culture")await tx.insert(culture).values({...keys,...draft.fields});else if(draft.family==="civilization")await tx.insert(civilization).values({...keys,...draft.fields});else if(draft.family==="language")await tx.insert(language).values({...keys,...draft.fields});else if(draft.family==="population")await tx.insert(population).values({...keys,...draft.fields});else if(draft.family==="belief")await tx.insert(belief).values({...keys,...draft.fields});else if(draft.family==="tradition")await tx.insert(tradition).values({...keys,...draft.fields});else await tx.insert(individual).values({...keys,...draft.fields,protectedFields:draft.protectedFields??["privateReputation"]});
  if(draft.nameAccounts?.length)await tx.insert(individualName).values(draft.nameAccounts.map((n,position)=>({...n,position,versionId,worldId})));
  if(draft.relationshipPeriods?.length)await tx.insert(relationshipPeriod).values(draft.relationshipPeriods.map((p,position)=>({...p,position,versionId,worldId})));
  if(draft.geographies.length)await tx.insert(geography).values(draft.geographies.map((g,position)=>({...g,versionId,worldId,position})));
  if(draft.participants.length)await tx.insert(participant).values(draft.participants.map((p,position)=>({...p,versionId,worldId,position})));
  if(draft.sections.length)await tx.insert(section).values(draft.sections.map((s,position)=>({...s,versionId,worldId,position})));
  if(draft.historyRefs.length)await tx.insert(history).values(draft.historyRefs.map(r=>({versionId,worldId,entityId:r.entityId,historyVersionId:r.versionId})));
  return versionId;
}
async function audit(tx:HistoryTx,userId:string,action:string,row:typeof head.$inferInsert) { await tx.insert(change).values({worldId:row.worldId,timelineId:row.timelineId,entityId:row.entityId,versionId:row.versionId,revision:row.revision,actorId:userId,action}); }
async function personalAndGeographicReview(tx:HistoryTx,versionIds:string[],divergence:number) {
  const review=await geographicSourceReview(tx,versionIds,divergence);
  if(versionIds.length){const rows=await tx.select({id:version.id}).from(version).where(and(inArray(version.id,versionIds),sql`${version.family}='individual' or exists(select 1 from world_relationship_period p where p.version_id=${version.id}) or exists(select 1 from world_lore_participant p join world_lore_identity i on i.id=p.target_id and i.world_id=p.world_id where p.version_id=${version.id} and i.family='individual')`));for(const row of rows)review.add(row.id);}
  return review;
}
export async function inheritPeoples(tx:HistoryTx,userId:string,worldId:string,parentId:string,timelineId:string,divergence:number) {
  const sources=await tx.select({h:head,v:version}).from(head).innerJoin(version,eq(version.id,head.versionId)).where(and(eq(head.worldId,worldId),eq(head.timelineId,parentId))).limit(LORE_LIMIT+1);if(sources.length>LORE_LIMIT)throw new WorldError("The parent exceeds the supported entity limit.",400);
  const reviewSources=await personalAndGeographicReview(tx,sources.map(({v})=>v.id),divergence);
  const pins=sources.map(({h,v})=>({worldId,timelineId,entityId:h.entityId,versionId:v.id,revision:1,mode:h.mode==="pending"||h.mode==="excluded"?h.mode:(loreInheritance(v.time,v.archived,v.narrative,divergence)==="inherited"&&reviewSources.has(v.id)?"pending":loreInheritance(v.time,v.archived,v.narrative,divergence)),sourceTimelineId:parentId,sourceVersionId:v.id,sourceRevision:h.revision}));
  if(pins.length){await tx.insert(head).values(pins);await tx.insert(change).values(pins.map(row=>({worldId:row.worldId,timelineId:row.timelineId,entityId:row.entityId,versionId:row.versionId,revision:row.revision,actorId:userId,action:"inherit"})));}
}
export async function changePeople(userId:string,worldId:string,input:unknown) {
  return worldWriteTransaction(userId,worldId,async tx=>{
    const command=loreCommandSchema.parse(input),timeline=await selectedTimeline(tx,worldId,command.timelineId);if(timeline.archivedAt)throw new WorldError("Restore this timeline before editing.",400);
    const count=(await tx.select({n:sql<number>`count(*)::integer`}).from(identity).where(eq(identity.worldId,worldId)))[0].n;
    let entityId:string,previous:LoreRecord|undefined,current:typeof head.$inferSelect|undefined;
    if(command.action==="create"){
      const {geographies:creationGeographies,protectedFields:creationProtection,nameAccounts:creationNames,relationshipPeriods:creationPeriods,...legacyDraft}=command.draft;const hashDraft={...legacyDraft,...creationGeographies.length?{geographies:creationGeographies}:{},...creationProtection?.length?{protectedFields:creationProtection}:{},...creationNames?.length?{nameAccounts:creationNames}:{},...creationPeriods?.length?{relationshipPeriods:creationPeriods}:{}};const requestHash=createHash("sha256").update(JSON.stringify({timelineId:timeline.id,draft:hashDraft})).digest("hex");const [retry]=await tx.select().from(identity).where(and(eq(identity.worldId,worldId),eq(identity.creatorId,userId),eq(identity.requestId,command.requestId)));if(retry){if(retry.requestHash!==requestHash)throw conflict();return retry.id;}
      if(count>=LORE_LIMIT)throw new WorldError(`A World supports ${LORE_LIMIT} retained entity identities in this checkpoint.`,400);entityId=randomUUID();await tx.insert(identity).values({id:entityId,worldId,family:command.draft.family,originTimelineId:timeline.id,creatorId:userId,requestId:command.requestId,requestHash});
    }else{entityId=command.id;[current]=await tx.select().from(head).where(and(eq(head.worldId,worldId),eq(head.timelineId,timeline.id),eq(head.entityId,entityId)));if(command.action!=="adopt-source"&&!current)throw unavailable();if((current?.revision??0)!==command.revision)throw conflict();if(current)previous=await detail(tx,worldId,timeline.id,entityId);}
    let next:typeof head.$inferInsert;
    if(command.action==="resolve"||command.action==="accept-parent"||command.action==="adopt-source"){
      if(timeline.primary)throw new WorldError("Choose an alternate timeline to manage sources.",400);
      if(command.action==="resolve"){if(!current?.sourceTimelineId)throw unavailable();next={...current,mode:command.decision==="exclude"?"excluded":(await tx.select().from(version).where(eq(version.id,current.versionId)))[0].timelineId===timeline.id?"interpretation":"inherited",revision:current.revision+1};}
      else {if(!timeline.parentId||(command.action==="adopt-source"&&current)||(command.action==="accept-parent"&&!current?.sourceTimelineId))throw unavailable();const [parent]=await tx.select({h:head,v:version}).from(head).innerJoin(version,eq(version.id,head.versionId)).where(and(eq(head.timelineId,timeline.parentId),eq(head.worldId,worldId),eq(head.entityId,entityId)));if(!parent||parent.h.revision!==command.parentRevision||parent.v.id!==command.parentVersionId)throw conflict();next={worldId,timelineId:timeline.id,entityId,versionId:parent.v.id,revision:(current?.revision??0)+1,sourceTimelineId:timeline.parentId,sourceVersionId:parent.v.id,sourceRevision:parent.h.revision,mode:parent.h.mode==="pending"||parent.h.mode==="excluded"?parent.h.mode:(loreInheritance(parent.v.time,parent.v.archived,parent.v.narrative,timeline.divergenceYear!)==="inherited"&&(await personalAndGeographicReview(tx,[parent.v.id],timeline.divergenceYear!)).has(parent.v.id)?"pending":loreInheritance(parent.v.time,parent.v.archived,parent.v.narrative,timeline.divergenceYear!))};}
    }else{
      if(current&&["pending","excluded"].includes(current.mode))throw new WorldError("Explicitly include this source before editing its interpretation.",400);
      const draft=command.action==="create"||command.action==="save"?command.draft:previous!.draft;
      if(previous&&draft.family!==previous.family)throw new WorldError("Keep this entity's family; create a different identity deliberately.",400);
      if(command.action==="save"&&previous?.archived)throw new WorldError("Restore this record before editing.",400);
      if(command.action==="create"||command.action==="save"){const existing=new Set(previous?.milestoneRecords.map(m=>m.id)??[]);let added=0;for(const m of draft.milestones){if(m.entryId)existing.add(m.entryId);else added++;}if(existing.size+added>40)throw new WorldError("This entity supports 40 retained milestones, including archived accounts.",400);}
      const versionId=await appendVersion(tx,userId,worldId,timeline.id,entityId,draft,previous,command.action==="archive");
      next={worldId,timelineId:timeline.id,entityId,versionId,revision:(current?.revision??0)+1,mode:current?.sourceTimelineId?"interpretation":"authored",sourceTimelineId:current?.sourceTimelineId??null,sourceVersionId:current?.sourceVersionId??null,sourceRevision:current?.sourceRevision??null};
      if(command.action==="create"||command.action==="save")for(const milestone of draft.milestones){
        let old:EntryRecord|undefined;
        if(milestone.entryId){const [h]=await tx.select({v:worldHistoryVersion,h:worldHistoryHead}).from(worldHistoryHead).innerJoin(worldHistoryVersion,eq(worldHistoryVersion.id,worldHistoryHead.versionId)).where(and(eq(worldHistoryHead.worldId,worldId),eq(worldHistoryHead.timelineId,timeline.id),eq(worldHistoryHead.entityId,milestone.entryId),inArray(worldHistoryHead.mode,["authored","inherited","interpretation"])));if(!h||!h.v.entryId)throw unavailable();if(h.h.revision!==milestone.revision)throw conflict();old={...h.v.payload as EntryRecord,revision:h.h.revision};}
        const eventDraft={...milestone.draft,visibility:draft.visibility==="protected"||(draft.family==="relationship"&&(draft.participants.some(p=>p.protected)||draft.relationshipPeriods?.some(p=>p.protected)))?"protected":milestone.draft.visibility??draft.visibility};
        // An unchanged linked fact does not create a new fictional event or historical revision.
        const [existingLink]=old?await tx.select().from(eventLink).where(and(eq(eventLink.targetId,entityId),eq(eventLink.entryId,old.id),eq(eventLink.versionId,(await tx.select().from(worldHistoryHead).where(and(eq(worldHistoryHead.timelineId,timeline.id),eq(worldHistoryHead.entityId,old.id))))[0].versionId))):[];
        const unchanged=old&&existingLink&&existingLink.eventType===milestone.eventType&&JSON.stringify(milestoneDraft(old))===JSON.stringify(entryDraftSchema.parse(eventDraft));
        const entryId=unchanged?old!.id:await changeHistoryInTransaction(tx,userId,worldId,{entity:"entry",timelineId:timeline.id,action:"save",id:milestone.entryId,revision:milestone.revision,draft:eventDraft});
        const [eventHead]=await tx.select().from(worldHistoryHead).where(and(eq(worldHistoryHead.timelineId,timeline.id),eq(worldHistoryHead.entityId,entryId)));
        const [link]=await tx.select().from(eventLink).where(and(eq(eventLink.versionId,eventHead.versionId),eq(eventLink.targetId,entityId)));
        if(!link||link.eventType!==milestone.eventType)await tx.insert(eventLink).values({versionId:eventHead.versionId,worldId,entryId,targetId:entityId,loreId:entityId,entityCategory:draft.family,eventType:milestone.eventType}).onConflictDoUpdate({target:[eventLink.versionId,eventLink.targetId],set:{eventType:milestone.eventType}});
      }
    }
    if(current)await tx.update(head).set(next).where(and(eq(head.timelineId,timeline.id),eq(head.entityId,entityId)));else await tx.insert(head).values(next);
    await audit(tx,userId,command.action,next);await tx.update(world).set({updatedAt:new Date()}).where(eq(world.id,worldId));return entityId;
  });
}

export async function pinnedHistoricalSource(userId:string,worldId:string,timelineId:string,entityId:string,versionId:string,review=false,ordinary=false):Promise<HistoricalSnapshot>{
  await worldReadAccess(userId,worldId,review);
  return db.transaction(async tx=>{
    await selectedTimeline(tx,worldId,timelineId);
    const [source]=await tx.select({payload:worldHistoryVersion.payload}).from(head).innerJoin(version,eq(version.id,head.versionId)).innerJoin(history,eq(history.versionId,head.versionId)).innerJoin(worldHistoryVersion,eq(worldHistoryVersion.id,history.historyVersionId)).where(and(eq(head.worldId,worldId),eq(head.timelineId,timelineId),eq(head.entityId,entityId),eq(history.historyVersionId,versionId),ordinary?and(inArray(head.mode,["authored","inherited","interpretation"]),eq(version.visibility,"ordinary"),sql`not (${version.family}='relationship' and exists(select 1 from world_lore_participant protected_participant where protected_participant.version_id=${version.id} and protected_participant.protected))`):undefined,ordinary?sql`coalesce(${worldHistoryVersion.payload}->>'visibility','ordinary')='ordinary'`:undefined));
    if(!source)throw unavailable();return ordinary&&"time"in source.payload?{...source.payload,notes:""}:source.payload;
  },{isolationLevel:"repeatable read",accessMode:"read only"});
}

export async function peoplesAtPlace(userId:string,worldId:string,timelineId:string,placeId:string,review=false,ordinary=false,offset=0,query="",family?:LoreFamily,category="",lifecycle=""){
  const owner=await worldReadAccess(userId,worldId,review);
  return db.transaction(async tx=>{const timeline=await selectedTimeline(tx,worldId,timelineId);if(!(await lorePlaces(tx,worldId,ordinary,[placeId])).length)throw unavailable();const ids=await entitiesAtPlace(tx,worldId,timelineId,placeId,ordinary);const rows=(await summaries(tx,worldId,timelineId,ordinary)).filter(r=>ids.has(r.id)&&(!family||r.family===family)&&`${r.name} ${r.family} ${r.searchNames??""}`.toLowerCase().includes(query.toLowerCase())&&(!category||(r.classification??"").toLowerCase().includes(category.toLowerCase()))&&(!lifecycle||r.archived===(lifecycle==="archived")));return {canEdit:!review&&owner.ownerId===userId&&!owner.archivedAt&&!timeline.archivedAt,timelineName:timeline.name,records:rows.slice(offset,offset+100).map(clientSummary),hasMore:rows.length>offset+100};},{isolationLevel:"repeatable read",accessMode:"read only"});
}
