"use client";
import { useEffect, useLayoutEffect, useMemo, useRef, useState, type PointerEvent, type FormEvent } from "react";
import { GuidedField } from "@/components/field-guidance";
import { acceptSavedHistory, boundedPoint, commitAction, draftOf, fitViewport, redoAction, rounded, mapDraftSchema, undoAction, validateMapDraft, zoomViewport, type AtlasBundle, type EditingHistory, type MapDraft, type Point, type Vertex } from "./atlas";
import type { AtlasMapEditor } from "./atlas-map-editor";
import { CartographyScene } from "./cartography-scene";
import { InteriorFloorNavigation, InteriorDestinationFields } from "./interior-floors";
import { furnishings, geographicInterior, interiorEntitySchema, interiorLayers, openingAnchor, openingStyles, transitions, type InteriorFloor } from "./interior";
import { dungeonEntitySchema, passageAppearances, dungeonLayers, geographicDungeon, planBaseShapes, duplicatePlanSource as duplicateInteriorSource, transformPlan as transformInterior, snapDungeonPoint, type PlanEntity as InteriorEntity, type PlanShape as InteriorShape, type DungeonLevel, type DungeonState } from "./dungeon";
import { DungeonLevelNavigation, DungeonGridFields } from "./dungeon-levels";
import styles from "./interior.module.css";
type Tool="circle"|"cavern"|"corridor"|"terrainpath"|"surface"|"trap"|"hazard"|"secret"|"annotation"|"select"|"move"|"points"|"pan"|"rectangle"|"room"|"wall"|"opening"|"window"|"transition"|"furnishing"|"landmark";
const interiorTools:Tool[]=["select","move","points","pan","rectangle","room","wall","opening","window","transition","furnishing","landmark"];
const labels:Record<Tool,string>={circle:"Round chamber",cavern:"Cavern outline",corridor:"Corridor / tunnel",terrainpath:"Water / chasm / terrain path",surface:"Surface area",trap:"Trap / alarm",hazard:"Hazard / phenomenon",secret:"Secret passage",annotation:"Private annotation",select:"Select",move:"Move",points:"Edit points",pan:"Pan",rectangle:"Rectangle room",room:"Polygon room",wall:"Wall path",opening:"Door / opening",window:"Window",transition:"Stairs / transition",furnishing:"Furnishing",landmark:"Custom landmark"};
const help:Record<Tool,string>={circle:"Tap the center and an edge. The circular-looking chamber retains editable boundary vertices.",cavern:"Tap an irregular cavern boundary, then Complete drawing. Every point remains editable.",corridor:"Tap passage points, then Complete drawing. Change width and appearance to author halls, branching tunnels and junctions.",terrainpath:"Tap an environmental path, then Complete drawing. Choose water, chasm, rubble or other appearance without simulation.",surface:"Tap a surface boundary, then Complete drawing. Name and describe any terrain or material.",trap:"Tap to place an authored trap or alarm. Its information never executes rolls or effects.",hazard:"Tap to place any environmental danger or unusual phenomenon. Effects remain narrative.",secret:"Tap a hidden passage path, then Complete drawing. Server previews omit protected records.",annotation:"Tap to place an author annotation. Its private notes are omitted from ordinary-content server previews.",select:"Tap an object or find it in the list to read and edit its information.",move:"Drag an editable object. Wall openings follow their attached segment; drag an opening along that segment.",points:"Select a room or wall, then drag its boundary points or edit their coordinates below.",pan:"Drag to pan. Zoom and Fit plan change only your view.",rectangle:"Tap two opposite corners. Room boundaries are editable and do not require walls.",room:"Tap boundary points, then Complete drawing. Rooms may overlap or form unconventional spaces.",wall:"Tap connected wall points, then Complete drawing. Openings attach to individual wall segments.",opening:"Tap near an editable wall segment to create a real gap. Edit its style, width and segment position below.",window:"Tap near an editable wall to attach a window. It remains associated with that wall segment.",transition:"Tap to place a transition. Choose its real destination in the information panel; connections are never automatic.",furnishing:"Tap to place a furnishing. These are authored World details, with no inventory or gameplay rules.",landmark:"Tap to place a meaningful custom object. Its stable location identity can retain any narrative description."};
type Props=Parameters<typeof AtlasMapEditor>[0]&{worldId:string;bundle:AtlasBundle;onOpenMap:(id:string,place?:string)=>void;onAddFloor:(buildingId:string)=>void;onEditFloor:(floor:InteriorFloor)=>void;onAddDungeonLevel?:(siteId:string)=>void;onEditDungeonLevel?:(level:DungeonLevel)=>void;onOrdinaryPreview?:()=>void};
type Gesture={pointer:number;start:Point;view:ReturnType<typeof fitViewport>;draft:MapDraft;shapeId?:string;vertexId?:string};
export function PlanEditor({worldId,map,geographies,canEdit,onDirtyChange,onClose,onSave,onReload,onExplore,onConnections,bundle,onOpenMap,onAddFloor,onEditFloor,onAddDungeonLevel,onEditDungeonLevel,onOrdinaryPreview,onPlaceHistory}:Props) {
 const isDungeon=map.mapKind==="dungeon",shapeKey=isDungeon?"dungeonShapes":"interiorShapes",entityKey=isDungeon?"dungeonEntities":"interiorEntities",stateKey=isDungeon?"dungeonState":"interiorState",linkKey=isDungeon?"dungeonLinks":"interiorLinks",layers=isDungeon?dungeonLayers:interiorLayers;
 const tools:Tool[]=isDungeon?["select","move","points","pan","rectangle","room","circle","cavern","corridor","wall","opening","transition","terrainpath","surface","trap","hazard","secret","furnishing","landmark","annotation"]:interiorTools;
 const [newVisibility,setNewVisibility]=useState<"ordinary"|"secret"|"god-only">("ordinary"),[appearance,setAppearance]=useState("constructed");
 const [history,setHistory]=useState<EditingHistory>(()=>({past:[],present:draftOf(map,geographies),future:[]})),historyRef=useRef(history),[saved,setSaved]=useState(()=>JSON.stringify(history.present)),[revision,setRevision]=useState(map.revision),[tool,setTool]=useState<Tool>("select"),[selectedId,setSelected]=useState<string|null>(null),[trace,setTrace]=useState<Vertex[]>([]),[traceFuture,setTraceFuture]=useState<Vertex[]>([]),[view,setView]=useState(fitViewport),[preview,setPreview]=useState<MapDraft|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[pending,setPending]=useState(false),[fieldsDirty,setFieldsDirty]=useState(false),[query,setQuery]=useState(""),[symbol,setSymbol]=useState("table"),[transition,setTransition]=useState("stairs"),[openingStyle,setOpeningStyle]=useState("door"),[vertexId,setVertex]=useState(""),[comparison,setComparison]=useState<string|null>(null),[formGeneration,setFormGeneration]=useState(0),[units,setUnits]=useState(2);
 const svg=useRef<SVGSVGElement>(null),gesture=useRef<Gesture|null>(null),frame=useRef<number|null>(null),queued=useRef<()=>void>(()=>{}),previewRef=useRef<MapDraft|null>(null),fieldForms=useRef(new Set<HTMLFormElement>());
 const draft=history.present,shapes=draft[shapeKey]! as InteriorShape[],entities=draft[entityKey]! as InteriorEntity[],state=draft[stateKey]!,dirty=JSON.stringify(draft)!==saved||trace.length>0||fieldsDirty;
 const entityIndex=useMemo(()=>new Map(entities.map(e=>[e.id,e])),[entities]),selected=shapes.find(s=>s.id===selectedId),entity=selected?entityIndex.get(selected.entityId):null;
 useLayoutEffect(()=>{const node=svg.current;if(!node)return;const resize=()=>setUnits(Math.max(view.width/node.clientWidth,view.height/node.clientHeight));const observer=new ResizeObserver(resize);observer.observe(node);resize();return()=>observer.disconnect();},[view]);
 const editable=(kind:InteriorEntity["kind"])=>canEdit&&!pending&&(state.layers as Record<string,{visible:boolean;locked:boolean}>)[kind].visible&&!(state.layers as Record<string,{visible:boolean;locked:boolean}>)[kind].locked;
 const associatedEditable=(s:InteriorShape)=>editable(entityIndex.get(s.entityId)!.kind)&&(s.variant!=="opening"||editable("wall"))&&(s.variant!=="wall"||shapes.filter(n=>n.variant==="opening"&&!n.archived&&n.wallId===s.id).every(n=>editable(entityIndex.get(n.entityId)!.kind)));
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};const click=(e:MouseEvent)=>{if(dirty&&(e.target as Element).closest("a[href]")&&!window.confirm("Discard the unsaved interior drawing and unapplied fields?")){e.preventDefault();e.stopPropagation();}};let returning=false;const back=(e:PopStateEvent)=>{if(returning){returning=false;return;}if(dirty&&!window.confirm("Discard unsaved interior changes and leave this map?")){e.stopImmediatePropagation();returning=true;window.history.go(1);}};window.addEventListener("popstate",back,true);window.addEventListener("beforeunload",unload);document.addEventListener("click",click,true);return()=>{window.removeEventListener("popstate",back,true);window.removeEventListener("beforeunload",unload);document.removeEventListener("click",click,true);};},[dirty]);
 useEffect(()=>()=>{if(frame.current!==null)cancelAnimationFrame(frame.current);},[]);
 function discardFields(){fieldForms.current.forEach(f=>f.reset());fieldForms.current.clear();setFieldsDirty(false);setFormGeneration(n=>n+1);}
 function guard(run:()=>void){if(dirty&&!window.confirm("Discard this unsaved interior draft, unfinished drawing and unapplied fields?"))return;run();}
 function select(id:string|null){if(fieldsDirty&&!window.confirm("Discard unapplied object fields?"))return;discardFields();setSelected(id);setVertex("");setError("");}
 function change(next:MapDraft){try{mapDraftSchema.parse(next);validateMapDraft(next);const h=commitAction(historyRef.current,next);historyRef.current=h;setHistory(h);setError("");setNotice("");return true;}catch(e){setError((e as Error).message);return false;}}
 function replace(s:InteriorShape){if(!associatedEditable(s)){setError("The object or an attached wall/opening layer is hidden or locked. Make those layers visible and editable first.");return false;}return change({...draft,[shapeKey]:shapes.map(n=>n.id===s.id?s:n)});}
 function point(e:PointerEvent<SVGSVGElement>):Point {const matrix=svg.current?.getScreenCTM();if(!matrix)return {x:0,y:0};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return isDungeon?snapDungeonPoint(boundedPoint(p),(state as DungeonState).grid):boundedPoint(p);}
 function add(s:Omit<Extract<InteriorShape,{variant:"area"}>,"id"|"entityId"|"version"|"archived">|Omit<Extract<InteriorShape,{variant:"wall"}>,"id"|"entityId"|"version"|"archived">|Omit<Extract<InteriorShape,{variant:"object"}>,"id"|"entityId"|"version"|"archived">|Omit<Extract<InteriorShape,{variant:"passage"}>,"id"|"entityId"|"version"|"archived">|Omit<Extract<InteriorShape,{variant:"opening"}>,"id"|"entityId"|"version"|"archived">,kind:InteriorEntity["kind"]) {
  if(!editable(kind))return;const id=crypto.randomUUID(),shapeId=crypto.randomUUID(),e:InteriorEntity={id,revision:null,kind,name:"",description:"",classification:"",geographyId:(isDungeon?geographicDungeon(kind):geographicInterior(kind as Parameters<typeof geographicInterior>[0]))?id:null,...(isDungeon?{visibility:tool==="secret"?"secret" as const:tool==="annotation"?"god-only" as const:newVisibility,privateNotes:""}:{})} as InteriorEntity;
  const next:MapDraft={...draft,[shapeKey]:[...shapes,{...s,version:1,id:shapeId,entityId:id,archived:false} as InteriorShape],[entityKey]:[...entities,e],geographies:(isDungeon?geographicDungeon(kind):geographicInterior(kind as Parameters<typeof geographicInterior>[0]))?[...draft.geographies,{id,revision:null,name:`Unnamed ${kind}`,description:"",kind:"location",context:isDungeon?"dungeon" as const:"interior" as const,parentId:map.geographyId!}]:draft.geographies,[linkKey]:kind==="transition"?[...draft[linkKey]!,{entityId:id,destinationMapId:null,destinationGeographyId:null}]:draft[linkKey]};if(change(next)){select(shapeId);setTrace([]);setTraceFuture([]);}
 }
 function complete(){if(tool==="wall")add({variant:"wall",points:trace,width:10},"wall");else if(["corridor","secret","terrainpath"].includes(tool))add({variant:"passage",points:trace,width:tool==="terrainpath"?60:80,appearance:appearance as "constructed"},tool==="terrainpath"?"terrain":"corridor");else add({variant:"area",points:trace},tool==="cavern"?"cavern":tool==="surface"?"terrain":"room");}
 function attach(p:Point){if(!editable("wall")||!editable(tool==="window"?"window":"opening")){setError("Show and unlock both the wall and opening layers first.");return;}
  const options=shapes.filter((s):s is Extract<InteriorShape,{variant:"wall"}>=>s.variant==="wall"&&!s.archived).flatMap(w=>w.points.slice(0,-1).map((a,i)=>{const b=w.points[i+1],length=Math.hypot(b.x-a.x,b.y-a.y),at=Math.max(0,Math.min(1,((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/(length*length)));return {w,a,b,length,at,distance:Math.hypot(p.x-a.x-(b.x-a.x)*at,p.y-a.y-(b.y-a.y)*at)};})).filter(o=>o.length>=4).sort((a,b)=>a.distance-b.distance),o=options[0];if(!o||o.distance>Math.max(20,20*units)){setError("Tap closer to a wall segment, or draw a wall first.");return;}const width=Math.max(4,Math.min(50,o.length*.6)),half=width/(2*o.length);add({variant:"opening",wallId:o.w.id,startId:o.a.id,endId:o.b.id,at:Math.max(half,Math.min(1-half,o.at)),width:rounded(width),style:tool==="window"?"window":openingStyle as typeof openingStyles[number]},tool==="window"?"window":"opening");
 }
 function down(e:PointerEvent<SVGSVGElement>){if(pending||e.button!==0)return;e.preventDefault();const p=point(e),hit=(e.target as Element).closest("[data-interior]")?.getAttribute("data-interior")??null,vertex=(e.target as Element).getAttribute("data-vertex");
  if(tool==="pan"){gesture.current={pointer:e.pointerId,start:{x:e.clientX,y:e.clientY},view,draft};e.currentTarget.setPointerCapture(e.pointerId);return;}
  if(tool==="select"){select(hit);return;}
  if(tool==="move"||tool==="points"){if(fieldsDirty){setError("Apply or discard object fields before editing geometry.");return;}const s=shapes.find(s=>s.id===(vertex?selectedId:hit));if(!s||s.archived||!associatedEditable(s))return;select(s.id);if(vertex)setVertex(vertex);gesture.current={pointer:e.pointerId,start:p,view,draft,shapeId:s.id,vertexId:vertex??undefined};e.currentTarget.setPointerCapture(e.pointerId);return;}
  if(fieldsDirty){setError("Apply or discard object fields before creating another object.");return;}
  if(tool==="circle"){if(!editable("room"))return;if(trace.length){const c=trace[0],r=Math.hypot(p.x-c.x,p.y-c.y);add({variant:"area",points:Array.from({length:24},(_,i)=>({id:crypto.randomUUID(),x:rounded(c.x+Math.cos(i*Math.PI/12)*r),y:rounded(c.y+Math.sin(i*Math.PI/12)*r)}))},"room");}else setTrace([{...p,id:crypto.randomUUID()}]);}
  else if(tool==="rectangle"){if(!editable("room"))return;if(trace.length){const a=trace[0],x=Math.min(a.x,p.x),y=Math.min(a.y,p.y),w=Math.abs(a.x-p.x),h=Math.abs(a.y-p.y);if(w<1||h<1){setError("Choose two different opposite corners.");return;}add({variant:"area",points:[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}].map(p=>({...p,id:crypto.randomUUID()}))},"room");}else setTrace([{...p,id:crypto.randomUUID()}]);}
  else if(["room","wall","cavern","corridor","secret","surface","terrainpath"].includes(tool)){if(!editable(tool==="secret"?"corridor":tool==="surface"||tool==="terrainpath"?"terrain":tool as InteriorEntity["kind"]))return;setTrace(t=>[...t,{...p,id:crypto.randomUUID()}]);setTraceFuture([]);}
  else if(tool==="opening"||tool==="window")attach(p);
  else if(["transition","furnishing","landmark","trap","hazard","annotation"].includes(tool))add({variant:"object",point:p,width:tool==="transition"?70:90,height:tool==="transition"?90:60,rotation:0,symbol:tool==="transition"?transition:tool==="furnishing"?symbol:["trap","hazard","annotation"].includes(tool)?tool:"custom"},tool as InteriorEntity["kind"]);
 }
 function move(e:PointerEvent<SVGSVGElement>){const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;const p=point(e),cx=e.clientX,cy=e.clientY;queued.current=()=>{if(tool==="pan"){const r=svg.current!.getBoundingClientRect(),u=Math.max(g.view.width/r.width,g.view.height/r.height);setView({...g.view,x:g.view.x-(cx-g.start.x)*u,y:g.view.y-(cy-g.start.y)*u});return;}const s=g.draft[shapeKey]!.find(s=>s.id===g.shapeId)!;let next:InteriorShape;
   if(g.vertexId&&"points" in s)next={...s,points:s.points.map(v=>v.id===g.vertexId?{...v,...p}:v)};
   else if(s.variant==="opening"){const a=openingAnchor(s,planBaseShapes(g.draft[shapeKey]!)),at=((p.x-a.a.x)*(a.b.x-a.a.x)+(p.y-a.a.y)*(a.b.y-a.a.y))/(a.length*a.length),half=s.width/(2*a.length);next={...s,at:Math.max(half,Math.min(1-half,at))};}
   else next=transformInterior(s,g.draft[shapeKey]!,p.x-g.start.x,p.y-g.start.y);
   const d={...g.draft,[shapeKey]:g.draft[shapeKey]!.map(n=>n.id===s.id?next:n)};try{validateMapDraft(d);previewRef.current=d;setPreview(d);setError("");}catch(error){setError((error as Error).message);previewRef.current=null;setPreview(null);}
  };if(frame.current===null)frame.current=requestAnimationFrame(()=>{frame.current=null;queued.current();});
 }
 function up(e:PointerEvent<SVGSVGElement>){if(gesture.current?.pointer!==e.pointerId)return;if(frame.current!==null){cancelAnimationFrame(frame.current);frame.current=null;queued.current();}if(previewRef.current)change(previewRef.current);previewRef.current=null;setPreview(null);gesture.current=null;}
 function markFields(e:FormEvent<HTMLFormElement>){fieldForms.current.add(e.currentTarget);setFieldsDirty(true);}
 function applied(form:HTMLFormElement){fieldForms.current.delete(form);setFieldsDirty(fieldForms.current.size>0);}
 function applyInformation(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||!entity)return;const f=new FormData(e.currentTarget),updated=(isDungeon?dungeonEntitySchema:interiorEntitySchema).parse({...entity,name:f.get("name")===null?entity.name:String(f.get("name")),description:String(f.get("description")),classification:String(f.get("classification")),...(isDungeon?{visibility:String(f.get("visibility")),privateNotes:String(f.get("privateNotes"))}:{})});let s:InteriorShape=selected;
  if(s.variant==="passage")s={...s,width:Number(f.get("width")),appearance:String(f.get("appearance")) as "constructed"};else if(s.variant==="wall")s={...s,width:Number(f.get("width"))};else if(s.variant==="object")s={...s,width:Number(f.get("width")),height:Number(f.get("height")),rotation:Number(f.get("rotation")),symbol:String(f.get("symbol"))};else if(s.variant==="opening"){const wall=shapes.find(n=>n.id===String(f.get("wallId")));const startId=String(f.get("startId"));if(!wall||wall.variant!=="wall"){setError("Choose an active wall.");return;}const i=wall.points.findIndex(p=>p.id===startId);if(!wall.points[i+1]){setError("Choose a segment present on the chosen wall, then apply again.");return;}s={...s,wallId:wall.id,startId,endId:wall.points[i+1].id,width:Number(f.get("width")),at:Number(f.get("at")),style:String(f.get("style")) as typeof openingStyles[number]};}
  if(!associatedEditable(s))return;const destination=String(f.get("destinationMapId")??"")||null,arrival=String(f.get("arrival")??"")||null;
  const next={...draft,[shapeKey]:shapes.map(n=>n.id===s.id?s:n),[entityKey]:entities.map(n=>n.id===entity.id?updated:n),geographies:draft.geographies.map(g=>g.id===entity.geographyId?{...g,name:updated.name||`Unnamed ${entity.kind}`,description:updated.description}:g),[linkKey]:entity.kind==="transition"?draft[linkKey]!.map(l=>l.entityId===entity.id?{...l,destinationMapId:destination,destinationGeographyId:arrival}:l):draft[linkKey]};if(change(next)){applied(e.currentTarget);setFormGeneration(n=>n+1);}
 }
 function duplicate(){if(!selected||!entity||!associatedEditable(selected))return;const group=selected.variant==="wall"?[selected,...shapes.filter(s=>s.variant==="opening"&&!s.archived&&s.wallId===selected.id)]:[selected],entityIds=new Map(group.map(s=>[s.entityId,crypto.randomUUID()])),copies=duplicateInteriorSource(group,()=>crypto.randomUUID()).map(s=>({...transformInterior(s,group,s.variant==="opening"?0:15,s.variant==="opening"?0:15),entityId:entityIds.get(s.entityId)!,archived:false}));const copiedEntities=[...entityIds].map(([oldId,id])=>{const old=entityIndex.get(oldId)!;return {...old,id,revision:null,geographyId:old.geographyId?id:null,name:old.name?`${old.name.slice(0,150)} copy`:""};});const next:MapDraft={...draft,[shapeKey]:[...shapes,...copies],[entityKey]:[...entities,...copiedEntities],geographies:[...draft.geographies,...copiedEntities.filter(e=>e.geographyId).map(e=>({id:e.id,revision:null,name:e.name||`Unnamed ${e.kind}`,description:e.description,kind:"location" as const,context:isDungeon?"dungeon" as const:"interior" as const,parentId:map.geographyId!}))],[linkKey]:[...draft[linkKey]!,...copiedEntities.filter(e=>e.kind==="transition").map(e=>({entityId:e.id,destinationMapId:null,destinationGeographyId:null}))]};if(change(next))select(copies[0].id);}

 async function save(){if(fieldsDirty||trace.length){setError("Apply or discard fields and finish or cancel the drawing before saving.");return;}setPending(true);setError("");try{const fresh=await onSave({revision,draft}),d=draftOf(fresh.map,fresh.geographies),h=acceptSavedHistory(historyRef.current,d);historyRef.current=h;setHistory(h);setSaved(JSON.stringify(d));setRevision(fresh.map.revision);setNotice(isDungeon?"Dungeon saved.":"Interior saved.");setFormGeneration(n=>n+1);}catch(e){setError((e as Error).message);}finally{setPending(false);}}
 const list=shapes.filter(s=>(entityIndex.get(s.entityId)?.name||entityIndex.get(s.entityId)?.kind||"").toLowerCase().includes(query.toLowerCase()));
 return <section className={styles.workspace} aria-label={isDungeon?"Dungeon Workshop":"Interior floor-plan editor"}><header><p className={styles.hint}>{isDungeon?"World Atlas / Dungeon Workshop":"World Atlas / Building interior"}</p><h2>{draft.name}</h2><div className={styles.tools}><button className="st-button is-secondary" onClick={()=>guard(onClose)}>Map library</button>{onExplore&&<button className="st-button is-secondary" onClick={()=>guard(onExplore)}>{isDungeon?"Explore dungeon":"Explore interior"}</button>}{onConnections&&<button className="st-button is-secondary" onClick={()=>guard(onConnections)}>Map connections</button>}<button className="st-button" disabled={!canEdit||pending} onClick={()=>void save()}>{pending?"Saving...":isDungeon?"Save dungeon":"Save interior"}</button></div>{onPlaceHistory&&<button type="button" className="st-button is-secondary" onClick={()=>onPlaceHistory(entity&&geographies.some(g=>g.id===entity.id)?entity.id:map.geographyId!)}>Historical milestones for saved place</button>}</header>
 {isDungeon?<DungeonLevelNavigation bundle={bundle} map={map} onOpen={(id,p)=>guard(()=>onOpenMap(id,p))} onCreate={canEdit&&onAddDungeonLevel?id=>guard(()=>onAddDungeonLevel(id)):undefined} onEdit={canEdit&&onEditDungeonLevel?l=>guard(()=>onEditDungeonLevel(l)):undefined}/>:<InteriorFloorNavigation bundle={bundle} map={map} onOpen={(id,p)=>guard(()=>onOpenMap(id,p))} onCreate={canEdit?id=>guard(()=>onAddFloor(id)):undefined} onEdit={canEdit?f=>guard(()=>onEditFloor(f)):undefined}/> }
 {error&&<p role="alert" className={styles.feedback}>{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className={styles.tools}>{tools.map(t=><button key={t} className="st-button is-secondary" aria-pressed={tool===t} disabled={pending||(!canEdit&&!["select","pan"].includes(t))} onClick={()=>{if((trace.length||fieldsDirty)&&!window.confirm("Discard unfinished drawing and unapplied fields?"))return;discardFields();setTrace([]);setTraceFuture([]);setTool(t);}}>{labels[t]}</button>)}<button className="st-button is-secondary" disabled={!canEdit||pending||fieldsDirty||(!history.past.length&&!trace.length)} onClick={()=>{if(trace.length){setTraceFuture([trace.at(-1)!,...traceFuture]);setTrace(trace.slice(0,-1));}else{const h=undoAction(historyRef.current);historyRef.current=h;setHistory(h);setFormGeneration(n=>n+1);}}}>Undo</button><button className="st-button is-secondary" disabled={!canEdit||pending||fieldsDirty||(!history.future.length&&!traceFuture.length)} onClick={()=>{if(traceFuture.length){setTrace([...trace,traceFuture[0]]);setTraceFuture(traceFuture.slice(1));}else{const h=redoAction(historyRef.current);historyRef.current=h;setHistory(h);setFormGeneration(n=>n+1);}}}>Redo</button><button className="st-button is-secondary" onClick={()=>setView(v=>zoomViewport(v,1.4))}>Zoom in</button><button className="st-button is-secondary" onClick={()=>setView(v=>zoomViewport(v,1/1.4))}>Zoom out</button><button className="st-button is-secondary" onClick={()=>setView(fitViewport())}>Fit plan</button></div><p>{help[tool]}</p>
 {isDungeon&&<><GuidedField label="New feature visibility" help="Ordinary content appears in the server preview. Secret and G.O.D.-only records are omitted; full author data remains limited to the World owner and explicit Administrator review."><select className="st-control" value={newVisibility} onChange={e=>setNewVisibility(e.target.value as typeof newVisibility)}>{["ordinary","secret","god-only"].map(v=><option key={v}>{v}</option>)}</select></GuidedField>{["corridor","secret","terrainpath"].includes(tool)&&<GuidedField label="Passage appearance" help="Constructed paths use straight editable segments; natural and environmental paths use a smooth outline between their editable points."><select className="st-control" value={appearance} onChange={e=>setAppearance(e.target.value)}>{passageAppearances.map(v=><option key={v}>{v}</option>)}</select></GuidedField>}<DungeonGridFields generation={formGeneration} onFieldsChange={markFields} onApplied={applied} grid={(state as DungeonState).grid} disabled={!canEdit||pending||trace.length>0||!state.layers.flooring.visible||("grid" in state.layers&&(!state.layers.grid.visible||state.layers.grid.locked))} onChange={grid=>change({...draft,dungeonState:{...state as DungeonState,grid}})}/>{onOrdinaryPreview&&<button className="st-button is-secondary" onClick={()=>guard(onOrdinaryPreview)}>Ordinary-content server preview</button>}<p className={styles.hint}>Author drafts contain protected content. The preview is owner-only and removes protected records on the server; it does not enable Player sharing.</p></>}
 {tool==="furnishing"&&<GuidedField label="Furnishing symbol" help="Choose a starter drawing; custom objects can describe any technology or genre."><select className="st-control" value={symbol} onChange={e=>setSymbol(e.target.value)}>{furnishings.map(s=><option key={s}>{s}</option>)}</select></GuidedField>}{tool==="transition"&&<GuidedField label="Transition symbol" help="Its appearance does not choose a destination or enforce physical movement."><select className="st-control" value={transition} onChange={e=>setTransition(e.target.value)}>{transitions.map(s=><option key={s}>{s}</option>)}</select></GuidedField>}{tool==="opening"&&<GuidedField label="Opening style" help="Place a door, passage or custom gap on an existing wall."><select className="st-control" value={openingStyle} onChange={e=>setOpeningStyle(e.target.value)}>{openingStyles.filter(s=>s!=="window").map(s=><option key={s}>{s}</option>)}</select></GuidedField>}
 {trace.length>0&&<div className={styles.tools}>{(["room","wall","cavern","corridor","secret","surface","terrainpath"].includes(tool))&&<button className="st-button" disabled={trace.length<(["room","cavern","surface"].includes(tool)?3:2)} onClick={complete}>Complete drawing</button>}<button className="st-button is-secondary" onClick={()=>{setTrace([]);setTraceFuture([]);}}>Cancel drawing</button><span>{trace.length} unfinished points</span></div>}
 <details><summary>Map information</summary><form key={formGeneration} onChange={markFields} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(change({...draft,name:String(f.get("mapName")),description:String(f.get("mapDescription"))}))applied(e.currentTarget);}}><GuidedField label={isDungeon?"Dungeon map name":"Interior map name"} help={isDungeon?"Name this drawing; it does not rename or replace its dungeon level or section.":"Name this drawing; it does not rename or replace the floor it represents."}><input className="st-control" name="mapName" required maxLength={160} defaultValue={draft.name} disabled={!canEdit||pending}/></GuidedField><GuidedField label={isDungeon?"Dungeon map description":"Interior map description"} help="Optional purpose or notes specific to this drawing."><textarea className="st-control" name="mapDescription" rows={3} maxLength={12000} defaultValue={draft.description} disabled={!canEdit||pending}/></GuidedField><button className="st-button is-secondary" disabled={!canEdit||pending}>Apply map information</button></form></details>
 <details><summary>{isDungeon?"Dungeon layers":"Interior layers"}</summary><p className={styles.hint}>Visibility affects drawing and selection. It does not protect private information.</p><div className={styles.layers}>{layers.map(k=><div className={styles.layer} key={k}><strong>{k==="flooring"?"Background / flooring":k}</strong>{(["visible","locked"] as const).map(field=><label key={field}><input aria-label={`${k} ${field}`} type="checkbox" checked={(state.layers as Record<string,{visible:boolean;locked:boolean}>)[k][field]} disabled={!canEdit||pending||fieldsDirty||trace.length>0} onChange={e=>change({...draft,[stateKey]:{...state,layers:{...state.layers,[k]:{...(state.layers as Record<string,{visible:boolean;locked:boolean}>)[k],[field]:e.target.checked}}}})}/>{field}</label>)}</div>)}</div><GuidedField label="Flooring appearance" help="Decorative boards or tiles. This is an illustration pattern, not a gameplay grid."><select className="st-control" value={state.flooring} disabled={!canEdit||pending||!state.layers.flooring.visible||state.layers.flooring.locked} onChange={e=>change({...draft,[stateKey]:{...state,flooring:e.target.value as typeof state.flooring}})}>{["plain","boards","tiles"].map(s=><option key={s}>{s}</option>)}</select></GuidedField></details>
 <div className={styles.layout}><div><svg ref={svg} className={styles.canvas} role="img" aria-label={`${draft.name} editable floor plan`} viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{gesture.current=null;previewRef.current=null;setPreview(null);if(frame.current!==null)cancelAnimationFrame(frame.current);frame.current=null;}}><CartographyScene draft={preview??draft} selectedId={selectedId} id={`interior-${map.id}`} unitsPerPixel={units} explorable/>{trace.length>0&&<polyline className={styles.trace} points={trace.map(p=>`${p.x},${p.y}`).join(" ")}/>} {tool==="points"&&selected&&"points" in selected&&associatedEditable(selected)&&!selected.archived&&selected.points.map(p=><circle key={p.id} data-vertex={p.id} className={styles.vertex} cx={p.x} cy={p.y} r={7*units}/>)}</svg><p className={styles.hint}>{shapes.filter(s=>!s.archived).length} active representations / {shapes.length} retained. {dirty?"Unsaved work":"Saved source"}</p></div>
 <aside className={styles.panel}>{selected&&entity?<><h3>{entity.name||`Unnamed ${entity.kind}`}{selected.archived?" (archived)":""}</h3><form key={`${selected.id}:${formGeneration}`} onChange={markFields} onSubmit={e=>{try{applyInformation(e);}catch(error){setError((error as Error).message);}}}><fieldset disabled={!associatedEditable(selected)||selected.archived}><GuidedField label="Object name" help={isDungeon?"Optional. Names and descriptions belong to the stable entity and are shared by other maps of this level or section.":"Optional. Names and descriptions belong to the stable entity and are shared by other maps of this floor."}><input className="st-control" name="name" maxLength={160} disabled={state.layers.labels.locked||!state.layers.labels.visible} defaultValue={entity.name}/></GuidedField><GuidedField label="Object description" help="Author any purpose, origin or unusual quality. No mechanics are required."><textarea className="st-control" name="description" rows={4} maxLength={12000} defaultValue={entity.description}/></GuidedField><GuidedField label="Authored classification" help="Optional free text, such as laboratory, living doorway or reactor."><input className="st-control" name="classification" maxLength={160} defaultValue={entity.classification}/></GuidedField>
 {isDungeon&&"visibility" in entity&&<><GuidedField label="Feature visibility" help="Secret and G.O.D.-only records are stored behind World authorization and removed from ordinary-content server previews."><select className="st-control" name="visibility" defaultValue={entity.visibility}>{["ordinary","secret","god-only"].map(v=><option key={v}>{v}</option>)}</select></GuidedField><GuidedField label="Private author notes" help="Optional protected notes, always omitted from the ordinary-content server preview. No Campaign or discovery state is created."><textarea className="st-control" name="privateNotes" maxLength={12000} rows={3} defaultValue={entity.privateNotes}/></GuidedField></>}
 {selected.variant==="passage"&&<GuidedField label="Passage appearance" help="Choose a constructed hallway, natural tunnel or environmental path. Identity and points are retained."><select className="st-control" name="appearance" defaultValue={selected.appearance}>{passageAppearances.map(v=><option key={v}>{v}</option>)}</select></GuidedField>}
 {selected.variant!=="area"&&<GuidedField label={selected.variant==="opening"?"Opening width":"Visual width"} help={selected.variant==="opening"?"The gap must fit its wall segment. Width is measured in drawing units.":"Illustrated width in map units; this does not set physical or gameplay dimensions."}><input className="st-control" name="width" type="number" required min={selected.variant==="wall"?1:4} max={selected.variant==="wall"?100:selected.variant==="opening"?240:500} step=".01" defaultValue={selected.width}/></GuidedField>}
 {selected.variant==="object"&&<><GuidedField label="Visual height" help="Illustrated height, from 4 to 500 map units."><input className="st-control" name="height" type="number" required min={4} max={500} step=".01" defaultValue={selected.height}/></GuidedField><GuidedField label="Rotation" help="Turn this representation from -180 to 180 degrees."><input className="st-control" name="rotation" type="number" required min={-180} max={180} step=".01" defaultValue={selected.rotation}/></GuidedField><GuidedField label="Object symbol" help="Change this representation without changing its entity identity."><select className="st-control" name="symbol" defaultValue={selected.symbol}>{(entity.kind==="transition"?transitions:entity.kind==="furnishing"?furnishings:isDungeon?[entity.kind,"custom"]:["custom"]).map(s=><option key={s}>{s}</option>)}</select></GuidedField></>}
 {selected.variant==="opening"&&<><GuidedField label="Attached wall" help="Choose an active wall, and a segment from that same wall below. The gap follows its segment when reshaped."><select className="st-control" name="wallId" defaultValue={selected.wallId}>{shapes.filter(s=>s.variant==="wall"&&!s.archived).map(s=><option key={s.id} value={s.id}>{entityIndex.get(s.entityId)?.name||`Wall ${shapes.indexOf(s)+1}`}</option>)}</select></GuidedField><GuidedField label="Wall segment" help="Choose a segment belonging to the selected wall. Its endpoint identities preserve the attachment."><select className="st-control" name="startId" defaultValue={selected.startId}>{shapes.filter((s):s is Extract<InteriorShape,{variant:"wall"}>=>s.variant==="wall"&&!s.archived).flatMap((w)=>w.points.slice(0,-1).map((p,i)=><option key={p.id} value={p.id}>{entityIndex.get(w.entityId)?.name||`Wall ${shapes.indexOf(w)+1}`} / segment {i+1}</option>))}</select></GuidedField><GuidedField label="Segment position" help="The center's fraction along its attached segment, between 0 and 1. Leave space for the gap at both ends."><input className="st-control" name="at" type="number" min={0} max={1} step="any" defaultValue={selected.at}/></GuidedField><GuidedField label="Opening appearance" help="Windows and doors use their own layers. Orientation follows the wall."><select className="st-control" name="style" defaultValue={selected.style}>{(entity.kind==="window"?["window"]:openingStyles.filter(s=>s!=="window")).map(s=><option key={s}>{s}</option>)}</select></GuidedField></>}
 {entity.kind==="transition"&&<InteriorDestinationFields worldId={worldId} bundle={bundle} mapId={map.id} destinationMapId={draft[linkKey]!.find(l=>l.entityId===entity.id)?.destinationMapId??null} destinationGeographyId={draft[linkKey]!.find(l=>l.entityId===entity.id)?.destinationGeographyId??null}/>}

 <button className="st-button is-secondary" disabled={!fieldsDirty}>Apply information</button></fieldset></form><div className={styles.tools}>{!selected.archived&&<><button className="st-button is-secondary" disabled={!associatedEditable(selected)||fieldsDirty||trace.length>0} onClick={duplicate}>Duplicate object</button>{[[-20,0,"Move left"],[20,0,"Move right"],[0,-20,"Move up"],[0,20,"Move down"]].map(([x,y,label])=><button key={label} className="st-button is-secondary" disabled={!associatedEditable(selected)||fieldsDirty||selected.variant==="opening"} onClick={()=>replace(transformInterior(selected,shapes,Number(x),Number(y)))}>{label}</button>)}<button className="st-button is-secondary" disabled={!associatedEditable(selected)||fieldsDirty} onClick={()=>replace(transformInterior(selected,shapes,0,0,1.1))}>Enlarge object</button><button className="st-button is-secondary" disabled={!associatedEditable(selected)||fieldsDirty} onClick={()=>replace(transformInterior(selected,shapes,0,0,.9))}>Shrink object</button><button className="st-button is-secondary" disabled={!associatedEditable(selected)||fieldsDirty||selected.variant==="opening"} onClick={()=>replace(transformInterior(selected,shapes,0,0,1,15))}>Rotate object</button></>}<button className="st-button is-secondary" disabled={!associatedEditable(selected)||fieldsDirty} onClick={()=>replace({...selected,archived:!selected.archived})}>{selected.archived?"Restore object":"Archive object"}</button></div>
 {tool==="points"&&"points" in selected&&<><GuidedField label="Boundary point" help="Select a persistent vertex to reshape this area or path."><select className="st-control" value={vertexId} disabled={fieldsDirty} onChange={e=>setVertex(e.target.value)}><option value="">Choose a point</option>{selected.points.map((p,i)=><option key={p.id} value={p.id}>Point {i+1}</option>)}</select></GuidedField>{selected.points.filter(p=>p.id===vertexId).map(p=><form key={`${p.id}:${p.x}:${p.y}`} onChange={markFields} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(replace({...selected,points:selected.points.map(n=>n.id===p.id?{...n,x:Number(f.get("x")),y:Number(f.get("y"))}:n)}))applied(e.currentTarget);}}><GuidedField label="Point X" help="Horizontal coordinate, 0 to 2000."><input className="st-control" name="x" type="number" required min={0} max={2000} step=".01" defaultValue={p.x}/></GuidedField><GuidedField label="Point Y" help="Vertical coordinate, 0 to 1200."><input className="st-control" name="y" type="number" required min={0} max={1200} step=".01" defaultValue={p.y}/></GuidedField><button className="st-button is-secondary">Apply point</button><button type="button" className="st-button is-secondary" disabled={fieldsDirty||!associatedEditable(selected)||selected.points.length>=256} onClick={()=>{const i=selected.points.findIndex(n=>n.id===p.id),b=selected.points[(i+1)%selected.points.length];if(selected.variant==="wall"&&i===selected.points.length-1){setError("Choose a segment start before the last wall endpoint.");return;}const points=[...selected.points];points.splice(i+1,0,{id:crypto.randomUUID(),x:rounded((p.x+b.x)/2),y:rounded((p.y+b.y)/2)});replace({...selected,points});}}>Insert midpoint</button><button type="button" className="st-button is-secondary" disabled={fieldsDirty||!associatedEditable(selected)||selected.points.length<=(selected.variant==="area"?3:2)} onClick={()=>{if(replace({...selected,points:selected.points.filter(n=>n.id!==p.id)}))setVertex("");}}>Remove point</button></form>)}</>}
 </>:<p>Select a room, wall or object to edit its source and information.</p>}{fieldsDirty&&<button className="st-button is-secondary" onClick={()=>{if(window.confirm("Discard unapplied fields?"))discardFields();}}>Discard object fields</button>}
 <GuidedField label={isDungeon?"Find dungeon object":"Find interior object"} help="Search retained names or types, including archived representations."><input className="st-control" value={query} onChange={e=>setQuery(e.target.value)}/></GuidedField><div className={styles.list}>{list.slice(0,200).map(s=><button key={s.id} className="st-button is-secondary" aria-pressed={s.id===selectedId} disabled={!(state.layers as Record<string,{visible:boolean;locked:boolean}>)[entityIndex.get(s.entityId)!.kind].visible||(state.layers as Record<string,{visible:boolean;locked:boolean}>)[entityIndex.get(s.entityId)!.kind].locked} onClick={()=>select(s.id)}>{entityIndex.get(s.entityId)?.name||`${entityIndex.get(s.entityId)?.kind} ${shapes.indexOf(s)+1}`}{s.archived?" (archived)":""}</button>)}{list.length>200&&<p>Showing 200 matches; narrow the search to find another object.</p>}</div></aside></div>
 <div className={styles.tools}><button className="st-button is-secondary" disabled={pending} onClick={()=>guard(()=>{void onReload().then(fresh=>{const d=draftOf(fresh.map,fresh.geographies),h={past:[],present:d,future:[]};historyRef.current=h;setHistory(h);setSaved(JSON.stringify(d));setRevision(fresh.map.revision);setTrace([]);discardFields();select(null);}).catch(e=>setError(e.message));})}>{isDungeon?"Reload saved dungeon":"Reload saved interior"}</button><button className="st-button is-secondary" onClick={()=>{const a=document.createElement("a"),url=URL.createObjectURL(new Blob([JSON.stringify({version:1,mapId:map.id,revision,draft,unfinishedDrawing:trace,unappliedFields:[...fieldForms.current].map(f=>Object.fromEntries(new FormData(f)))},null,2)],{type:"application/json"}));a.href=url;a.download=isDungeon?"dungeon-author-draft.json":"interior-draft.json";a.click();URL.revokeObjectURL(url);}}>{isDungeon?"Download dungeon author draft":"Download interior draft"}</button><button className="st-button is-secondary" disabled={pending} onClick={()=>void onReload().then(f=>setComparison(`${f.map.name}: revision ${f.map.revision}. ${f.map[shapeKey]?.filter(s=>!s.archived).length??0} active objects. ${f.map[entityKey]?.map(e=>e.name||e.kind).join(", ")}`)).catch(e=>setError(e.message))}>{isDungeon?"Compare saved dungeon":"Compare saved interior"}</button></div>{comparison&&<p className={styles.feedback}>{comparison}</p>}
 </section>;
}
