"use client";
import { useEffect,useLayoutEffect,useMemo,useRef,useState,type PointerEvent } from "react";
import { GuidedField } from "@/components/field-guidance";
import { acceptSavedHistory, boundedPoint,commitAction,draftOf,fitViewport,redoAction,undoAction,validateMapDraft,zoomViewport,type EditingHistory,type MapDraft,type Point,type Vertex } from "./atlas";
import type { AtlasMapEditor } from "./atlas-map-editor";
import { CartographyScene } from "./cartography-scene";
import { SettlementScene } from "./settlement-scene";
import { defaultSettlementState,settlementKinds,settlementLayer,settlementLayers,settlementVariants,transformShape,type SettlementShape,type SettlementEntity } from "./settlement";
import styles from "./atlas.module.css";
import city from "./settlement.module.css";
type Props=Parameters<typeof AtlasMapEditor>[0]&{onBackground:()=>void;onCreateInterior?:(buildingId:string)=>void};
type Tool="select"|"move"|"points"|"pan"|"rectangle"|"outline"|SettlementEntity["kind"];
const tools:[Tool,string][]=[["select","Select"],["move","Move object"],["points","Edit points"],["pan","Pan"],["rectangle","Rectangle building"],["outline","Building outline"],["street","Street"],["district","District"],["wall","Wall"],["waterway","Waterway"],["space","Open space"],["landmark","Landmark"]];
export function SettlementEditor({map,geographies,canEdit,onDirtyChange,onClose,onSave,onReload,onExplore,onConnections,onBackground,onCreateInterior}:Props){
 const [history,setHistory]=useState<EditingHistory>(()=>({past:[],present:draftOf(map,geographies),future:[]})),ref=useRef(history);
 const [saved,setSaved]=useState(()=>JSON.stringify(history.present)),[revision,setRevision]=useState(map.revision),[tool,setTool]=useState<Tool>("select"),[view,setView]=useState(fitViewport),[selectedId,setSelected]=useState<string|null>(null),[pointId,setPoint]=useState(""),[trace,setTrace]=useState<Vertex[]>([]),[preview,setPreview]=useState<SettlementShape|null>(null),[variant,setVariant]=useState<SettlementShape["variant"]>("plain"),[existing,setExisting]=useState(""),[newName,setNewName]=useState(""),[pending,setPending]=useState(false),[fieldsDirty,setFieldsDirty]=useState(false),[pointFieldsDirty,setPointFieldsDirty]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[comparison,setComparison]=useState<Awaited<ReturnType<Props["onReload"]>>|null>(null),[units,setUnits]=useState(2),[query,setQuery]=useState("");
 const pointForm=useRef<HTMLFormElement>(null);
 const svg=useRef<SVGSVGElement>(null),form=useRef<HTMLFormElement>(null),gesture=useRef<{pointer:number;start:Point;screen:Point;view:typeof view;shape?:SettlementShape;vertex?:string;mode:Tool}|null>(null),frame=useRef<number|null>(null),last=useRef<{clientX:number;clientY:number;pointerId:number}|null>(null);
 const draft=history.present,shapes=useMemo(()=>draft.settlementShapes??[],[draft.settlementShapes]),entities=useMemo(()=>draft.settlementEntities??[],[draft.settlementEntities]),state=draft.settlementState??defaultSettlementState();
 const entityIndex=useMemo(()=>new Map(entities.map(e=>[e.geographyId,e])),[entities]),geoIndex=useMemo(()=>new Map(draft.geographies.map(g=>[g.id,g])),[draft.geographies]);
 const selected=shapes.find(s=>s.id===selectedId),entity=selected&&entityIndex.get(selected.geographyId),geo=selected&&geoIndex.get(selected.geographyId),selectedPoint=selected?.type!=="marker"?selected?.points.find(p=>p.id===pointId):null;
 const fingerprint=useMemo(()=>JSON.stringify(draft),[draft]),dirty=fingerprint!==saved||fieldsDirty||pointFieldsDirty||!!trace.length||!!preview,dirtyRef=useRef(dirty);
 useEffect(()=>{dirtyRef.current=dirty;onDirtyChange(dirty);},[dirty,onDirtyChange]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue="";}};const click=(e:MouseEvent)=>{if((e.target as Element).closest?.("a[href]")&&dirtyRef.current&&!window.confirm("Leave and discard unsaved settlement changes?")){e.preventDefault();e.stopPropagation();}};let returning=false;const back=(e:PopStateEvent)=>{if(returning){returning=false;return;}if(dirtyRef.current&&!window.confirm("Leave and discard unsaved settlement changes?")){e.stopImmediatePropagation();returning=true;window.history.go(1);}};window.addEventListener("beforeunload",before);document.addEventListener("click",click,true);window.addEventListener("popstate",back,true);return()=>{window.removeEventListener("beforeunload",before);document.removeEventListener("click",click,true);window.removeEventListener("popstate",back,true);if(frame.current!==null)cancelAnimationFrame(frame.current);};},[]);
 useLayoutEffect(()=>{const node=svg.current;if(!node)return;const resize=()=>{if(node.clientWidth&&node.clientHeight)setUnits(Math.max(view.width/node.clientWidth,view.height/node.clientHeight));};const observer=new ResizeObserver(resize);observer.observe(node);resize();return()=>observer.disconnect();},[view]);
 const editable=(kind:SettlementEntity["kind"])=>canEdit&&state.layers[settlementLayer(kind)].visible&&!state.layers[settlementLayer(kind)].locked;
 function update(h:EditingHistory){ref.current=h;setHistory(h);}
 function commit(next:MapDraft){try{validateMapDraft(next);update(commitAction(ref.current,next));setError("");setNotice("");return true;}catch(e){setError((e as Error).message);return false;}}
 function change(shape:SettlementShape){if(!entity||!editable(entity.kind))return false;return commit({...ref.current.present,settlementShapes:(ref.current.present.settlementShapes??[]).map(s=>s.id===shape.id?shape:s)});}
 function discardFields(){if((fieldsDirty||pointFieldsDirty)&&!window.confirm("Discard unapplied property fields?"))return false;form.current?.reset();pointForm.current?.reset();setFieldsDirty(false);setPointFieldsDirty(false);return true;}
 function choose(next:Tool){if(gesture.current||!discardFields())return;if(trace.length&&!window.confirm("Discard this unfinished path or area?"))return;setTrace([]);setTool(next);setExisting("");setVariant("plain");setError("");}
 function select(id:string){if(id!==selectedId&&!discardFields())return;setSelected(id);setPoint("");}
 function project(x:number,y:number){const matrix=svg.current!.getScreenCTM()!;const point=new DOMPoint(x,y).matrixTransform(matrix.inverse());return boundedPoint({x:point.x,y:point.y});}
 function add(kind:SettlementEntity["kind"],geometry:Omit<Extract<SettlementShape,{type:"area"}>,"version"|"id"|"geographyId"|"archived"|"variant">|Omit<Extract<SettlementShape,{type:"line"}>,"version"|"id"|"geographyId"|"archived"|"variant">|Omit<Extract<SettlementShape,{type:"marker"}>,"version"|"id"|"geographyId"|"archived"|"variant">){
  if(!editable(kind)){setError("Show and unlock the matching layer before drawing.");return;}
  const current=ref.current.present,e=entities.find(e=>e.geographyId===existing&&e.kind===kind),id=e?.geographyId??crypto.randomUUID();
  const semantic=e??{geographyId:id,revision:null,kind,classification:"",districtIds:[]};
  const g=geoIndex.get(id)??{id,revision:null,name:newName.trim()||`New ${kind} ${entities.filter(e=>e.kind===kind).length+1}`,description:"",kind:"location" as const,context:kind==="building"?"building site" as const:"local area" as const,parentId:map.geographyId!};
  const shape={version:1 as const,id:crypto.randomUUID(),geographyId:id,archived:false,variant,...geometry} as SettlementShape;
  if(commit({...current,settlementShapes:[...(current.settlementShapes??[]),shape],settlementEntities:e?entities:[...entities,semantic],geographies:geoIndex.has(id)?current.geographies:[...current.geographies,g]})){setSelected(shape.id);setTrace([]);setTool("select");setNewName("");setPoint("");}
 }
 function complete(){const kind=tool==="outline"?"building":tool as SettlementEntity["kind"];add(kind,["building","district","space"].includes(kind)?{type:"area",points:trace}:{type:"line",points:trace,width:kind==="street"?18:kind==="wall"?10:20,curve:kind==="wall"?0:.6});}
 function down(e:PointerEvent<SVGSVGElement>){if(!e.isPrimary||e.button!==0||pending||gesture.current)return;e.preventDefault();if((fieldsDirty||pointFieldsDirty)&&tool!=="pan"){setError("Apply property fields before drawing or moving objects.");return;}
  const p=project(e.clientX,e.clientY),target=e.target as Element,id=target.closest("[data-settlement]")?.getAttribute("data-settlement"),vertex=target.closest("[data-city-vertex]")?.getAttribute("data-city-vertex");
  if(["outline","street","district","wall","waterway","space"].includes(tool)){const kind=tool==="outline"?"building":tool as SettlementEntity["kind"];if(!editable(kind)){setError("Show and unlock the matching layer.");return;}if(trace.length<256)setTrace([...trace,{...p,id:crypto.randomUUID()}]);else setError("Use at most 256 points for one object.");return;}
  if(tool==="landmark"){add("landmark",{type:"marker",point:p,size:18,rotation:0});return;}
  if(tool==="rectangle"&&!editable("building")){setError("Show and unlock Buildings.");return;}
  if(id&&tool!=="pan"){select(id);if(vertex)setPoint(vertex);}
  const shape=shapes.find(s=>s.id===id),ent=shape&&entityIndex.get(shape.geographyId);
  if(tool==="pan"||tool==="rectangle"||shape&&ent&&editable(ent.kind)&&(tool==="move"||tool==="points"&&vertex)){
   gesture.current={pointer:e.pointerId,start:p,screen:{x:e.clientX,y:e.clientY},view,shape,vertex:vertex??undefined,mode:tool};e.currentTarget.setPointerCapture(e.pointerId);
  }
 }
 function flush(){frame.current=null;const e=last.current,g=gesture.current;if(!e||!g||e.pointerId!==g.pointer)return;last.current=null;
  if(g.mode==="pan"){const matrix=svg.current!.getScreenCTM()!;setView({...g.view,x:g.view.x-(e.clientX-g.screen.x)/matrix.a,y:g.view.y-(e.clientY-g.screen.y)/matrix.d});return;}
  const p=project(e.clientX,e.clientY);if(g.mode==="rectangle"){const a=g.start;setPreview({version:1,id:"preview",geographyId:"preview",archived:false,variant,type:"area",points:[a,{x:p.x,y:a.y},p,{x:a.x,y:p.y}].map(q=>({...q,id:crypto.randomUUID()}))});return;}
  if(g.shape)setPreview(g.mode==="move"?transformShape(g.shape,p.x-g.start.x,p.y-g.start.y):g.shape.type!=="marker"?{...g.shape,points:g.shape.points.map(q=>q.id===g.vertex?{...q,...p}:q)}:g.shape);
 }
 function moving(e:PointerEvent<SVGSVGElement>){last.current={clientX:e.clientX,clientY:e.clientY,pointerId:e.pointerId};if(frame.current===null)frame.current=requestAnimationFrame(flush);}
 function finish(e:PointerEvent<SVGSVGElement>,cancel=false){if(frame.current!==null)cancelAnimationFrame(frame.current);flush();const g=gesture.current;if(!g||g.pointer!==e.pointerId)return;const p=project(e.clientX,e.clientY);gesture.current=null;setPreview(null);if(cancel||g.mode==="pan")return;
  if(g.mode==="rectangle"){const a=g.start;add("building",{type:"area",points:[a,{x:p.x,y:a.y},p,{x:a.x,y:p.y}].map(q=>({...q,id:crypto.randomUUID()}))});}
  else if(g.shape){change(g.mode==="move"?transformShape(g.shape,p.x-g.start.x,p.y-g.start.y):g.shape.type!=="marker"?{...g.shape,points:g.shape.points.map(q=>q.id===g.vertex?{...q,...p}:q)}:g.shape);}
 }
 function leave(action:()=>void){if(!dirty||window.confirm("Discard unsaved settlement changes?"))action();}
 function accept(loaded:Awaited<ReturnType<Props["onReload"]>>,reset=false){const next=draftOf(loaded.map,loaded.geographies);update(reset?{past:[],present:next,future:[]}:acceptSavedHistory(ref.current,next));setRevision(loaded.map.revision);setSaved(JSON.stringify(next));setFieldsDirty(false);setPointFieldsDirty(false);setTrace([]);setComparison(null);setError("");setNotice("Settlement saved.");}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({format:"serrian-settlement-draft-v1",mapId:map.id,revision,draft:ref.current.present},null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="settlement-draft.json";a.click();URL.revokeObjectURL(url);}
 const shown=useMemo(()=>preview&&preview.id!=="preview"?{...draft,settlementShapes:shapes.map(s=>s.id===preview.id?preview:s)}:draft,[draft,preview,shapes]);
 const kindForTool=tool==="rectangle"||tool==="outline"?"building":settlementKinds.includes(tool as SettlementEntity["kind"])?tool as SettlementEntity["kind"]:null;
 const list=shapes.filter(s=>(geoIndex.get(s.geographyId)?.name??"").toLowerCase().includes(query.toLowerCase()));
 return <section className={styles.workshop} aria-label="Settlement editor"><header className={styles.heading}><div><p className={styles.eyebrow}>Settlement workshop</p><h2>{map.name}</h2><p role="status">{dirty?"Unsaved changes":notice||"All changes saved"}{!canEdit?" | Read-only":""}</p></div><div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={()=>leave(onClose)}>Map library</button>{onExplore&&<button className="st-button is-secondary" disabled={pending} onClick={()=>leave(onExplore)}>Explore settlement</button>}{canEdit&&<><button className="st-button is-secondary" disabled={pending} onClick={()=>leave(onBackground)}>Terrain and artwork</button>{onConnections&&<button className="st-button is-secondary" disabled={pending||dirty} onClick={onConnections}>Edit connections</button>}<button className="st-button" disabled={pending||!dirty||fieldsDirty||pointFieldsDirty||!!trace.length||!!preview} onClick={async()=>{setPending(true);try{validateMapDraft(ref.current.present);accept(await onSave({revision,draft:ref.current.present}));}catch(e){setError((e as Error).message);}finally{setPending(false);}}}>{pending?"Saving...":"Save settlement"}</button></>}</div></header>
 <div role="toolbar" aria-label="Settlement tools" className={city.tools}>{tools.filter(([id])=>canEdit||id==="select"||id==="pan").map(([id,label])=><button key={id} className="st-button is-secondary" aria-pressed={id===tool} disabled={pending||!!preview} onClick={()=>choose(id)}>{label}</button>)}{canEdit&&<><button className="st-button is-secondary" disabled={pending||fieldsDirty||pointFieldsDirty||!history.past.length} onClick={()=>{setTrace([]);update(undoAction(ref.current));}}>Undo</button><button className="st-button is-secondary" disabled={pending||fieldsDirty||pointFieldsDirty||!history.future.length} onClick={()=>update(redoAction(ref.current))}>Redo</button></>}</div>
 <p className={styles.toolHelp}>{tool==="rectangle"?"Drag from one corner to the opposite corner to create a building.":kindForTool?"Tap points to draw a path or boundary, then Complete object. Landmarks need one tap. No grid, district or conventional architecture is required.":tool==="points"?"Select an object and drag its points, or use the point controls below.":tool==="move"?"Drag a selected object; its persistent place identity stays the same.":"Select a place to read or edit its information. Pan and zoom change only your view."}</p>
 {kindForTool&&canEdit&&<div className={styles.drawingBar}><GuidedField label="New place name" help="Optional name for the next object. You can rename and describe it after drawing."><input className="st-control" maxLength={160} value={newName} onChange={e=>setNewName(e.target.value)}/></GuidedField><GuidedField label="Existing place" help="Draw another representation of the same place, rather than creating another building or district identity."><select className="st-control" value={existing} onChange={e=>setExisting(e.target.value)}><option value="">Create a new place</option>{entities.filter(e=>e.kind===kindForTool).map(e=><option key={e.geographyId} value={e.geographyId}>{geoIndex.get(e.geographyId)?.name}</option>)}</select></GuidedField><GuidedField label="Appearance" help="A visual distinction only. Custom classifications and stories remain unrestricted."><select className="st-control" value={variant} onChange={e=>setVariant(e.target.value as typeof variant)}>{settlementVariants(kindForTool).map(v=><option key={v}>{v}</option>)}</select></GuidedField>{tool!=="rectangle"&&tool!=="landmark"&&<><button className="st-button" disabled={trace.length<(["outline","district","space"].includes(tool)?3:2)} onClick={complete}>Complete object</button><button className="st-button is-secondary" onClick={()=>setTrace([])}>Cancel object</button></>}</div>}
 {error&&<div role="alert" className={styles.feedback}><p>{error} Your draft is retained.</p><button className="st-button is-secondary" disabled={pending} onClick={async()=>{try{setComparison(await onReload());}catch(e){setError((e as Error).message);}}}>Load saved settlement to compare</button><button className="st-button is-secondary" onClick={download}>Download draft</button></div>}
 {comparison&&<aside className={styles.comparison}><h3>Saved settlement | revision {comparison.map.revision}</h3><p>{comparison.map.settlementShapes?.length} retained representations. Your draft is still below.</p><button className="st-button" onClick={()=>{if(window.confirm("Replace your draft with the saved settlement? Download it first to keep your changes."))accept(comparison,true);}}>Use saved settlement</button></aside>}
 <div className={styles.editorGrid}><div className={styles.mapFrame}><div className={styles.navigation}><button className="st-button is-secondary" aria-label="Zoom in" onClick={()=>setView(v=>zoomViewport(v,1.4))}>+</button><button className="st-button is-secondary" aria-label="Zoom out" onClick={()=>setView(v=>zoomViewport(v,1/1.4))}>-</button><button className="st-button is-secondary" onClick={()=>setView(fitViewport())}>Fit map</button></div><svg ref={svg} className={styles.canvas} data-tool={tool==="pan"?"pan":"select"} aria-label="Editable settlement map" viewBox={`${view.x} ${view.y} ${view.width} ${view.height}`} onPointerDown={down} onPointerMove={moving} onPointerUp={e=>finish(e)} onPointerCancel={e=>finish(e,true)}><CartographyScene draft={draft} id={`city-${map.id}`} editable={false} unitsPerPixel={units} cacheTerrain settlement={false}/><SettlementScene draft={shown} selectedId={selectedId} units={units} editable={canEdit}/>{trace.length>0&&<polyline className={city.preview} points={trace.map(p=>`${p.x},${p.y}`).join(" ")}/>}{preview?.id==="preview"&&preview.type==="area"&&<polygon className={city.preview} points={preview.points.map(p=>`${p.x},${p.y}`).join(" ")}/>}<g className={city.vertices}>{tool==="points"&&selected&&!selected.archived&&entity&&editable(entity.kind)&&selected.type!=="marker"&&selected.points.map(p=><circle key={p.id} data-settlement={selected.id} data-city-vertex={p.id} cx={p.x} cy={p.y} r={8*units}/>)}</g></svg></div>
 <aside className={styles.inspector}><fieldset disabled={pending}><h3>{geo?.name??"Settlement places"}</h3>{selected&&entity&&geo&&<><p>{entity.kind}: {selected.archived?"Archived representation":"Persistent World place"}</p>{editable(entity.kind)?<form ref={form} className={city.properties} key={`${selected.id}:${fingerprint}`} onChange={()=>setFieldsDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);let s=selected;if(s.type==="line")s={...s,width:Number(f.get("width")),curve:Number(f.get("curve"))};if(s.type==="marker")s={...s,size:Number(f.get("size")),rotation:Number(f.get("rotation"))};s={...s,variant:String(f.get("variant")) as SettlementShape["variant"]};if(commit({...draft,settlementShapes:shapes.map(n=>n.id===s.id?s:n),settlementEntities:entities.map(n=>n.geographyId===entity.geographyId?{...n,classification:String(f.get("classification")),districtIds:f.getAll("districtIds").map(String)}:n),geographies:draft.geographies.map(g=>g.id===geo.id?{...g,name:String(f.get("name")).trim(),description:String(f.get("description"))}:g)}))setFieldsDirty(false);}}>
 {entity.kind==="building"&&canEdit&&onCreateInterior&&<button type="button" className="st-button is-secondary" disabled={fieldsDirty||pointFieldsDirty||trace.length>0||entity.revision===null} onClick={()=>{if(dirty&&!window.confirm("Discard the unsaved settlement draft before creating an interior?"))return;onCreateInterior(entity.geographyId);}}>Create interior floor</button>}{entity.kind==="building"&&entity.revision===null&&<p>Save this building in the settlement before creating its interior.</p>}
 <GuidedField label="Place name" help="This name belongs to the persistent place and is shared by its other maps and representations."><input className="st-control" name="name" required maxLength={160} defaultValue={geo.name}/></GuidedField><GuidedField label="Place description" help="Record any story, purpose or detail you choose. No history or origin explanation is required."><textarea className="st-control" name="description" rows={4} maxLength={12000} defaultValue={geo.description}/></GuidedField><GuidedField label="Authored classification" help="Optional custom description of the kind of place, such as laboratory, home or dimensional anchor."><input className="st-control" name="classification" maxLength={160} defaultValue={entity.classification}/></GuidedField><GuidedField label="Object appearance" help="Change the visual style without changing this place's identity."><select name="variant" className="st-control" defaultValue={selected.variant}>{settlementVariants(entity.kind).map(v=><option key={v}>{v}</option>)}</select></GuidedField>{selected.type==="line"&&<><GuidedField label="Path width" help="Visual width in map units, from 1 to 100. This does not define movement rules."><input className="st-control" name="width" type="number" min={1} max={100} step=".01" defaultValue={selected.width}/></GuidedField><GuidedField label="Path curve" help="Zero uses straight segments; values up to one soften bends."><input className="st-control" name="curve" type="number" min={0} max={1} step=".01" defaultValue={selected.curve}/></GuidedField></>}{selected.type==="marker"&&<><GuidedField label="Landmark size" help="Visual radius from 4 to 160 map units."><input className="st-control" name="size" type="number" min={4} max={160} defaultValue={selected.size}/></GuidedField><GuidedField label="Landmark rotation" help="Rotate the symbol from -180 to 180 degrees."><input className="st-control" name="rotation" type="number" min={-180} max={180} defaultValue={selected.rotation}/></GuidedField></>}
 <fieldset><legend>District memberships</legend><p>A place may belong to several overlapping districts, or none.</p>{entities.filter(n=>n.kind==="district"&&n.geographyId!==entity.geographyId).map(n=><label key={n.geographyId}><input type="checkbox" name="districtIds" value={n.geographyId} defaultChecked={entity.districtIds.includes(n.geographyId)}/>{geoIndex.get(n.geographyId)?.name}</label>)}</fieldset><button className="st-button is-secondary">Apply properties</button></form>:<p>{geo.description||"No description recorded."}</p>}
 {editable(entity.kind)&&<div className={styles.actions}><button className="st-button is-secondary" disabled={fieldsDirty||pointFieldsDirty} onClick={()=>{const id=crypto.randomUUID(),gid=crypto.randomUUID(),copy={...selected,id,geographyId:gid,...(selected.type!=="marker"?{points:selected.points.map(p=>({...p,id:crypto.randomUUID()}))}:{})};if(commit({...draft,settlementShapes:[...shapes,copy],settlementEntities:[...entities,{...entity,geographyId:gid,revision:null}],geographies:[...draft.geographies,{...geo,id:gid,revision:null,name:`${geo.name.slice(0,150)} copy`}]}))select(id);}}>Duplicate object</button><button className="st-button is-danger" disabled={fieldsDirty||pointFieldsDirty} onClick={()=>{if(window.confirm(selected.archived?"Restore this representation?":"Archive this representation? Its place identity, geometry and relationships will be retained."))change({...selected,archived:!selected.archived});}}>{selected.archived?"Restore object":"Archive object"}</button>{!selected.archived&&<>{[["Left",-10,0],["Right",10,0],["Up",0,-10],["Down",0,10]].map(([label,x,y])=><button key={String(label)} className="st-button is-secondary" disabled={fieldsDirty||pointFieldsDirty} onClick={()=>change(transformShape(selected,Number(x),Number(y)))}>{label} 10</button>)}<button className="st-button is-secondary" disabled={fieldsDirty||pointFieldsDirty} onClick={()=>change(transformShape(selected,0,0,15))}>Rotate 15 degrees</button><button className="st-button is-secondary" disabled={fieldsDirty||pointFieldsDirty} onClick={()=>change(transformShape(selected,0,0,0,1.1))}>Enlarge 10%</button><button className="st-button is-secondary" disabled={fieldsDirty||pointFieldsDirty} onClick={()=>change(transformShape(selected,0,0,0,1/1.1))}>Reduce 10%</button></>}</div>}
 {tool==="points"&&editable(entity.kind)&&selected.type!=="marker"&&<><GuidedField label="Object point" help="Select a boundary or path vertex. Editing it keeps the same object and point identities."><select className="st-control" value={pointId} disabled={fieldsDirty||pointFieldsDirty} onChange={e=>setPoint(e.target.value)}><option value="">Choose a point</option>{selected.points.map((p,i)=><option key={p.id} value={p.id}>Point {i+1}</option>)}</select></GuidedField>{selectedPoint&&<form ref={pointForm} key={`${selectedPoint.id}:${selectedPoint.x}:${selectedPoint.y}`} onChange={()=>setPointFieldsDirty(true)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(change({...selected,points:selected.points.map(p=>p.id===pointId?{...p,x:Number(f.get("x")),y:Number(f.get("y"))}:p)}))setPointFieldsDirty(false);}}><GuidedField label="Point X" help="Horizontal map coordinate from 0 to 2000."><input className="st-control" name="x" type="number" min={0} max={2000} step=".01" required defaultValue={selectedPoint.x}/></GuidedField><GuidedField label="Point Y" help="Vertical map coordinate from 0 to 1200."><input className="st-control" name="y" type="number" min={0} max={1200} step=".01" required defaultValue={selectedPoint.y}/></GuidedField><button className="st-button is-secondary" disabled={fieldsDirty}>Apply point</button><button type="button" className="st-button is-secondary" disabled={fieldsDirty||pointFieldsDirty||selected.points.length>=256} onClick={()=>{const points=[...selected.points],at=points.findIndex(p=>p.id===pointId),a=points[at],b=points[(at+1)%points.length];if(selected.type==="line"&&at===points.length-1){setError("Select a point before the final endpoint to insert a midpoint.");return;}points.splice(at+1,0,{id:crypto.randomUUID(),...boundedPoint({x:(a.x+b.x)/2,y:(a.y+b.y)/2})});change({...selected,points});}}>Insert midpoint</button><button type="button" className="st-button is-danger" disabled={fieldsDirty||pointFieldsDirty||selected.points.length<=(selected.type==="area"?3:2)} onClick={()=>{change({...selected,points:selected.points.filter(p=>p.id!==pointId)});setPoint("");}}>Remove point</button></form>}</>}
 </>}
 <details><summary>Settlement layers</summary><div className={city.layerGrid}>{settlementLayers.map(l=><div key={l}><label><input type="checkbox" checked={state.layers[l].visible} disabled={!canEdit||fieldsDirty} onChange={e=>commit({...draft,settlementState:{...state,layers:{...state.layers,[l]:{...state.layers[l],visible:e.target.checked}}}})}/>{l}</label><label><input type="checkbox" checked={state.layers[l].locked} disabled={!canEdit||fieldsDirty} onChange={e=>commit({...draft,settlementState:{...state,layers:{...state.layers,[l]:{...state.layers[l],locked:e.target.checked}}}})}/>Lock {l}</label></div>)}</div><p>Terrain, water and background artwork use the existing Terrain and artwork editor. Hiding a layer never makes information private.</p></details>
 <GuidedField label="Find settlement object" help="Search names to locate an object, including archived representations."><input className="st-control" value={query} onChange={e=>setQuery(e.target.value)}/></GuidedField><div className={city.list}>{list.slice(0,200).map(s=><button key={s.id} className="st-button is-secondary" aria-pressed={s.id===selectedId} disabled={!state.layers[settlementLayer(entityIndex.get(s.geographyId)!.kind)].visible||state.layers[settlementLayer(entityIndex.get(s.geographyId)!.kind)].locked} onClick={()=>select(s.id)}>{geoIndex.get(s.geographyId)?.name}{s.archived?" (archived)":""}</button>)}{list.length>200&&<p>Showing the first 200 matches. Narrow your search to locate another object.</p>}</div>
 </fieldset></aside></div></section>;
}
