"use client";
import { useEffect, useRef, useState } from "react";
import { branchDraftSchema, historyContextLabel, timelineDraftSchema, type InheritanceReview, type WorldTimeline } from "./branching-history";
import { Field } from "./world-field";
import { SaveError, worldApi } from "./client-api";
import { eraLabel, timeLabel, yearLabel, type WorldBundle } from "./history";
import { YEAR_LIMIT } from "./world-year";
import styles from "./worlds.module.css";

function TimelineEditor({target,create,bundle,onClose,onSave,onReload,onDirty}:{target:WorldTimeline;create:boolean;bundle:WorldBundle;onClose:()=>void;onSave:(body:unknown)=>Promise<void>;onReload:()=>Promise<WorldBundle>;onDirty:(dirty:boolean)=>void}){
  const dialog=useRef<HTMLDialogElement>(null);
  const [draft,setDraft]=useState({name:create?"":target.name,description:create?"":target.description,explanation:create?"":target.explanation,parentId:target.id,divergenceYear:target.divergenceYear??0});
  const [saved,setSaved]=useState(target),[original,setOriginal]=useState(JSON.stringify(draft)),[error,setError]=useState(""),[pending,setPending]=useState(false),[conflict,setConflict]=useState(false),[discard,setDiscard]=useState(false);
  const dirty=original!==JSON.stringify(draft);
  useEffect(()=>{dialog.current?.showModal();},[]);
  useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
  useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>event.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  function close(){if(pending)return;if(dirty)setDiscard(true);else onClose();}
  return <dialog ref={dialog} className={styles.editor} aria-label={create?"Create alternate timeline":"Edit timeline"} onCancel={event=>{event.preventDefault();close();}}>
    <header className={styles.editorHeader}><div><p className={styles.eyebrow}>{bundle.world.name} · Timeline manager</p><h2>{create?"Create alternate timeline":"Edit timeline"}</h2></div><button type="button" className="st-button is-secondary" disabled={pending} onClick={close}>Close timeline editor</button></header>
    <form onSubmit={async event=>{event.preventDefault();setError("");setConflict(false);const {parentId,divergenceYear,...identity}=draft;const parsed=(create?branchDraftSchema:timelineDraftSchema).safeParse(create?draft:identity);if(!parsed.success){setError(parsed.error.issues.map(issue=>issue.message).join(" "));return;}setPending(true);try{await onSave(create?{action:"create",parentRevision:bundle.timelines.find(t=>t.id===parentId)!.revision,draft:{...identity,parentId,divergenceYear}}:{action:"save",id:saved.id,revision:saved.revision,draft:identity});}catch(failure){setError(failure instanceof Error?failure.message:"Your timeline draft is retained.");setConflict(failure instanceof SaveError&&failure.status===409);}finally{setPending(false);}}}>
      <fieldset className={styles.editorFields} disabled={pending}>
        <Field label="Timeline name" help="Name the history readers will select. Its permanent identity remains unchanged when renamed."><input autoFocus required maxLength={160} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></Field>
        <Field label="Timeline description" help="Describe this history in your own words. Optional; up to 50,000 characters."><textarea rows={4} maxLength={50000} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></Field>
        {create&&<><Field label="Parent timeline" help="This branch uses the selected parent's current historical versions. Archived timelines cannot be new parents."><select value={draft.parentId} onChange={event=>setDraft({...draft,parentId:event.target.value})}>{bundle.timelines.filter(t=>!t.archived).map(t=><option key={t.id} value={t.id}>{t.name}{t.primary?" (primary)":""}</option>)}</select></Field>
        <Field label="Divergence canonical year" help="A signed whole World year, including zero. Branching at the start of Year N automatically inherits only fully dated predecessor records strictly before N. Approximate, undated, planned and crossing accounts need a decision. Parentage and divergence are fixed after creation."><input required type="number" step={1} min={bundle.timelines.find(t=>t.id===draft.parentId)?.divergenceYear??-YEAR_LIMIT} max={YEAR_LIMIT} value={Number.isFinite(draft.divergenceYear)?draft.divergenceYear:""} onChange={event=>setDraft({...draft,divergenceYear:event.target.value===""?NaN:Number(event.target.value)})}/></Field><p className={styles.caption}>Divergence is the start of canonical Year {Number.isFinite(draft.divergenceYear)?yearLabel(draft.divergenceYear):"…"}. Events in that year or later are not automatically inherited.</p></>}
        <Field label="Why history differs" help="Explain the divergence freely. No Campaign, prescribed cause or mechanical consequence is required. Optional; up to 50,000 characters."><textarea rows={4} maxLength={50000} value={draft.explanation} onChange={event=>setDraft({...draft,explanation:event.target.value})}/></Field>
      </fieldset>
      {error&&<p role="alert" className={styles.feedback}>{error}</p>}
      {conflict&&!create&&<button type="button" className="st-button is-secondary" onClick={async()=>{try{const fresh=await onReload(),latest=fresh.timelines.find(t=>t.id===saved.id);if(!latest)throw new Error("This timeline is unavailable. Your draft is retained.");const next={...draft,name:latest.name,description:latest.description,explanation:latest.explanation};setSaved(latest);setDraft(next);setOriginal(JSON.stringify(next));setError("");setConflict(false);}catch(failure){setError((failure as Error).message);}}}>Load latest timeline</button>}
      {discard&&<div className={styles.feedback}><p>Discard the unsaved timeline draft?</p><button type="button" className="st-button is-secondary" onClick={()=>setDiscard(false)}>Keep writing</button><button type="button" className="st-button" onClick={onClose}>Discard timeline draft</button></div>}
      <footer className={styles.editorFooter}><span>Private World history</span><button className="st-button" disabled={pending}>{pending?"Saving…":create?"Create timeline":"Save timeline"}</button></footer>
    </form>
  </dialog>;
}
export function TimelineManager({bundle,canManage,onSelect,onReload,onDirty,onInterpret}:{bundle:WorldBundle;canManage:boolean;onSelect:(id:string,tab?:"history"|"timelines")=>void;onReload:()=>Promise<WorldBundle>;onDirty:(dirty:boolean)=>void;onInterpret:(review:InheritanceReview)=>void}){
  const [editor,setEditor]=useState<{target:WorldTimeline;create:boolean}|null>(null),[error,setError]=useState(""),[pending,setPending]=useState(false),[showExcluded,setShowExcluded]=useState(false),[limit,setLimit]=useState(30),[search,setSearch]=useState("");
  const timeline=bundle.selectedTimeline,api=`/api/worlds/${bundle.world.id}/timelines`;
  async function action(body:unknown){setError("");setPending(true);try{await worldApi(api,"POST",body);await onReload();}catch(failure){setError((failure as Error).message);}finally{setPending(false);}}
  const reviews=bundle.inheritanceReview.filter(item=>(showExcluded||item.context.mode!=="excluded")&&("title"in item.record?item.record.title:item.record.name).toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  return <section aria-label="Timeline manager" className={styles.story}>
    <div className={styles.sectionHeading}><div><p className={styles.eyebrow}>{bundle.world.name}</p><h2>Timeline manager</h2><p className={styles.muted}>Primary History remains intact. Alternatives inherit pinned sources and contain their own developments.</p></div>{canManage&&!timeline.archived&&<button className="st-button" onClick={()=>setEditor({target:timeline,create:true})}>Create alternate timeline</button>}</div>
    {error&&<p role="alert" className={styles.feedback}>{error}</p>}
    <ul className={styles.timelineBranches}>{bundle.timelines.map(item=><li key={item.id} data-selected={item.id===timeline.id}><div><button className="st-button is-secondary" aria-pressed={item.id===timeline.id} onClick={()=>onSelect(item.id,"timelines")}>{item.name}</button><p>{item.primary?"Primary History":`${bundle.timelines.find(t=>t.id===item.parentId)?.name} → start of Year ${yearLabel(item.divergenceYear!)}`}{item.archived?" · Archived":""}</p></div>{canManage&&<div className={styles.actions}>{!item.archived&&<button className="st-button is-ghost" onClick={()=>setEditor({target:item,create:false})}>Edit {item.name}</button>}{!item.primary&&<button className="st-button is-secondary" disabled={pending} onClick={()=>{if(window.confirm(item.archived?"Restore this timeline and its preserved history?":"Archive this timeline? Descendants remain available and every historical source is retained."))void action({action:item.archived?"restore":"archive",id:item.id,revision:item.revision});}}>{item.archived?"Restore":"Archive"} {item.name}</button>}</div>}</li>)}</ul>
    <h3>{timeline.name}</h3>{timeline.description&&<p className={styles.prose}>{timeline.description}</p>}{timeline.explanation&&<div className={styles.authorNotes}><strong>Why history differs</strong><p className={styles.prose}>{timeline.explanation}</p></div>}
    <div className={styles.actions}><button className="st-button" onClick={()=>onSelect(timeline.id,"history")}>Browse {timeline.name}</button>{!timeline.primary&&<button className="st-button is-secondary" onClick={()=>onSelect(bundle.timelines.find(t=>t.primary)!.id,"history")}>Return to Primary History</button>}</div>
    {!timeline.primary&&<><h3>Inherited source review</h3><p className={styles.caption}>Unresolved accounts are kept outside the effective history. Including a complete source deliberately adopts its full account, including uncertain or later portions. Accepting a newer parent version replaces this branch&apos;s current interpretation and reapplies the divergence rules.</p><label className="st-field">Find inherited source<input className="st-control" type="search" value={search} onChange={event=>{setSearch(event.target.value);setLimit(30);}}/></label><label className={styles.archiveToggle}><input type="checkbox" checked={showExcluded} onChange={event=>{setShowExcluded(event.target.checked);setLimit(30);}}/>Include sources not inherited</label>
    <div className={styles.inheritanceList}>{reviews.slice(0,limit).map(item=><article key={item.record.id} data-entity-id={item.record.id}><h4>{"title"in item.record?item.record.title:item.record.name}</h4><p>{item.availableParent?"New parent source; not adopted":historyContextLabel(item.context)} · {"time"in item.record?timeLabel(item.record.time):eraLabel(item.record)}</p>{item.context.coveredUntil!==null&&<p>Existence known through Year {yearLabel(item.context.coveredUntil)}; later continuation is unknown.</p>}<p className={styles.excerpt}>{"account"in item.record?item.record.account:item.record.description}</p><small>Source: {bundle.timelines.find(t=>t.id===item.context.sourceTimelineId)?.name} · pinned revision {item.context.sourceRevision}{item.context.newerParent?" · Newer parent version available":""}</small><details><summary>Read complete pinned source</summary><p className={styles.prose}>{"account"in item.record?item.record.account:item.record.description}</p>{"notes"in item.record&&<p className={styles.prose}>{item.record.notes}</p>}</details>{canManage&&!timeline.archived&&item.availableParent&&<button className="st-button is-secondary" disabled={pending} onClick={()=>void action({action:"adopt-parent",id:timeline.id,revision:timeline.revision,entityId:item.record.id,parentRevision:item.context.parentRevision,parentVersionId:item.context.parentVersionId})}>Review new parent source</button>}{canManage&&!timeline.archived&&!item.availableParent&&<div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={()=>{if(window.confirm("Adopt this complete source in the selected branch, including any uncertain or post-divergence portions?"))void action({action:"resolve",id:timeline.id,entityId:item.record.id,revision:item.record.revision,decision:"include"});}}>Include complete source</button><button className="st-button is-secondary" disabled={pending} onClick={()=>void action({action:"resolve",id:timeline.id,entityId:item.record.id,revision:item.record.revision,decision:"exclude"})}>Exclude from this history</button>{item.context.mode!=="pending"&&item.context.mode!=="excluded"&&!item.record.archived&&<button className="st-button" onClick={()=>onInterpret(item)}>Write branch interpretation</button>}{item.context.newerParent&&<button className="st-button" disabled={pending} onClick={()=>{if(window.confirm("Replace this branch interpretation with the parent's latest version and reassess inheritance? Existing descendants will keep their pinned versions."))void action({action:"accept-parent",id:timeline.id,entityId:item.record.id,revision:item.record.revision,parentRevision:item.context.parentRevision,parentVersionId:item.context.parentVersionId});}}>Accept newer parent version</button>}</div>}</article>)}</div>{reviews.length>limit&&<button className="st-button is-secondary" onClick={()=>setLimit(limit+30)}>More inherited sources</button>}{!reviews.length&&<p>No matching inherited sources.</p>}</>}
    {editor&&<TimelineEditor target={editor.target} create={editor.create} bundle={bundle} onDirty={onDirty} onClose={()=>setEditor(null)} onReload={onReload} onSave={async body=>{const result=await worldApi<{id:string}>(api,"POST",body);setEditor(null);await onReload();if(editor.create)onSelect(result.id,"history");}}/>}
  </section>;
}
