"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, BookOpen, Feather, Plus, X } from "lucide-react";
import { accuracyLabels, chronologicalEntries, narrativeLabels, type EntryRecord, type EraRecord, type TagReference, type WorldBundle, type WorldRecord } from "./history";
import { SaveError, worldApi } from "./client-api";
import { WorldCover } from "./world-registry";
import { WorldEditor, type EditorTarget } from "./world-editor";
import { HistoricalTimeline } from "./historical-timeline";
import styles from "./worlds.module.css";
import { formatEra, formatTime, type DatingSystem } from "./chronology";
import { ChronologyWorkspace } from "./chronology-workspace";
type Selected = {kind:"era";record:EraRecord} | {kind:"entry";record:EntryRecord};
function HistoryDetails({ selected, eras, displaySystem, canEdit, pending, error, onClose, onEdit, onLifecycle }: { selected: Selected; eras: EraRecord[]; displaySystem?:DatingSystem|null; canEdit: boolean; pending: boolean; error: string; onClose: () => void; onEdit: () => void; onLifecycle: () => Promise<void> }) {
  const ref = useRef<HTMLDialogElement>(null);
  const [confirm,setConfirm] = useState(false);
  useEffect(() => {ref.current?.showModal();},[]);
  const entry = selected.kind === "entry" ? selected.record : null;
  const era = selected.kind === "era" ? selected.record : null;
  return <dialog ref={ref} className={styles.editor} aria-labelledby="history-detail-title" onCancel={(event) => {if(pending) event.preventDefault(); else onClose();}}><header className={styles.editorHeader}><div><p className={styles.eyebrow}>{era ? "Historical era" : "Historical entry"} {selected.record.archived && "· Archived"}</p><h2 id="history-detail-title">{era?.name ?? entry?.title}</h2></div><button className="st-button is-ghost" aria-label="Close historical details" disabled={pending} onClick={onClose}><X size={20}/></button></header><div className={styles.reader}><p className={styles.dateHeading}>{era ? formatEra(era,displaySystem) : formatTime(entry!.time,displaySystem)}</p>{entry && <div className={styles.chips}><span data-planned={entry.narrative === "planned"}>{narrativeLabels[entry.narrative]}</span><span>{accuracyLabels[entry.accuracy]}</span>{eras.filter((item) => entry.eraIds.includes(item.id)).map((item) => <span key={item.id}>{item.name}{item.archived ? " · archived era" : ""}</span>)}</div>}<div className={styles.prose}>{era?.description || entry?.account || "No historical account has been written yet."}</div>{selected.record.sourceDating && <aside className={styles.authorNotes}><h3>Original dating context</h3><p>{selected.record.sourceDating.name} · revision {selected.record.sourceDating.revision}</p><p>{selected.record.sourceDating.origin}</p><p>{era ? formatEra(era,selected.record.sourceDating) : formatTime(entry!.time,selected.record.sourceDating)}</p></aside>}{entry?.notes && <aside className={styles.authorNotes}><h3>Author notes</h3><p className={styles.prose}>{entry.notes}</p></aside>}</div>{error && <p role="alert" className={styles.feedback}>{error}</p>}{confirm && <div className={styles.feedback}><p>{selected.record.archived ? "Restore this account to active history?" : era ? "Archive this era? Its entries and associations will be kept." : "Archive this entry? Its historical account will be kept."}</p><div className={styles.actions}><button className="st-button is-secondary" disabled={pending} onClick={() => setConfirm(false)}>Cancel</button><button className="st-button" disabled={pending} onClick={onLifecycle}>{pending ? "Saving…" : selected.record.archived ? "Restore history" : "Archive history"}</button></div></div>}<footer className={styles.editorFooter}><span className={styles.muted}>Private world material</span><div className={styles.actions}>{canEdit && <><button className="st-button is-secondary" disabled={pending} onClick={() => setConfirm(true)}>{selected.record.archived ? "Restore" : "Archive"}</button>{!selected.record.archived && <button className="st-button" disabled={pending} onClick={onEdit}><Feather size={16}/>Edit {era ? "era" : "entry"}</button>}</>}<button className="st-button is-secondary" disabled={pending} onClick={onClose}>Close</button></div></footer></dialog>;
}
export function WorldWorkspace({ initialBundle, worlds, tags, review }: { initialBundle:WorldBundle;worlds:WorldRecord[];tags:TagReference[];review:boolean }) {
  const router = useRouter();
  const [bundle,setBundle] = useState(initialBundle);
  const [tab,setTab] = useState<"overview"|"history"|"chronology">("overview");
  const [mode,setMode] = useState<"timeline"|"list">("timeline");
  const [editor,setEditor] = useState<EditorTarget|null>(null);
  const [selected,setSelected] = useState<Selected|null>(null);
  const [query,setQuery] = useState("");
  const [accuracy,setAccuracy] = useState("");
  const [narrative,setNarrative] = useState("");
  const [eraFilter,setEraFilter] = useState("");
  const [archived,setArchived] = useState(false);
  const [limit,setLimit] = useState(40);
  const [pending,setPending] = useState(false);
  const [error,setError] = useState("");
  const [detailError,setDetailError] = useState("");
  const [notice,setNotice] = useState("");
  const [displaySystemId,setDisplaySystemId] = useState(initialBundle.defaultDatingSystemId);
  const displaySystem = bundle.datingSystems.find((system)=>system.id===displaySystemId) ?? null;
  const world = bundle.world;
  const canEdit = bundle.canEdit && !review;
  const apiUrl = `/api/worlds/${world.id}`;
  async function reload() {const fresh = await worldApi<WorldBundle>(`${apiUrl}${review ? "?review=1" : ""}`); setBundle(fresh); return fresh;}
  function selectEntry(record:EntryRecord) {setDetailError("");setSelected({kind:"entry",record});}
  function selectEra(record:EraRecord) {setDetailError("");setSelected({kind:"era",record});}
  const search = query.trim().toLocaleLowerCase();
  const entries = chronologicalEntries(bundle.entries.filter((entry) => entry.archived === archived && (!accuracy || entry.accuracy === accuracy) && (!narrative || entry.narrative === narrative) && (!eraFilter || (eraFilter === "none" ? entry.eraIds.length === 0 : entry.eraIds.includes(eraFilter))) && (!search || `${entry.title} ${entry.account} ${entry.notes}`.toLocaleLowerCase().includes(search))));
  const eras = bundle.eras.filter((era) => era.archived === archived);
  const activeEntries = bundle.entries.filter((entry) => !entry.archived);
  const activeEras = bundle.eras.filter((era) => !era.archived);
  return <main className={styles.page}><div className={styles.content}>
    <div className={styles.workspaceBar}><Link href={`/worlds${review ? "?scope=review" : ""}`}><ArrowLeft size={16}/>World registry</Link><label className={styles.switcher}><span>Switch world</span><select className="st-control" aria-label="Switch world" value={world.id} onChange={(event) => router.push(`/worlds/${event.target.value}${review ? "?review=1" : ""}`)}>{worlds.map((item) => <option value={item.id} key={item.id}>{item.name}{item.archived ? " (archived)" : ""}</option>)}</select></label></div>
    {(review || world.archived) && <p className={styles.reviewBanner}>{review ? `Administrator review · Read-only · Owner: ${world.ownerName}` : "This world is archived. Its history is preserved. Restore it from the registry to continue writing."}</p>}
    <header className={styles.worldHero}><WorldCover world={world} large/><div className={styles.worldIdentity}><p className={styles.eyebrow}>A private world of Serrian Tide</p><h1>{world.name}</h1><p className={styles.lead}>{world.description || "A world taking shape, one story at a time."}</p><div className={styles.chips}>{tags.filter((tag) => world.tagIds.includes(tag.id)).map((tag) => <span key={tag.id}>{tag.name}</span>)}</div><div className={styles.worldStats}><span><strong>{world.eraCount}</strong> historical eras</span><span><strong>{world.entryCount}</strong> entries</span></div>{canEdit && <button className="st-button is-secondary" onClick={() => setEditor({kind:"world",record:world,section:"identity"})}>Edit identity</button>}</div></header>
    <nav className={styles.workspaceTabs} aria-label="World workspace"><button aria-current={tab === "overview" ? "page" : undefined} className={tab === "overview" ? styles.activeTab : ""} onClick={() => setTab("overview")}>Overview</button><button aria-current={tab === "history" ? "page" : undefined} className={tab === "history" ? styles.activeTab : ""} onClick={() => setTab("history")}>History <span>{world.entryCount}</span></button><button aria-current={tab === "chronology" ? "page" : undefined} className={tab === "chronology" ? styles.activeTab : ""} onClick={()=>setTab("chronology")}>Chronology</button></nav>
    {tab !== "chronology" && <label className={styles.displayConvention}>View years using<select aria-label="View years using" className="st-control" value={displaySystemId ?? ""} onChange={(event)=>setDisplaySystemId(event.target.value || null)}><option value="">Canonical world years</option>{bundle.datingSystems.map((system)=><option value={system.id} key={system.id}>{system.name}{system.archived ? " (archived context)" : ""}</option>)}</select><span className={styles.muted}>Changes labels only. Historical positions stay fixed.</span></label>}
    <div hidden={tab !== "chronology"}><ChronologyWorkspace bundle={bundle} canEdit={canEdit} reload={reload} onDefaultChanged={setDisplaySystemId}/></div>
    {error && <div className={styles.feedback} role="alert"><p>{error}</p><button className="st-button is-secondary" onClick={() => reload().then(() => setError("")).catch((failure) => setError(failure.message))}>Reload saved history</button></div>}
    {notice && <p className={styles.notice} role="status">{notice}</p>}
    <div hidden={tab !== "overview"}>
      <div className={styles.overviewGrid}><section className={styles.story}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>The opening pages</p><h2>Introduction</h2></div>{canEdit && <button className="st-button is-ghost" onClick={() => setEditor({kind:"world",record:world,section:"introduction"})}><Feather size={16}/>Write introduction</button>}</div><div className={styles.prose}>{world.introduction || "What kind of world is this? Begin with the story a newcomer should hear."}</div></section><aside className={styles.recent}><p className={styles.eyebrow}>Fresh from the archive</p><h2>Recently written</h2>{[...activeEntries].sort((a,b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0,4).map((entry) => <button key={entry.id} className={styles.readingLink} onClick={() => selectEntry(entry)}><span>{entry.title}</span><small>{formatTime(entry.time,displaySystem)}{entry.narrative === "planned" ? " · Planned" : ""}</small></button>)}{!activeEntries.length && <p className={styles.muted}>Your world&apos;s turning points will gather here.</p>}{canEdit && <button className="st-button is-secondary" onClick={() => setEditor({kind:"entry"})}><Plus size={16}/>Write a historical entry</button>}</aside></div>
      <HistoricalTimeline displaySystem={displaySystem} compact eras={activeEras} entries={activeEntries} onEntry={selectEntry} onEra={selectEra}/>
      <section className={styles.story}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Across the ages</p><h2>Historical overview</h2></div>{canEdit && <button className="st-button is-ghost" onClick={() => setEditor({kind:"world",record:world,section:"history"})}>Write historical overview</button>}</div><div className={styles.prose}>{world.historicalOverview || "Draw together the ages and events that shaped this world. The detailed record lives in History."}</div><button className="st-button is-secondary" onClick={() => setTab("history")}><BookOpen size={17}/>Explore full history</button></section>
    </div>
    <div hidden={tab !== "history"}>
      <div className={styles.sectionHeading}><div><p className={styles.eyebrow}>The historical record</p><h2>Ages & turning points</h2></div>{canEdit && <div className={styles.actions}><button className="st-button is-secondary" onClick={() => setEditor({kind:"era"})}><Plus size={16}/>New era</button><button className="st-button" onClick={() => setEditor({kind:"entry"})}><Plus size={16}/>New entry</button></div>}</div>
      <div className={styles.historyFilters}><label>Search history<input className="st-control" type="search" value={query} onChange={(e) => {setQuery(e.target.value);setLimit(40);}} placeholder="Find an account…"/></label><label>Narrative status<select aria-label="Narrative status" className="st-control" value={narrative} onChange={(e) => {setNarrative(e.target.value);setLimit(40);}}><option value="">All statuses</option>{Object.entries(narrativeLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Accuracy<select aria-label="Accuracy" className="st-control" value={accuracy} onChange={(e) => {setAccuracy(e.target.value);setLimit(40);}}><option value="">All accounts</option>{Object.entries(accuracyLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Historical era<select aria-label="Historical era" className="st-control" value={eraFilter} onChange={(e) => {setEraFilter(e.target.value);setLimit(40);}}><option value="">All eras</option><option value="none">No era association</option>{bundle.eras.map((era) => <option value={era.id} key={era.id}>{era.name}{era.archived ? " (archived)" : ""}</option>)}</select></label></div>
      <div className={styles.historyViewBar}><div className={styles.tabs} role="group" aria-label="History presentation"><button className={mode === "timeline" ? styles.activeTab : ""} aria-pressed={mode === "timeline"} onClick={() => setMode("timeline")}>Timeline</button><button className={mode === "list" ? styles.activeTab : ""} aria-pressed={mode === "list"} onClick={() => setMode("list")}>Chronological list</button></div><label className={styles.archiveToggle}><input type="checkbox" checked={archived} onChange={(e) => {setArchived(e.target.checked);setLimit(40);}}/>View archived history</label><span className={styles.muted}>{entries.length} matching entries</span></div>
      <div hidden={mode !== "timeline"}><HistoricalTimeline displaySystem={displaySystem} eras={eras} entries={entries} onEntry={selectEntry} onEra={selectEra}/></div>
      <div hidden={mode !== "list"} className={styles.chronicle} aria-label="Chronological history"><p className={styles.caption}>Windows are ordered by their earliest possible year; durations by their beginning. Undated accounts appear last.</p>{entries.slice(0,limit).map((entry) => <article className={styles.chronicleEntry} key={entry.id} data-planned={entry.narrative === "planned"}><div className={styles.chronicleDate}>{formatTime(entry.time,displaySystem)}<small>{narrativeLabels[entry.narrative]}</small></div><div><div className={styles.chips}><span>{accuracyLabels[entry.accuracy]}</span><span>{entry.time.kind === "window" ? "Uncertain occurrence" : entry.time.kind === "duration" ? "Duration" : entry.time.kind === "approximate" ? "Approximate" : entry.time.kind === "undated" ? "Undated" : "Known date"}</span></div><h3><button onClick={() => selectEntry(entry)}>{entry.title}</button></h3><p className={styles.excerpt}>{entry.account}</p><button className="st-button is-ghost" onClick={() => selectEntry(entry)}>Read account</button></div></article>)}{!entries.length && <div className={styles.emptyState}><BookOpen size={36}/><h3>No matching historical entries</h3><p>Write a first account, or adjust the filters.</p></div>}{entries.length > limit && <button className="st-button is-secondary" onClick={() => setLimit(limit+40)}>Read more entries</button>}</div>
      <details className={styles.eraCollection} open><summary>Historical eras <span>{eras.length}</span></summary><div className={styles.eraGrid}>{eras.map((era) => <button key={era.id} className={styles.eraCard} data-tone={era.tone} onClick={() => selectEra(era)}><span>{era.name}</span><small>{formatEra(era,displaySystem)}</small><p>{era.description || "An age waiting to be described."}</p></button>)}</div>{!eras.length && <p className={styles.muted}>{archived ? "No archived eras." : "Create the ages that give your world its historical shape. Their dates can overlap or remain unknown."}</p>}</details>
    </div>
    {selected && <HistoryDetails key={`${selected.kind}:${selected.record.id}:${selected.record.revision}`} selected={selected} eras={bundle.eras} displaySystem={displaySystem} canEdit={canEdit} pending={pending} error={detailError} onClose={() => setSelected(null)} onEdit={() => {setEditor(selected);setSelected(null);}} onLifecycle={async () => {setPending(true);setDetailError("");try{await worldApi(`${apiUrl}/history`,"POST",{entity:selected.kind,id:selected.record.id,revision:selected.record.revision,action:selected.record.archived ? "restore" : "archive"});setSelected(null);setNotice("Historical record saved. Its account and associations are preserved.");try{await reload();}catch(failure){setError(failure instanceof Error ? `Saved successfully. ${failure.message}` : "Saved; reload history to see the change.");}}catch(failure){setDetailError(failure instanceof Error ? failure.message : "The change failed.");}finally{setPending(false);}}}/>}
    {editor && <WorldEditor key={`${editor.kind}:${editor.record?.id ?? "new"}:${editor.record?.revision ?? 0}:${editor.kind === "world" ? editor.section : ""}`} target={editor} tags={tags} eras={bundle.eras} datingSystems={bundle.datingSystems} displaySystem={displaySystem} onClose={() => setEditor(null)} onReload={editor.record ? async () => {const fresh = await reload();if(editor.kind === "world") setEditor({...editor,record:fresh.world});else if(editor.kind === "era"){const record = fresh.eras.find((era) => era.id === editor.record!.id);if(!record)throw new SaveError("This era is unavailable. Your draft is retained.",404);setEditor({kind:"era",record});}else{const record = fresh.entries.find((entry) => entry.id === editor.record!.id);if(!record)throw new SaveError("This entry is unavailable. Your draft is retained.",404);setEditor({kind:"entry",record});}} : undefined} onSave={async (draft) => {if(editor.kind === "world") await worldApi(apiUrl,"PATCH",{action:"save",revision:editor.record!.revision,draft});else await worldApi(`${apiUrl}/history`,"POST",{entity:editor.kind,id:editor.record?.id,revision:editor.record?.revision,action:"save",draft});setEditor(null);setNotice("Saved to your private world.");try{await reload();}catch(failure){setError(failure instanceof Error ? `Saved successfully. ${failure.message}` : "Saved; reload history to see the change.");}}}/>}
  </div></main>;
}
