"use client";
import { useEffect, useRef, useState } from "react";
import { addExceptionalResponder, cancelActionDeclaration, abandonActionDeclaration, continueActionDeclarationAfterRuling, resumeInterruptedActionDeclaration } from "@/app/heavens/tabletop/action-declaration-actions";
import { ruleGodPlayerCombatRequest } from "@/app/heavens/tabletop/player-combat-ruling-actions";
import { changeCombatParticipation, ruleCombatCondition, resolveCombatRevivalExpiration } from "@/app/heavens/tabletop/combat-participation-actions";
import { ruleOnDefenseIntervention } from "@/app/heavens/tabletop/defense-intervention-actions";
import { withdrawCombatCheckpoint } from "@/app/heavens/tabletop/combat-recovery-actions";
import { applyCombatFirearmResult, commitCombatFirearmTrigger } from "./operation-actions";
import type { CombatFocus, CombatOperations } from "./next-input";
import { EffectRuling, EffectEvidence } from "./effect-ruling";
import { combatMessage } from "./form-controls";
import { combatRollSummary } from "./result-summary";
import { isOrdinaryAttackReport, isSpellResultReport } from "./attack-report";
import type { CombatEntity, CombatScreenData, CombatScreenScope } from "./screen-types";
import styles from "./combat-screen.module.css";
const object = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
export function OperationPanel({ scope, data, entity, operations, focus, disabled, refresh }: { scope: CombatScreenScope; data: CombatScreenData; entity: CombatEntity; operations: CombatOperations | null; focus: CombatFocus | null; disabled: boolean; refresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [reason, setReason] = useState(""), [penalty, setPenalty] = useState(""), [treatment, setTreatment] = useState<"preserve" | "zero">("preserve");
  const running = useRef(false), requests = useRef<Record<string, string>>({});
  const controls = useRef<HTMLDetailsElement>(null);
  useEffect(() => { if (focus?.participantId === entity.participantId && (focus.kind === "response" || focus.kind === "ruling" && !focus.planId) && controls.current) controls.current.open = true; }, [focus, entity.participantId]);
  const closed = !!data.projection?.closed, ordinaryDisabled = disabled || closed || busy;
  const actions = data.projection?.declarations.filter((entry) => entry.actorCharacterId === entity.participantId) ?? [];
  const revivals = (data.information?.entity.participantId === entity.participantId ? data.information.combatHistory?.revivals : []) ?? [];
  async function run(operation: () => Promise<unknown>, success = "Combat updated.") {
    if (running.current) return; running.current = true; setBusy(true); setMessage("");
    try { const result = await operation(); const status = object(result).status;
      setMessage(status === "requires-god-ruling" || status === "partially-applied" ? "Supported work was checked. Resolve the specific remaining question below." : status === "awaiting-response" ? "Resolve the confirmed responses before applying this result." : status === "awaiting-completion" ? "The recorded defense added Initiative. Complete that remaining timing before applying consequences." : success); await refresh(); }
    catch (error) { setMessage(combatMessage(error instanceof Error ? error.message : "The command was not confirmed. Refresh and inspect before retrying.")); await refresh(); }
    finally { running.current = false; setBusy(false); }
  }
  function request(value: unknown) { const key = JSON.stringify(value); return requests.current[key] ||= crypto.randomUUID(); }
  return <div>
    {actions.filter((entry) => entry.timing?.status === "active" && entry.status === "awaiting-god-ruling").map((entry) => <p className={styles.notice} key={entry.id}>{entry.lockedSnapshot?.label ?? entry.draft.label}: the recorded Roll needs a G.O.D. ruling. The action still has {entry.timing?.remainingInitiativeCost} Initiative remaining. Its damage and final outcome have not been applied. Resolve any earlier completed actions before advancing to this action’s completion.</p>)}
    {scope.role === "player" ? actions.filter((entry) => entry.timing?.status === "completed" && !["resolved", "cancelled", "abandoned"].includes(entry.status)).map((entry) => <p className={styles.notice} key={entry.id}>{entry.lockedSnapshot?.label ?? entry.draft.label}: timing complete. Waiting for the G.O.D. to review the result. Your next action becomes available after this result is settled.</p>) : null}
    {operations?.firearms?.attacks.filter((attack) => attack.actorParticipantId === entity.participantId).map((attack) => <details key={attack.id}><summary>{attack.itemName} · {attack.attackFinalized && attack.effectPlanStatus === "applied" && attack.effectiveStatus !== "cancelled" ? "resolved" : attack.effectiveStatus.replaceAll("-", " ")}</summary><p>{attack.roundsConsumed} rounds fired · {attack.firingPortionsResolved} firing portions completed</p>{attack.rulingReasons.map((reason) => <p key={reason}>{combatMessage(reason)}</p>)}
      {attack.aimTimingStatus === "completed" && !attack.triggerPendingActionId ? <button className="st-button" disabled={ordinaryDisabled || !entity.canControl} onClick={() => void run(() => commitCombatFirearmTrigger(scope, attack.id), "Firing committed with the original declaration Roll.")}>Aim complete: begin firing</button> : null}
      {(scope.role === "god" || entity.canControl) && attack.triggerTimingStatus === "completed" && attack.effectPlanStatus !== "applied" ? <button className="st-button" disabled={ordinaryDisabled} onClick={() => void run(() => applyCombatFirearmResult(scope, attack.id), "Firearm consequences reconciled with the original Roll.")}>Resolve firearm result</button> : null}
      {attack.bullets.map((bullet) => <div key={bullet.id}><p>Bullet {bullet.bulletIndex} · {bullet.status} · {bullet.hitLocationName} · {bullet.proposedNetDamage ?? "ruling required"} damage</p>
        {bullet.grossDamage !== null ? <p className={styles.muted}>{bullet.authoredDamage} ammunition damage + {bullet.dexDamageModifier} DEX + {bullet.additionalSuccessDamage} additional-success damage = {bullet.grossDamage} before protection. Armor {bullet.armor ?? "requires ruling"} · Soak {bullet.soak ?? "requires ruling"} · net {bullet.proposedNetDamage ?? "requires ruling"}. Damage cannot fall below zero.</p> : null}
      </div>)}
    </details>)}
    {scope.role === "god" && entity.participantId > 0 && entity.canControl && !closed ? <div className={styles.notice}>
      <p>{entity.participation.departureKind === "surrender" ? "This NPC has surrendered / yielded. Actions and responses are stopped; their condition and history are preserved." : "If this NPC gives up the fight, record their surrender here. G.O.D. assigns any XP and Fame in closeout."}</p>
      <button className="st-button" disabled={ordinaryDisabled || entity.condition.status !== "able" || entity.participation.departed}
        onClick={() => void run(() => changeCombatParticipation(scope.encounterId, { participantId: entity.participantId, operation: "surrender",
          reason: reason.trim() || "NPC surrendered / yielded.", expectedRevision: entity.participation.revision,
          requestKey: request({ participant: entity.participantId, operation: "surrender", revision: entity.participation.revision, reason }) }), "Surrender recorded. The NPC no longer receives action or response prompts.")}>Surrender / Yield</button>
    </div> : null}
    {scope.role === "god" ? <details><summary>Death, incapacitation &amp; participation</summary><label className="st-field">Condition / participation reason<textarea className="st-control" value={reason} onChange={(event) => setReason(event.target.value)} /></label><p>{combatMessage(entity.statusText)}</p><div className={styles.actions}>
        {(["withdraw", "confirm-escape", "arrive"] as const).map((operation) => <button className="st-button" key={operation} disabled={ordinaryDisabled || !reason.trim() || operation === "arrive" && !entity.participation.departed} onClick={() => void run(() => changeCombatParticipation(scope.encounterId, { participantId: entity.participantId, operation, reason, expectedRevision: entity.participation.revision,
          requestKey: request({ participant: entity.participantId, operation, revision: entity.participation.revision, reason }) }), operation === "arrive" ? "Combatant returned with preserved Initiative and debt." : "Departure recorded. Membership and history are preserved.")}>{operation === "withdraw" ? "Withdraw from combat" : operation === "confirm-escape" ? "Confirm escape" : "Return to combat"}</button>)}
      </div><label className="st-field">Incapacitation Initiative treatment<select className="st-control" value={treatment} onChange={(event) => setTreatment(event.target.value as "preserve" | "zero")}><option value="preserve">Preserve Initiative</option><option value="zero">Zero under the specific condition rule</option></select></label><div className={styles.actions}>
        {(["dead", "incapacitated", "able"] as const).map((status) => <button className="st-button" key={status} disabled={disabled || busy || !reason.trim()} onClick={() => void run(() => ruleCombatCondition(scope.encounterId, { participantId: entity.participantId, status, reason, initiativeTreatment: status === "incapacitated" ? treatment : undefined, expectedRevision: entity.condition.revision,
          requestKey: request({ participant: entity.participantId, status, revision: entity.condition.revision, reason, treatment }) }))}>{status === "able" ? "Confirm resolved condition" : status === "dead" ? "Rule death" : "Rule incapacitation"}</button>)}
      </div>{revivals.map(object).filter((revival) => revival.status === "awaiting-ruling").map((revival) => <div className={styles.notice} key={String(revival.effectId)}><p>{String(revival.expirationConsequence)}</p><div className={styles.actions}>{[true, false].map((stabilized) => <button className="st-button" key={String(stabilized)} disabled={disabled || busy || !reason.trim()} onClick={() => void run(() => resolveCombatRevivalExpiration(scope.encounterId, { participantId: entity.participantId, effectId: Number(revival.effectId), stabilized, reason }))}>{stabilized ? "Stabilization succeeded" : "Stabilization failed"}</button>)}</div></div>)}</details> : null}
    {scope.role === "god" ? <details ref={controls}><summary>G.O.D. controls for {entity.name}</summary>
      <label className="st-field">Ruling / participation reason<textarea className="st-control" value={reason} onChange={(event) => setReason(event.target.value)} /></label>
      {operations?.requests.filter((entry) => entry.characterId === entity.participantId && ["pending", "clarification-requested"].includes(entry.status)).map((entry) => <fieldset key={entry.id}><legend>{entry.requestType.replaceAll("-", " ")}</legend><p>{entry.intent}</p>{entry.requestType === "called-shot" ? <label className="st-field">Called Shot penalty<input className="st-control" type="number" min="0" value={penalty} onChange={(event) => setPenalty(event.target.value)} /></label> : null}<div className={styles.actions}>{(["approved", "rejected", "clarification-requested"] as const).map((status) => <button className="st-button" key={status} disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => ruleGodPlayerCombatRequest(scope.encounterId, entry.id, { status, response: reason, rulingReason: reason, calledShotPenalty: penalty === "" ? null : Number(penalty) }), "Player request reviewed.")}>{status === "approved" ? "Approve" : status === "rejected" ? "Reject" : "Request clarification"}</button>)}</div></fieldset>)}
      {operations?.defenses?.reactions.filter((entry) => entry.responderCharacterId === entity.participantId && entry.status === "needs-ruling").map((entry) => <fieldset key={entry.id}><legend>{entry.reactionType}: defense ruling</legend><p>{entry.rulingReason || entry.outcome}</p><EffectEvidence value={entry.objectiveComparison} /><div className={styles.actions}><button className="st-button" disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => ruleOnDefenseIntervention(scope.encounterId, entry.id, { disposition: "continue", defenseSucceeded: false, reason }))}>Attack continues</button><button className="st-button" disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => ruleOnDefenseIntervention(scope.encounterId, entry.id, { disposition: "cancel", defenseSucceeded: true, reason }))}>Defense cancels attack</button></div></fieldset>)}
      <details><summary>Unfinished actions &amp; interventions</summary>{actions.filter((entry) => !["resolved", "cancelled", "abandoned"].includes(entry.status)).map((entry) => <div key={entry.id}><p>{entry.lockedSnapshot?.label ?? entry.draft.label} · {entry.status}</p><div className={styles.actions}>
        <button className="st-button" disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => cancelActionDeclaration(scope.encounterId, entry.id, reason))}>Cancel unfinished action</button>
        {entry.status === "interrupted" ? <><button className="st-button" disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => resumeInterruptedActionDeclaration(scope.encounterId, entry.id, reason))}>Resume interrupted action</button><button className="st-button" disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => abandonActionDeclaration(scope.encounterId, entry.id, reason))}>Abandon interrupted action</button></> : null}
        {entry.status === "awaiting-god-ruling" ? <button className="st-button" disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => continueActionDeclarationAfterRuling(scope.encounterId, entry.id, reason))}>Continue after ruling</button> : null}</div></div>)}
        {data.projection?.declarations.filter((entry) => entry.timing?.status === "active" && entry.actorCharacterId !== entity.participantId).map((entry) => <button className="st-button" key={entry.id} disabled={ordinaryDisabled || !reason.trim() || operations?.sealed || !!entity.currentAction} onClick={() => void run(() => addExceptionalResponder(scope.encounterId, entry.id, entity.participantId, reason))}>Authorize {entity.name} intervention in {entry.lockedSnapshot?.label ?? entry.draft.label}</button>)}
        {data.projection?.checkpoint ? <button className="st-button" disabled={ordinaryDisabled || !reason.trim()} onClick={() => void run(() => withdrawCombatCheckpoint(scope.encounterId, { checkpointId: data.projection!.checkpoint!.id, reason }), "Simultaneous choices withdrawn through explicit recovery.")}>Recover incomplete simultaneous choices</button> : null}
      </details>
    </details> : null}
    {scope.role === "god" ? operations?.plans.filter((plan) => !["applied", "cancelled", "declined", "superseded"].includes(plan.status) && !isSpellResultReport(plan) && (!isOrdinaryAttackReport(plan) || plan.status === "partially-applied" || plan.effects.length !== 1) && (plan.actorParticipantId === entity.participantId || plan.effects.some((effect) => effect.targetParticipantId === entity.participantId))).map((plan) => <EffectRuling key={plan.id} encounterId={scope.encounterId} plan={plan} focusSequence={focus?.participantId === entity.participantId && focus.planId === plan.id ? focus.sequence : undefined} disabled={disabled || busy} closed={closed} refresh={refresh} />) : null}
    <details><summary>Rolls &amp; results</summary>{operations?.rolls.filter((roll) => roll.rollerCharacterId === entity.participantId || roll.targetCharacterId === entity.participantId).map((roll) => <p key={roll.id}>{roll.rollerCharacterName} · {roll.label}: {combatRollSummary(roll)}{roll.rulingText ? ` · ${roll.rulingText}` : ""}</p>)}{operations?.outcomes.filter((outcome) => outcome.actorId === entity.participantId || outcome.targetId === entity.participantId).map((outcome) => <p key={outcome.id}>{outcome.actor} → {outcome.target}: {outcome.label} · {outcome.summary}</p>)}
      {scope.role === "god" ? operations?.plans.filter((plan) => ["applied", "cancelled", "declined", "superseded"].includes(plan.status) && (plan.actorParticipantId === entity.participantId || plan.effects.some((effect) => effect.targetParticipantId === entity.participantId))).map((plan) => <EffectRuling key={plan.id} encounterId={scope.encounterId} plan={plan} disabled closed={closed} refresh={refresh} />) : null}
    </details>
    {message ? <p role="status">{message}</p> : null}
  </div>;
}
