import assert from "node:assert/strict";
import test from "node:test";

import {
  assertCreatureCanonicalIdsSystemOwned,
  createCreatureDraftCanonicalId,
  createCreatureCanonicalIdentity,
  isCreatureDraftCanonicalId,
  resolveSystemAssignedCreatureIds,
} from "./creature-canonical-ids";

test("temporary IDs use getRandomValues when randomUUID is unavailable", () => {
  const bytes = Uint8Array.from({ length: 16 }, (_, index) => index);
  const identity = createCreatureCanonicalIdentity({
    getRandomValues: <T extends ArrayBufferView | null>(target: T): T => {
      if (!(target instanceof Uint8Array)) throw new Error("Expected UUID bytes.");
      target.set(bytes);
      return target as T;
    },
  } as Crypto);

  assert.equal(identity, "00010203-0405-4607-8809-0a0b0c0d0e0f");
  assert.match(`DRAFT-CREATURE-${identity.toUpperCase()}`, /^DRAFT-CREATURE-[0-9A-F-]{36}$/);
  assert.throws(
    () => createCreatureCanonicalIdentity({} as Crypto),
    /browser cannot create a temporary Creature ID/,
  );
});

test("Creature editors receive opaque temporary IDs without user-authored values", () => {
  const ids = [
    createCreatureDraftCanonicalId("CREATURE"),
    createCreatureDraftCanonicalId("HP"),
    createCreatureDraftCanonicalId("ATK"),
    createCreatureDraftCanonicalId("ABL"),
  ];

  assert.equal(new Set(ids).size, ids.length);
  assert.match(ids[0]!, /^DRAFT-CREATURE-[0-9A-F-]{36}$/);
  assert.match(ids[1]!, /^DRAFT-HP-[0-9A-F-]{36}$/);
  assert.match(ids[2]!, /^DRAFT-ATK-[0-9A-F-]{36}$/);
  assert.match(ids[3]!, /^DRAFT-ABL-[0-9A-F-]{36}$/);
  assert.ok(ids.every(isCreatureDraftCanonicalId));
});

test("a new master Creature receives server-owned IDs for every canonical identity", () => {
  const assigned = resolveSystemAssignedCreatureIds({
    core: { canonicalId: "USER-CREATURE" },
    hpPools: [{ canonicalId: "USER-POOL" }],
    hitLocations: [{ hpPoolCanonicalId: "USER-POOL" }],
    attacks: [{ canonicalId: "USER-ATTACK" }],
    abilities: [{ canonicalId: "USER-ABILITY" }],
  }, true);

  assert.match(assigned.coreCanonicalId, /^CREATURE-[0-9A-F-]{36}$/);
  assert.match(assigned.hpPoolCanonicalIds[0]!, /^HP-[0-9A-F-]{36}$/);
  assert.equal(assigned.hitLocationPoolCanonicalIds[0], assigned.hpPoolCanonicalIds[0]);
  assert.match(assigned.attackCanonicalIds[0]!, /^ATK-[0-9A-F-]{36}$/);
  assert.match(assigned.abilityCanonicalIds[0]!, /^ABL-[0-9A-F-]{36}$/);
});

test("existing Creature IDs remain stable while new child records receive persisted IDs", () => {
  const draftPool = createCreatureDraftCanonicalId("HP");
  const draftAttack = createCreatureDraftCanonicalId("ATK");
  const draftAbility = createCreatureDraftCanonicalId("ABL");
  const assigned = resolveSystemAssignedCreatureIds({
    core: { canonicalId: "CREATURE-STORED" },
    hpPools: [{ canonicalId: "HP-STORED" }, { canonicalId: draftPool }],
    hitLocations: [
      { hpPoolCanonicalId: "HP-STORED" },
      { hpPoolCanonicalId: draftPool },
    ],
    attacks: [{ canonicalId: "ATK-STORED" }, { canonicalId: draftAttack }],
    abilities: [{ canonicalId: "ABL-STORED" }, { canonicalId: draftAbility }],
  }, false);

  assert.equal(assigned.coreCanonicalId, "CREATURE-STORED");
  assert.equal(assigned.hpPoolCanonicalIds[0], "HP-STORED");
  assert.equal(assigned.hitLocationPoolCanonicalIds[0], "HP-STORED");
  assert.match(assigned.hpPoolCanonicalIds[1]!, /^HP-[0-9A-F-]{36}$/);
  assert.equal(assigned.hitLocationPoolCanonicalIds[1], assigned.hpPoolCanonicalIds[1]);
  assert.deepEqual(assigned.attackCanonicalIds.slice(0, 1), ["ATK-STORED"]);
  assert.match(assigned.attackCanonicalIds[1]!, /^ATK-[0-9A-F-]{36}$/);
  assert.deepEqual(assigned.abilityCanonicalIds.slice(0, 1), ["ABL-STORED"]);
  assert.match(assigned.abilityCanonicalIds[1]!, /^ABL-[0-9A-F-]{36}$/);
});

test("save boundaries reject user-authored replacements but accept stored and draft identities", () => {
  assert.doesNotThrow(() => assertCreatureCanonicalIdsSystemOwned(
    [{ canonicalId: "HP-STORED" }, { canonicalId: createCreatureDraftCanonicalId("HP") }],
    [{ canonicalId: "HP-STORED" }],
    "HP Pool",
  ));
  assert.throws(
    () => assertCreatureCanonicalIdsSystemOwned(
      [{ canonicalId: "HP-USER-REPLACEMENT" }],
      [{ canonicalId: "HP-STORED" }],
      "HP Pool",
    ),
    /generated by the system and cannot be changed/,
  );
});
