export type CreatureCanonicalIdKind = "CREATURE" | "HP" | "ATK" | "ABL";

const DRAFT_PREFIX = "DRAFT-";

export function createCreatureCanonicalIdentity(cryptoApi: Crypto | undefined = globalThis.crypto): string {
  if (typeof cryptoApi?.randomUUID === "function") return cryptoApi.randomUUID();
  if (typeof cryptoApi?.getRandomValues !== "function") {
    throw new Error("This browser cannot create a temporary Creature ID. Reload in a browser with Web Crypto support.");
  }
  const bytes = new Uint8Array(16);
  cryptoApi.getRandomValues(bytes);
  bytes[6] = (bytes[6]! & 0x0f) | 0x40;
  bytes[8] = (bytes[8]! & 0x3f) | 0x80;
  const hex = [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function randomIdentity(kind: CreatureCanonicalIdKind, draft: boolean): string {
  const prefix = draft ? `${DRAFT_PREFIX}${kind}` : kind;
  return `${prefix}-${createCreatureCanonicalIdentity().toLocaleUpperCase("en-US")}`;
}

export function createCreatureDraftCanonicalId(kind: CreatureCanonicalIdKind): string {
  return randomIdentity(kind, true);
}

export function createCreaturePersistedCanonicalId(kind: CreatureCanonicalIdKind): string {
  return randomIdentity(kind, false);
}

export function isCreatureDraftCanonicalId(value: string): boolean {
  return value.toLocaleUpperCase("en-US").startsWith(DRAFT_PREFIX);
}

export function assertCreatureCanonicalIdsSystemOwned(
  submitted: ReadonlyArray<{ canonicalId: string }>,
  stored: ReadonlyArray<{ canonicalId: string }>,
  label: string,
) {
  const storedIds = new Set(stored.map(({ canonicalId }) => canonicalId.toLocaleUpperCase("en-US")));
  for (const { canonicalId } of submitted) {
    const submittedId = canonicalId.trim().toLocaleUpperCase("en-US");
    if (!isCreatureDraftCanonicalId(submittedId) && !storedIds.has(submittedId)) {
      throw new Error(`${label} IDs are generated by the system and cannot be changed.`);
    }
  }
}

export function resolveSystemAssignedCreatureIds(source: {
  core: { canonicalId: string };
  hpPools: ReadonlyArray<{ canonicalId: string }>;
  hitLocations: ReadonlyArray<{ hpPoolCanonicalId: string | null }>;
  attacks: ReadonlyArray<{ canonicalId: string }>;
  abilities: ReadonlyArray<{ canonicalId: string }>;
}, assignCreatureId: boolean) {
  const hpPoolIds = new Map<string, string>();
  const hpPoolCanonicalIds = source.hpPools.map(({ canonicalId }) => {
    const assigned = assignCreatureId || isCreatureDraftCanonicalId(canonicalId)
      ? createCreaturePersistedCanonicalId("HP")
      : canonicalId;
    hpPoolIds.set(canonicalId.toLocaleLowerCase("en-US"), assigned);
    return assigned;
  });
  return {
    coreCanonicalId: assignCreatureId
      ? createCreaturePersistedCanonicalId("CREATURE")
      : source.core.canonicalId,
    hpPoolCanonicalIds,
    hitLocationPoolCanonicalIds: source.hitLocations.map(({ hpPoolCanonicalId }) => (
      hpPoolCanonicalId === null
        ? null
        : hpPoolIds.get(hpPoolCanonicalId.toLocaleLowerCase("en-US")) ?? hpPoolCanonicalId
    )),
    attackCanonicalIds: source.attacks.map(({ canonicalId }) => (
      assignCreatureId || isCreatureDraftCanonicalId(canonicalId)
        ? createCreaturePersistedCanonicalId("ATK")
        : canonicalId
    )),
    abilityCanonicalIds: source.abilities.map(({ canonicalId }) => (
      assignCreatureId || isCreatureDraftCanonicalId(canonicalId)
        ? createCreaturePersistedCanonicalId("ABL")
        : canonicalId
    )),
  };
}
