import { sql } from "drizzle-orm";
import { boolean, check, foreignKey, index, integer, jsonb, pgTable, primaryKey, serial, text, timestamp, unique, type AnyPgColumn } from "drizzle-orm/pg-core";
import { user } from "./auth-schema";
import { world, worldTimeline, worldDatingSystem } from "./world-schema";
import { worldCalendarAnchor } from "./world-calendar-history-schema";
import { worldHistoryVersion } from "./world-timeline-schema";
import { worldGeography } from "./world-atlas-schema";
import type { HistoricalTime } from "@/features/worlds/history";
import type { SourceDating } from "@/features/worlds/chronology";
import type { CalendarSource } from "@/features/worlds/calendar-dates";
import type { LoreFamily, LoreMode } from "@/features/worlds/peoples";

export const worldLoreIdentity = pgTable("world_lore_identity", {
  id: text("id").primaryKey(), worldId: text("world_id").notNull().references(() => world.id, { onDelete: "restrict" }), family: text("family").$type<LoreFamily>().notNull(),
  originTimelineId: text("origin_timeline_id").notNull(), creatorId: text("creator_id").notNull().references(() => user.id, { onDelete: "restrict" }), requestId: text("request_id").notNull(), requestHash: text("request_hash").notNull(), createdAt: timestamp("created_at").notNull().defaultNow(),
}, t => [unique("lore_identity_world_uq").on(t.id, t.worldId), unique("lore_identity_family_uq").on(t.id, t.worldId, t.family), unique("lore_identity_request_uq").on(t.worldId, t.creatorId, t.requestId), foreignKey({ name: "lore_identity_timeline_fk", columns: [t.originTimelineId, t.worldId], foreignColumns: [worldTimeline.id, worldTimeline.worldId] }).onDelete("restrict"), index("lore_identity_world_idx").on(t.worldId, t.family), check("lore_identity_family_valid", sql`${t.family} in ('species','people','origin','relationship')`)]);

export const worldLoreVersion = pgTable("world_lore_version", {
  id: text("id").primaryKey(), worldId: text("world_id").notNull(), entityId: text("entity_id").notNull(), family: text("family").$type<LoreFamily>().notNull(), timelineId: text("timeline_id").notNull(),
  authorId: text("author_id").notNull().references(() => user.id, { onDelete: "restrict" }), createdAt: timestamp("created_at").notNull().defaultNow(), archived: sqlBoolean(),
  time: jsonb("historical_time").$type<HistoricalTime>().notNull(), accuracy: text("accuracy").notNull(), narrative: text("narrative").$type<"recorded" | "planned">().notNull(), visibility: text("visibility").$type<"ordinary" | "protected">().notNull(), privateNotes: text("private_notes").notNull().default(""),
  datingSystemId: text("dating_system_id"), sourceDating: jsonb("source_dating").$type<SourceDating>(), calendarSource: jsonb("calendar_source").$type<CalendarSource>(), startVersionId: text("start_version_id"), endVersionId: text("end_version_id"),
}, t => [unique("lore_version_entity_uq").on(t.id, t.worldId, t.entityId), unique("lore_version_family_uq").on(t.id, t.worldId, t.family), unique("lore_version_world_uq").on(t.id, t.worldId),
  foreignKey({ name: "lore_version_identity_fk", columns: [t.entityId, t.worldId, t.family], foreignColumns: [worldLoreIdentity.id, worldLoreIdentity.worldId, worldLoreIdentity.family] }).onDelete("restrict"),
  foreignKey({ name: "lore_version_timeline_fk", columns: [t.timelineId, t.worldId], foreignColumns: [worldTimeline.id, worldTimeline.worldId] }).onDelete("restrict"),
  foreignKey({ name: "lore_version_dating_fk", columns: [t.datingSystemId, t.worldId], foreignColumns: [worldDatingSystem.id, worldDatingSystem.worldId] }).onDelete("restrict"),
  foreignKey({ name: "lore_version_calendar_start_fk", columns: [t.startVersionId, t.worldId], foreignColumns: [worldCalendarAnchor.versionId, worldCalendarAnchor.worldId] }).onDelete("restrict"),
  foreignKey({ name: "lore_version_calendar_end_fk", columns: [t.endVersionId, t.worldId], foreignColumns: [worldCalendarAnchor.versionId, worldCalendarAnchor.worldId] }).onDelete("restrict"),
  index("lore_version_entity_idx").on(t.worldId, t.entityId, t.createdAt), check("lore_version_context_valid", sql`${t.accuracy} in ('established','disputed','unverified','disproven') and ${t.narrative} in ('recorded','planned') and ${t.visibility} in ('ordinary','protected') and world_lore_time_valid(${t.time})`)]);

// Domain content is kept in distinct typed tables; the shared header contains only historical/provenance metadata.
function sqlBoolean() { return boolean("archived").notNull().default(false); }
const detailKeys = (family: LoreFamily) => ({ versionId: text("version_id").primaryKey(), worldId: text("world_id").notNull(), family: text("family").notNull().default(family), name: text("name").notNull(), description: text("description").notNull().default("") });
const narrative = (column: string) => text(column).notNull().default("");
const detailConstraints = (family: LoreFamily, t: { versionId: AnyPgColumn; worldId: AnyPgColumn; family: AnyPgColumn; name: AnyPgColumn }) => [foreignKey({ name: `lore_${family}_version_fk`, columns: [t.versionId, t.worldId, t.family], foreignColumns: [worldLoreVersion.id, worldLoreVersion.worldId, worldLoreVersion.family] }).onDelete("restrict"), check(`lore_${family}_valid`, sql`${t.family}=${sql.raw("'"+family+"'")} and length(trim(${t.name})) between 1 and 160`)];
export const worldSpeciesVersion = pgTable("world_species_version", { ...detailKeys("species"), classification: narrative("classification"), form: narrative("form"), biology: narrative("biology"), propagation: narrative("propagation"), development: narrative("development"), aging: narrative("aging"), adaptations: narrative("adaptations"), habitats: narrative("habitats"), supernatural: narrative("supernatural"), traits: narrative("traits"), variations: narrative("variations"), transformations: narrative("transformations") }, t => detailConstraints("species", t));
export const worldPeopleVersion = pgTable("world_people_version", { ...detailKeys("people"), classification: narrative("classification"), identity: narrative("identity"), heritage: narrative("heritage"), distinctions: narrative("distinctions"), practices: narrative("practices"), development: narrative("development") }, t => detailConstraints("people", t));
export const worldOriginVersion = pgTable("world_origin_version", { ...detailKeys("origin"), provenance: narrative("provenance"), perspective: narrative("perspective"), explanation: narrative("explanation") }, t => detailConstraints("origin", t));
export const worldRelationshipVersion = pgTable("world_relationship_version", { ...detailKeys("relationship"), relationshipType: narrative("relationship_type"), interpretation: narrative("interpretation") }, t => detailConstraints("relationship", t));

export const worldLoreHead = pgTable("world_lore_head", {
  worldId: text("world_id").notNull(), timelineId: text("timeline_id").notNull(), entityId: text("entity_id").notNull(), versionId: text("version_id").notNull(), revision: integer("revision").notNull(), mode: text("mode").$type<LoreMode>().notNull(), sourceTimelineId: text("source_timeline_id"), sourceVersionId: text("source_version_id"), sourceRevision: integer("source_revision"),
}, t => [primaryKey({ columns: [t.timelineId, t.entityId] }), index("lore_head_world_idx").on(t.worldId, t.timelineId), foreignKey({ name: "lore_head_timeline_fk", columns: [t.timelineId, t.worldId], foreignColumns: [worldTimeline.id, worldTimeline.worldId] }).onDelete("restrict"), foreignKey({ name: "lore_head_version_fk", columns: [t.versionId, t.worldId, t.entityId], foreignColumns: [worldLoreVersion.id, worldLoreVersion.worldId, worldLoreVersion.entityId] }).onDelete("restrict"), foreignKey({ name: "lore_head_source_version_fk", columns: [t.sourceVersionId, t.worldId, t.entityId], foreignColumns: [worldLoreVersion.id, worldLoreVersion.worldId, worldLoreVersion.entityId] }).onDelete("restrict"), foreignKey({ name: "lore_head_source_timeline_fk", columns: [t.sourceTimelineId, t.worldId], foreignColumns: [worldTimeline.id, worldTimeline.worldId] }).onDelete("restrict"), check("lore_head_valid", sql`${t.revision}>0 and ${t.mode} in ('authored','inherited','pending','excluded','interpretation') and ((${t.sourceTimelineId} is null and ${t.sourceVersionId} is null and ${t.sourceRevision} is null and ${t.mode}='authored') or (${t.sourceTimelineId} is not null and ${t.sourceVersionId} is not null and ${t.sourceRevision} is not null and ${t.sourceRevision}>0 and ${t.mode}<>'authored'))`)]);
const versionKeys = () => ({ versionId: text("version_id").notNull(), worldId: text("world_id").notNull() });
const versionFk = (name: string, t: { versionId: AnyPgColumn; worldId: AnyPgColumn }) => foreignKey({ name, columns: [t.versionId, t.worldId], foreignColumns: [worldLoreVersion.id, worldLoreVersion.worldId] }).onDelete("restrict");
export const worldLoreParticipant = pgTable("world_lore_participant", { ...versionKeys(), position: integer("position").notNull(), targetId: text("target_id"), authoredReference: narrative("authored_reference"), role: text("role").notNull(), account: narrative("account") }, t => [primaryKey({ columns: [t.versionId, t.position] }), versionFk("lore_participant_version_fk", t), foreignKey({ name: "lore_participant_target_fk", columns: [t.targetId, t.worldId], foreignColumns: [worldLoreIdentity.id, worldLoreIdentity.worldId] }).onDelete("restrict"), index("lore_participant_target_idx").on(t.worldId, t.targetId), check("lore_participant_valid", sql`${t.position} between 0 and 99 and length(trim(${t.role})) between 1 and 80 and ((${t.targetId} is not null and ${t.authoredReference}='') or (${t.targetId} is null and length(trim(${t.authoredReference})) between 1 and 1000))`)]);
export const worldLoreSection = pgTable("world_lore_section", { ...versionKeys(), id: text("id").notNull(), position: integer("position").notNull(), title: text("title").notNull(), body: narrative("body"), protected: boolean("protected").notNull() }, t => [primaryKey({ columns: [t.versionId, t.id] }), versionFk("lore_section_version_fk", t), check("lore_section_valid", sql`${t.position} between 0 and 39 and length(trim(${t.title})) between 1 and 160`)]);
export const worldLoreHistory = pgTable("world_lore_history", { ...versionKeys(), entityId: text("entity_id").notNull(), historyVersionId: text("history_version_id").notNull() }, t => [primaryKey({ columns: [t.versionId, t.entityId] }), versionFk("lore_history_version_fk", t), foreignKey({ name: "lore_history_source_fk", columns: [t.historyVersionId, t.worldId, t.entityId], foreignColumns: [worldHistoryVersion.id, worldHistoryVersion.worldId, worldHistoryVersion.entityId] }).onDelete("restrict"), index("lore_history_source_idx").on(t.worldId, t.entityId)]);

export const worldLoreChange = pgTable("world_lore_change", { id: serial("id").primaryKey(), worldId: text("world_id").notNull(), timelineId: text("timeline_id").notNull(), entityId: text("entity_id").notNull(), versionId: text("version_id").notNull(), revision: integer("revision").notNull(), actorId: text("actor_id").notNull().references(() => user.id, {onDelete:"restrict"}), action: text("action").notNull(), createdAt: timestamp("created_at").notNull().defaultNow() }, t => [unique("lore_change_revision_uq").on(t.timelineId,t.entityId,t.revision),foreignKey({name:"lore_change_head_fk",columns:[t.timelineId,t.entityId],foreignColumns:[worldLoreHead.timelineId,worldLoreHead.entityId]}).onDelete("restrict"),foreignKey({name:"lore_change_version_fk",columns:[t.versionId,t.worldId,t.entityId],foreignColumns:[worldLoreVersion.id,worldLoreVersion.worldId,worldLoreVersion.entityId]}).onDelete("restrict"),index("lore_change_entity_idx").on(t.worldId,t.entityId,t.id)]);

// Universal event links pin the existing History source. Atlas retains its original geography identity.
export const worldHistoryVersionEntity = pgTable("world_history_version_entity", { versionId:text("version_id").notNull(),worldId:text("world_id").notNull(),entryId:text("entry_id").notNull(),targetId:text("target_id").notNull(),loreId:text("lore_id"),geographyId:text("geography_id"),eventType:text("event_type").notNull(),entityCategory:text("entity_category").notNull() }, t => [primaryKey({columns:[t.versionId,t.targetId]}),foreignKey({name:"history_entity_version_fk",columns:[t.versionId,t.worldId,t.entryId],foreignColumns:[worldHistoryVersion.id,worldHistoryVersion.worldId,worldHistoryVersion.entityId]}).onDelete("restrict"),foreignKey({name:"history_entity_lore_fk",columns:[t.loreId,t.worldId],foreignColumns:[worldLoreIdentity.id,worldLoreIdentity.worldId]}).onDelete("restrict"),foreignKey({name:"history_entity_geography_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("history_entity_target_idx").on(t.worldId,t.targetId),index("history_entity_category_idx").on(t.worldId,t.entityCategory),index("history_entity_type_idx").on(t.worldId,t.eventType),check("history_entity_target_valid",sql`coalesce(length(trim(${t.entityCategory})) between 1 and 160 and length(trim(${t.eventType})) between 1 and 160 and ((${t.loreId}=${t.targetId} and ${t.geographyId} is null) or (${t.geographyId}=${t.targetId} and ${t.loreId} is null)),false)`)]);
