import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, unique } from "drizzle-orm/pg-core";
import { world } from "./world-schema";
import { defaultPresentation, type MapDrawing, type MapPresentation } from "@/features/worlds/cartography";
import type { GenerationProvenance } from "@/features/worlds/generation-spec";
import type { Geometry } from "@/features/worlds/atlas";
const lifecycle = () => ({revision:integer("revision").notNull().default(1),createdAt:timestamp("created_at").notNull().defaultNow(),updatedAt:timestamp("updated_at").notNull().defaultNow(),archivedAt:timestamp("archived_at")});
export const worldGeography = pgTable("world_geography", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),parentId:text("parent_id"),name:text("name").notNull(),description:text("description").notNull().default(""),kind:text("kind").notNull(),...lifecycle(),
},t=>[unique("world_geography_id_world_uq").on(t.id,t.worldId),foreignKey({name:"world_geography_parent_world_fk",columns:[t.parentId,t.worldId],foreignColumns:[t.id,t.worldId]}).onDelete("restrict"),index("world_geography_world_idx").on(t.worldId),check("world_geography_valid",sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND length(${t.description}) <= 12000 AND ${t.kind} IN ('continent','island','location') AND ${t.revision} > 0 AND (${t.parentId} IS NULL OR ${t.parentId} <> ${t.id})`)]);
export const worldAtlasMap = pgTable("world_atlas_map", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),name:text("name").notNull(),description:text("description").notNull().default(""),scope:text("scope").notNull().default("world"),generation:jsonb("generation").$type<GenerationProvenance>(),sourceMapId:text("source_map_id"),presentation:jsonb("presentation").$type<MapPresentation>().notNull().default(defaultPresentation()),width:integer("width").notNull().default(2000),height:integer("height").notNull().default(1200),...lifecycle(),
},t=>[unique("world_atlas_map_id_world_uq").on(t.id,t.worldId),index("world_atlas_map_world_idx").on(t.worldId),foreignKey({name:"world_atlas_map_source_world_fk",columns:[t.sourceMapId,t.worldId],foreignColumns:[t.id,t.worldId]}).onDelete("restrict"),check("world_atlas_generation_valid",sql`(${t.generation} IS NULL AND ${t.sourceMapId} IS NULL) OR (${t.generation} IS NOT NULL AND world_atlas_generation_valid(${t.generation}) IS TRUE AND ${t.generation}->>'requestId'=${t.id} AND (${t.generation}->>'sourceMapId') IS NOT DISTINCT FROM ${t.sourceMapId} AND (${t.sourceMapId} IS NULL OR ${t.sourceMapId}<>${t.id}))`),check("world_atlas_presentation_valid",sql`world_atlas_presentation_valid(${t.presentation})`),check("world_atlas_map_valid",sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND length(${t.description}) <= 12000 AND ${t.scope} IN ('world','continent','regional','local') AND ${t.width}=2000 AND ${t.height}=1200 AND ${t.revision}>0`)]);
export const worldAtlasFeature = pgTable("world_atlas_feature", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),mapId:text("map_id").notNull(),geographyId:text("geography_id").notNull(),geometry:jsonb("geometry").$type<Geometry>().notNull(),archivedAt:timestamp("archived_at"),
},t=>[foreignKey({name:"world_atlas_feature_map_world_fk",columns:[t.mapId,t.worldId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId]}).onDelete("restrict"),foreignKey({name:"world_atlas_feature_geography_world_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_atlas_feature_map_idx").on(t.mapId),check("world_atlas_geometry_shape_valid",sql`jsonb_typeof(${t.geometry})='object' AND coalesce(${t.geometry}->>'version'='1' AND ((${t.geometry}->>'type'='polygon' AND jsonb_typeof(${t.geometry}->'points')='array' AND jsonb_array_length(${t.geometry}->'points') BETWEEN 3 AND 256) OR (${t.geometry}->>'type'='point' AND jsonb_typeof(${t.geometry}->'point')='object')),false)`),check("world_atlas_geometry_coordinates_valid",sql`world_atlas_geometry_valid(${t.geometry})`)]);

export const worldAtlasDrawing = pgTable("world_atlas_drawing", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),mapId:text("map_id").notNull(),geographyId:text("geography_id"),content:jsonb("content").$type<MapDrawing>().notNull(),sortOrder:integer("sort_order").notNull().default(0),archivedAt:timestamp("archived_at"),
},t=>[foreignKey({name:"world_atlas_drawing_map_world_fk",columns:[t.mapId,t.worldId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId]}).onDelete("restrict"),foreignKey({name:"world_atlas_drawing_geography_world_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_atlas_drawing_map_idx").on(t.mapId),check("world_atlas_drawing_sort_valid",sql`${t.sortOrder} BETWEEN 0 AND 511`),check("world_atlas_drawing_content_valid",sql`world_atlas_drawing_valid(${t.content}) AND ${t.content}->>'id'=${t.id} AND (${t.content}->>'geographyId') IS NOT DISTINCT FROM ${t.geographyId} AND ${t.content}->>'archived'=(${t.archivedAt} IS NOT NULL)::text`)]);
