import { sql } from "drizzle-orm";
import { bigint, boolean, check, foreignKey, index, integer, jsonb, pgTable, primaryKey, text, timestamp, unique, uniqueIndex, type AnyPgColumn } from "drizzle-orm/pg-core";
import { user } from "./auth-schema";
import { itemTagCatalog } from "./item-schema";
import type { HistoricalTime } from "@/features/worlds/history";
import type { SourceDating } from "@/features/worlds/chronology";

const lifecycle = () => ({ revision: integer("revision").notNull().default(1), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow(), archivedAt: timestamp("archived_at") });
export const world = pgTable("world", {
  id: text("id").primaryKey(), ownerId: text("owner_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  name: text("name").notNull(), description: text("description").notNull().default(""), introduction: text("introduction").notNull().default(""), historicalOverview: text("historical_overview").notNull().default(""), tone: text("tone").notNull().default("primary"), ...lifecycle(),
}, (t) => [index("world_owner_idx").on(t.ownerId, t.archivedAt, t.updatedAt), check("world_identity_valid", sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND ${t.revision} > 0 AND ${t.tone} IN ('primary','secondary','info','muted')`)]);
export const worldTimeline = pgTable("world_timeline", {
  id:text("id").primaryKey(), worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),
  primary:boolean("is_primary").notNull().default(false), parentId:text("parent_id").references(():AnyPgColumn=>worldTimeline.id,{onDelete:"restrict"}),
  divergenceYear:bigint("divergence_year",{mode:"number"}), name:text("name").notNull(),description:text("description").notNull().default(""),explanation:text("explanation").notNull().default(""),...lifecycle(),
},t=>[unique("world_timeline_id_world_uq").on(t.id,t.worldId),uniqueIndex("world_timeline_primary_uq").on(t.worldId).where(sql`${t.primary}`),index("world_timeline_world_idx").on(t.worldId,t.parentId),
  foreignKey({name:"world_timeline_parent_world_fk",columns:[t.parentId,t.worldId],foreignColumns:[t.id,t.worldId]}).onDelete("restrict"),
  check("world_timeline_valid",sql`length(trim(${t.name})) between 1 and 160 and ${t.revision}>0 and ((${t.primary} and ${t.parentId} is null and ${t.divergenceYear} is null and ${t.archivedAt} is null) or (not ${t.primary} and ${t.parentId} is not null and ${t.parentId}<>${t.id} and ${t.divergenceYear} is not null and abs(${t.divergenceYear})<=1000000000000))`)]);
export const worldDatingSystem = pgTable("world_dating_system", {
  id: text("id").primaryKey(), worldId: text("world_id").notNull().references(() => world.id, {onDelete:"restrict"}),
  name:text("name").notNull(),description:text("description").notNull().default(""),origin:text("origin").notNull(),
  epochYear:bigint("epoch_year",{mode:"number"}).notNull(),numbering:text("numbering").notNull(),
  beforeLabel:text("before_label").notNull(),afterLabel:text("after_label").notNull(),notes:text("notes").notNull().default(""),
  referencedAt:timestamp("referenced_at"),...lifecycle(),
}, (t) => [unique("world_dating_id_world_uq").on(t.id,t.worldId),index("world_dating_world_idx").on(t.worldId),
  check("world_dating_valid",sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND length(trim(${t.origin})) BETWEEN 1 AND 1000 AND length(trim(${t.beforeLabel})) BETWEEN 1 AND 80 AND length(trim(${t.afterLabel})) BETWEEN 1 AND 80 AND abs(${t.epochYear}) <= 1000000000000 AND ${t.numbering} IN ('year-zero','no-year-zero') AND ${t.revision} > 0`)]);
export const worldChronologyPreference = pgTable("world_chronology_preference", {
  worldId:text("world_id").primaryKey().references(()=>world.id,{onDelete:"restrict"}),defaultDatingSystemId:text("default_dating_system_id"),
}, (t)=>[foreignKey({name:"world_default_dating_world_fk",columns:[t.defaultDatingSystemId,t.worldId],foreignColumns:[worldDatingSystem.id,worldDatingSystem.worldId]}).onDelete("restrict")]);
const datingSource = () => ({datingSystemId:text("dating_system_id"),sourceDating:jsonb("source_dating").$type<SourceDating>()});
export const worldEra = pgTable("world_historical_era", {
  timelineId:text("timeline_id").notNull().references(()=>worldTimeline.id,{onDelete:"restrict"}),
  id: text("id").primaryKey(), worldId: text("world_id").notNull().references(() => world.id, { onDelete: "restrict" }), name: text("name").notNull(), description: text("description").notNull().default(""), startYear: bigint("start_year", { mode: "number" }), endYear: bigint("end_year", { mode: "number" }), tone: text("tone").notNull().default("primary"), ...datingSource(), ...lifecycle(),
}, (t) => [foreignKey({name:"world_era_timeline_world_fk",columns:[t.timelineId,t.worldId],foreignColumns:[worldTimeline.id,worldTimeline.worldId]}).onDelete("restrict"),index("world_era_timeline_idx").on(t.timelineId,t.startYear),foreignKey({name:"world_era_dating_world_fk",columns:[t.datingSystemId,t.worldId],foreignColumns:[worldDatingSystem.id,worldDatingSystem.worldId]}).onDelete("restrict"), check("world_era_dating_source_valid",sql`(${t.datingSystemId} IS NULL AND ${t.sourceDating} IS NULL) OR (${t.datingSystemId} IS NOT NULL AND ${t.sourceDating} IS NOT NULL AND jsonb_typeof(${t.sourceDating}) = 'object' AND coalesce(${t.sourceDating}->>'version' = '1' AND ${t.sourceDating}->>'systemId' = ${t.datingSystemId}, false))`), unique("world_era_id_world_uq").on(t.id, t.worldId), index("world_era_world_idx").on(t.worldId), check("world_era_valid", sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND ${t.revision} > 0 AND ${t.tone} IN ('primary','secondary','info','muted') AND (${t.startYear} IS NULL OR abs(${t.startYear}) <= 1000000000000) AND (${t.endYear} IS NULL OR abs(${t.endYear}) <= 1000000000000) AND (${t.startYear} IS NULL OR ${t.endYear} IS NULL OR ${t.startYear} <= ${t.endYear})`)]);
export const worldEntry = pgTable("world_historical_entry", {
  timelineId:text("timeline_id").notNull().references(()=>worldTimeline.id,{onDelete:"restrict"}),
  id: text("id").primaryKey(), worldId: text("world_id").notNull().references(() => world.id, { onDelete: "restrict" }), title: text("title").notNull(), account: text("account").notNull(), notes: text("notes").notNull().default(""), time: jsonb("historical_time").$type<HistoricalTime>().notNull(), accuracy: text("accuracy").notNull().default("established"), narrative: text("narrative").notNull().default("recorded"), ...datingSource(), ...lifecycle(),
}, (t) => [foreignKey({name:"world_entry_timeline_world_fk",columns:[t.timelineId,t.worldId],foreignColumns:[worldTimeline.id,worldTimeline.worldId]}).onDelete("restrict"),index("world_entry_timeline_idx").on(t.timelineId,t.updatedAt),foreignKey({name:"world_entry_dating_world_fk",columns:[t.datingSystemId,t.worldId],foreignColumns:[worldDatingSystem.id,worldDatingSystem.worldId]}).onDelete("restrict"), check("world_entry_dating_source_valid",sql`(${t.datingSystemId} IS NULL AND ${t.sourceDating} IS NULL) OR (${t.datingSystemId} IS NOT NULL AND ${t.sourceDating} IS NOT NULL AND jsonb_typeof(${t.sourceDating}) = 'object' AND coalesce(${t.sourceDating}->>'version' = '1' AND ${t.sourceDating}->>'systemId' = ${t.datingSystemId}, false))`), unique("world_entry_id_world_uq").on(t.id, t.worldId), index("world_entry_world_idx").on(t.worldId), check("world_entry_valid", sql`length(trim(${t.title})) BETWEEN 1 AND 160 AND length(trim(${t.account})) > 0 AND ${t.revision} > 0 AND ${t.accuracy} IN ('established','disputed','unverified','disproven') AND ${t.narrative} IN ('recorded','planned')`), check("world_entry_time_valid", sql`coalesce(jsonb_typeof(${t.time}) = 'object' AND ${t.time}->>'version' = '1' AND ${t.time}->>'scale' = 'world-year' AND CASE ${t.time}->>'kind' WHEN 'undated' THEN NOT (${t.time} ?| array['year','startYear','endYear']) WHEN 'known' THEN jsonb_typeof(${t.time}->'year') = 'number' AND (${t.time}->>'year')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'year')::numeric) = (${t.time}->>'year')::numeric AND NOT (${t.time} ?| array['startYear','endYear']) WHEN 'approximate' THEN jsonb_typeof(${t.time}->'year') = 'number' AND (${t.time}->>'year')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'year')::numeric) = (${t.time}->>'year')::numeric AND NOT (${t.time} ?| array['startYear','endYear']) WHEN 'window' THEN jsonb_typeof(${t.time}->'startYear') = 'number' AND jsonb_typeof(${t.time}->'endYear') = 'number' AND (${t.time}->>'startYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND (${t.time}->>'endYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'startYear')::numeric) = (${t.time}->>'startYear')::numeric AND trunc((${t.time}->>'endYear')::numeric) = (${t.time}->>'endYear')::numeric AND (${t.time}->>'startYear')::numeric <= (${t.time}->>'endYear')::numeric AND NOT (${t.time} ? 'year') WHEN 'duration' THEN jsonb_typeof(${t.time}->'startYear') = 'number' AND jsonb_typeof(${t.time}->'endYear') = 'number' AND (${t.time}->>'startYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND (${t.time}->>'endYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'startYear')::numeric) = (${t.time}->>'startYear')::numeric AND trunc((${t.time}->>'endYear')::numeric) = (${t.time}->>'endYear')::numeric AND (${t.time}->>'startYear')::numeric <= (${t.time}->>'endYear')::numeric AND NOT (${t.time} ? 'year') ELSE false END, false)`)]);
export const worldEntryEra = pgTable("world_entry_era", { worldId: text("world_id").notNull(), entryId: text("entry_id").notNull(), eraId: text("era_id").notNull() }, (t) => [primaryKey({ columns: [t.entryId, t.eraId] }), foreignKey({ name: "world_entry_era_entry_world_fk", columns: [t.entryId, t.worldId], foreignColumns: [worldEntry.id, worldEntry.worldId] }).onDelete("restrict"), foreignKey({ name: "world_entry_era_era_world_fk", columns: [t.eraId, t.worldId], foreignColumns: [worldEra.id, worldEra.worldId] }).onDelete("restrict"), index("world_entry_era_world_idx").on(t.worldId)]);
export const worldTag = pgTable("world_classification_tag", { worldId: text("world_id").notNull().references(() => world.id, { onDelete: "restrict" }), tagId: integer("tag_id").notNull().references(() => itemTagCatalog.id, { onDelete: "restrict" }) }, (t) => [primaryKey({ columns: [t.worldId, t.tagId] })]);
