import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, unique } from "drizzle-orm/pg-core";
import { world, worldEntry } from "./world-schema";
import { worldCalendarVersion } from "./world-calendar-schema";
import type { CalendarDate } from "@/features/worlds/calendar";
import type { CalendarSource, CalendarEndpoint } from "@/features/worlds/calendar-dates";
import type { CalendarPeriod } from "@/features/worlds/calendar-evolution";
import type { HistoricalTime } from "@/features/worlds/history";
const lifecycle=()=>({revision:integer("revision").notNull().default(1),archivedAt:timestamp("archived_at"),createdAt:timestamp("created_at").notNull().defaultNow()});
export const worldDayReference=pgTable("world_day_reference",{worldId:text("world_id").primaryKey().references(()=>world.id,{onDelete:"restrict"}),label:text("label").notNull(),description:text("description").notNull()},t=>[check("world_day_reference_valid",sql`length(trim(${t.label})) between 1 and 160 and length(trim(${t.description})) between 1 and 4000`)]);
export const worldCalendarAnchor=pgTable("world_calendar_anchor",{versionId:text("version_id").primaryKey(),worldId:text("world_id").notNull().references(()=>worldDayReference.worldId,{onDelete:"restrict"}),date:jsonb("calendar_date").$type<CalendarDate>().notNull(),elapsedDay:text("elapsed_day").notNull()},t=>[unique("world_calendar_anchor_version_world_uq").on(t.versionId,t.worldId),foreignKey({name:"calendar_anchor_version_world_fk",columns:[t.versionId,t.worldId],foreignColumns:[worldCalendarVersion.id,worldCalendarVersion.worldId]}).onDelete("restrict"),check("calendar_anchor_valid",sql`${t.elapsedDay} ~ '^(0|-?[1-9][0-9]{0,19})$' and coalesce(jsonb_typeof(${t.date})='object' and ${t.date} ?& array['year','month','day'],false)`)]);
export const worldCalendarHistory=pgTable("world_calendar_history",{versionId:text("version_id").primaryKey(),worldId:text("world_id").notNull(),period:jsonb("period").$type<CalendarPeriod>().notNull(),revision:integer("revision").notNull().default(1)},t=>[foreignKey({name:"calendar_history_version_world_fk",columns:[t.versionId,t.worldId],foreignColumns:[worldCalendarVersion.id,worldCalendarVersion.worldId]}).onDelete("restrict"),check("calendar_history_valid",sql`${t.revision}>0 and coalesce(jsonb_typeof(${t.period})='object' and ${t.period}->'time'->>'version'='1' and ${t.period}->'time'->>'scale'='world-year',false)`)]);
export const worldCalendarAdoption=pgTable("world_calendar_adoption",{id:text("id").primaryKey(),worldId:text("world_id").notNull(),versionId:text("version_id").notNull(),label:text("label").notNull(),period:jsonb("period").$type<CalendarPeriod>().notNull(),...lifecycle()},t=>[foreignKey({name:"calendar_adoption_version_world_fk",columns:[t.versionId,t.worldId],foreignColumns:[worldCalendarVersion.id,worldCalendarVersion.worldId]}).onDelete("restrict"),index("calendar_adoption_world_idx").on(t.worldId),check("calendar_adoption_valid",sql`${t.revision}>0 and length(trim(${t.label})) between 1 and 160 and coalesce(${t.period}->'time'->>'scale'='world-year' and ${t.period}->'time'->>'version'='1',false)`)]);
export const worldCalendarReform=pgTable("world_calendar_reform",{id:text("id").primaryKey(),worldId:text("world_id").notNull(),name:text("name").notNull(),predecessorId:text("predecessor_id").notNull(),successorId:text("successor_id").notNull(),time:jsonb("effective_time").$type<HistoricalTime>().notNull(),reason:text("reason").notNull(),details:text("details").notNull(),entryId:text("entry_id"),cutover:jsonb("cutover").$type<{before:CalendarEndpoint;after:CalendarEndpoint}>(),...lifecycle()},t=>[
  foreignKey({name:"calendar_reform_predecessor_world_fk",columns:[t.predecessorId,t.worldId],foreignColumns:[worldCalendarVersion.id,worldCalendarVersion.worldId]}).onDelete("restrict"),foreignKey({name:"calendar_reform_successor_world_fk",columns:[t.successorId,t.worldId],foreignColumns:[worldCalendarVersion.id,worldCalendarVersion.worldId]}).onDelete("restrict"),foreignKey({name:"calendar_reform_entry_world_fk",columns:[t.entryId,t.worldId],foreignColumns:[worldEntry.id,worldEntry.worldId]}).onDelete("restrict"),index("calendar_reform_world_idx").on(t.worldId),check("calendar_reform_valid",sql`${t.revision}>0 and ${t.predecessorId}<>${t.successorId} and length(trim(${t.name})) between 1 and 160 and length(trim(${t.reason})) between 1 and 4000 and coalesce(${t.time}->>'version'='1' and ${t.time}->>'scale'='world-year',false) and (${t.cutover} is null or coalesce(${t.cutover}->'before'->>'versionId'=${t.predecessorId} and ${t.cutover}->'after'->>'versionId'=${t.successorId} and (${t.cutover}->'after'->>'elapsedDay')::numeric=(${t.cutover}->'before'->>'elapsedDay')::numeric+1,false))`)
]);
export const worldCalendarEntryDate=pgTable("world_calendar_entry_date",{entryId:text("entry_id").primaryKey(),worldId:text("world_id").notNull(),startVersionId:text("start_version_id").notNull(),endVersionId:text("end_version_id"),source:jsonb("source").$type<CalendarSource>().notNull()},t=>[
  foreignKey({name:"calendar_entry_date_entry_world_fk",columns:[t.entryId,t.worldId],foreignColumns:[worldEntry.id,worldEntry.worldId]}).onDelete("restrict"),foreignKey({name:"calendar_entry_date_start_anchor_world_fk",columns:[t.startVersionId,t.worldId],foreignColumns:[worldCalendarAnchor.versionId,worldCalendarAnchor.worldId]}).onDelete("restrict"),foreignKey({name:"calendar_entry_date_end_anchor_world_fk",columns:[t.endVersionId,t.worldId],foreignColumns:[worldCalendarAnchor.versionId,worldCalendarAnchor.worldId]}).onDelete("restrict"),check("calendar_entry_date_valid",sql`coalesce(${t.source}->>'version'='1' and ${t.source}->'start'->>'versionId'=${t.startVersionId} and ${t.source}->'start'->>'elapsedDay' ~ '^(0|-?[1-9][0-9]{0,19})$' and case ${t.source}->>'kind' when 'known' then ${t.endVersionId} is null and not (${t.source} ? 'end') when 'approximate' then ${t.endVersionId} is null and not (${t.source} ? 'end') when 'window' then ${t.endVersionId}=${t.source}->'end'->>'versionId' and (${t.source}->'end'->>'elapsedDay')::numeric>=(${t.source}->'start'->>'elapsedDay')::numeric when 'duration' then ${t.endVersionId}=${t.source}->'end'->>'versionId' and (${t.source}->'end'->>'elapsedDay')::numeric>=(${t.source}->'start'->>'elapsedDay')::numeric else false end,false)`)
]);
