import { sql } from "drizzle-orm";
import { bigint, check, foreignKey, index, integer, jsonb, pgTable, primaryKey, text, timestamp, unique } from "drizzle-orm/pg-core";
import { user } from "./auth-schema";
import { itemTagCatalog } from "./item-schema";
import type { HistoricalTime } from "@/features/worlds/history";

const lifecycle = () => ({ revision: integer("revision").notNull().default(1), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow(), archivedAt: timestamp("archived_at") });
export const world = pgTable("world", {
  id: text("id").primaryKey(), ownerId: text("owner_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  name: text("name").notNull(), description: text("description").notNull().default(""), introduction: text("introduction").notNull().default(""), historicalOverview: text("historical_overview").notNull().default(""), tone: text("tone").notNull().default("primary"), ...lifecycle(),
}, (t) => [index("world_owner_idx").on(t.ownerId, t.archivedAt, t.updatedAt), check("world_identity_valid", sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND ${t.revision} > 0 AND ${t.tone} IN ('primary','secondary','info','muted')`)]);
export const worldEra = pgTable("world_historical_era", {
  id: text("id").primaryKey(), worldId: text("world_id").notNull().references(() => world.id, { onDelete: "restrict" }), name: text("name").notNull(), description: text("description").notNull().default(""), startYear: bigint("start_year", { mode: "number" }), endYear: bigint("end_year", { mode: "number" }), tone: text("tone").notNull().default("primary"), ...lifecycle(),
}, (t) => [unique("world_era_id_world_uq").on(t.id, t.worldId), index("world_era_world_idx").on(t.worldId), check("world_era_valid", sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND ${t.revision} > 0 AND ${t.tone} IN ('primary','secondary','info','muted') AND (${t.startYear} IS NULL OR abs(${t.startYear}) <= 1000000000000) AND (${t.endYear} IS NULL OR abs(${t.endYear}) <= 1000000000000) AND (${t.startYear} IS NULL OR ${t.endYear} IS NULL OR ${t.startYear} <= ${t.endYear})`)]);
export const worldEntry = pgTable("world_historical_entry", {
  id: text("id").primaryKey(), worldId: text("world_id").notNull().references(() => world.id, { onDelete: "restrict" }), title: text("title").notNull(), account: text("account").notNull(), notes: text("notes").notNull().default(""), time: jsonb("historical_time").$type<HistoricalTime>().notNull(), accuracy: text("accuracy").notNull().default("established"), narrative: text("narrative").notNull().default("recorded"), ...lifecycle(),
}, (t) => [unique("world_entry_id_world_uq").on(t.id, t.worldId), index("world_entry_world_idx").on(t.worldId), check("world_entry_valid", sql`length(trim(${t.title})) BETWEEN 1 AND 160 AND length(trim(${t.account})) > 0 AND ${t.revision} > 0 AND ${t.accuracy} IN ('established','disputed','unverified','disproven') AND ${t.narrative} IN ('recorded','planned')`), check("world_entry_time_valid", sql`coalesce(jsonb_typeof(${t.time}) = 'object' AND ${t.time}->>'version' = '1' AND ${t.time}->>'scale' = 'world-year' AND CASE ${t.time}->>'kind' WHEN 'undated' THEN NOT (${t.time} ?| array['year','startYear','endYear']) WHEN 'known' THEN jsonb_typeof(${t.time}->'year') = 'number' AND (${t.time}->>'year')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'year')::numeric) = (${t.time}->>'year')::numeric AND NOT (${t.time} ?| array['startYear','endYear']) WHEN 'approximate' THEN jsonb_typeof(${t.time}->'year') = 'number' AND (${t.time}->>'year')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'year')::numeric) = (${t.time}->>'year')::numeric AND NOT (${t.time} ?| array['startYear','endYear']) WHEN 'window' THEN jsonb_typeof(${t.time}->'startYear') = 'number' AND jsonb_typeof(${t.time}->'endYear') = 'number' AND (${t.time}->>'startYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND (${t.time}->>'endYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'startYear')::numeric) = (${t.time}->>'startYear')::numeric AND trunc((${t.time}->>'endYear')::numeric) = (${t.time}->>'endYear')::numeric AND (${t.time}->>'startYear')::numeric <= (${t.time}->>'endYear')::numeric AND NOT (${t.time} ? 'year') WHEN 'duration' THEN jsonb_typeof(${t.time}->'startYear') = 'number' AND jsonb_typeof(${t.time}->'endYear') = 'number' AND (${t.time}->>'startYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND (${t.time}->>'endYear')::numeric BETWEEN -1000000000000 AND 1000000000000 AND trunc((${t.time}->>'startYear')::numeric) = (${t.time}->>'startYear')::numeric AND trunc((${t.time}->>'endYear')::numeric) = (${t.time}->>'endYear')::numeric AND (${t.time}->>'startYear')::numeric <= (${t.time}->>'endYear')::numeric AND NOT (${t.time} ? 'year') ELSE false END, false)`)]);
export const worldEntryEra = pgTable("world_entry_era", { worldId: text("world_id").notNull(), entryId: text("entry_id").notNull(), eraId: text("era_id").notNull() }, (t) => [primaryKey({ columns: [t.entryId, t.eraId] }), foreignKey({ name: "world_entry_era_entry_world_fk", columns: [t.entryId, t.worldId], foreignColumns: [worldEntry.id, worldEntry.worldId] }).onDelete("restrict"), foreignKey({ name: "world_entry_era_era_world_fk", columns: [t.eraId, t.worldId], foreignColumns: [worldEra.id, worldEra.worldId] }).onDelete("restrict"), index("world_entry_era_world_idx").on(t.worldId)]);
export const worldTag = pgTable("world_classification_tag", { worldId: text("world_id").notNull().references(() => world.id, { onDelete: "restrict" }), tagId: integer("tag_id").notNull().references(() => itemTagCatalog.id, { onDelete: "restrict" }) }, (t) => [primaryKey({ columns: [t.worldId, t.tagId] })]);
