import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, unique } from "drizzle-orm/pg-core";
import { world } from "./world-schema";
import { defaultPresentation, type MapDrawing, type MapPresentation } from "@/features/worlds/cartography";
import type { GenerationProvenance } from "@/features/worlds/generation-spec";
import { defaultSettlementState, type SettlementShape, type SettlementState } from "@/features/worlds/settlement";
import { defaultInteriorState, type InteriorState, type InteriorShape } from "@/features/worlds/interior";
import type { Geometry } from "@/features/worlds/atlas";
const lifecycle = () => ({revision:integer("revision").notNull().default(1),createdAt:timestamp("created_at").notNull().defaultNow(),updatedAt:timestamp("updated_at").notNull().defaultNow(),archivedAt:timestamp("archived_at")});
export const worldGeography = pgTable("world_geography", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),parentId:text("parent_id"),name:text("name").notNull(),description:text("description").notNull().default(""),kind:text("kind").notNull(),context:text("context").notNull().default("place"),...lifecycle(),
},t=>[unique("world_geography_id_world_uq").on(t.id,t.worldId),foreignKey({name:"world_geography_parent_world_fk",columns:[t.parentId,t.worldId],foreignColumns:[t.id,t.worldId]}).onDelete("restrict"),index("world_geography_world_idx").on(t.worldId),check("world_geography_context_valid",sql`${t.context} IN ('place','region','local area','settlement','building site','interior') AND (${t.kind}='location' OR ${t.context}='place')`),check("world_geography_valid",sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND length(${t.description}) <= 12000 AND ${t.kind} IN ('continent','island','location') AND ${t.revision} > 0 AND (${t.parentId} IS NULL OR ${t.parentId} <> ${t.id})`)]);
export const worldAtlasMap = pgTable("world_atlas_map", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),name:text("name").notNull(),description:text("description").notNull().default(""),scope:text("scope").notNull().default("world"),mapKind:text("map_kind").notNull().default("generic"),interiorState:jsonb("interior_state").$type<InteriorState>().notNull().default(defaultInteriorState()),settlementState:jsonb("settlement_state").$type<SettlementState>().notNull().default(defaultSettlementState()),geographyId:text("geography_id"),generation:jsonb("generation").$type<GenerationProvenance>(),sourceMapId:text("source_map_id"),presentation:jsonb("presentation").$type<MapPresentation>().notNull().default(defaultPresentation()),width:integer("width").notNull().default(2000),height:integer("height").notNull().default(1200),...lifecycle(),
},t=>[unique("world_atlas_map_id_world_uq").on(t.id,t.worldId),unique("world_atlas_map_place_world_uq").on(t.id,t.worldId,t.geographyId),check("world_atlas_map_kind_valid",sql`${t.mapKind} IN ('generic','settlement','interior') AND (${t.mapKind}='generic' OR ${t.geographyId} IS NOT NULL)`),check("world_atlas_interior_state_valid",sql`world_atlas_interior_state_valid(${t.interiorState}) IS TRUE`),check("world_atlas_settlement_state_valid",sql`world_atlas_settlement_state_valid(${t.settlementState})`),foreignKey({name:"world_atlas_map_geography_world_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_atlas_map_geography_idx").on(t.geographyId),index("world_atlas_map_world_idx").on(t.worldId),foreignKey({name:"world_atlas_map_source_world_fk",columns:[t.sourceMapId,t.worldId],foreignColumns:[t.id,t.worldId]}).onDelete("restrict"),check("world_atlas_generation_valid",sql`(${t.generation} IS NULL AND ${t.sourceMapId} IS NULL) OR (${t.generation} IS NOT NULL AND world_atlas_generation_valid(${t.generation}) IS TRUE AND ${t.generation}->>'requestId'=${t.id} AND (${t.generation}->>'sourceMapId') IS NOT DISTINCT FROM ${t.sourceMapId} AND (${t.sourceMapId} IS NULL OR ${t.sourceMapId}<>${t.id}))`),check("world_atlas_presentation_valid",sql`world_atlas_presentation_valid(${t.presentation})`),check("world_atlas_map_valid",sql`length(trim(${t.name})) BETWEEN 1 AND 160 AND length(${t.description}) <= 12000 AND ${t.scope} IN ('world','continent','regional','local') AND ${t.width}=2000 AND ${t.height}=1200 AND ${t.revision}>0`)]);
export const worldAtlasFeature = pgTable("world_atlas_feature", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),mapId:text("map_id").notNull(),geographyId:text("geography_id").notNull(),geometry:jsonb("geometry").$type<Geometry>().notNull(),archivedAt:timestamp("archived_at"),
},t=>[foreignKey({name:"world_atlas_feature_map_world_fk",columns:[t.mapId,t.worldId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId]}).onDelete("restrict"),foreignKey({name:"world_atlas_feature_geography_world_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_atlas_feature_map_idx").on(t.mapId),check("world_atlas_geometry_shape_valid",sql`jsonb_typeof(${t.geometry})='object' AND coalesce(${t.geometry}->>'version'='1' AND ((${t.geometry}->>'type'='polygon' AND jsonb_typeof(${t.geometry}->'points')='array' AND jsonb_array_length(${t.geometry}->'points') BETWEEN 3 AND 256) OR (${t.geometry}->>'type'='point' AND jsonb_typeof(${t.geometry}->'point')='object')),false)`),check("world_atlas_geometry_coordinates_valid",sql`world_atlas_geometry_valid(${t.geometry})`)]);

export const worldAtlasDrawing = pgTable("world_atlas_drawing", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),mapId:text("map_id").notNull(),geographyId:text("geography_id"),content:jsonb("content").$type<MapDrawing>().notNull(),sortOrder:integer("sort_order").notNull().default(0),archivedAt:timestamp("archived_at"),
},t=>[foreignKey({name:"world_atlas_drawing_map_world_fk",columns:[t.mapId,t.worldId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId]}).onDelete("restrict"),foreignKey({name:"world_atlas_drawing_geography_world_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_atlas_drawing_map_idx").on(t.mapId),check("world_atlas_drawing_sort_valid",sql`${t.sortOrder} BETWEEN 0 AND 511`),check("world_atlas_drawing_content_valid",sql`world_atlas_drawing_valid(${t.content}) AND ${t.content}->>'id'=${t.id} AND (${t.content}->>'geographyId') IS NOT DISTINCT FROM ${t.geographyId} AND ${t.content}->>'archived'=(${t.archivedAt} IS NOT NULL)::text`)]);

// A preferred destination for a place on a source map. Other maps of that place remain available.
export const worldAtlasConnection = pgTable("world_atlas_connection", {
  id:text("id").primaryKey(),worldId:text("world_id").notNull().references(()=>world.id,{onDelete:"restrict"}),sourceMapId:text("source_map_id").notNull(),geographyId:text("geography_id").notNull(),destinationGeographyId:text("destination_geography_id"),destinationMapId:text("destination_map_id").notNull(),...lifecycle(),
},t=>[foreignKey({name:"world_atlas_connection_arrival_world_fk",columns:[t.destinationGeographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),unique("world_atlas_connection_source_place_uq").on(t.sourceMapId,t.geographyId),foreignKey({name:"world_atlas_connection_source_world_fk",columns:[t.sourceMapId,t.worldId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId]}).onDelete("restrict"),foreignKey({name:"world_atlas_connection_destination_world_fk",columns:[t.destinationMapId,t.worldId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId]}).onDelete("restrict"),foreignKey({name:"world_atlas_connection_geography_world_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_atlas_connection_world_idx").on(t.worldId),index("world_atlas_connection_destination_idx").on(t.destinationMapId),check("world_atlas_connection_valid",sql`${t.sourceMapId}<>${t.destinationMapId} AND ${t.revision}>0`)]);

export const worldSettlementEntity=pgTable("world_settlement_entity",{
 geographyId:text("geography_id").primaryKey(),worldId:text("world_id").notNull(),settlementId:text("settlement_id").notNull(),kind:text("kind").notNull(),classification:text("classification").notNull().default(""),revision:integer("revision").notNull().default(1),
},t=>[unique("world_settlement_entity_place_uq").on(t.geographyId,t.worldId,t.settlementId),unique("world_settlement_entity_kind_uq").on(t.geographyId,t.worldId,t.settlementId,t.kind),foreignKey({name:"world_settlement_entity_geography_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),foreignKey({name:"world_settlement_entity_parent_fk",columns:[t.settlementId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_settlement_entity_parent_idx").on(t.settlementId),check("world_settlement_entity_valid",sql`${t.kind} IN ('street','district','building','wall','waterway','space','landmark') AND length(${t.classification})<=160 AND ${t.revision}>0 AND ${t.geographyId}<>${t.settlementId}`)]);
export const worldSettlementMembership=pgTable("world_settlement_membership",{
 geographyId:text("geography_id").notNull(),districtId:text("district_id").notNull(),worldId:text("world_id").notNull(),settlementId:text("settlement_id").notNull(),districtKind:text("district_kind").notNull().default("district"),
},t=>[unique("world_settlement_membership_uq").on(t.geographyId,t.districtId),foreignKey({name:"world_settlement_membership_member_fk",columns:[t.geographyId,t.worldId,t.settlementId],foreignColumns:[worldSettlementEntity.geographyId,worldSettlementEntity.worldId,worldSettlementEntity.settlementId]}).onDelete("restrict"),foreignKey({name:"world_settlement_membership_district_fk",columns:[t.districtId,t.worldId,t.settlementId,t.districtKind],foreignColumns:[worldSettlementEntity.geographyId,worldSettlementEntity.worldId,worldSettlementEntity.settlementId,worldSettlementEntity.kind]}).onDelete("restrict"),check("world_settlement_membership_valid",sql`${t.districtKind}='district' AND ${t.geographyId}<>${t.districtId}`)]);
export const worldAtlasSettlementShape=pgTable("world_atlas_settlement_shape",{
 id:text("id").primaryKey(),worldId:text("world_id").notNull(),mapId:text("map_id").notNull(),settlementId:text("settlement_id").notNull(),geographyId:text("geography_id").notNull(),content:jsonb("content").$type<SettlementShape>().notNull(),sortOrder:integer("sort_order").notNull(),
},t=>[foreignKey({name:"world_atlas_settlement_shape_map_fk",columns:[t.mapId,t.worldId,t.settlementId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId,worldAtlasMap.geographyId]}).onDelete("restrict"),foreignKey({name:"world_atlas_settlement_shape_entity_fk",columns:[t.geographyId,t.worldId,t.settlementId],foreignColumns:[worldSettlementEntity.geographyId,worldSettlementEntity.worldId,worldSettlementEntity.settlementId]}).onDelete("restrict"),index("world_atlas_settlement_shape_map_idx").on(t.mapId),check("world_atlas_settlement_shape_valid",sql`world_atlas_settlement_shape_valid(${t.content}) AND ${t.content}->>'id'=${t.id} AND ${t.content}->>'geographyId'=${t.geographyId} AND ${t.sortOrder} BETWEEN 0 AND 3999`)]);

export const worldInteriorFloor=pgTable("world_interior_floor",{
 geographyId:text("geography_id").primaryKey(),worldId:text("world_id").notNull(),buildingId:text("building_id").notNull(),settlementId:text("settlement_id").notNull(),buildingKind:text("building_kind").notNull().default("building"),classification:text("classification").notNull().default(""),label:text("label").notNull().default(""),order:integer("display_order"),elevation:text("elevation").notNull().default(""),...lifecycle(),
},t=>[unique("world_interior_floor_world_uq").on(t.geographyId,t.worldId),foreignKey({name:"world_interior_floor_geography_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),foreignKey({name:"world_interior_floor_building_fk",columns:[t.buildingId,t.worldId,t.settlementId,t.buildingKind],foreignColumns:[worldSettlementEntity.geographyId,worldSettlementEntity.worldId,worldSettlementEntity.settlementId,worldSettlementEntity.kind]}).onDelete("restrict"),index("world_interior_floor_building_idx").on(t.buildingId),check("world_interior_floor_valid",sql`${t.buildingKind}='building' AND ${t.geographyId}<>${t.buildingId} AND length(${t.classification})<=160 AND length(${t.label})<=80 AND length(${t.elevation})<=80 AND (${t.order} IS NULL OR ${t.order} BETWEEN -100000 AND 100000) AND ${t.revision}>0`)]);
export const worldInteriorEntity=pgTable("world_interior_entity",{
 id:text("id").primaryKey(),worldId:text("world_id").notNull(),floorId:text("floor_id").notNull(),geographyId:text("geography_id"),kind:text("kind").notNull(),name:text("name").notNull().default(""),description:text("description").notNull().default(""),classification:text("classification").notNull().default(""),revision:integer("revision").notNull().default(1),
},t=>[unique("world_interior_entity_floor_uq").on(t.id,t.worldId,t.floorId),foreignKey({name:"world_interior_entity_floor_fk",columns:[t.floorId,t.worldId],foreignColumns:[worldInteriorFloor.geographyId,worldInteriorFloor.worldId]}).onDelete("restrict"),foreignKey({name:"world_interior_entity_geography_fk",columns:[t.geographyId,t.worldId],foreignColumns:[worldGeography.id,worldGeography.worldId]}).onDelete("restrict"),index("world_interior_entity_floor_idx").on(t.floorId),check("world_interior_entity_valid",sql`${t.kind} IN ('room','wall','opening','window','transition','furnishing','landmark') AND length(${t.name})<=160 AND length(${t.description})<=12000 AND length(${t.classification})<=160 AND ${t.revision}>0 AND (CASE WHEN ${t.kind} IN ('room','transition','landmark') THEN ${t.geographyId} IS NOT NULL AND ${t.geographyId}=${t.id} ELSE ${t.geographyId} IS NULL END)`)]);
export const worldAtlasInteriorShape=pgTable("world_atlas_interior_shape",{
 id:text("id").primaryKey(),worldId:text("world_id").notNull(),mapId:text("map_id").notNull(),floorId:text("floor_id").notNull(),entityId:text("entity_id").notNull(),content:jsonb("content").$type<InteriorShape>().notNull(),sortOrder:integer("sort_order").notNull(),
},t=>[foreignKey({name:"world_atlas_interior_shape_map_fk",columns:[t.mapId,t.worldId,t.floorId],foreignColumns:[worldAtlasMap.id,worldAtlasMap.worldId,worldAtlasMap.geographyId]}).onDelete("restrict"),foreignKey({name:"world_atlas_interior_shape_entity_fk",columns:[t.entityId,t.worldId,t.floorId],foreignColumns:[worldInteriorEntity.id,worldInteriorEntity.worldId,worldInteriorEntity.floorId]}).onDelete("restrict"),index("world_atlas_interior_shape_map_idx").on(t.mapId),check("world_atlas_interior_shape_valid",sql`world_atlas_interior_shape_valid(${t.content}) IS TRUE AND ${t.content}->>'id'=${t.id} AND ${t.content}->>'entityId'=${t.entityId} AND ${t.sortOrder} BETWEEN 0 AND 3999`)]);
