import type { EvolutionOwner, EvolutionRequirementMode } from "./evolution-requirements";

export type EvolutionDestinationPreparation = {
  kind: EvolutionOwner; sourceId: number; sourceName: string; sourceToken: string;
  requestKey: string; canonicalId: string | null;
};
export type CreateEvolutionDestinationInput = EvolutionDestinationPreparation & {
  destinationName: string; pathName: string; description: string; notes: string;
};
export type CreatedEvolutionDestination = {
  kind: EvolutionOwner; sourceId: number; sourceName: string; destinationId: number;
  destinationName: string; canonicalId: string | null; pathId: number; pathVersion: number;
};
/** Exact relational references for future consumers. Availability is not individual eligibility. */
export type EvolutionPathReference = {
  kind: EvolutionOwner; pathId: number; pathVersion: number; pathName: string;
  sourceId: number; destinationId: number; destinationName: string;
  requirementMode: EvolutionRequirementMode; sourceArchived: boolean; destinationArchived: boolean; available: boolean;
};

export function destinationCanonicalId(kind: EvolutionOwner, requestKey: string) {
  if (!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(requestKey)) throw new Error("Reload destination creation to obtain a valid request identity.");
  return kind === "creature" ? `CREATURE-${requestKey.toUpperCase()}` : null;
}

export function normalizeDestinationCreation(input: CreateEvolutionDestinationInput) {
  if (!input || !["race", "creature"].includes(input.kind) || !Number.isSafeInteger(input.sourceId) || input.sourceId <= 0) throw new Error("Choose an exact saved Race or Creature source.");
  const canonicalId = destinationCanonicalId(input.kind, input.requestKey);
  if (input.canonicalId !== canonicalId) throw new Error("The destination canonical ID is generated by the system and cannot be changed.");
  if (!/^[a-f0-9]{64}$/.test(input.sourceToken)) throw new Error("Reload the source before creating its Evolution destination.");
  const required = (value: unknown, label: string, max: number) => {
    if (typeof value !== "string" || !value.trim() || value.trim().length > max) throw new Error(`${label} is required and must be ${max} characters or fewer.`);
    return value.trim();
  };
  const optional = (value: unknown) => {
    if (typeof value !== "string" || value.length > 10000) throw new Error("Path description and notes must be 10000 characters or fewer.");
    return value.trim();
  };
  return { ...input, destinationName: required(input.destinationName, "Destination name", 200), pathName: required(input.pathName, "Evolution path name", 200),
    description: optional(input.description), notes: optional(input.notes), canonicalId };
}
