import assert from "node:assert/strict";
import path from "node:path";
import type { Page, Request } from "playwright-core";
import { db, pool } from "@/db";
import { readCreatureNpcTemplateInTransaction, buildCreatureNpcSnapshot, createCreatureNpcInTransaction } from "@/features/creatures/creature-npc-constructor-service";
import { saveCreatureFormsInTransaction } from "@/features/creatures/creature-form-service";
import { emptyCreatureFormMechanics } from "@/features/creatures/creature-forms";
import { creatureFormFixture } from "./creature-form-fixture";
import { setDetailsOpen } from "./interaction-rule-browser-checks";

async function until(check: () => Promise<boolean>) {
  const end = Date.now() + 30_000;
  while (Date.now() < end) { if (await check()) return; await new Promise(resolve => setTimeout(resolve, 100)); }
  throw new Error("Timed out waiting for Form save");
}
async function runtimeRows() {
  const tables = (await pool.query("select tablename from pg_tables where schemaname='public' and (tablename like 'campaign_%' or tablename like 'character_%' or tablename like 'inventory_%') order by tablename")).rows as Array<{ tablename: string }>;
  return Object.fromEntries(await Promise.all(tables.map(async ({ tablename }) => [tablename, (await pool.query(`select to_jsonb(t) body from "${tablename}" t order by to_jsonb(t)::text`)).rows])));
}

export async function checkCreatureForms(page: Page, input: { base: string; artifacts: string; campaignId: number; userId: string }) {
  const { base, artifacts, campaignId, userId } = input;
  await page.setViewportSize({ width: 1365, height: 1000 });
  await page.goto(`${base}/heavens/creatures`);
  await page.getByRole("button", { name: "New Creature", exact: true }).click();
  await page.getByLabel("Canonical Name", { exact: true }).fill("Form Browser Creature");
  await page.getByRole("button", { name: "Stats & Movement", exact: true }).click();
  for (const field of await page.locator(".creature-attribute-row input[type=number]").all()) await field.fill("30");
  await page.getByRole("button", { name: "Forms", exact: true }).click();
  const editor = page.getByRole("region", { name: "Creature Forms editor" }).or(page.locator('[aria-label="Creature Forms editor"]'));
  await editor.getByRole("button", { name: "Add Form", exact: true }).click();
  await editor.getByLabel("Form Name", { exact: true }).fill("Authored Form");
  await editor.getByLabel("Form Description", { exact: true }).fill("Browser-authored alternate state");
  await setDetailsOpen(editor, "Size and exceptional steps", true);
  await editor.getByLabel("Form Size", { exact: true }).selectOption("Small");
  await editor.getByLabel("Form HP Multiplier Steps", { exact: true }).fill("2");
  await setDetailsOpen(editor, "Attributes", true);
  await editor.getByLabel("attributes source", { exact: true }).selectOption("override");
  await editor.locator(".creature-attribute-row input[type=number]").first().fill("45");
  await setDetailsOpen(editor, "Movement", true);
  await editor.getByLabel("movement source", { exact: true }).selectOption("override");
  await editor.getByRole("button", { name: "Add Movement", exact: true }).click();
  await editor.getByPlaceholder("Mode", { exact: true }).fill("Swim");
  await editor.getByPlaceholder("Base Movement", { exact: true }).fill("12");
  await editor.getByPlaceholder("Initiative", { exact: true }).fill("3");
  await editor.getByPlaceholder("Requirements", { exact: true }).fill("Water");
  await setDetailsOpen(editor, "HP pools and hit locations", true);
  await editor.getByLabel("Body source", { exact: true }).selectOption("override");
  await editor.getByRole("button", { name: "Add HP Pool", exact: true }).click();
  await editor.getByPlaceholder("Pool Name", { exact: true }).fill("Form body");
  await editor.getByPlaceholder("HP %", { exact: true }).fill("100");
  await editor.getByRole("button", { name: "Add Location", exact: true }).click();
  await editor.getByLabel("Location Name", { exact: true }).fill("Fins");
  await editor.getByLabel("Natural Armor", { exact: true }).fill("2");
  await editor.getByLabel("Natural Soak", { exact: true }).fill("1");
  await editor.getByLabel("Location Effect", { exact: true }).fill("Cannot swim when disabled");
  await page.getByRole("button", { name: "Save Creature", exact: true }).click();
  await page.getByText("Form Browser Creature was saved.", { exact: true }).waitFor();
  const creatureId = (await pool.query("select id from creatures where canonical_name='Form Browser Creature'")).rows[0].id as number;
  let template = (await db.transaction(tx => readCreatureNpcTemplateInTransaction(tx, creatureId)))!;
  assert.equal(template.forms!.length, 1);
  const authored = template.forms![0];
  assert.equal(authored.mechanics.attributes.rows[0].value, 45);
  assert.equal(authored.mechanics.body.hitLocations[0].naturalArmor, 2);
  assert.equal(authored.mechanics.movement.rows[0].requirements, "Water");
  assert.equal(authored.mechanics.size, "Small");
  await page.screenshot({ path: path.join(artifacts, "forms-authoring-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await editor.evaluate(element => element.scrollWidth > element.clientWidth + 2), false, "390px Form authoring fits");
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 2), false, "390px page fits");
  await page.screenshot({ path: path.join(artifacts, "forms-authoring-phone.png"), fullPage: true });
  await page.reload();
  await page.locator("#creature-search").fill("Form Browser Creature");
  await page.locator(".skill-library__row").filter({ hasText: "Form Browser Creature" }).click();
  await page.getByRole("button", { name: "Forms", exact: true }).click();
  assert.equal(await editor.getByLabel("Form Name", { exact: true }).inputValue(), "Authored Form");
  await setDetailsOpen(editor, "Attributes", true);
  assert.equal(await editor.locator(".creature-attribute-row input[type=number]").first().inputValue(), "45");

  const [skill] = (await pool.query("insert into skill(name,classification,tier,primary_attribute) values('Form Awareness','standard',1,'WIS') returning id")).rows;
  const complex = creatureFormFixture(skill.id as number);
  const extras = Array.from({ length: 16 }, (_, index) => ({ ...creatureFormFixture(), key: `extra-${index}`, name: `Additional Form ${index}`, mechanics: emptyCreatureFormMechanics(), transformation: null }));
  await db.transaction(tx => saveCreatureFormsInTransaction(tx, creatureId, [authored, complex, ...extras], template));
  template = (await db.transaction(tx => readCreatureNpcTemplateInTransaction(tx, creatureId)))!;
  const npcId = await db.transaction(tx => createCreatureNpcInTransaction(tx, { campaignId, controllerUserId: userId, creatureId, name: "Form Browser NPC", roleLabel: "Form fixture", snapshot: buildCreatureNpcSnapshot(template) }));
  await page.setViewportSize({ width: 1365, height: 1000 });
  await page.goto(`${base}/heavens/npcs/${npcId}`);
  const viewer = page.getByRole("region", { name: "Creature Form viewer", exact: true });
  const select = viewer.getByLabel("View Form", { exact: true });
  assert.equal(await select.inputValue(), "");
  assert.equal(await select.locator("option").count(), 19);
  assert.equal(await viewer.locator("[data-creature-form-preview]").count(), 0);
  await pool.query("insert into campaign_character_active_health(character_id,total_damage) values($1,7) on conflict (character_id) do update set total_damage=7", [npcId]);
  await page.reload(); await select.waitFor();
  const storedBefore = (await pool.query("select * from campaign_creature_npc_profile where character_id=$1", [npcId])).rows[0];
  const before = await runtimeRows();
  const mutations: string[] = [];
  const observe = (request: Request) => { if (!["GET", "HEAD"].includes(request.method())) mutations.push(`${request.method()} ${request.url()}`); };
  page.on("request", observe);
  await select.selectOption(String(template.forms![1].id));
  await viewer.getByRole("heading", { name: "Winged Form", exact: true }).waitFor();
  const text = await viewer.innerText();
  for (const expected of ["does not change the Creature NPC's current runtime state", "Effective 15", "Winged torso", "Natural Armor 4", "Grounded if disabled", "Flight: Base 18", "Form Talons", "Attack 67%", "Form Moon Sight", "Resistance", "Rank 3", "Form cold rule", "Claws only", "Cannot write", "Quintessence"]) assert.ok(text.includes(expected), `Preview displays ${expected}`);
  await setDetailsOpen(viewer, "Ability costs, conditions, limits, effects and Magic Construction", true);
  assert.ok((await viewer.innerText()).includes("Sight cost"));
  assert.ok((await viewer.innerText()).includes("At night"));
  assert.equal(await viewer.locator("button").count(), 0, "Preview has no runtime actions");
  assert.equal(await page.getByRole("button", { name: "Save Individual", exact: true }).isDisabled(), true);
  await page.screenshot({ path: path.join(artifacts, "forms-preview-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await viewer.evaluate(element => element.scrollWidth > element.clientWidth + 2), false);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 2), false);
  await page.screenshot({ path: path.join(artifacts, "forms-preview-phone.png"), fullPage: true });
  await select.selectOption(String(template.forms![0].id));
  assert.ok((await viewer.innerText()).includes("Fins"));
  await select.selectOption(String(template.forms![17].id));
  assert.ok((await viewer.innerText()).includes("Additional Form 15"));
  await select.selectOption("");
  assert.equal(await viewer.locator("[data-creature-form-preview]").count(), 0);
  await select.selectOption(String(template.forms![1].id));
  page.off("request", observe);
  assert.deepEqual(mutations, [], "Form selection and viewing send no mutation requests");
  assert.deepEqual(await runtimeRows(), before, "Every existing Campaign/Character/inventory runtime row is unchanged by preview");
  await page.getByLabel("Personality", { exact: true }).fill("Unrelated edit while viewing Winged Form");
  await page.getByRole("button", { name: "Save Individual", exact: true }).click();
  await until(async () => (await pool.query("select personality from campaign_creature_npc_profile where character_id=$1", [npcId])).rows[0].personality === "Unrelated edit while viewing Winged Form");
  const storedAfter = (await pool.query("select * from campaign_creature_npc_profile where character_id=$1", [npcId])).rows[0];
  assert.deepEqual(JSON.parse(storedAfter.current_snapshot_json), JSON.parse(storedBefore.current_snapshot_json));
  assert.equal(storedAfter.baseline_snapshot_json, storedBefore.baseline_snapshot_json);
  assert.equal((await pool.query("select total_damage from campaign_character_active_health where character_id=$1", [npcId])).rows[0].total_damage, 7);
  await page.reload(); await select.waitFor(); assert.equal(await select.inputValue(), "");
  await select.selectOption(String(template.forms![1].id));
  await page.goto(`${base}/heavens/npcs?campaign=${campaignId}`);
  await page.goto(`${base}/heavens/npcs/${npcId}`); await select.waitFor(); assert.equal(await select.inputValue(), "");
  console.log("PASS: Creature Form browser authoring, all 18 snapshot Forms, full native preview, local reset, zero mutation requests, unchanged DB/runtime, safe unrelated save, desktop and 390px");
}
