import assert from "node:assert/strict";
import type { Page } from "playwright-core";
import { db, pool } from "@/db";
import { readProtectionLayersInTransaction } from "@/features/protection/protection-service";
import { protectionAtLocation, type ProtectionTarget } from "@/features/protection/protection-layers";
import { readRaceNaturalProtectionInTransaction, saveRaceNaturalProtectionInTransaction } from "@/features/races/race-natural-protection-service";
import { calculateOrdinaryAttackDamage } from "@/features/tabletop-operations/ordinary-attack-consequence-service";

export async function checkProtectionLayers(page: Page, input: { base: string; artifacts: string; campaignId: number; userId: string; creatureId: number; npcId: number; encounterId: number }) {
  const { base, artifacts, campaignId, userId, creatureId, npcId, encounterId } = input;
  const read = (target: ProtectionTarget) => db.transaction((tx) => readProtectionLayersInTransaction(tx, target));
  const damageBefore = calculateOrdinaryAttackDamage(10, 2, 5, 1);
  await page.goto(`${base}/heavens/races`);
  await page.getByRole("button", { name: "New Race", exact: true }).click();
  await page.getByLabel("Name", { exact: true }).fill("Protection Test Race");
  await page.getByRole("button", { name: "Save Race", exact: true }).click();
  await page.getByText("Protection Test Race was saved.", { exact: true }).waitFor();
  const raceId = (await pool.query("select id from races where name='Protection Test Race'")).rows[0].id as number;
  assert.deepEqual(await db.transaction((tx) => readRaceNaturalProtectionInTransaction(tx, raceId)), []);
  await page.getByRole("button", { name: "Mechanics", exact: true }).click();
  const section = page.getByRole("region", { name: "Natural Protection", exact: true });
  const movement = page.getByRole("heading", { name: "Movement Modes", exact: true });
  const interactions = page.getByRole("region", { name: "Racial Interaction Rules", exact: true });
  assert.ok((await movement.boundingBox())!.y < (await section.boundingBox())!.y);
  assert.ok((await section.boundingBox())!.y < (await interactions.boundingBox())!.y);
  // Plain HTTP on a home/LAN host exposes getRandomValues, but not randomUUID.
  // Keep that browser capability difference for both additions and the save.
  await page.evaluate(() => Object.defineProperty(crypto, "randomUUID", { configurable: true, value: undefined }));
  assert.equal(await page.evaluate(() => typeof crypto.randomUUID), "undefined");
  assert.equal(await page.evaluate(() => typeof crypto.getRandomValues), "function");
  await section.getByRole("button", { name: "Add Natural Protection", exact: true }).click();
  const first = section.getByRole("article").nth(0);
  await first.waitFor({ timeout: 5_000 });
  await first.getByLabel("Protection Name", { exact: true }).fill("Scaled Hide");
  await first.getByLabel("Soak", { exact: true }).fill("1");
  assert.equal(await first.getByLabel("Coverage", { exact: true }).inputValue(), "all");
  await section.getByRole("button", { name: "Add Natural Protection", exact: true }).click();
  const second = section.getByRole("article").nth(1);
  await second.getByLabel("Protection Name", { exact: true }).fill("Shell");
  await second.getByLabel("Soak", { exact: true }).fill("2");
  await second.getByLabel("Coverage", { exact: true }).selectOption("locations");
  await page.getByRole("button", { name: "Save Race", exact: true }).click();
  await page.getByText("Coverage needs All locations or at least one selected location.", { exact: true }).waitFor();
  assert.deepEqual(await db.transaction((tx) => readRaceNaturalProtectionInTransaction(tx, raceId)), []);
  const coverageLabels = await second.getByRole("checkbox").evaluateAll((inputs) => inputs.map((input) => input.closest("label")!.textContent));
  assert.deepEqual(coverageLabels, ["Head", "Right Arm", "Left Arm", "Right Lower Leg", "Right Upper Leg", "Left Lower Leg", "Left Upper Leg", "Groin", "Stomach", "Chest"]);
  for (const name of ["Groin", "Stomach", "Chest"]) await second.getByLabel(name, { exact: true }).check();
  await page.setViewportSize({ width: 390, height: 844 });
  for (const element of await section.locator("input,select,button").all()) assert.equal(await element.evaluate((element) => { const box = element.getBoundingClientRect(); return box.left >= 0 && box.right <= innerWidth; }), true);
  await second.screenshot({ path: `${artifacts}/race-natural-protection-phone.png` });
  await page.getByRole("button", { name: "Save Race", exact: true }).click();
  await page.getByText("Protection Test Race was saved.", { exact: true }).waitFor();
  const saved = await db.transaction((tx) => readRaceNaturalProtectionInTransaction(tx, raceId));
  assert.equal(new Set(saved.map(({ key }) => key)).size, 2, "Multiple additions retain distinct protection identities without randomUUID.");
  assert.deepEqual(saved.map(({ name, naturalSoak, coverage }) => ({ name, naturalSoak, coverage })), [
    { name: "Scaled Hide", naturalSoak: 1, coverage: { kind: "all" } },
    { name: "Shell", naturalSoak: 2, coverage: { kind: "locations", locationKeys: ["7", "8", "9"] } },
  ]);
  await page.reload();
  await page.locator(".skill-library__row").filter({ hasText: "Protection Test Race" }).click();
  await page.getByRole("button", { name: "Mechanics", exact: true }).click();
  assert.deepEqual((await db.transaction((tx) => readRaceNaturalProtectionInTransaction(tx, raceId))).map(({ key }) => key), saved.map(({ key }) => key));
  assert.equal(await second.getByLabel("Chest", { exact: true }).isChecked(), true);
  await page.setViewportSize({ width: 1365, height: 1000 });
  const characterId = (await pool.query("insert into campaign_character (campaign_id,player_user_id,name) values ($1,$2,'Protection Character') returning id", [campaignId, userId])).rows[0].id as number;
  await pool.query("insert into campaign_character_profile (character_id,race_id) values ($1,$2)", [characterId, raceId]);
  const target: ProtectionTarget = { kind: "character", characterId };
  const naked = await read(target); assert.equal(naked.worn.length, 0); assert.deepEqual(naked.natural.map(({ soak }) => soak), [1, 2]);
  const itemId = (await pool.query("insert into items (canonical_id,name,catalog_scope,equipment_group,record_type,family,category,price_basis) values ('ARMOR-PROTECTION-TEST','Worn Breastplate','equipment','armor','Armor','Armor','Armor','Each') returning id")).rows[0].id;
  await pool.query("insert into campaign_inventory_item(campaign_id,item_id) values ($1,$2)", [campaignId, itemId]);
  await pool.query("insert into armor_profiles (item_id,base_soak,coverage,damage_modifiers_source_text) values ($1,5,'Chest','Fire +2')", [itemId]);
  await pool.query("insert into armor_location_reference (location_code,location_name,sort_order) values ('9','Chest',9) on conflict do nothing");
  await pool.query("insert into armor_locations (item_id,location_code,sort_order) values ($1,'9',0)", [itemId]);
  await pool.query("insert into item_armor_damage_modifiers (item_id,damage_type,modifier,modifier_text,notes,sort_order) values ($1,'Fire','+2','Fire +2','Authored metadata only',0)", [itemId]);
  for (const owner of [characterId, npcId]) {
    await pool.query("insert into campaign_character_item (character_id,item_id,quantity,unit_cost_credits) values ($1,$2,1,0)", [owner, itemId]);
    assert.equal((await read({ kind: "character", characterId: owner })).worn.length, 0, "Ownership alone is not worn protection");
    await pool.query("insert into campaign_character_item_equipment_state (character_id,item_id,state,quantity) values ($1,$2,'worn',1)", [owner, itemId]);
    await pool.query("insert into campaign_character_active_modifier (character_id,label,modifier_channel,target_key,amount,source_kind,source_id,source_name,duration_kind,duration_label) values ($1,'Temporary Ward','soak','self',1,'spell','ward-1','Ward Spell','until-removed','Until Removed')", [owner]);
  }
  const character = await read(target), chest = protectionAtLocation(character, "9"), head = protectionAtLocation(character, "0");
  assert.deepEqual(chest.natural.map(({ soak }) => soak), [1, 2]); assert.equal(chest.worn[0].baseSoak, 5); assert.equal(chest.temporary[0].amount, 1);
  assert.equal(chest.worn[0].damageModifiers[0].damageType, "Fire"); assert.equal(chest.worn[0].damageModifiersSourceText, "Fire +2");
  assert.equal(head.natural.length, 1); assert.equal(head.worn.length, 0); assert.equal(head.temporary.length, 1);
  const npcBefore = (await pool.query("select baseline_snapshot_json,current_snapshot_json from campaign_creature_npc_profile where character_id=$1", [npcId])).rows[0];
  const npc = protectionAtLocation(await read({ kind: "character", characterId: npcId }), "9");
  assert.deepEqual([npc.natural[0].armor, npc.natural[0].soak, npc.worn[0].baseSoak, npc.temporary[0].amount], [3, 2, 5, 1]);
  const [occurrence] = (await pool.query("select character_id,creature_snapshot_json from campaign_session_encounter_participant where encounter_id=$1 and participant_kind='creature'", [encounterId])).rows;
  const directTarget: ProtectionTarget = { kind: "encounter-participant", campaignId, encounterId, participantId: occurrence.character_id };
  await pool.query("update campaign_session_encounter_participant set local_state_json=jsonb_set(local_state_json,'{modifiers}',$1::jsonb) where encounter_id=$2 and character_id=$3", [JSON.stringify([
    { effectPlanEffectId: 91, label: "Occurrence Ward", channel: "soak", targetKey: "self", amount: 4, sourceIdentity: { name: "Ward" }, duration: { kind: "scene" } },
    { effectPlanEffectId: 92, label: "Expired Ward", channel: "soak", targetKey: "self", amount: 9, expiredAt: new Date().toISOString() },
  ]), encounterId, occurrence.character_id]);
  const direct = protectionAtLocation(await read(directTarget), "9");
  assert.deepEqual([direct.natural[0].armor, direct.natural[0].soak], [3, 2]); assert.equal(direct.worn.length, 0);
  assert.deepEqual(direct.temporary.map(({ amount }) => amount), [4]);
  await assert.rejects(read({ ...directTarget, campaignId: campaignId + 999 }), /does not belong/);
  await first.getByLabel("Soak", { exact: true }).fill("4");
  await page.getByRole("button", { name: "Save Race", exact: true }).click();
  await page.getByText("Protection Test Race was saved.", { exact: true }).waitFor();
  assert.equal((await read(target)).natural[0].soak, 4, "Race edits are resolved live without copying into Characters");
  const emptyRaceId = (await pool.query("select id from races where name='Migration Legacy Race'")).rows[0].id;
  await pool.query("update campaign_character_profile set race_id=$1 where character_id=$2", [emptyRaceId, characterId]);
  assert.deepEqual((await read(target)).natural, []);
  await pool.query("update campaign_character_profile set race_id=null where character_id=$1", [characterId]);
  assert.deepEqual((await read(target)).natural, []);
  await pool.query("update campaign_character_profile set race_id=$1 where character_id=$2", [raceId, characterId]);
  assert.equal((await read(target)).natural[0].soak, 4);
  assert.deepEqual((await pool.query("select baseline_snapshot_json,current_snapshot_json from campaign_creature_npc_profile where character_id=$1", [npcId])).rows[0], npcBefore);
  assert.deepEqual((await pool.query("select creature_snapshot_json from campaign_session_encounter_participant where encounter_id=$1 and character_id=$2", [encounterId, occurrence.character_id])).rows[0].creature_snapshot_json, occurrence.creature_snapshot_json);
  await page.goto(`${base}/heavens/creatures`);
  await page.locator(".skill-library__row").filter({ hasText: "Authoring Test Creature" }).click();
  await page.getByRole("button", { name: "Health & Protection", exact: true }).click();
  assert.equal(await page.getByLabel("Natural Armor", { exact: true }).inputValue(), "3");
  assert.equal(await page.getByLabel("Natural Soak", { exact: true }).inputValue(), "2");
  await page.goto(`${base}/heavens/npcs/${npcId}`);
  await page.getByRole("button", { name: "Health & Protection", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.getByLabel("Natural Soak", { exact: true }).inputValue(), "2");
  await page.getByLabel("Natural Soak", { exact: true }).fill("3");
  await page.getByRole("button", { name: "Save Individual", exact: true }).click();
  await page.getByText("Authoring Individual was saved. The Authoring Test Creature master Creature was not changed.", { exact: true }).waitFor();
  await page.reload();
  await page.getByRole("button", { name: "Health & Protection", exact: true }).click();
  assert.equal(await page.getByLabel("Natural Soak", { exact: true }).inputValue(), "3");
  const savedNpcProtection = protectionAtLocation(await read({ kind: "character", characterId: npcId }), "9");
  assert.equal(savedNpcProtection.natural[0].soak, 3);
  assert.equal(savedNpcProtection.worn[0]?.baseSoak, 5, "Editing natural protection must preserve Worn equipment state");
  assert.equal(savedNpcProtection.temporary[0]?.amount, 1, "Editing anatomy must preserve active modifiers");
  assert.equal((await pool.query("select soak from creature_hit_locations where creature_id=$1 and hit_location_number=9", [creatureId])).rows[0].soak, 2);
  assert.equal((await pool.query("select baseline_snapshot_json from campaign_creature_npc_profile where character_id=$1", [npcId])).rows[0].baseline_snapshot_json, npcBefore.baseline_snapshot_json);
  await page.setViewportSize({ width: 1365, height: 1000 });
  const rowIds = (await pool.query("select id,key from race_natural_protections where race_id=$1 order by key", [raceId])).rows;
  const current = await db.transaction((tx) => readRaceNaturalProtectionInTransaction(tx, raceId));
  await db.transaction((tx) => saveRaceNaturalProtectionInTransaction(tx, raceId, current));
  assert.deepEqual((await pool.query("select id,key from race_natural_protections where race_id=$1 order by key", [raceId])).rows, rowIds);
  await assert.rejects(db.transaction((tx) => saveRaceNaturalProtectionInTransaction(tx, raceId, [{ ...current[0], naturalSoak: -1 }])), /zero or greater/);
  assert.deepEqual(await db.transaction((tx) => readRaceNaturalProtectionInTransaction(tx, raceId)), current);
  for (const amount of ["-1", "Infinity", "NaN"]) await assert.rejects(pool.query("update race_natural_protections set natural_soak=$1 where race_id=$2", [amount, raceId]), /amounts_valid/);
  await assert.rejects(pool.query("insert into race_natural_protection_locations(protection_id,location_key) values ($1,'10')", [rowIds[0].id]), /location_valid/);
  assert.deepEqual(calculateOrdinaryAttackDamage(10, 2, 5, 1), damageBefore);
  assert.equal(damageBefore.netDamage, 6);
  console.log("PASS: Pass 3 Race authoring, live inheritance, worn/natural/temporary separation, exact coverage, direct/NPC snapshot preservation, mobile UI and unchanged ordinary damage");
}
