import assert from "node:assert/strict";
import type { Page } from "playwright-core";
import { pool } from "@/db";

export async function checkRaceNaturalAttacksBrowser(page: Page, base: string) {
  assert.equal(process.env.SERRIAN_DISPOSABLE_RACE_AUTHORING, "true");
  const skillId = (await pool.query("insert into skill(name,classification,tier) values('Browser Natural Attack Skill','standard',3) returning id")).rows[0].id;
  const name = "Natural Attack Browser Race";
  const button = (name: string) => page.getByRole("button", { name, exact: true });
  const save = async (raceName = name) => { await button("Save Race").click(); await page.getByText(`${raceName} was saved.`, { exact: true }).waitFor(); };
  const open = async (raceName = name) => {
    await page.goto(`${base}/heavens/races`);
    await page.locator("#race-search").fill(raceName);
    await page.locator(".skill-library__row").filter({ hasText: raceName }).click();
    await button("Natural Attacks").click();
  };
  const row = (index: number) => page.getByRole("article", { name: `Natural Attack ${index}`, exact: true });
  await page.goto(`${base}/heavens/races`);
  await button("New Race").click(); await page.getByLabel("Name", { exact: true }).fill(name);
  await button("Natural Attacks").click(); await page.getByText("No Natural Attacks authored.", { exact: true }).waitFor();
  // The authoring key must also work on plain HTTP LAN hosts.
  await page.evaluate(() => Object.defineProperty(crypto, "randomUUID", { configurable: true, value: undefined }));
  await button("Add Natural Attack").click();
  assert.equal(await row(1).getByLabel("Attack %", { exact: true }).count(), 0);
  await row(1).getByLabel("Attack Name", { exact: true }).fill("Bite");
  await row(1).getByLabel("Damage", { exact: true }).fill("4");
  await row(1).getByLabel("Damage Type", { exact: true }).fill("Piercing");
  await row(1).getByLabel("Attack Mode", { exact: true }).selectOption("melee");
  assert.equal(await row(1).getByLabel("Short Range", { exact: true }).count(), 0);
  await row(1).getByLabel("Reach", { exact: true }).fill("2");
  await row(1).getByLabel("Reach Unit", { exact: true }).fill("feet");
  await row(1).getByLabel("Magical", { exact: true }).selectOption("false");
  await row(1).getByLabel("Attack Initiative", { exact: true }).fill("0");
  await button("Save Race").click();
  await page.locator(".skill-editor__feedback").filter({ hasText: "Attack Initiative must be greater than zero" }).waitFor();
  assert.equal((await pool.query("select count(*)::int n from races where name=$1", [name])).rows[0].n, 0);
  await row(1).getByLabel("Attack Initiative", { exact: true }).fill("3");
  await row(1).getByLabel("Search Attack Skills", { exact: true }).fill("Browser Natural Attack Skill");
  await row(1).getByLabel("Attack Skill", { exact: true }).locator(`option[value="${skillId}"]`).waitFor({ state: "attached" });
  await row(1).getByLabel("Attack Skill", { exact: true }).selectOption(String(skillId));
  await row(1).getByLabel("Attack Basis Notes", { exact: true }).fill("Character Skill basis");
  await row(1).getByRole("group", { name: "Required HP Pools", exact: true }).getByRole("checkbox").first().check();
  await row(1).getByRole("group", { name: "Required Hit Locations", exact: true }).getByRole("checkbox").first().check();
  await row(1).getByLabel("Anatomy Requirement Notes", { exact: true }).fill("Requires a functional jaw.");
  await row(1).getByRole("button", { name: "Add On-Hit Effect", exact: true }).click();
  await row(1).getByLabel("Title", { exact: true }).fill("Venom ruling");
  await row(1).getByLabel("Instructions", { exact: true }).fill("G.O.D. resolves the authored venom.");
  await save();
  const raceId = (await pool.query("select id from races where name=$1", [name])).rows[0].id;
  const stored = async () => (await pool.query("select * from race_natural_attacks where race_id=$1 order by sort_order,id", [raceId])).rows;
  const original = await stored();
  assert.equal(original[0].skill_id, skillId);
  assert.equal(original[0].authoring_json.magical, false);
  assert.equal(original[0].anatomy_requirement_json.notes, "Requires a functional jaw.");
  assert.equal(original[0].authoring_json.onHitEffects[0].effect.title, "Venom ruling");
  await open();
  assert.equal(await row(1).getByLabel("Attack Skill", { exact: true }).inputValue(), String(skillId));
  assert.equal(await row(1).getByLabel("Reach", { exact: true }).inputValue(), "2");
  assert.equal(await row(1).getByLabel("Anatomy Requirement Notes", { exact: true }).inputValue(), "Requires a functional jaw.");
  await button("Add Natural Attack").click();
  await row(2).getByLabel("Attack Name", { exact: true }).fill("Spines");
  await row(2).getByLabel("Damage", { exact: true }).fill("6");
  await row(2).getByLabel("Attack Mode", { exact: true }).selectOption("ranged");
  assert.equal(await row(2).getByLabel("Reach", { exact: true }).count(), 0);
  await row(2).getByLabel("Distance Unit", { exact: true }).fill("feet");
  for (const [label, value] of [["Short", "10"], ["Medium", "20"], ["Long", "30"]]) await row(2).getByLabel(`${label} Range`, { exact: true }).fill(value);
  await row(2).getByLabel("Magical", { exact: true }).selectOption("true");
  await row(2).getByRole("button", { name: "Move Up", exact: true }).click();
  await save();
  assert.deepEqual((await stored()).map(attack => attack.attack_name), ["Spines", "Bite"]);
  await open();
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    const help = row(1).locator('[data-field-guidance="Attack Initiative"] summary');
    await help.click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await row(1).screenshot({ path: `artifacts/race-authoring/natural-attacks-${width}.png` });
    await help.press("Escape");
    assert.equal(await help.evaluate(element => element === document.activeElement), true);
    assert.equal(await page.locator(".skill-editor__header").getByText("Unsaved changes", { exact: true }).count(), 0);
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await row(1).getByRole("button", { name: "Remove Natural Attack", exact: true }).click();
  await save();
  assert.deepEqual((await stored()).map(attack => attack.attack_name), ["Bite"]);
  await button("Variants").click();
  await page.getByLabel("Variant Name", { exact: true }).fill("Natural Attack Browser Variant");
  await button("Clone as Variant").click();
  await page.getByText("Natural Attack Browser Variant was created as a variant.", { exact: true }).waitFor();
  await button("Natural Attacks").click();
  assert.equal(await row(1).getByLabel("Damage", { exact: true }).inputValue(), "4");
  await row(1).getByLabel("Damage", { exact: true }).fill("11");
  await save("Natural Attack Browser Variant");
  assert.equal((await stored())[0].damage, "4");
  assert.equal((await stored())[0].id, original[0].id);
  console.log("PASS: Race Natural Attack add/edit/remove/reorder, validation, Skill/anatomy/on-hit reload, independent variant, HTTP-safe keys, guidance and 1440/390px layouts");
}
