import assert from "node:assert/strict";
import type { Page } from "playwright-core";
import { pool } from "@/db";

export async function checkRaceFormMechanicsBrowser(page: Page, base: string) {
  assert.equal(process.env.SERRIAN_DISPOSABLE_RACE_AUTHORING, "true");
  const [skill] = (await pool.query("insert into skill(name,classification,tier) values('Form Browser Skill','standard',1) returning id")).rows;
  const name = "Form Mechanics Browser Race";
  const button = (name: string) => page.getByRole("button", { name, exact: true });
  const form = page.getByRole("article", { name: "Form 1", exact: true });
  const section = (title: string) => form.locator("details").filter({ has: page.locator("summary").filter({ hasText: new RegExp(`^${title} ·`) }) }).first();
  const expand = async (title: string) => { const target = section(title); if (!(await target.evaluate(element => (element as HTMLDetailsElement).open))) await target.locator(":scope > summary").click(); return target; };
  const save = async (raceName = name) => { await button("Save Race").click(); await page.getByText(`${raceName} was saved.`, { exact: true }).waitFor(); };
  const open = async () => { await page.goto(`${base}/heavens/races`); await page.locator("#race-search").fill(name); await page.locator(".skill-library__row").filter({ hasText: name }).click(); await button("Forms").click(); };
  await page.goto(`${base}/heavens/races`);
  await button("New Race").click(); await page.getByLabel("Name", { exact: true }).fill(name);
  await button("Forms").click();
  await page.evaluate(() => Object.defineProperty(crypto, "randomUUID", { configurable: true, value: undefined }));
  await button("Add Form").click(); await form.getByLabel("Form Name", { exact: true }).fill("Wolf Form");
  await expand("Attributes");
  for (const [label, value] of [["Strength", "5"], ["Dexterity", "10"], ["Constitution", "5"], ["Intelligence", "0"], ["Wisdom", "5"], ["Charisma", "-5"]]) await form.getByLabel(`${label} change while in this Form`, { exact: true }).fill(value);
  const body = await expand("Body");
  await body.getByLabel("Form Size", { exact: true }).selectOption("Large");
  await body.getByLabel("Body and hit locations in this Form", { exact: true }).selectOption("override");
  await body.getByLabel("Body layout", { exact: true }).selectOption("custom");
  await body.getByLabel("Pool Name", { exact: true }).first().fill("Wolf head");
  await body.getByLabel("Location Name", { exact: true }).first().fill("Muzzle");
  const movement = await expand("Movement");
  await movement.getByLabel("Movement in this Form", { exact: true }).selectOption("override");
  await movement.getByRole("button", { name: "Add Movement", exact: true }).click();
  await movement.getByLabel("Movement Mode", { exact: true }).fill("Land");
  await movement.getByLabel("Base Movement", { exact: true }).fill("4");
  await movement.getByLabel("Notes", { exact: true }).fill("Four-legged movement");
  const protection = await expand("Protection");
  await protection.getByLabel("Natural Protection in this Form", { exact: true }).selectOption("override");
  await protection.getByRole("button", { name: "Add Natural Protection", exact: true }).click();
  await protection.getByLabel("Protection Name", { exact: true }).fill("Fur"); await protection.getByLabel("Soak", { exact: true }).fill("2");
  await protection.getByLabel("Coverage", { exact: true }).selectOption("locations");
  await protection.getByRole("checkbox", { name: "Muzzle", exact: true }).check();
  const attacks = await expand("Natural Attacks");
  await attacks.getByLabel("Natural Attacks in this Form", { exact: true }).selectOption("override");
  await attacks.getByRole("button", { name: "Add Natural Attack", exact: true }).click();
  await attacks.getByLabel("Attack Name", { exact: true }).fill("Bite");
  await attacks.getByLabel("Damage", { exact: true }).fill("5");
  await attacks.getByLabel("Attack Initiative", { exact: true }).fill("3");
  await attacks.getByLabel("Attack Mode", { exact: true }).selectOption("melee");
  await attacks.getByLabel("Search Attack Skills", { exact: true }).fill("Form Browser Skill");
  await attacks.getByLabel("Attack Skill", { exact: true }).locator(`option[value="${skill.id}"]`).waitFor({ state: "attached" });
  await attacks.getByLabel("Attack Skill", { exact: true }).selectOption(String(skill.id));
  await attacks.getByRole("group", { name: "Required HP Pools", exact: true }).getByRole("checkbox", { name: "Wolf head", exact: true }).check();
  const skills = await expand("Skills / Abilities");
  await skills.getByLabel("Skills and Abilities in this Form", { exact: true }).selectOption("add");
  await skills.getByLabel("Search", { exact: true }).fill("Form Browser Skill");
  await skills.getByLabel("Matching Skills", { exact: true }).locator(`option[value="${skill.id}"]`).waitFor({ state: "attached" });
  await skills.getByLabel("Matching Skills", { exact: true }).selectOption(String(skill.id));
  await skills.getByRole("button", { name: "Add Skill or Ability", exact: true }).click();
  await skills.getByLabel("Form Skill points", { exact: true }).fill("5");
  const rules = await expand("Interaction Rules");
  await rules.getByLabel("Interaction Rules in this Form", { exact: true }).selectOption("add");
  await rules.getByRole("button", { name: "Add Interaction Rule", exact: true }).click();
  await rules.getByLabel("Rule Name", { exact: true }).fill("Cold resistance");
  await rules.getByLabel("Rule Type", { exact: true }).selectOption("resistance");
  await rules.getByLabel("Amount (%)", { exact: true }).fill("25");
  await rules.getByLabel("Damage Type", { exact: true }).fill("Cold");
  const physical = await expand("Using the body and equipment");
  await physical.getByLabel("Using hands, tools & objects", { exact: true }).selectOption("none");
  await physical.getByLabel("Using hands, tools & objects Notes", { exact: true }).fill("Paws");
  await physical.getByLabel("Speech", { exact: true }).selectOption("limited");
  await physical.getByLabel("Speech Notes", { exact: true }).fill("Short sounds");
  await physical.getByLabel("Equipment interaction", { exact: true }).selectOption("unusable");
  await physical.getByLabel("Equipment interaction Notes", { exact: true }).fill("Keep carried equipment");
  await physical.getByRole("button", { name: "Add Restriction", exact: true }).click();
  await physical.getByLabel("Restriction Name", { exact: true }).fill("Fine tools");
  await physical.getByLabel("Restriction Notes", { exact: true }).fill("No fingers");
  await save();
  const raceId = (await pool.query("select id from races where name=$1", [name])).rows[0].id;
  const stored = async (id = raceId) => (await pool.query("select * from race_forms where race_id=$1", [id])).rows[0];
  const original = await stored();
  assert.deepEqual(original.mechanics_json.attributeAdjustments, { STR: 5, DEX: 10, CON: 5, INT: 0, WIS: 5, CHR: -5 });
  assert.equal((await pool.query("select anatomy_json from races where id=$1", [raceId])).rows[0].anatomy_json, null);
  assert.equal((await pool.query("select count(*)::int n from race_natural_attacks where race_id=$1", [raceId])).rows[0].n, 0);
  await open();
  for (const title of ["Body", "Attributes", "Movement", "Protection", "Natural Attacks", "Skills / Abilities", "Interaction Rules", "Using the body and equipment"]) await expand(title);
  assert.equal(await form.getByLabel("Charisma change while in this Form", { exact: true }).inputValue(), "-5");
  assert.equal(await body.getByLabel("Pool Name", { exact: true }).first().inputValue(), "Wolf head");
  assert.equal(await attacks.getByLabel("Attack Skill", { exact: true }).inputValue(), String(skill.id));
  assert.equal(await protection.getByRole("checkbox", { name: "Muzzle", exact: true }).isChecked(), true);
  assert.equal(await rules.getByLabel("Rule Name", { exact: true }).inputValue(), "Cold resistance");
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 });
    const help = form.locator('[data-field-guidance="Strength change while in this Form"] summary');
    await help.click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await section("Attributes").screenshot({ path: `artifacts/race-authoring/form-mechanics-attributes-${width}.png` });
    await help.press("Escape");
    assert.equal(await help.evaluate(element => element === document.activeElement), true);
    await physical.screenshot({ path: `artifacts/race-authoring/form-mechanics-physical-${width}.png` });
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await button("Variants").click(); await page.getByLabel("Variant Name", { exact: true }).fill("Form Mechanics Browser Variant");
  await button("Clone as Variant").click(); await page.getByText("Form Mechanics Browser Variant was created as a variant.", { exact: true }).waitFor();
  await button("Forms").click(); await expand("Attributes");
  assert.equal(await form.getByLabel("Strength change while in this Form", { exact: true }).inputValue(), "5");
  await form.getByLabel("Strength change while in this Form", { exact: true }).fill("-7");
  await save("Form Mechanics Browser Variant");
  assert.deepEqual(await stored(), original);
  console.log("PASS: multi-system Form mechanics and signed Attributes author/save/reload/clone through shared editors; Race untouched; desktop/390px layouts and guidance pass");
}
