import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { copyFile, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import pg from "pg";
import { emptyRaceNaturalAttack } from "../src/features/races/race-natural-attacks";

test("Race Soak migration, independent variants, protection integration and authoring browser", { timeout: 900_000 }, async () => {
  const parent = path.resolve(tmpdir());
  const root = path.resolve(await mkdtemp(path.join(parent, "serrian-race-authoring-")));
  assert.equal(path.dirname(root), parent); assert.ok(path.basename(root).startsWith("serrian-race-authoring-"));
  const data = path.join(root, "data"), bin = process.env.SERRIAN_TEST_POSTGRES_BIN ?? "C:/Program Files/PostgreSQL/18/bin";
  const exe = (name: string) => path.join(bin, `${name}${process.platform === "win32" ? ".exe" : ""}`);
  const listener = createServer(); await new Promise<void>((resolve) => listener.listen(0, "127.0.0.1", resolve));
  const address = listener.address(); assert.ok(address && typeof address === "object"); const port = address.port;
  await new Promise<void>((resolve) => listener.close(() => resolve()));
  const databaseUrl = `postgresql://postgres@127.0.0.1:${port}/serrian_race_authoring_dev`;
  let started = false, pool: pg.Pool | null = null;
  try {
    execFileSync(exe("initdb"), ["--auth=trust", "--encoding=UTF8", "--no-locale", "--username=postgres", "-D", data], { stdio: "pipe", windowsHide: true });
    execFileSync(exe("pg_ctl"), ["-D", data, "-l", path.join(root, "postgres.log"), "-o", `-p ${port} -h 127.0.0.1`, "-w", "start"], { stdio: "ignore", windowsHide: true }); started = true;
    pool = new pg.Pool({ connectionString: `postgresql://postgres@127.0.0.1:${port}/postgres` });
    await pool.query("create database serrian_race_authoring_dev"); await pool.end();
    pool = new pg.Pool({ connectionString: databaseUrl });
    const journal = JSON.parse(readFileSync("drizzle/meta/_journal.json", "utf8"));
    const legacy = path.join(root, "legacy"); await mkdir(path.join(legacy, "meta"), { recursive: true });
    const entries = journal.entries.filter((entry: { idx: number }) => entry.idx < 64);
    await writeFile(path.join(legacy, "meta/_journal.json"), JSON.stringify({ ...journal, entries }));
    for (const entry of entries) await copyFile(path.resolve("drizzle", `${entry.tag}.sql`), path.join(legacy, `${entry.tag}.sql`));
    await migrate(drizzle(pool), { migrationsFolder: legacy });
    const [race] = (await pool.query("insert into races(name,size,base_magic,legacy_description) values ('Migration Race','Colossal',3,'Preserve lore') returning *")).rows;
    await pool.query("insert into races(name) values ('Unrelated Independent Race')");
    const protections = (await pool.query("insert into race_natural_protections(race_id,key,name,natural_armor,natural_soak,coverage_kind,sort_order) values ($1,'hide','Hide',9,2,'all',0),($1,'shell','Shell',7,0.5,'locations',1) returning *", [race.id])).rows;
    await pool.query("insert into race_natural_protection_locations(protection_id,location_key) values ($1,'9')", [protections[1].id]);
    const locations = (await pool.query("select * from race_natural_protection_locations")).rows;
    const beforeAttacks = path.join(root, "before-attacks"); await mkdir(path.join(beforeAttacks, "meta"), { recursive: true });
    const beforeAttackEntries = journal.entries.filter((entry: { idx: number }) => entry.idx < 71);
    await writeFile(path.join(beforeAttacks, "meta/_journal.json"), JSON.stringify({ ...journal, entries: beforeAttackEntries }));
    for (const entry of beforeAttackEntries) await copyFile(path.resolve("drizzle", `${entry.tag}.sql`), path.join(beforeAttacks, `${entry.tag}.sql`));
    await migrate(drizzle(pool), { migrationsFolder: beforeAttacks });
    assert.deepEqual((await pool.query("select * from races where id=$1", [race.id])).rows[0], { ...race, parent_race_id: null, anatomy_json: null });
    assert.equal((await pool.query("select count(*)::int n from races where parent_race_id is not null")).rows[0].n, 0);
    const expected = protections.map((row) => { const result = { ...row }; delete result.natural_armor; return result; });
    assert.deepEqual((await pool.query("select * from race_natural_protections order by id")).rows, expected);
    assert.deepEqual((await pool.query("select * from race_natural_protection_locations")).rows, locations);
    assert.equal((await pool.query("select count(*)::int n from information_schema.columns where table_name='race_natural_protections' and column_name='natural_armor'")).rows[0].n, 0);
    for (const value of [-1, "NaN", "Infinity", "-Infinity"]) await assert.rejects(pool.query("update race_natural_protections set natural_soak=$1", [value]), /amounts_valid/);
    await assert.rejects(pool.query("update races set parent_race_id=id where id=$1", [race.id]), /parent_not_self/);
    await assert.rejects(pool.query("update races set parent_race_id=2147483647 where id=$1", [race.id]), /foreign key/);
    const variant = (await pool.query("insert into races(name,parent_race_id,anatomy_json) values ('Existing Migration Variant',$1,$2) returning id", [race.id, JSON.stringify({ schemaVersion: 1, hpPools: [{ canonicalId: "tail", poolName: "Tail", hpPercentage: 20, notes: "Keep tail", sortOrder: 0 }], hitLocations: [{ hitLocationNumber: 0, locationName: "Tail", bodyPartsIncluded: "Tail", hpPoolCanonicalId: "tail", locationEffect: "", notes: "", sortOrder: 0 }] })])).rows[0].id;
    const skillId = (await pool.query("insert into skill(name,classification,tier) values ('Migration Skill','standard',1) returning id")).rows[0].id;
    await pool.query("insert into race_skill_links(race_id,skill_id,link_type,value) values($1,$2,'Skill',2)", [variant, skillId]);
    await pool.query("insert into race_attribute_caps(race_id,attribute_key,max_value) values($1,'STR',45)", [variant]);
    await pool.query("insert into race_movement_modes(race_id,movement_mode,base_value,notes) values($1,'Land',3,'Keep movement')", [variant]);
    const creatureId = (await pool.query("insert into creatures(canonical_id,canonical_name,size) values('CREATURE-RACE-ATTACK-MIGRATION','Preserved Creature','Medium') returning id")).rows[0].id;
    await pool.query("insert into creature_attacks(creature_id,canonical_id,attack_name,attack_percentage,damage) values($1,'ATK-RACE-MIGRATION','Preserved Bite',63,'4')", [creatureId]);
    const preservedTables = ["races", "race_attribute_caps", "race_movement_modes", "race_skill_links", "race_natural_protections", "race_natural_protection_locations", "skill", "creatures", "creature_attacks"];
    const beforeMigration = await Promise.all(preservedTables.map(table => pool!.query(`select to_jsonb(t) body from ${table} t order by to_jsonb(t)::text`)));
    const beforeForms = path.join(root, "before-forms"); await mkdir(path.join(beforeForms, "meta"), { recursive: true });
    const beforeFormEntries = journal.entries.filter((entry: { idx: number }) => entry.idx < 72);
    await writeFile(path.join(beforeForms, "meta/_journal.json"), JSON.stringify({ ...journal, entries: beforeFormEntries }));
    for (const entry of beforeFormEntries) await copyFile(path.resolve("drizzle", `${entry.tag}.sql`), path.join(beforeForms, `${entry.tag}.sql`));
    await migrate(drizzle(pool), { migrationsFolder: beforeForms });
    for (const [index, table] of preservedTables.entries()) assert.deepEqual((await pool.query(`select to_jsonb(t) body from ${table} t order by to_jsonb(t)::text`)).rows, beforeMigration[index].rows, `${table} unchanged by Natural Attack migration`);
    assert.equal((await pool.query("select count(*)::int n from race_natural_attacks")).rows[0].n, 0);
    const attack = emptyRaceNaturalAttack("migration-bite");
    await pool.query("insert into race_natural_attacks(race_id,key,attack_name,damage,authoring_json,skill_id,anatomy_requirement_json,sort_order) values($1,$2,'Existing Bite','4',$3,$4,$5,0)", [variant, attack.key, JSON.stringify(attack.authoring), skillId, JSON.stringify(attack.anatomy)]);
    await pool.query("update races set interaction_rules_json=$1 where id=$2", [JSON.stringify({ schemaVersion: 1, rules: [] }), variant]);
    const formPreservedTables = [...preservedTables, "race_natural_attacks"];
    const beforeFormMigration = await Promise.all(formPreservedTables.map(table => pool!.query(`select to_jsonb(t) body from ${table} t order by to_jsonb(t)::text`)));
    const beforeMechanics = path.join(root, "before-form-mechanics"); await mkdir(path.join(beforeMechanics, "meta"), { recursive: true });
    const beforeMechanicsEntries = journal.entries.filter((entry: { idx: number }) => entry.idx < 73);
    await writeFile(path.join(beforeMechanics, "meta/_journal.json"), JSON.stringify({ ...journal, entries: beforeMechanicsEntries }));
    for (const entry of beforeMechanicsEntries) await copyFile(path.resolve("drizzle", `${entry.tag}.sql`), path.join(beforeMechanics, `${entry.tag}.sql`));
    await migrate(drizzle(pool), { migrationsFolder: beforeMechanics });
    for (const [index, table] of formPreservedTables.entries()) assert.deepEqual((await pool.query(`select to_jsonb(t) body from ${table} t order by to_jsonb(t)::text`)).rows, beforeFormMigration[index].rows, `${table} unchanged by Forms migration`);
    assert.equal((await pool.query("select count(*)::int n from race_forms")).rows[0].n, 0);
    console.log("PASS: Forms migration preserves exact Race/variant, Anatomy, Natural Attack, protection, caps, movement, Skill, Interaction Rule and Creature data; zero Forms inferred");
    await pool.query("insert into race_forms(race_id,key,name,description,notes,sort_order) values($1,'wolf','Wolf Form','Existing alternate state','Keep notes',0),($1,'mist','Mist Form','Existing mist','Keep mist',1)", [variant]);
    const oldForms = (await pool.query("select * from race_forms order by id")).rows;
    await pool.query('insert into "user"(id,name,email) values(\'form-migration-user\',\'Migration User\',\'form-migration@example.invalid\')');
    const campaign = (await pool.query("insert into campaign(name,attribute_points,skill_points,max_starting_skill,points_to_unlock_next_tier,max_points_in_skill,starting_credit_amount,currency_system,fate_point_method,created_by_user_id) values('Form Migration Campaign',100,100,50,10,100,250,'Credits','Assigned','form-migration-user') returning id")).rows[0].id;
    await pool.query("insert into campaign_player(campaign_id,user_id) values($1,'form-migration-user')", [campaign]);
    const character = (await pool.query("insert into campaign_character(campaign_id,player_user_id,name) values($1,'form-migration-user','Preserved Character') returning id", [campaign])).rows[0].id;
    await pool.query("insert into campaign_character_profile(character_id,race_id) values($1,$2)", [character, variant]);
    await pool.query("insert into campaign_character_attribute(character_id,attribute_key,value) values($1,'STR',35)", [character]);
    const mechanicsPreservedTables = [...formPreservedTables, "campaign", "campaign_character", "campaign_character_profile", "campaign_character_attribute"];
    const beforeMechanicsMigration = await Promise.all(mechanicsPreservedTables.map(table => pool!.query(`select to_jsonb(t) body from ${table} t order by to_jsonb(t)::text`)));
    const beforeTransformation = path.join(root, "before-form-transformation"); await mkdir(path.join(beforeTransformation, "meta"), { recursive: true });
    const beforeTransformationEntries = journal.entries.filter((entry: { idx: number }) => entry.idx < 74);
    await writeFile(path.join(beforeTransformation, "meta/_journal.json"), JSON.stringify({ ...journal, entries: beforeTransformationEntries }));
    for (const entry of beforeTransformationEntries) await copyFile(path.resolve("drizzle", `${entry.tag}.sql`), path.join(beforeTransformation, `${entry.tag}.sql`));
    await migrate(drizzle(pool), { migrationsFolder: beforeTransformation });
    for (const [index, table] of mechanicsPreservedTables.entries()) assert.deepEqual((await pool.query(`select to_jsonb(t) body from ${table} t order by to_jsonb(t)::text`)).rows, beforeMechanicsMigration[index].rows, `${table} unchanged by Form mechanics migration`);
    assert.deepEqual((await pool.query("select * from race_forms order by id")).rows, oldForms.map(row => ({ ...row, mechanics_json: null })));
    for (const table of ["race_form_movement_modes", "race_form_natural_attacks", "race_form_natural_protections", "race_form_natural_protection_locations", "race_form_skill_links"]) assert.equal((await pool.query(`select count(*)::int n from ${table}`)).rows[0].n, 0);
    console.log("PASS: Form mechanics migration preserves Pass 2 Forms and all Race/Creature/Character data; defaults remain Use Race, with zero inferred mechanics");
    const { emptyRaceFormMechanics, raceFormMechanicsProfile } = await import("../src/features/races/race-form-mechanics");
    const preservedMechanics = emptyRaceFormMechanics(); preservedMechanics.attributeAdjustments.STR = 5; preservedMechanics.attributeAdjustments.CHR = -5;
    await pool.query("update race_forms set mechanics_json=$1 where key='wolf'", [JSON.stringify(raceFormMechanicsProfile(preservedMechanics))]);
    const transformationTables: string[] = (await pool.query("select tablename from pg_tables where schemaname='public' order by tablename")).rows.map(row => row.tablename);
    const beforeTransformationMigration = await Promise.all(transformationTables.map(table => pool!.query(`select to_jsonb(t) body from "${table}" t order by to_jsonb(t)::text`)));
    await migrate(drizzle(pool), { migrationsFolder: path.resolve("drizzle") });
    for (const [index, table] of transformationTables.entries()) {
      const expected = table === "race_forms" ? beforeTransformationMigration[index].rows.map(row => ({ body: { ...row.body, transformation_json: null, access_mode: "unrestricted" } })) : beforeTransformationMigration[index].rows;
      assert.deepEqual((await pool.query(`select to_jsonb(t) body from "${table}" t order by to_jsonb(t)::text`)).rows, expected, `${table} preserved by transformation migration`);
    }
    await assert.rejects(pool.query("update race_forms set transformation_json='{}'"), /transformation_shape/);
    console.log("PASS: transformation migration preserves every public table and signed Pass 3 mechanics; existing Forms have null transformation definitions");
    assert.equal((await pool.query("select count(*)::int n from drizzle.__drizzle_migrations")).rows[0].n, journal.entries.length);
    console.log("PASS: Natural Attack migration preserves existing Races, variants, Anatomy, Skill links, protection, movement, caps and Creatures; no attacks inferred");
    console.log("PASS: migration preserves exact Soak, coverage, lore and independent Races; discards Armor without conversion");
    await pool.end(); pool = null;
    const environment: NodeJS.ProcessEnv = { ...process.env, DATABASE_URL: databaseUrl, SERRIAN_DISPOSABLE_RACE_AUTHORING: "true", SERRIAN_DISPOSABLE_COMBAT_COMPLETION: "true", NODE_ENV: "test" };
    delete environment.NODE_TEST_CONTEXT;
    execFileSync(process.execPath, ["--experimental-test-module-mocks", "--conditions=react-server", "--import", "tsx", "--test", "--test-reporter=tap", "scripts/race-natural-attacks-db.test.mjs"], { env: environment, windowsHide: true, stdio: "inherit", timeout: 180_000 });
    execFileSync(process.execPath, ["--experimental-test-module-mocks", "--conditions=react-server", "--import", "tsx", "--test", "--test-reporter=tap", "scripts/race-forms-db.test.mjs"], { env: environment, windowsHide: true, stdio: "inherit", timeout: 180_000 });
    execFileSync(process.execPath, ["--experimental-test-module-mocks", "--conditions=react-server", "--import", "tsx", "--test", "--test-reporter=tap", "scripts/race-form-mechanics-db.test.mjs"], { env: environment, windowsHide: true, stdio: "inherit", timeout: 180_000 });
    execFileSync(process.execPath, ["--experimental-test-module-mocks", "--conditions=react-server", "--import", "tsx", "--test", "--test-reporter=tap", "scripts/race-form-preview-db.test.mjs"], { env: environment, windowsHide: true, stdio: "inherit", timeout: 180_000 });
    if (process.env.RACE_FORM_PREVIEW_ONLY === "1") return;
    if (process.env.RACE_NATURAL_ATTACKS_ONLY === "1" || process.env.RACE_FORMS_ONLY === "1" || process.env.RACE_FORM_MECHANICS_ONLY === "1") return;
    execFileSync(process.execPath, ["--conditions=react-server", "--import", "tsx", "scripts/race-authoring-checks.ts"], { env: environment, windowsHide: true, stdio: "inherit", timeout: 600_000 });
    execFileSync(process.execPath, ["--conditions=react-server", "--import", "tsx", "--test", "--test-concurrency=1", "scripts/incoming-effect-target-db.test.ts", "scripts/pass5-runtime-db.test.ts", "scripts/pass6-gameplay-db.test.ts"], { env: environment, windowsHide: true, stdio: "inherit", timeout: 180_000 });
  } finally {
    if (pool) await pool.end();
    if (started && existsSync(path.join(data, "postmaster.pid"))) execFileSync(exe("pg_ctl"), ["-D", data, "-m", "fast", "-w", "stop"], { stdio: "ignore", windowsHide: true });
    assert.equal(existsSync(path.join(data, "postmaster.pid")), false);
    await rm(root, { recursive: true, force: true });
  }
});
