import { captureWorldsScreenshot } from "./worlds-browser-evidence";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type pg from "pg";
import type { Browser, BrowserContext, Page } from "playwright-core";
import { draftOf, polygonCenter, type AtlasBundle, type GeographyDraft } from "../src/features/worlds/atlas";
import { terrainMarks, type TerrainDrawing } from "../src/features/worlds/cartography";
import { presetSpec } from "../src/features/worlds/generation-spec";
type Service=typeof import("../src/features/worlds/atlas-service");
type Worlds=typeof import("../src/features/worlds/world-service");
type Fixture={worldId:string;mapId:string;continentId:string};

export async function connectedGeographyServiceChecks(service:Service,worlds:Worlds,pool:pg.Pool,foreignWorld:string):Promise<Fixture> {
  const worldId=await worlds.createWorld("world-god",{name:"Aetheria connected Atlas"});
  const mapId=randomUUID();await service.changeAtlas("world-god",worldId,{action:"generate",id:mapId,name:"Aetheria world chart",description:"Continents and distant islands, ready for connected exploration.",spec:presetSpec("continental","connected-geography-3d"),sourceMapId:null,sourceRevision:null});
  let bundle=await service.getAtlas("world-god",worldId),map=bundle.maps.find(m=>m.id===mapId)!;
  const continentId=map.features.find(f=>bundle.geographies.find(g=>g.id===f.geographyId)?.kind==="continent")!.geographyId;
  const draft=draftOf(map,bundle.geographies);draft.geographies=draft.geographies.map(g=>g.id===continentId?{...g,name:"Valdoria",description:"A continent of old kingdoms and pine-covered highlands."}:g);
  await service.changeAtlas("world-god",worldId,{action:"save",id:mapId,revision:map.revision,draft});
  const region:GeographyDraft={id:randomUUID(),revision:null,name:"Service region",description:"Independent administrative location, not an extra landmass.",kind:"location",context:"region",parentId:continentId};
  await service.changeAtlas("world-god",worldId,{action:"geography",draft:region});
  const a=await service.changeAtlas("world-god",worldId,{action:"create",name:"Service detail A",description:"",scope:"regional",geographyId:region.id});
  const b=await service.changeAtlas("world-god",worldId,{action:"create",name:"Service detail B",description:"",scope:"regional",geographyId:region.id});
  bundle=await service.getAtlas("world-god",worldId);map=bundle.maps.find(m=>m.id===mapId)!;
  const oldRevision=map.revision;
  await service.changeAtlas("world-god",worldId,{action:"connect",id:mapId,revision:oldRevision,geographyId:region.id,destinationMapId:a});
  await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"connect",id:mapId,revision:oldRevision,geographyId:region.id,destinationMapId:b}),/newer/);
  bundle=await service.getAtlas("world-god",worldId);assert.equal(bundle.maps.filter(m=>m.geographyId===region.id).length,2);
  const link=bundle.connections!.find(c=>c.sourceMapId===mapId&&c.geographyId===region.id)!;assert.equal(link.destinationMapId,a);
  const destination=bundle.maps.find(m=>m.id===a)!;
  await service.changeAtlas("world-god",worldId,{action:"associate",id:a,revision:destination.revision,geographyId:continentId});assert.equal((await service.getAtlas("world-god",worldId)).connections!.find(c=>c.id===link.id)!.destinationMapId,a);await service.changeAtlas("world-god",worldId,{action:"associate",id:a,revision:destination.revision+1,geographyId:region.id});
  await service.changeAtlas("world-god",worldId,{action:"archive-map",id:a,revision:destination.revision+2});
  await assert.rejects(()=>service.getAtlas("world-god",worldId,false,a),/unavailable/);
  bundle=await service.getAtlas("world-god",worldId);assert.equal(bundle.connections!.find(c=>c.id===link.id)!.destinationMapId,a);
  await service.changeAtlas("world-god",worldId,{action:"restore-map",id:a,revision:bundle.maps.find(m=>m.id===a)!.revision});
  const foreignMap=await service.changeAtlas("other-god",foreignWorld,{action:"create",name:"Private foreign chart",description:"Secret geography must not leak",scope:"world"});
  bundle=await service.getAtlas("world-god",worldId);map=bundle.maps.find(m=>m.id===mapId)!;
  await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"connect",id:mapId,revision:map.revision,geographyId:region.id,destinationMapId:foreignMap}),/unavailable/);
  await assert.rejects(()=>service.getAtlas("world-god",worldId,false,foreignMap),/unavailable/);
  await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"associate",id:mapId,revision:map.revision,geographyId:randomUUID()}),/unavailable/);
  await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"connect",id:mapId,revision:map.revision,geographyId:region.id,destinationMapId:mapId}),/unavailable/);
  await assert.rejects(()=>pool.query("insert into world_atlas_connection(id,world_id,source_map_id,geography_id,destination_map_id) values($1,$2,$3,$4,$5)",[randomUUID(),worldId,b,region.id,foreignMap]),/foreign key/);
  await service.changeAtlas("world-god",worldId,{action:"connect",id:b,revision:1,geographyId:continentId,destinationMapId:mapId});assert.equal((await service.getAtlas("world-god",worldId)).connections!.find(c=>c.sourceMapId===b)!.destinationMapId,mapId);
  await assert.rejects(()=>pool.query("delete from world_geography where id=$1",[region.id]),/foreign key/);
  await assert.rejects(()=>pool.query("delete from world_atlas_map where id=$1",[a]),/foreign key/);
  const currentRegion=(await service.getAtlas("world-god",worldId)).geographies.find(g=>g.id===region.id)!;
  await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"geography",draft:{...region,revision:currentRegion.revision,parentId:region.id}}),/itself/);
  for(const [actor,review] of [["other-god",false],["world-admin",false],["world-player",false],["world-player",true]] as const)await assert.rejects(()=>service.getAtlas(actor,worldId,review,mapId));
  assert.equal((await service.getAtlas("world-admin",worldId,true,mapId)).canEdit,false);
  await assert.rejects(()=>service.changeAtlas("world-admin",worldId,{action:"associate",id:mapId,revision:map.revision,geographyId:continentId}));
  const partial=await service.getAtlas("world-god",worldId,false,mapId);assert.ok(partial.maps.find(m=>m.id===mapId)!.drawings!.length>10);assert.ok(partial.maps.filter(m=>m.id!==mapId).every(m=>!m.features.length&&!m.drawings!.length));
  const copy=await service.changeAtlas("world-god",worldId,{action:"duplicate",id:mapId,revision:map.revision,newId:randomUUID(),name:"Connected source copy"});const copied=(await service.getAtlas("world-god",worldId)).connections!.find(c=>c.sourceMapId===copy&&c.geographyId===region.id)!;assert.equal(copied.destinationMapId,a);assert.notEqual(copied.id,link.id);
  await service.changeAtlas("world-god",worldId,{action:"connect",id:mapId,revision:map.revision,geographyId:region.id,destinationMapId:null});
  const d=await service.changeAtlas("world-god",worldId,{action:"duplicate",id:b,revision:2,newId:randomUUID(),name:"Associated copy"});assert.equal((await service.getAtlas("world-god",worldId)).maps.find(m=>m.id===d)!.geographyId,region.id);
  console.log("PASS: connected map service: multiple destinations, revision conflicts, archive/restore retention, same-World FKs and cross-level links, unavailable guessed IDs, cycles, stable associated duplication, G.O.D./Administrator/Player authorization and single-source exploration reads.");
  return {worldId,mapId,continentId};
}

async function signIn(context:BrowserContext,url:string,id:string){const r=await context.request.post(`${url}/api/auth/sign-in/email`,{headers:{Origin:url},data:{email:`${id}@example.invalid`,password:"Worlds-Test-Only-Password!"}});assert.equal(r.status(),200,await r.text());}
async function hydrated(page:Page){await page.waitForFunction(()=>[...document.querySelectorAll("button")].some(b=>Object.keys(b).some(k=>k.startsWith("__reactProps$"))));}
export async function connectedGeographyBrowserChecks(browser:Browser,baseUrl:string,f:Fixture,pool:pg.Pool,captureDirectory="docs/screenshots/worlds-atlas-pass-3d") {
  const captures=path.resolve(captureDirectory);await mkdir(captures,{recursive:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100},hasTouch:true,extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.81"}});await signIn(context,baseUrl,"world-god");
  const page=await context.newPage(),errors:string[]=[],navigationTimings:{map:string;milliseconds:number;phone:boolean}[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("dialog",d=>d.accept());
  const api=`${baseUrl}/api/worlds/${f.worldId}/atlas`,url=`${baseUrl}/worlds/${f.worldId}`;
  async function bundle(){const r=await context.request.get(api);assert.equal(r.status(),200);return await r.json() as AtlasBundle;}
  async function post(body:unknown){const r=await context.request.post(api,{headers:{Origin:baseUrl},data:body});assert.equal(r.status(),200,await r.text());return await r.json() as {id:string};}
  async function library(){await page.goto(url);await hydrated(page);await page.getByRole("button",{name:"Atlas",exact:true}).click();await page.getByRole("heading",{name:"Atlas",exact:true}).waitFor();}
  async function shot(name:string){await page.waitForFunction(()=>{const svg=document.querySelector("svg[aria-label=\"Explorable geographic map\"]") as SVGSVGElement|null;return svg&&Math.abs(Number(svg.dataset.unitsPerPixel)-Math.max(svg.viewBox.baseVal.width/svg.clientWidth,svg.viewBox.baseVal.height/svg.clientHeight))<.05;});await page.getByRole("region",{name:"Map explorer",exact:true}).scrollIntoViewIfNeeded();await page.waitForTimeout(450);await page.evaluate(()=>{document.documentElement.style.scrollBehavior="auto";window.scrollTo({top:0,behavior:"instant"});});await page.waitForTimeout(80);await captureWorldsScreenshot(page,{path:path.join(captures,name),fullPage:true});}
  async function openChart(name:string){const start=performance.now(),title=name.replace(/^Open /,"").replace(/ \u00b7 preferred$/,"");await page.getByRole("complementary",{name:"Place information",exact:true}).getByRole("button",{name,exact:true}).click();await page.getByRole("heading",{name:title,exact:true}).waitFor();navigationTimings.push({map:title,milliseconds:Math.round((performance.now()-start)*10)/10,phone:page.viewportSize()!.width<500});assert.equal(await page.getByRole("region",{name:"Map editor",exact:true}).count(),0);}
  async function connections(name:string){await page.getByRole("button",{name:`Connect ${name}`,exact:true}).click();return page.getByRole("dialog");}
  async function prefer(source:string,place:string,destination:string){await library();const dialog=await connections(source);await dialog.getByLabel("Connecting place",{exact:true}).selectOption(place);await dialog.getByLabel("Preferred destination",{exact:true}).selectOption(destination);await dialog.getByRole("button",{name:"Save destination link",exact:true}).click();await dialog.waitFor({state:"hidden"});}
  async function newPlace(name:string,parentId:string,contextName:string){await library();await page.getByRole("button",{name:"New geography",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("Geography name",{exact:true}).fill(name);await dialog.getByLabel("Description",{exact:true}).fill(`${name} is an authored place with its own history and connected chart.`);await dialog.getByLabel("Geography kind",{exact:true}).selectOption("location");await dialog.getByLabel("Location context",{exact:true}).selectOption(contextName);await dialog.getByLabel("Parent geography",{exact:true}).selectOption(parentId);await dialog.getByRole("button",{name:"Save geography",exact:true}).click();await dialog.waitFor({state:"hidden"});return (await bundle()).geographies.find(g=>g.name===name)!.id;}
  async function newMap(name:string,scope:string,placeId:string){await library();await page.getByRole("button",{name:"New map",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("Map name",{exact:true}).fill(name);await dialog.getByLabel("Description",{exact:true}).fill("An editable cartographic representation of the same stable place.");await dialog.getByLabel("Map scale",{exact:true}).selectOption(scope);await dialog.getByLabel("Represented place",{exact:true}).selectOption(placeId);await dialog.getByRole("button",{name:"Create map",exact:true}).click();await page.getByRole("region",{name:"Map editor",exact:true}).waitFor();await page.getByRole("button",{name:"Map library",exact:true}).click();return (await bundle()).maps.find(m=>m.name===name)!.id;}
  // Connect an existing saved generated continent, rather than creating a replacement identity.
  const continentMap=await newMap("Valdoria detail","continent","");await library();const dialog=await connections("Valdoria detail");await dialog.getByLabel("Represented place",{exact:true}).selectOption(f.continentId);await dialog.getByRole("button",{name:"Save map association",exact:true}).click();await dialog.waitFor({state:"hidden"});
  const regionId=await newPlace("Kingdom of Ashenfall",f.continentId,"region"),townId=await newPlace("Grayhaven",regionId,"settlement");
  const regionMap=await newMap("Ashenfall regional chart","regional",regionId),townMap=await newMap("Grayhaven local chart","local",townId),altTown=await newMap("Grayhaven approaches","local",townId);
  // Native detailed artwork and shared markers saved through the real API, then edited again in-browser.
  let b=await bundle();const world=b.maps.find(m=>m.id===f.mapId)!;
  for(const [id,landGeo,childGeo] of [[continentMap,f.continentId,regionId],[regionMap,f.continentId,townId],[townMap,null,null]] as const){
    const m=b.maps.find(m=>m.id===id)!,draft=draftOf(m,b.geographies);draft.features=landGeo?[{...structuredClone(world.features.find(feature=>feature.geographyId===landGeo)!),id:randomUUID(),geometry:{version:1,type:"polygon",points:[[140,120],[850,90],[1620,190],[1830,800],[1470,1060],[650,1120],[160,830]].map(([x,y])=>({id:randomUUID(),x,y}))}}]:[];
    if(childGeo)draft.features.push({id:randomUUID(),geographyId:childGeo,archived:false,geometry:{version:1,type:"point",point:{x:1050,y:680}}});
    draft.drawings=structuredClone(world.drawings!.filter(d=>d.type==="terrain").slice(0,24)).map(d=>({...d,id:randomUUID()}));draft.geographies=b.geographies.filter(g=>draft.features.some(feature=>feature.geographyId===g.id)).map(g=>({id:g.id,revision:g.revision,name:g.name,description:g.description,kind:g.kind,context:g.context,parentId:g.parentId}));await post({action:"save",id,revision:m.revision,draft});b=await bundle();
  }
  await prefer("Aetheria world chart",f.continentId,continentMap);await prefer("Valdoria detail",regionId,regionMap);await prefer("Ashenfall regional chart",townId,townMap);await prefer("Grayhaven local chart",townId,f.mapId);
  // Two authoring tabs must preserve the losing preference draft and explicitly reload revisions.
  await library();const conflictDialog=await connections("Ashenfall regional chart");await conflictDialog.getByLabel("Connecting place",{exact:true}).selectOption(townId);await conflictDialog.getByLabel("Preferred destination",{exact:true}).selectOption(altTown);
  const otherTab=await context.newPage();await otherTab.goto(url);await hydrated(otherTab);await otherTab.getByRole("button",{name:"Atlas",exact:true}).click();await otherTab.getByRole("button",{name:"Connect Ashenfall regional chart",exact:true}).click();const otherDialog=otherTab.getByRole("dialog");await otherDialog.getByLabel("Connecting place",{exact:true}).selectOption(townId);await otherDialog.getByLabel("Preferred destination",{exact:true}).selectOption(altTown);await otherDialog.getByRole("button",{name:"Save destination link",exact:true}).click();await otherDialog.waitFor({state:"hidden"});
  await conflictDialog.getByRole("button",{name:"Save destination link",exact:true}).click();await conflictDialog.getByRole("alert").filter({hasText:"newer map"}).waitFor();assert.equal(await conflictDialog.getByLabel("Preferred destination",{exact:true}).inputValue(),altTown);await conflictDialog.getByRole("button",{name:"Reload saved connections",exact:true}).click();await conflictDialog.getByRole("alert").waitFor({state:"hidden"});await conflictDialog.getByLabel("Preferred destination",{exact:true}).selectOption(townMap);await conflictDialog.getByRole("button",{name:"Save destination link",exact:true}).click();await conflictDialog.waitFor({state:"hidden"});await otherTab.close();
  b=await bundle();const identities=b.geographies.map(g=>g.id).sort(),provenance=b.maps.find(m=>m.id===f.mapId)!.generation;
  await library();await page.getByRole("button",{name:"Explore Aetheria world chart",exact:true}).click();await page.getByRole("heading",{name:"Aetheria world chart",exact:true}).waitFor();await shot("world-connected.png");
  await writeFile(path.resolve("artifacts/guidance/worlds-3d-display-inspection.json"),JSON.stringify(await page.getByLabel("Explorable geographic map",{exact:true}).evaluate(node=>({matrix:(node as SVGSVGElement).getScreenCTM()?.a,viewBox:node.getAttribute("viewBox"),labels:[...node.querySelectorAll("text")].slice(0,5).map(t=>({text:t.textContent,size:t.getAttribute("font-size"),computed:getComputedStyle(t).fontSize}))})),null,2));
  // Select the actual saved SVG continent. Exploration must leave all persisted rows untouched.
  const beforeExplore=(await pool.query("select to_jsonb(m) as row from world_atlas_map m where world_id=$1 order by id",[f.worldId])).rows;
  const featureId=b.maps.find(m=>m.id===f.mapId)!.features.find(feature=>feature.geographyId===f.continentId)!.id;
  const geometry=b.maps.find(m=>m.id===f.mapId)!.features.find(feature=>feature.id===featureId)!.geometry;assert.equal(geometry.type,"polygon");const center=polygonCenter(geometry.points);
  await page.getByLabel("Explorable geographic map",{exact:true}).scrollIntoViewIfNeeded();
  const click=await page.getByLabel("Explorable geographic map",{exact:true}).evaluate((node,point)=>{const matrix=(node as SVGSVGElement).getScreenCTM()!;return {x:point.x*matrix.a+matrix.e,y:point.y*matrix.d+matrix.f};},center);assert.ok(click.y>=0&&click.y<1100,JSON.stringify(click));await page.mouse.click(click.x,click.y);
  await page.waitForURL(new RegExp(`place=${f.continentId}`));
  const panel=page.getByRole("complementary",{name:"Place information",exact:true});await panel.getByRole("heading",{name:"Valdoria",exact:true}).waitFor();await shot("continent-selection.png");
  await openChart("Open Valdoria detail · preferred");await panel.getByRole("button",{name:"Kingdom of Ashenfall",exact:true}).first().click();await openChart("Open Ashenfall regional chart · preferred");await panel.getByRole("button",{name:"Grayhaven",exact:true}).first().click();await shot("regional-towns.png");assert.equal(await panel.getByRole("button",{name:"Open Grayhaven approaches",exact:true}).count(),1);await shot("place-information.png");
  await openChart("Open Grayhaven local chart · preferred");const crumbs=page.getByRole("navigation",{name:"Geographic breadcrumbs",exact:true});assert.match(await crumbs.innerText(),/Aetheria connected Atlas[\s\S]*Valdoria[\s\S]*Kingdom of Ashenfall[\s\S]*Grayhaven/);assert.equal(await panel.getByRole("button",{name:"Open Aetheria world chart \u00b7 preferred",exact:true}).count(),1);await shot("breadcrumbs.png");
  await page.goBack();await page.getByRole("heading",{name:"Ashenfall regional chart",exact:true}).waitFor();await page.goForward();await page.getByRole("heading",{name:"Grayhaven local chart",exact:true}).waitFor();await page.reload();await page.getByRole("heading",{name:"Grayhaven local chart",exact:true}).waitFor();
  await openChart("Open Aetheria world chart \u00b7 preferred");assert.deepEqual((await pool.query("select to_jsonb(m) as row from world_atlas_map m where world_id=$1 order by id",[f.worldId])).rows,beforeExplore);
  // Request failure preserves the displayed map and pan/zoom context; retry is a real authorized read.
  await panel.getByRole("button",{name:"Valdoria",exact:true}).click();const view=await page.getByLabel("Explorable geographic map",{exact:true}).getAttribute("viewBox");await page.route(`**/api/worlds/${f.worldId}/atlas?map=${continentMap}*`,route=>route.fulfill({status:503,json:{error:"A temporary chart read failed."}}));await panel.getByRole("button",{name:"Open Valdoria detail · preferred",exact:true}).click();await page.getByRole("alert").filter({hasText:"temporary chart"}).waitFor();assert.equal(await page.getByLabel("Explorable geographic map",{exact:true}).getAttribute("viewBox"),view);await page.unrouteAll({behavior:"wait"});await page.getByRole("button",{name:"Retry map",exact:true}).click();await page.getByRole("heading",{name:"Valdoria detail",exact:true}).waitFor();
  // Source edits retain geography IDs and the persisted preferred link.
  await library();await page.getByRole("button",{name:"Open Aetheria world chart",exact:true}).click();const editor=page.getByRole("region",{name:"Map editor",exact:true});await editor.getByRole("button",{name:"Valdoria",exact:true}).click();await page.getByLabel("Feature name",{exact:true}).fill("Valdoria renamed");await page.getByRole("button",{name:"Apply geography changes",exact:true}).click();await page.getByRole("button",{name:"Move feature",exact:true}).click();await page.getByRole("button",{name:"Right",exact:true}).click();await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByText("Map saved. Your features and geography identities are preserved.",{exact:true}).waitFor();await page.getByRole("button",{name:"Explore map",exact:true}).click();await panel.getByRole("button",{name:"Valdoria renamed",exact:true}).click();await openChart("Open Valdoria detail · preferred");
  b=await bundle();assert.deepEqual(b.geographies.map(g=>g.id).sort(),identities);assert.deepEqual(b.maps.find(m=>m.id===f.mapId)!.generation,provenance);assert.equal(b.connections!.find(c=>c.sourceMapId===f.mapId&&c.geographyId===f.continentId)!.destinationMapId,continentMap);
  await library();const card=page.locator("article").filter({has:page.getByRole("heading",{name:"Valdoria detail",exact:true})});await card.getByRole("button",{name:"Archive map",exact:true}).click();await page.getByRole("button",{name:"Explore Aetheria world chart",exact:true}).click();await panel.getByRole("button",{name:"Valdoria renamed",exact:true}).click();assert.equal(await panel.getByRole("button",{name:"Open Valdoria detail · preferred",exact:true}).count(),0);await panel.getByText("Valdoria detail · archived, unavailable for exploration",{exact:true}).waitFor();
  await library();await page.getByLabel("Include archived records",{exact:true}).check();await page.locator("article").filter({has:page.getByRole("heading",{name:"Valdoria detail",exact:true})}).getByRole("button",{name:"Restore map",exact:true}).click();await page.getByRole("button",{name:"Explore Aetheria world chart",exact:true}).click();await panel.getByRole("button",{name:"Valdoria renamed",exact:true}).click();await openChart("Open Valdoria detail · preferred");
  // Read-only Administrator review traverses the same hierarchy; other actors receive no map data.
  for(const [actor,review,status] of [["other-god",false,404],["world-admin",false,404],["world-player",false,403]] as const){const denied=await browser.newContext({extraHTTPHeaders:{"X-Forwarded-For":actor==="other-god"?"203.0.113.82":actor==="world-admin"?"203.0.113.83":"203.0.113.84"}});await signIn(denied,baseUrl,actor);const deniedRead=await denied.request.get(`${api}?map=${townMap}${review?"&review=1":""}`);assert.equal(deniedRead.status(),status);assert.match(deniedRead.headers()["cache-control"],/no-store/);assert.ok(!(await deniedRead.text()).includes("Grayhaven"));const deniedPage=await denied.newPage();await deniedPage.goto(`${url}?atlas=${townMap}`);assert.equal(await deniedPage.getByRole("heading",{name:"Grayhaven local chart",exact:true}).count(),0);await denied.close();}
  const anonymous=await browser.newContext();assert.equal((await anonymous.request.get(`${api}?map=${townMap}`)).status(),401);await anonymous.close();
  const admin=await browser.newContext({viewport:{width:1440,height:1100},extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.85"}});await signIn(admin,baseUrl,"world-admin");const ap=await admin.newPage();await ap.goto(`${url}?review=1&atlas=${f.mapId}&place=${f.continentId}`);await ap.getByRole("button",{name:"Open Valdoria detail · preferred",exact:true}).click();await ap.getByRole("heading",{name:"Valdoria detail",exact:true}).waitFor();assert.equal(await ap.getByRole("button",{name:"Edit map",exact:true}).count(),0);assert.equal(await ap.getByRole("button",{name:"Edit connections",exact:true}).count(),0);assert.equal((await admin.request.post(api,{headers:{Origin:baseUrl},data:{action:"connect",id:f.mapId,revision:1,geographyId:f.continentId,destinationMapId:continentMap}})).status(),404);await admin.close();
  await page.setViewportSize({width:390,height:844});await page.goto(`${url}?atlas=${f.mapId}&place=${f.continentId}`);await page.getByRole("heading",{name:"Aetheria world chart",exact:true}).waitFor();await openChart("Open Valdoria detail · preferred");await panel.getByRole("button",{name:"Kingdom of Ashenfall",exact:true}).first().click();await openChart("Open Ashenfall regional chart · preferred");const phoneSvg=page.getByLabel("Explorable geographic map",{exact:true});await phoneSvg.scrollIntoViewIfNeeded();const townPoint=await phoneSvg.evaluate(node=>{const matrix=(node as SVGSVGElement).getScreenCTM()!;return {x:1050*matrix.a+matrix.e,y:680*matrix.d+matrix.f};});await page.touchscreen.tap(townPoint.x,townPoint.y);await panel.getByRole("heading",{name:"Grayhaven",exact:true}).waitFor();
  await phoneSvg.evaluate(node=>node.scrollIntoView({block:"center",behavior:"instant"}));const panPoint=await phoneSvg.evaluate(node=>{const rect=node.getBoundingClientRect();return {x:rect.x+rect.width/2,y:rect.y+rect.height/2};});
  assert.ok(await phoneSvg.evaluate((node,point)=>document.elementFromPoint(point.x,point.y)?.closest("svg")===node,panPoint),JSON.stringify(panPoint));
  await page.evaluate(`(() => {window.atlasTouchTrace=[];for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>window.atlasTouchTrace.push({type:e.type,button:e.button,primary:e.isPrimary,x:e.clientX,y:e.clientY,target:e.target.closest('svg')?.getAttribute('aria-label')}),true);})()`);
  const beforePan=await phoneSvg.getAttribute("viewBox"),session=await context.newCDPSession(page);await session.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{id:1,x:panPoint.x-30,y:panPoint.y-20}]});await page.waitForTimeout(40);await session.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{id:1,x:panPoint.x-10,y:panPoint.y-10}]});await page.waitForTimeout(40);await session.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{id:1,x:panPoint.x+15,y:panPoint.y}]});await page.waitForTimeout(40);await session.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await session.detach();await writeFile(path.resolve("artifacts/guidance/worlds-3d-touch-trace.json"),JSON.stringify({panPoint,events:await page.evaluate("window.atlasTouchTrace")},null,2));await page.waitForFunction(previous=>document.querySelector("svg[aria-label=\"Explorable geographic map\"]")?.getAttribute("viewBox")!==previous,beforePan,{timeout:5000});assert.notEqual(await phoneSvg.getAttribute("viewBox"),beforePan);await page.getByRole("button",{name:"Fit map",exact:true}).click();await shot("phone-region.png");await openChart("Open Grayhaven local chart · preferred");await shot("phone-town.png");assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole("button",{name:"Previous map",exact:true}).click();await page.getByRole("heading",{name:"Ashenfall regional chart",exact:true}).waitFor();await openChart("Open Aetheria world chart");
  await page.getByRole("button",{name:"Edit connections",exact:true}).click();await page.getByLabel("Connecting place",{exact:true}).selectOption(f.continentId);await captureWorldsScreenshot(page,{path:path.join(captures,"phone-connections.png"),fullPage:false});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole("button",{name:"Close connections",exact:true}).click();
  // Browse a separate connected copy near the native terrain budget, keeping the normal chart readable.
  await page.setViewportSize({width:1440,height:1100});const denseBundle=await bundle(),denseMap=denseBundle.maps.find(m=>m.name==="Connected source copy")!,denseDraft=draftOf(denseMap,denseBundle.geographies);
  let denseMarks=(denseDraft.drawings??[]).filter(d=>d.type==="terrain").reduce((n,d)=>n+terrainMarks(d).length,0);
  for(let i=0;denseMarks<5000;i++){const stroke:TerrainDrawing={version:1,id:randomUUID(),name:`Exploration stress woodland ${i}`,archived:false,geographyId:null,type:"terrain",kind:i%3?"forest":"hills",points:[{id:randomUUID(),x:550,y:500+i%8*12},{id:randomUUID(),x:1000,y:620+i%8*12},{id:randomUUID(),x:1380,y:660+i%8*12}],radius:55,spacing:12,density:3,seed:10000+i};denseDraft.drawings!.push(stroke);denseMarks+=terrainMarks(stroke).length;}
  assert.ok(denseMarks<=5500);await post({action:"save",id:denseMap.id,revision:denseMap.revision,draft:denseDraft});await post({action:"connect",id:denseMap.id,revision:denseMap.revision+1,geographyId:f.continentId,destinationMapId:continentMap});
  const denseStart=performance.now();await page.goto(`${url}?atlas=${denseMap.id}&place=${f.continentId}`);await page.getByRole("heading",{name:denseMap.name,exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('[data-terrain-cache-ready]').length>30);const denseOpenMilliseconds=Math.round((performance.now()-denseStart)*10)/10;assert.equal(await page.locator('[data-terrain-mark]').count(),denseMarks);await shot("dense-exploration.png");await openChart("Open Valdoria detail \u00b7 preferred");
  assert.deepEqual(errors,[]);await writeFile(path.join(captures,"navigation.json"),JSON.stringify({sourceMaps: (await bundle()).maps.length,generatedTerrainStrokes:world.drawings!.filter(d=>d.type==="terrain").length,denseExplorer:{marks:denseMarks,openingAndCacheWarmMilliseconds:denseOpenMilliseconds},nativeTerrainMarks:world.drawings!.filter(d=>d.type==="terrain").reduce((n,d)=>n+terrainMarks(d).length,0),navigationTimings,linkedLevels:4,desktop:[1440,1100],phone:[390,844],browserBackForward:true,sameWorldAuthorization:true},null,2)+"\n");await context.close();
  console.log("PASS: production connected Atlas browser workflow: saved generated World → same continent → authored region → town, multiple charts, breadcrumbs/deep reload/back/forward, read failure recovery, source rename/move persistence, archive/restore and desktop/phone privacy review.");
}
