import { captureWorldsScreenshot } from "./worlds-browser-evidence";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import path from "node:path";
import type pg from "pg";
import type { BrowserContext, Page } from "playwright-core";
import { draftOf, moveGeometry, type AtlasBundle, type GeographyDraft, type MapDraft } from "../src/features/worlds/atlas";
type Service=typeof import("../src/features/worlds/atlas-service");
type Worlds=typeof import("../src/features/worlds/world-service");
const polygon=()=>({version:1 as const,type:"polygon" as const,points:[[100,100],[600,100],[600,600],[100,600]].map(([x,y])=>({id:randomUUID(),x,y}))});
export async function atlasServiceChecks(service:Service,worlds:Worlds,pool:pg.Pool,foreignWorld:string) {
  const worldId=await worlds.createWorld("world-god",{name:"Atlas workshop rehearsal"});
  const a=await service.changeAtlas("world-god",worldId,{action:"create",name:"Service chart",description:"A persisted blank",scope:"world"});
  const b=await service.changeAtlas("world-god",worldId,{action:"create",name:"Second chart",description:"Independent geometry",scope:"regional"});
  let bundle=await service.getAtlas("world-god",worldId);assert.equal(bundle.maps.length,2);assert.equal(bundle.maps[0].features.length,0);
  const id=randomUUID(),geoId=randomUUID(),geo:GeographyDraft={id:geoId,revision:null,name:"Service continent",description:"Stable climate and history",kind:"continent",parentId:null};
  let map=bundle.maps.find(m=>m.id===a)!,draft:MapDraft={...draftOf(map,bundle.geographies),features:[{id,geographyId:geoId,geometry:polygon(),archived:false}],geographies:[geo]};
  await service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision,draft});bundle=await service.getAtlas("world-god",worldId);map=bundle.maps.find(m=>m.id===a)!;assert.equal(map.features[0].geographyId,geoId);assert.equal(bundle.maps.find(m=>m.id===b)!.revision,1);
  draft=draftOf(map,bundle.geographies);draft.features[0].geometry=moveGeometry(draft.features[0].geometry,20,30);const races=await Promise.allSettled([service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision,draft}),service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision,draft})]);assert.equal(races.filter(r=>r.status==="fulfilled").length,1);assert.equal(races.filter(r=>r.status==="rejected").length,1);
  bundle=await service.getAtlas("world-god",worldId);map=bundle.maps.find(m=>m.id===a)!;const clean=structuredClone(bundle);const bad=draftOf(map,bundle.geographies);bad.geographies[0].name="Must roll back";bad.features[0].geometry={version:1,type:"polygon",points:polygon().points.map(p=>({...p,x:0,y:0}))};await assert.rejects(service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision,draft:bad}),/area|distinct/);assert.deepEqual(await service.getAtlas("world-god",worldId),clean);
  await assert.rejects(service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision,draft:{...draftOf(map,bundle.geographies),features:[]}}),/Keep saved features/);
  const parent=randomUUID();await service.changeAtlas("world-god",worldId,{action:"geography",draft:{id:parent,revision:null,name:"Parent continent",description:"",kind:"continent",parentId:null}});const g=bundle.geographies.find(g=>g.id===geoId)!;await service.changeAtlas("world-god",worldId,{action:"geography",draft:{id:g.id,revision:g.revision,name:g.name,description:g.description,kind:g.kind,parentId:parent}});
  await assert.rejects(service.changeAtlas("world-god",worldId,{action:"geography",draft:{id:parent,revision:1,name:"Parent continent",description:"",kind:"continent",parentId:geoId}}),/contain itself/);
  await assert.rejects(pool.query("update world_geography set parent_id=$1 where id=$2",[geoId,parent]),/cycle/);
  const foreignGeo=randomUUID();await service.changeAtlas("other-god",foreignWorld,{action:"geography",draft:{id:foreignGeo,revision:null,name:"Secret foreign continent",description:"Private",kind:"continent",parentId:null}});
  await assert.rejects(service.changeAtlas("world-god",worldId,{action:"geography",draft:{...geo,id:randomUUID(),parentId:foreignGeo}}),/this World/);
  await assert.rejects(pool.query("insert into world_atlas_feature(id,world_id,map_id,geography_id,geometry) values($1,$2,$3,$4,$5)",[randomUUID(),worldId,a,foreignGeo,polygon()]),/foreign key/);
  await assert.rejects(pool.query("update world_geography set parent_id=$1 where id=$2",[foreignGeo,geoId]),/foreign key/);
  const foreignMap=await service.changeAtlas("other-god",foreignWorld,{action:"create",name:"Secret foreign map",description:"",scope:"local"});
  await assert.rejects(pool.query("insert into world_atlas_feature(id,world_id,map_id,geography_id,geometry) values($1,$2,$3,$4,$5)",[randomUUID(),worldId,foreignMap,geoId,polygon()]),/foreign key/);
  bundle=await service.getAtlas("world-god",worldId);map=bundle.maps.find(m=>m.id===a)!;const attempt=draftOf(map,bundle.geographies);attempt.features.push({id:randomUUID(),geographyId:foreignGeo,geometry:polygon(),archived:false});await assert.rejects(service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision,draft:attempt}),/newer|unavailable/);
  for(const geometry of [{version:1,type:"point",point:{x:2001,y:1}},{version:1,type:"point",point:{x:null,y:1}},{version:1,type:"polygon",points:polygon().points.map(p=>({...p,x:0,y:0}))}])await assert.rejects(pool.query("insert into world_atlas_feature(id,world_id,map_id,geography_id,geometry) values($1,$2,$3,$4,$5)",[randomUUID(),worldId,a,geoId,geometry]),/check constraint/);
  await assert.rejects(pool.query('delete from "user" where id=$1',["world-god"]),/foreign key/);
  for(const userId of ["other-god","world-admin"]){await assert.rejects(service.getAtlas(userId,worldId),/unavailable/);await assert.rejects(service.changeAtlas(userId,worldId,{action:"create",name:"Forbidden",description:"",scope:"world"}),/unavailable/);}
  await assert.rejects(service.getAtlas("world-player",worldId),/access/);assert.equal((await service.getAtlas("world-admin",worldId,true)).canEdit,false);
  bundle=await service.getAtlas("world-god",worldId);map=bundle.maps.find(m=>m.id===a)!;const current=draftOf(map,bundle.geographies);current.features[0].archived=true;await service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision,draft:current});bundle=await service.getAtlas("world-god",worldId);assert.equal(bundle.maps.find(m=>m.id===a)!.features[0].archived,true);assert.equal(bundle.geographies.find(g=>g.id===geoId)!.archived,false);
  await assert.rejects(service.changeAtlas("world-god",worldId,{action:"archive-geography",id:geoId,revision:bundle.geographies.find(g=>g.id===geoId)!.revision}),/linked/);
  const unused=randomUUID();await service.changeAtlas("world-god",worldId,{action:"geography",draft:{...geo,id:unused,name:"Unmapped island",kind:"island"}});await service.changeAtlas("world-god",worldId,{action:"archive-geography",id:unused,revision:1});await service.changeAtlas("world-god",worldId,{action:"restore-geography",id:unused,revision:2});
  map=bundle.maps.find(m=>m.id===a)!;await service.changeAtlas("world-god",worldId,{action:"archive-map",id:a,revision:map.revision});await assert.rejects(service.changeAtlas("world-god",worldId,{action:"save",id:a,revision:map.revision+1,draft:current}),/Restore/);await service.changeAtlas("world-god",worldId,{action:"restore-map",id:a,revision:map.revision+1});assert.equal((await service.getAtlas("world-god",worldId)).maps.find(m=>m.id===a)!.features[0].id,id);
  const world=await worlds.getWorld("world-god",worldId);await worlds.changeWorld("world-god",worldId,{action:"archive",revision:world.world.revision});await assert.rejects(service.changeAtlas("world-god",worldId,{action:"create",name:"Blocked",description:"",scope:"world"}),/Restore this world/);await worlds.changeWorld("world-god",worldId,{action:"restore",revision:world.world.revision+1});
  console.log("PASS: Atlas blank/multiple maps, stable editable geometry, atomic invalid-save rollback, CAS races, hierarchy cycles, cross-world FKs, owner/Admin/Player isolation, account-deletion safeguards and map/feature/geography archives.");
  return {worldId,foreignMap,foreignGeo};
}
async function openAtlas(page:Page,url:string){await page.goto(url);await page.getByRole("button",{name:"Atlas",exact:true}).click();await page.getByRole("heading",{name:"Atlas",exact:true}).waitFor();}
async function screenPoint(page:Page,x:number,y:number){const canvas=page.getByRole("application",{name:"Editable map canvas"});await canvas.scrollIntoViewIfNeeded();return canvas.evaluate((node,p)=>{const matrix=(node as SVGSVGElement).getScreenCTM()!;const result=new DOMPoint(p.x,p.y).matrixTransform(matrix);return {x:result.x,y:result.y};},{x,y});}
async function clickPoint(page:Page,x:number,y:number){const p=await screenPoint(page,x,y);await page.mouse.click(p.x,p.y);}
async function save(page:Page){await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByText("Map saved. Your features and geography identities are preserved.",{exact:true}).waitFor();}
async function rename(page:Page,name:string){await page.getByLabel("Feature name",{exact:true}).fill(name);await page.getByRole("button",{name:"Apply geography changes",exact:true}).click();}
export async function atlasBrowserChecks(page:Page,god:BrowserContext,url:string,fixture:{worldId:string},artifacts:string) {
  const api=`${url}/api/worlds/${fixture.worldId}/atlas`,worldUrl=`${url}/worlds/${fixture.worldId}`;
  const read=async()=>{const r=await god.request.get(api);assert.equal(r.status(),200);return await r.json() as AtlasBundle;};
  await openAtlas(page,worldUrl);await page.getByRole("button",{name:"New map",exact:true}).click();await page.getByLabel("Map name",{exact:true}).fill("The Northern Seas");await page.getByLabel("Description",{exact:true}).fill("Coastlines, islands and remembered places");await page.getByRole("button",{name:"Create map",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();
  await page.getByRole("button",{name:"Draw landmass",exact:true}).click();for(const [x,y] of [[350,250],[650,190],[820,380],[700,650],[380,680],[250,480]])await clickPoint(page,x,y);await page.getByRole("button",{name:"Close outline",exact:true}).click();await rename(page,"Valdoria");await save(page);
  let bundle=await read(),map=bundle.maps.find(m=>m.name==="The Northern Seas")!,continent=map.features[0];const identity={id:continent.id,geographyId:continent.geographyId};assert.equal(continent.geometry.type,"polygon");
  await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await save(page);assert.equal((await read()).maps.find(m=>m.id===map.id)!.features.find(f=>f.id===identity.id)!.archived,true);await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();await save(page);const redone=(await read()).maps.find(m=>m.id===map.id)!.features.find(f=>f.id===identity.id)!;assert.equal(redone.archived,false);assert.equal(redone.geographyId,identity.geographyId);
  // The mandatory real reopen/reshape regression: same saved feature and geography.
  await page.reload();await page.getByRole("button",{name:"Atlas",exact:true}).click();await page.getByRole("button",{name:"Open The Northern Seas",exact:true}).click();await page.getByRole("button",{name:"Valdoria",exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Boundary point",{exact:true}).selectOption({index:1});
  await page.getByLabel("Point X",{exact:true}).fill("365");await page.getByLabel("Point Y",{exact:true}).fill("260");await page.getByRole("button",{name:"Apply point position",exact:true}).click();await save(page);await page.reload();await page.getByRole("button",{name:"Atlas",exact:true}).click();await page.getByRole("button",{name:"Open The Northern Seas",exact:true}).click();bundle=await read();map=bundle.maps.find(m=>m.id===map.id)!;continent=map.features.find(f=>f.id===identity.id)!;assert.equal(continent.geographyId,identity.geographyId);assert.equal(continent.geometry.type,"polygon");if(continent.geometry.type!=="polygon")throw new Error("Missing polygon");assert.deepEqual({x:continent.geometry.points[0].x,y:continent.geometry.points[0].y},{x:365,y:260});assert.equal(bundle.geographies.find(g=>g.id===identity.geographyId)!.name,"Valdoria");
  console.log("PASS: mandatory blank map -> draw continent -> save -> page reload -> select SAME continent -> edit coastline vertex -> save -> reload retains changed geometry and stable geographic identity.");
  await page.getByRole("button",{name:"Valdoria",exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Boundary point",{exact:true}).selectOption({index:1});await page.getByRole("button",{name:"Add point after",exact:true}).click();assert.equal(await page.getByLabel("Boundary point",{exact:true}).locator("option").count(),8);await page.getByRole("button",{name:"Remove point",exact:true}).click();assert.equal(await page.getByLabel("Boundary point",{exact:true}).locator("option").count(),7);await page.getByRole("button",{name:"Undo",exact:true}).click();assert.equal(await page.getByLabel("Boundary point",{exact:true}).locator("option").count(),8);await page.getByRole("button",{name:"Redo",exact:true}).click();assert.equal(await page.getByLabel("Boundary point",{exact:true}).locator("option").count(),7);
  await page.getByRole("button",{name:"Move feature",exact:true}).click();const start=await screenPoint(page,500,400);await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(start.x+12,start.y+8,{steps:6});await page.mouse.up();await save(page);const moved=(await read()).maps.find(m=>m.id===map.id)!.features.find(f=>f.id===identity.id)!;assert.notDeepEqual(moved.geometry,continent.geometry);
  const navigationBefore=JSON.stringify(moved.geometry);await page.getByRole("button",{name:"Select",exact:true}).click();await clickPoint(page,500,400);await page.getByRole("button",{name:"Pan",exact:true}).click();const pan=await screenPoint(page,500,400);await page.mouse.move(pan.x,pan.y);await page.mouse.down();await page.mouse.move(pan.x+35,pan.y+15,{steps:5});await page.mouse.up();await page.getByRole("button",{name:"Zoom in",exact:true}).click();await page.getByRole("button",{name:"Zoom out",exact:true}).click();await page.getByRole("button",{name:"Fit map",exact:true}).click();assert.equal(JSON.stringify((await read()).maps.find(m=>m.id===map.id)!.features.find(f=>f.id===identity.id)!.geometry),navigationBefore);assert.equal(await page.getByRole("button",{name:"Save map",exact:true}).isEnabled(),false);
  await page.getByRole("button",{name:"Zoom in",exact:true}).click();await page.getByRole("button",{name:"Draw landmass",exact:true}).click();await page.getByLabel("Landmass kind",{exact:true}).selectOption("island");for(const [x,y] of [[1100,450],[1300,430],[1350,620],[1150,650]])await clickPoint(page,x,y);await page.getByRole("button",{name:"Close outline",exact:true}).click();await rename(page,"Amber Isle");await save(page);const zoomBundle=await read(),zoomMap=zoomBundle.maps.find(m=>m.id===map.id)!,islandGeo=zoomBundle.geographies.find(g=>g.name==="Amber Isle")!,island=zoomMap.features.find(f=>f.geographyId===islandGeo.id)!;if(island.geometry.type!=="polygon")throw new Error("Expected the island outline");assert.deepEqual({x:island.geometry.points[0].x,y:island.geometry.points[0].y},{x:1100,y:450},"Zoomed mouse input must preserve logical coordinates.");await page.getByRole("button",{name:"Fit map",exact:true}).click();
  await page.getByRole("button",{name:"Place location",exact:true}).click();await clickPoint(page,500,400);await rename(page,"Dawnwatch");await save(page);assert.equal((await read()).maps.find(m=>m.id===map.id)!.features.length,3);
  await page.getByRole("button",{name:"Valdoria",exact:true}).click();await page.getByRole("button",{name:"Move feature",exact:true}).click();await page.getByRole("button",{name:"Right",exact:true}).click();const failRoute="**/api/worlds/*/atlas";await page.route(failRoute,async route=>route.request().method()==="POST"?route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Atlas failure rehearsal. Your draft is retained."})}):route.continue());await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByText(/Atlas failure rehearsal/).waitFor();assert.equal(await page.getByText("Unsaved changes",{exact:true}).count(),1);await page.unroute(failRoute);await save(page);
  const second=await god.newPage();await openAtlas(second,worldUrl);await second.getByRole("button",{name:"Open The Northern Seas",exact:true}).click();await second.getByRole("button",{name:"Valdoria",exact:true}).click();await second.getByRole("button",{name:"Move feature",exact:true}).click();await second.getByRole("button",{name:"Right",exact:true}).click();await save(second);await page.getByRole("button",{name:"Left",exact:true}).click();await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByText(/A newer map or geography/).waitFor();assert.equal(await page.getByText("Unsaved changes",{exact:true}).count(),1);await page.getByRole("button",{name:"Load saved map to compare",exact:true}).click();await page.getByRole("heading",{name:/Saved map · revision/}).waitFor();page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Use saved map",exact:true}).click();assert.equal(await page.getByRole("button",{name:"Save map",exact:true}).isEnabled(),false);await second.close();
  await page.getByRole("button",{name:"Valdoria",exact:true}).click();await page.getByLabel("Geographic description",{exact:true}).fill("An unapplied information draft");assert.equal(await page.getByRole("button",{name:"Save map",exact:true}).isEnabled(),false);page.once("dialog",d=>d.dismiss());await page.getByRole("button",{name:"Select",exact:true}).click();assert.equal(await page.getByLabel("Geographic description",{exact:true}).inputValue(),"An unapplied information draft");await page.getByRole("button",{name:"Apply geography changes",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();assert.equal(await page.getByLabel("Geographic description",{exact:true}).inputValue(),"");
  await page.getByRole("application",{name:"Editable map canvas"}).scrollIntoViewIfNeeded();await captureWorldsScreenshot(page,{path:path.join(artifacts,"worlds-atlas-editor-desktop.png"),fullPage:true});
  const phone=await god.browser()!.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,storageState:await god.storageState()});const mobile=await phone.newPage();mobile.on("pageerror",error=>{throw error;});await openAtlas(mobile,worldUrl);await mobile.getByRole("button",{name:"Open The Northern Seas",exact:true}).click();await mobile.getByRole("button",{name:"Valdoria",exact:true}).click();await mobile.getByRole("button",{name:"Edit points",exact:true}).click();await mobile.getByLabel("Boundary point",{exact:true}).selectOption({index:1});await mobile.getByRole("button",{name:"Right",exact:true}).tap();await mobile.getByRole("button",{name:"Add point after",exact:true}).tap();await mobile.getByRole("button",{name:"Undo",exact:true}).tap();await mobile.getByRole("button",{name:"Redo",exact:true}).tap();await save(mobile);
  const cdp=await phone.newCDPSession(mobile);await mobile.getByRole("button",{name:"Move feature",exact:true}).tap();const touch=await screenPoint(mobile,620,400);await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[touch]});await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:touch.x+8,y:touch.y+5}]});await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await save(mobile);
  await mobile.getByRole("button",{name:"Valdoria",exact:true}).tap();await mobile.getByRole("button",{name:"Edit points",exact:true}).tap();await mobile.locator("g[data-vertex]").first().waitFor({state:"visible"});const touchMap=(await read()).maps.find(m=>m.id===map.id)!,touchFeature=touchMap.features.find(f=>f.id===identity.id)!;if(touchFeature.geometry.type!=="polygon")throw new Error("Expected the continent");const firstPoint=touchFeature.geometry.points[0],pointTouch=await screenPoint(mobile,firstPoint.x,firstPoint.y);await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[pointTouch]});await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:pointTouch.x+3,y:pointTouch.y+4}]});await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await save(mobile);const reshaped=(await read()).maps.find(m=>m.id===map.id)!.features.find(f=>f.id===identity.id)!;assert.notDeepEqual(reshaped.geometry,touchFeature.geometry);if(reshaped.geometry.type!=="polygon")throw new Error("Expected the same continent");assert.equal(reshaped.geometry.points[0].id,firstPoint.id);
  await mobile.getByRole("button",{name:"Pan",exact:true}).tap();const panTouch=await screenPoint(mobile,500,400);await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[panTouch]});await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:panTouch.x+12,y:panTouch.y+10}]});await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});assert.equal(await mobile.getByRole("button",{name:"Save map",exact:true}).isEnabled(),false);await mobile.getByRole("button",{name:"Fit map",exact:true}).tap();await mobile.getByRole("button",{name:"Place location",exact:true}).tap();const spot=await screenPoint(mobile,1500,800);await mobile.touchscreen.tap(spot.x,spot.y);await rename(mobile,"Island Light");await save(mobile);const phoneBundle=await read(),phoneMap=phoneBundle.maps.find(m=>m.id===map.id)!,lightGeo=phoneBundle.geographies.find(g=>g.name==="Island Light")!,light=phoneMap.features.find(f=>f.geographyId===lightGeo.id)!;assert.deepEqual(light.geometry,{version:1,type:"point",point:{x:1500,y:800}},"Touch input after resizing must preserve logical coordinates.");assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const labelBounds=await mobile.getByRole("application",{name:"Editable map canvas"}).evaluate(node=>({text:[...node.querySelectorAll("text[data-geography-label]")].map(e=>{const b=e.getBoundingClientRect();return {left:b.left,right:b.right,top:b.top,bottom:b.bottom};}),markers:[...node.querySelectorAll('[data-place-art]')].map(e=>{const b=e.getBoundingClientRect();return {left:b.left,right:b.right,top:b.top,bottom:b.bottom};})}));assert.ok(labelBounds.text.length>0&&labelBounds.markers.length>0,"Actual labels and illustrated location markers must be measured.");for(const label of labelBounds.text)for(const marker of labelBounds.markers)assert.ok(label.right<=marker.left||label.left>=marker.right||label.bottom<=marker.top||label.top>=marker.bottom,"Phone labels must not be obscured by location markers.");await mobile.getByRole("application",{name:"Editable map canvas"}).scrollIntoViewIfNeeded();await captureWorldsScreenshot(mobile,{path:path.join(artifacts,"worlds-atlas-editor-mobile.png"),fullPage:true});await captureWorldsScreenshot(mobile.getByRole("application",{name:"Editable map canvas"}).locator(".."),{path:path.join(artifacts,"worlds-atlas-canvas-mobile.png")});await captureWorldsScreenshot(mobile.getByRole("complementary",{name:"Geographic information",exact:true}),{path:path.join(artifacts,"worlds-atlas-information-mobile.png")});await phone.close();
  await page.reload();await page.getByRole("button",{name:"Atlas",exact:true}).click();await page.getByRole("button",{name:"Open The Northern Seas",exact:true}).click();await page.getByRole("button",{name:"Amber Isle",exact:true}).click();page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Archive feature",exact:true}).click();await save(page);assert.equal((await read()).maps.find(m=>m.id===map.id)!.features.filter(f=>f.archived).length,1);page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Restore feature",exact:true}).click();await save(page);
  await page.getByRole("button",{name:"Move feature",exact:true}).click();await page.getByRole("button",{name:"Right",exact:true}).click();page.once("dialog",d=>d.dismiss());await page.getByRole("button",{name:"Map library",exact:true}).click();assert.equal(await page.getByRole("application",{name:"Editable map canvas"}).count(),1);page.once("dialog",d=>d.dismiss());await page.getByRole("button",{name:"History 0",exact:true}).click();assert.equal(await page.getByRole("application",{name:"Editable map canvas"}).count(),1);await save(page);await page.getByRole("button",{name:"Map library",exact:true}).click();await captureWorldsScreenshot(page,{path:path.join(artifacts,"worlds-atlas-library-desktop.png"),fullPage:true});const beforeArchive=(await read()).maps.find(m=>m.id===map.id)!;page.once("dialog",d=>d.accept());await page.getByRole("article").filter({has:page.getByRole("heading",{name:"The Northern Seas",exact:true})}).getByRole("button",{name:"Archive map",exact:true}).click();await page.getByLabel("Include archived records",{exact:true}).check();await page.getByRole("button",{name:"Open The Northern Seas",exact:true}).waitFor();assert.equal((await read()).maps.find(m=>m.id===map.id)!.archived,true);page.once("dialog",d=>d.accept());await page.getByRole("article").filter({has:page.getByRole("heading",{name:"The Northern Seas",exact:true})}).getByRole("button",{name:"Restore map",exact:true}).click();const restored=(await read()).maps.find(m=>m.id===map.id)!;assert.deepEqual(restored.features,beforeArchive.features);
  await page.getByRole("button",{name:"New geography",exact:true}).click();await page.getByLabel("Geography name",{exact:true}).fill("Acknowledged geography");let failReload=true;await page.route("**/api/worlds/*/atlas",async route=>{if(route.request().method()==="GET"&&failReload){failReload=false;await route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({error:"Readback failure rehearsal"})});}else await route.continue();});await page.getByRole("button",{name:"Save geography",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});await page.getByText(/Saved successfully.*Readback failure/).waitFor();assert.equal((await read()).geographies.filter(g=>g.name==="Acknowledged geography").length,1);await page.unroute("**/api/worlds/*/atlas");await page.getByRole("button",{name:"Reload Atlas",exact:true}).click();await page.getByRole("heading",{name:"Acknowledged geography",exact:true}).waitFor();
  console.log("PASS: Atlas actual mouse/touch drawing, move/point editing, zoom coordinate transforms, resize, undo/redo, location placement, failed draft retention, real two-tab conflict comparison, navigation/unapplied-field guards, acknowledged-save readback recovery, label/marker bounds and archive/restore; desktop/phone functional checks.");
  return {worldId:fixture.worldId,mapId:map.id};
}
