import { captureWorldsScreenshot } from "./worlds-browser-evidence";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import type pg from "pg";
import type { Browser, Page } from "playwright-core";
import { draftOf, type AtlasBundle } from "../src/features/worlds/atlas";
import { defaultPresentation, terrainKinds, type MapDrawing } from "../src/features/worlds/cartography";
type Service=typeof import("../src/features/worlds/atlas-service");
type Fixture={worldId:string;mapId:string;featureId:string;geographyId:string};
const points=()=>[[400,350],[700,450]].map(([x,y])=>({id:randomUUID(),x,y}));
export async function cartographyServiceChecks(service:Service,pool:pg.Pool,f:Fixture,foreignWorld:string) {
  const old=await service.getAtlas("other-god",f.worldId),map=old.maps.find(m=>m.id===f.mapId)!;
  assert.equal(map.drawings!.length,0);assert.deepEqual(map.presentation,defaultPresentation());assert.equal(map.features[0].id,f.featureId);assert.equal(map.features[0].geographyId,f.geographyId);
  const testMap=await service.changeAtlas("other-god",f.worldId,{action:"create",name:"Drawing validation",description:"",scope:"regional"});
  const terrain:MapDrawing={version:1,id:"ffffffff-ffff-4fff-8fff-ffffffffffff",name:"Range",type:"terrain",kind:"mountains",points:points(),radius:55,spacing:40,density:2,seed:123,geographyId:null,archived:false};
  const river:MapDrawing={version:1,id:"00000000-0000-4000-8000-000000000001",name:"River",type:"path",kind:"river",points:points(),width:5,curve:.8,geographyId:null,archived:false};
  let bundle=await service.getAtlas("other-god",f.worldId),current=bundle.maps.find(m=>m.id===testMap)!;const draft=draftOf(current,bundle.geographies);draft.drawings=[terrain,river];await service.changeAtlas("other-god",f.worldId,{action:"save",id:testMap,revision:current.revision,draft});
  bundle=await service.getAtlas("other-god",f.worldId);current=bundle.maps.find(m=>m.id===testMap)!;assert.equal(current.drawings!.length,2);assert.deepEqual(current.drawings!.map(d=>d.id),[terrain.id,river.id],"Drawing stack order survives a save and readback.");const clean=structuredClone(bundle),bad=draftOf(current,bundle.geographies);bad.name="Atomic rollback";bad.drawings![0]={...terrain,points:[{...points()[0],x:2001}]};await assert.rejects(service.changeAtlas("other-god",f.worldId,{action:"save",id:testMap,revision:current.revision,draft:bad}));assert.deepEqual(await service.getAtlas("other-god",f.worldId),clean);
  await assert.rejects(service.changeAtlas("other-god",f.worldId,{action:"save",id:testMap,revision:current.revision,draft:{...draftOf(current,bundle.geographies),drawings:undefined}}),/Keep saved drawings/);
  const foreignGeo=(await pool.query("select id from world_geography where world_id=$1 limit 1",[foreignWorld])).rows[0].id;
  const forged={...river,id:randomUUID(),geographyId:foreignGeo};await assert.rejects(service.changeAtlas("other-god",f.worldId,{action:"save",id:testMap,revision:current.revision,draft:{...draftOf(current,bundle.geographies),drawings:[...current.drawings!,forged]}}),/unavailable/);
  await assert.rejects(pool.query("insert into world_atlas_drawing(id,world_id,map_id,geography_id,content) values($1,$2,$3,$4,$5)",[forged.id,f.worldId,testMap,foreignGeo,forged]),/foreign key/);
  const foreignMap=(await pool.query("select id from world_atlas_map where world_id=$1 limit 1",[foreignWorld])).rows[0].id;
  const cross={...terrain,id:randomUUID()};await assert.rejects(pool.query("insert into world_atlas_drawing(id,world_id,map_id,content) values($1,$2,$3,$4)",[cross.id,f.worldId,foreignMap,cross]),/foreign key/);
  for(const value of [{...terrain,points:[{id:randomUUID(),x:null,y:2}]},{...terrain,points:[{id:randomUUID(),y:2}]},{...terrain,density:0},{...terrain,radius:"55"},{...terrain,spacing:0},{...river,points:[]},{...terrain,extra:"<script>"},{...terrain,geographyId:f.geographyId}]){const content={...value,id:randomUUID()};await assert.rejects(pool.query("insert into world_atlas_drawing(id,world_id,map_id,content) values($1,$2,$3,$4)",[content.id,f.worldId,testMap,content]),/check constraint/);}
  await assert.rejects(pool.query("update world_atlas_map set presentation=$1 where id=$2",[{...defaultPresentation(),layers:{land:{visible:true}}},testMap]),/check constraint/);
  const modified=draftOf(current,bundle.geographies);modified.drawings![0]={...terrain,kind:"forest",density:1};const races=await Promise.allSettled([service.changeAtlas("other-god",f.worldId,{action:"save",id:testMap,revision:current.revision,draft:modified}),service.changeAtlas("other-god",f.worldId,{action:"save",id:testMap,revision:current.revision,draft:modified})]);assert.equal(races.filter(r=>r.status==="fulfilled").length,1);
  for(const user of ["world-god","world-admin","world-player"]){await assert.rejects(service.getAtlas(user,f.worldId));await assert.rejects(service.changeAtlas(user,f.worldId,{action:"save",id:testMap,revision:1,draft:modified}));}assert.equal((await service.getAtlas("world-admin",f.worldId,true)).canEdit,false);
  bundle=await service.getAtlas("other-god",f.worldId);current=bundle.maps.find(m=>m.id===testMap)!;const kinds=terrainKinds.map(kind=>({...terrain,id:randomUUID(),name:kind,kind}));await service.changeAtlas("other-god",f.worldId,{action:"save",id:testMap,revision:current.revision,draft:{...draftOf(current,bundle.geographies),drawings:[...current.drawings!,...kinds]}});assert.equal((await service.getAtlas("other-god",f.worldId)).maps.find(m=>m.id===testMap)!.drawings!.length,11);
  assert.deepEqual((await service.getAtlas("other-god",f.worldId)).maps.find(m=>m.id===f.mapId)!.features,map.features);assert.equal((await service.getAtlas("other-god",f.worldId)).maps.find(m=>m.id===f.mapId)!.revision,map.revision);
  console.log("PASS: 0104 retains existing 3A identities; drawing source persistence, all terrain kinds, strict database validators, atomic failures, incomplete old drafts, CAS races and cross-World/role privacy.");
  return f;
}
async function screenPoint(page:Page,x:number,y:number) {const canvas=page.getByRole("application",{name:"Editable map canvas"});await canvas.scrollIntoViewIfNeeded();return canvas.evaluate((node,p)=>{const m=(node as SVGSVGElement).getScreenCTM()!;const q=new DOMPoint(p.x,p.y).matrixTransform(m);return {x:q.x,y:q.y};},{x,y});}
async function drag(page:Page,coordinates:number[][]) {const start=await screenPoint(page,...coordinates[0] as [number,number]);await page.mouse.move(start.x,start.y);await page.mouse.down();for(const [x,y] of coordinates.slice(1)){const p=await screenPoint(page,x,y);await page.mouse.move(p.x,p.y,{steps:12});}await page.mouse.up();}
async function open(page:Page,url:string) {await page.goto(url);await page.getByRole("button",{name:"Atlas",exact:true}).click();await page.getByRole("button",{name:"Open The Valdorian Atlas",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();}
async function save(page:Page) {await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByRole("status").filter({hasText:"Map saved."}).waitFor();}
async function drawingName(page:Page,name:string) {await page.getByLabel("Drawing name",{exact:true}).fill(name);await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();}
export async function cartographyBrowserChecks(browser:Browser,baseUrl:string,f:Fixture,artifacts:string) {
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.46"}});
  const signed=await context.request.post(`${baseUrl}/api/auth/sign-in/email`,{headers:{Origin:baseUrl},data:{email:"other-god@example.invalid",password:"Worlds-Test-Only-Password!"}});assert.equal(signed.status(),200);
  const page=await context.newPage(),errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));const url=`${baseUrl}/worlds/${f.worldId}`,api=`${baseUrl}/api/worlds/${f.worldId}/atlas`;
  const read=async()=>{const response=await context.request.get(api);assert.equal(response.status(),200);const bundle=await response.json() as AtlasBundle;return {bundle,map:bundle.maps.find(m=>m.id===f.mapId)!};};
  try {
    const original=(await read()).map.features.find(n=>n.id===f.featureId)!;assert.equal(original.geometry.type,"polygon");
    await open(page,url);await page.getByRole("button",{name:"Valdoria (3A)",exact:true}).click();await page.getByRole("button",{name:"Sculpt coast",exact:true}).click();await page.getByLabel("Coast brush size",{exact:true}).fill("150");await drag(page,[[650,160],[650,315]]);
    await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();for(let i=0;i<3;i++)await page.getByRole("button",{name:"Add coastal detail",exact:true}).click();await page.getByRole("button",{name:"Smooth coastline",exact:true}).click();
    await page.getByRole("button",{name:"Paint terrain",exact:true}).click();await page.getByLabel("Brush size",{exact:true}).fill("60");await drag(page,[[540,450],[730,330],[920,350],[1080,420]]);await drawingName(page,"The Spine");
    await page.getByLabel("Terrain brush",{exact:true}).selectOption("forest");await drag(page,[[570,730],[750,700],[900,720],[1020,650]]);await drawingName(page,"Deepwood");
    await page.getByRole("button",{name:"Draw path",exact:true}).click();for(const [x,y] of [[1040,460],[1100,570],[1190,700],[1390,850]]){const p=await screenPoint(page,x,y);await page.mouse.click(p.x,p.y);}await page.getByRole("button",{name:"Complete path",exact:true}).click();await drawingName(page,"Silver Run");
    await page.getByRole("button",{name:"Place symbol",exact:true}).click();await page.getByLabel("Symbol kind",{exact:true}).selectOption("city");const town=await screenPoint(page,1180,700);await page.mouse.click(town.x,town.y);await drawingName(page,"Port Veyra");await page.getByLabel("Linked geography name",{exact:true}).fill("Port Veyra");await page.getByRole("button",{name:"Apply linked geography",exact:true}).click();
    await page.getByRole("button",{name:"Place label",exact:true}).click();await page.getByLabel("New label text",{exact:true}).fill("Port Veyra");const label=await screenPoint(page,1190,780);await page.mouse.click(label.x,label.y);await drawingName(page,"Port Veyra label");
    await save(page);let result=await read(),coast=result.map.features.find(n=>n.id===f.featureId)!;assert.notDeepEqual(coast.geometry,original.geometry);assert.equal(coast.geographyId,f.geographyId);assert.ok(coast.geometry.type==="polygon"&&coast.geometry.points.length>=80,"Detail and smoothing must leave a substantial editable coastline.");
    const range=result.map.drawings!.find(d=>d.name==="The Spine")!,forest=result.map.drawings!.find(d=>d.name==="Deepwood")!,river=result.map.drawings!.find(d=>d.name==="Silver Run")!,symbol=result.map.drawings!.find(d=>d.type==="symbol")!,nameLabel=result.map.drawings!.find(d=>d.type==="label")!;assert.equal(symbol.geographyId,nameLabel.geographyId);assert.equal(result.bundle.geographies.find(g=>g.id===symbol.geographyId)!.name,"Port Veyra");assert.equal(result.map.drawings!.filter(d=>d.type==="terrain").every(d=>d.geographyId===null),true);
    await open(page,url);await page.getByRole("button",{name:"Valdoria (3A)",exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Boundary point",{exact:true}).selectOption({index:1});await page.getByLabel("Point Y",{exact:true}).fill("230");await page.getByRole("button",{name:"Apply point position",exact:true}).click();
    await page.getByRole("button",{name:"The Spine",exact:true}).click();await page.getByRole("button",{name:"Move feature",exact:true}).click();await page.getByRole("button",{name:"Right",exact:true}).click();
    await page.getByRole("button",{name:"Deepwood",exact:true}).click();await page.getByLabel("Stroke density",{exact:true}).fill("1");await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();await page.getByRole("button",{name:"Send backward",exact:true}).click();
    await page.getByRole("button",{name:"Silver Run",exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Drawing point",{exact:true}).selectOption({index:2});await page.getByLabel("Drawing X",{exact:true}).fill("1140");await page.getByRole("button",{name:"Apply drawing position",exact:true}).click();
    await page.getByRole("button",{name:"Port Veyra",exact:true}).click();await page.getByLabel("Placed symbol scale",{exact:true}).fill("1.3");await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();await page.getByLabel("Drawing X",{exact:true}).fill("1200");await page.getByRole("button",{name:"Apply drawing position",exact:true}).click();
    await page.getByRole("button",{name:"Port Veyra label",exact:true}).click();await page.getByLabel("Label text",{exact:true}).fill("Port Veyra Harbour");await page.getByLabel("Placed label size",{exact:true}).fill("34");await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();await save(page);await open(page,url);
    result=await read();coast=result.map.features.find(n=>n.id===f.featureId)!;assert.equal(coast.geometry.type,"polygon");if(coast.geometry.type!=="polygon"||original.geometry.type!=="polygon"||range.type!=="terrain"||river.type!=="path")throw new Error("Fixture types changed.");assert.equal(coast.geometry.points[0].y,230);for(const p of original.geometry.points)assert.ok(coast.geometry.points.some(n=>n.id===p.id));const changedRange=result.map.drawings!.find(d=>d.id===range.id)!;assert.equal(changedRange.type,"terrain");if(changedRange.type!=="terrain")throw new Error("Range type changed.");assert.equal(changedRange.points[0].x,range.points[0].x+10);assert.deepEqual(changedRange.points.map(p=>p.id),range.points.map(p=>p.id));const changedForest=result.map.drawings!.find(d=>d.id===forest.id)!;assert.equal(changedForest.type,"terrain");if(changedForest.type!=="terrain")throw new Error("Forest type changed.");assert.equal(changedForest.density,1);const changedRiver=result.map.drawings!.find(d=>d.id===river.id)!;assert.equal(changedRiver.type,"path");if(changedRiver.type!=="path")throw new Error("River type changed.");assert.equal(changedRiver.points[1].x,1140);assert.deepEqual(changedRiver.points.map(p=>p.id),river.points.map(p=>p.id));
    assert.deepEqual(result.map.drawings!.filter(d=>d.type==="terrain").map(d=>d.id),[forest.id,range.id]);const editedSymbol=result.map.drawings!.find(d=>d.id===symbol.id)!,editedLabel=result.map.drawings!.find(d=>d.id===nameLabel.id)!;assert.equal(editedSymbol.geographyId,symbol.geographyId);assert.equal(editedLabel.geographyId,nameLabel.geographyId);assert.ok(editedSymbol.type==="symbol"&&editedSymbol.scale===1.3&&editedSymbol.point.x===1200);assert.ok(editedLabel.type==="label"&&editedLabel.text==="Port Veyra Harbour"&&editedLabel.size===34);
    console.log("PASS: mandatory 3B existing 3A continent -> sculpt bay -> mountains/forest/river/settlement/label -> save/reload -> reshape original coast, move range, change forest and reshape river -> save/reload, with stable relevant identities.");
    await page.getByRole("button",{name:"Paint terrain",exact:true}).click();const accents:[[number,number],string][]=[[[460,450],"hills"],[[710,500],"valleys"],[[780,900],"grassland"],[[1280,430],"desert"],[[1250,850],"wetland"],[[1010,250],"snow"],[[460,620],"lake"]];for(const [[x,y],kind] of accents){await page.getByLabel("Terrain brush",{exact:true}).selectOption(kind);await page.getByLabel("Brush size",{exact:true}).fill("40");await drag(page,[[x,y],[x+100,y+20]]);}await save(page);
    await page.getByRole("button",{name:"Deepwood",exact:true}).click();page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Archive drawing",exact:true}).click();await save(page);assert.equal((await read()).map.drawings!.find(d=>d.id===forest.id)!.archived,true);page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Restore drawing",exact:true}).click();await save(page);assert.deepEqual((await read()).map.drawings!.find(d=>d.id===forest.id),changedForest);
    await page.getByRole("button",{name:"Deepwood",exact:true}).click();await page.getByLabel("Drawing name",{exact:true}).fill("Retained forest draft");await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();await page.route(api,route=>route.request().method()==="POST"?route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary art save failure"})}):route.continue());await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByRole("alert").getByText("Temporary art save failure",{exact:true}).waitFor();assert.equal(await page.getByLabel("Drawing name",{exact:true}).inputValue(),"Retained forest draft");await page.unroute(api);
    const second=await context.newPage();await open(second,url);await second.getByRole("button",{name:"Silver Run",exact:true}).click();await second.getByLabel("Saved path width",{exact:true}).fill("9");await second.getByRole("button",{name:"Apply drawing changes",exact:true}).click();await save(second);await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByRole("alert").getByText(/newer map or geography/).waitFor();assert.equal(await page.getByLabel("Drawing name",{exact:true}).inputValue(),"Retained forest draft");await page.getByRole("button",{name:"Load saved map to compare",exact:true}).click();await page.getByRole("heading",{name:/Saved map · revision/}).waitFor();assert.ok(await page.getByLabel("Saved geometry comparison",{exact:true}).locator("[data-drawing]").count()>0);page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Use saved map",exact:true}).click();await page.getByRole("status").filter({hasText:"All changes saved"}).waitFor();await second.close();
    await page.getByText("Style and layers",{exact:true}).click();await page.getByLabel("Lock terrain layer",{exact:true}).check();assert.equal(await page.getByRole("button",{name:"The Spine",exact:true}).isEnabled(),false);await page.getByLabel("Lock terrain layer",{exact:true}).uncheck();await page.getByLabel("Show terrain layer",{exact:true}).uncheck();assert.equal(await page.getByRole("application",{name:"Editable map canvas"}).locator('[data-layer="terrain"]').count(),0);await page.getByLabel("Show terrain layer",{exact:true}).check();await page.getByLabel("Map appearance",{exact:true}).selectOption("illuminated");await save(page);
    const beforeExport=await read();const downloaded=page.waitForEvent("download");await page.getByRole("button",{name:"Export PNG",exact:true}).click();const output=await downloaded,exportPath=path.join(artifacts,"worlds-cartography-export.png");await output.saveAs(exportPath);const png=await readFile(exportPath);assert.equal(png.subarray(1,4).toString(),"PNG");assert.equal(png.readUInt32BE(16),2000);assert.equal(png.readUInt32BE(20),1200);assert.deepEqual(await read(),beforeExport);
    await page.getByRole("button",{name:"Freehand coast",exact:true}).click();await page.getByLabel("Landmass kind",{exact:true}).selectOption("island");await drag(page,[[1720,180],[1820,210],[1840,320],[1770,360],[1670,290],[1720,180]]);await page.getByRole("button",{name:"Close outline",exact:true}).click();await page.getByLabel("Feature name",{exact:true}).fill("Crescent Isle");await page.getByRole("button",{name:"Apply geography changes",exact:true}).click();await page.getByRole("button",{name:"Smooth coastline",exact:true}).click();await save(page);await open(page,url);
    const tracedBundle=await read();const traced=tracedBundle.map.features.find(n=>n.geographyId===tracedBundle.bundle.geographies.find(g=>g.name==="Crescent Isle")!.id)!;assert.equal(traced.geometry.type,"polygon");
    const finalDownload=page.waitForEvent("download");await page.getByRole("button",{name:"Export PNG",exact:true}).click();await (await finalDownload).saveAs(exportPath);const finalPng=await readFile(exportPath);
    await captureWorldsScreenshot(page.getByRole("application",{name:"Editable map canvas"}).locator(".."),{path:path.join(artifacts,"worlds-cartography-desktop.png")});
    const phone=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,storageState:await context.storageState()});const mobile=await phone.newPage();mobile.on("pageerror",e=>errors.push(e.message));await open(mobile,url);const cdp=await phone.newCDPSession(mobile);
    const touchDrag=async(coords:number[][])=>{const first=await screenPoint(mobile,...coords[0] as [number,number]);await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[first]});for(const [x,y] of coords.slice(1)){const p=await screenPoint(mobile,x,y);await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[p]});}await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});};
    const phoneDownload=mobile.waitForEvent("download");await mobile.getByRole("button",{name:"Export PNG",exact:true}).tap();const phoneExport=path.join(artifacts,"worlds-cartography-export-mobile.png");await (await phoneDownload).saveAs(phoneExport);assert.deepEqual(await readFile(phoneExport),finalPng,"Full-map export is identical across desktop and phone viewports.");
    await mobile.getByRole("button",{name:"Valdoria (3A)",exact:true}).tap();await mobile.getByRole("button",{name:"Sculpt coast",exact:true}).tap();await mobile.getByLabel("Coast brush size",{exact:true}).fill("160");await touchDrag([[900,1050],[900,1010],[900,970]]);await save(mobile);
    await mobile.getByRole("button",{name:"Paint terrain",exact:true}).tap();await mobile.getByLabel("Terrain brush",{exact:true}).selectOption("forest");await touchDrag([[620,820],[680,850],[750,870]]);await drawingName(mobile,"Phone woodland");await mobile.getByRole("button",{name:"Undo",exact:true}).tap();await mobile.getByRole("button",{name:"Redo",exact:true}).tap();await save(mobile);
    await mobile.getByRole("button",{name:"Silver Run",exact:true}).tap();await mobile.getByRole("button",{name:"Edit points",exact:true}).tap();await mobile.getByLabel("Drawing point",{exact:true}).selectOption({index:2});const p=(await read()).map.drawings!.find(d=>d.id===river.id)!;if(p.type!=="path")throw new Error("River type changed.");await touchDrag([[p.points[1].x,p.points[1].y],[p.points[1].x+20,p.points[1].y+15]]);await save(mobile);await open(mobile,url);const phoneRiver=(await read()).map.drawings!.find(d=>d.id===river.id)!;assert.ok(phoneRiver.type==="path");if(phoneRiver.type!=="path")throw new Error("Phone river type changed.");assert.equal(phoneRiver.points[1].id,p.points[1].id);assert.equal(phoneRiver.points[1].x,p.points[1].x+20);assert.equal(phoneRiver.points[1].y,p.points[1].y+15);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await captureWorldsScreenshot(mobile.getByRole("application",{name:"Editable map canvas"}).locator(".."),{path:path.join(artifacts,"worlds-cartography-mobile.png")});await captureWorldsScreenshot(mobile,{path:path.join(artifacts,"worlds-cartography-mobile-page.png"),fullPage:true});await phone.close();assert.deepEqual(errors,[]);
    console.log("PASS: all terrain brushes, actual mouse/touch sculpting/painting/path editing, failed drafts, real two-tab recovery, layer locks/visibility, styles, editable source retention and verified 2000x1200 PNG export; desktop/phone functional checks.");
  }catch(failure){await captureWorldsScreenshot(page,{path:path.join(artifacts,"worlds-cartography-failure.png"),fullPage:true}).catch(()=>{});console.log(JSON.stringify({cartographyErrors:errors,alerts:await page.getByRole("alert").allTextContents(),invalidFields:await page.locator("input:invalid").evaluateAll(nodes=>nodes.map(n=>({label:n.getAttribute("aria-labelledby"),message:(n as HTMLInputElement).validationMessage})))}));throw failure;}finally{await context.close();}
}
