import { captureWorldsScreenshot } from "./worlds-browser-evidence";
import assert from "node:assert/strict";
import path from "node:path";
import type pg from "pg";
import type { BrowserContext, Page } from "playwright-core";
import type * as Service from "../src/features/worlds/world-service";
import { datingDraftOf, formatTime } from "../src/features/worlds/chronology";
import { entryDraftOf } from "../src/features/worlds/client-api";
import type { HistoricalTime } from "../src/features/worlds/history";

export async function chronologyServiceChecks(service:typeof Service,pool:pg.Pool,existingWorld:string,foreignWorld:string) {
  const before=(await pool.query("select id,historical_time,dating_system_id,source_dating from world_historical_entry where world_id=$1 order by id",[existingWorld])).rows;
  const eraBefore=(await pool.query("select * from world_historical_era where world_id=$1 order by id",[existingWorld])).rows;
  const fallback=await service.getWorld("world-god",existingWorld);assert.equal(fallback.defaultDatingSystemId,null);assert.deepEqual(fallback.datingSystems,[]);
  const worldId=await service.createWorld("world-god",{name:"Silver Coast",description:"An archive of the ways its people count the years."});
  const draft={...datingDraftOf(),name:"Founding Reckoning",origin:"The founding of the first city",beforeLabel:"Before Founding",afterLabel:"After Founding"};
  const founding=(await service.changeChronology("world-god",worldId,{action:"save",draft}))!;
  const astral=(await service.changeChronology("world-god",worldId,{action:"save",draft:{...draft,name:"Astral Count",epochYear:-500,numbering:"year-zero"}}))!;
  const foreignSystem=(await service.changeChronology("other-god",foreignWorld,{action:"save",draft:{...draft,name:"Foreign secret reckoning"}}))!;
  assert.equal((await service.getWorld("world-god",worldId)).datingSystems.length,2);
  for(const epochYear of [0.5,1e12+1,NaN])await assert.rejects(service.changeChronology("world-god",worldId,{action:"save",draft:{...draft,epochYear}}));
  const dates:HistoricalTime[]=[{version:1,scale:"world-year",kind:"known",year:0},{version:1,scale:"world-year",kind:"approximate",year:-1},{version:1,scale:"world-year",kind:"window",startYear:-10,endYear:10},{version:1,scale:"world-year",kind:"duration",startYear:0,endYear:100},{version:1,scale:"world-year",kind:"known",year:-1e12},{version:1,scale:"world-year",kind:"undated"}];
  const entryIds:string[]=[];
  for(const [index,time] of dates.entries())entryIds.push(await service.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:{title:`Source date ${index}`,account:"A year-only historical account.",time,accuracy:"established",narrative:"recorded",datingSystemId:founding,datingSystemRevision:1}}));
  await service.changeHistory("world-god",worldId,{entity:"era",action:"save",draft:{name:"Age of the first city",startYear:null,endYear:0,datingSystemId:founding,datingSystemRevision:1}});
  const records=await service.getWorld("world-god",worldId);
  for(const [index,id] of entryIds.entries())assert.deepEqual(records.entries.find((entry)=>entry.id===id)!.time,dates[index]);
  assert.deepEqual(records.entries.find((entry)=>entry.id===entryIds[0])!.sourceDating?.years,[1]);
  assert.equal(records.entries.find((entry)=>entry.id===entryIds[5])!.datingSystemId,null);
  const originSystem=records.datingSystems.find((system)=>system.id===founding)!;assert.equal(originSystem.referenced,true);
  await assert.rejects(service.changeChronology("world-god",worldId,{action:"save",id:founding,revision:1,draft:{...draft,epochYear:1}}),/locked/);
  await assert.rejects(service.changeChronology("world-god",worldId,{action:"save",id:founding,revision:1,draft:{...draft,numbering:"year-zero"}}),/locked/);
  await service.changeChronology("world-god",worldId,{action:"save",id:astral,revision:1,draft:{...draft,name:"Astral Count",epochYear:-450,numbering:"year-zero"}});
  const competing=await Promise.allSettled([service.changeChronology("world-god",worldId,{action:"save",id:astral,revision:2,draft:{...draft,name:"Astral Count",epochYear:-400,numbering:"year-zero"}}),service.changeChronology("world-god",worldId,{action:"save",id:astral,revision:2,draft:{...draft,name:"Astral Count",epochYear:-425,numbering:"year-zero"}})]);
  assert.equal(competing.filter((result)=>result.status==="fulfilled").length,1);assert.equal(competing.filter((result)=>result.status==="rejected").length,1);
  const dateSnapshot=(await pool.query("select id,historical_time,source_dating from world_historical_entry where world_id=$1 order by id",[worldId])).rows;
  await service.changeChronology("world-god",worldId,{action:"default",revision:1,systemId:founding});
  await assert.rejects(service.changeChronology("world-god",worldId,{action:"default",revision:1,systemId:astral}),/newer version/);
  await assert.rejects(service.changeChronology("world-god",worldId,{action:"archive",id:founding,revision:1}),/another default/);
  await service.changeChronology("world-god",worldId,{action:"default",revision:2,systemId:null});
  assert.deepEqual((await pool.query("select id,historical_time,source_dating from world_historical_entry where world_id=$1 order by id",[worldId])).rows,dateSnapshot);
  await service.changeChronology("world-god",worldId,{action:"archive",id:founding,revision:1});
  const archived=await service.getWorld("world-god",worldId);assert.ok(archived.datingSystems.find((system)=>system.id===founding)!.archived);
  const old=archived.entries.find((entry)=>entry.id===entryIds[0])!;
  await service.changeHistory("world-god",worldId,{entity:"entry",id:old.id,revision:old.revision,action:"save",draft:{...entryDraftOf(old),notes:"Keep the original notation.",datingSystemRevision:2}});
  assert.deepEqual((await service.getWorld("world-god",worldId)).entries.find((entry)=>entry.id===old.id)!.sourceDating,old.sourceDating);
  await assert.rejects(service.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:{...entryDraftOf(old),title:"Rejected archived assignment",datingSystemRevision:2}}),/Restore this dating system/);
  await assert.rejects(service.changeChronology("world-god",worldId,{action:"default",revision:3,systemId:founding}),/Restore/);
  await service.changeChronology("world-god",worldId,{action:"restore",id:founding,revision:2});
  await service.changeChronology("world-god",worldId,{action:"save",id:founding,revision:3,draft:{...draft,description:"An established reckoning.",beforeLabel:"Before the First City",afterLabel:"After the First City"}});
  assert.deepEqual((await service.getWorld("world-god",worldId)).entries.find((entry)=>entry.id===old.id)!.sourceDating,old.sourceDating,"Editable labels must not erase original source notation.");
  await assert.rejects(pool.query("update world_historical_entry set source_dating='{}'::jsonb where id=$1",[old.id]),/check constraint/);
  await assert.rejects(service.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:{...entryDraftOf(old),title:"Stale dating arithmetic",datingSystemRevision:3}}),/newer version/);
  const sourceDraft={...entryDraftOf(old),datingSystemId:foreignSystem,datingSystemRevision:1};
  await assert.rejects(service.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:sourceDraft}),/unavailable/);
  await assert.rejects(service.changeHistory("world-god",worldId,{entity:"era",action:"save",draft:{name:"Forged era source",startYear:0,endYear:10,datingSystemId:foreignSystem,datingSystemRevision:1}}),/unavailable/);
  await assert.rejects(service.changeChronology("world-god",worldId,{action:"default",revision:3,systemId:foreignSystem}),/unavailable/);
  await assert.rejects(pool.query("insert into world_chronology_preference(world_id,default_dating_system_id) values($1,$2) on conflict(world_id) do update set default_dating_system_id=$2",[worldId,foreignSystem]),/foreign key/);
  await assert.rejects(pool.query("update world_historical_entry set dating_system_id=$1,source_dating=$2 where id=$3",[foreignSystem,{...old.sourceDating,systemId:foreignSystem},old.id]),/foreign key/);
  for(const id of ["other-god","world-admin"])await assert.rejects(service.changeChronology(id,worldId,{action:"save",draft}),/unavailable/);
  await assert.rejects(service.changeChronology("world-player",worldId,{action:"save",draft}),/access/);
  await assert.rejects(service.getWorld("other-god",worldId),/unavailable/);assert.equal((await service.getWorld("world-admin",worldId,true)).canEdit,false);
  assert.deepEqual((await pool.query("select id,historical_time,dating_system_id,source_dating from world_historical_entry where world_id=$1 order by id",[existingWorld])).rows,before);
  assert.deepEqual((await pool.query("select * from world_historical_era where world_id=$1 order by id",[existingWorld])).rows,eraBefore);
  console.log("PASS: chronology persistence, multiple reckonings, source precision, immutable referenced arithmetic, defaults without date rewrites, archived retention, revisions, same-world FKs and role privacy.");
  return {worldId,founding,foreignSystem,entryId:old.id};
}
type Fixture=Awaited<ReturnType<typeof chronologyServiceChecks>>;
async function ready(page:Page){await page.waitForFunction(()=>[...document.querySelectorAll("button")].some((button)=>Object.keys(button).some((key)=>key.startsWith("__reactProps$"))));}
async function card(page:Page,name:string){return page.locator("article").filter({has:page.getByRole("heading",{name,exact:true})});}
export async function chronologyBrowserChecks(service:typeof Service,page:Page,context:BrowserContext,baseUrl:string,fixture:Fixture,artifactRoot:string) {
  const {worldId}=fixture;
  await page.goto(`${baseUrl}/worlds/${worldId}`);await ready(page);await page.getByRole("button",{name:"Chronology",exact:true}).click();
  await page.getByRole("button",{name:"New dating system",exact:true}).click();await page.getByLabel("Dating system name",{exact:true}).fill("Sundering Count");await page.getByLabel("Historical origin",{exact:true}).fill("The Sundering of the coast");await page.getByLabel("Epoch in canonical years",{exact:true}).fill("100");await page.getByLabel("Before-origin label",{exact:true}).fill("Before Sundering");await page.getByLabel("After-origin label",{exact:true}).fill("After Sundering");
  await page.getByLabel("Help for Year numbering",{exact:true}).click();
  await captureWorldsScreenshot(page,{path:path.join(artifactRoot,"worlds-chronology-editor-desktop.png"),fullPage:false});
  await page.route(`**/api/worlds/${worldId}/chronology`,(route)=>route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary chronology save failure."})}));
  await page.getByRole("dialog").getByRole("button",{name:"Create dating system",exact:true}).click();await page.getByRole("alert").filter({hasText:"Temporary chronology save failure."}).waitFor();assert.equal(await page.getByLabel("Dating system name",{exact:true}).inputValue(),"Sundering Count");
  await page.unroute(`**/api/worlds/${worldId}/chronology`);await page.getByRole("dialog").getByRole("button",{name:"Create dating system",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});
  const system=(await service.getWorld("world-god",worldId)).datingSystems.find((item)=>item.name==="Sundering Count")!;
  await page.getByLabel("Convert to",{exact:true}).selectOption(system.id);await page.getByLabel("Sample year",{exact:true}).fill("100");assert.match(await page.locator("output").innerText(),/Year 1 After Sundering/);
  await page.getByLabel("Convert from",{exact:true}).selectOption(system.id);await page.getByLabel("Convert to",{exact:true}).selectOption("");await page.getByLabel("Sample year",{exact:true}).fill("1");assert.match(await page.locator("output").innerText(),/Year 100/);
  await page.getByLabel("Sample year",{exact:true}).fill("0");await page.getByRole("alert").filter({hasText:"no Year 0"}).waitFor();await page.getByLabel("Sample year",{exact:true}).fill("-1");assert.match(await page.locator("output").innerText(),/Year 99/);
  await page.getByRole("button",{name:"Use Sundering Count as default",exact:true}).click();await (await card(page,"Sundering Count")).getByText("Default display",{exact:true}).waitFor();
  await page.getByRole("region",{name:"World chronology",exact:true}).scrollIntoViewIfNeeded();await captureWorldsScreenshot(page,{path:path.join(artifactRoot,"worlds-chronology-desktop.png"),fullPage:true});
  await page.reload();await ready(page);assert.equal(await page.getByLabel("View years using",{exact:true}).inputValue(),system.id);
  await page.getByRole("button",{name:/^History \d/}).click();
  const canvas=page.getByRole("region",{name:/Timeline canvas/});const marker=canvas.getByRole("button",{name:/^Source date 0\./});const before=await marker.boundingBox();assert.ok(before);
  await page.getByLabel("View years using",{exact:true}).selectOption("");const after=await marker.boundingBox();assert.ok(after);assert.ok(Math.abs(after.x-before.x)<.5 && Math.abs(after.y-before.y)<.5,"Switching labels must not move an event.");
  await page.getByLabel("View years using",{exact:true}).selectOption(system.id);await page.locator("#history-year").fill("1");await page.getByRole("button",{name:"Go",exact:true}).click();assert.match(await page.getByRole("region",{name:"Historical timeline",exact:true}).locator("p[aria-live='polite']").innerText(),/Sundering/);
  await page.getByRole("button",{name:"New entry",exact:true}).click();await page.getByLabel("Entry title",{exact:true}).fill("A new coast");await page.getByLabel("Historical account",{exact:true}).fill("The coast was remade after the Sundering.");await page.getByLabel("Date representation",{exact:true}).selectOption("known");await page.getByLabel("Year",{exact:true}).fill("0");assert.equal(await page.getByLabel("Year",{exact:true}).inputValue(),"0");await page.getByLabel("Year",{exact:true}).fill("1");await page.getByRole("button",{name:"Save history",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});
  const authored=(await service.getWorld("world-god",worldId)).entries.find((entry)=>entry.title==="A new coast")!;assert.deepEqual(authored.time,{version:1,scale:"world-year",kind:"known",year:100});assert.deepEqual(authored.sourceDating?.years,[1]);
  await page.getByRole("button",{name:"Chronological list",exact:true}).click();await page.getByLabel("Search history",{exact:true}).fill("A new coast");await page.getByRole("button",{name:"A new coast",exact:true}).click();assert.ok((await page.getByRole("dialog").innerText()).includes(formatTime(authored.time,system)));await page.getByRole("heading",{name:"Original dating context",exact:true}).waitFor();await page.getByRole("button",{name:"Close historical details",exact:true}).click();
  // Two independent browser tabs use the same system revision.
  await page.getByRole("button",{name:"Chronology",exact:true}).click();await page.getByRole("button",{name:"Edit Sundering Count",exact:true}).click();await page.getByLabel("Description",{exact:true}).fill("This draft must survive a conflict.");
  const second=await context.newPage();await second.goto(`${baseUrl}/worlds/${worldId}`);await ready(second);await second.getByRole("button",{name:"Chronology",exact:true}).click();await second.getByRole("button",{name:"Edit Sundering Count",exact:true}).click();assert.equal(await second.getByLabel("Epoch in canonical years",{exact:true}).getAttribute("readonly"),"");await second.getByLabel("Description",{exact:true}).fill("A newer second-tab description.");await second.getByRole("button",{name:"Save dating system",exact:true}).click();await second.getByRole("dialog").waitFor({state:"hidden"});
  await page.getByRole("button",{name:"Save dating system",exact:true}).click();await page.getByRole("button",{name:"Load latest version",exact:true}).waitFor();assert.equal(await page.getByLabel("Description",{exact:true}).inputValue(),"This draft must survive a conflict.");page.once("dialog",(dialog)=>dialog.accept());await page.getByRole("button",{name:"Load latest version",exact:true}).click();await page.waitForFunction(()=>document.querySelector<HTMLTextAreaElement>("dialog[open] textarea")?.value==="A newer second-tab description.");await page.getByRole("button",{name:"Close dating editor",exact:true}).click();await second.close();
  await page.getByRole("button",{name:"Use canonical as default",exact:true}).click();await (await card(page,"Canonical world years")).getByText("Default display",{exact:true}).waitFor();await page.getByRole("button",{name:"Archive Sundering Count",exact:true}).click();await page.getByRole("button",{name:"Restore Sundering Count",exact:true}).waitFor();
  await page.getByRole("button",{name:/^History \d/}).click();await page.getByRole("button",{name:"A new coast",exact:true}).click();await page.getByText("Sundering Count · revision 1",{exact:true}).waitFor();await page.getByRole("button",{name:"Close historical details",exact:true}).click();
  await page.getByRole("button",{name:"Chronology",exact:true}).click();await page.setViewportSize({width:390,height:844});await page.getByRole("region",{name:"World chronology",exact:true}).scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await captureWorldsScreenshot(page,{path:path.join(artifactRoot,"worlds-chronology-mobile.png"),fullPage:true});
  await page.getByRole("button",{name:"New dating system",exact:true}).click();await page.getByLabel("Dating system name",{exact:true}).fill("A mobile count");await page.getByLabel("Historical origin",{exact:true}).fill("A remembered winter");await page.getByLabel("Year numbering",{exact:true}).selectOption("year-zero");await page.getByLabel("Help for Epoch in canonical years",{exact:true}).click();await captureWorldsScreenshot(page,{path:path.join(artifactRoot,"worlds-chronology-editor-mobile.png"),fullPage:false});await page.getByRole("dialog").getByRole("button",{name:"Create dating system",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});await page.reload();await ready(page);assert.ok((await service.getWorld("world-god",worldId)).datingSystems.some((item)=>item.name==="A mobile count"));await page.setViewportSize({width:1440,height:900});
  console.log("PASS: chronology authoring, preview/conversion, defaults across reload, measured timeline position stability, source-context reading, no-zero validation, failed drafts, two-tab conflicts, archive retention and phone persistence.");
}
