import { captureWorldsScreenshot } from "./worlds-browser-evidence";
import assert from "node:assert/strict";
import { randomUUID as id } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type pg from "pg";
import type { Browser, BrowserContext } from "playwright-core";
import { draftOf, type AtlasBundle, type AtlasMap } from "../src/features/worlds/atlas";
import { defaultInteriorState, furnishings, geographicInterior, openingAnchor, type InteriorEntity, type InteriorShape } from "../src/features/worlds/interior";
type Service=typeof import("../src/features/worlds/atlas-service");type Worlds=typeof import("../src/features/worlds/world-service");
type Fixture={worldId:string;buildingId:string;exterior:string;maps:string[];dense:string;copy:string};
const points=(coordinates:number[][])=>coordinates.map(([x,y])=>({id:id(),x,y}));
function furnish(map:AtlasMap,b:AtlasBundle,edition=0,dense=false){
 const d=draftOf(map,b.geographies);d.interiorShapes=[];d.interiorEntities=[];d.interiorLinks=[];d.interiorState=defaultInteriorState();d.interiorState.flooring=edition%2?"boards":"tiles";d.geographies=[];
 const add=(kind:InteriorEntity["kind"],name:string,shape:object)=>{const eid=id(),sid=id();d.interiorEntities!.push({id:eid,revision:null,kind,name,description:name?`${name}: an authored space in the impossible observatory.`:"",classification:kind==="room"?"Authored interior area":"",geographyId:geographicInterior(kind)?eid:null});d.interiorShapes!.push({...shape,version:1,id:sid,entityId:eid,archived:false} as InteriorShape);if(geographicInterior(kind))d.geographies.push({id:eid,revision:null,name:name||`Unnamed ${kind}`,description:name?`${name}: an authored space in the impossible observatory.`:"",kind:"location",context:"interior",parentId:map.geographyId!});if(kind==="transition")d.interiorLinks!.push({entityId:eid,destinationMapId:null,destinationGeographyId:null});return d.interiorShapes!.at(-1)!;};
 if(dense){for(let n=0;n<960;n++){const x=80+n%40*46,y=70+Math.floor(n/40)*44;add(n%12===0?"landmark":"furnishing",n%12===0?`Instrument ${n}`:"",{variant:"object",point:{x,y},width:28,height:24,rotation:n%2?15:0,symbol:n%12===0?"custom":furnishings[n%furnishings.length]});}return d;}
 const layout=edition%2?[[[260,140],[980,140],[980,600],[760,600],[760,1040],[260,1040]],[[980,140],[1710,140],[1710,470],[980,470]],[[980,470],[1710,470],[1710,1040],[760,1040],[760,600],[980,600]]]:[[[260,140],[980,140],[980,600],[260,600]],[[260,600],[980,600],[980,1040],[260,1040]],[[980,140],[1710,140],[1710,470],[980,470]],[[980,470],[1710,470],[1710,1040],[980,1040]]];
 layout.forEach((xy,i)=>add("room",["Reading hall","Workshop","Sleeping chamber","Mirror gallery"][i],{variant:"area",points:points(xy)}));
 const walls=[add("wall","Outer boundary",{variant:"wall",width:14,points:points([[260,140],[1710,140],[1710,1040],[260,1040],[260,140]])}),add("wall","Central partition",{variant:"wall",width:10,points:points([[980,140],[980,1040]])}),add("wall","Gallery partition",{variant:"wall",width:8,points:points([[980,470],[1710,470]])})] as Extract<InteriorShape,{variant:"wall"}>[];
 const open=(wall:number,segment:number,at:number,width:number,style:string,name:string)=>{const w=walls[wall];add(style==="window"?"window":"opening",name,{variant:"opening",wallId:w.id,startId:w.points[segment].id,endId:w.points[segment+1].id,at,width,style});};
 open(0,2,.6,110,"double door","Main entrance");open(0,0,.23,90,"window","Northern window");open(0,1,.22,80,"window","Eastern window");open(1,0,.36,85,"door","Library doorway");open(2,0,.5,80,"passage","Gallery passage");
 add("transition","Spiral stairs",{variant:"object",point:{x:1580,y:900},width:95,height:125,rotation:0,symbol:"stairs"});add("transition","Mirror portal",{variant:"object",point:{x:1100,y:850},width:75,height:110,rotation:0,symbol:"portal"});
 for(let n=0;n<24;n++){const room=n%4,x=room<2?360+n%3*170:1100+n%3*180,y=room===0?260+Math.floor(n/4)%2*130:room===1?710+Math.floor(n/4)%2*130:room===2?240+Math.floor(n/4)%2*120:620+Math.floor(n/4)%2*130;add("furnishing",n===0?"The Keeper's desk":"",{variant:"object",point:{x,y},width:70+(n%3)*12,height:60,rotation:n%3?0:15,symbol:furnishings[n%furnishings.length]});}
 add("landmark","Dimensional anchor",{variant:"object",point:{x:620,y:480},width:80,height:90,rotation:0,symbol:"custom"});return d;
}
export async function interiorServiceChecks(service:Service,worlds:Worlds,pool:pg.Pool,foreign:string):Promise<Fixture>{
 const worldId=await worlds.createWorld("world-god",{name:"The Impossible Observatory"}),settlement=id();
 await service.changeAtlas("world-god",worldId,{action:"geography",draft:{id:settlement,revision:null,name:"Mirrorglass",description:"Settlement fixture",kind:"location",context:"settlement",parentId:null}});
 const exterior=await service.changeAtlas("world-god",worldId,{action:"create",name:"Observatory exterior",description:"Original settlement building",scope:"local",mapKind:"settlement",geographyId:settlement});const buildingId=id();let b=await service.getAtlas("world-god",worldId,false,exterior),m=b.maps.find(m=>m.id===exterior)!,d=draftOf(m,b.geographies);d.geographies=[{id:buildingId,revision:null,name:"Impossible Observatory",description:"One building, many authored interiors.",kind:"location",context:"building site",parentId:settlement}];d.settlementEntities=[{geographyId:buildingId,revision:null,kind:"building",classification:"Genre-neutral observatory",districtIds:[]}];d.settlementShapes=[{version:1,id:id(),geographyId:buildingId,archived:false,type:"area",variant:"custom",points:points([[770,450],[1180,450],[1250,750],[720,750]])}];await service.changeAtlas("world-god",worldId,{action:"save",id:exterior,revision:m.revision,draft:d});
 const maps:string[]=[];for(const [i,name] of ["Basement archives","Ground reception","Second laboratory","Floating wing","Beyond the Mirror"].entries()){const mapId=await service.changeAtlas("world-god",worldId,{action:"create-floor",buildingId,draft:{name,description:`${name}. Its elevation is authored, with no physical constraint.`,label:i===0?"Basement":i===4?"Elsewhere":`Level ${i}`,order:i===0?-1:i,elevation:i===4?"Outside ordinary space":""},mapName:`${name} plan`});maps.push(mapId);b=await service.getAtlas("world-god",worldId,false,mapId);m=b.maps.find(m=>m.id===mapId)!;await service.changeAtlas("world-god",worldId,{action:"save",id:mapId,revision:m.revision,draft:furnish(m,b,i)});}
 b=await service.getAtlas("world-god",worldId,false,maps[1]);m=b.maps.find(m=>m.id===maps[1])!;d=draftOf(m,b.geographies);d.interiorLinks=d.interiorEntities!.filter(e=>e.kind==="transition").map(e=>({entityId:e.id,destinationMapId:e.name==="Mirror portal"?maps[4]:maps[3],destinationGeographyId:null}));await service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:m.revision,draft:d});
 const destination=await service.getAtlas("world-god",worldId,false,maps[3]),arrival=destination.maps.find(m=>m.id===maps[3])!.interiorEntities!.find(e=>e.name==="Spiral stairs")!.id;
 b=await service.getAtlas("world-god",worldId,false,maps[1]);m=b.maps.find(m=>m.id===maps[1])!;d=draftOf(m,b.geographies);d.interiorLinks!.find(l=>l.entityId===d.interiorEntities!.find(e=>e.name==="Spiral stairs")!.id)!.destinationGeographyId=arrival;await service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:m.revision,draft:d});
 b=await service.getAtlas("world-god",worldId,false,maps[1]);m=b.maps.find(m=>m.id===maps[1])!;const stable=structuredClone(m);const copy=await service.changeAtlas("world-god",worldId,{action:"duplicate",id:m.id,revision:m.revision,newId:id(),name:"Ground decorative reference"}),copyBundle=await service.getAtlas("world-god",worldId,false,copy),copied=copyBundle.maps.find(m=>m.id===copy)!;assert.equal(copied.geographyId,m.geographyId);assert.deepEqual(copied.interiorEntities!.map(e=>e.id).sort(),m.interiorEntities!.map(e=>e.id).sort());assert.notEqual(copied.interiorShapes![0].id,m.interiorShapes![0].id);for(const s of copied.interiorShapes!)if(s.variant==="opening"&&!s.archived)openingAnchor(s,copied.interiorShapes!);assert.deepEqual(copied.interiorLinks,m.interiorLinks);
 d=draftOf(m,b.geographies);const sharedRoom=d.interiorEntities!.find(e=>e.kind==="room")!;sharedRoom.description="Shared room narrative updated in original.";d.geographies.find(g=>g.id===sharedRoom.id)!.description=sharedRoom.description;await service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:m.revision,draft:d});await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:copy,revision:copied.revision,draft:draftOf(copied,copyBundle.geographies)}),/another|newer/);await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:m.revision,draft:draftOf(stable,b.geographies)}),/newer/);
 b=await service.getAtlas("world-god",worldId,false,maps[1]);m=b.maps.find(m=>m.id===maps[1])!;d=draftOf(m,b.geographies);const bad=structuredClone(d),wall=bad.interiorShapes!.find(s=>s.variant==="wall")!;if(wall.variant==="wall")wall.points[0].id=id();await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:m.revision,draft:bad}),/removes a segment/);assert.deepEqual((await service.getAtlas("world-god",worldId,false,m.id)).maps.find(n=>n.id===m.id)!.interiorShapes,m.interiorShapes);
 await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"archive-geography",id:d.geographies[0].id,revision:d.geographies[0].revision}),/linked/);
 const missing=structuredClone(d);missing.interiorShapes!.pop();await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:m.revision,draft:missing}),/Keep saved interior/);
 const spoof=structuredClone(d);spoof.interiorEntities![0].id=id();await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:m.revision,draft:spoof}));
 for(const user of ["other-god","world-player","world-admin"])await assert.rejects(()=>service.getAtlas(user,worldId,false,m.id));assert.equal((await service.getAtlas("world-admin",worldId,true,m.id)).canEdit,false);for(const user of ["other-god","world-player","world-admin"])await assert.rejects(()=>service.changeAtlas(user,worldId,{action:"create-floor",buildingId,draft:{name:"Unauthorized",description:"",label:"",order:null,elevation:""},mapName:"Unauthorized"}));await assert.rejects(()=>service.getAtlas("world-god",foreign,false,m.id));await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"create-floor",buildingId:id(),draft:{name:"Forged",description:"",label:"",order:null,elevation:""},mapName:"Forged"}));
 await assert.rejects(()=>pool.query("update world_interior_floor set world_id=$1 where geography_id=$2",[foreign,m.geographyId]),/foreign key/);await assert.rejects(()=>pool.query("update world_atlas_interior_shape set floor_id=$1 where map_id=$2",[b.maps.find(n=>n.id===maps[2])!.geographyId,m.id]),/foreign key/);
 for(const s of m.interiorShapes!){assert.equal((await pool.query("select world_atlas_interior_shape_valid($1) as valid",[s])).rows[0].valid,true);assert.equal((await pool.query("select world_atlas_interior_shape_valid($1) as valid",[{...s,entityId:undefined}])).rows[0].valid,false);}assert.equal((await pool.query("select world_atlas_interior_state_valid($1) as valid",[{version:1,flooring:"plain",layers:{}}])).rows[0].valid,false);
 let floor=b.floors!.find(f=>f.id===b.maps.find(n=>n.id===maps[4])!.geographyId)!;const retained=structuredClone(m.interiorLinks);await service.changeAtlas("world-god",worldId,{action:"archive-floor",id:floor.id,revision:floor.revision});await assert.rejects(()=>service.getAtlas("world-god",worldId,false,maps[4]),/unavailable/);await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"create",name:"Archived floor bypass",description:"",scope:"local",geographyId:floor.id}),/unavailable/);const retainedDuplicate=await service.changeAtlas("world-god",worldId,{action:"duplicate",id:m.id,revision:m.revision,newId:id(),name:"Retained unavailable destination copy"});assert.deepEqual((await service.getAtlas("world-god",worldId,false,retainedDuplicate)).maps.find(n=>n.id===retainedDuplicate)!.interiorLinks,retained);b=await service.getAtlas("world-god",worldId,false,m.id);assert.equal(b.maps.find(n=>n.id===maps[4])!.unavailable,true);assert.deepEqual(b.maps.find(n=>n.id===m.id)!.interiorLinks,retained);d=draftOf(b.maps.find(n=>n.id===m.id)!,b.geographies);await service.changeAtlas("world-god",worldId,{action:"save",id:m.id,revision:b.maps.find(n=>n.id===m.id)!.revision,draft:d});floor=b.floors!.find(f=>f.id===floor.id)!;await service.changeAtlas("world-god",worldId,{action:"restore-floor",id:floor.id,revision:floor.revision});await service.getAtlas("world-god",worldId,false,maps[4]);
 b=await service.getAtlas("world-god",worldId);floor=b.floors!.find(f=>f.id===floor.id)!;await service.changeAtlas("world-god",worldId,{action:"edit-floor",id:floor.id,revision:floor.revision,geographyRevision:floor.geographyRevision,draft:{name:floor.name,description:floor.description,label:floor.label,order:2,elevation:floor.elevation}});b=await service.getAtlas("world-god",worldId);assert.equal(b.floors!.find(f=>f.id===floor.id)!.order,2);assert.equal(b.maps.find(n=>n.id===maps[4])!.geographyId,floor.id);
 const dense=await service.changeAtlas("world-god",worldId,{action:"floor-map",floorId:floor.id,name:"Dense interior performance"});b=await service.getAtlas("world-god",worldId,false,dense);m=b.maps.find(n=>n.id===dense)!;const started=performance.now();await service.changeAtlas("world-god",worldId,{action:"save",id:dense,revision:m.revision,draft:furnish(m,b,0,true)});const elapsed=performance.now()-started;
 b=await service.getAtlas("world-god",worldId,false,maps[1]);assert.ok(b.maps.filter(n=>n.id!==maps[1]).every(n=>!n.interiorShapes));assert.equal(b.floors!.filter(f=>f.buildingId===buildingId).length,5);assert.equal((await pool.query("select count(*)::int as n from world_settlement_entity where geography_id=$1",[buildingId])).rows[0].n,1);
 console.log(`PASS: interiors preserve the existing building, five floor identities, attached openings, non-linear stairs/portal arrivals, duplicate-map sharing, CAS, retained archive links, authorization and same-World DB constraints; dense 960-object save ${elapsed.toFixed(0)}ms.`);return {worldId,buildingId,exterior,maps,dense,copy};
}
async function login(c:BrowserContext,url:string,user="world-god"){const r=await c.request.post(`${url}/api/auth/sign-in/email`,{headers:{Origin:url},data:{email:`${user}@example.invalid`,password:"Worlds-Test-Only-Password!"}});assert.equal(r.status(),200,await r.text());}
export async function interiorBrowserChecks(browser:Browser,baseUrl:string,f:Fixture,pool:pg.Pool,evidence="docs/screenshots/worlds-atlas-pass-3e-b"){
 const capture=path.resolve(evidence);await mkdir(capture,{recursive:true});const c=await browser.newContext({viewport:{width:1440,height:1100},hasTouch:true,extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.113"}});await login(c,baseUrl);const page=await c.newPage(),errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));let acceptDialogs=true;page.on("dialog",d=>acceptDialogs?d.accept():d.dismiss());const api=`${baseUrl}/api/worlds/${f.worldId}/atlas`,url=`${baseUrl}/worlds/${f.worldId}`;
 async function read(mapId?:string){const r=await c.request.get(`${api}${mapId?`?map=${mapId}`:""}`);assert.equal(r.status(),200,await r.text());return await r.json() as AtlasBundle;}
 async function library(p=page){await p.goto(url);await p.getByRole("button",{name:"Atlas",exact:true}).click();await p.getByRole("heading",{name:"Atlas",exact:true}).waitFor();}
 async function open(name:string,p=page){await library(p);await p.getByRole("button",{name:`Open ${name}`,exact:true}).click();await p.getByRole("region",{name:"Interior floor-plan editor"}).waitFor();await p.locator("svg [data-interior]").first().waitFor();}
 async function shot(name:string,p=page){await p.evaluate(()=>window.scrollTo(0,0));await p.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));await captureWorldsScreenshot(p,{path:path.join(capture,name),fullPage:true});}

 const canvas=()=>page.getByRole("img",{name:/editable floor plan/});
 async function tap(x:number,y:number){const screen=await canvas().evaluate((node,point)=>{const m=(node as SVGSVGElement).getScreenCTM()!;return {x:m.a*point.x+m.c*point.y+m.e,y:m.b*point.x+m.d*point.y+m.f};},{x,y});await page.mouse.click(screen.x,screen.y);}
 await open("Ground reception plan");await page.getByRole("button",{name:"Wall path",exact:true}).click();await tap(100,400);acceptDialogs=false;await page.getByRole("button",{name:"Map library",exact:true}).click();await page.getByText("1 unfinished points",{exact:true}).waitFor();acceptDialogs=true;await page.getByRole("button",{name:"Cancel drawing",exact:true}).click();await page.getByRole("button",{name:"Select",exact:true}).click();await page.getByRole("button",{name:"Reading hall",exact:true}).click();await page.getByLabel("Object description",{exact:true}).fill("Unapplied fields remain protected.");acceptDialogs=false;await page.getByRole("button",{name:"Map library",exact:true}).click();assert.equal(await page.getByLabel("Object description",{exact:true}).inputValue(),"Unapplied fields remain protected.");acceptDialogs=true;await page.getByRole("button",{name:"Discard object fields",exact:true}).click();await shot("01-editor-desktop.png");const source=await read(f.maps[1]),map=source.maps.find(m=>m.id===f.maps[1])!,room=map.interiorEntities!.find(e=>e.name==="Reading hall")!;
 await page.getByRole("button",{name:"Reading hall",exact:true}).click();await shot("02-room-properties.png");await page.getByLabel("Object description",{exact:true}).fill("Reading hall verified through real browser editing.");await page.getByRole("button",{name:"Apply information",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();assert.equal((await read(f.maps[1])).maps.find(m=>m.id===f.maps[1])!.interiorEntities!.find(e=>e.id===room.id)!.description,"Reading hall verified through real browser editing.");
 await page.getByRole("button",{name:"Main entrance",exact:true}).click();await shot("03-attached-opening.png");const opening=map.interiorShapes!.find(s=>s.entityId===map.interiorEntities!.find(e=>e.name==="Main entrance")!.id)!;assert.equal(opening.variant,"opening");if(opening.variant==="opening"){const anchor=openingAnchor(opening,map.interiorShapes!);const wallNode=page.locator(`[data-interior="${opening.wallId}"]`);const paths=await wallNode.locator("path").evaluateAll(nodes=>nodes.map(n=>n.getAttribute("d")??""));assert.ok(paths.length>=10);assert.ok(!paths.some(d=>d===`M ${anchor.a.x} ${anchor.a.y} L ${anchor.b.x} ${anchor.b.y}`),"Wall rendering must split the attached segment, not paint a door over a solid line.");}
 await page.getByRole("button",{name:"The Keeper's desk",exact:true}).click();await shot("04-furnishing-properties.png");await page.getByLabel("Rotation",{exact:true}).fill("30");await page.getByRole("button",{name:"Apply information",exact:true}).click();await page.getByRole("button",{name:"Move right",exact:true}).click();await page.getByRole("button",{name:"Enlarge object",exact:true}).click();await page.getByRole("button",{name:"Duplicate object",exact:true}).click();await page.getByRole("button",{name:"Archive object",exact:true}).click();await page.getByRole("button",{name:"Restore object",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Rectangle room",exact:true}).click();await tap(90,90);await tap(220,210);await page.getByLabel("Object name",{exact:true}).fill("Browser-created room");await page.getByRole("button",{name:"Apply information",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Boundary point",{exact:true}).selectOption({label:"Point 1"});await page.getByLabel("Point X",{exact:true}).fill("95");await page.getByRole("button",{name:"Apply point",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Select",exact:true}).click();await page.getByRole("button",{name:"Browser-created room",exact:true}).click();await page.getByRole("button",{name:"Duplicate object",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();const roomCopies=(await read(f.maps[1])).maps.find(m=>m.id===f.maps[1])!.interiorEntities!.filter(e=>e.name.startsWith("Browser-created room"));assert.equal(roomCopies.length,2);assert.notEqual(roomCopies[0].id,roomCopies[1].id);
 await page.getByRole("button",{name:"Outer boundary",exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Boundary point",{exact:true}).selectOption({label:"Point 1"});await page.getByRole("button",{name:"Remove point",exact:true}).click();await page.getByRole("alert").filter({hasText:/removes a segment/}).waitFor();await page.getByLabel("Point X",{exact:true}).fill("250");await page.getByRole("button",{name:"Apply point",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();const attached=(await read(f.maps[1])).maps.find(m=>m.id===f.maps[1])!;for(const opening of attached.interiorShapes!)if(opening.variant==="opening"&&!opening.archived)openingAnchor(opening,attached.interiorShapes!);
 await page.getByText("Interior layers",{exact:true}).click();await page.getByLabel("opening locked",{exact:true}).check();await page.getByRole("button",{name:"Move right",exact:true}).isDisabled().then(disabled=>assert.equal(disabled,true));await page.getByLabel("opening locked",{exact:true}).uncheck();await page.getByText("Interior layers",{exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();
 await shot("05-completed-interior.png");await page.getByLabel("Choose floor map",{exact:true}).selectOption(f.maps[0]);await page.getByRole("heading",{name:"Basement archives plan",exact:true}).waitFor();await shot("06-floor-navigation-basement.png");await page.getByLabel("Choose floor map",{exact:true}).selectOption(f.maps[1]);await page.getByRole("heading",{name:"Ground reception plan",exact:true}).waitFor();await page.getByRole("button",{name:"Spiral stairs",exact:true}).first().click();await shot("07-transition-properties.png");
 const other=await c.newPage();await open("Ground reception plan",other);const sharedTab=await c.newPage();await open("Ground decorative reference",sharedTab);await page.getByRole("button",{name:"Reading hall",exact:true}).click();await page.getByLabel("Object description",{exact:true}).fill("Winning tab interior edit.");await page.getByRole("button",{name:"Apply information",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();await other.getByRole("button",{name:"Reading hall",exact:true}).click();await other.getByLabel("Object description",{exact:true}).fill("Losing draft remains recoverable.");await other.getByRole("button",{name:"Apply information",exact:true}).click();await other.getByRole("button",{name:"Save interior",exact:true}).click();await other.getByRole("alert").filter({hasText:/newer/}).waitFor();assert.equal(await other.getByLabel("Object description",{exact:true}).inputValue(),"Losing draft remains recoverable.");const download=other.waitForEvent("download");await other.getByRole("button",{name:"Download interior draft",exact:true}).click();assert.ok((await download).suggestedFilename().endsWith(".json"));await other.close();await sharedTab.getByRole("button",{name:"Reading hall",exact:true}).click();await sharedTab.getByLabel("Object description",{exact:true}).fill("Stale shared-room metadata.");await sharedTab.getByRole("button",{name:"Apply information",exact:true}).click();await sharedTab.getByRole("button",{name:"Save interior",exact:true}).click();await sharedTab.getByRole("alert").filter({hasText:/another|newer/}).waitFor();assert.equal(await sharedTab.getByLabel("Object description",{exact:true}).inputValue(),"Stale shared-room metadata.");await sharedTab.close();
 await page.getByRole("button",{name:"Explore interior",exact:true}).click();await page.getByRole("region",{name:"Map explorer"}).waitFor();await page.getByRole("button",{name:"Spiral stairs",exact:true}).first().click();await page.getByRole("button",{name:/Open Floating wing plan/}).click();await page.getByRole("heading",{name:"Floating wing plan",exact:true}).waitFor();assert.equal(new URL(page.url()).searchParams.get("place"),(await read(f.maps[3])).maps.find(m=>m.id===f.maps[3])!.interiorEntities!.find(e=>e.name==="Spiral stairs")!.id);await shot("08-authored-stair-arrival.png");await page.goBack();await page.getByRole("heading",{name:"Ground reception plan",exact:true}).waitFor();await page.getByRole("button",{name:"Mirror portal",exact:true}).first().click();await page.getByRole("button",{name:/Open Beyond the Mirror plan/}).click();await page.getByRole("heading",{name:"Beyond the Mirror plan",exact:true}).waitFor();await page.reload();await page.getByRole("heading",{name:"Beyond the Mirror plan",exact:true}).waitFor();await shot("09-explore-interior.png");await page.goBack();await page.getByRole("heading",{name:"Ground reception plan",exact:true}).waitFor();let portalBundle=await read(f.maps[1]),portalFloor=portalBundle.floors!.find(fl=>fl.id===portalBundle.maps.find(m=>m.id===f.maps[4])!.geographyId)!;let lifecycle=await c.request.post(api,{headers:{Origin:baseUrl},data:{action:"archive-floor",id:portalFloor.id,revision:portalFloor.revision}});assert.equal(lifecycle.status(),200);await page.reload();await page.getByRole("heading",{name:"Ground reception plan",exact:true}).waitFor();await page.getByRole("button",{name:"Mirror portal",exact:true}).first().click();await page.getByText(/Beyond the Mirror plan.*unavailable for exploration/).waitFor();assert.equal(await page.getByRole("button",{name:/Open Beyond the Mirror plan/}).count(),0);portalBundle=await read(f.maps[1]);portalFloor=portalBundle.floors!.find(fl=>fl.id===portalFloor.id)!;lifecycle=await c.request.post(api,{headers:{Origin:baseUrl},data:{action:"restore-floor",id:portalFloor.id,revision:portalFloor.revision}});assert.equal(lifecycle.status(),200);await page.reload();await page.getByRole("heading",{name:"Ground reception plan",exact:true}).waitFor();await page.getByRole("button",{name:"Mirror portal",exact:true}).first().click();await page.getByRole("button",{name:/Open Beyond the Mirror plan/}).click();await page.getByRole("heading",{name:"Beyond the Mirror plan",exact:true}).waitFor();await page.getByRole("button",{name:"Return to exterior: Observatory exterior",exact:true}).click();await page.getByRole("heading",{name:"Observatory exterior",exact:true}).waitFor();await page.getByRole("region",{name:"Building floors"}).waitFor();await shot("10-exterior-interior-choices.png");
 await page.getByRole("button",{name:"Add floor",exact:true}).click();await page.getByRole("dialog",{name:"Create an interior floor"}).waitFor();await page.getByLabel("Floor name",{exact:true}).fill("Browser mezzanine");await page.getByLabel("Floor-plan map name",{exact:true}).fill("Browser mezzanine plan");await page.getByRole("button",{name:"Create floor map",exact:true}).click();await page.getByRole("heading",{name:"Browser mezzanine plan",exact:true}).waitFor();await page.getByRole("button",{name:"Wall path",exact:true}).click();await tap(500,300);await tap(1300,300);await page.getByRole("button",{name:"Complete drawing",exact:true}).click();await page.getByRole("button",{name:"Door / opening",exact:true}).click();await tap(900,300);await page.getByLabel("Object name",{exact:true}).fill("Browser wall door");await page.getByRole("button",{name:"Apply information",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();await page.getByRole("button",{name:"Map library",exact:true}).click();
 await open("Ground reception plan");await page.setViewportSize({width:390,height:844});await page.getByRole("button",{name:"Furnishing",exact:true}).click();await canvas().scrollIntoViewIfNeeded();const bounds=await canvas().boundingBox();assert.ok(bounds);const touchX=bounds.x+bounds.width*.18,touchY=bounds.y+bounds.height*.18;const logical=await canvas().evaluate((node,p)=>{const xy=new DOMPoint(p.x,p.y).matrixTransform((node as SVGSVGElement).getScreenCTM()!.inverse());return {x:Math.round(xy.x*100)/100,y:Math.round(xy.y*100)/100};},{x:touchX,y:touchY});await page.touchscreen.tap(touchX,touchY);await page.getByLabel("Object name",{exact:true}).fill("Phone table");await page.getByRole("button",{name:"Apply information",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();const phoneSaved=await read(f.maps[1]),phoneEntity=phoneSaved.maps.find(m=>m.id===f.maps[1])!.interiorEntities!.find(e=>e.name==="Phone table")!,phoneShape=phoneSaved.maps.find(m=>m.id===f.maps[1])!.interiorShapes!.find(s=>s.entityId===phoneEntity.id)!;assert.equal(phoneShape.variant,"object");if(phoneShape.variant==="object")assert.deepEqual(phoneShape.point,logical);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 async function phoneTap(x:number,y:number){await canvas().scrollIntoViewIfNeeded();const p=await canvas().evaluate((node,logical)=>{const m=(node as SVGSVGElement).getScreenCTM()!;return {x:m.a*logical.x+m.c*logical.y+m.e,y:m.b*logical.x+m.d*logical.y+m.f};},{x,y});await page.touchscreen.tap(p.x,p.y);}
 await page.getByRole("button",{name:"Rectangle room",exact:true}).click();await phoneTap(70,760);await phoneTap(220,990);await page.getByLabel("Object name",{exact:true}).fill("Phone room");await page.getByRole("button",{name:"Apply information",exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Boundary point",{exact:true}).selectOption({label:"Point 1"});await page.getByLabel("Point X",{exact:true}).fill("75");await page.getByRole("button",{name:"Apply point",exact:true}).click();
 await page.getByRole("button",{name:"Door / opening",exact:true}).click();await phoneTap(1450,140);await page.getByLabel("Object name",{exact:true}).fill("Phone door");assert.equal(await page.locator("input:invalid").count(),0);await page.getByRole("button",{name:"Apply information",exact:true}).click();
 await page.getByRole("button",{name:"Select",exact:true}).click();await page.getByRole("button",{name:"Phone table",exact:true}).first().click();await page.getByRole("button",{name:"Move",exact:true}).click();await canvas().scrollIntoViewIfNeeded();const startTouch=await canvas().evaluate((node,p)=>{const m=(node as SVGSVGElement).getScreenCTM()!;return {x:m.a*p.x+m.e,y:m.d*p.y+m.f,dx:m.a*70,dy:m.d*40};},logical);const native=await c.newCDPSession(page);await native.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:startTouch.x,y:startTouch.y,id:1}]});await native.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:startTouch.x+startTouch.dx,y:startTouch.y+startTouch.dy,id:1}]});await native.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await native.detach();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();const touchSaved=(await read(f.maps[1])).maps.find(m=>m.id===f.maps[1])!,movedPhone=touchSaved.interiorShapes!.find(s=>s.entityId===phoneEntity.id)!;assert.equal(movedPhone.variant,"object");if(movedPhone.variant==="object"){assert.ok(Math.abs(movedPhone.point.x-logical.x-70)<=.2);assert.ok(Math.abs(movedPhone.point.y-logical.y-40)<=.2);}assert.ok(touchSaved.interiorEntities!.some(e=>e.name==="Phone room"));assert.ok(touchSaved.interiorEntities!.some(e=>e.name==="Phone door"));await shot("11-phone-editor.png");await page.getByLabel("Choose floor map",{exact:true}).selectOption(f.maps[0]);await page.getByRole("heading",{name:"Basement archives plan",exact:true}).waitFor();await page.getByLabel("Choose floor map",{exact:true}).selectOption(f.maps[1]);await page.getByRole("heading",{name:"Ground reception plan",exact:true}).waitFor();await page.getByRole("button",{name:"Explore interior",exact:true}).click();await page.getByRole("region",{name:"Map explorer"}).waitFor();await page.getByRole("button",{name:"Phone table",exact:true}).first().click();await shot("12-phone-explore.png");assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.setViewportSize({width:1440,height:1100});const start=performance.now();await open("Dense interior performance");const loadMs=performance.now()-start;assert.equal(await page.locator("svg [data-interior]").count(),960);const panStart=performance.now();await page.getByRole("button",{name:"Pan",exact:true}).click();await canvas().scrollIntoViewIfNeeded();const box=await canvas().boundingBox();assert.ok(box);await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.62,box.y+box.height*.58,{steps:18});await page.mouse.up();const panMs=performance.now()-panStart;await shot("13-dense-interior.png");const payload=await c.request.get(`${api}?map=${f.dense}`),payloadBytes=(await payload.body()).byteLength;const metrics={objects:960,loadMs:Math.round(loadMs),panMs:Math.round(panMs),payloadBytes,otherFloorSourcesLoaded:(await payload.json() as AtlasBundle).maps.filter(m=>m.id!==f.dense&&m.interiorShapes).length};assert.equal(metrics.otherFloorSourcesLoaded,0);assert.ok(loadMs<30000);await writeFile(path.join(capture,"performance.json"),JSON.stringify(metrics,null,2)+"\n");
 const anonymous=await browser.newContext();assert.ok([401,403].includes((await anonymous.request.get(`${api}?map=${f.maps[1]}`)).status()));await anonymous.close();
 for(const user of ["other-god","world-player","world-admin"]){const unauthorized=await browser.newContext();await login(unauthorized,baseUrl,user);assert.equal((await unauthorized.request.get(`${api}?map=${f.maps[1]}`)).status(),user==="world-player"?403:404);assert.equal((await unauthorized.request.post(api,{headers:{Origin:baseUrl},data:{action:"floor-map",floorId:phoneSaved.maps.find(m=>m.id===f.maps[1])!.geographyId,name:"Unauthorized"}})).status(),user==="world-player"?403:404);if(user==="world-admin"){const admin=await unauthorized.newPage();await admin.goto(`${url}?review=1&atlas=${f.maps[1]}`);await admin.getByRole("region",{name:"Map explorer"}).waitFor();assert.equal(await admin.getByRole("button",{name:"Edit map",exact:true}).count(),0);assert.equal(await admin.getByRole("button",{name:"Add floor",exact:true}).count(),0);}await unauthorized.close();}
 assert.ok((await pool.query("select count(*)::int as n from world_interior_floor where building_id=$1",[f.buildingId])).rows[0].n>=6);assert.deepEqual(errors,[]);console.log(`PASS: actual interior editor/Explore, attached wall-gap DOM, room/furnishing lifecycle, point editing, two-tab conflict/download, five-floor choices, non-linear stairs/portal arrival, browser history/reload, exterior creation, phone touch persistence, admin/private authorization; 960-object metrics ${JSON.stringify(metrics)}.`);await c.close();
}

/** Runs against the same isolated production server; uses only its disposable fixture World. */
export async function interiorPerformanceChecks(browser:Browser,baseUrl:string,worldId:string,evidence="docs/screenshots/worlds-atlas-pass-3e-b"){
 const c=await browser.newContext({viewport:{width:1440,height:1100},extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.114"}});await login(c,baseUrl);const api=`${baseUrl}/api/worlds/${worldId}/atlas`,headers=await c.request.get(api);assert.equal(headers.status(),200);const b=await headers.json() as AtlasBundle,dense=b.maps.find(m=>m.name==="Dense interior performance")!,basement=b.maps.find(m=>m.name==="Basement archives plan")!;assert.ok(dense&&basement);
 const requestStart=performance.now(),r=await c.request.get(`${api}?map=${dense.id}`);assert.equal(r.status(),200);const source=await r.json() as AtlasBundle,sourceReadMs=performance.now()-requestStart,original=source.maps.find(m=>m.id===dense.id)!,entity=original.interiorEntities!.find(e=>e.name==="Instrument 0")!,shape=original.interiorShapes!.find(s=>s.entityId===entity.id)!;assert.equal(shape.variant,"object");
 const page=await c.newPage();await page.goto(`${baseUrl}/worlds/${worldId}`);await page.getByRole("button",{name:"Atlas",exact:true}).click();const loadStart=performance.now();await page.getByRole("button",{name:"Open Dense interior performance",exact:true}).click();await page.locator("svg [data-interior]").first().waitFor();const editorLoadMs=performance.now()-loadStart;
 const selectionStart=performance.now();await page.getByRole("button",{name:"Instrument 0",exact:true}).click();await page.getByLabel("Object name",{exact:true}).waitFor();const selectionMs=performance.now()-selectionStart,editStart=performance.now();await page.getByRole("button",{name:"Move right",exact:true}).click();const changed=await page.locator(`[data-interior="${shape.id}"]`).getAttribute("transform");assert.ok(changed?.startsWith("translate(100 70)"));const editingMs=performance.now()-editStart;
 const saveStart=performance.now();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();const saveMs=performance.now()-saveStart,saved=await (await c.request.get(`${api}?map=${dense.id}`)).json() as AtlasBundle,moved=saved.maps.find(m=>m.id===dense.id)!.interiorShapes!.find(s=>s.id===shape.id)!;assert.equal(moved.variant,"object");if(moved.variant==="object")assert.deepEqual(moved.point,{x:100,y:70});assert.equal(moved.entityId,shape.entityId);
 await page.getByRole("button",{name:"Move left",exact:true}).click();await page.getByRole("button",{name:"Save interior",exact:true}).click();await page.getByText("Interior saved.",{exact:true}).waitFor();const floorStart=performance.now();await page.getByLabel("Choose floor map",{exact:true}).selectOption(basement.id);await page.getByRole("heading",{name:"Basement archives plan",exact:true}).waitFor();await page.locator("svg [data-interior]").first().waitFor();const floorNavigationMs=performance.now()-floorStart;
 const destination=await (await c.request.get(`${api}?map=${basement.id}`)).json() as AtlasBundle;assert.ok(destination.maps.filter(m=>m.id!==basement.id).every(m=>!m.interiorShapes));
 const file=path.resolve(evidence,"performance.json");const previous=JSON.parse(await (await import("node:fs/promises")).readFile(file,"utf8"));const measurements={...previous,sourceReadMs:Math.round(sourceReadMs),editorLoadMs:Math.round(editorLoadMs),selectionMs:Math.round(selectionMs),editingMs:Math.round(editingMs),saveMs:Math.round(saveMs),floorNavigationMs:Math.round(floorNavigationMs)};for(const value of [sourceReadMs,editorLoadMs,selectionMs,editingMs,saveMs,floorNavigationMs])assert.ok(value<30000);await writeFile(file,JSON.stringify(measurements,null,2)+"\n");console.log(`PASS: dense source loading, selection, exact-coordinate editing, save/reload identity and floor navigation measurements ${JSON.stringify(measurements)}.`);await c.close();
}
