import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import type pg from "pg";
import type { Browser, Page } from "playwright-core";
import { draftOf, polygonCenter, rounded, type AtlasBundle } from "../src/features/worlds/atlas";
import { generateMap } from "../src/features/worlds/map-generator";
import { presetSpec, type Preset } from "../src/features/worlds/generation-spec";
import { descriptionExample, interpretDescription } from "../src/features/worlds/description-interpreter";
import { bounds, edgeDistance } from "../src/features/worlds/generation-geometry";
type Service=typeof import("../src/features/worlds/atlas-service");
const equivalent=(value:unknown)=>JSON.parse(JSON.stringify(value,(key,v)=>key==="id"||key==="geographyId"?undefined:v));
export async function generationServiceChecks(service:Service,pool:pg.Pool,worldId:string,foreignWorld:string){
  const sourceBefore=await service.getAtlas("other-god",worldId),spec=presetSpec("northern","service-generation-42"),id=randomUUID();
  const command={action:"generate",id,name:"Seeded northern chart",description:"Private synthetic generation context",spec,sourceMapId:null,sourceRevision:null};
  const responses=await Promise.all([service.changeAtlas("other-god",worldId,command),service.changeAtlas("other-god",worldId,command)]);assert.deepEqual(responses,[id,id]);
  let bundle=await service.getAtlas("other-god",worldId),map=bundle.maps.find(m=>m.id===id)!;assert.equal(bundle.maps.filter(m=>m.id===id).length,1);
  assert.deepEqual(equivalent(map.features.map(f=>f.geometry)).sort((a:unknown,b:unknown)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),equivalent(generateMap(spec,randomUUID).draft.features.map(f=>f.geometry)).sort((a:unknown,b:unknown)=>JSON.stringify(a).localeCompare(JSON.stringify(b))));
  assert.equal(map.generation!.createdBy,"other-god");assert.deepEqual(map.generation!.spec,spec);
  const provenance=structuredClone(map.generation),edited=draftOf(map,bundle.geographies);edited.name="Manually named northern chart";const range=edited.drawings!.find(d=>d.type==="terrain"&&d.kind==="mountains")!;if(range.type!=="terrain")throw new Error("No generated range.");range.points[0].x=rounded(range.points[0].x+4);await service.changeAtlas("other-god",worldId,{action:"save",id,revision:map.revision,draft:edited});
  bundle=await service.getAtlas("other-god",worldId);map=bundle.maps.find(m=>m.id===id)!;assert.deepEqual(map.generation,provenance);
  assert.equal(await service.changeAtlas("other-god",worldId,command),id,"Retrying acknowledged creation never regenerates manually edited source.");
  assert.deepEqual((await service.getAtlas("other-god",worldId)).maps.find(m=>m.id===id),map);
  const copyId=randomUUID(),copyCommand={action:"duplicate",id,revision:map.revision,newId:copyId,name:"Northern chart copy"};await service.changeAtlas("other-god",worldId,copyCommand);await service.changeAtlas("other-god",worldId,copyCommand);
  bundle=await service.getAtlas("other-god",worldId);const copy=bundle.maps.find(m=>m.id===copyId)!;assert.deepEqual(copy.features.map(f=>f.geographyId).sort(),map.features.map(f=>f.geographyId).sort());assert.deepEqual(equivalent([...copy.features].sort((a,b)=>a.geographyId.localeCompare(b.geographyId))),equivalent([...map.features].sort((a,b)=>a.geographyId.localeCompare(b.geographyId))));assert.deepEqual(equivalent(copy.drawings),equivalent(map.drawings));assert.ok(copy.features.every(f=>!map.features.some(old=>old.id===f.id)));assert.ok(copy.drawings!.every(d=>!map.drawings!.some(old=>old.id===d.id)));assert.equal(copy.generation!.sourceMapId,id);
  const alternate=randomUUID();await service.changeAtlas("other-god",worldId,{...command,id:alternate,name:"New starting design",spec:presetSpec("continental","service-variation-43"),sourceMapId:copyId,sourceRevision:copy.revision});
  bundle=await service.getAtlas("other-god",worldId);assert.deepEqual(bundle.maps.find(m=>m.id===id),map);assert.deepEqual(bundle.maps.find(m=>m.id===copyId),copy);
  for(const original of sourceBefore.maps)assert.deepEqual(bundle.maps.find(m=>m.id===original.id),original);for(const original of sourceBefore.geographies)assert.deepEqual(bundle.geographies.find(g=>g.id===original.id),original);
  const beforeFailure=structuredClone(bundle),foreignMap=(await pool.query("select id from world_atlas_map where world_id=$1 limit 1",[foreignWorld])).rows[0].id;
  for(const input of [{...command,id:randomUUID(),spec:{...spec,settings:{...spec.settings,continents:999}}},{...command,id:randomUUID(),sourceMapId:foreignMap,sourceRevision:1},{...command,id:randomUUID(),sourceMapId:copyId,sourceRevision:1},{...copyCommand,newId:randomUUID(),id:foreignMap},{...command,id:randomUUID(),generation:{createdBy:"world-admin"}}])await assert.rejects(service.changeAtlas("other-god",worldId,input));
  assert.deepEqual(await service.getAtlas("other-god",worldId),beforeFailure);
  const describedSpec=interpretDescription(descriptionExample,presetSpec("continental","description-service-2026")),describedId=randomUUID(),describedCommand={...command,id:describedId,name:"Description service chart",spec:describedSpec};
  await assert.rejects(service.changeAtlas("other-god",worldId,describedCommand),/acknowledge/);
  for(const spec of [{...describedSpec,plan:{...describedSpec.plan,forestRegion:"north"}},{...describedSpec,interpretation:{...describedSpec.interpretation!,warnings:[]}},{...describedSpec,interpretation:{...describedSpec.interpretation!,understood:["An invented city"]}}])await assert.rejects(service.changeAtlas("other-god",worldId,{...describedCommand,spec,descriptionWarningsAccepted:true}),/do not match/);
  assert.deepEqual(await service.getAtlas("other-god",worldId),beforeFailure);
  const acceptedDescription={...describedCommand,descriptionWarningsAccepted:true};await service.changeAtlas("other-god",worldId,acceptedDescription);
  bundle=await service.getAtlas("other-god",worldId);let described=bundle.maps.find(m=>m.id===describedId)!;assert.deepEqual(described.generation!.spec,describedSpec);const originalRecipe=structuredClone(described.generation),descriptionDraft=draftOf(described,bundle.geographies),wood=descriptionDraft.drawings!.find(d=>d.type==="terrain"&&d.kind==="forest")!;if(wood.type!=="terrain")throw new Error("No description forest.");wood.density=1;await service.changeAtlas("other-god",worldId,{action:"save",id:describedId,revision:described.revision,draft:descriptionDraft});await service.changeAtlas("other-god",worldId,acceptedDescription);described=(await service.getAtlas("other-god",worldId)).maps.find(m=>m.id===describedId)!;assert.deepEqual(described.generation,originalRecipe);assert.equal((described.drawings!.find(d=>d.id===wood.id) as typeof wood).density,1);
  for(const who of ["world-god","world-admin","world-player"]){await assert.rejects(service.getAtlas(who,worldId));await assert.rejects(service.changeAtlas(who,worldId,{...command,id:randomUUID()}));await assert.rejects(service.changeAtlas(who,worldId,{...copyCommand,newId:randomUUID()}));}assert.equal((await service.getAtlas("world-admin",worldId,true)).canEdit,false);
  for(const patch of [{kind:null},{spec:{...spec,algorithm:null}},{spec:{...spec,algorithm:"serrian-atlas-v3"}},{spec:{...spec,version:2}},{spec:{...spec,settings:{...spec.settings,style:null}}},{spec:{...spec,plan:{...spec.plan,baySide:null}}},{createdBy:null},{extra:true}]){const rowId=randomUUID(),metadata={...provenance,...patch,requestId:rowId};await assert.rejects(pool.query("insert into world_atlas_map(id,world_id,name,generation) values($1,$2,'Invalid metadata',$3)",[rowId,worldId,metadata]),/check constraint/);}
  const rowId=randomUUID(),foreignMetadata={...provenance,requestId:rowId,sourceMapId:foreignMap,sourceRevision:1};await assert.rejects(pool.query("insert into world_atlas_map(id,world_id,name,generation,source_map_id) values($1,$2,'Cross-World source',$3,$4)",[rowId,worldId,foreignMetadata,foreignMap]),/foreign key/);await assert.rejects(pool.query("insert into world_atlas_map(id,world_id,name,source_map_id) values($1,$2,'Missing metadata',$3)",[randomUUID(),worldId,id]),/check constraint/);
  console.log("PASS: seeded and description-derived ordinary-source persistence, immutable recipes through manual edits, explicit description-limit acknowledgment and server re-interpretation/forgery rejection, concurrent/idempotent creation, independent duplicate drawings with same-World geography links, safe new-map variations, unchanged originals, invalid metadata/SQL rejection and all role/source-reference privacy.");
  return {worldId};
}
async function openAtlas(page:Page,url:string){await page.goto(url);await page.getByRole("button",{name:"Atlas",exact:true}).click();await page.getByRole("heading",{name:"Atlas",exact:true}).waitFor();}
async function save(page:Page){await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByRole("status").filter({hasText:"Map saved."}).waitFor();}
async function point(page:Page,x:number,y:number){const svg=page.getByRole("application",{name:"Editable map canvas"});await svg.scrollIntoViewIfNeeded();return svg.evaluate((node,p)=>{const m=(node as SVGSVGElement).getScreenCTM()!;const q=new DOMPoint(p.x,p.y).matrixTransform(m);return{x:q.x,y:q.y};},{x,y});}
export async function generationBrowserChecks(browser:Browser,baseUrl:string,f:{worldId:string},artifacts:string,captureDirectory="docs/screenshots/worlds-atlas-refinement/regressions"){
  const captures=path.resolve(captureDirectory);await mkdir(captures,{recursive:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100},hasTouch:false,extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.51"}}),page=await context.newPage(),errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  const signed=await context.request.post(`${baseUrl}/api/auth/sign-in/email`,{headers:{Origin:baseUrl},data:{email:"other-god@example.invalid",password:"Worlds-Test-Only-Password!"}});assert.equal(signed.status(),200);
  const url=`${baseUrl}/worlds/${f.worldId}`,api=`${baseUrl}/api/worlds/${f.worldId}/atlas`,read=async()=>{const r=await context.request.get(api);assert.equal(r.status(),200);return await r.json() as AtlasBundle;};
  try{
    for(const [preset,seed,file] of [["continental","atlas-world-2026","continental-world.png"],["northern","atlas-north-2026","northern-continent.png"],["archipelago","atlas-islands-2026","archipelago.png"],["rugged","atlas-rugged-2026","rugged-world.png"]] as [Preset,string,string][]){
      await openAtlas(page,url);await page.getByRole("button",{name:"Generate map",exact:true}).click();await page.getByLabel("Generation preset",{exact:true}).selectOption(preset);await page.getByLabel("Generation seed",{exact:true}).fill(seed);await page.getByRole("button",{name:"Preview map",exact:true}).click();await page.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();await page.getByLabel("Generated map artwork",{exact:true}).screenshot({path:path.join(captures,file)});
      if(preset==="continental"){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(captures,"generation-controls.png"),fullPage:true});}
      page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Map library",exact:true}).click();
    }
    await page.getByRole("button",{name:"Generate map",exact:true}).click();await page.getByLabel("Generation preset",{exact:true}).selectOption("northern");await page.getByLabel("Generation seed",{exact:true}).fill("editable-acceptance-2026");await page.getByRole("button",{name:"Preview map",exact:true}).click();await page.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();await page.getByLabel("Generated map name",{exact:true}).fill("Editable generated continent");
    await page.route(api,route=>route.request().method()==="POST"?route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary generated save failure"})}):route.continue());await page.getByRole("button",{name:"Save as new editable map",exact:true}).click();await page.getByRole("alert").getByText(/Temporary generated save failure/).waitFor();assert.ok(await page.getByLabel("Generated map artwork",{exact:true}).locator("[data-feature]").count()>0);await page.unroute(api);await page.getByRole("button",{name:"Save as new editable map",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();
    let bundle=await read();const original=bundle.maps.find(m=>m.name==="Editable generated continent")!,originalGeos=bundle.geographies.filter(g=>original.features.some(n=>n.geographyId===g.id));const continent=original.features.find(n=>originalGeos.find(g=>g.id===n.geographyId)?.kind==="continent")!,island=original.features.find(n=>originalGeos.find(g=>g.id===n.geographyId)?.kind==="island")!,mountain=original.drawings!.find(d=>d.type==="terrain"&&d.kind==="mountains")!,forest=original.drawings!.find(d=>d.type==="terrain"&&d.kind==="forest")!,river=original.drawings!.find(d=>d.type==="path")!;
    await openAtlas(page,url);await page.getByRole("button",{name:"Open Editable generated continent",exact:true}).click();await page.getByRole("button",{name:originalGeos.find(g=>g.id===continent.geographyId)!.name,exact:true}).click();await page.getByRole("button",{name:"Sculpt coast",exact:true}).click();await page.getByLabel("Coast brush size",{exact:true}).fill("160");if(continent.geometry.type!=="polygon")throw new Error("No generated polygon.");const coast=continent.geometry.points[40],a=await point(page,coast.x,coast.y),b=await point(page,coast.x,coast.y-45);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:12});await page.mouse.up();await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();
    await page.getByRole("button",{name:originalGeos.find(g=>g.id===island.geographyId)!.name,exact:true}).click();await page.getByRole("button",{name:"Move feature",exact:true}).click();await page.getByRole("button",{name:"Right",exact:true}).click();
    await page.getByRole("button",{name:mountain.name,exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Drawing point",{exact:true}).selectOption({index:1});if(mountain.type!=="terrain")throw new Error("No mountains.");await page.getByLabel("Drawing X",{exact:true}).fill(String(rounded(mountain.points[0].x+8)));await page.getByRole("button",{name:"Apply drawing position",exact:true}).click();
    await page.getByRole("button",{name:forest.name,exact:true}).click();await page.getByLabel("Stroke density",{exact:true}).fill("1");await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();
    await page.getByRole("button",{name:river.name,exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Drawing point",{exact:true}).selectOption({index:2});if(river.type!=="path")throw new Error("No river.");await page.getByLabel("Drawing Y",{exact:true}).fill(String(rounded(river.points[1].y+12)));await page.getByRole("button",{name:"Apply drawing position",exact:true}).click();
    await page.getByRole("button",{name:"Place symbol",exact:true}).click();await page.getByLabel("Symbol kind",{exact:true}).selectOption("city");const center=polygonCenter(continent.geometry.points),town=await point(page,center.x+150,center.y+90);await page.mouse.click(town.x,town.y);await page.getByLabel("Drawing name",{exact:true}).fill("Brightwatch");await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();await page.getByLabel("Linked geography name",{exact:true}).fill("Brightwatch");await page.getByRole("button",{name:"Apply linked geography",exact:true}).click();await save(page);
    await openAtlas(page,url);await page.getByRole("button",{name:"Open Editable generated continent",exact:true}).click();bundle=await read();const edited=bundle.maps.find(m=>m.id===original.id)!;assert.equal(edited.features.find(n=>n.id===continent.id)!.geographyId,continent.geographyId);assert.notDeepEqual(edited.features.find(n=>n.id===continent.id)!.geometry,continent.geometry);assert.notDeepEqual(edited.features.find(n=>n.id===island.id)!.geometry,island.geometry);assert.deepEqual(edited.generation,original.generation);
    for(const drawing of [mountain,forest,river]){const saved=edited.drawings!.find(n=>n.id===drawing.id)!;assert.notDeepEqual(saved,drawing);assert.equal(saved.type,drawing.type);if((saved.type==="terrain"||saved.type==="path")&&(drawing.type==="terrain"||drawing.type==="path"))assert.deepEqual(saved.points.map(p=>p.id),drawing.points.map(p=>p.id));}
    assert.ok(bundle.geographies.some(g=>g.name==="Brightwatch"));await page.getByRole("application",{name:"Editable map canvas"}).locator("..").screenshot({path:path.join(captures,"edited-generated-map.png")});
    await page.getByRole("button",{name:"Map library",exact:true}).click();await page.getByRole("button",{name:"Duplicate Editable generated continent",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();bundle=await read();const copy=bundle.maps.find(m=>m.name==="Editable generated continent copy")!;assert.equal(copy.generation!.sourceMapId,original.id);assert.ok(copy.features.every(n=>!edited.features.some(o=>o.id===n.id)));await page.getByRole("button",{name:"Map library",exact:true}).click();await page.getByRole("button",{name:"Generate variation of Editable generated continent copy",exact:true}).click();await page.getByLabel("Generation seed",{exact:true}).fill("alternate-design-2026");await page.getByRole("button",{name:"Preview map",exact:true}).click();await page.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();await page.getByLabel("Generated map name",{exact:true}).fill("Alternate northern design");await page.getByRole("button",{name:"Save as new editable map",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();bundle=await read();assert.deepEqual(bundle.maps.find(m=>m.id===original.id),edited);assert.deepEqual(bundle.maps.find(m=>m.id===copy.id),copy);for(const g of originalGeos)assert.deepEqual(bundle.geographies.find(n=>n.id===g.id),g);
    await page.getByRole("button",{name:"Map library",exact:true}).click();await page.getByRole("button",{name:"Generate map",exact:true}).click();await page.getByLabel("Creation method",{exact:true}).selectOption("describe");await page.getByLabel("Describe the geography",{exact:true}).fill("One continent. A volcano and two cities.");await page.getByRole("button",{name:"Interpret description",exact:true}).click();await page.getByRole("region",{name:"Description limits",exact:true}).waitFor();assert.equal(await page.getByRole("button",{name:"Preview map",exact:true}).isDisabled(),true);assert.match(await page.getByRole("region",{name:"Description limits",exact:true}).innerText(),/volcano/);assert.match(await page.getByRole("region",{name:"Description limits",exact:true}).innerText(),/cities/);
    await page.getByRole("button",{name:"Use example description",exact:true}).click();assert.equal(await page.getByRole("button",{name:"Preview map",exact:true}).isDisabled(),true);await page.getByRole("button",{name:"Interpret description",exact:true}).click();await page.getByRole("region",{name:"Reviewed geographic plan",exact:true}).waitFor();assert.match(await page.getByRole("region",{name:"Reviewed geographic plan",exact:true}).innerText(),/north-south/);await page.getByLabel("Generation seed",{exact:true}).fill("description-example-2026");await page.getByLabel("Use the supported plan despite these limits",{exact:true}).check();await page.getByRole("button",{name:"Preview map",exact:true}).click();await page.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();
    await page.getByLabel("Describe the geography",{exact:true}).fill(`${descriptionExample} No mountains.`);assert.equal(await page.getByRole("button",{name:"Save as new editable map",exact:true}).isDisabled(),true);await page.getByLabel("Describe the geography",{exact:true}).fill(descriptionExample);await page.getByRole("button",{name:"Interpret description",exact:true}).click();await page.getByLabel("Use the supported plan despite these limits",{exact:true}).check();await page.getByRole("button",{name:"Preview map",exact:true}).click();await page.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();await page.getByLabel("Generated map artwork",{exact:true}).screenshot({path:path.join(captures,"description-driven.png")});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(captures,"description-controls.png"),fullPage:true});await page.getByLabel("Generated map name",{exact:true}).fill("Description northern chart");await page.getByRole("button",{name:"Save as new editable map",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();
    bundle=await read();const described=bundle.maps.find(m=>m.name==="Description northern chart")!,recipe=structuredClone(described.generation),main=described.features.find(f=>bundle.geographies.find(g=>g.id===f.geographyId)?.kind==="continent")!;assert.equal(recipe!.spec!.description,descriptionExample);assert.equal(recipe!.spec!.plan.forestRegion,"south");assert.equal(recipe!.spec!.plan.additionalBaySide,"east");if(main.geometry.type!=="polygon")throw new Error("Description did not create editable land.");const extent=bounds(main.geometry.points);assert.ok(extent.y+extent.height/2<600);assert.equal(described.features.length,4);for(const island of described.features.filter(f=>f.id!==main.id)){if(island.geometry.type!=="polygon")throw new Error("No ordinary island.");assert.ok(bounds(island.geometry.points).x>extent.x+extent.width);}
    const describedRange=described.drawings!.find(d=>d.type==="terrain"&&d.kind==="mountains")!,describedWood=described.drawings!.find(d=>d.type==="terrain"&&d.kind==="forest")!,describedRiver=described.drawings!.find(d=>d.type==="path")!;if(describedRange.type!=="terrain"||describedWood.type!=="terrain"||describedRiver.type!=="path")throw new Error("Description created incompatible source.");assert.ok(bounds(describedRange.points).height>bounds(describedRange.points).width);assert.ok(describedWood.points.reduce((sum,p)=>sum+p.y,0)/describedWood.points.length>extent.y+extent.height*.5);assert.ok(edgeDistance(describedRiver.points.at(-1)!,main.geometry.points)<.1);assert.ok(describedRiver.points.at(-1)!.x>extent.x+extent.width*.55);
    await openAtlas(page,url);await page.getByRole("button",{name:"Open Description northern chart",exact:true}).click();await page.getByText("Creation recipe",{exact:true}).click();await page.getByText("Limits acknowledged at creation:",{exact:true}).waitFor();assert.ok((await page.getByText(`Original description: ${descriptionExample}`,{exact:true}).count())>0);await page.getByRole("button",{name:describedWood.name,exact:true}).click();await page.getByLabel("Stroke density",{exact:true}).fill("1");await page.getByRole("button",{name:"Apply drawing changes",exact:true}).click();await save(page);await openAtlas(page,url);bundle=await read();const describedEdited=bundle.maps.find(m=>m.id===described.id)!;assert.deepEqual(describedEdited.generation,recipe);assert.equal((describedEdited.drawings!.find(d=>d.id===describedWood.id) as typeof describedWood).density,1);assert.deepEqual(describedEdited.features,described.features);
    await page.getByRole("button",{name:"Duplicate Description northern chart",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();await page.getByRole("button",{name:"Map library",exact:true}).click();await page.getByRole("button",{name:"Generate variation of Description northern chart copy",exact:true}).click();assert.equal(await page.getByLabel("Creation method",{exact:true}).inputValue(),"describe");assert.equal(await page.getByLabel("Describe the geography",{exact:true}).inputValue(),descriptionExample);await page.getByLabel("Generation seed",{exact:true}).fill("description-alternate-2026");await page.getByLabel("Use the supported plan despite these limits",{exact:true}).check();await page.getByRole("button",{name:"Preview map",exact:true}).click();await page.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();await page.getByLabel("Generated map name",{exact:true}).fill("Description alternate design");await page.getByRole("button",{name:"Save as new editable map",exact:true}).click();await page.getByRole("application",{name:"Editable map canvas"}).waitFor();assert.deepEqual((await read()).maps.find(m=>m.id===described.id),describedEdited);
    for(const [who,status]of [[null,401],["world-god",404],["world-player",403],["world-admin",404]] as const){const denied=await browser.newContext();if(who){const sign=await denied.request.post(`${baseUrl}/api/auth/sign-in/email`,{headers:{Origin:baseUrl},data:{email:`${who}@example.invalid`,password:"Worlds-Test-Only-Password!"}});assert.equal(sign.status(),200);}const result=await denied.request.get(api);assert.equal(result.status(),status);assert.match(result.headers()["cache-control"],/no-store/);assert.equal((await result.text()).includes(descriptionExample),false);assert.equal((await denied.request.post(api,{headers:{Origin:baseUrl},data:{action:"generate",id:randomUUID(),name:"Forbidden",description:"",spec:recipe!.spec,sourceMapId:null,sourceRevision:null,descriptionWarningsAccepted:true}})).status(),status);if(who==="world-admin"){const review=await denied.request.get(`${api}?review=1`);assert.equal(review.status(),200);assert.equal((await review.json() as AtlasBundle).canEdit,false);assert.equal((await denied.request.post(`${api}?review=1`,{headers:{Origin:baseUrl},data:{action:"generate",id:randomUUID(),name:"Forbidden",description:"",spec:recipe!.spec,sourceMapId:null,sourceRevision:null,descriptionWarningsAccepted:true}})).status(),404);}await denied.close();}
    const phone=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,storageState:await context.storageState()}),mobile=await phone.newPage();mobile.on("pageerror",e=>errors.push(e.message));
    await openAtlas(mobile,url);await mobile.getByRole("button",{name:"Generate map",exact:true}).tap();await mobile.getByLabel("Generation preset",{exact:true}).selectOption("archipelago");await mobile.getByLabel("Generation seed",{exact:true}).fill("phone-generator-2026");await mobile.getByRole("button",{name:"Preview map",exact:true}).tap();await mobile.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mobile.screenshot({path:path.join(captures,"phone-generation.png"),fullPage:true});mobile.once("dialog",d=>d.accept());await mobile.getByRole("button",{name:"Map library",exact:true}).tap();
    await mobile.getByRole("button",{name:"Open Editable generated continent",exact:true}).tap();await mobile.getByRole("button",{name:forest.name,exact:true}).tap();await mobile.getByLabel("Stroke density",{exact:true}).fill("2");await mobile.getByRole("button",{name:"Apply drawing changes",exact:true}).tap();await save(mobile);await mobile.getByRole("application",{name:"Editable map canvas"}).locator("..").screenshot({path:path.join(captures,"phone-editor.png")});
    await mobile.getByRole("button",{name:"Map library",exact:true}).tap();await mobile.getByRole("button",{name:"Generate map",exact:true}).tap();await mobile.getByLabel("Creation method",{exact:true}).selectOption("describe");await mobile.getByRole("button",{name:"Use example description",exact:true}).tap();await mobile.getByRole("button",{name:"Interpret description",exact:true}).tap();await mobile.getByLabel("Generation seed",{exact:true}).fill("phone-description-2026");await mobile.getByLabel("Use the supported plan despite these limits",{exact:true}).check();await mobile.getByRole("button",{name:"Preview map",exact:true}).tap();await mobile.getByRole("heading",{name:"Unsaved preview",exact:true}).waitFor();assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await mobile.screenshot({path:path.join(captures,"phone-description.png"),fullPage:true});await mobile.getByLabel("Generated map artwork",{exact:true}).screenshot({path:path.join(captures,"phone-description-map.png")});await mobile.getByLabel("Generated map name",{exact:true}).fill("Phone described continent");await mobile.getByRole("button",{name:"Save as new editable map",exact:true}).tap();await mobile.getByRole("application",{name:"Editable map canvas"}).waitFor();assert.equal((await read()).maps.find(m=>m.name==="Phone described continent")!.generation!.spec!.description,descriptionExample);await phone.close();assert.deepEqual(errors,[]);
    console.log("PASS: production-browser maps across four presets/seeds and a real description paragraph; reviewed direction/count/terrain plans, visible unsupported details and acknowledgment, stale text/preview protection, saved description geometry reflecting instructions, immutable recipe through edits, duplicate/description variation preserving originals and private description HTTP role isolation; mandatory native sculpt/island/mountain/forest/river/settlement edits with stable identities, phone generation/edit/save and committed screenshots.");
  }catch(failure){await page.screenshot({path:path.join(artifacts,"worlds-generation-failure.png"),fullPage:true}).catch(()=>{});console.log(JSON.stringify({generationErrors:errors,alerts:await page.getByRole("alert").allTextContents()}));throw failure;}finally{await context.close();}
}
