import assert from "node:assert/strict";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type pg from "pg";
import type { BrowserContext, Page } from "playwright-core";
import type * as Service from "../src/features/worlds/calendar-service";
import type * as Worlds from "../src/features/worlds/world-service";
import { annual, blankCalendarRules, yearDays } from "../src/features/worlds/calendar";

export async function calendarServiceChecks(service:typeof Service,worlds:typeof Worlds,pool:pg.Pool,existingWorld:string,foreignWorld:string,adminWorld:string){
  const before=(await worlds.getWorld("world-god",existingWorld));
  const worldId=await worlds.createWorld("world-god",{name:"The Many Moons",description:"Time kept by the coast and the temples."});
  const rules={...blankCalendarRules(),months:Array.from({length:10},(_,i)=>({name:`Moon ${i+1}`,days:36})),weekdays:["Ash","Birch","Cedar","Dawn","Ember","Frost"],timeUnits:{hoursPerDay:10,minutesPerHour:100}};
  const extraId=randomUUID();rules.intercalations.push({id:extraId,name:"Still Day",month:10,afterDay:36,inWeek:false,rule:{...annual(),every:4,exceptEvery:100,restoreEvery:400}});
  rules.seasons.push({name:"Long Light",description:"The coast's bright season.",start:{month:1,day:1},end:{month:5,day:36}});
  rules.observances.push({name:"First Lights",description:"Lanterns in the harbour.",kind:"festival",date:{kind:"month-day",month:1,day:1},rule:annual()},{name:"Still Day feast",description:"Outside the weekday cycle.",kind:"holiday",date:{kind:"intercalary",id:extraId},rule:annual()});
  const draft={name:"Coastal Calendar",description:"Ten moons and six-day weeks.",context:"Kept by the people of the coast."};
  const versionId=(await service.changeCalendar("world-god",worldId,{action:"create",draft,title:"Ancient rules",rules}))!;
  const initial=await service.getCalendars("world-god",worldId),calendar=initial.calendars[0];assert.equal(initial.versions[0].id,versionId);assert.deepEqual(initial.versions[0].rules,rules);assert.equal(initial.defaultVersionId,null);
  const foreignVersion=(await service.changeCalendar("other-god",foreignWorld,{action:"create",draft:{...draft,name:"Foreign private calendar"},title:"Secret rules",rules}))!;
  await service.changeCalendar("world-admin",adminWorld,{action:"create",draft:{...draft,name:"Admin calendar"},title:"Admin rules",rules});
  await service.changeCalendar("world-god",worldId,{action:"create",draft:{...draft,name:"Temple Calendar"},title:"Temple rules",rules:{...rules,months:Array.from({length:12},(_,i)=>({name:`Temple month ${i+1}`,days:29})),intercalations:[],seasons:[],observances:[]}});
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"create",draft,title:"Invalid",rules:{...rules,months:[{name:"Bad",days:0}]}}));
  await service.changeCalendar("world-god",worldId,{action:"default",revision:initial.worldRevision,versionId});
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"default",revision:initial.worldRevision,versionId:null}),/newer version/);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"archive",id:calendar.id,revision:1}),/another default/);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"archive-version",id:versionId,revision:1}),/another default/);
  const choices=await service.getCalendars("world-god",worldId);assert.equal(choices.defaultVersionId,versionId);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"default",revision:choices.worldRevision,versionId:foreignVersion}),/unavailable/);
  await assert.rejects(pool.query("update world_calendar_preference set default_version_id=$1 where world_id=$2",[foreignVersion,worldId]),/foreign key/);
  await assert.rejects(pool.query("insert into world_calendar_version(id,world_id,calendar_id,title,rules) values($1,$2,$3,'Forged',$4)",[randomUUID(),foreignWorld,calendar.id,rules]),/foreign key/);
  const original=(await pool.query("select * from world_calendar_version where id=$1",[versionId])).rows[0];
  const revised={...rules,months:Array.from({length:12},(_,i)=>({name:`Imperial ${i+1}`,days:30})),intercalations:[],seasons:[],observances:[]};
  const competing=await Promise.allSettled([service.changeCalendar("world-god",worldId,{action:"version",id:calendar.id,revision:1,title:"Revised rules",rules:revised}),service.changeCalendar("world-god",worldId,{action:"version",id:calendar.id,revision:1,title:"Competing rules",rules:revised})]);assert.equal(competing.filter(item=>item.status==="fulfilled").length,1);assert.equal(competing.filter(item=>item.status==="rejected").length,1);assert.deepEqual((await pool.query("select * from world_calendar_version where id=$1",[versionId])).rows[0],original);
  await service.changeCalendar("world-god",worldId,{action:"default",revision:choices.worldRevision,versionId:null});await service.changeCalendar("world-god",worldId,{action:"archive-version",id:versionId,revision:1});
  const archived=await service.getCalendars("world-god",worldId);assert.equal(yearDays(archived.versions.find(item=>item.id===versionId)!.rules,4).length,361);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"default",revision:archived.worldRevision,versionId}),/Restore/);await service.changeCalendar("world-god",worldId,{action:"restore-version",id:versionId,revision:2});
  for(const actor of ["other-god","world-admin"]){await assert.rejects(service.getCalendars(actor,worldId),/unavailable/);await assert.rejects(service.changeCalendar(actor,worldId,{action:"create",draft,title:"Forbidden",rules}),/unavailable/);}
  for(const actor of ["world-player","anonymous"]){await assert.rejects(service.getCalendars(actor,worldId),/access/);await assert.rejects(service.changeCalendar(actor,worldId,{action:"create",draft,title:"Forbidden",rules}),/access/);}
  assert.equal((await service.getCalendars("world-admin",worldId,true)).canEdit,false);assert.deepEqual(await worlds.getWorld("world-god",existingWorld),before);
  const active=await service.getCalendars("world-god",worldId),activeCalendar=active.calendars.find(item=>item.id===calendar.id)!;
  await service.changeCalendar("world-god",worldId,{action:"archive",id:calendar.id,revision:activeCalendar.revision});
  const retired=await service.getCalendars("world-god",worldId);assert.equal(retired.calendars.find(item=>item.id===calendar.id)!.archived,true);assert.deepEqual(retired.versions.find(item=>item.id===versionId)!.rules,rules);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"version",id:calendar.id,revision:activeCalendar.revision+1,title:"Archived edit",rules}),/Restore/);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"identity",id:calendar.id,revision:activeCalendar.revision+1,draft}),/Restore/);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"default",revision:retired.worldRevision,versionId}),/Restore/);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"restore",id:calendar.id,revision:activeCalendar.revision}),/newer version/);
  await service.changeCalendar("world-god",worldId,{action:"restore",id:calendar.id,revision:activeCalendar.revision+1});
  await assert.rejects(pool.query("delete from world_calendar where id=$1",[calendar.id]),/foreign key/);
  const liveWorld=await worlds.getWorld("world-god",worldId);await worlds.changeWorld("world-god",worldId,{action:"archive",revision:liveWorld.world.revision});
  assert.equal((await service.getCalendars("world-god",worldId)).canEdit,false);
  await assert.rejects(service.changeCalendar("world-god",worldId,{action:"create",draft,title:"Archived world edit",rules}),/Restore this world/);
  await worlds.changeWorld("world-god",worldId,{action:"restore",revision:liveWorld.world.revision+1});
  console.log("PASS: calendars persist with unusual rules, multiple traditions, immutable saved versions, revision conflicts, preferred display, calendar/version/world archive safeguards, same-world FKs and all roles; existing history is unchanged.");
  return {worldId,versionId,calendarId:calendar.id,foreignVersion};
}
type Fixture=Awaited<ReturnType<typeof calendarServiceChecks>>;
async function ready(page:Page){await page.waitForFunction(()=>[...document.querySelectorAll("button")].some(button=>Object.keys(button).some(key=>key.startsWith("__reactProps$"))));}
export async function calendarBrowserChecks(service:typeof Service,page:Page,context:BrowserContext,baseUrl:string,fixture:Fixture,artifactRoot:string){
  const {worldId}=fixture;await page.goto(`${baseUrl}/worlds/${worldId}`);await ready(page);await page.getByRole("button",{name:"Calendars",exact:true}).click();await page.getByRole("button",{name:"Open Coastal Calendar",exact:true}).click();await page.getByLabel("Rules version",{exact:true}).selectOption(fixture.versionId);
  await page.getByLabel("Preview calendar year",{exact:true}).fill("4");await page.getByRole("button",{name:"View year",exact:true}).click();await page.getByText(/361 days · 6-day weeks/).waitFor();assert.equal(await page.getByRole("region",{name:"Calendar year preview",exact:true}).getByLabel("Months in this year").getByRole("button").count(),10);
  await page.getByRole("button",{name:/^1, Ash, Moon 1, Year 4/}).click();await page.getByRole("complementary",{name:"Selected calendar day",exact:true}).getByText("First Lights",{exact:true}).waitFor();
  await page.getByRole("button",{name:"Use as preferred calendar",exact:true}).click();await page.getByRole("button",{name:"Clear preferred calendar",exact:true}).waitFor();
  await page.getByRole("region",{name:"Selected calendar",exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifactRoot,"worlds-calendar-desktop.png"),fullPage:true});
  await page.getByRole("button",{name:"Revise calendar rules",exact:true}).click();await page.getByLabel("Rules version name",{exact:true}).fill("New coastal rules");await page.getByLabel("Month 1 name",{exact:true}).fill("Dawn Moon");
  await page.route(`**/api/worlds/${worldId}/calendars`,route=>route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary calendar save failure."})}));await page.getByRole("button",{name:"Save rules version",exact:true}).click();await page.getByRole("alert").filter({hasText:"Temporary calendar save failure."}).waitFor();assert.equal(await page.getByLabel("Month 1 name",{exact:true}).inputValue(),"Dawn Moon");await page.unroute(`**/api/worlds/${worldId}/calendars`);
  const second=await context.newPage();await second.goto(`${baseUrl}/worlds/${worldId}`);await ready(second);await second.getByRole("button",{name:"Calendars",exact:true}).click();await second.getByRole("button",{name:"Open Coastal Calendar",exact:true}).click();await second.getByRole("button",{name:"Edit calendar identity",exact:true}).click();await second.getByLabel("Calendar description",{exact:true}).fill("A newer second-tab description.");await second.getByRole("button",{name:"Save calendar identity",exact:true}).click();await second.getByRole("dialog").waitFor({state:"hidden"});
  await page.getByRole("button",{name:"Save rules version",exact:true}).click();await page.getByRole("button",{name:"Load latest calendar",exact:true}).waitFor();assert.equal(await page.getByLabel("Month 1 name",{exact:true}).inputValue(),"Dawn Moon");page.once("dialog",dialog=>dialog.accept());await page.getByRole("button",{name:"Load latest calendar",exact:true}).click();await page.getByLabel("Month 1 name",{exact:true}).fill("Dawn Moon");await page.getByLabel("Rules version name",{exact:true}).fill("New coastal rules");await page.getByRole("button",{name:"Save rules version",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});await second.close();
  await page.getByLabel("Rules version",{exact:true}).selectOption(fixture.versionId);await page.getByRole("button",{name:"Clear preferred calendar",exact:true}).click();await page.getByRole("button",{name:"Archive rules version",exact:true}).click();await page.getByRole("button",{name:"Restore rules version",exact:true}).waitFor();assert.equal((await service.getCalendars("world-god",worldId)).versions.find(item=>item.id===fixture.versionId)!.rules.months[0].name,"Moon 1");await page.getByRole("button",{name:"Restore rules version",exact:true}).click();
  await page.setViewportSize({width:390,height:844});await page.getByLabel("Preview calendar year",{exact:true}).fill("4");await page.getByRole("button",{name:"View year",exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(artifactRoot,"worlds-calendar-mobile.png"),fullPage:true});
  await page.getByRole("button",{name:"New calendar",exact:true}).click();await page.getByLabel("Calendar name",{exact:true}).fill("Small-window Calendar");await page.getByRole("button",{name:"Months",exact:true}).click();await page.getByLabel("Month 1 name",{exact:true}).fill("Ember");await page.getByLabel("Month 1 days",{exact:true}).fill("29");await page.getByRole("button",{name:"Add month",exact:true}).click();await page.getByLabel("Month 2 name",{exact:true}).fill("Frost");await page.getByRole("button",{name:"Week & day",exact:true}).click();await page.getByLabel("Weekday names",{exact:true}).fill("Ash\nBirch\nCedar\nDawn\nEmber\nFrost");await page.getByLabel("Help for Calendar year numbering",{exact:true}).click();await page.screenshot({path:path.join(artifactRoot,"worlds-calendar-editor-mobile.png"),fullPage:false});
  await page.getByRole("button",{name:"Extra days",exact:true}).click();await page.getByRole("button",{name:"Add intercalary day",exact:true}).click();await page.getByLabel("Extra day 1 name",{exact:true}).fill("Between Years");await page.getByRole("button",{name:"Seasons",exact:true}).click();await page.getByRole("button",{name:"Add season",exact:true}).click();await page.getByLabel("Season 1 name",{exact:true}).fill("Bright season");await page.getByRole("button",{name:"Observances",exact:true}).click();await page.getByRole("button",{name:"Add observance",exact:true}).click();await page.getByLabel("Observance 1 name",{exact:true}).fill("Ember festival");await page.getByRole("button",{name:"Preview",exact:true}).click();assert.equal(await page.getByRole("dialog").getByRole("region",{name:"Calendar year preview",exact:true}).count(),1);await page.getByRole("button",{name:"Create calendar",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});await page.reload();await ready(page);await page.getByRole("button",{name:"Calendars",exact:true}).click();await page.getByRole("button",{name:"Open Small-window Calendar",exact:true}).waitFor();assert.ok((await service.getCalendars("world-god",worldId)).calendars.some(item=>item.name==="Small-window Calendar"));await page.setViewportSize({width:1440,height:900});
  console.log("PASS: actual calendars render seasons and festivals, leap previews, rules revisions, preferred persistence, failed drafts, actual two-tab conflict reload, archive retention, phone authoring and screenshots; no geometry overflow.");
}
