import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import type pg from "pg";
import type { Browser, BrowserContext, Locator, Page } from "playwright-core";
import { emptyLore, type LoreDraft, type LoreRecord, type LoreList } from "../src/features/worlds/peoples";
import { entryDraftOf } from "../src/features/worlds/client-api";
import type { HistoricalTime } from "../src/features/worlds/history";
type Worlds=typeof import("../src/features/worlds/world-service");
type Timelines=typeof import("../src/features/worlds/branching-history-service");
const known=(year:number):HistoricalTime=>({version:1,scale:"world-year",kind:"known",year});
const participant=(targetId:string|null,role:string,authoredReference="")=>({targetId,role,authoredReference,account:""});

export async function seedPeoplesUpgrade(pool:pg.Pool,worldId:string){
  const timeline=(await pool.query("select id from world_timeline where world_id=$1 and is_primary",[worldId])).rows[0].id;
  const campaign=(await pool.query("select id from campaign where name='Bridge B Foreign Campaign'")).rows[0].id;
  const context=randomUUID();await pool.query("insert into world_campaign_context(id,campaign_id,world_id,timeline_id,creator_id,starting_year) values($1,$2,$3,$4,'other-god',-50)",[context,campaign,worldId,timeline]);
  await pool.query("insert into world_campaign_context_change(context_id,actor_id,action,snapshot) values($1,'other-god','link',$2)",[context,{id:context,campaignId:campaign,worldId,timelineId:timeline,startingYear:-50,revision:1}]);
  await pool.query("insert into world_campaign_home(campaign_id,context_id,revision) values($1,$2,1)",[campaign,context]);
  const tables=(await pool.query("select tablename from pg_tables where schemaname='public' and tablename like 'world%' order by tablename")).rows;
  const before=new Map<string,unknown>();for(const {tablename}of tables){assert.match(tablename,/^[a-z_]+$/);before.set(tablename,(await pool.query(`select to_jsonb(t) row from ${tablename} t order by to_jsonb(t)::text`)).rows);}
  return async()=>{
    for(const [table,expected]of before){const projection=table==="world_historical_entry"?"to_jsonb(t)-'visibility'":"to_jsonb(t)";assert.deepEqual((await pool.query(`select ${projection} row from ${table} t order by (${projection})::text`)).rows,expected,`0114 preserves ${table}`);}
    for(const table of ["world_lore_identity","world_lore_version","world_lore_head","world_history_version_entity"])assert.equal((await pool.query(`select count(*)::int n from ${table}`)).rows[0].n,0);
    assert.equal((await pool.query("select count(*)::int n from world_historical_entry where visibility<>'ordinary'")).rows[0].n,0);
    console.log("PASS: populated 0113→0114 and reapplication preserve Worlds, all date representations, pinned alternate/nested History, calendars, protected Atlas/dungeons and retained Campaign contexts/home/audit; new entities start empty.");
  };
}

export async function peoplesServiceChecks(worlds:Worlds,timelines:Timelines,pool:pg.Pool,foreignWorld:string,chronology:{worldId:string;founding:string},calendar:{worldId:string;exactId:string}){
  const service=await import("../src/features/worlds/peoples-service"),milestones=await import("../src/features/worlds/milestone-service");
  const worldId=await worlds.createWorld("world-god",{name:"4A Ashborne origins",description:"Contradictory ancestry without gameplay mechanics."});
  const primary=(await worlds.getWorld("world-god",worldId)).selectedTimeline.id;
  const get=(id:string,timelineId=primary)=>service.getPeople("world-god",worldId,timelineId,id);
  const create=async(draft:Partial<LoreDraft>&Pick<LoreDraft,"family"|"name">,timelineId=primary)=>service.changePeople("world-god",worldId,{action:"create",timelineId,requestId:randomUUID(),draft:{...emptyLore(draft.family),...draft}});
  const save=async(r:LoreRecord,draft:Partial<LoreDraft>={},timelineId=primary)=>service.changePeople("world-god",worldId,{action:"save",timelineId,id:r.id,revision:r.revision,draft:{...r.draft,...draft}});
  const event=(title:string,time:HistoricalTime=known(405))=>({eventType:"emergence",draft:{title,account:"An author-recorded appearance.",notes:"",time,accuracy:"disputed" as const,narrative:"recorded" as const,eraIds:[]}});
  const retry={action:"create",timelineId:primary,requestId:randomUUID(),draft:{...emptyLore("species"),name:"Ashborne",description:"Beings of living ash.",time:known(100),milestones:[event("Emergence of Ashborne")]}};
  const ash=await service.changePeople("world-god",worldId,retry);assert.equal(await service.changePeople("world-god",worldId,retry),ash);await assert.rejects(service.changePeople("world-god",worldId,{...retry,draft:{...retry.draft,name:"Changed retry"}}),/newer version/);
  let r=await get(ash);const entryId=r.milestoneRecords[0].id;assert.equal(r.milestoneRecords.length,1);assert.equal(r.milestoneRecords[0].revision,1);
  await save(r,{name:"Ashborne renamed"});r=await get(ash);assert.equal(r.milestoneRecords[0].revision,1,"Metadata edits do not manufacture historical changes");
  await save(r,{milestones:r.draft.milestones.map(m=>({...m,draft:{...m.draft,time:known(412)}}))});r=await get(ash);assert.equal(r.milestoneRecords[0].id,entryId);assert.equal(r.milestoneRecords[0].revision,2);assert.deepEqual(r.milestoneRecords[0].time,known(412));
  assert.equal((await worlds.getWorld("world-god",worldId)).entries.length,1);assert.equal((await pool.query("select count(*)::int n from world_history_version where entity_id=$1",[entryId])).rows[0].n,2);
  const people=await create({family:"people",name:"Willow Coast folk",time:known(50),participants:[participant(ash,"shared heritage")]});
  const origins:string[]=[];for(const [index,description]of ["Forged by three gods.","Born of ancestral fire.","No creator is known."].entries())origins.push(await create({family:"origin",name:`Ashborne origin ${index+1}`,description,time:{version:1,scale:"world-year",kind:"undated"},participants:[participant(ash,"subject"),...index===0?["Glass Mother","Quiet Smith","Unborn Flame"].map(name=>participant(null,"claimed creator",name)):[participant(null,"attributed source","Unknown maker")]],accuracy:index===0?"disputed":"unverified",privateNotes:`Protected origin note ${index+1}`}));
  const relation=await create({family:"relationship",name:"Threefold ancestry",fields:{relationshipType:"Divine and ancestral inheritance",interpretation:"No exclusive parent, including a paradox."},participants:[participant(ash,"descendant"),participant(people,"ancestor"),participant(ash,"paradoxical progenitor"),participant(null,"divine contributor","Unborn Flame")],time:known(-10)});
  assert.equal((await get(relation)).participants.length,4);assert.equal((await get(ash)).related.filter(x=>x.family==="origin").length,3);
  const hidden=await create({family:"origin",name:"Secret Ashborne origin",description:"Protected origin narrative.",visibility:"protected",participants:[participant(ash,"subject")],milestones:[event("Secret emergence",{version:1,scale:"world-year",kind:"undated"})]});
  await save(await get(people),{privateNotes:"Private ethnic detail",sections:[{id:randomUUID(),title:"Secret rites",body:"Protected ritual content",protected:true}],participants:[participant(ash,"heritage"),participant(hidden,"protected explanation")]});
  const preview=await service.getPeople("world-god",worldId,primary,people,false,true);assert.equal(preview.draft.privateNotes,"");assert.deepEqual(preview.draft.sections,[]);assert.equal(preview.participants.length,1);assert.equal(JSON.stringify(await service.peoplesReferences("world-god",worldId,primary,false,true)).includes(hidden),false);await assert.rejects(service.getPeople("world-god",worldId,primary,hidden,false,true),/unavailable/);
  const dates:HistoricalTime[]=[known(0),{version:1,scale:"world-year",kind:"approximate",year:-1e12},{version:1,scale:"world-year",kind:"window",startYear:-10,endYear:10},{version:1,scale:"world-year",kind:"duration",startYear:0,endYear:600},{version:1,scale:"world-year",kind:"undated"}];
  const dateIds:string[]=[];for(const [index,time]of dates.entries()){const id=await create({family:"species",name:`Date precision ${index}`,time,milestones:[event(`Precision milestone ${index}`,time)]});dateIds.push(id);assert.deepEqual((await get(id)).draft.time,time);assert.deepEqual((await get(id)).milestoneRecords[0].time,time);}
  const branch=await timelines.changeTimeline("world-god",worldId,{action:"create",parentRevision:1,draft:{parentId:primary,divergenceYear:300,name:"4A alternate ancestry"}});
  assert.equal((await get(ash,branch)).mode,"inherited");assert.equal((await get(origins[0],branch)).mode,"pending");assert.equal((await get(dateIds[3],branch)).mode,"pending");assert.equal((await get(dateIds[0],branch)).mode,"inherited");
  const included=await get(origins[0],branch);await service.changePeople("world-god",worldId,{action:"resolve",timelineId:branch,id:included.id,revision:included.revision,decision:"include"});assert.equal((await get(origins[0],branch)).mode,"inherited");
  const pinned=await get(people,branch),parent=await get(people);await save(parent,{name:"Changed Coast folk"});assert.equal((await get(people,branch)).draft.name,pinned.draft.name);assert.equal((await get(people,branch)).versionId,pinned.versionId);
  const parentLatest=await get(people);await service.changePeople("world-god",worldId,{action:"accept-parent",timelineId:branch,id:people,revision:pinned.revision,parentRevision:parentLatest.revision,parentVersionId:parentLatest.versionId});assert.equal((await get(people,branch)).draft.name,"Changed Coast folk");
  await assert.rejects(service.changePeople("world-god",worldId,{action:"accept-parent",timelineId:branch,id:people,revision:pinned.revision,parentRevision:parentLatest.revision,parentVersionId:parentLatest.versionId}),/newer version/);
  const local=await get(ash,branch);await save(local,{name:"Alternate Ashborne",milestones:[event("Alternate appearance",known(20))]},branch);assert.equal((await get(ash,branch)).mode,"interpretation");assert.equal((await get(ash)).draft.name,"Ashborne renamed");assert.equal((await worlds.getWorld("world-god",worldId)).entries.some(e=>e.title==="Alternate appearance"),false);
  const nested=await timelines.changeTimeline("world-god",worldId,{action:"create",parentRevision:1,draft:{parentId:branch,divergenceYear:700,name:"4A nested source"}});const child=await get(ash,nested);await save(await get(ash,branch),{description:"A later local interpretation"},branch);assert.equal((await get(ash,nested)).versionId,child.versionId);
  const late=await create({family:"species",name:"New parent source",time:known(10)});assert.equal((await service.peoplesReferences("world-god",worldId,branch)).parent.some(p=>p.id===late),true);const lateParent=await get(late);await service.changePeople("world-god",worldId,{action:"adopt-source",timelineId:branch,id:late,revision:0,parentVersionId:lateParent.versionId,parentRevision:lateParent.revision});assert.equal((await get(late,branch)).mode,"inherited");
  const count=async()=>(await pool.query("select (select count(*) from world_lore_version)::int lore,(select count(*) from world_history_version)::int history,(select count(*) from world_lore_change)::int changes")).rows[0];
  const stale=await get(ash);await save(stale,{description:"Edited after stale tab opened"});const beforeStale=await count();await assert.rejects(save(stale),/newer version/);assert.deepEqual(await count(),beforeStale);
  const current=await get(ash);const oldEvent=current.milestoneRecords[0];await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"save",id:entryId,revision:oldEvent.revision,draft:{...entryDraftOf(oldEvent),title:"Direct History edit"}});const beforeEventConflict=await count();await assert.rejects(save(current),/newer version/);assert.deepEqual(await count(),beforeEventConflict,"Rejected entity save rolls back its new source");assert.equal((await get(ash)).milestoneRecords[0].title,"Direct History edit");
  await save(await get(ash),{milestones:[...(await get(ash)).draft.milestones,event("A second milestone",{version:1,scale:"world-year",kind:"approximate",year:-20})]});
  await milestones.linkMilestone("world-god",worldId,{timelineId:primary,entryId,revision:(await get(ash)).milestoneRecords.find(m=>m.id===entryId)!.revision,targetId:people,kind:"lore",eventType:"affected population"});assert.equal((await milestones.milestoneLinks("world-god",worldId,primary,entryId)).links.length,2);
  const place=randomUUID();await pool.query("insert into world_geography(id,world_id,name,kind,context) values($1,$2,'Willowfen retained place','location','settlement')",[place,worldId]);await milestones.linkMilestone("world-god",worldId,{timelineId:primary,entryId,revision:(await get(ash)).milestoneRecords.find(m=>m.id===entryId)!.revision,targetId:place,kind:"geography",eventType:"founding setting"});assert.equal((await milestones.milestoneLinks("world-god",worldId,primary,entryId)).links.length,3);
  // A newly linked parent entity remains navigable without silently adopting it into an older branch.
  const parentOnly=await create({family:"people",name:"Later parent identity"});await milestones.linkMilestone("world-god",worldId,{timelineId:primary,entryId,revision:(await get(ash)).milestoneRecords.find(m=>m.id===entryId)!.revision,targetId:parentOnly,kind:"lore",eventType:"later attributed participant"});
  const parentEvent=(await pool.query("select revision,version_id from world_history_head where timeline_id=$1 and entity_id=$2",[primary,entryId])).rows[0],branchEvent=(await pool.query("select revision from world_history_head where timeline_id=$1 and entity_id=$2",[branch,entryId])).rows[0];
  await timelines.changeTimeline("world-god",worldId,{action:"accept-parent",id:branch,entityId:entryId,revision:branchEvent.revision,parentRevision:parentEvent.revision,parentVersionId:parentEvent.version_id});await timelines.changeTimeline("world-god",worldId,{action:"resolve",id:branch,entityId:entryId,revision:branchEvent.revision+1,decision:"include"});
  assert.equal((await milestones.milestoneLinks("world-god",worldId,branch,entryId)).links.find(l=>l.id===parentOnly)!.timelineId,primary);await assert.rejects(get(parentOnly,branch),/unavailable/);
  const linkRows=(await pool.query("select distinct entity_category,event_type from world_history_version_entity where entry_id=$1",[entryId])).rows;assert.ok(linkRows.some(x=>x.entity_category==="species"&&x.event_type==="emergence"));assert.ok(linkRows.some(x=>x.entity_category==="people"));assert.ok(linkRows.some(x=>x.entity_category==="settlement"));
  const e=(await worlds.getWorld("world-god",worldId)).entries.find(e=>e.id===entryId)!;await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"archive",id:entryId,revision:e.revision});assert.ok((await get(ash)).milestoneRecords.some(m=>m.id===entryId&&m.archived));await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"restore",id:entryId,revision:e.revision+1});assert.equal((await milestones.milestoneLinks("world-god",worldId,primary,entryId)).links.length,4);
  const beforeArchive=await get(relation);await service.changePeople("world-god",worldId,{action:"archive",timelineId:primary,id:relation,revision:beforeArchive.revision});assert.equal((await get(relation)).archived,true);await service.changePeople("world-god",worldId,{action:"restore",timelineId:primary,id:relation,revision:beforeArchive.revision+1});assert.equal((await get(relation)).participants.length,4);
  // A failed second milestone must undo the first milestone, entity version and audit.
  const bad=await get(ash),atomicBefore=await count();await assert.rejects(save(bad,{milestones:[event("Should roll back"),{...event("Forged event"),entryId:randomUUID(),revision:1}]}),/unavailable/);assert.deepEqual(await count(),atomicBefore);assert.equal((await worlds.getWorld("world-god",worldId)).entries.some(e=>e.title==="Should roll back"),false);
  const foreignPrimary=(await worlds.getWorld("other-god",foreignWorld)).selectedTimeline.id;const foreignId=await service.changePeople("other-god",foreignWorld,{action:"create",timelineId:foreignPrimary,requestId:randomUUID(),draft:{...emptyLore("species"),name:"Private other species"}});await assert.rejects(save(await get(people),{participants:[participant(foreignId,"forged heritage")]}),/available participants/);await assert.rejects(service.getPeople("world-god",worldId,foreignPrimary,ash),/unavailable/);
  for(const user of ["other-god","world-player","world-admin","anonymous"]){await assert.rejects(service.listPeoples(user,worldId,primary),/unavailable|access/);await assert.rejects(service.getPeople(user,worldId,primary,ash),/unavailable|access/);await assert.rejects(service.changePeople(user,worldId,retry),/unavailable|access/);await assert.rejects(milestones.milestoneLinks(user,worldId,primary,entryId),/unavailable|access/);}
  assert.equal((await service.listPeoples("world-admin",worldId,primary,true)).canEdit,false);assert.equal((await service.getPeople("world-admin",worldId,primary,hidden,true)).draft.visibility,"protected");
  const archWorld=await worlds.getWorld("world-god",worldId);await worlds.changeWorld("world-god",worldId,{action:"archive",revision:archWorld.world.revision});await assert.rejects(save(await get(ash)),/Restore/);await worlds.changeWorld("world-god",worldId,{action:"restore",revision:archWorld.world.revision+1});
  await timelines.changeTimeline("world-god",worldId,{action:"archive",id:nested,revision:1});await assert.rejects(save(await get(ash,nested),{},nested),/Restore/);await timelines.changeTimeline("world-god",worldId,{action:"restore",id:nested,revision:2});
  // Existing chronology and anchored calendar contexts are reused and pinned.
  const reckoning=(await worlds.getWorld("world-god",chronology.worldId)).datingSystems.find(s=>s.id===chronology.founding)!;
  const dated=await service.changePeople("world-god",chronology.worldId,{action:"create",timelineId:(await worlds.getWorld("world-god",chronology.worldId)).selectedTimeline.id,requestId:randomUUID(),draft:{...emptyLore("species"),name:"Reckoning source",time:known(-1),datingSystemId:reckoning.id,datingSystemRevision:reckoning.revision}});assert.equal((await service.getPeople("world-god",chronology.worldId,(await worlds.getWorld("world-god",chronology.worldId)).selectedTimeline.id,dated)).sourceDating!.revision,reckoning.revision);
  const calendarBundle=await worlds.getWorld("world-god",calendar.worldId),exact=calendarBundle.entries.find(e=>e.id===calendar.exactId)!;
  const calendarDraft=service.milestoneDraft(exact).calendarDate!;const calendars=await import("../src/features/worlds/calendar-service"),rules=await calendars.getCalendars("world-god",calendar.worldId),currentVersion=rules.versions.find(v=>v.id===calendarDraft.start.versionId)!;
  const calCommand={action:"create",timelineId:calendarBundle.selectedTimeline.id,requestId:randomUUID(),draft:{...emptyLore("species"),name:"Calendar source",calendarDate:calendarDraft}};await assert.rejects(service.changePeople("world-god",calendar.worldId,calCommand),/newer calendar history/);
  calCommand.draft.calendarDate={...calendarDraft,start:{...calendarDraft.start,revision:currentVersion.revision}};
  const cal=await service.changePeople("world-god",calendar.worldId,calCommand),calRecord=await service.getPeople("world-god",calendar.worldId,calendarBundle.selectedTimeline.id,cal);assert.equal(calRecord.calendarSource!.start.elapsedDay,exact.calendarSource!.start.elapsedDay);
  await service.changePeople("world-god",calendar.worldId,{action:"save",timelineId:calendarBundle.selectedTimeline.id,id:cal,revision:calRecord.revision,draft:{...calRecord.draft,description:"Metadata preserves original calendar notation"}});assert.deepEqual((await service.getPeople("world-god",calendar.worldId,calendarBundle.selectedTimeline.id,cal)).calendarSource,calRecord.calendarSource);
  // Historical references pin immutable source versions, and only a retained old pin may survive an edit.
  const refs=await service.peoplesReferences("world-god",worldId,primary),sourceRef=refs.history.find(h=>h.entityId===entryId)!;
  await save(await get(people),{historyRefs:[{entityId:sourceRef.entityId,versionId:sourceRef.versionId}]});
  const sourceEntry=(await worlds.getWorld("world-god",worldId)).entries.find(e=>e.id===entryId)!;await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"save",id:entryId,revision:sourceEntry.revision,draft:{...entryDraftOf(sourceEntry),notes:"Revised historical annotation"}});
  await save(await get(people),{description:"Metadata retains its original historical source"});assert.equal((await get(people)).historyNames[0].versionId,sourceRef.versionId);
  assert.equal((await service.pinnedHistoricalSource("world-god",worldId,primary,people,sourceRef.versionId) as {notes:string}).notes,sourceEntry.notes);await assert.rejects(service.pinnedHistoricalSource("world-god",worldId,primary,ash,sourceRef.versionId),/unavailable/);
  await assert.rejects(create({family:"people",name:"Forged old pin",historyRefs:[{entityId:entryId,versionId:sourceRef.versionId}]}),/newer version/);
  await assert.rejects(save(await get(people),{historyRefs:[{entityId:entryId,versionId:randomUUID()}]}),/unavailable/);
  // Committed source content, participants, history links, audit and identity remain immutable.
  const v=(await get(ash)).versionId;for(const command of ["update world_lore_identity set family='people' where id=$1","delete from world_lore_identity where id=$1"])await assert.rejects(pool.query(command,[ash]),/cannot be changed/);
  await assert.rejects(pool.query("update world_lore_version set private_notes='Changed' where id=$1",[v]),/cannot be changed/);await assert.rejects(pool.query("update world_species_version set name='Changed' where version_id=$1",[v]),/immutable/);await assert.rejects(pool.query("insert into world_lore_section(version_id,world_id,id,position,title,body,protected) values($1,$2,$3,0,'Late section','Late content',false)",[v,worldId,randomUUID()]),/immutable/);
  await assert.rejects(pool.query("update world_lore_head set revision=revision where timeline_id=$1 and entity_id=$2",[primary,ash]),/stale revision/);await assert.rejects(pool.query("delete from world_lore_head where entity_id=$1",[ash]),/Retain/);await assert.rejects(pool.query("update world_lore_change set action='save' where entity_id=$1",[ash]),/cannot be changed/);
  await assert.rejects(pool.query("insert into world_lore_identity(id,world_id,family,origin_timeline_id,creator_id,request_id,request_hash) values($1,$2,'species',$3,'other-god',$4,'x')",[randomUUID(),worldId,primary,randomUUID()]),/authorship/);
  // Database FKs enforce same-World boundaries independently of the HTTP validators.
  const client=await pool.connect();try{
    await client.query("begin");const clone=randomUUID();await client.query("insert into world_lore_version(id,world_id,entity_id,family,timeline_id,author_id,historical_time,accuracy,narrative,visibility) select $1,world_id,entity_id,family,timeline_id,author_id,historical_time,accuracy,narrative,visibility from world_lore_version where id=$2",[clone,v]);
    await assert.rejects(client.query("insert into world_lore_participant(version_id,world_id,position,target_id,role) values($1,$2,0,$3,'forged ancestor')",[clone,worldId,foreignId]),/foreign key/);await client.query("rollback");
    await client.query("begin");const incomplete=randomUUID();await client.query("insert into world_lore_version(id,world_id,entity_id,family,timeline_id,author_id,historical_time,accuracy,narrative,visibility) select $1,world_id,entity_id,family,timeline_id,author_id,historical_time,accuracy,narrative,visibility from world_lore_version where id=$2",[incomplete,v]);await assert.rejects(client.query("commit"),/complete typed content/);await client.query("rollback");
    await client.query("begin");const invalidDate=randomUUID();await assert.rejects(client.query("insert into world_lore_version(id,world_id,entity_id,family,timeline_id,author_id,historical_time,accuracy,narrative,visibility) select $1,world_id,entity_id,family,timeline_id,author_id,'{\"kind\":\"undated\"}'::jsonb,accuracy,narrative,visibility from world_lore_version where id=$2",[invalidDate,v]),/check constraint/);await client.query("rollback");
  }finally{await client.query("rollback");client.release();}
  // Dense related records are metadata-only, bounded, and never recursively expanded.
  const denseWorld=await worlds.createWorld("world-god",{name:"4A dense relationship fixture"}),denseTimeline=(await worlds.getWorld("world-god",denseWorld)).selectedTimeline.id;
  const denseCreate=async(draft:LoreDraft)=>service.changePeople("world-god",denseWorld,{action:"create",timelineId:denseTimeline,requestId:randomUUID(),draft});const roots:string[]=[];
  for(let i=0;i<120;i++)roots.push(await denseCreate({...emptyLore("species"),name:`Species ${String(i).padStart(3,"0")}`,description:"Large source ".repeat(250),time:known(10)}));
  for(let i=0;i<180;i++)await denseCreate({...emptyLore("relationship"),name:`Network ${i}`,fields:{relationshipType:"Shared original ancestry"},participants:[participant(roots[i%120],"ancestor"),participant(roots[(i+1)%120],"descendant")],time:known(15)});
  const began=performance.now(),denseList=await service.listPeoples("world-god",denseWorld,denseTimeline),denseDetail=await service.getPeople("world-god",denseWorld,denseTimeline,roots[1]),denseRefs=await service.peoplesReferences("world-god",denseWorld,denseTimeline),ms=Math.round(performance.now()-began);assert.equal(denseList.records.length,100);assert.equal(denseList.hasMore,true);assert.equal(denseRefs.entities.length,300);assert.ok(denseDetail.related.length>0&&denseDetail.related.length<=100);assert.equal(JSON.stringify(denseList).includes("Large source"),false);assert.equal((await service.listPeoples("world-god",denseWorld,denseTimeline,false,false,"Species 119")).records.length,1);assert.equal((await service.listPeoples("world-god",denseWorld,denseTimeline,false,false,"",0,"species")).records.every(r=>r.family==="species"),true);
  await mkdir("artifacts/guidance/worlds-4a-1",{recursive:true});await writeFile("artifacts/guidance/worlds-4a-1/performance.json",JSON.stringify({entities:300,species:120,relationships:180,listPage:100,listAndDetailAndReferencesMs:ms,listBytes:Buffer.byteLength(JSON.stringify(denseList)),detailBytes:Buffer.byteLength(JSON.stringify(denseDetail)),referenceBytes:Buffer.byteLength(JSON.stringify(denseRefs))},null,2)+"\n");
  console.log(`PASS: 4A species/peoples, contradictory origins, multiple ancestry and unresolved references; canonical milestones, metadata-only edits, idempotency, stale/atomic saves, archive/restore, private preview, direct-parent/nested pins and adoption, authorization, original chronology/calendar sources and SQL immutability; 300-record fixture reads ${ms}ms.`);
  return {worldId,primary,branch,nested,ash,people,origins,hidden,relation,entryId,place,foreignWorld,foreignId,foreignPrimary,denseWorld,denseTimeline};
}

async function signIn(context:BrowserContext,baseUrl:string,user="world-god"){const response=await context.request.post(`${baseUrl}/api/auth/sign-in/email`,{headers:{Origin:baseUrl},data:{email:`${user}@example.invalid`,password:"Worlds-Test-Only-Password!"}});assert.equal(response.status(),200,await response.text());}
async function visible(locator:Locator){await locator.waitFor({state:"visible"});}
async function ready(page:Page){await page.waitForFunction(()=>[...document.querySelectorAll("button")].some(b=>Object.keys(b).some(k=>k.startsWith("__reactProps$"))));}
async function noOverflow(page:Page){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
export async function peoplesBrowserChecks(browser:Browser,baseUrl:string,fixture:Awaited<ReturnType<typeof peoplesServiceChecks>>,worlds:Worlds,pool:pg.Pool){
  const service=await import("../src/features/worlds/peoples-service");const errors:string[]=[];
  const context=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:{"X-Forwarded-For":"198.51.100.101"}});await signIn(context,baseUrl);const page=await context.newPage();page.on("pageerror",e=>errors.push(e.message));page.on("dialog",d=>d.accept());
  const route=`${baseUrl}/worlds/${fixture.worldId}?tab=peoples&timeline=${fixture.primary}`;
  try{
    await page.goto(route);await ready(page);await visible(page.getByRole("button",{name:"Create races and species",exact:true}));await page.getByRole("button",{name:"Create races and species",exact:true}).click();const dialog=page.getByRole("dialog");await visible(dialog);await dialog.getByLabel("Name",{exact:true}).fill("Browser crystal beings");await dialog.getByLabel("Description",{exact:true}).fill("A self-authored species of living crystals.");await dialog.getByText("Historical milestones",{exact:true}).click();await dialog.getByRole("button",{name:"Add historical milestone"}).click();await dialog.getByLabel("Milestone 1 type",{exact:true}).fill("Crystallization");await dialog.getByLabel("Milestone 1 title",{exact:true}).fill("First crystal emergence");await dialog.getByLabel("Milestone 1 account",{exact:true}).fill("An attributed emergence from a sleeping mountain.");await dialog.getByLabel("Milestone 1 date precision",{exact:true}).selectOption("known");await dialog.getByLabel("Milestone 1 year",{exact:true}).fill("405");
    const endpoint=`**/api/worlds/${fixture.worldId}/peoples`;await page.route(endpoint,r=>r.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary entity save failure."})}));await dialog.getByRole("button",{name:"Save record",exact:true}).click();await visible(dialog.getByRole("alert"));assert.equal(await dialog.getByLabel("Name",{exact:true}).inputValue(),"Browser crystal beings");await page.unroute(endpoint);
    const reads=`**/api/worlds/${fixture.worldId}/peoples?*`;await page.route(reads,r=>r.request().url().includes("record=")?r.continue():r.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary list readback failure."})}));
    await dialog.getByRole("button",{name:"Save record",exact:true}).click();await dialog.waitFor({state:"hidden"});await visible(page.getByRole("heading",{name:"Browser crystal beings",exact:true}));await visible(page.getByRole("status").filter({hasText:"Saved successfully."}));await page.unroute(reads);const createdId=new URL(page.url()).searchParams.get("entity")!;
    const created=await service.getPeople("world-god",fixture.worldId,fixture.primary,createdId);assert.equal(created.milestoneRecords.length,1);const milestoneId=created.milestoneRecords[0].id;
    await page.reload();await visible(page.getByRole("heading",{name:"Browser crystal beings",exact:true}));await page.getByRole("button",{name:"Edit record",exact:true}).click();await dialog.getByLabel("Milestone 1 year",{exact:true}).fill("412");await dialog.getByRole("button",{name:"Save record",exact:true}).click();await dialog.waitFor({state:"hidden"});assert.equal((await service.getPeople("world-god",fixture.worldId,fixture.primary,createdId)).milestoneRecords[0].id,milestoneId);
    await page.getByRole("link",{name:"First crystal emergence",exact:true}).click();await visible(page.getByRole("dialog"));await visible(page.getByRole("link",{name:"Browser crystal beings",exact:true}));assert.ok((await page.getByRole("dialog").textContent())!.includes("An attributed emergence"));await page.getByRole("link",{name:"Browser crystal beings",exact:true}).click();await visible(page.getByRole("heading",{name:"Browser crystal beings",exact:true}));
    // Two tabs retain the failing draft and offer explicit reload.
    const second=await context.newPage();second.on("dialog",d=>d.accept());await second.goto(page.url());await visible(second.getByRole("button",{name:"Edit record",exact:true}));await second.getByRole("button",{name:"Edit record",exact:true}).click();await second.getByRole("dialog").getByLabel("Description",{exact:true}).fill("Unsaved second-tab text");await page.getByRole("button",{name:"Edit record",exact:true}).click();await dialog.getByLabel("Description",{exact:true}).fill("First-tab accepted edit");await dialog.getByRole("button",{name:"Save record",exact:true}).click();await dialog.waitFor({state:"hidden"});await second.getByRole("dialog").getByRole("button",{name:"Save record",exact:true}).click();await visible(second.getByRole("dialog").getByRole("alert"));assert.equal(await second.getByRole("dialog").getByLabel("Description",{exact:true}).inputValue(),"Unsaved second-tab text");await second.getByRole("button",{name:"Load latest record",exact:true}).click();await second.waitForFunction(()=>document.querySelector<HTMLTextAreaElement>('dialog textarea')?.value==="First-tab accepted edit");assert.equal(await second.getByRole("dialog").getByLabel("Description",{exact:true}).inputValue(),"First-tab accepted edit");await second.close();
    // Related origins and server-side redaction are checked in the actual HTTP responses.
    await page.goto(`${route}&entity=${fixture.ash}`);await visible(page.getByRole("heading",{name:"Ashborne renamed",exact:true}));await page.getByRole("button",{name:"Ashborne origin 1",exact:true}).click();await visible(page.getByRole("heading",{name:"Ashborne origin 1",exact:true}));await page.getByRole("button",{name:"Ordinary knowledge preview",exact:true}).click();assert.equal((await context.request.get(`${baseUrl}/api/worlds/${fixture.worldId}/peoples?timeline=${fixture.primary}&record=${fixture.hidden}&ordinary=1`)).status(),404);const ordinary=await context.request.get(`${baseUrl}/api/worlds/${fixture.worldId}/peoples?timeline=${fixture.primary}&record=${fixture.people}&ordinary=1`);const text=await ordinary.text();assert.equal(text.includes("Private ethnic detail"),false);assert.equal(text.includes("Secret rites"),false);assert.equal(text.includes(fixture.hidden),false);
    await page.goto(`${baseUrl}/worlds/${fixture.worldId}?tab=history&timeline=${fixture.primary}&entry=${fixture.entryId}`);await visible(page.getByRole("link",{name:"Willowfen retained place",exact:true}));await page.getByRole("link",{name:"Willowfen retained place",exact:true}).click();await visible(page.getByRole("heading",{name:"Willowfen retained place",exact:true}));assert.equal(new URL(page.url()).searchParams.get("place"),fixture.place);
    await page.goto(`${route}&entity=${fixture.people}`);await visible(page.getByRole("heading",{name:"Changed Coast folk",exact:true}));await page.getByRole("button",{name:"Direct History edit",exact:true}).click();await visible(page.getByRole("dialog",{name:"Pinned historical source",exact:true}));assert.equal((await page.getByRole("dialog",{name:"Pinned historical source",exact:true}).textContent())!.includes("Revised historical annotation"),false);await page.getByRole("button",{name:"Close source",exact:true}).click();
    const clock=(await pool.query("select to_jsonb(t) row from campaign_session t order by id")).rows;await page.goto(`${route}&entity=${fixture.ash}`);await visible(page.getByRole("heading",{name:"Ashborne renamed",exact:true}));await page.getByLabel("Selected timeline",{exact:true}).selectOption(fixture.branch);await visible(page.getByRole("heading",{name:"Alternate Ashborne",exact:true}));assert.deepEqual((await pool.query("select to_jsonb(t) row from campaign_session t order by id")).rows,clock);await noOverflow(page);
    // Actual touch-enabled phone create/edit/search/navigation, no desktop emulation assumptions.
    const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,extraHTTPHeaders:{"X-Forwarded-For":"198.51.100.102"}});await signIn(phone,baseUrl);const mobile=await phone.newPage();mobile.on("pageerror",e=>errors.push(e.message));mobile.on("dialog",d=>d.accept());await mobile.goto(route);await visible(mobile.getByRole("button",{name:"Create peoples",exact:true}));await mobile.getByRole("button",{name:"Create peoples",exact:true}).tap();const form=mobile.getByRole("dialog");await form.getByLabel("Name",{exact:true}).fill("Phone coast folk");await form.getByLabel("Description",{exact:true}).fill("Written on a touch-enabled phone.");await form.getByRole("button",{name:"Save record",exact:true}).tap();await form.waitFor({state:"hidden"});await visible(mobile.getByRole("heading",{name:"Phone coast folk",exact:true}));await mobile.getByRole("button",{name:"Edit record",exact:true}).tap();await form.getByLabel("Description",{exact:true}).fill("Edited and retained on phone.");await form.getByRole("button",{name:"Save record",exact:true}).tap();await form.waitFor({state:"hidden"});await mobile.getByRole("button",{name:"Close record",exact:true}).tap();const searchReply=mobile.waitForResponse(r=>r.url().includes("/peoples?")&&r.url().includes("q=Phone+coast")&&r.request().method()==="GET");await mobile.getByLabel("Search peoples and origins",{exact:true}).fill("Phone coast");await searchReply;await mobile.waitForFunction(()=>document.querySelectorAll('[aria-label="Peoples and origins"] button[class*="card"]').length===1);await visible(mobile.getByRole("button",{name:/Phone coast folk Peoples/}));await noOverflow(mobile);assert.ok(await mobile.evaluate(()=>navigator.maxTouchPoints>0));
    // Small targeted evidence set for the new layout only, retained in the repo.
    await mobile.getByRole("heading",{name:"Peoples and origins",exact:true}).evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-130));await mobile.screenshot({path:"artifacts/guidance/worlds-4a-1/peoples-phone.png",fullPage:false});await phone.close();await page.goto(`${route}&entity=${fixture.ash}`);await visible(page.getByRole("heading",{name:"Ashborne renamed",exact:true}));await visible(page.getByRole("button",{name:/^Ashborne renamed Races and species/}));await page.getByRole("article",{name:"World entity details",exact:true}).evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-180));await page.screenshot({path:"artifacts/guidance/worlds-4a-1/peoples-desktop.png",fullPage:false});
    const dense=await context.request.get(`${baseUrl}/api/worlds/${fixture.denseWorld}/peoples?timeline=${fixture.denseTimeline}`);assert.equal((await dense.json() as LoreList).records.length,100);
    for(const user of ["other-god","world-player","world-admin","anonymous"]){const denied=await browser.newContext({extraHTTPHeaders:{"X-Forwarded-For":`198.51.100.${103+["other-god","world-player","world-admin","anonymous"].indexOf(user)}`}});if(user!=="anonymous")await signIn(denied,baseUrl,user);for(const endpoint of [`peoples?timeline=${fixture.primary}`,`peoples?timeline=${fixture.primary}&record=${fixture.ash}`,`milestones?timeline=${fixture.primary}&entry=${fixture.entryId}`]){const response=await denied.request.get(`${baseUrl}/api/worlds/${fixture.worldId}/${endpoint}`);assert.ok([401,403,404].includes(response.status()));assert.equal((await response.text()).includes("Ashborne"),false);}const forbidden=await denied.newPage();await forbidden.goto(route);assert.equal((await forbidden.content()).includes("Ashborne renamed"),false);if(user==="world-admin"){await forbidden.goto(`${route}&review=1&entity=${fixture.hidden}`);await visible(forbidden.getByRole("heading",{name:"Secret Ashborne origin",exact:true}));assert.equal(await forbidden.getByRole("button",{name:"Edit record",exact:true}).count(),0);}await denied.close();}
    assert.deepEqual(errors,[]);assert.equal((await worlds.getWorld("world-god",fixture.worldId)).entries.filter(e=>e.id===milestoneId).length,1);
    console.log("PASS: production desktop/native-touch phone entity and milestone create/edit/reload/search, bidirectional full-account and original-place navigation, two-tab retained conflict recovery, alternate context/clock safety, server preview and all role/direct-route denials, explicit Administrator review; two targeted screenshots retained.");
  }catch(failure){await page.screenshot({path:"artifacts/guidance/worlds-4a-1/browser-failure.png",fullPage:false}).catch(()=>{});await writeFile("artifacts/guidance/worlds-4a-1/browser-failure.html",await page.content()).catch(()=>{});console.log(JSON.stringify({url:page.url(),errors,alerts:await page.getByRole("alert").allTextContents()}));throw failure;}finally{await context.close();}
}
