import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type pg from "pg";
import type { Browser, BrowserContext, Page, Locator } from "playwright-core";
import { entryDraftOf } from "../src/features/worlds/client-api";
import type { EntryDraft, HistoricalTime } from "../src/features/worlds/history";
type Worlds=typeof import("../src/features/worlds/world-service");
type Timelines=typeof import("../src/features/worlds/branching-history-service");
export async function seedBridgeUpgrade(pool:pg.Pool,worldId:string){
  const site=randomUUID(),level=randomUUID(),room=randomUUID(),map=randomUUID(),shape=randomUUID();
  await pool.query("insert into world_geography(id,world_id,name,kind,context,parent_id) values($1,$2,'Retained dungeon','location','dungeon',null),($3,$2,'Retained dungeon level','location','dungeon level',$1),($4,$2,'Retained dungeon room','location','dungeon',$3)",[site,worldId,level,room]);
  await pool.query("insert into world_dungeon_site(geography_id,world_id) values($1,$2)",[site,worldId]);await pool.query("insert into world_dungeon_level(geography_id,world_id,site_id) values($1,$2,$3)",[level,worldId,site]);
  await pool.query("insert into world_dungeon_entity(id,world_id,level_id,geography_id,kind,name,visibility,private_notes) values($1,$2,$3,$1,'room','Retained secret','god-only','Keep this unchanged')",[room,worldId,level]);
  await pool.query("insert into world_atlas_map(id,world_id,name,map_kind,geography_id) values($1,$2,'Retained dungeon map','dungeon',$3)",[map,worldId,level]);
  await pool.query("insert into world_atlas_dungeon_shape(id,world_id,map_id,level_id,entity_id,content,sort_order) values($1,$2,$3,$4,$5,$6,0)",[shape,worldId,map,level,room,{version:1,id:shape,entityId:room,archived:false,variant:"area",points:[[10,10],[100,10],[100,100]].map(([x,y])=>({id:randomUUID(),x,y}))}]);
  const tables=["world","world_historical_entry","world_historical_era","world_entry_era","world_dating_system","world_chronology_preference","world_calendar","world_calendar_version","world_calendar_preference","world_day_reference","world_calendar_anchor","world_calendar_entry_date","world_calendar_adoption","world_calendar_reform","world_calendar_history","world_geography","world_atlas_map","world_atlas_drawing","world_atlas_feature","world_atlas_connection","world_settlement_entity","world_settlement_membership","world_atlas_settlement_shape","world_interior_floor","world_interior_entity","world_atlas_interior_shape","world_dungeon_site","world_dungeon_level","world_dungeon_entity","world_atlas_dungeon_shape"];
  const snapshot=new Map<string,unknown>();for(const table of tables)snapshot.set(table,(await pool.query(`select to_jsonb(t) as row from ${table} t order by to_jsonb(t)::text`)).rows);
  return async()=>{
    for(const [table,expected]of snapshot){const projection=table==="world_historical_entry"||table==="world_historical_era"?"to_jsonb(t)-'timeline_id'":"to_jsonb(t)";assert.deepEqual((await pool.query(`select ${projection} as row from ${table} t order by (${projection})::text`)).rows,expected,`0112 preserves ${table}`);}
    assert.equal((await pool.query("select count(*)::int as n from world w left join world_timeline t on t.world_id=w.id and t.is_primary where t.id is null")).rows[0].n,0);
    const rows=(await pool.query("select v.payload,e.historical_time,e.source_dating,c.source from world_history_version v join world_historical_entry e on e.id=v.entry_id left join world_calendar_entry_date c on c.entry_id=e.id")).rows;
    for(const row of rows){assert.deepEqual(row.payload.time,row.historical_time);assert.deepEqual(row.payload.sourceDating,row.source_dating);assert.deepEqual(row.payload.calendarSource,row.source);}
    console.log("PASS: populated 0111→0112 preserves every prior World, historical date/source, calendar and Atlas/settlement/interior/dungeon projection; stable Primary History and pinned legacy versions backfilled.");
  };
}
const time=(year:number):HistoricalTime=>({version:1,scale:"world-year",kind:"known",year});
const draft=(title:string,historicalTime:HistoricalTime=time(300)):EntryDraft=>({title,account:`Original ${title}`,notes:"Source notes",time:historicalTime,eraIds:[],accuracy:"established",narrative:"recorded"});
export async function branchingServiceChecks(worlds:Worlds,timelines:Timelines,pool:pg.Pool,foreignWorld:string){
  const worldId=await worlds.createWorld("world-god",{name:"Branching Empire"});
  const initial=await worlds.getWorld("world-god",worldId);assert.equal(initial.timelines.length,1);assert.equal(initial.selectedTimeline.primary,true);
  const primary=initial.selectedTimeline.id;
  const ids:Record<string,string>={};for(const [title,t]of [["Founding",time(300)],["Collapse",time(650)],["Successors",time(800)],["Crossing window",{version:1,scale:"world-year",kind:"window",startYear:600,endYear:700}],["Crossing duration",{version:1,scale:"world-year",kind:"duration",startYear:600,endYear:700}],["Approximate",{version:1,scale:"world-year",kind:"approximate",year:300}],["Undated",{version:1,scale:"world-year",kind:"undated"}],["Negative",time(-1e12)]] as [string,HistoricalTime][])ids[title]=await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:draft(title,t)});
  ids.Plan=await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:{...draft("Plan"),narrative:"planned"}});
  const era=await worlds.changeHistory("world-god",worldId,{entity:"era",action:"save",draft:{name:"Empire era",description:"Originally ending 800",startYear:300,endYear:800,tone:"primary"}});
  const openEra=await worlds.changeHistory("world-god",worldId,{entity:"era",action:"save",draft:{name:"Open age",description:"",startYear:0,endYear:null,tone:"primary"}});
  const create=async(parentId:string,year:number,name:string)=>{const bundle=await worlds.getWorld("world-god",worldId,false,parentId);return timelines.changeTimeline("world-god",worldId,{action:"create",parentRevision:bundle.selectedTimeline.revision,draft:{parentId,divergenceYear:year,name,description:"Alternate historical foundations",explanation:"The Emperor survived."}});};
  const branch=await create(primary,650,"The Empire Survives");let b=await worlds.getWorld("world-god",worldId,false,branch);
  assert.deepEqual(b.entries.map(e=>e.title).sort(),["Founding","Negative"]);assert.equal(b.eras.find(e=>e.id===era)!.endYear,null);assert.equal(b.eras.find(e=>e.id===openEra)!.historyContext!.coveredUntil,649);
  for(const title of ["Crossing window","Crossing duration","Approximate","Undated","Plan"])assert.equal(b.inheritanceReview.find(r=>r.record.id===ids[title])!.context.mode,"pending");
  for(const title of ["Collapse","Successors"])assert.equal(b.inheritanceReview.find(r=>r.record.id===ids[title])!.context.mode,"excluded");
  const preParent=await worlds.getWorld("world-god",worldId);
  const authored=await worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",action:"save",draft:draft("Emperor survives",time(650))});
  const authoredEra=await worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"era",action:"save",draft:{name:"Divine expansion",startYear:650,endYear:null,tone:"info"}});
  await worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",action:"save",draft:{...draft("Expansion",time(800)),eraIds:[authoredEra]}});
  assert.deepEqual((await worlds.getWorld("world-god",worldId)).entries,preParent.entries);
  await assert.rejects(worlds.changeHistory("world-god",worldId,{entity:"entry",id:authored,revision:1,action:"save",draft:draft("Forged primary")}),/unavailable/);
  await assert.rejects(worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",action:"save",draft:{...draft("Forged era"),eraIds:[randomUUID()]}}),/available era/);
  b=await worlds.getWorld("world-god",worldId,false,branch);const founding=b.entries.find(e=>e.id===ids.Founding)!;
  await worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",id:founding.id,revision:founding.revision,action:"save",draft:{...entryDraftOf(founding),account:"Disputed founding in this branch",accuracy:"disputed"}});
  assert.equal((await worlds.getWorld("world-god",worldId)).entries.find(e=>e.id===founding.id)!.account,"Original Founding");
  const child=await create(branch,800,"The Empire Becomes Divine");let c=await worlds.getWorld("world-god",worldId,false,child);
  assert.ok(c.entries.some(e=>e.id===authored));assert.equal(c.entries.some(e=>e.title==="Expansion"),false);assert.equal(c.entries.find(e=>e.id===founding.id)!.account,"Disputed founding in this branch");assert.equal(c.eras.find(e=>e.id===era)!.historyContext!.coveredUntil,649);
  await assert.rejects(create(branch,649,"Too early"),/earlier ancestor/);
  const ancestor=(await worlds.getWorld("world-god",worldId)).entries.find(e=>e.id===founding.id)!;
  await worlds.changeHistory("world-god",worldId,{entity:"entry",id:ancestor.id,revision:ancestor.revision,action:"save",draft:{...entryDraftOf(ancestor),account:"Revised parent founding"}});
  b=await worlds.getWorld("world-god",worldId,false,branch);assert.equal(b.entries.find(e=>e.id===founding.id)!.account,"Disputed founding in this branch");const changed=b.inheritanceReview.find(r=>r.record.id===founding.id)!;assert.equal(changed.context.newerParent,true);
  const accept={action:"accept-parent",id:branch,entityId:founding.id,revision:changed.record.revision,parentRevision:changed.context.parentRevision,parentVersionId:changed.context.parentVersionId};
  await timelines.changeTimeline("world-god",worldId,accept);await assert.rejects(timelines.changeTimeline("world-god",worldId,accept),/newer version/);
  b=await worlds.getWorld("world-god",worldId,false,branch);assert.equal(b.entries.find(e=>e.id===founding.id)!.account,"Revised parent founding");c=await worlds.getWorld("world-god",worldId,false,child);assert.equal(c.entries.find(e=>e.id===founding.id)!.account,"Disputed founding in this branch");assert.equal(c.inheritanceReview.find(r=>r.record.id===founding.id)!.context.newerParent,true);
  const unknown=b.inheritanceReview.find(r=>r.record.id===ids.Undated)!;await timelines.changeTimeline("world-god",worldId,{action:"resolve",id:branch,entityId:unknown.record.id,revision:unknown.record.revision,decision:"include"});assert.ok((await worlds.getWorld("world-god",worldId,false,branch)).entries.some(e=>e.id===unknown.record.id&&e.time.kind==="undated"));
  const cross=b.inheritanceReview.find(r=>r.record.id===ids["Crossing window"])!;await timelines.changeTimeline("world-god",worldId,{action:"resolve",id:branch,entityId:cross.record.id,revision:cross.record.revision,decision:"exclude"});assert.equal((await worlds.getWorld("world-god",worldId,false,branch)).inheritanceReview.find(r=>r.record.id===cross.record.id)!.context.mode,"excluded");
  const current=(await worlds.getWorld("world-god",worldId,false,branch)).entries.find(e=>e.id===authored)!;
  await worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",id:current.id,revision:current.revision,action:"archive"});await worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",id:current.id,revision:current.revision+1,action:"restore"});
  await assert.rejects(worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",id:current.id,revision:current.revision,action:"save",draft:entryDraftOf(current)}),/newer version/);
  await timelines.changeTimeline("world-god",worldId,{action:"archive",id:branch,revision:1});assert.equal((await worlds.getWorld("world-god",worldId,false,child)).canEdit,true);await assert.rejects(create(branch,900,"Archived parent"),/Restore the parent/);await assert.rejects(worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",action:"save",draft:draft("Archived write")}),/Restore this timeline/);await timelines.changeTimeline("world-god",worldId,{action:"restore",id:branch,revision:2});
  await assert.rejects(timelines.changeTimeline("world-god",worldId,{action:"archive",id:primary,revision:1}),/permanent/);
  const negative=await create(primary,-1e12,"Earliest boundary");assert.equal((await worlds.getWorld("world-god",worldId,false,negative)).entries.length,0);const zero=await create(primary,0,"Year zero branch");assert.deepEqual((await worlds.getWorld("world-god",worldId,false,zero)).entries.map(e=>e.title),["Negative"]);await create(primary,1e12,"Latest boundary");
  for(const user of ["other-god","world-admin","world-player","anonymous"]){await assert.rejects(worlds.getWorld(user,worldId,false,branch),/unavailable|access/);await assert.rejects(timelines.changeTimeline(user,worldId,{action:"save",id:branch,revision:3,draft:{name:"Unauthorized"}}),/unavailable|access/);}
  assert.equal((await worlds.getWorld("world-admin",worldId,true,branch)).canEdit,false);await assert.rejects(worlds.getWorld("world-god",foreignWorld,false,branch),/unavailable/);
  const foreign=(await worlds.getWorld("other-god",foreignWorld)).selectedTimeline;
  await assert.rejects(timelines.changeTimeline("world-god",worldId,{action:"create",parentRevision:1,draft:{name:"Foreign",parentId:foreign.id,divergenceYear:1}}),/unavailable/);
  await assert.rejects(pool.query("update world_timeline set parent_id=$1 where id=$2",[child,branch]),/immutable/);await assert.rejects(pool.query("delete from world_timeline where id=$1",[primary]),/Archive/);await assert.rejects(pool.query("update world_timeline set divergence_year=0 where id=$1",[branch]),/immutable/);
  await assert.rejects(pool.query("insert into world_timeline(id,world_id,parent_id,divergence_year,name) values($1,$2,$3,0,'Foreign')",[randomUUID(),worldId,foreign.id]),/same-world|foreign key/);
  const version=(await pool.query("select id from world_history_version where entity_id=$1 limit 1",[founding.id])).rows[0].id;await assert.rejects(pool.query("update world_history_version set payload=payload where id=$1",[version]),/immutable/);await assert.rejects(pool.query("delete from world_history_version where id=$1",[version]),/immutable/);
  await assert.rejects(pool.query("delete from world_history_head where timeline_id=$1 and entity_id=$2",[branch,founding.id]),/immutable/);
  await assert.rejects(pool.query("insert into world_history_version(id,world_id,entity_id,timeline_id,payload) select $1,world_id,entity_id,timeline_id,payload from world_history_version where id=$2",[randomUUID(),version]),/exactly one/);
  await assert.rejects(pool.query("insert into world_history_version(id,world_id,entity_id,entry_id,timeline_id,payload,start_version_id) select $1,world_id,entity_id,entry_id,timeline_id,payload,$2 from world_history_version where id=$3",[randomUUID(),randomUUID(),version]),/protected columns|foreign key/);
  const foreignEntry=await worlds.changeHistory("other-god",foreignWorld,{entity:"entry",action:"save",draft:draft("Other owner's source")});
  await assert.rejects(pool.query("insert into world_history_version(id,world_id,entity_id,entry_id,timeline_id,payload) select $1,$2,entity_id,entry_id,$3,jsonb_set(payload,'{worldId}',to_jsonb($2::text)) from world_history_version where entity_id=$4 limit 1",[randomUUID(),worldId,branch,foreignEntry]),/foreign key/);
  const beforeStale=(await pool.query("select to_jsonb(h) row from world_history_head h where timeline_id=$1 order by entity_id",[branch])).rows;
  const staleVersionCount=(await pool.query("select count(*)::int n from world_history_version where world_id=$1",[worldId])).rows[0].n;
  await assert.rejects(worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",id:current.id,revision:current.revision,action:"save",draft:entryDraftOf(current)}),/newer version/);
  assert.deepEqual((await pool.query("select to_jsonb(h) row from world_history_head h where timeline_id=$1 order by entity_id",[branch])).rows,beforeStale);assert.equal((await pool.query("select count(*)::int n from world_history_version where world_id=$1",[worldId])).rows[0].n,staleVersionCount);
  // Meaningful bounded fixture: 1,200 entries, shared identity pins, 12 branches, including nested ancestry.
  const perfWorld=await worlds.createWorld("world-god",{name:"Many histories"}),perfPrimary=(await worlds.getWorld("world-god",perfWorld)).selectedTimeline.id;
  await pool.query("insert into world_historical_entry(id,world_id,title,account,historical_time) select gen_random_uuid()::text,$1,'Historical account '||n,'An authored account with preserved identity.',jsonb_build_object('version',1,'scale','world-year','kind','known','year',n-600) from generate_series(1,1200) n",[perfWorld]);
  const start=performance.now();let perfParent=perfPrimary;for(let index=0;index<12;index++)perfParent=await timelines.changeTimeline("world-god",perfWorld,{action:"create",parentRevision:1,draft:{name:`Branch ${index}`,parentId:index<6?perfPrimary:perfParent,divergenceYear:500+index}});
  const createdMs=Math.round(performance.now()-start),readStart=performance.now(),perfBundle=await worlds.getWorld("world-god",perfWorld,false,perfParent),readMs=Math.round(performance.now()-readStart);
  assert.ok(perfBundle.entries.length>1000);assert.equal((await pool.query("select count(*)::int n from world_history_version where world_id=$1",[perfWorld])).rows[0].n,1200,"Branches share versions instead of copying history payloads");
  console.log(`PASS: pinned inheritance, alternate authoring/interpretation, nested branches, uncertainty, explicit reconciliation, immutable ancestry, lifecycle, unchanged stale writes, all roles and SQL protections. 1,200 records/12 branches: creation ${createdMs}ms, selected projection ${readMs}ms, ${Buffer.byteLength(JSON.stringify(perfBundle))} bytes; only selected heads loaded.`);
  const clipWorld=await worlds.createWorld("world-god",{name:"Partial era view"}),clipPrimary=(await worlds.getWorld("world-god",clipWorld)).selectedTimeline;
  await worlds.changeHistory("world-god",clipWorld,{entity:"era",action:"save",draft:{name:"Predecessor Empire",startYear:300,endYear:900,tone:"primary"}});
  const clipTimeline=await timelines.changeTimeline("world-god",clipWorld,{action:"create",parentRevision:clipPrimary.revision,draft:{name:"Partial continuity",parentId:clipPrimary.id,divergenceYear:650}});
  await worlds.changeHistory("world-god",clipWorld,{timelineId:clipTimeline,entity:"entry",action:"save",draft:draft("Alternate future",time(800))});
  return {worldId,primary,branch,child,founding:founding.id,authored,perfWorld,perfTimeline:perfParent,clipWorld,clipTimeline};
}
type Fixture=Awaited<ReturnType<typeof branchingServiceChecks>>;
export async function branchingSourceChecks(worlds:Worlds,timelines:Timelines,pool:pg.Pool,chronologyWorld:string,calendarWorld:string){
  const result:string[]=[];
  for(const worldId of [chronologyWorld,calendarWorld]){
    const original=await worlds.getWorld("world-god",worldId),branch=await timelines.changeTimeline("world-god",worldId,{action:"create",parentRevision:original.selectedTimeline.revision,draft:{name:"Source preservation branch",parentId:original.selectedTimeline.id,divergenceYear:700}});
    const inherited=await worlds.getWorld("world-god",worldId,false,branch);
    for(const review of inherited.inheritanceReview){const source=original.entries.find(e=>e.id===review.record.id)??original.eras.find(e=>e.id===review.record.id)!;assert.deepEqual(review.record.sourceDating??null,source.sourceDating??null);if("calendarSource"in source)assert.deepEqual((review.record as typeof source).calendarSource,source.calendarSource);}
    const row=inherited.inheritanceReview.find(r=>"calendarSource"in r.record&&r.record.calendarSource);
    if(row){await timelines.changeTimeline("world-god",worldId,{action:"resolve",id:branch,entityId:row.record.id,revision:row.record.revision,decision:"include"});const entry=(await worlds.getWorld("world-god",worldId,false,branch)).entries.find(e=>e.id===row.record.id)!;await worlds.changeHistory("world-god",worldId,{timelineId:branch,entity:"entry",id:entry.id,revision:entry.revision,action:"save",draft:{...entryDraftOf(entry),notes:"Branch-specific source notes"}});assert.deepEqual((await worlds.getWorld("world-god",worldId,false,branch)).entries.find(e=>e.id===entry.id)!.calendarSource,entry.calendarSource);}
    assert.deepEqual((await worlds.getWorld("world-god",worldId)).entries,original.entries);result.push(branch);
  }
  assert.ok((await pool.query("select count(*)::int n from world_history_version where start_version_id is not null")).rows[0].n>0);
  const activeVersions=(await pool.query("select v.id from world_calendar_version v join world_calendar c on c.id=v.calendar_id where v.world_id=$1 and v.archived_at is null and c.archived_at is null limit 2",[calendarWorld])).rows;
  assert.equal(activeVersions.length,2);const alternateEntry=await worlds.changeHistory("world-god",calendarWorld,{timelineId:result[1],entity:"entry",action:"save",draft:draft("Alternate reform account",time(700))});
  const evolution=await import("../src/features/worlds/calendar-evolution-service");await assert.rejects(evolution.changeCalendarEvolution("world-god",calendarWorld,{action:"reform",draft:{name:"Unsupported alternate reform",predecessorId:activeVersions[0].id,successorId:activeVersions[1].id,time:time(700),reason:"Authored alternate event",details:"",entryId:alternateEntry,cutover:null}}),/reference Primary History/);
  console.log("PASS: alternate source notation preserves year reckonings, calendar dates/precision and immutable references; branch note edits retain original precise sources and leave primary accounts unchanged.");
  return {calendarWorld,calendarTimeline:result[1]};
}
async function signIn(context:BrowserContext,baseUrl:string,user:string){const response=await context.request.post(`${baseUrl}/api/auth/sign-in/email`,{headers:{Origin:baseUrl},data:{email:`${user}@example.invalid`,password:"Worlds-Test-Only-Password!"}});assert.equal(response.status(),200,await response.text());}
async function hydrated(page:Page){await page.waitForFunction(()=>[...document.querySelectorAll("button")].some(button=>Object.keys(button).some(key=>key.startsWith("__reactProps$"))));}
async function noOverflow(page:Page){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),"Phone timeline management fits the viewport");}
async function valueSaved(locator:Locator,value:string){const deadline=Date.now()+10_000;while(Date.now()<deadline){if(await locator.inputValue().catch(()=>"")===value)return;await locator.page().waitForTimeout(50);}assert.equal(await locator.inputValue(),value);}
export async function branchingBrowserChecks(browser:Browser,baseUrl:string,f:Fixture,worlds:Worlds,timelines:Timelines,sources:Awaited<ReturnType<typeof branchingSourceChecks>>){
  const context=await browser.newContext({viewport:{width:1440,height:900},extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.161"}});await signIn(context,baseUrl,"world-god");const page=await context.newPage(),errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));page.on("dialog",dialog=>void dialog.accept());
  try {
  const url=`${baseUrl}/worlds/${f.worldId}`;
  await page.goto(`${baseUrl}/worlds/${f.clipWorld}?timeline=${f.clipTimeline}&tab=history`);await hydrated(page);const partialBand=page.getByRole("region",{name:"Historical timeline",exact:true}).locator('[data-known-through="649"]');await partialBand.waitFor();const measured=await partialBand.evaluate(node=>{const band=node.getBoundingClientRect(),lane=node.parentElement!.getBoundingClientRect();return {bandRight:band.right,laneRight:lane.right,laneWidth:lane.width,title:node.getAttribute("title")};});assert.ok(measured.bandRight<measured.laneRight-measured.laneWidth*.1,"Partial era must stop at its predecessor extent rather than span the branch future");assert.match(measured.title??"",/649; continuation unknown/);
  await page.goto(url);await hydrated(page);await page.getByRole("button",{name:"Timelines",exact:true}).click();await page.getByRole("heading",{name:"Timeline manager",exact:true}).waitFor();
  await page.getByRole("button",{name:"Create alternate timeline",exact:true}).click();let modal=page.getByRole("dialog");await modal.getByLabel("Timeline name",{exact:true}).fill("Browser surviving empire");await modal.getByLabel("Divergence canonical year",{exact:true}).fill("650");await modal.getByLabel("Why history differs",{exact:true}).fill("The creator chooses an entirely original explanation.");
  await page.route(`**/api/worlds/${f.worldId}/timelines`,route=>route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Simulated timeline failure; draft retained."})}));await modal.getByRole("button",{name:"Create timeline",exact:true}).click();await modal.getByRole("alert").waitFor();assert.equal(await modal.getByLabel("Timeline name",{exact:true}).inputValue(),"Browser surviving empire");await page.unroute(`**/api/worlds/${f.worldId}/timelines`);await modal.getByRole("button",{name:"Create timeline",exact:true}).click();await modal.waitFor({state:"hidden"});
  const browserBranch=(await worlds.getWorld("world-god",f.worldId)).timelines.find(t=>t.name==="Browser surviving empire")!.id;await page.waitForURL(`**timeline=${browserBranch}**`);await page.getByLabel("Selected timeline",{exact:true}).waitFor();await page.waitForFunction(id=>[...document.querySelectorAll("select")].some(s=>s.value===id),browserBranch);
  await page.getByRole("button",{name:"New entry",exact:true}).click();modal=page.getByRole("dialog");assert.match(await modal.textContent()??"",/Writing in Browser surviving empire/);await modal.getByLabel("Entry title",{exact:true}).fill("A different year 650");await modal.getByLabel("Historical account",{exact:true}).fill("The empire endured instead of collapsing.");await modal.getByLabel("Date representation",{exact:true}).selectOption("known");await modal.getByLabel("Year",{exact:true}).fill("650");await modal.getByLabel("Historical accuracy",{exact:true}).selectOption("disputed");await modal.getByRole("button",{name:"Save history",exact:true}).click();await modal.waitFor({state:"hidden"});
  let bundle=await worlds.getWorld("world-god",f.worldId,false,browserBranch);const authored=bundle.entries.find(e=>e.title==="A different year 650")!;assert.ok(authored);assert.equal((await worlds.getWorld("world-god",f.worldId)).entries.some(e=>e.id===authored.id),false);
  await page.reload();await hydrated(page);assert.equal(await page.getByLabel("Selected timeline",{exact:true}).inputValue(),browserBranch);await page.getByRole("button",{name:"Chronological list",exact:true}).click();await page.getByLabel("Search history",{exact:true}).fill(authored.title);await page.getByRole("button",{name:authored.title,exact:true}).click();await page.getByRole("button",{name:"Edit entry",exact:true}).click();await page.getByLabel("Entry title",{exact:true}).fill("Unchanged stale branch draft");
  const second=await context.newPage();await second.goto(`${url}?timeline=${browserBranch}&tab=history`);await hydrated(second);await second.getByRole("button",{name:"Chronological list",exact:true}).click();await second.getByLabel("Search history",{exact:true}).fill(authored.title);await second.getByRole("button",{name:authored.title,exact:true}).click();await second.getByRole("button",{name:"Edit entry",exact:true}).click();await second.getByLabel("Historical account",{exact:true}).fill("Another tab's revised branch account");await second.getByRole("button",{name:"Save changes",exact:true}).click();await second.getByRole("dialog").waitFor({state:"hidden"});
  await page.getByRole("button",{name:"Save changes",exact:true}).click();await page.getByRole("button",{name:"Load latest version",exact:true}).waitFor();assert.equal(await page.getByLabel("Entry title",{exact:true}).inputValue(),"Unchanged stale branch draft");await page.getByRole("button",{name:"Load latest version",exact:true}).click();await valueSaved(page.getByLabel("Historical account",{exact:true}),"Another tab's revised branch account");await page.getByRole("button",{name:"Close editor",exact:true}).click();await second.close();
  await page.getByRole("button",{name:"Timelines",exact:true}).click();await page.getByRole("button",{name:"Create alternate timeline",exact:true}).click();modal=page.getByRole("dialog");await modal.getByLabel("Timeline name",{exact:true}).fill("Browser divine empire");await modal.getByLabel("Divergence canonical year",{exact:true}).fill("800");await modal.getByRole("button",{name:"Create timeline",exact:true}).click();await modal.waitFor({state:"hidden"});const child=(await worlds.getWorld("world-god",f.worldId)).timelines.find(t=>t.name==="Browser divine empire")!;await page.waitForURL(`**timeline=${child.id}**`);await page.getByLabel("Selected timeline",{exact:true}).selectOption(f.primary);await page.waitForURL(`**timeline=${f.primary}**`);await page.goBack();await page.waitForURL(`**timeline=${child.id}**`);await page.goForward();await page.waitForURL(`**timeline=${f.primary}**`);
  await page.getByLabel("Selected timeline",{exact:true}).selectOption(child.id);await valueSaved(page.getByLabel("Selected timeline",{exact:true}),child.id);await page.getByRole("button",{name:"New entry",exact:true}).click();await page.getByLabel("Entry title",{exact:true}).fill("Protected navigation draft");page.removeAllListeners("dialog");page.once("dialog",dialog=>void dialog.dismiss());await page.goBack();await page.getByRole("dialog").waitFor();assert.equal(await page.getByLabel("Entry title",{exact:true}).inputValue(),"Protected navigation draft");assert.ok(page.url().includes(child.id));page.on("dialog",dialog=>void dialog.accept());await page.getByRole("button",{name:"Close editor",exact:true}).click();await page.getByRole("button",{name:"Discard draft",exact:true}).click();
  await page.goto(`${url}?timeline=${browserBranch}&tab=timelines`);await hydrated(page);await page.getByRole("button",{name:"Edit Browser surviving empire",exact:true}).click();modal=page.getByRole("dialog");await modal.getByLabel("Timeline description",{exact:true}).fill("Timeline metadata draft retained");bundle=await worlds.getWorld("world-god",f.worldId,false,browserBranch);await timelines.changeTimeline("world-god",f.worldId,{action:"save",id:browserBranch,revision:bundle.selectedTimeline.revision,draft:{name:bundle.selectedTimeline.name,description:"Newer description",explanation:"Newer explanation"}});await modal.getByRole("button",{name:"Save timeline",exact:true}).click();await modal.getByRole("button",{name:"Load latest timeline",exact:true}).waitFor();assert.equal(await modal.getByLabel("Timeline description",{exact:true}).inputValue(),"Timeline metadata draft retained");await modal.getByRole("button",{name:"Load latest timeline",exact:true}).click();await valueSaved(modal.getByLabel("Timeline description",{exact:true}),"Newer description");await modal.getByRole("button",{name:"Close timeline editor",exact:true}).click();
  await page.getByRole("button",{name:"Archive Browser surviving empire",exact:true}).click();await page.getByRole("button",{name:"Restore Browser surviving empire",exact:true}).waitFor();await page.reload();await hydrated(page);await page.getByRole("button",{name:"Restore Browser surviving empire",exact:true}).waitFor();await page.getByRole("button",{name:"Restore Browser surviving empire",exact:true}).click();await page.getByRole("button",{name:"Archive Browser surviving empire",exact:true}).waitFor();
  await page.goto(`${baseUrl}/worlds/${sources.calendarWorld}?timeline=${sources.calendarTimeline}&tab=history`);await hydrated(page);await page.getByRole("button",{name:"Calendars",exact:true}).click();await page.getByRole("button",{name:/^Open Imperial (Calendar|Tradition)$/,exact:true}).click();await page.getByText("Primary History's adoptions, reforms and effective periods",{exact:false}).waitFor();assert.equal(await page.getByText("Year-only transition",{exact:true}).count(),0);
  await page.goto(`${url}?timeline=${browserBranch}&tab=timelines`);await hydrated(page);bundle=await worlds.getWorld("world-god",f.worldId,false,browserBranch);const uncertain=bundle.inheritanceReview.find(item=>"title"in item.record&&item.record.title==="Undated")!;await page.locator(`[data-entity-id="${uncertain.record.id}"]`).getByRole("button",{name:"Include complete source",exact:true}).click();await page.locator(`[data-entity-id="${uncertain.record.id}"]`).getByRole("button",{name:"Write branch interpretation",exact:true}).waitFor();await page.locator(`[data-entity-id="${uncertain.record.id}"]`).getByRole("button",{name:"Write branch interpretation",exact:true}).click();await page.getByLabel("Historical account",{exact:true}).fill("The unknown date remains unknown; this branch interprets the source.");await page.getByRole("button",{name:"Save changes",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});assert.equal((await worlds.getWorld("world-god",f.worldId,false,browserBranch)).entries.find(entry=>entry.id===uncertain.record.id)!.time.kind,"undated");
  const parentSource=(await worlds.getWorld("world-god",f.worldId)).entries.find(entry=>entry.id===f.founding)!;await worlds.changeHistory("world-god",f.worldId,{entity:"entry",id:parentSource.id,revision:parentSource.revision,action:"save",draft:{...entryDraftOf(parentSource),notes:"New parent source for browser reconciliation"}});await page.reload();await hydrated(page);await page.locator(`[data-entity-id="${f.founding}"]`).getByRole("button",{name:"Accept newer parent version",exact:true}).click();await page.locator(`[data-entity-id="${f.founding}"]`).getByRole("button",{name:"Accept newer parent version",exact:true}).waitFor({state:"hidden"});assert.equal((await worlds.getWorld("world-god",f.worldId,false,browserBranch)).entries.find(entry=>entry.id===f.founding)!.notes,"New parent source for browser reconciliation");
  const performanceUrl=`${baseUrl}/worlds/${f.perfWorld}?timeline=${f.perfTimeline}&tab=history`;await page.goto(performanceUrl);await hydrated(page);let start=performance.now();await page.getByLabel("Selected timeline",{exact:true}).selectOption((await worlds.getWorld("world-god",f.perfWorld)).selectedTimeline.id);await page.getByRole("button",{name:"New entry",exact:true}).waitFor();const primaryPerf=(await worlds.getWorld("world-god",f.perfWorld)).selectedTimeline.id;await page.waitForFunction(id=>[...document.querySelectorAll("select")].some(s=>s.value===id),primaryPerf);const switchMs=Math.round(performance.now()-start);start=performance.now();await page.getByRole("button",{name:"Chronological list",exact:true}).click();await page.getByLabel("Search history",{exact:true}).fill("Historical account 1199");await page.getByRole("button",{name:"Historical account 1199",exact:true}).waitFor();const browseMs=Math.round(performance.now()-start);
  const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.162"}});await signIn(phone,baseUrl,"world-god");const mobile=await phone.newPage();mobile.on("pageerror",error=>errors.push(error.message));mobile.on("dialog",dialog=>void dialog.accept());await mobile.goto(`${url}?timeline=${browserBranch}&tab=timelines`);await hydrated(mobile);await noOverflow(mobile);await mobile.getByRole("button",{name:"Create alternate timeline",exact:true}).tap();let phoneModal=mobile.getByRole("dialog");await phoneModal.getByLabel("Timeline name",{exact:true}).fill("Phone history");await phoneModal.getByLabel("Divergence canonical year",{exact:true}).fill("850");await phoneModal.getByRole("button",{name:"Create timeline",exact:true}).tap();await phoneModal.waitFor({state:"hidden"});const phoneBranch=(await worlds.getWorld("world-god",f.worldId)).timelines.find(t=>t.name==="Phone history")!;await mobile.waitForURL(`**timeline=${phoneBranch.id}**`);await mobile.getByRole("button",{name:"New entry",exact:true}).tap();phoneModal=mobile.getByRole("dialog");await phoneModal.getByLabel("Entry title",{exact:true}).fill("Phone historical account");await phoneModal.getByLabel("Historical account",{exact:true}).fill("A branch written using native touch controls.");await phoneModal.getByLabel("Historical accuracy",{exact:true}).selectOption("unverified");await noOverflow(mobile);await phoneModal.getByRole("button",{name:"Save history",exact:true}).tap();await phoneModal.waitFor({state:"hidden"});await mobile.reload();await hydrated(mobile);await noOverflow(mobile);assert.ok((await worlds.getWorld("world-god",f.worldId,false,phoneBranch.id)).entries.some(e=>e.title==="Phone historical account"&&e.time.kind==="undated"));await mobile.getByLabel("Selected timeline",{exact:true}).selectOption(f.primary);await mobile.waitForURL(`**timeline=${f.primary}**`);await noOverflow(mobile);
  for(const user of ["other-god","world-admin","world-player"]){const role=await browser.newContext({extraHTTPHeaders:{"X-Forwarded-For":`203.0.113.${user==="other-god"?163:user==="world-admin"?164:165}`}});await signIn(role,baseUrl,user);const endpoint=`${baseUrl}/api/worlds/${f.worldId}?timeline=${browserBranch}`,response=await role.request.get(endpoint);assert.equal(response.status(),user==="world-player"?403:404);assert.equal((await response.text()).includes("surviving empire"),false);const denied=await role.request.post(`${baseUrl}/api/worlds/${f.worldId}/timelines`,{headers:{Origin:baseUrl},data:{action:"archive",id:browserBranch,revision:1}});assert.equal(denied.status(),user==="world-player"?403:404);const p=await role.newPage();await p.goto(`${url}?timeline=${browserBranch}`);assert.equal(await p.getByLabel("Selected timeline",{exact:true}).count(),0);if(user==="world-admin"){const review=await role.request.get(`${endpoint}&review=1`);assert.equal(review.status(),200);assert.equal((await review.json()).canEdit,false);await p.goto(`${url}?timeline=${browserBranch}&tab=timelines&review=1`);await hydrated(p);assert.equal(await p.getByRole("button",{name:"Create alternate timeline",exact:true}).count(),0);assert.equal(await p.getByRole("button",{name:`Edit Browser surviving empire`,exact:true}).count(),0);}await role.close();}
  const anonymous=await browser.newContext({extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.166"}});assert.equal((await anonymous.request.get(`${baseUrl}/api/worlds/${f.worldId}?timeline=${browserBranch}`)).status(),401);await anonymous.close();
  const invalid=await context.request.get(`${baseUrl}/api/worlds/${f.worldId}?timeline=${randomUUID()}`);assert.equal(invalid.status(),404);await page.goto(`${url}?timeline=${randomUUID()}`);assert.equal(await page.getByLabel("Selected timeline",{exact:true}).count(),0);
  assert.deepEqual(errors,[]);console.log(`PASS: real production desktop + native-touch 390px timeline creation, nested authoring, persisted distinct history, failure drafts, actual two-tab conflicts, timeline metadata conflicts, reload/deep links/back/forward, archive/restore and all role privacy. 1,200-record browser switch ${switchMs}ms; searchable browsing ${browseMs}ms.`);await phone.close();await context.close();
  }catch(failure){console.log(JSON.stringify({branchingUrl:page.url(),branchingTitle:await page.title(),timelineChoice:await page.getByLabel("Selected timeline",{exact:true}).inputValue().catch(()=>null),branchingAlerts:await page.getByRole("alert").allTextContents(),branchingButtons:await page.getByRole("button").allTextContents()}));await page.screenshot({path:"artifacts/guidance/bridge-a-failure.png",fullPage:false});throw failure;}
}
