import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import path from "node:path";
import type pg from "pg";
import type { Page, BrowserContext } from "playwright-core";
import type * as Worlds from "../src/features/worlds/world-service";
import type * as Calendars from "../src/features/worlds/calendar-service";
import type * as Evolution from "../src/features/worlds/calendar-evolution-service";
import { annual, blankCalendarRules } from "../src/features/worlds/calendar";
import { toElapsed, fromElapsed, type CalendarEntryDraft } from "../src/features/worlds/calendar-dates";
import { entryDraftOf } from "../src/features/worlds/client-api";
export async function evolutionServiceChecks(worlds:typeof Worlds,calendars:typeof Calendars,evolution:typeof Evolution,pool:pg.Pool,foreignWorld:string,foreignVersion:string){
  const worldId=await worlds.createWorld("world-god",{name:"Imperial Ages",description:"Calendars carried through an empire's changing ages."});
  const rules={...blankCalendarRules(),months:Array.from({length:10},(_,i)=>({name:`Old Moon ${i+1}`,days:36})),weekdays:["Ash","Birch","Cedar","Dawn","Ember","Frost"]};
  rules.intercalations.push({id:randomUUID(),name:"Still Day",month:10,afterDay:36,inWeek:false,rule:{...annual(),every:4}});
  const oldId=(await calendars.changeCalendar("world-god",worldId,{action:"create",draft:{name:"Imperial Calendar",description:"A changing civil tradition.",context:""},title:"Founding rules",rules}))!;
  let bundle=await calendars.getCalendars("world-god",worldId);const calendarId=bundle.calendars[0].id;
  const replacement={...blankCalendarRules(),months:Array.from({length:12},(_,i)=>({name:`Imperial ${i+1}`,days:29})),weekdays:["One","Two","Three","Four","Five","Six","Seven"]};
  const newId=(await calendars.changeCalendar("world-god",worldId,{action:"version",id:calendarId,revision:1,title:"Imperial reformation",rules:replacement}))!;
  const unanchoredId=(await calendars.changeCalendar("world-god",worldId,{action:"create",draft:{name:"Temple Calendar",description:"A simultaneous sacred tradition.",context:""},title:"Temple rules",rules:replacement}))!;
  const start={versionId:oldId,revision:1,date:{year:1,month:1,day:1}},next={versionId:newId,revision:1,date:{year:1,month:1,day:1}};
  await assert.rejects(evolution.changeCalendarEvolution("world-god",worldId,{action:"anchor",endpoint:start,elapsedDay:"0",sameDayUnit:true}),/origin/);
  await evolution.changeCalendarEvolution("world-god",worldId,{action:"origin",label:"Days since the First Dawn",description:"Day 0 is the first dawn remembered by the coast. Each calendar day represents one common elapsed day."});
  await assert.rejects(evolution.changeCalendarEvolution("world-god",worldId,{action:"origin",label:"Replaced",description:"Cannot rewrite origin"}),/immutable/);
  await evolution.changeCalendarEvolution("world-god",worldId,{action:"anchor",endpoint:start,elapsedDay:"0",sameDayUnit:true});
  await evolution.changeCalendarEvolution("world-god",worldId,{action:"anchor",endpoint:next,elapsedDay:"380",sameDayUnit:true});
  await assert.rejects(evolution.changeCalendarEvolution("world-god",worldId,{action:"anchor",endpoint:start,elapsedDay:"1",sameDayUnit:true}),/immutable/);
  await assert.rejects(evolution.changeCalendarEvolution("world-god",worldId,{action:"anchor",endpoint:{...start,versionId:foreignVersion},elapsedDay:"0",sameDayUnit:true}),/unavailable/);
  bundle=await calendars.getCalendars("world-god",worldId);assert.equal(bundle.evolution.anchors.length,2);assert.equal(toElapsed(rules,bundle.evolution.anchors.find(a=>a.versionId===oldId),start.date),"0");assert.equal(toElapsed(replacement,bundle.evolution.anchors.find(a=>a.versionId===newId),next.date),"380");assert.deepEqual(fromElapsed(replacement,bundle.evolution.anchors.find(a=>a.versionId===newId),"380"),next.date);
  const known={version:1 as const,scale:"world-year" as const,kind:"known" as const,year:801};
  await evolution.changeCalendarEvolution("world-god",worldId,{action:"period",versionId:newId,revision:null,period:{time:known,notes:"Adopted under the new empire.",continues:true}});
  const periodRace=await Promise.allSettled(["A","B"].map(notes=>evolution.changeCalendarEvolution("world-god",worldId,{action:"period",versionId:newId,revision:1,period:{time:known,notes,continues:true}})));assert.equal(periodRace.filter(r=>r.status==="fulfilled").length,1);assert.equal(periodRace.filter(r=>r.status==="rejected").length,1);
  const imperialAdoption=await evolution.changeCalendarEvolution("world-god",worldId,{action:"adoption",draft:{label:"Imperial civil offices",versionId:newId,period:{time:known,notes:"",continues:true}}});
  await evolution.changeCalendarEvolution("world-god",worldId,{action:"adoption",draft:{label:"Temple communities",versionId:unanchoredId,period:{time:{version:1,scale:"world-year",kind:"duration",startYear:500,endYear:1500},notes:"Used alongside civil time.",continues:false}}});
  const entry=await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:{title:"The Imperial Decree",account:"The surviving decree remains the authoritative account.",time:known,accuracy:"established",narrative:"planned",eraIds:[]}});
  const basic={name:"Imperial reform",predecessorId:oldId,successorId:newId,time:known,reason:"Civil administration changed the months and began a new epoch.",details:"Temple use continued.",entryId:entry,cutover:null};
  const yearOnly=await evolution.changeCalendarEvolution("world-god",worldId,{action:"reform",draft:{...basic,name:"Year-only transition"}});
  const cutover={before:{...start,date:{year:2,month:1,day:20}},after:next};
  const reformId=await evolution.changeCalendarEvolution("world-god",worldId,{action:"reform",draft:{...basic,cutover}});
  await assert.rejects(evolution.changeCalendarEvolution("world-god",worldId,{action:"reform",draft:{...basic,cutover:{...cutover,after:{...next,date:{year:1,month:1,day:2}}}}}),/immediately follow/);
  const foreignEntry=await worlds.changeHistory("other-god",foreignWorld,{entity:"entry",action:"save",draft:{title:"Secret",account:"Private narrative",time:known,accuracy:"established",narrative:"recorded",eraIds:[]}});
  await assert.rejects(evolution.changeCalendarEvolution("world-god",worldId,{action:"reform",draft:{...basic,entryId:foreignEntry}}),/unavailable/);
  await assert.rejects(pool.query("insert into world_calendar_anchor(version_id,world_id,calendar_date,elapsed_day) values($1,$2,$3,'0')",[foreignVersion,worldId,start.date]),/foreign key/);
  await assert.rejects(pool.query("update world_calendar_reform set entry_id=$1 where id=$2",[foreignEntry,reformId]),/foreign key/);
  await evolution.changeCalendarEvolution("other-god",foreignWorld,{action:"origin",label:"Secret Day Origin",description:"Another owner's private reference."});
  await evolution.changeCalendarEvolution("other-god",foreignWorld,{action:"anchor",endpoint:{...start,versionId:foreignVersion},elapsedDay:"0",sameDayUnit:true});
  await assert.rejects(pool.query("insert into world_calendar_entry_date(entry_id,world_id,start_version_id,source) values($1,$2,$3,$4)",[entry,worldId,foreignVersion,{version:1,kind:"known",start:{versionId:foreignVersion,elapsedDay:"0"}}]),/foreign key/);
  const preciseIds:string[]=[];
  for(const kind of ["known","approximate","window","duration"] as const){const calendarDate:CalendarEntryDraft=kind==="known"||kind==="approximate"?{kind,start:cutover.before}:{kind,start:cutover.before,end:next};preciseIds.push(await worlds.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:{title:`Calendar ${kind}`,account:"A retained calendar account.",time:{version:1,scale:"world-year",kind:"undated"},accuracy:"disputed",narrative:"recorded",eraIds:[],calendarDate}}));}
  let records=await worlds.getWorld("world-god",worldId);for(const [i,id]of preciseIds.entries()){const record=records.entries.find(e=>e.id===id)!;assert.equal(record.time.kind,"undated");assert.equal(record.calendarSource!.kind,["known","approximate","window","duration"][i]);assert.equal(record.calendarSource!.start.elapsedDay,"379");assert.equal(record.calendarSource!.start.calendarName,"Imperial Calendar");}
  const account=records.entries.find(e=>e.id===entry)!;assert.equal(account.account,"The surviving decree remains the authoritative account.");assert.equal(account.narrative,"planned");assert.equal((await calendars.getCalendars("world-god",worldId)).evolution.reforms.find(r=>r.id===yearOnly)!.cutover,null);
  const exact=records.entries.find(e=>e.id===preciseIds[0])!,original=exact.calendarSource;
  const raw={kind:"known",start:cutover.before};
  await assert.rejects(worlds.changeHistory("world-god",worldId,{entity:"entry",id:exact.id,revision:exact.revision,action:"save",draft:{...entryDraftOf(exact),title:"Bad unanchored save",calendarDate:{...raw,start:{...start,versionId:unanchoredId}}}}),/no authored day anchor/);
  await assert.rejects(worlds.changeHistory("world-god",worldId,{entity:"entry",id:exact.id,revision:exact.revision,action:"save",draft:{...entryDraftOf(exact),calendarDate:{kind:"duration",start:next,end:start}}}),/ending calendar date/);
  await calendars.changeCalendar("world-god",worldId,{action:"archive-version",id:oldId,revision:1});
  await calendars.changeCalendar("world-god",worldId,{action:"identity",id:calendarId,revision:2,draft:{name:"Imperial Tradition",description:"Current name",context:""}});
  await worlds.changeHistory("world-god",worldId,{entity:"entry",id:exact.id,revision:exact.revision,action:"save",draft:{...entryDraftOf(exact),notes:"Retained after retirement",calendarDate:raw}});
  await assert.rejects(worlds.changeHistory("world-god",worldId,{entity:"entry",action:"save",draft:{...entryDraftOf(exact),calendarDate:{...raw,start:{...cutover.before,revision:2}}}}),/Restore/);
  records=await worlds.getWorld("world-god",worldId);assert.deepEqual(records.entries.find(e=>e.id===exact.id)!.calendarSource,original);
  await calendars.changeCalendar("world-god",worldId,{action:"restore-version",id:oldId,revision:2});
  for(const [id,status] of [["other-god",404],["world-admin",404],["world-player",403],["anonymous",403]] as const)await assert.rejects(evolution.changeCalendarEvolution(id,worldId,{action:"origin",label:"Forbidden",description:"Unauthorized"}),(error:unknown)=>(error as {status:number}).status===status);
  assert.equal((await calendars.getCalendars("world-admin",worldId,true)).canEdit,false);
  await evolution.changeCalendarEvolution("world-god",worldId,{action:"archive",entity:"adoption",id:imperialAdoption,revision:1});await assert.rejects(evolution.changeCalendarEvolution("world-god",worldId,{action:"restore",entity:"adoption",id:imperialAdoption,revision:1}),/newer/);await evolution.changeCalendarEvolution("world-god",worldId,{action:"restore",entity:"adoption",id:imperialAdoption,revision:2});
  assert.deepEqual((await calendars.getCalendars("world-god",worldId)).versions.find(v=>v.id===oldId)!.rules,rules);
  console.log("PASS: historical evolution persists immutable origins/anchors, successive periods, concurrent edits, simultaneous/open-ended adoption, year-only and consecutive skipped/repeated-date cutovers, linked planned History, precise/approximate/window/duration sources, retired snapshot retention, rollback and owner/composite-FK isolation.");
  const originWorldId=await worlds.createWorld("world-god",{name:"Origin Authoring"});await calendars.changeCalendar("world-god",originWorldId,{action:"create",draft:{name:"Origin Calendar",description:"",context:""},title:"Origin rules",rules:blankCalendarRules()});
  return {worldId,oldId,newId,unanchoredId,calendarId,entry,exactId:exact.id,reformId,originWorldId};
}

type Fixture=Awaited<ReturnType<typeof evolutionServiceChecks>>;
async function open(page:Page,baseUrl:string,f:Fixture){await page.goto(`${baseUrl}/worlds/${f.worldId}`);await page.getByRole("button",{name:"Calendars",exact:true}).click();await page.getByRole("button",{name:"Open Imperial Tradition",exact:true}).click();await page.getByLabel("Rules version",{exact:true}).selectOption(f.newId);await page.getByText("History, adoption & date comparison",{exact:true}).click();}
export async function evolutionBrowserChecks(page:Page,context:BrowserContext,baseUrl:string,f:Fixture,artifactRoot:string){
  await page.goto(`${baseUrl}/worlds/${f.originWorldId}`);await page.getByRole("button",{name:"Calendars",exact:true}).click();await page.getByRole("button",{name:"Open Origin Calendar",exact:true}).click();await page.getByText("History, adoption & date comparison",{exact:true}).click();await page.getByRole("button",{name:"Anchors",exact:true}).click();await page.getByRole("button",{name:"Establish day origin",exact:true}).click();await page.getByLabel("Day reference name",{exact:true}).fill("Harbour Dawn");await page.getByLabel("Origin and day meaning",{exact:true}).fill("Day zero is the first harbour dawn; one calendar day is one shared elapsed day.");await page.getByRole("button",{name:"Save calendar history",exact:true}).click();await page.getByRole("heading",{name:"Harbour Dawn",exact:true}).waitFor();
  await open(page,baseUrl,f);await page.getByRole("heading",{name:"Imperial reform",exact:true}).waitFor();await page.getByText(/Last old date:/).waitFor();
  const reformCard=page.locator("article").filter({has:page.getByRole("heading",{name:"Imperial reform",exact:true})});await reformCard.getByRole("button",{name:"Archive reform",exact:true}).click();await reformCard.getByRole("button",{name:"Restore reform",exact:true}).click();
  await page.getByLabel("Historical calendar evolution",{exact:true}).screenshot({path:path.join(artifactRoot,"worlds-calendar-history-desktop.png")});
  await page.getByRole("button",{name:"Convert",exact:true}).click();await page.getByLabel("Conversion source version",{exact:true}).selectOption(f.oldId);await page.getByLabel("Conversion source calendar year",{exact:true}).fill("2");await page.getByLabel("Conversion source day",{exact:true}).fill("21");await page.getByLabel("Conversion target version",{exact:true}).selectOption(f.newId);await page.getByRole("button",{name:"Convert date",exact:true}).click();await page.getByRole("status").filter({hasText:"elapsed day 380"}).waitFor();
  await page.getByLabel("Conversion target version",{exact:true}).selectOption(f.unanchoredId);await page.getByRole("button",{name:"Convert date",exact:true}).click();await page.getByRole("alert").filter({hasText:"no authored day anchor"}).waitFor();
  await page.getByLabel("Historical calendar evolution",{exact:true}).screenshot({path:path.join(artifactRoot,"worlds-calendar-conversion-desktop.png")});
  await page.getByRole("button",{name:"History",exact:true}).click();await page.getByRole("button",{name:"Set effective period",exact:true}).click();await page.getByLabel("Effective period context",{exact:true}).fill("Retained historical-period draft");
  await page.route(`**/api/worlds/${f.worldId}/calendars/history`,route=>route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary historical-calendar save failure."})}));await page.getByRole("button",{name:"Save calendar history",exact:true}).click();await page.getByRole("alert").filter({hasText:"Temporary historical-calendar"}).waitFor();assert.equal(await page.getByLabel("Effective period context",{exact:true}).inputValue(),"Retained historical-period draft");await page.unroute(`**/api/worlds/${f.worldId}/calendars/history`);
  const other=await context.newPage();await open(other,baseUrl,f);await other.getByRole("button",{name:"Set effective period",exact:true}).click();await other.getByLabel("Effective period context",{exact:true}).fill("Second tab history");await other.getByRole("button",{name:"Save calendar history",exact:true}).click();await other.getByRole("dialog").waitFor({state:"hidden"});
  await page.getByRole("button",{name:"Save calendar history",exact:true}).click();await page.getByRole("button",{name:"Load latest calendar history",exact:true}).waitFor();assert.equal(await page.getByLabel("Effective period context",{exact:true}).inputValue(),"Retained historical-period draft");page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Load latest calendar history",exact:true}).click();await page.getByLabel("Effective period context",{exact:true}).fill("Verified effective context");await page.getByRole("button",{name:"Save calendar history",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});await other.close();
  await page.getByRole("button",{name:"Record reform",exact:true}).click();await page.getByLabel("Reform name",{exact:true}).fill("Later imperial clarification");await page.getByLabel("Predecessor version",{exact:true}).selectOption(f.oldId);await page.getByLabel("Successor version",{exact:true}).selectOption(f.newId);await page.getByLabel("Reason for reform",{exact:true}).fill("An authored year-level reform, without an invented day.");await page.getByLabel("Reform effective representation",{exact:true}).selectOption("approximate");await page.getByLabel("Reform effective year",{exact:true}).fill("900");await page.getByLabel("Linked History entry",{exact:true}).selectOption(f.entry);await page.getByText("Optional exact cutover",{exact:true}).click();await page.getByLabel("Specify consecutive cutover dates",{exact:true}).check();await page.getByLabel("Last old date calendar year",{exact:true}).fill("2");await page.getByLabel("Last old date day",{exact:true}).fill("20");await page.getByRole("button",{name:"Save calendar history",exact:true}).click();await page.getByRole("heading",{name:"Later imperial clarification",exact:true}).waitFor();
  await page.getByRole("button",{name:"Adoption",exact:true}).click();await page.getByLabel("Compare adoption at World year",{exact:true}).fill("1000");await page.getByRole("heading",{name:"Imperial civil offices",exact:true}).waitFor();await page.getByRole("heading",{name:"Temple communities",exact:true}).waitFor();
  await page.getByRole("button",{name:"Record adoption",exact:true}).click();await page.getByLabel("Adopting people or institution",{exact:true}).fill("Harbour guilds");await page.getByLabel("Adoption representation",{exact:true}).selectOption("known");await page.getByLabel("Adoption year",{exact:true}).fill("850");await page.getByLabel("Adoption has no recorded end",{exact:true}).check();await page.getByRole("button",{name:"Save calendar history",exact:true}).click();await page.getByRole("heading",{name:"Harbour guilds",exact:true}).waitFor();await page.getByRole("region",{name:"Selected calendar",exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(artifactRoot,"worlds-calendar-evolution-desktop.png"),fullPage:true});
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(artifactRoot,"worlds-calendar-evolution-mobile.png"),fullPage:true});
  await page.getByRole("button",{name:"Anchors",exact:true}).click();// The Temple tradition has its own gallery selection.
  await page.getByRole("button",{name:"Open Temple Calendar",exact:true}).click();const panel=page.getByLabel("Historical calendar evolution",{exact:true});if(!await panel.getByRole("button",{name:"Anchors",exact:true}).isVisible())await page.getByText("History, adoption & date comparison",{exact:true}).click();await page.getByRole("button",{name:"Anchors",exact:true}).click();await page.getByRole("button",{name:"Establish version anchor",exact:true}).click();await page.getByLabel("Anchor elapsed day",{exact:true}).fill("0");await page.getByLabel("Confirm common day unit",{exact:true}).check();await page.screenshot({path:path.join(artifactRoot,"worlds-calendar-anchor-mobile.png"),fullPage:false});await page.getByRole("button",{name:"Save calendar history",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});
  await page.getByRole("navigation",{name:"World workspace",exact:true}).getByRole("button",{name:/^History/}).click();await page.getByRole("button",{name:"New entry",exact:true}).click();await page.getByLabel("Entry title",{exact:true}).fill("A precise mobile calendar account");await page.getByLabel("Historical account",{exact:true}).fill("Saved without inventing a canonical year.");await page.getByText("Original calendar date",{exact:true}).click();await page.getByLabel("Calendar date precision",{exact:true}).selectOption("known");await page.getByLabel("Source version",{exact:true}).selectOption(f.newId);await page.getByLabel("Source calendar year",{exact:true}).fill("1");await page.getByLabel("Source day",{exact:true}).fill("1");await page.getByRole("button",{name:"Save history",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});await page.reload();await page.getByRole("navigation",{name:"World workspace",exact:true}).getByRole("button",{name:/^History/}).click();
  await page.getByRole("region",{name:"Undated entries",exact:true}).getByText("A precise mobile calendar account",{exact:true}).waitFor();await page.getByRole("region",{name:"Undated entries",exact:true}).getByText(/no canonical World year/).waitFor();await page.getByRole("button",{name:"Chronological list",exact:true}).click();const card=page.locator("article").filter({has:page.getByRole("heading",{name:"A precise mobile calendar account",exact:true})});await card.getByRole("button",{name:"Read account",exact:true}).click();await page.getByRole("dialog").getByText("Canonical World year unknown",{exact:true}).waitFor();await page.getByRole("complementary",{name:"Original calendar context",exact:true}).getByText(/elapsed day 380/).waitFor();await page.getByLabel("Compare original calendar date using",{exact:true}).selectOption(f.oldId);await page.getByRole("status").filter({hasText:"Equivalent date notation"}).waitFor();await page.screenshot({path:path.join(artifactRoot,"worlds-calendar-source-mobile.png"),fullPage:false});await page.getByRole("button",{name:"Close historical details",exact:true}).click();await page.setViewportSize({width:1440,height:900});
  await card.getByRole("button",{name:"Read account",exact:true}).click();await page.getByRole("button",{name:"Edit entry",exact:true}).click();await page.getByLabel("Source day",{exact:true}).fill("2");
  const lifecycleTab=await context.newPage();await open(lifecycleTab,baseUrl,f);await lifecycleTab.getByRole("button",{name:"Archive rules version",exact:true}).click();await lifecycleTab.getByRole("button",{name:"Restore rules version",exact:true}).click();
  await page.getByRole("button",{name:"Save changes",exact:true}).click();await page.getByRole("button",{name:"Load latest version",exact:true}).waitFor();assert.equal(await page.getByLabel("Source day",{exact:true}).inputValue(),"2");page.once("dialog",d=>d.accept());await page.getByRole("button",{name:"Load latest version",exact:true}).click();await page.waitForFunction(()=>document.querySelector<HTMLInputElement>('input[aria-labelledby]')!==null);await page.getByLabel("Source day",{exact:true}).waitFor();assert.equal(await page.getByLabel("Source day",{exact:true}).inputValue(),"1");await page.getByLabel("Source day",{exact:true}).fill("2");await page.getByRole("button",{name:"Save changes",exact:true}).click();await page.getByRole("dialog").waitFor({state:"hidden"});await lifecycleTab.close();
  console.log("PASS: historical calendar browser authoring, supported/refused conversions, two-tab periods and retired-source reference reload, failed drafts, approximate linked reforms, simultaneous/open adoption, phone anchors, exact History persistence/context and desktop/phone screenshots.");
}
