import assert from "node:assert/strict";
import { randomUUID as id } from "node:crypto";
import { mkdir,writeFile } from "node:fs/promises";
import path from "node:path";
import type pg from "pg";
import type { Browser,BrowserContext } from "playwright-core";
import { draftOf,type AtlasBundle,type AtlasMap,type MapDraft } from "../src/features/worlds/atlas";
import { defaultSettlementState,type SettlementEntity,type SettlementShape } from "../src/features/worlds/settlement";
type Service=typeof import("../src/features/worlds/atlas-service");type Worlds=typeof import("../src/features/worlds/world-service");
type Fixture={worldId:string;settlementId:string;parentMap:string;mapId:string;denseId:string};
function populated(map:AtlasMap,b:AtlasBundle,buildings=24):MapDraft{
 const d=draftOf(map,b.geographies);d.settlementShapes=[];d.settlementEntities=[];d.settlementState=defaultSettlementState();d.geographies=[];
 function add(kind:SettlementEntity["kind"],name:string,shape:Omit<SettlementShape,"version"|"id"|"geographyId"|"archived"|"variant">){const gid=id();d.geographies.push({id:gid,revision:null,name,description:`Authored ${name}: no origin or architecture is prescribed.`,kind:"location",context:kind==="building"?"building site":"local area",parentId:map.geographyId!});d.settlementEntities!.push({geographyId:gid,revision:null,kind,classification:kind==="building"?"Custom structure":"",districtIds:[]});d.settlementShapes!.push({version:1,id:id(),geographyId:gid,archived:false,variant:"plain",...shape} as SettlementShape);return gid;}
 const points=(xy:number[][])=>xy.map(([x,y])=>({id:id(),x,y}));
 const a=add("district","Harbor district",{type:"area",points:points([[240,180],[1250,180],[1250,970],[240,970]])} as never),c=add("district","Cultural quarter",{type:"area",points:points([[750,400],[1760,400],[1760,1030],[750,1030]])} as never);
 for(let i=0;i<buildings;i++){const cols=buildings>100?36:8,w=buildings>100?26:70,h=buildings>100?20:55,x=290+(i%cols)*(buildings>100?39:155),y=240+Math.floor(i/cols)*(buildings>100?27:170);const gid=add("building",`Structure ${i+1}`,{type:"area",points:points([[x,y],[x+w,y],[x+w,y+h],[x,y+h]])} as never);d.settlementEntities!.find(e=>e.geographyId===gid)!.districtIds=i%3===0?[a,c]:[a];}
 for(let i=0;i<(buildings>100?24:3);i++)add("street",`Route ${i+1}`,{type:"line",width:buildings>100?8:24,curve:.6,points:points([[200,210+i*32],[700,250+i*32],[1790,230+i*32]])} as never);
 add("wall","Outer boundary",{type:"line",width:12,curve:0,points:points([[150,130],[1840,130],[1860,1060],[150,1060],[150,160]])} as never);
 add("waterway","Canal",{type:"line",width:40,curve:.5,points:points([[100,900],[900,960],[1900,880]])} as never);
 add("space","Common square",{type:"area",points:points([[1000,600],[1200,600],[1250,770],[950,770]])} as never);
 add("landmark","Dimensional beacon",{type:"marker",point:{x:1100,y:680},size:25,rotation:0} as never);return d;
}
export async function settlementServiceChecks(service:Service,worlds:Worlds,pool:pg.Pool,foreign:string):Promise<Fixture>{
 const worldId=await worlds.createWorld("world-god",{name:"Standalone settlement Atlas"}),settlementId=id();await service.changeAtlas("world-god",worldId,{action:"geography",draft:{id:settlementId,revision:null,name:"Glasshaven",description:"A settlement whose author decides its nature.",kind:"location",context:"settlement",parentId:null}});
 const mapId=await service.changeAtlas("world-god",worldId,{action:"create",name:"Glasshaven overview",description:"Dedicated settlement layout.",scope:"local",mapKind:"settlement",geographyId:settlementId});
 const parentMap=await service.changeAtlas("world-god",worldId,{action:"create",name:"Regional approaches",description:"The same settlement identity at a higher level.",scope:"regional"});
 let b=await service.getAtlas("world-god",worldId,false,parentMap),m=b.maps.find(m=>m.id===parentMap)!;const p=draftOf(m,b.geographies);p.features=[{id:id(),geographyId:settlementId,archived:false,geometry:{version:1,type:"point",point:{x:1000,y:600}}}];p.geographies=b.geographies.filter(g=>g.id===settlementId).map(g=>({id:g.id,revision:g.revision,name:g.name,description:g.description,kind:g.kind,context:g.context,parentId:g.parentId}));await service.changeAtlas("world-god",worldId,{action:"save",id:parentMap,revision:m.revision,draft:p});
 b=await service.getAtlas("world-god",worldId,false,mapId);m=b.maps.find(m=>m.id===mapId)!;await service.changeAtlas("world-god",worldId,{action:"save",id:mapId,revision:m.revision,draft:populated(m,b)});
 b=await service.getAtlas("world-god",worldId,false,mapId);m=b.maps.find(m=>m.id===mapId)!;assert.equal(m.settlementShapes!.length,33);const original=structuredClone(m),draft=draftOf(m,b.geographies);
 await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:mapId,revision:m.revision,draft:{...draft,settlementShapes:[]}}),/Keep saved settlement/);
 const invalid=structuredClone(draft);invalid.settlementShapes![0].geographyId=id();await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:mapId,revision:m.revision,draft:invalid}));
 const alternate=await service.changeAtlas("world-god",worldId,{action:"duplicate",id:mapId,revision:m.revision,newId:id(),name:"Glasshaven reference"});const copy=(await service.getAtlas("world-god",worldId,false,alternate)).maps.find(m=>m.id===alternate)!;assert.equal(copy.mapKind,"settlement");assert.equal(copy.geographyId,settlementId);assert.deepEqual(copy.settlementShapes!.map(s=>s.geographyId),original.settlementShapes!.map(s=>s.geographyId));assert.notEqual(copy.settlementShapes![0].id,original.settlementShapes![0].id);
 const fresh=(await service.getAtlas("world-god",worldId,false,mapId));m=fresh.maps.find(m=>m.id===mapId)!;const edit=draftOf(m,fresh.geographies);edit.geographies[0].description="Revised in original chart";await service.changeAtlas("world-god",worldId,{action:"save",id:mapId,revision:m.revision,draft:edit});await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:alternate,revision:copy.revision,draft:draftOf(copy,fresh.geographies)}),/newer/);
 m=(await service.getAtlas("world-god",worldId,false,mapId)).maps.find(m=>m.id===mapId)!;await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"save",id:mapId,revision:m.revision-1,draft:edit}),/newer/);
 for(const user of ["other-god","world-admin","world-player"])await assert.rejects(()=>service.getAtlas(user,worldId,false,mapId));assert.equal((await service.getAtlas("world-admin",worldId,true,mapId)).canEdit,false);await assert.rejects(()=>service.changeAtlas("world-admin",worldId,{action:"archive-map",id:mapId,revision:m.revision}));
 await assert.rejects(()=>service.changeAtlas("world-god",worldId,{action:"create",name:"Foreign",description:"",scope:"local",mapKind:"settlement",geographyId:id()}));await assert.rejects(()=>service.getAtlas("world-god",foreign,false,mapId));
 await assert.rejects(()=>pool.query("update world_atlas_settlement_shape set world_id=$1 where map_id=$2",[foreign,mapId]),/foreign key/);
 const shape=m.settlementShapes![0];assert.equal((await pool.query("select world_atlas_settlement_shape_valid($1::jsonb) as valid",[shape])).rows[0].valid,true);const broken={...shape,variant:undefined};assert.equal((await pool.query("select world_atlas_settlement_shape_valid($1::jsonb) as valid",[broken])).rows[0].valid,false);
 await assert.rejects(()=>pool.query("update world_atlas_settlement_shape set content=$1 where id=$2",[broken,shape.id]),/check constraint/);
 const generic=await service.changeAtlas("world-god",worldId,{action:"create",name:"Adoptable native map",description:"Original source",scope:"local"});let adopt=(await service.getAtlas("world-god",worldId,false,generic)).maps.find(m=>m.id===generic)!;const adoptionDraft=draftOf(adopt,(await service.getAtlas("world-god",worldId,false,generic)).geographies);adoptionDraft.drawings=[{version:1,id:id(),name:"Retained watercourse",geographyId:null,archived:false,type:"path",kind:"stream",points:[{id:id(),x:200,y:300},{id:id(),x:1200,y:650}],width:8,curve:.5}];await service.changeAtlas("world-god",worldId,{action:"save",id:generic,revision:adopt.revision,draft:adoptionDraft});adopt=(await service.getAtlas("world-god",worldId,false,generic)).maps.find(m=>m.id===generic)!;const before={features:adopt.features,drawings:adopt.drawings,presentation:adopt.presentation};await service.changeAtlas("world-god",worldId,{action:"adopt-settlement",id:generic,revision:adopt.revision,geographyId:settlementId});adopt=(await service.getAtlas("world-god",worldId,false,generic)).maps.find(m=>m.id===generic)!;assert.deepEqual({features:adopt.features,drawings:adopt.drawings,presentation:adopt.presentation},before);
 const denseId=await service.changeAtlas("world-god",worldId,{action:"create",name:"Dense settlement stress",description:"Synthetic scalability fixture",scope:"local",mapKind:"settlement",settlement:{id:id(),revision:null,name:"Dense city",description:"",kind:"location",context:"settlement",parentId:null},geographyId:null}).catch(()=>"");assert.equal(denseId,""); // invalid compound creation must roll back
 const denseSettlement=id();const dense=await service.changeAtlas("world-god",worldId,{action:"create",name:"Dense settlement stress",description:"Synthetic scalability fixture",scope:"local",mapKind:"settlement",settlement:{id:denseSettlement,revision:null,name:"Dense city",description:"",kind:"location",context:"settlement",parentId:null},geographyId:denseSettlement});b=await service.getAtlas("world-god",worldId,false,dense);m=b.maps.find(m=>m.id===dense)!;await service.changeAtlas("world-god",worldId,{action:"save",id:dense,revision:m.revision,draft:populated(m,b,900)});
 const header=await service.getAtlas("world-god",worldId);assert.equal(header.maps.find(m=>m.id===dense)!.settlementShapes,undefined);const target=await service.getAtlas("world-god",worldId,false,mapId);assert.equal(target.maps.find(m=>m.id===dense)!.settlementShapes,undefined);assert.ok(!target.geographies.some(g=>g.parentId===denseSettlement),"A targeted map read must omit unrelated building descriptions.");
 console.log("PASS: settlement source, stable entities and overlapping memberships, atomic rollback, same-World FKs, adoption/duplication, cross-map metadata conflicts, targeted loading and role privacy; 900-building fixture persists.");return {worldId,settlementId,parentMap,mapId,denseId:dense};
}

async function login(c:BrowserContext,url:string,user="world-god"){const r=await c.request.post(`${url}/api/auth/sign-in/email`,{headers:{Origin:url},data:{email:`${user}@example.invalid`,password:"Worlds-Test-Only-Password!"}});assert.equal(r.status(),200,await r.text());}
export async function settlementBrowserChecks(browser:Browser,baseUrl:string,f:Fixture,pool:pg.Pool){
 const capture=path.resolve("docs/screenshots/worlds-atlas-pass-3e-a");await mkdir(capture,{recursive:true});const c=await browser.newContext({viewport:{width:1440,height:1100},hasTouch:true,extraHTTPHeaders:{"X-Forwarded-For":"203.0.113.101"}});await login(c,baseUrl);const page=await c.newPage(),errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("dialog",d=>d.accept());const api=`${baseUrl}/api/worlds/${f.worldId}/atlas`,url=`${baseUrl}/worlds/${f.worldId}`;
 async function read(mapId?:string){const r=await c.request.get(`${api}${mapId?`?map=${mapId}`:""}`);assert.equal(r.status(),200);return await r.json() as AtlasBundle;}
 async function post(body:unknown){const r=await c.request.post(api,{headers:{Origin:baseUrl},data:body});assert.equal(r.status(),200,await r.text());return await r.json() as {id:string};}
 async function library(p=page){await p.goto(url);await p.getByRole("button",{name:"Atlas",exact:true}).click();await p.getByRole("heading",{name:"Atlas",exact:true}).waitFor();}
 async function open(name:string,p=page){await library(p);await p.getByRole("button",{name:`Open ${name}`,exact:true}).click();await p.getByRole("region",{name:"Settlement editor",exact:true}).waitFor();}
 const canvas=()=>page.getByLabel("Editable settlement map",{exact:true});
 async function point(x:number,y:number){const svg=canvas();await svg.evaluate(node=>node.scrollIntoView({block:"center",behavior:"instant"}));return await svg.evaluate((node,p)=>{const m=(node as SVGSVGElement).getScreenCTM()!;return {x:p.x*m.a+m.e,y:p.y*m.d+m.f};},{x,y});}
 async function tap(x:number,y:number,touch=false){const p=await point(x,y);if(touch)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);}
 async function rect(x:number,y:number,w:number,h:number,touch=false){const a=await point(x,y),b=await point(x+w,y+h);if(touch){const session=await c.newCDPSession(page);await session.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{id:1,x:a.x,y:a.y}]});await page.waitForTimeout(40);await session.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{id:1,x:b.x,y:b.y}]});await page.waitForTimeout(40);await session.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});await session.detach();}else{await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:6});await page.mouse.up();}}
 async function tool(name:string,nameOfPlace:string){await page.getByRole("button",{name,exact:true}).click();await page.getByLabel("New place name",{exact:true}).fill(nameOfPlace);}
 async function pathTool(name:string,place:string,points:number[][],touch=false){await tool(name,place);for(const [x,y]of points)await tap(x,y,touch);await page.getByRole("button",{name:"Complete object",exact:true}).click();}
 async function save(p=page){const button=p.getByRole("button",{name:"Save settlement",exact:true});assert.equal(await button.isEnabled(),true,`Save must be enabled after the edit. Alerts: ${(await p.getByRole("alert").allTextContents()).join(" | ")}; status: ${(await p.getByRole("status").allTextContents()).join(" | ")}`);await button.click();await p.getByRole("status").filter({hasText:"Settlement saved"}).waitFor();}
 async function shot(name:string){await page.evaluate(()=>{document.documentElement.style.scrollBehavior="auto";window.scrollTo({top:0,behavior:"instant"});});await page.waitForTimeout(120);await page.screenshot({path:path.join(capture,name),fullPage:true});}
 await library();await page.getByRole("button",{name:"New settlement map",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("Map name",{exact:true}).fill("Glasshaven town plan");await dialog.getByLabel("Description",{exact:true}).fill("A settlement built without any required genre or origin.");await dialog.getByLabel("Represented place",{exact:true}).selectOption(f.settlementId);await dialog.getByLabel("Map scale",{exact:true}).selectOption("local");await dialog.getByRole("button",{name:"Create map",exact:true}).click();await page.getByRole("region",{name:"Settlement editor",exact:true}).waitFor();
 await pathTool("District","Gardens quarter",[[300,180],[1250,180],[1250,900],[300,900]]);
 await page.getByLabel("Place description",{exact:true}).fill("A district of botanical workshops and floating gardens.");await page.getByRole("button",{name:"Apply properties",exact:true}).click();await shot("district-properties.png");
 await pathTool("District","Cultural commons",[[850,350],[1750,350],[1750,1020],[850,1020]]);
 await pathTool("Street","Market way",[[200,450],[700,460],[1150,540],[1750,470]]);
 await page.getByLabel("Path width",{exact:true}).fill("30");await page.getByRole("button",{name:"Apply properties",exact:true}).click();
 await pathTool("Street","Garden lane",[[950,170],[900,700],[930,1020]]);
 await pathTool("Waterway","Canal of reflections",[[120,920],[900,990],[1880,890]]);
 await pathTool("Wall","Custom perimeter",[[240,120],[1780,120],[1820,1080],[240,1080],[240,180]]);
 await pathTool("Open space","Gathering square",[[980,600],[1300,600],[1300,820],[980,820]]);
 for(const [i,x,y]of [[1,430,260],[2,670,260],[3,1070,260],[4,1380,600],[5,460,600],[6,710,640]]){await tool("Rectangle building",i===1?"Glass conservatory":`Workshop ${i}`);await rect(x,y,140,105);}
 await pathTool("Building outline","Irregular laboratory",[[1400,250],[1550,250],[1550,330],[1630,330],[1630,440],[1400,440]]);
 await tool("Landmark","Beacon of stories");await tap(1130,700);
 await page.getByLabel("Place description",{exact:true}).fill("A beacon built by its author's own unexplained craft.");await page.getByLabel("Authored classification",{exact:true}).fill("Narrative beacon");await page.getByRole("button",{name:"Apply properties",exact:true}).click();
 await page.getByRole("button",{name:"Glass conservatory",exact:true}).click();await page.getByLabel("Place description",{exact:true}).fill("Plants from imagined dimensions grow inside this structure.");await page.getByLabel("Authored classification",{exact:true}).fill("Botanical laboratory");for(const checkbox of await page.locator('input[name="districtIds"]').all())await checkbox.check();await page.getByRole("button",{name:"Apply properties",exact:true}).click();await shot("building-properties.png");await save();
 let b=await read();const mapId=b.maps.find(m=>m.name==="Glasshaven town plan")!.id;b=await read(mapId);let town=b.maps.find(m=>m.id===mapId)!;assert.equal(town.settlementShapes!.length,15);assert.equal(town.geographyId,f.settlementId);const original=structuredClone(town),building=town.settlementShapes!.find(s=>b.geographies.find(g=>g.id===s.geographyId)?.name==="Glass conservatory")!;
 await shot("desktop-settlement-editor.png");await shot("streets-footprints.png");await page.getByRole("button",{name:"Terrain and artwork",exact:true}).click();await page.getByText("Style and layers",{exact:true}).click();await page.getByLabel("Map appearance",{exact:true}).selectOption("illuminated");await page.getByRole("button",{name:"Save map",exact:true}).click();await page.getByRole("status").filter({hasText:"Map saved"}).waitFor();await page.getByRole("button",{name:"Return to settlement",exact:true}).click();await page.getByRole("region",{name:"Settlement editor",exact:true}).waitFor();assert.deepEqual((await read(mapId)).maps.find(m=>m.id===mapId)!.settlementShapes,original.settlementShapes);await page.getByRole("button",{name:"Map library",exact:true}).click();await open("Glasshaven town plan");b=await read(mapId);town=b.maps.find(m=>m.id===mapId)!;assert.deepEqual(town.settlementShapes,original.settlementShapes);
 await page.getByRole("button",{name:"Glass conservatory",exact:true}).click();await page.getByRole("button",{name:"Right 10",exact:true}).click();await page.getByRole("button",{name:"Rotate 15 degrees",exact:true}).click();await page.getByRole("button",{name:"Enlarge 10%",exact:true}).click();await page.getByRole("button",{name:"Undo",exact:true}).click();await page.getByRole("button",{name:"Redo",exact:true}).click();
 await page.getByRole("button",{name:"Market way",exact:true}).click();await page.getByRole("button",{name:"Edit points",exact:true}).click();await page.getByLabel("Object point",{exact:true}).selectOption({label:"Point 2"});await page.getByLabel("Point Y",{exact:true}).fill("490");await page.getByRole("button",{name:"Apply point",exact:true}).click();
 await page.getByRole("button",{name:"Gardens quarter",exact:true}).click();await page.getByLabel("Object point",{exact:true}).selectOption({label:"Point 2"});await page.getByLabel("Point X",{exact:true}).fill("1280");await page.getByRole("button",{name:"Apply point",exact:true}).click();await save();
 b=await read(mapId);town=b.maps.find(m=>m.id===mapId)!;const moved=town.settlementShapes!.find(s=>s.id===building.id)!;assert.equal(moved.geographyId,building.geographyId);assert.notDeepEqual(moved,building);assert.deepEqual(moved.type!=="marker"?moved.points.map(p=>p.id):[],building.type!=="marker"?building.points.map(p=>p.id):[]);await page.getByRole("button",{name:"Glass conservatory",exact:true}).click();await page.getByRole("button",{name:"Duplicate object",exact:true}).click();await save();const duplicated=await read(mapId),copyGeo=duplicated.geographies.find(g=>g.name==="Glass conservatory copy")!;assert.notEqual(copyGeo.id,building.geographyId);assert.ok(duplicated.maps.find(m=>m.id===mapId)!.settlementShapes!.some(s=>s.geographyId===copyGeo.id));
 await page.getByRole("button",{name:"Workshop 2",exact:true}).click();await page.getByRole("button",{name:"Archive object",exact:true}).click();await save();await page.getByRole("button",{name:"Workshop 2 (archived)",exact:true}).click();await page.getByRole("button",{name:"Restore object",exact:true}).click();await save();
 await page.getByText("Settlement layers",{exact:true}).click();await page.getByLabel("Lock buildings",{exact:true}).check();await save();const count=await canvas().locator("[data-settlement]").count();await page.getByRole("button",{name:"Rectangle building",exact:true}).click();await rect(400,820,100,80);await page.getByRole("alert").filter({hasText:"unlock Buildings"}).waitFor();assert.equal(await canvas().locator("[data-settlement]").count(),count);await page.getByLabel("Lock buildings",{exact:true}).uncheck();await page.getByRole("button",{name:"Select",exact:true}).click();await save();
 const other=await c.newPage();other.on("dialog",d=>d.accept());await open("Glasshaven town plan",other);await page.getByRole("button",{name:"Glass conservatory",exact:true}).click();await other.getByRole("button",{name:"Glass conservatory",exact:true}).click();await page.getByLabel("Place description",{exact:true}).fill("First tab retained revision.");await page.getByRole("button",{name:"Apply properties",exact:true}).click();await save();await other.getByLabel("Place description",{exact:true}).fill("Losing draft remains available.");await other.getByRole("button",{name:"Apply properties",exact:true}).click();await other.getByRole("button",{name:"Save settlement",exact:true}).click();await other.getByRole("alert").filter({hasText:"newer"}).waitFor();assert.equal(await other.getByLabel("Place description",{exact:true}).inputValue(),"Losing draft remains available.");await other.close();
 const parent=(await read(f.parentMap)).maps.find(m=>m.id===f.parentMap)!;await post({action:"connect",id:parent.id,revision:parent.revision,geographyId:f.settlementId,destinationMapId:mapId});await page.goto(`${url}?atlas=${f.parentMap}&place=${f.settlementId}`);await page.getByRole("button",{name:"Open Glasshaven town plan · preferred",exact:true}).click();await page.getByRole("heading",{name:"Glasshaven town plan",exact:true}).waitFor();await shot("connected-navigation.png");await shot("desktop-town-map.png");await page.getByRole("button",{name:"Glass conservatory",exact:true}).first().click();await page.getByRole("complementary",{name:"Place information"}).getByText("Botanical laboratory",{exact:true}).waitFor();await shot("settlement-explore.png");await page.reload();await page.getByRole("heading",{name:"Glass conservatory",exact:true}).waitFor();await page.goBack();await page.goForward();await page.getByRole("heading",{name:"Glasshaven town plan",exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});await open("Glasshaven town plan");await tool("Rectangle building","Touch workshop");await rect(320,760,130,100,true);await page.getByLabel("Place description",{exact:true}).fill("Created with native touch on a phone.");await page.getByRole("button",{name:"Apply properties",exact:true}).click();await pathTool("Street","Touch trail",[[500,830],[750,860],[900,920]],true);await page.getByRole("button",{name:"Move object",exact:true}).click();await rect(385,810,30,0,true);await save();const touchBundle=await read(mapId),touchPlace=touchBundle.geographies.find(g=>g.name==="Touch workshop")!,touchShape=touchBundle.maps.find(m=>m.id===mapId)!.settlementShapes!.find(s=>s.geographyId===touchPlace.id)!;assert.equal(touchShape.type,"area");if(touchShape.type!=="area")throw Error();assert.ok(Math.abs(touchShape.points[0].x-350)<1,"Native touch movement must persist its translated footprint.");assert.ok(Math.abs(touchShape.points[0].y-760)<1);await shot("mobile-settlement-editor.png");assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole("button",{name:"Explore settlement",exact:true}).click();await page.getByRole("button",{name:"Touch workshop",exact:true}).first().click();await page.getByRole("heading",{name:"Touch workshop",exact:true}).waitFor();await shot("mobile-settlement-explore.png");
 await library();await page.getByRole("button",{name:"New settlement map",exact:true}).click();const newDialog=page.getByRole("dialog");await newDialog.getByLabel("Map name",{exact:true}).fill("Unconventional habitat");await newDialog.getByLabel("Represented place",{exact:true}).selectOption("new");await newDialog.getByLabel("Settlement name",{exact:true}).fill("Drifting dimensional colony");await newDialog.getByRole("button",{name:"Create map",exact:true}).click();await page.getByRole("region",{name:"Settlement editor",exact:true}).waitFor();const authored=(await read()).geographies.find(g=>g.name==="Drifting dimensional colony")!;assert.equal(authored.context,"settlement");assert.equal((await read()).maps.find(m=>m.name==="Unconventional habitat")!.geographyId,authored.id);
 await page.setViewportSize({width:1440,height:1100});const t=performance.now();await open("Dense settlement stress");const openingMs=performance.now()-t;await canvas().locator("[data-settlement]").nth(899).waitFor();const chooseStart=performance.now();await page.getByLabel("Find settlement object",{exact:true}).fill("Structure 450");await page.getByRole("button",{name:"Structure 450",exact:true}).click();const selectionMs=performance.now()-chooseStart;const editStart=performance.now();await page.getByRole("button",{name:"Right 10",exact:true}).click();await save();const editSaveMs=performance.now()-editStart;await shot("dense-settlement.png");
 const navigationStart=performance.now();await page.getByRole("button",{name:"Explore settlement",exact:true}).click();await page.getByRole("heading",{name:"Dense settlement stress",exact:true}).waitFor();await page.getByLabel("Explorable geographic map",{exact:true}).locator("[data-settlement]").nth(899).waitFor();const navigationMs=performance.now()-navigationStart;await shot("dense-settlement-explore.png");
 const roles:[string,number][]=[["other-god",404],["world-player",403],["world-admin",404]];for(const [user,status]of roles){const ctx=await browser.newContext({extraHTTPHeaders:{"X-Forwarded-For":`203.0.113.${user==="other-god"?102:user==="world-player"?103:104}`}});await login(ctx,baseUrl,user);const r=await ctx.request.get(`${api}?map=${mapId}`);assert.equal(r.status(),status);assert.match(r.headers()["cache-control"],/no-store/);if(user==="world-admin"){const p=await ctx.newPage();await p.goto(`${url}?review=1&atlas=${mapId}&place=${building.geographyId}`);await p.getByRole("heading",{name:"Glass conservatory",exact:true}).waitFor();assert.equal(await p.getByRole("button",{name:"Edit map",exact:true}).count(),0);const forged=await ctx.request.post(api,{headers:{Origin:baseUrl},data:{action:"archive-map",id:mapId,revision:1}});assert.equal(forged.status(),404);}await ctx.close();}
 const anon=await browser.newContext();assert.equal((await anon.request.get(`${api}?map=${mapId}`)).status(),401);await anon.close();assert.equal((await pool.query("select count(*)::int as n from world_settlement_entity where settlement_id=$1",[f.settlementId])).rows[0].n>30,true);assert.deepEqual(errors,[]);await writeFile(path.join(capture,"performance.json"),JSON.stringify({buildings:900,openingMs,selectionMs,editSaveMs,navigationMs,desktop:[1440,1100],phone:[390,844],nativeTouchAuthoring:true,staleDraftRetained:true},null,2));await c.close();
 console.log("PASS: production settlement browser creation, paths/footprints/areas/landmarks, metadata and overlapping districts, save/reopen, edits/undo/redo, archive/restore, locked layers, two-tab conflict, Explore/connected links, phone touch creation and 900-building performance/privacy.");
}
