import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type pg from "pg";
import type { Browser, BrowserContext, Page, Locator } from "playwright-core";
import type { AssociationBundle } from "../src/features/worlds/campaign-associations";
type Worlds = typeof import("../src/features/worlds/world-service");
type Bridge = typeof import("../src/features/worlds/campaign-association-service");
type Timelines = typeof import("../src/features/worlds/branching-history-service");

export async function seedAssociationCampaigns(pool: pg.Pool) {
  const ownerColumn = (await pool.query("select 1 from information_schema.columns where table_name='campaign' and column_name='owner_user_id'")).rowCount ? ",owner_user_id" : "";
  const create = async (name: string, owner = "world-god") => (await pool.query(`insert into campaign(name,overview,attribute_points,skill_points,max_starting_skill,points_to_unlock_next_tier,max_points_in_skill,starting_credit_amount,currency_system,fate_point_method,created_by_user_id${ownerColumn}) values($1,'Association fixture',100,100,10,10,10,100,'Credits','Assigned',$2${ownerColumn ? ",$2" : ""}) returning id`, [name, owner])).rows[0].id as number;
  const heirs = await create("Bridge B Lost Heirs"), imperial = await create("Bridge B Imperial Dawn"), ancient = await create("Bridge B Ancient War"), archived = await create("Bridge B Archived Campaign"), foreign = await create("Bridge B Foreign Campaign", "other-god"), admin = await create("Bridge B Admin Campaign", "world-admin");
  await pool.query("insert into campaign_player(campaign_id,user_id) values($1,'world-player'),($1,'other-god')", [heirs]);
  const scale: number[] = [];for (let i = 0; i < 100; i++) scale.push(await create(`Bridge B Scale ${String(i + 1).padStart(3, "0")}`));
  return { heirs, imperial, ancient, archived, foreign, admin, scale };
}
export async function seedAssociationUpgrade(pool: pg.Pool, worldId: string) {
  const primary = (await pool.query("select id from world_timeline where world_id=$1 and is_primary", [worldId])).rows[0].id;
  const branch = randomUUID(), child = randomUUID();
  await pool.query("insert into world_timeline(id,world_id,parent_id,divergence_year,name) values($1,$2,$3,650,'Retained pre-Bridge-B alternative')", [branch, worldId, primary]);
  const source = (await pool.query("select v.* from world_history_version v where world_id=$1 and entry_id is not null limit 1", [worldId])).rows[0];
  const version = randomUUID();
  await pool.query("insert into world_history_version(id,world_id,entity_id,entry_id,timeline_id,payload,dating_system_id,start_version_id,end_version_id) select $1,world_id,entity_id,entry_id,$2,jsonb_set(payload,'{account}','\"Retained alternate historical account\"'),dating_system_id,start_version_id,end_version_id from world_history_version where id=$3", [version, branch, source.id]);
  await pool.query("insert into world_history_head(timeline_id,world_id,entity_id,version_id,mode,revision,source_timeline_id,source_version_id,source_revision) values($1,$2,$3,$4,'interpretation',1,$5,$6,1)", [branch, worldId, source.entity_id, version, primary, source.id]);
  await pool.query("insert into world_timeline(id,world_id,parent_id,divergence_year,name) values($1,$2,$3,900,'Retained nested alternative')", [child, worldId, branch]);
  await pool.query("insert into world_history_head(timeline_id,world_id,entity_id,version_id,mode,revision,source_timeline_id,source_version_id,source_revision) values($1,$2,$3,$4,'inherited',1,$5,$4,1)", [child, worldId, source.entity_id, version, branch]);
  const tables = (await pool.query("select tablename from pg_tables where schemaname='public' and tablename like 'world%' order by tablename")).rows;
  const snapshots = new Map<string, unknown>();
  for (const { tablename } of tables) { assert.match(tablename, /^[a-z_]+$/);snapshots.set(tablename, (await pool.query(`select to_jsonb(t) row from ${tablename} t order by to_jsonb(t)::text`)).rows); }
  return async () => {
    for (const [table, expected] of snapshots) assert.deepEqual((await pool.query(`select to_jsonb(t) row from ${table} t order by to_jsonb(t)::text`)).rows, expected, `0113 preserves ${table}`);
    for (const table of ["world_campaign_context", "world_campaign_home", "world_authoring_selection", "world_campaign_context_change"]) assert.equal((await pool.query(`select count(*)::int n from ${table}`)).rows[0].n, 0);
    console.log("PASS: populated 0112→0113 and reapplication preserve all prior Worlds, pinned alternate/nested interpretations, dates, calendars, Atlas and protected dungeon data; new association tables start empty.");
  };
}
export async function associationServiceChecks(worlds: Worlds, bridge: Bridge, timelines: Timelines, pool: pg.Pool, fixture: Awaited<ReturnType<typeof seedAssociationCampaigns>>, foreignWorld: string) {
  const choices = await bridge.eligibleCampaigns("world-god");
  const choice = (id: number) => choices.find(item => item.id === id)!;
  assert.equal(choices.some(row => row.id === fixture.foreign || row.id === fixture.admin), false);
  assert.equal((await bridge.eligibleCampaigns("other-god")).some(row => row.id === fixture.heirs), false, "Campaign membership grants no eligibility");
  const count = async () => (await pool.query("select (select count(*)::int from world) worlds,(select count(*)::int from world_timeline) timelines,(select count(*)::int from world_campaign_context) contexts,(select count(*)::int from world_campaign_home) homes,(select count(*)::int from world_campaign_context_change) audits")).rows[0];
  const beforeInvalid = await count();
  await assert.rejects(worlds.createWorld("world-god", { name: "Atomic forged Campaign", associatedCampaigns: [{ id: fixture.foreign, updatedAt: choice(fixture.heirs).updatedAt }] }), /unavailable/);
  await assert.rejects(worlds.createWorld("world-god", { name: "Atomic stale Campaign", associatedCampaigns: [{ id: fixture.heirs, updatedAt: "2000-01-01T00:00:00.000Z" }] }), /changed/);
  await assert.rejects(worlds.createWorld("world-god", { name: "Atomic bad classification", associatedCampaigns: [{ id: fixture.heirs, updatedAt: choice(fixture.heirs).updatedAt }], tagIds: [2147483647] }), /available Era/);
  assert.deepEqual(await count(), beforeInvalid);
  const worldId = await worlds.createWorld("world-god", { name: "Bridge B Association Foundation", associatedCampaigns: [fixture.heirs, fixture.imperial, fixture.ancient].map(id => ({ id, updatedAt: choice(id).updatedAt })) });
  const primary = (await worlds.getWorld("world-god", worldId)).selectedTimeline.id;
  let bundle = await bridge.worldCampaignAssociations("world-god", worldId);assert.equal(bundle.contexts.length, 3);assert.ok(bundle.contexts.every(row => row.timelineId === primary && row.startingYear === null));assert.equal(bundle.selection.contextId, null);assert.ok(bundle.homes.every(home => home.contextId === null));
  const single = await worlds.createWorld("world-god", { name: "Bridge B Single", associatedCampaigns: [{ id: fixture.heirs, updatedAt: choice(fixture.heirs).updatedAt }] });
  assert.equal((await bridge.worldCampaignAssociations("world-god", single)).contexts.length, 1);assert.equal((await bridge.campaignWorldAssociations("world-god", fixture.heirs)).contexts.length, 2);
  const branch = await timelines.changeTimeline("world-god", worldId, { action: "create", parentRevision: 1, draft: { parentId: primary, divergenceYear: 650, name: "Bridge B Empire Survives" } });
  const twin = await timelines.changeTimeline("world-god", worldId, { action: "create", parentRevision: 1, draft: { parentId: primary, divergenceYear: 650, name: "Bridge B Same Year Alternative" } });
  const child = await timelines.changeTimeline("world-god", worldId, { action: "create", parentRevision: 1, draft: { parentId: branch, divergenceYear: 900, name: "Bridge B Divine Empire" } });
  const add = async (campaignId: number, timelineId: string, startingYear: number | null = null, target = worldId) => bridge.changeCampaignAssociation("world-god", target, { action: "link", campaignId, timelineId, startingYear, campaignUpdatedAt: choice(campaignId).updatedAt });
  const heirsBranch = (await add(fixture.heirs, branch, -900))!;await add(fixture.imperial, branch, 0);await add(fixture.ancient, child, 900);await add(fixture.heirs, child, 500);await add(fixture.ancient, twin, 650);
  await assert.rejects(add(fixture.heirs, branch), /already.*retained/);
  await assert.rejects(add(fixture.heirs, (await worlds.getWorld("other-god", foreignWorld)).selectedTimeline.id), /unavailable/);
  await assert.rejects(bridge.changeCampaignAssociation("world-god", worldId, { action: "link", campaignId: fixture.foreign, timelineId: primary, campaignUpdatedAt: choice(fixture.heirs).updatedAt }), /unavailable/);
  for (const user of ["other-god", "world-player", "world-admin", "anonymous"]) { await assert.rejects(bridge.worldCampaignAssociations(user, worldId), /unavailable|access/);await assert.rejects(bridge.campaignWorldAssociations(user, fixture.heirs), /unavailable|access/);await assert.rejects(bridge.changeCampaignAssociation(user, worldId, { action: "link", campaignId: fixture.heirs, timelineId: primary, campaignUpdatedAt: choice(fixture.heirs).updatedAt }), /unavailable|access/); }
  assert.equal((await bridge.worldCampaignAssociations("world-admin", worldId, true)).canManage, false);
  const adminWorld = await worlds.createWorld("world-admin", { name: "Bridge B Admin owned", associatedCampaigns: [{ id: fixture.admin, updatedAt: (await bridge.eligibleCampaigns("world-admin"))[0].updatedAt }] });assert.equal((await bridge.worldCampaignAssociations("world-admin", adminWorld)).contexts.length, 1);
  const historyBefore = await worlds.getWorld("world-god", worldId);
  await bridge.changeCampaignAssociation("world-god", worldId, { action: "home", campaignId: fixture.heirs, revision: 1, contextId: heirsBranch });
  await bridge.changeCampaignAssociation("world-god", worldId, { action: "select", campaignId: fixture.heirs, revision: 0, contextId: heirsBranch, viewingYear: 300 });
  assert.equal((await bridge.authoringContextSummary("world-god")).context!.id,heirsBranch);assert.equal((await bridge.authoringContextSummary("other-god")).selection.contextId,null);assert.equal((await bridge.authoringContextSummary("world-admin")).context,null);for(const user of ["world-player","anonymous"])await assert.rejects(bridge.authoringContextSummary(user),/access/);
  const edit = { action: "edit", campaignId: fixture.heirs, id: heirsBranch, revision: 1, startingYear: -1e12 };
  await bridge.changeCampaignAssociation("world-god", worldId, edit);
  const beforeStale = await count();await assert.rejects(bridge.changeCampaignAssociation("world-god", worldId, edit), /newer version/);assert.deepEqual(await count(), beforeStale);
  await assert.rejects(bridge.changeCampaignAssociation("world-god", worldId, { action: "remove", campaignId: fixture.heirs, id: heirsBranch, revision: 2, homeRevision: 2 }), /explicitly clear/);
  const singleContext = (await bridge.worldCampaignAssociations("world-god", single)).contexts[0];
  await bridge.changeCampaignAssociation("world-god", worldId, { action: "remove", campaignId: fixture.heirs, id: heirsBranch, revision: 2, homeRevision: 2, homeOutcome: "replace", replacementId: singleContext.id });
  bundle = await bridge.worldCampaignAssociations("world-god", worldId);assert.equal(bundle.selection.contextId, heirsBranch);assert.equal(bundle.selection.viewingYear, 300);assert.equal(bundle.contexts.find(row => row.id === heirsBranch)!.available, false);assert.equal(bundle.homes.find(row => row.campaignId === fixture.heirs)!.contextId, singleContext.id);
  assert.equal((await bridge.authoringContextSummary("world-god")).context!.available,false);
  await bridge.changeCampaignAssociation("world-god", worldId, { action: "restore", campaignId: fixture.heirs, id: heirsBranch, revision: 3 });assert.equal((await bridge.worldCampaignAssociations("world-god", worldId)).contexts.find(row => row.id === heirsBranch)!.available, true);
  await timelines.changeTimeline("world-god", worldId, { action: "archive", id: branch, revision: 1 });bundle = await bridge.worldCampaignAssociations("world-god", worldId);assert.equal(bundle.contexts.find(row => row.id === heirsBranch)!.available, false);assert.equal(bundle.selection.contextId, heirsBranch);await assert.rejects(add(fixture.ancient, branch), /active/);await assert.rejects(bridge.changeCampaignAssociation("world-god", worldId, { action: "select", campaignId: fixture.heirs, revision: 1, contextId: heirsBranch, viewingYear: null }), /Restore/);await timelines.changeTimeline("world-god", worldId, { action: "restore", id: branch, revision: 2 });
  await worlds.changeWorld("world-god", worldId, { action: "archive", revision: 1 });assert.equal((await bridge.worldCampaignAssociations("world-god", worldId)).contexts.find(row => row.id === heirsBranch)!.available, false);await worlds.changeWorld("world-god", worldId, { action: "restore", revision: 2 });
  await pool.query("update campaign set archived_at=now(),archived_by_user_id='world-god',archive_reason='Fixture' where id=$1", [fixture.heirs]);assert.equal((await bridge.worldCampaignAssociations("world-god", worldId)).contexts.find(row => row.id === heirsBranch)!.campaignArchived, true);await pool.query("update campaign set archived_at=null,archived_by_user_id=null,archive_reason='' where id=$1", [fixture.heirs]);
  assert.deepEqual((await worlds.getWorld("world-god", worldId)).entries, historyBefore.entries);assert.deepEqual((await worlds.getWorld("world-god", worldId)).eras, historyBefore.eras);
  await bridge.changeCampaignAssociation("world-god", worldId, { action: "select", campaignId: fixture.heirs, revision: 1, contextId: null, viewingYear: null });await assert.rejects(bridge.changeCampaignAssociation("world-god", worldId, { action: "select", campaignId: fixture.heirs, revision: 1, contextId: null, viewingYear: null }), /newer version/);
  await assert.rejects(pool.query("insert into world_campaign_context(id,campaign_id,world_id,timeline_id,creator_id) values($1,$2,$3,$4,'world-god')", [randomUUID(), fixture.foreign, worldId, primary]), /same-owner/);
  await assert.rejects(pool.query("update world_campaign_context set timeline_id=$1,revision=revision+1 where id=$2", [child, heirsBranch]), /immutable/);
  await assert.rejects(pool.query("update world_campaign_context set starting_year=42 where id=$1", [heirsBranch]), /revision/);await assert.rejects(pool.query("delete from world_campaign_context where id=$1", [heirsBranch]), /retained/);
  await assert.rejects(pool.query("update world_campaign_context_change set action='link' where context_id=$1", [heirsBranch]), /immutable/);
  await assert.rejects(pool.query("update world_campaign_home set context_id=$1,revision=revision+1 where campaign_id=$2", [bundle.contexts.find(row => row.campaignId === fixture.imperial)!.id, fixture.heirs]), /this Campaign|foreign key/);
  await assert.rejects(pool.query("insert into world_authoring_selection(user_id,context_id,revision) values('other-god',$1,1)", [heirsBranch]), /this creator/);
  await assert.rejects(pool.query("delete from campaign where id=$1", [fixture.heirs]), /foreign key/);
  const lifecycle=await import("../src/features/lifecycle/lifecycle-service");const preview=await lifecycle.previewLifecycleEntityForActor({entityKind:"campaign",entityId:fixture.heirs},{userId:"world-god",roles:["god"]});assert.equal(preview.canArchive,true);assert.equal(preview.canDelete,false);assert.ok(preview.dependencies.some(row=>row.blocking&&row.count>0&&row.label.includes("World and timeline associations")));
  await pool.query("update campaign set created_by_user_id='other-god',name='Private transferred Campaign name' where id=$1",[fixture.heirs]);
  const transferred=await bridge.worldCampaignAssociations("world-god",worldId);assert.equal(transferred.contexts.find(row=>row.id===heirsBranch)!.campaignName,"Campaign unavailable");assert.equal((await bridge.campaignWorldAssociations("other-god",fixture.heirs)).contexts.length,0,"A new Campaign owner cannot discover the previous owner's World context");
  await assert.rejects(bridge.changeCampaignAssociation("world-god",worldId,{action:"restore",campaignId:fixture.heirs,id:heirsBranch,revision:4}),/unavailable/);
  await pool.query("update campaign set created_by_user_id='world-god',name='Bridge B Lost Heirs' where id=$1",[fixture.heirs]);
  const perfWorld = await worlds.createWorld("world-god", { name: "Bridge B Relationship Scale" });const perfPrimary = (await worlds.getWorld("world-god", perfWorld)).selectedTimeline.id;
  const perfA = await timelines.changeTimeline("world-god", perfWorld, { action: "create", parentRevision: 1, draft: { parentId: perfPrimary, divergenceYear: 650, name: "Scale alternative" } });const perfB = await timelines.changeTimeline("world-god", perfWorld, { action: "create", parentRevision: 1, draft: { parentId: perfA, divergenceYear: 900, name: "Scale nested" } });
  const start = performance.now();for (const id of fixture.scale) for (const timeline of [perfPrimary, perfA, perfB]) await add(id, timeline, null, perfWorld);const createdMs = performance.now() - start;
  const readStart = performance.now();const projection = await bridge.worldCampaignAssociations("world-god", perfWorld);const readMs = performance.now() - readStart;assert.equal(projection.contexts.length, 300);assert.ok(projection.contexts.every(row => !Object.hasOwn(row, "characters") && !Object.hasOwn(row, "players")));
  console.log(`PASS: association creation is atomic; many Campaigns/Worlds/timelines, nested/same-year branches, independent home/authoring dates, explicit home removal/replacement, stale/no-op rejection, archive/restore, strict ownership/membership and SQL/audit protections. 100 Campaigns/300 contexts: creation ${Math.round(createdMs)}ms; bounded joined projection ${Math.round(readMs)}ms, ${Buffer.byteLength(JSON.stringify(projection))} bytes.`);
  return { worldId, primary, branch, child, twin, heirsBranch, single, perfWorld, ...fixture };
}

async function hydrated(page: Page) { await page.waitForFunction(() => [...document.querySelectorAll("button")].some(button => Object.keys(button).some(key => key.startsWith("__reactProps$")))); }
async function valueSaved(locator: Locator, value: string) { const deadline=Date.now()+30000;while(Date.now()<deadline){try{if(await locator.inputValue()===value)return;}catch{}await new Promise(resolve=>setTimeout(resolve,75));}assert.equal(await locator.inputValue(),value); }
async function signIn(context: BrowserContext, url: string, user: string) { const response = await context.request.post(`${url}/api/auth/sign-in/email`, { headers: { Origin: url }, data: { email: `${user}@example.invalid`, password: "Worlds-Test-Only-Password!" } });assert.equal(response.status(), 200, await response.text()); }
export async function associationBrowserChecks(browser: Browser, base: string, fixture: Awaited<ReturnType<typeof associationServiceChecks>>, worlds: Worlds, bridge: Bridge, timelines: Timelines, pool: pg.Pool) {
  const errors: string[] = [];
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, extraHTTPHeaders: { "X-Forwarded-For": "203.0.113.181" } });await signIn(context, base, "world-god");
  const page = await context.newPage();page.on("pageerror", error => errors.push(error.message));page.on("dialog", dialog => dialog.accept());
  const worldUrl = `${base}/worlds/${fixture.worldId}?tab=campaigns&timeline=${fixture.primary}`;
  const pane = () => page.getByRole("region", { name: "Campaign Associations", exact: true });
  async function open() { await page.goto(worldUrl);await hydrated(page);await pane().getByRole("button", { name: "Associate Campaign", exact: true }).waitFor(); }
  async function create(name: string, campaigns: string[], fail = false) {
    await page.goto(`${base}/worlds`);await hydrated(page);await page.getByRole("button", { name: "Create world", exact: true }).click();const dialog = page.getByRole("dialog", { name: "Create a world" });await dialog.getByLabel("World name", { exact: true }).fill(name);
    for (const campaign of campaigns) await dialog.getByLabel(campaign, { exact: true }).check();
    if (fail) { await page.route("**/api/worlds", route => route.request().method() === "POST" ? route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Fixture save failed; draft retained." }) }) : route.continue());await dialog.getByRole("button", { name: "Create world", exact: true }).click();await dialog.getByRole("alert").waitFor();assert.equal(await dialog.getByLabel("World name", { exact: true }).inputValue(), name);for (const campaign of campaigns) assert.equal(await dialog.getByLabel(campaign, { exact: true }).isChecked(), true);await page.unroute("**/api/worlds"); }
    await dialog.getByRole("button", { name: "Create world", exact: true }).click();await dialog.waitFor({ state: "hidden" });const world = (await worlds.listWorlds("world-god")).find(row => row.name === name)!;assert.ok(world);
    const associations = await bridge.worldCampaignAssociations("world-god", world.id);assert.equal(associations.contexts.length, campaigns.length);const primary=(await worlds.getWorld("world-god",world.id)).selectedTimeline.id;assert.ok(associations.contexts.every(row => row.startingYear === null && row.timelineId === primary));return world.id;
  }
  await create("Bridge B Browser Independent", []);await create("Bridge B Browser One", ["Bridge B Lost Heirs"]);await create("Bridge B Browser Several", ["Bridge B Lost Heirs", "Bridge B Imperial Dawn", "Bridge B Ancient War"], true);
  await open();assert.equal(await pane().getByText(/No Campaign selected for Worlds authoring/).count(), 1);
  await page.getByLabel("Selected timeline", { exact: true }).selectOption(fixture.branch);await pane().getByRole("button", { name: "Associate Campaign", exact: true }).waitFor();
  await pane().getByRole("button", { name: "Associate Campaign", exact: true }).click();let dialog = page.getByRole("dialog", { name: "Associate Campaign", exact: true });await dialog.getByLabel("Existing Campaign", { exact: true }).selectOption(String(fixture.ancient));await dialog.getByLabel("Historical starting year", { exact: true }).fill("300");await dialog.getByRole("button", { name: "Save association", exact: true }).click();await dialog.waitFor({ state: "hidden" });
  let bundle = await bridge.worldCampaignAssociations("world-god", fixture.worldId);const ancient = bundle.contexts.find(row => row.campaignId === fixture.ancient && row.timelineId === fixture.branch)!;assert.equal(ancient.startingYear, 300);
  const ancientCard = page.locator(`[data-context-id="${ancient.id}"]`);await ancientCard.getByRole("button", { name: "Set as home", exact: true }).click();await page.waitForFunction(id => document.querySelector(`[data-context-id="${id}"]`)?.textContent?.includes("Home context"), ancient.id);
  await pane().getByLabel("Campaign and timeline for authoring", { exact: true }).selectOption(ancient.id);await pane().getByLabel("Authoring viewing year", { exact: true }).fill("900");
  await page.route("**/campaigns", route => route.request().method() === "POST" ? route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: "Fixture authoring failure" }) }) : route.continue());await pane().getByRole("button", { name: "Save authoring context", exact: true }).click();await pane().getByRole("alert").waitFor();assert.equal(await pane().getByLabel("Authoring viewing year", { exact: true }).inputValue(), "900");await page.unroute("**/campaigns");
  const retainedUrl=page.url();page.removeAllListeners("dialog");page.once("dialog",dialog=>dialog.dismiss());await page.getByLabel("Selected timeline",{exact:true}).selectOption(fixture.child);assert.equal(page.url(),retainedUrl);assert.equal(await pane().getByLabel("Authoring viewing year",{exact:true}).inputValue(),"900");page.on("dialog",dialog=>dialog.accept());
  const selectionSaved=page.waitForResponse(response=>new URL(response.url()).pathname===`/api/worlds/${fixture.worldId}/campaigns`&&response.request().method()==="POST");await pane().getByRole("button", { name: "Save authoring context", exact: true }).click();const selectionResponse=await selectionSaved;assert.equal(selectionResponse.status(),200,await selectionResponse.text());await pane().locator("p").filter({hasText:/Bridge B Ancient War.*Bridge B Empire Survives.*900/}).waitFor();
  bundle = await bridge.worldCampaignAssociations("world-god", fixture.worldId);assert.equal(bundle.selection.contextId, ancient.id);assert.equal(bundle.selection.viewingYear, 900);assert.equal(bundle.contexts.find(row => row.id === ancient.id)!.startingYear, 300);
  await page.reload();await hydrated(page);await valueSaved(pane().getByLabel("Authoring viewing year", { exact: true }), "900");assert.equal(await page.getByLabel("Selected timeline", { exact: true }).inputValue(), fixture.branch);
  await page.getByLabel("Selected timeline",{exact:true}).selectOption(fixture.primary);await page.getByRole("complementary",{name:"Worlds authoring context"}).getByText(/Authoring for.*Bridge B Ancient War.*Bridge B Empire Survives/).waitFor();assert.equal((await bridge.worldCampaignAssociations("world-god",fixture.worldId)).selection.contextId,ancient.id);await page.goBack();await page.waitForURL(url=>url.searchParams.get("timeline")===fixture.branch);await page.goForward();await page.waitForURL(url=>url.searchParams.get("timeline")===fixture.primary);await page.goBack();await page.waitForURL(url=>url.searchParams.get("timeline")===fixture.branch);await pane().getByRole("button",{name:"Associate Campaign",exact:true}).waitFor();
  // Two actual editor tabs preserve stale unchanged drafts until explicit reload.
  const second = await context.newPage();second.on("pageerror", error => errors.push(error.message));second.on("dialog", dialog => dialog.accept());await second.goto(page.url());await hydrated(second);await second.locator(`[data-context-id="${ancient.id}"]`).getByRole("button", { name: "Edit starting year", exact: true }).click();const secondDialog = second.getByRole("dialog", { name: "Edit association" });await secondDialog.getByLabel("Historical starting year", { exact: true }).waitFor();
  await ancientCard.getByRole("button", { name: "Edit starting year", exact: true }).click();dialog = page.getByRole("dialog", { name: "Edit association" });await dialog.getByLabel("Historical starting year", { exact: true }).fill("301");await dialog.getByRole("button", { name: "Save association", exact: true }).click();await dialog.waitFor({ state: "hidden" });
  await secondDialog.getByRole("button", { name: "Save association", exact: true }).click();await secondDialog.getByRole("alert").waitFor();assert.match(await secondDialog.getByRole("alert").innerText(), /newer version/);assert.equal(await secondDialog.getByLabel("Historical starting year", { exact: true }).inputValue(), "300");await secondDialog.getByRole("button", { name: "Load latest associations", exact: true }).click();await valueSaved(second.getByRole("dialog", { name: "Edit association" }).getByLabel("Historical starting year", { exact: true }), "301");await second.getByRole("button", { name: "Close association editor", exact: true }).click();await second.close();
  await ancientCard.getByRole("button", { name: "Remove association", exact: true }).click();await pane().getByLabel("Show removed associations", { exact: true }).check();await ancientCard.getByRole("button", { name: "Restore association", exact: true }).waitFor();bundle = await bridge.worldCampaignAssociations("world-god", fixture.worldId);assert.equal(bundle.homes.find(row => row.campaignId === fixture.ancient)!.contextId, null);assert.equal(bundle.selection.contextId, ancient.id);assert.equal(bundle.contexts.find(row => row.id === ancient.id)!.available, false);
  await ancientCard.getByRole("button", { name: "Restore association", exact: true }).click();await ancientCard.getByRole("button", { name: "Edit starting year", exact: true }).waitFor();assert.equal((await bridge.worldCampaignAssociations("world-god", fixture.worldId)).selection.viewingYear, 900);
  const currentTimeline = (await worlds.getWorld("world-god", fixture.worldId, false, fixture.branch)).selectedTimeline;await timelines.changeTimeline("world-god", fixture.worldId, { action: "archive", id: fixture.branch, revision: currentTimeline.revision });await page.reload();await hydrated(page);await ancientCard.getByText(/Timeline archived/).first().waitFor();assert.equal(await ancientCard.getByRole("button", { name: "Edit starting year", exact: true }).count(), 0);await timelines.changeTimeline("world-god", fixture.worldId, { action: "restore", id: fixture.branch, revision: currentTimeline.revision + 1 });await page.reload();await hydrated(page);await ancientCard.getByRole("button", { name: "Edit starting year", exact: true }).waitFor();
  // Campaign settings exposes the same IDs through direct management links.
  await page.goto(`${base}/heavens/campaigns?campaign=${fixture.ancient}`);await hydrated(page);const settings = page.getByRole("region", { name: "World contexts" });await settings.getByRole("link", { name: /Bridge B Association Foundation.*Bridge B Empire Survives/ }).waitFor();assert.match(await settings.innerText(), /Selected for your Worlds authoring/);assert.equal(await page.getByLabel("Attribute Points", { exact: true }).inputValue(), "100");await settings.getByRole("link", { name: /Bridge B Association Foundation.*Bridge B Empire Survives/ }).click();await pane().getByRole("button", { name: "Associate Campaign", exact: true }).waitFor();assert.equal(new URL(page.url()).searchParams.get("timeline"), fixture.branch);
  const phone = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, extraHTTPHeaders: { "X-Forwarded-For": "203.0.113.182" } });await signIn(phone, base, "world-god");const mobile = await phone.newPage();mobile.on("pageerror", error => errors.push(error.message));mobile.on("dialog", dialog => dialog.accept());await mobile.goto(`${base}/worlds/${fixture.worldId}?tab=campaigns&timeline=${fixture.child}`);await hydrated(mobile);await mobile.getByRole("button", { name: "Associate Campaign", exact: true }).tap();const mobileDialog = mobile.getByRole("dialog", { name: "Associate Campaign", exact: true });await mobileDialog.getByLabel("Existing Campaign", { exact: true }).selectOption(String(fixture.imperial));await mobileDialog.getByLabel("Historical starting year", { exact: true }).fill("-10");await mobileDialog.getByRole("button", { name: "Save association", exact: true }).tap();await mobileDialog.waitFor({ state: "hidden" });const mobileContext = (await bridge.worldCampaignAssociations("world-god", fixture.worldId)).contexts.find(row => row.campaignId === fixture.imperial && row.timelineId === fixture.child)!;assert.equal(mobileContext.startingYear, -10);await mobile.reload();await hydrated(mobile);await mobile.locator(`[data-context-id="${mobileContext.id}"]`).getByRole("button", { name: "Edit starting year", exact: true }).tap();await mobile.getByRole("dialog", { name: "Edit association" }).getByLabel("Historical starting year", { exact: true }).fill("0");await mobile.getByRole("dialog", { name: "Edit association" }).getByRole("button", { name: "Save association", exact: true }).tap();await mobile.getByRole("dialog", { name: "Edit association" }).waitFor({ state: "hidden" });assert.equal((await bridge.worldCampaignAssociations("world-god", fixture.worldId)).contexts.find(row => row.id === mobileContext.id)!.startingYear, 0);assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  const mobileCard=mobile.locator(`[data-context-id="${mobileContext.id}"]`);await mobileCard.getByRole("button",{name:"Set as home",exact:true}).tap();await mobileCard.getByText(/Home context/).waitFor();await mobileCard.getByRole("button",{name:"Remove association",exact:true}).tap();await mobile.getByLabel("Show removed associations",{exact:true}).check();await mobileCard.getByRole("button",{name:"Restore association",exact:true}).tap();await mobileCard.getByRole("button",{name:"Edit starting year",exact:true}).waitFor();
  await mobile.goto(`${base}/worlds`);await hydrated(mobile);await mobile.getByRole("button",{name:"Create world",exact:true}).tap();const phoneCreation=mobile.getByRole("dialog",{name:"Create a world"});await phoneCreation.getByLabel("World name",{exact:true}).fill("Bridge B Phone World");await phoneCreation.getByLabel("Bridge B Lost Heirs",{exact:true}).tap();await phoneCreation.getByRole("button",{name:"Create world",exact:true}).tap();await phoneCreation.waitFor({state:"hidden"});const phoneWorld=(await worlds.listWorlds("world-god")).find(row=>row.name==="Bridge B Phone World")!;assert.equal((await bridge.worldCampaignAssociations("world-god",phoneWorld.id)).contexts.length,1);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await phone.close();
  for (const [index, user] of ["other-god", "world-admin", "world-player", "anonymous"].entries()) {
    const role = await browser.newContext({ extraHTTPHeaders: { "X-Forwarded-For": `203.0.113.${183 + index}` } });if (user !== "anonymous") await signIn(role, base, user);
    const response = await role.request.get(`${base}/api/worlds/${fixture.worldId}/campaigns`);assert.ok([401, 403, 404].includes(response.status()));assert.equal((await response.text()).includes("Bridge B Lost Heirs"), false);
    const campaignResponse = await role.request.get(`${base}/api/worlds/campaign-contexts?campaignId=${fixture.heirs}`);assert.ok([401, 403, 404].includes(campaignResponse.status()));
    const forged = await role.request.post(`${base}/api/worlds/${fixture.worldId}/campaigns`, { headers: { Origin: base }, data: { action: "home", campaignId: fixture.heirs, revision: 3, contextId: fixture.heirsBranch } });assert.ok([401, 403, 404].includes(forged.status()));
    if (user === "world-admin") { const review = await role.newPage();review.on("pageerror", error => errors.push(error.message));await review.goto(`${base}/worlds/${fixture.worldId}?tab=campaigns&review=1`);await hydrated(review);await review.getByRole("heading", { name: "Campaign Associations", exact: true }).waitFor();assert.equal(await review.getByRole("button", { name: "Associate Campaign", exact: true }).count(), 0);assert.equal(await review.getByRole("button", { name: "Set as home", exact: true }).count(), 0);await review.goto(`${base}/heavens/campaigns?campaign=${fixture.heirs}`);await hydrated(review);await review.getByRole("region", { name: "World contexts" }).getByText(/Only this Campaign’s creator/).waitFor();assert.equal(await review.getByRole("link", { name: /Bridge B Association Foundation/ }).count(), 0); }
    await role.close();
  }
  const denied = await context.request.post(`${base}/api/worlds/${fixture.worldId}/campaigns`, { headers: { Origin: "https://foreign.example" }, data: { action: "home", campaignId: fixture.heirs, revision: 3, contextId: null } });assert.equal(denied.status(), 403);
  const response = await context.request.get(`${base}/api/worlds/${fixture.worldId}/campaigns`);assert.match(response.headers()["cache-control"], /no-store/);const data = await response.json() as AssociationBundle;assert.equal(data.contexts.find(row => row.id === mobileContext.id)!.startingYear, 0);
  await page.goto(`${base}/worlds/${fixture.perfWorld}?tab=campaigns`);await hydrated(page);const start = performance.now();await pane().getByRole("button", { name: "Associate Campaign", exact: true }).waitFor();const loaded = performance.now() - start;const searchStart = performance.now();await pane().getByLabel("Find associated Campaigns", { exact: true }).fill("Scale 100");await pane().getByRole("heading", { name: "Bridge B Scale 100", exact: true }).first().waitFor();assert.equal(await pane().locator("[data-context-id]").count(), 3);console.log(`PASS: real desktop and native-touch 390px atomic creation, multiple associations, home/authoring distinctions, dates before divergence, failed drafts, real two-tab unchanged conflicts, removal/restoration, archived timeline retention, Campaign-settings deep links, all roles, membership privacy and CSRF. 300-context browser metadata load ${Math.round(loaded)}ms; search ${Math.round(performance.now() - searchStart)}ms.`);
  assert.deepEqual(errors, []);await context.close();
  // The harness compares every existing Campaign/runtime table before and after.
  assert.equal((await pool.query("select count(*)::int n from world_campaign_context_change")).rows[0].n > 0, true);
}
