import assert from "node:assert/strict";
import {createHash,randomUUID} from "node:crypto";
import {mkdir,writeFile} from "node:fs/promises";
import type pg from "pg";
import type {Browser,BrowserContext,Locator,Page} from "playwright-core";
import {emptyLore,type LoreDraft,type LoreFamily,type LoreRecord} from "../src/features/worlds/peoples";
import type {HistoricalTime} from "../src/features/worlds/history";
type Worlds=typeof import("../src/features/worlds/world-service");
type Timelines=typeof import("../src/features/worlds/branching-history-service");
const families=["culture","civilization","language","population","belief","tradition"] as const;
const known=(year:number):HistoricalTime=>({version:1,scale:"world-year",kind:"known",year});
const undated:HistoricalTime={version:1,scale:"world-year",kind:"undated"};
const participant=(targetId:string,role:string)=>({targetId,role,authoredReference:"",account:""});
const geography=(geographyId:string,type="inhabited by",time:HistoricalTime=undated,destinationId:string|null=null)=>({id:randomUUID(),geographyId,destinationId,relationshipType:type,account:"An explicitly authored geographic account.",time,protected:false});
const event=(type:string,title:string,time:HistoricalTime)=>({eventType:type,draft:{title,account:`An attributed ${type} account.`,notes:"",time,accuracy:"disputed" as const,narrative:"recorded" as const,eraIds:[]}});

export async function seedSocietiesUpgrade(pool:pg.Pool,worldId:string){
  const timelineId=(await pool.query("select id from world_timeline where world_id=$1 and is_primary",[worldId])).rows[0].id;
  const owner=(await pool.query("select owner_id from world where id=$1",[worldId])).rows[0].owner_id;
  const ids=[randomUUID(),randomUUID(),randomUUID(),randomUUID()],requestId=randomUUID();
  const {geographies:_,...legacyDraft}=emptyLore("species");void _;legacyDraft.name="Retained pre-0115 species";legacyDraft.description="Retained historical content";legacyDraft.accuracy="disputed";legacyDraft.privateNotes="Retained protected notes";
  const retry={action:"create",timelineId,requestId,draft:legacyDraft};
  const requestHash=createHash("sha256").update(JSON.stringify({timelineId,draft:legacyDraft})).digest("hex");
  const client=await pool.connect();try{await client.query("begin");
    for(const [i,family] of ["species","people","origin","relationship"].entries())await client.query("insert into world_lore_identity(id,world_id,family,origin_timeline_id,creator_id,request_id,request_hash) values($1,$2,$3,$4,$5,$6,$7)",[ids[i],worldId,family,timelineId,owner,i===0?requestId:randomUUID(),i===0?requestHash:"retained source"]);
    for(const [i,family] of ["species","people","origin","relationship"].entries()){
      const v=randomUUID();await client.query("insert into world_lore_version(id,world_id,entity_id,family,timeline_id,author_id,historical_time,accuracy,narrative,visibility,private_notes) values($1,$2,$3,$4,$5,$6,$7,'disputed','recorded',$8,'Retained protected notes')",[v,worldId,ids[i],family,timelineId,owner,undated,i===2?"protected":"ordinary"]);
      const table=family==="species"?"world_species_version":family==="people"?"world_people_version":family==="origin"?"world_origin_version":"world_relationship_version";
      if(family==="relationship")await client.query(`insert into ${table}(version_id,world_id,name,description,relationship_type) values($1,$2,$3,'Retained competing ancestry','Custom ancestors')`,[v,worldId,"Retained relationship"]);
      else await client.query(`insert into ${table}(version_id,world_id,name,description) values($1,$2,$3,'Retained historical content')`,[v,worldId,i===0?legacyDraft.name:`Retained ${family}`]);
      if(i>1)await client.query("insert into world_lore_participant(version_id,world_id,position,target_id,role) values($1,$2,0,$3,'subject')",[v,worldId,ids[0]]);
      if(i===3)await client.query("insert into world_lore_participant(version_id,world_id,position,target_id,role) values($1,$2,1,$3,'ancestor')",[v,worldId,ids[1]]);
      await client.query("insert into world_lore_head(world_id,timeline_id,entity_id,version_id,revision,mode) values($1,$2,$3,$4,1,'authored')",[worldId,timelineId,ids[i],v]);
      await client.query("insert into world_lore_change(world_id,timeline_id,entity_id,version_id,revision,actor_id,action) values($1,$2,$3,$4,1,$5,'create')",[worldId,timelineId,ids[i],v,owner]);
    }await client.query("commit");
  }catch(error){await client.query("rollback");throw error;}finally{client.release();}
  const tables=(await pool.query("select tablename from pg_tables where schemaname='public' and tablename like 'world%' order by tablename")).rows;
  const before=new Map<string,unknown>();for(const {tablename}of tables){assert.match(tablename,/^[a-z_]+$/);before.set(tablename,(await pool.query(`select to_jsonb(t) row from ${tablename} t order by to_jsonb(t)::text`)).rows);}
  return {worldId,timelineId,owner,id:ids[0],retry,verify:async()=>{
    for(const [table,expected]of before)assert.deepEqual((await pool.query(`select to_jsonb(t) row from ${table} t order by to_jsonb(t)::text`)).rows,expected,`0115 preserves ${table}`);
    for(const f of families)assert.equal((await pool.query(`select count(*)::int n from world_${f}_version`)).rows[0].n,0);
    assert.equal((await pool.query("select count(*)::int n from world_lore_geography")).rows[0].n,0);
    console.log("PASS: populated 0114→0115/reapplication preserve prior typed identities, immutable sources, participants, protected knowledge, all historical/calendar/Atlas records and Campaign contexts; new domain/geo tables start empty.");
  }};
}

async function signIn(context:BrowserContext,baseUrl:string,user="world-god"){
  const response=await context.request.post(`${baseUrl}/api/auth/sign-in/email`,{headers:{Origin:baseUrl},data:{email:`${user}@example.invalid`,password:"Worlds-Test-Only-Password!"}});assert.equal(response.status(),200,await response.text());
}
async function visible(locator:Locator){await locator.waitFor({state:"visible"});}
async function ready(page:Page){await page.waitForFunction(()=>[...document.querySelectorAll("button")].some(b=>Object.keys(b).some(k=>k.startsWith("__reactProps$"))));}
async function noOverflow(page:Page){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
export async function societiesBrowserChecks(browser:Browser,baseUrl:string,fixture:Awaited<ReturnType<typeof societiesServiceChecks>>,pool:pg.Pool,artifactDirectory="artifacts/guidance/worlds-4a-2"){
  const service=await import("../src/features/worlds/peoples-service"),errors:string[]=[];
  const route=`${baseUrl}/worlds/${fixture.worldId}?tab=peoples&timeline=${fixture.primary}`;
  const context=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:{"X-Forwarded-For":"198.51.100.141"}});await signIn(context,baseUrl);
  const page=await context.newPage();page.on("pageerror",e=>errors.push(e.message));page.on("dialog",d=>d.accept());
  const labels={culture:"Cultures",civilization:"Civilizations",language:"Languages",population:"Populations and communities",belief:"Beliefs",tradition:"Traditions and practices"};
  const field={culture:"Values and ideals",civilization:"Social and cultural institutions",language:"Communication method",population:"Population estimates and uncertainty",belief:"Beliefs and claims",tradition:"Practice and observance"};
  const created=new Map<string,string>();
  try{
    for(const family of families){
      await page.goto(route);await ready(page);await page.getByText("Cultures, civilizations and communities",{exact:true}).click();await page.getByRole("button",{name:`Create ${labels[family].toLowerCase()}`,exact:true}).click();const dialog=page.getByRole("dialog");await visible(dialog);await dialog.getByLabel("Name",{exact:true}).fill(`Browser ${family}`);
      await dialog.getByRole("button",{name:"Close editor",exact:true}).click();await visible(dialog.getByRole("button",{name:"Keep editing",exact:true}));await dialog.getByRole("button",{name:"Keep editing",exact:true}).click();assert.equal(await dialog.getByLabel("Name",{exact:true}).inputValue(),`Browser ${family}`);
      await dialog.getByText("Characteristics and authored detail",{exact:true}).click();await dialog.getByLabel(field[family],{exact:true}).fill(family==="language"?"Stories encoded in moving light":family==="population"?"No numeric count is known":"Original authored optional detail");
      await dialog.getByText("Subjects, ancestry and related records",{exact:true}).click();await dialog.getByRole("button",{name:"Add participant",exact:true}).click();await dialog.getByLabel("Participant 1 reference",{exact:true}).selectOption(fixture.sharedCulture);await dialog.getByLabel("Participant 1 role",{exact:true}).fill(family==="belief"?"believed by":"associated culture");
      if(family==="civilization"){
        await dialog.getByText("Places and migration",{exact:true}).click();await dialog.getByRole("button",{name:"Add place association",exact:true}).click();await dialog.getByLabel("Place association 1 place",{exact:true}).selectOption(fixture.places.region);await dialog.getByLabel("Place association 1 relationship",{exact:true}).fill("geographic presence");
        await dialog.getByText("Historical milestones",{exact:true}).click();await dialog.getByRole("button",{name:"Author founding milestone",exact:true}).click();await dialog.getByLabel("Milestone 1 account",{exact:true}).fill("The civilization's founding was entered once in this editor.");await dialog.getByLabel("Milestone 1 date precision",{exact:true}).selectOption("known");await dialog.getByLabel("Milestone 1 year",{exact:true}).fill("600");
        const endpoint=`**/api/worlds/${fixture.worldId}/peoples`;await page.route(endpoint,r=>r.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Temporary society save failure."})}));await dialog.getByRole("button",{name:"Save record",exact:true}).click();await visible(dialog.getByRole("alert"));assert.equal(await dialog.getByLabel("Milestone 1 year",{exact:true}).inputValue(),"600");await page.unroute(endpoint);
      }
      await dialog.getByRole("button",{name:"Save record",exact:true}).click();await dialog.waitFor({state:"hidden"});await visible(page.getByRole("heading",{name:`Browser ${family}`,exact:true}));const id=new URL(page.url()).searchParams.get("entity")!;created.set(family,id);const saved=await service.getPeople("world-god",fixture.worldId,fixture.primary,id);assert.equal(saved.participants[0].targetId,fixture.sharedCulture);
      await page.reload();await visible(page.getByRole("heading",{name:`Browser ${family}`,exact:true}));await page.getByRole("button",{name:"Edit record",exact:true}).click();const edit=page.getByRole("dialog");await edit.getByText("Characteristics and authored detail",{exact:true}).click();await edit.getByLabel(field[family],{exact:true}).fill(`Edited ${family} survives reload`);await edit.getByRole("button",{name:"Save record",exact:true}).click();await edit.waitFor({state:"hidden"});assert.equal((await service.getPeople("world-god",fixture.worldId,fixture.primary,id)).draft.fields[family==="culture"?"values":family==="civilization"?"institutions":family==="language"?"method":family==="population"?"estimates":family==="belief"?"claims":"practice"],`Edited ${family} survives reload`);
    }
    const civ=created.get("civilization")!;await page.goto(`${route}&entity=${civ}`);await visible(page.getByRole("heading",{name:"Browser civilization",exact:true}));const founding=(await service.getPeople("world-god",fixture.worldId,fixture.primary,civ)).milestoneRecords[0].id;
    await page.getByRole("button",{name:"Edit record",exact:true}).click();let dialog=page.getByRole("dialog");await dialog.getByLabel("Milestone 1 year",{exact:true}).fill("605");await dialog.getByRole("button",{name:"Save record",exact:true}).click();await dialog.waitFor({state:"hidden"});const corrected=await service.getPeople("world-god",fixture.worldId,fixture.primary,civ);assert.equal(corrected.milestoneRecords[0].id,founding);assert.deepEqual(corrected.milestoneRecords[0].time,known(605));assert.equal((await pool.query("select count(*)::int n from world_historical_entry where id=$1",[founding])).rows[0].n,1);
    await page.getByRole("link",{name:"Browser civilization: founding",exact:true}).click();await visible(page.getByRole("dialog"));assert.ok((await page.getByRole("dialog").textContent())!.includes("founding was entered once"));await page.getByRole("link",{name:"Browser civilization",exact:true}).click();await visible(page.getByRole("heading",{name:"Browser civilization",exact:true}));
    await page.getByRole("link",{name:"Northern region",exact:true}).click();await visible(page.getByRole("heading",{name:"Atlas",exact:true}));assert.equal(new URL(page.url()).searchParams.get("place"),fixture.places.region);await page.goBack();await visible(page.getByRole("heading",{name:"Browser civilization",exact:true}));
    const second=await context.newPage();second.on("dialog",d=>d.accept());await second.goto(page.url());await visible(second.getByRole("button",{name:"Edit record",exact:true}));await second.getByRole("button",{name:"Edit record",exact:true}).click();await second.getByRole("dialog").getByLabel("Description",{exact:true}).fill("Unsaved competing civilization draft");await page.getByRole("button",{name:"Edit record",exact:true}).click();dialog=page.getByRole("dialog");await dialog.getByLabel("Description",{exact:true}).fill("Accepted civilization edit");await dialog.getByRole("button",{name:"Save record",exact:true}).click();await dialog.waitFor({state:"hidden"});await second.getByRole("dialog").getByRole("button",{name:"Save record",exact:true}).click();await visible(second.getByRole("dialog").getByRole("alert"));assert.equal(await second.getByRole("dialog").getByLabel("Description",{exact:true}).inputValue(),"Unsaved competing civilization draft");await second.getByRole("button",{name:"Load latest record",exact:true}).click();await second.waitForFunction(()=>document.querySelector<HTMLTextAreaElement>('dialog textarea')?.value==="Accepted civilization edit");await second.close();
    await page.getByRole("button",{name:"Close record",exact:true}).click();await page.getByLabel("Record family",{exact:true}).selectOption("language");const reply=page.waitForResponse(r=>r.url().includes("/peoples?")&&r.url().includes("q=Browser+language")&&r.request().method()==="GET");await page.getByLabel("Search peoples and origins",{exact:true}).fill("Browser language");await reply;await page.waitForFunction(()=>document.querySelectorAll('[aria-label="Peoples and origins"] button[class*="card"]').length===1);await visible(page.getByRole("button",{name:/Browser language Languages/}));
    await page.goto(`${route}&entity=${fixture.population}`);await visible(page.getByRole("heading",{name:"Harbor Ashborne community",exact:true}));await page.getByRole("button",{name:"Ordinary knowledge preview",exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[aria-label="Peoples and origins"]')?.textContent?.includes("Protected migration account"));const preview=await context.request.get(`${baseUrl}/api/worlds/${fixture.worldId}/peoples?timeline=${fixture.primary}&record=${fixture.population}&ordinary=1`);assert.equal(preview.status(),200);const body=await preview.text();assert.equal(body.includes("Secret ash hall"),false);assert.equal(body.includes("Protected migration account"),false);
    await page.goto(`${route}&entity=${fixture.population}`);await visible(page.getByRole("heading",{name:"Harbor Ashborne community",exact:true}));await page.getByLabel("Selected timeline",{exact:true}).selectOption(fixture.branch);await visible(page.getByRole("heading",{name:"Harbor Ashborne community",exact:true}));await visible(page.getByText("Alternate migration destination",{exact:true}));
    await page.goto(`${route}&entity=${fixture.civilization}`);await visible(page.getByRole("heading",{name:"Gathered hearths",exact:true}));await page.getByRole("button",{name:"Close record",exact:true}).click();const placeReply=page.waitForResponse(r=>r.url().includes("place=")&&r.url().includes("/peoples?")&&r.request().method()==="GET");await page.getByLabel("Records linked to place",{exact:true}).selectOption(fixture.places.mountains);await placeReply;await visible(page.getByRole("button",{name:/Harbor Ashborne community Populations/}));assert.equal(new URL(page.url()).searchParams.get("atPlace"),fixture.places.mountains);await page.reload();await visible(page.getByRole("button",{name:/Mountain community Populations/}));await noOverflow(page);
    await mkdir(artifactDirectory,{recursive:true});await page.getByRole("heading",{name:"Peoples and origins",exact:true}).evaluate(el=>window.scrollTo(0,el.getBoundingClientRect().top+window.scrollY-120));await page.screenshot({path:`${artifactDirectory}/societies-desktop.png`,fullPage:false});
    const phone=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,extraHTTPHeaders:{"X-Forwarded-For":"198.51.100.142"}});await signIn(phone,baseUrl);const mobile=await phone.newPage();mobile.on("pageerror",e=>errors.push(e.message));mobile.on("dialog",d=>d.accept());
    for(const family of families){await mobile.goto(route);await ready(mobile);await mobile.getByText("Cultures, civilizations and communities",{exact:true}).tap();await mobile.getByRole("button",{name:`Create ${labels[family].toLowerCase()}`,exact:true}).tap();const form=mobile.getByRole("dialog");await form.getByLabel("Name",{exact:true}).fill(`Phone ${family}`);if(family==="population"){await form.getByText("Places and migration",{exact:true}).tap();await form.getByRole("button",{name:"Add place association",exact:true}).tap();await form.getByLabel("Place association 1 place",{exact:true}).selectOption(fixture.places.region);await form.getByLabel("Place association 1 destination",{exact:true}).selectOption(fixture.places.townB);await form.getByLabel("Place association 1 relationship",{exact:true}).fill("migration");await form.getByText("Historical milestones",{exact:true}).tap();await form.getByRole("button",{name:"Author migration milestone",exact:true}).tap();await form.getByLabel("Milestone 1 account",{exact:true}).fill("An explicitly authored phone migration");await form.getByLabel("Milestone 1 date precision",{exact:true}).selectOption("approximate");await form.getByLabel("Milestone 1 year",{exact:true}).fill("850");}await noOverflow(mobile);await form.getByRole("button",{name:"Save record",exact:true}).tap();await form.waitFor({state:"hidden"});await visible(mobile.getByRole("heading",{name:`Phone ${family}`,exact:true}));const id=new URL(mobile.url()).searchParams.get("entity")!;await mobile.reload();await visible(mobile.getByRole("heading",{name:`Phone ${family}`,exact:true}));await mobile.getByRole("button",{name:"Edit record",exact:true}).tap();const editor=mobile.getByRole("dialog");await editor.getByLabel("Description",{exact:true}).fill(`Phone ${family} edited after reload`);await editor.getByRole("button",{name:"Save record",exact:true}).tap();await editor.waitFor({state:"hidden"});const persisted=await service.getPeople("world-god",fixture.worldId,fixture.primary,id);assert.equal(persisted.family,family);assert.equal(persisted.draft.description,`Phone ${family} edited after reload`);}
    await mobile.getByRole("button",{name:"Close record",exact:true}).tap();await mobile.getByLabel("Record family",{exact:true}).selectOption("tradition");const phoneReply=mobile.waitForResponse(r=>r.url().includes("q=Phone+tradition")&&r.request().method()==="GET");await mobile.getByLabel("Search peoples and origins",{exact:true}).fill("Phone tradition");await phoneReply;await mobile.waitForFunction(()=>document.querySelectorAll('[aria-label="Peoples and origins"] button[class*="card"]').length===1);await noOverflow(mobile);assert.ok(await mobile.evaluate(()=>navigator.maxTouchPoints>0));await mobile.getByLabel("Search peoples and origins",{exact:true}).evaluate(el=>window.scrollTo(0,el.closest("[data-field-guidance]")!.getBoundingClientRect().top+window.scrollY-115));await mobile.screenshot({path:`${artifactDirectory}/societies-phone.png`,fullPage:false});await phone.close();
    for(const [index,user]of ["other-god","world-player","world-admin"].entries()){const denied=await browser.newContext({extraHTTPHeaders:{"X-Forwarded-For":`198.51.100.${143+index}`}});await signIn(denied,baseUrl,user);const response=await denied.request.get(`${baseUrl}/api/worlds/${fixture.worldId}/peoples?timeline=${fixture.primary}&record=${fixture.civilization}`);assert.ok(response.status()>=400);assert.equal((await response.text()).includes("Gathered hearths"),false);const forbidden=await denied.newPage();await forbidden.goto(route);const privateHtml=await forbidden.content();assert.equal(privateHtml.includes("Gathered hearths"),false);assert.equal(privateHtml.includes("Ashborne interconnected societies"),false);assert.equal(await forbidden.getByRole("button",{name:"Create cultures",exact:true}).count(),0);if(user==="world-admin"){const review=await denied.request.get(`${baseUrl}/api/worlds/${fixture.worldId}/peoples?timeline=${fixture.primary}&record=${fixture.civilization}&review=1`);assert.equal(review.status(),200);const reviewed=await denied.newPage();await reviewed.goto(`${route}&entity=${fixture.civilization}&review=1`);await visible(reviewed.getByRole("heading",{name:"Gathered hearths",exact:true}));assert.equal(await reviewed.getByRole("button",{name:"Edit record",exact:true}).count(),0);}await denied.close();}
    const anonymous=await browser.newContext();const anonymousPage=await anonymous.newPage();await anonymousPage.goto(route);assert.equal((await anonymousPage.content()).includes("Gathered hearths"),false);assert.ok((await anonymous.request.get(`${baseUrl}/api/worlds/${fixture.worldId}/peoples?timeline=${fixture.primary}&place=${fixture.places.region}`)).status()>=400);await anonymous.close();assert.deepEqual(errors,[]);
    console.log("PASS: real production desktop and native-touch phone authoring/reload of all six society families, typed edits, saved participants/places, founding/migration milestones and corrections, History/entity/Atlas navigation, search/family/place filters, failed and unsaved drafts, real two-tab recovery, alternate development, protected server projection and unauthorized/Admin-review access; two screenshots retained.");
  }catch(error){await mkdir(artifactDirectory,{recursive:true});await page.screenshot({path:`${artifactDirectory}/browser-failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${artifactDirectory}/browser-failure.html`,await page.content()).catch(()=>{});throw error;}finally{await context.close();}
}

export async function societiesServiceChecks(worlds:Worlds,timelines:Timelines,pool:pg.Pool,foreignWorld:string,upgrade:Awaited<ReturnType<typeof seedSocietiesUpgrade>>,artifactDirectory="artifacts/guidance/worlds-4a-2"){
  const service=await import("../src/features/worlds/peoples-service"),atlas=await import("../src/features/worlds/atlas-service"),milestones=await import("../src/features/worlds/milestone-service");
  assert.equal(await service.changePeople(upgrade.owner,upgrade.worldId,upgrade.retry),upgrade.id,"An old create hash survives the additive geography default");
  const worldId=await worlds.createWorld("world-god",{name:"Ashborne interconnected societies"}),primary=(await worlds.getWorld("world-god",worldId)).selectedTimeline.id;
  const get=(id:string,timelineId=primary,ordinary=false)=>service.getPeople("world-god",worldId,timelineId,id,false,ordinary);
  const create=(family:LoreFamily,name:string,extra:Partial<LoreDraft>={},timelineId=primary)=>service.changePeople("world-god",worldId,{action:"create",timelineId,requestId:randomUUID(),draft:{...emptyLore(family),name,...extra}});
  const save=(r:LoreRecord,extra:Partial<LoreDraft>={},timelineId=primary)=>service.changePeople("world-god",worldId,{action:"save",timelineId,id:r.id,revision:r.revision,draft:{...r.draft,...extra}});
  const places:string[]=[];for(const [index,name]of ["Ember continent","Shared mountain range","Northern region","Coal harbor","Willow town","Secret ash hall"].entries()){
    const id=randomUUID();await atlas.changeAtlas("world-god",worldId,{action:"geography",draft:{id,revision:null,name,description:"Authored Atlas geography",kind:index===0?"continent":"location",context:index===0?"place":index===3||index===4?"settlement":index===5?"dungeon":"region",parentId:index===0?null:places[0]}});places.push(id);
  }
  const [continent,mountains,region,townA,townB,secretPlace]=places;void continent;
  // A real protected dungeon identity proves geography references cannot leak its name in ordinary projections.
  const site=randomUUID(),level=randomUUID();for(const [id,name,context]of [[site,"Protected-reference site","dungeon"],[level,"Protected-reference level","dungeon level"]])await atlas.changeAtlas("world-god",worldId,{action:"geography",draft:{id,revision:null,name,description:"",kind:"location",context,parentId:null}});
  await pool.query("insert into world_dungeon_site(geography_id,world_id) values($1,$2)",[site,worldId]);await pool.query("insert into world_dungeon_level(geography_id,world_id,site_id) values($1,$2,$3)",[level,worldId,site]);await pool.query("insert into world_dungeon_entity(id,world_id,level_id,geography_id,kind,name,visibility) values($1,$2,$3,$1,'landmark','Secret ash hall','secret')",[secretPlace,worldId,level]);
  const ash=await create("species","Ashborne",{description:"Living ash with contradictory origins.",time:known(100)}),light=await create("species","Luminous",{description:"Unrelated beings of light."});
  const origins:string[]=[];for(const [i,account]of ["Three divine ancestors created them.","An ancient machine created them.","Natural or supernatural evolution created them."].entries())origins.push(await create("origin",`Ashborne account ${i+1}`,{description:account,accuracy:"disputed",participants:[participant(ash,"subject"),...(i===0?["Glass Mother","Quiet Smith","Unborn Flame"]:[i===1?"Ancient machine":"Evolution"]).map(authoredReference=>({targetId:null,authoredReference,role:"claimed source",account:""}))]}));
  const peopleA=await create("people","Coast Ashborne",{participants:[participant(ash,"heritage")]}),peopleB=await create("people","Mountain Ashborne",{participants:[participant(ash,"heritage")]});
  const sharedCulture=await create("culture","Ember circles",{time:known(405),fields:{values:"Shared memory without shared biology",customs:"Silent meals and light dances",social:"Overlapping family circles",extraordinary:"Magic and machinery are both studied",arts:"Songs made of flame",knowledge:"Learning through collective remembrance",classification:"Creator-defined memory culture"},participants:[participant(peopleA,"shared by"),participant(light,"shared by"),participant(peopleB,"influences")],geographies:[geography(mountains,"cultural presence",known(450))],milestones:[event("emergence","Ember culture emerges",known(405))]});
  const secondCulture=await create("culture","Quiet embers",{fields:{values:"Privacy of memory",customs:"Solitary observance"},participants:[participant(peopleB,"shared by"),participant(peopleA,"overlaps with")]});
  const languageA=await create("language","Voices",{fields:{method:"Telepathic colors carried by light",dialects:"Mountain resonance and harbor echoes",origins:"Two conflicting claims",representation:"No required writing system"},participants:[participant(sharedCulture,"used by"),participant(secondCulture,"used by")]});
  const ancestralLanguage=await create("language","First signs",{fields:{method:"Original memory traces"}});
  const languageB=await create("language","Voices",{fields:{method:"Chemical signs and movement",development:"Its methods change while identity continues"},participants:[participant(languageA,"claimed ancestral language"),participant(ancestralLanguage,"competing ancestral language"),participant(sharedCulture,"used by"),participant(secondCulture,"used by")]});assert.notEqual(languageA,languageB);
  await save(await get(sharedCulture),{participants:[...(await get(sharedCulture)).draft.participants,participant(languageA,"uses language"),participant(languageB,"uses language")]});
  const beliefA=await create("belief","Three sparks",{fields:{claims:"The three ancestors are claimed creators",interpretations:"Several incompatible readings"},participants:[participant(origins[0],"concerns an attributed origin"),participant(sharedCulture,"believed by"),participant(secondCulture,"disputed by")]});
  const beliefB=await create("belief","The ancient engine",{fields:{claims:"A machine is believed to be responsible"},participants:[participant(origins[1],"derived from"),participant(sharedCulture,"believed by")]});
  const traditionA=await create("tradition","Light remembrance",{fields:{practice:"Patterns of light are performed together",transmission:"Taught between unrelated peoples"},participants:[participant(peopleA,"practiced by"),participant(light,"practiced by")]});
  const traditionB=await create("tradition","Ember silence",{fields:{practice:"A custom of silent shared meals"},participants:[participant(sharedCulture,"practiced by"),participant(secondCulture,"reinterpreted by")]});
  const civilization=await create("civilization","Gathered hearths",{time:known(600),fields:{foundations:"Contradictory foundation claims remain attributed",institutions:"Independent learning circles without a central government",economy:"Shared exchange and voluntary trade",knowledge:"Competing magical and technical traditions",achievements:"Living memory libraries",transformations:"Several possible future divisions"},participants:[peopleA,peopleB,sharedCulture,secondCulture,languageA,languageB,beliefA,beliefB,traditionA,traditionB].map(targetId=>participant(targetId,"includes")),geographies:[geography(region,"geographic presence",known(600)),geography(townA,"settlement presence",known(600))],milestones:[event("founding","Gathered hearths founded",known(600))]});
  const migrationTime:HistoricalTime={version:1,scale:"world-year",kind:"duration",startYear:800,endYear:850};
  const population=await create("population","Harbor Ashborne community",{time:known(650),fields:{identity:"An overlapping mixed community",estimates:"Unknown; no count has been invented",habitat:"Adapted to shared mountain and coastal life",demographics:"Several peoples and languages"},participants:[participant(peopleA,"includes"),participant(light,"includes"),participant(sharedCulture,"shares culture"),participant(civilization,"associated civilization"),participant(languageA,"uses language")],geographies:[geography(mountains,"shared habitat",known(650)),geography(townA,"settlement presence",known(650)),geography(townA,"migration",migrationTime,townB),{...geography(region,"secret gathering",undated),protected:true,account:"Protected migration account"},geography(townA,"hidden destination",undated,secretPlace)],milestones:[event("migration","Harbor community migration",migrationTime)]});
  const secondPopulation=await create("population","Mountain community",{participants:[participant(peopleB,"includes"),participant(secondCulture,"shares culture"),participant(civilization,"associated civilization"),participant(languageB,"uses language")],geographies:[geography(mountains),geography(region)]});
  const relationship=await create("relationship","Shared and disputed memory",{fields:{relationshipType:"Custom cultural exchange"},participants:[participant(sharedCulture,"influences"),participant(secondCulture,"disputes"),participant(civilization,"records competing accounts"),participant(beliefA,"interprets")]});assert.equal((await get(relationship)).participants.length,4);
  for(const family of families){const id=await create(family,`Minimal ${family}`);const r=await get(id);assert.equal(r.family,family);assert.equal(r.draft.time.kind,"undated");assert.ok(Object.values(r.draft.fields).every(v=>v===""));assert.equal(r.milestoneRecords.length,0);await service.changePeople("world-god",worldId,{action:"archive",timelineId:primary,id,revision:r.revision});const archived=await get(id);assert.equal(archived.archived,true);await service.changePeople("world-god",worldId,{action:"restore",timelineId:primary,id,revision:archived.revision});assert.equal((await get(id)).archived,false);assert.ok((await pool.query("select 1 from world_lore_version where id=$1",[r.versionId])).rowCount);}
  assert.equal((await pool.query("select count(*)::int n from world_campaign_context where world_id=$1",[worldId])).rows[0].n,0,"World authoring requires no Campaign");
  let civ=await get(civilization);const founding=civ.milestoneRecords[0].id;assert.deepEqual(civ.milestoneRecords[0].time,known(600));assert.equal((await milestones.milestoneLinks("world-god",worldId,primary,founding)).links[0].name,"Gathered hearths");
  await save(civ,{milestones:civ.draft.milestones.map(m=>({...m,draft:{...m.draft,time:known(605)}}))});civ=await get(civilization);assert.equal(civ.milestoneRecords[0].id,founding);assert.equal(civ.milestoneRecords[0].revision,2);await save(civ,{name:"Gathered hearths"});assert.equal((await get(civilization)).milestoneRecords[0].revision,2);
  const migration=(await get(population)).milestoneRecords[0].id;let migrationRecord=(await get(population)).milestoneRecords[0];for(const [targetId,kind]of [[civilization,"lore"],[peopleA,"lore"],[townB,"geography"]] as const){await milestones.linkMilestone("world-god",worldId,{timelineId:primary,entryId:migration,revision:migrationRecord.revision,targetId,kind,eventType:"affected by migration"});migrationRecord=(await get(population)).milestoneRecords[0];}assert.equal((await milestones.milestoneLinks("world-god",worldId,primary,migration)).links.length,4);
  const atMountains=await service.peoplesAtPlace("world-god",worldId,primary,mountains);assert.ok(atMountains.records.some(r=>r.id===population)&&atMountains.records.some(r=>r.id===secondPopulation));assert.equal((await service.peoplesAtPlace("world-god",worldId,primary,townB)).records.some(r=>r.id===population),true);
  let pop=await get(population);assert.equal(pop.geographies.length,5);const ordinary=await get(population,primary,true);assert.equal(ordinary.geographies.length,3);assert.equal(JSON.stringify(ordinary).includes("Protected migration account"),false);assert.equal(JSON.stringify(ordinary).includes("Secret ash hall"),false);assert.equal((await service.peoplesReferences("world-god",worldId,primary,false,true)).places.some(p=>p.id===secretPlace),false);await assert.rejects(service.peoplesAtPlace("world-god",worldId,primary,secretPlace,false,true),/unavailable/);
  const protectedBelief=await create("belief","Protected foundation belief",{visibility:"protected",privateNotes:"Protected belief notes"});await save(await get(secondCulture),{participants:[...(await get(secondCulture)).draft.participants,participant(protectedBelief,"secret interpretation")]});assert.equal(JSON.stringify(await get(secondCulture,primary,true)).includes(protectedBelief),false);
  const primaryBefore=JSON.stringify(await get(population));const branch=await timelines.changeTimeline("world-god",worldId,{action:"create",parentRevision:1,draft:{parentId:primary,name:"Alternate harbor history",description:"A different route",divergenceYear:700}});assert.equal((await get(population,branch)).mode,"pending","Later migration inside an earlier account needs review");assert.equal((await get(civilization,branch)).mode,"inherited");
  let alternate=await get(population,branch);await service.changePeople("world-god",worldId,{action:"resolve",timelineId:branch,id:population,revision:alternate.revision,decision:"include"});alternate=await get(population,branch);await save(alternate,{geographies:alternate.draft.geographies.map(g=>g.destinationId===townB?{...g,destinationId:region,account:"Alternate migration destination"}:g)},branch);assert.equal(JSON.stringify(await get(population)),primaryBefore);assert.equal((await get(population,branch)).geographies.some(g=>g.destinationId===region),true);
  const nested=await timelines.changeTimeline("world-god",worldId,{action:"create",parentRevision:1,draft:{parentId:branch,name:"Nested harbor history",description:"",divergenceYear:900}});assert.equal((await get(population,nested)).mode,"pending");
  const culture=await get(sharedCulture);const pinned=(await get(sharedCulture,branch)).versionId;await save(culture,{fields:{...culture.draft.fields,customs:"Primary changed after branch capture"}});assert.equal((await get(sharedCulture,branch)).versionId,pinned);const inherited=await get(sharedCulture,branch);await assert.rejects(service.changePeople("world-god",worldId,{action:"accept-parent",timelineId:branch,id:sharedCulture,revision:inherited.revision,parentVersionId:pinned,parentRevision:inherited.sourceRevision}),/newer version/);await service.changePeople("world-god",worldId,{action:"accept-parent",timelineId:branch,id:sharedCulture,revision:inherited.revision,parentVersionId:inherited.parentVersionId,parentRevision:inherited.parentRevision});
  const late=await create("language","New parent language",{time:known(100)});assert.equal((await service.listPeoples("world-god",worldId,branch)).records.some(r=>r.id===late),false);const parent=await get(late);await service.changePeople("world-god",worldId,{action:"adopt-source",timelineId:branch,id:late,revision:0,parentVersionId:parent.versionId,parentRevision:parent.revision});assert.equal((await get(late,branch)).id,late);
  const stale=await get(civilization);await save(stale,{description:"First accepted change"});await assert.rejects(save(stale,{description:"Stale rejected change"}),/newer version/);
  const town=(await atlas.getAtlas("world-god",worldId)).geographies.find(p=>p.id===townA)!;await atlas.changeAtlas("world-god",worldId,{action:"archive-geography",id:townA,revision:town.revision});pop=await get(population);assert.equal(pop.geographies.some(g=>g.geographyId===townA&&g.unavailable),true);await save(pop,{description:"Archived place references retained"});await assert.rejects(create("culture","Forged archived selection",{geographies:[geography(townA)]}),/Choose places/);
  const oldPopulation=(await get(population)).versionId;let restored=await get(population);await service.changePeople("world-god",worldId,{action:"archive",timelineId:primary,id:population,revision:restored.revision});restored=await get(population);await service.changePeople("world-god",worldId,{action:"restore",timelineId:primary,id:population,revision:restored.revision});assert.equal((await get(population)).geographies.length,5);assert.ok((await pool.query("select 1 from world_lore_version where id=$1",[oldPopulation])).rowCount);
  for(const user of ["other-god","world-player","world-admin"]){await assert.rejects(service.getPeople(user,worldId,primary,population));await assert.rejects(service.changePeople(user,worldId,{action:"create",timelineId:primary,requestId:randomUUID(),draft:{...emptyLore("culture"),name:"Unauthorized"}}));}assert.equal((await service.getPeople("world-admin",worldId,primary,population,true)).id,population);await assert.rejects(service.getPeople("world-player",worldId,primary,population,true));
  const foreignPlace=(await pool.query("select id from world_geography where world_id=$1 limit 1",[foreignWorld])).rows[0].id;await assert.rejects(create("population","Foreign location",{geographies:[geography(foreignPlace)]}),/Choose places/);await assert.rejects(create("belief","Forged participant",{participants:[participant(upgrade.id,"believed by")]}),/Choose available/);
  // Source guards apply to every new typed table and geographic child, including late inserts.
  for(const [family,entityId]of [["culture",sharedCulture],["civilization",civilization],["language",languageA],["population",population],["belief",beliefA],["tradition",traditionA]] as const){const r=await get(entityId);await assert.rejects(pool.query(`update world_${family}_version set description='Rewrite' where version_id=$1`,[r.versionId]),/immutable/);}
  await assert.rejects(pool.query("update world_lore_geography set account='Rewrite' where version_id=$1",[(await get(population)).versionId]),/immutable/);
  await assert.rejects(pool.query("insert into world_lore_geography(version_id,world_id,id,position,geography_id,relationship_type,historical_time) values($1,$2,$3,99,$4,'Late source',$5)",[(await get(population)).versionId,worldId,randomUUID(),region,undated]),/immutable/);
  const client=await pool.connect();try{await client.query("begin");const v=randomUUID(),source=(await get(sharedCulture)).versionId;await client.query("insert into world_lore_version select (jsonb_populate_record(null::world_lore_version,to_jsonb(v)||jsonb_build_object('id',$1::text))).* from world_lore_version v where id=$2",[v,source]);await client.query("insert into world_culture_version select (jsonb_populate_record(null::world_culture_version,to_jsonb(v)||jsonb_build_object('version_id',$1::text))).* from world_culture_version v where version_id=$2",[v,source]);await assert.rejects(client.query("insert into world_lore_geography(version_id,world_id,id,position,geography_id,relationship_type,historical_time) values($1,$2,$3,0,$4,'Forged FK',$5)",[v,worldId,randomUUID(),foreignPlace,undated]),/foreign key/);}finally{await client.query("rollback");client.release();}
  const denseWorld=await worlds.createWorld("world-god",{name:"Dense societies fixture"}),denseTimeline=(await worlds.getWorld("world-god",denseWorld)).selectedTimeline.id,densePlace=randomUUID();await atlas.changeAtlas("world-god",denseWorld,{action:"geography",draft:{id:densePlace,revision:null,name:"Shared dense region",kind:"location",context:"region",description:"",parentId:null}});
  const beganWrites=performance.now();const denseIds:string[]=[];for(let i=0;i<360;i++){const family=families[i%6];denseIds.push(await service.changePeople("world-god",denseWorld,{action:"create",timelineId:denseTimeline,requestId:randomUUID(),draft:{...emptyLore(family),name:`${family} ${i}`,description:"Large chosen domain narrative. ".repeat(200),geographies:[geography(densePlace)],participants:i?[participant(denseIds[i-1],"related original practice")]:[],milestones:i%7===0?[event("authored development",`Development ${i}`,known(i))]:[]}}));}const writeMs=Math.round(performance.now()-beganWrites);
  const began=performance.now();const list=await service.listPeoples("world-god",denseWorld,denseTimeline),listMs=Math.round(performance.now()-began);const detailStart=performance.now(),detail=await service.getPeople("world-god",denseWorld,denseTimeline,denseIds[105]),detailMs=Math.round(performance.now()-detailStart);const referenceStart=performance.now(),refs=await service.peoplesReferences("world-god",denseWorld,denseTimeline),referenceMs=Math.round(performance.now()-referenceStart);const placeStart=performance.now(),atPlace=await service.peoplesAtPlace("world-god",denseWorld,denseTimeline,densePlace),placeMs=Math.round(performance.now()-placeStart),readMs=Math.round(performance.now()-began);const nextPlacePage=await service.peoplesAtPlace("world-god",denseWorld,denseTimeline,densePlace,false,false,100);assert.equal(nextPlacePage.records.length,100);assert.ok(nextPlacePage.records.every(r=>!atPlace.records.some(first=>first.id===r.id)));assert.equal(list.records.length,100);assert.equal(refs.entities.length,360);assert.equal(atPlace.records.length,100);assert.equal(atPlace.hasMore,true);assert.equal(JSON.stringify(list).includes("Large chosen"),false);assert.equal(detail.geographies.length,1);assert.equal(detail.milestoneRecords.length,1);for(const family of families)assert.equal((await service.listPeoples("world-god",denseWorld,denseTimeline,false,false,"",0,family)).records.length,60);assert.equal((await service.listPeoples("world-god",denseWorld,denseTimeline,false,false,"language 356")).records.length,1);
  await mkdir(artifactDirectory,{recursive:true});await writeFile(`${artifactDirectory}/performance.json`,JSON.stringify({entities:360,families:6,milestones:52,geographicAssociations:360,relationships:359,writeMs,listMs,detailMs,referenceMs,placeMs,listDetailReferencesAndPlaceMs:readMs,listBytes:JSON.stringify(list).length,detailBytes:JSON.stringify(detail).length,referenceBytes:JSON.stringify(refs).length,placeBytes:JSON.stringify(atPlace).length},null,2)+"\n");
  console.log(`PASS: complete saved Ashborne societies, six typed families, shared cultures/languages/beliefs/traditions, overlapping communities and migration, canonical founding corrections/multi-entity events, preserved branch/nested sources, same-World geography/SQL guards, archived references and server redaction; 360-entity reads ${readMs}ms.`);
  return {worldId,primary,branch,nested,ash,peopleA,sharedCulture,secondCulture,languageA,languageB,civilization,population,beliefA,traditionA,founding,migration,places:{mountains,region,townA,townB,secretPlace}};
}
